### ISSUE TITLE
Fatal error: Call to a member function render() on null 

### ISSUE THREAD

**Issue by pascalmaddin** [timber/timber#1002]
Hi everybody,

I moved a WP-Installation to another computer (I am using MAMP) and when I call the page in the browser I get an fatal error instead of the page (page works fine on the other computer)

The error is: **Fatal error: Call to a member function render() on null in [path-to-site]/plugins/timber-library/lib/Loader.php on line 71**

I am using Plugin Version Version 1.0.3 (the error also came under the version 1.0.1) and the newest WordPress version 4.5.2. The PHP version is 5.6.10.

Anybody with an idea?

**Comment by connorjburton** [comment]
Could you please provide your theme and Timber plugin in an email? connorjburton@gmail.com

Initial guess is that Twig doesn't exist in your plugin.

Thanks

**Comment by pascalmaddin** [comment]
I was a problem with a weird apache configuration. Problem solved, thank you.
