### ISSUE TITLE
Q: Timber plugin version method

### ISSUE THREAD

**Issue by ogrosko** [timber/timber#1005]
You have made great job with version 1.0.*
Is there some method for getting timber version?

There are namespaces naming changed and I need to keep compatibility for older versions.
I would need something like:

`if (version_compare(\Timber::get_version(), '1.0.0', '<')) {
	# old namspace functionality
}
else {
	# new namspace functionality
}`

**Comment by connorjburton** [comment]
Hi,

Timber 1.0.X should be fully backwards compatible with old versions. Is there something specific that you are doing that isnt working?

**Comment by ogrosko** [comment]
Yes I am using small plugin for cache clearing https://github.com/ogrosko/clear-cache-for-timber/blob/master/clear-cache-for-timber.php

See line 40:    `echo TimberCommand::clear_cache();` results in error due to namespace changed in v 1.0

**Comment by connorjburton** [comment]
Aha, I must have missed `TimberCommand` when transitioning to namespacing. I will fix this in `1.0.3`. I will also introduce/investigate a version method/attribute so you can check the current version.
