### ISSUE TITLE
WP Conditional Tags within Timber

### ISSUE THREAD

**Issue by middle8media** [timber/timber#1006]
Is it possible to use WP conditionals tags within Timber?

http://codex.wordpress.org/Conditional_Tags#A_Single_Page.2C_a_Single_Post.2C_an_Attachment_or_Any_Other_Custom_Post_Type

**Comment by connorjburton** [comment]
You should be able to do something like `fn('is_singular')` - @jarednova may know a more elegant way if there is one.

**Comment by jarednova** [comment]
@middle8media the solution from @connorjburton should work, but this might beg a better syntax. Here's what's in my head:

```twig
{# whatever.twig #}
{% if view.is_singular %}
   <h1>I am a single page</h1>
{% else %}
   <h2>this is something else</h2>
{% endif %}
```

Any thoughts on how something like that would/wouldn't be helpful?

**Comment by connorjburton** [comment]
`view.is('singular')` for ultimate syntax sugar. Although away from WP conventions so probably not recommended :)
