### ISSUE TITLE
Changing default twig directory causes issues with Customizer

### ISSUE THREAD

**Issue by ypantig** [timber/timber#1013]
Hi,

I was playing around with Customizer and I found that the sections that I create for the Customizer gets hidden for some reason. Upon closer inspection (disabling plugins and commenting out some code), I was able to find that commenting out the line where I'm changing the default twig views directory to my own causes this. However, even if I have the `locations` setup as well, it's not pulling the twig files that I have from the directory that I set it to.

Here's how I'm changing the directories (I'm using namespaces hence the backslash):

```
public function after_setup_theme__setTimberDir()
  {
    // set where to find timber includes
    \Timber::$dirname = array( '/src/views/' );
    \Timber::$locations = array( '/src/views/' );
  }
```

with this action in the construct:
`add_action( 'after_setup_theme', array( &$this, 'after_setup_theme__setTimberDir' ) );`

Any ideas?

Thanks!

**Comment by mrgrain** [comment]
Hey @ypantig We are using the customizer here successfully. Could you provide us with your code to create the customizer sections? I'll try to replicate.

**Comment by ypantig** [comment]
Yes of course. Here's the code the I have on my customizer class:

`<?php

namespace YP\Theme;

class Customizer
{

  public function __construct()
  {

    add_action( 'customize_register', array( &$this, 'customize_register__addSettings' ) );
    // add_action( 'customize_register', array( &$this, 'customize_register__addSections' ) );
    // add_action( 'customize_register', array( &$this, 'customize_register__addControls' ) );

  }


  /**
   * add settings for the customizer
   *
   * @author Ynah Pantig
   * @package
   * @since 1.0
   * @param $wp_customize
   * @return
   */

  public function customize_register__addSettings( $wp_customize )
  {

    $wp_customize->add_section( 'new_section' , array(
            'title'    => __( 'Section Name', 'theme' ),
            'priority' => 100
        ) );

    $wp_customize->add_setting( 'new_setting' , array(
        'type' => 'theme_mod', // or 'option'
        'capability' => 'edit_theme_options',
        // 'theme_supports' => '', // Rarely needed.
        'default' => '',
        // 'transport' => 'refresh', // or postMessage
    ) );

    $wp_customize->add_control( new \WP_Customize_Color_Control( $wp_customize, 'header_colour', array(
        'label'    => __( 'Header Color', 'theme' ),
        'section'  => 'new_section',
        'settings' => 'new_setting',
    ) ) );

  }/* customize_register__addSettings() */


  /**
   * add sections to the customizer
   *
   * @author Ynah Pantig
   * @package
   * @since 1.0
   * @param $wp_customize
   * @return
   */

  public function customize_register__addSections( $wp_customize )
  {
    // error_log( 'add sections' );

  }/* customize_register__addSections() */

  /**
   * add sections to the customizer
   *
   * @author Ynah Pantig
   * @package
   * @since 1.0
   * @param $wp_customize
   * @return
   */

  public function customize_register__addControls( $wp_customize )
  {

  }/* customize_register__addSections() */

} /* class Customizer() */
`

**Comment by mrgrain** [comment]
Hmm thanks for that. Just letting you now I'm still trying to reproduce the issue. =/

**Comment by ypantig** [comment]
Sorry, I just saw your comment. That's weird. I'll test that one out again and let you know as soon as I can.

**Comment by palmiak** [comment]
Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
