### ISSUE TITLE
TimberImage resize working locally but not on amazon server

### ISSUE THREAD

**Issue by kmturley** [timber/timber#1017]
### Expected behavior
I was expecting TimberImage to resize images on my amazon ec2 server as it does on my local machine

### Actual behavior
It is outputting the original image, for example:

    <img src="{{ post.thumbnail.src|resize(640, 360) }}" alt="" />

When outputted locally the result is:

    http://localhost:8888/new/wp-content/uploads/2016/05/abc-640x360-c-default.jpg

When running the same code on amazon ec2 the result is:

    http://mysite.com/new/wp-content/uploads/2016/05/abc.jpg

### Steps to reproduce behavior
Normal resize image code, on an amazon ec2 instance. I've tried enabling errors to ensure it wasn't erroring:

    define('WP_DEBUG', true);
    define('WP_DEBUG_LOG', true);
    define('WP_DEBUG_DISPLAY', true);

and also in my php.ini, but nothing errors out:

    display_errors = on

### What version of WordPress, PHP and Timber are you using?
Local: WordPress 4.4.2, Timber 1.0.3, PHP 5.5.29
Server: WordPress 4.4.2, Timber 1.0.3, PHP 5.3.29

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
via Wordpress plugin manager

Guides used to install wordpress:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/install-LAMP.html
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/hosting-wordpress.html

**Comment by kmturley** [comment]
I added some code to TimberImage.php to add a param to the image url depending on where it is served:

    if ( file_exists($new_server_path) ) {
        if ( $force ) {
            // Force operation - warning: will regenerate the image on every pageload, use for testing purposes only!
            unlink($new_server_path.'?force');
        } else {
            // return existing file (caching)
            return $new_url.'?cache';
        }
    }
    // otherwise generate result file
    if ( $op->run($old_server_path, $new_server_path) ) {
        if ( get_class($op) === 'TimberImageOperationResize' && $external ) {
            $new_url = strtolower($new_url);
        }
        return $new_url.'?success';
    } else {
        // in case of error, we return source file itself
        return $src.'?error';
    }

And the result I am getting is:

    http://mysite.com/new/wp-content/uploads/2016/04/Photo-Mar-10-11-49-23-PM.jpg?error

**Comment by kmturley** [comment]
I added the following debugging code to Resize.php 

    if ( !is_wp_error($image) ) {
        $crop = self::get_target_sizes($load_filename);
        $image->crop($crop['x'],
                        $crop['y'],
                        $crop['src_w'],
                        $crop['src_h'],
                        $crop['target_w'],
                        $crop['target_h']
        );
        $result = $image->save($save_filename);
        if ( is_wp_error($result) ) {
            // @codeCoverageIgnoreStart
            Helper::error_log('Error resizing image');
            Helper::error_log($result);
            print_r('is_wp_error $result');
            print_r($result);
            die();
            return false;
            // @codeCoverageIgnoreEnd
        } else {
            print_r('!is_wp_error $result');
            print_r($result);
            die();
            return true;
        }
    } else if ( isset($image->error_data['error_loading_image']) ) {
        print_r('error_data');
        print_r($image->error_data['error_loading_image']);
        die();
        // @codeCoverageIgnoreStart
        Helper::error_log('error loading '.$image->error_data['error_loading_image']);
    } else {
        print_r('is_wp_error $image');
        print_r($image);
        die();
        Helper::error_log($image);
        // @codeCoverageIgnoreEnd
    }

The debugging message I got then was:

    is_wp_error $image
    WP_Error Object(
        [errors] => Array([image_no_editor] => Array([0] => No editor could be selected.))
        [error_data] => Array()
    )

So I fixed the issue by installing a graphic library, using the command:

    sudo yum install php-gd

Maybe Timber should output a message somewhere if graphics library isn't installed?

**Comment by connorjburton** [comment]
Ah, okay thanks for this, I was just modifying those methods the other day, we do do a check for Imagick but not `php-gd`

I will re-open and assign to 1.0.4 to add an error when php-gd isn't found

Thanks for investigating!

**Comment by jarednova** [comment]
Yeah thanks for posting the solution @kmturley!

**Comment by kmturley** [comment]
no problem!

**Comment by connorjburton** [comment]
Hi @kmturley - could you double check that nothing was showing in your wp-content/debug.log? Or your php errors log. Something should have been in there regarding this, all I can really do is to change the error message.

**Comment by kmturley** [comment]
This is the error message from wp-content/debug.log looks ok:

    [22-May-2016 23:32:25 UTC] PHP Fatal error:  Class 'Timber\Cache\KeyGenerator' not found in /var/www/html/milou/new/wp-content/plugins/timber-library/lib/Loader.php on line 328
    [22-May-2016 23:33:22 UTC] WP_Error Object (   
        [errors] => Array
            (   
                [image_no_editor] => Array
                    (   
                        [0] => No editor could be selected.
                    )

            )

        [error_data] => Array
            (
            )
    )

Would be good to have something in the documentation to point users to wp-content/debug.log if they are experiencing issues with Timber? that all errors are logged there?

Also something in the documentation noting the dependancies required e.g. php-gd library, and the behaviour of Timber Image if the editor does not exist, that it falls back to the original image?

**Comment by connorjburton** [comment]
Okay sure, I have added a better error message for this now. Any documentation changes I would highly appreciate you adding to this issue https://github.com/timber/timber/issues/1035 👍 

Thanks!
