### ISSUE TITLE
GIF Image Resize

### ISSUE THREAD

**Issue by horch004** [timber/timber#1019]
### Expected behavior
A resized static GIF image with transparent background

### Actual behavior
A resized static GIF image with a black background

### Steps to reproduce behavior
`<img src="{{ post.thumbnail.src|resize(80) }}" />` where the thumbnail is a static GIF image with a transparent background.

### What version of WordPress, PHP and Timber are you using?
Latest WP, PHP 7 and latest Timber as plugin.

## Possible solution
When I change the Twig Image resize function (Timber\Image\Operation\Resize::run) to resize all .gif images using the run_animated_gif method, the 'old' static gif image is resized and keeps the transparent background.

## Code change
if ( \Timber\ImageHelper::is_animated_gif($load_filename) ) { ....
To
if ( strpos(strtolower($load_filename), '.gif') > -1 || \Timber\ImageHelper::is_animated_gif($load_filename) ) { ...

**Comment by jarednova** [comment]
@lggorman — can you take a look at this one?

**Comment by lggorman** [comment]
@horch004 Any chance you could check which php image manipulation library you're using by default (ImageMagick vs GD)? I was only able to replicate this bug by switching my default to the GD library, and a [this ticket] (https://core.trac.wordpress.org/ticket/13461) seems to be addressing the same sort of problem with GD.  Though that wouldn't explain why `run_animated_gif` seemed to do the trick, since that explicitly uses Imagick.

**Comment by horch004** [comment]
@lggorman ImageMagick and GD are both installed. With a phpinfo plugin I see them both configured. When I search Google about Wordpress using ImageMagick instead of GD it seems Wordpress uses GD by default(?).

**Comment by lggorman** [comment]
@horch004 Definitely seems that was the case before 3.5 now, though I think it should look for Imagick first [in the latest](https://make.wordpress.org/core/2012/12/06/wp_image_editor-is-incoming/).  If it's not the default you should be able to set it in `functions.php` with something along these lines:
```
add_filter('wp_image_editors', function($editors){
	$editors = array_diff( $editors, array( 'WP_Image_Editor_Imagick' ) );
	array_unshift( $editors, 'WP_Image_Editor_Imagick'  );
	return $editors;
});
```
That said, it might still be worthwhile for us to make a code edit to make sure Imagick is being used for image resizing.

**Comment by horch004** [comment]
@lggorman Thanks for looking into the issue. I solved the issue by installing an WP Imagick plugin and regenerating all thumbnails.

**Comment by connorjburton** [comment]
I have added better errors in #1030
