### ISSUE TITLE
Plugin updates bug

### ISSUE THREAD

**Issue by Matt-Yorkley** [timber/timber#1020]
Hi there, I've recently been having issues on a couple of Wordpress installations and have narrowed down the culprit to the Timber plugin.

The issue is that updating any plugins leads to the update hanging part way through. The plugins update successfully, but the UI doesn't finish and often leaves the annoying ".maintenance" file in the root (which temporarily puts the site into maintenance mode whilst updating, but normally gets deleted when the update is finished. This effectively breaks the site until the file is manually deleted from the server.) 

I'm not getting any useful errors in any logs, but I've discovered when I deactivate the Timber plugin everything returns to normal.

I'm using Timber 1.03 with Gantry 5.2.17, but I had this cropping up with earlier versions too. Wordpress 4.5.2.

**Comment by Matt-Yorkley** [comment]
Update; there's a notice produced using Wordpress Debug Bar:

"NOTICE: wp-content/plugins/timber-library/lib/Admin.php:49 - Trying to get property of non-object
WP_List_Table->display, WP_List_Table->display_rows_or_placeholder, WP_Plugins_List_Table->display_rows, WP_Plugins_List_Table->single_row, do_action('after_plugin_row_timber-library/timber.php'), call_user_func_array, wp_plugin_update_row, do_action('in_plugin_update_message-timber-library/timber.php'), call_user_func_array, Timber\Admin::in_plugin_update_message"

**Comment by Matt-Yorkley** [comment]
Actually 2 notices, the second references line 61 as well:

"NOTICE: wp-content/plugins/timber-library/lib/Admin.php:61 - Trying to get property of non-object
WP_List_Table->display, WP_List_Table->display_rows_or_placeholder, WP_Plugins_List_Table->display_rows, WP_Plugins_List_Table->single_row, do_action('after_plugin_row_timber-library/timber.php'), call_user_func_array, wp_plugin_update_row, do_action('in_plugin_update_message-timber-library/timber.php'), call_user_func_array, Timber\Admin::in_plugin_update_message"

These appear only after clicking "update" on a plugin on the Wordpress plugins admin page.

**Comment by palmiak** [comment]
Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
