### ISSUE TITLE
After downloading from wp.org - activating plugin: Fatal error: Class 'Timber\Timber' in /wp-content/plugins/timber-library/init.php on line 5

### ISSUE THREAD

**Issue by bjornbjorn** [timber/timber#1022]
### Expected behavior

1. Downloading Timber from http://downloads.wordpress.org/plugin/timber-library.zip I expect to get the latest release
2. When clicking the "Activate" link for Timber in WP admin I expect the plugin to be activated.

### Actual behavior

A PHP error is thrown:

```
Fatal error: Class 'Timber\Timber' in /wp-content/plugins/timber-library/init.php on line 5
```

It seems the version you get when you download "timber-library.zip" to get the latest version from downloads.wordpress.org does not work.

### Steps to reproduce behavior

1. wget http://downloads.wordpress.org/plugin/timber-library.zip
2. unzip and see Timber listed in admin as 1.0.3
3. Try to activate and get error

### Steps to fix

1. wget https://downloads.wordpress.org/plugin/timber-library.1.0.3.zip
2. unzip and see Timber listed in admin as 1.0.3
3. Activation works

If I list the directory I can see the zips downloaded are not identical (although both plugins identify as version 1.0.3 in WP admin)

````
-rw-r--r--   1 bjorn  staff   729K May 14 19:12 timber-library.1.0.3.zip
-rw-r--r--   1 bjorn  staff   787K May 14 19:11 timber-library.zip
````

### What version of WordPress, PHP and Timber are you using?

Timber 1.0.3
WordPress 4.5.2
PHP 5.6.20

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

wget http://downloads.wordpress.org/plugin/timber-library.zip

**Comment by connorjburton** [comment]
One for you @jarednova ?

**Comment by jarednova** [comment]
Yeah I'll take a deep-dive

**Comment by bjornbjorn** [comment]
Hi, just some additional info .. when pushing this site to the staging server just now I got the same "Class not found Timber\Timber in init.php" error.

I fixed it by adding this to the top in init.php:

```
if ( ! class_exists( 'Timber' ) ) {
    require_once( 'lib/timber.php' );
}
```

Not sure if this is related to the original issue as I got that error also on my local install but thought I'd add some more context. Might it have something to do with my directory structure? I have WP installed in /vendor/wordpress while the plugins are located in /webroot/wp-content/plugins

**Comment by jarednova** [comment]
@bjornbjorn: thanks so much for this info. I was able to recreate the problem and encounter your issue.

It looks like there was an SVN problem with files that were checked into trunk (but for some reason not downloading). I nuked everything and started fresh. After everything was (re)checked into SVN; I ran through the steps and it works!

**Comment by bjornbjorn** [comment]
Did a fresh install of latest WP/timber-library.zip and can confirm it works now. Thanks a lot for the fix! :-)
