### ISSUE TITLE
Function to call WP Login Form.

### ISSUE THREAD

**Issue by middle8media** [timber/timber#1023]
Is there a function to call `wp_login_form( $args );`?

Something along the lines of `{{ function('get_search_form') }}`

**Comment by connorjburton** [comment]
There isn't anything built in IIRC but you can do `{{ function('wp_login_form', {object: args}) }}`

**Comment by wesm87** [comment]
You could also use [`TimberHelper::function_wrapper()`](https://github.com/timber/timber/wiki/WP-Integration#functions) to create a custom Twig function to handle this for you.

**Comment by littlbr** [comment]
I'm trying to use TimberHelper::function_wrapper() to build a custom login form and I'm failing.

when calling {{ login_form }} in my view, the form is built, but the arguments are ignored. Any idea?

`$login_args = array(
	'echo'           => true,
	'redirect'       => home_url( '/wp-admin/' ), 
	'form_id'        => 'loginform',
	'label_username' => __( 'Username' ),
	'label_password' => __( 'Password' ),
	'label_remember' => __( 'Remember Me' ),
	'label_log_in'   => __( 'Log In' ),
	'id_username'    => 'user_login',
	'id_password'    => 'user_pass',
	'id_remember'    => 'rememberme',
	'id_submit'      => 'wp-submit',
	'remember'       => true,
	'value_username' => NULL,
	'value_remember' => true
);

$context['login_form'] = TimberHelper::function_wrapper( 'wp_login_form', $login_args ) );`
