### ISSUE TITLE
Please Update Your Docs

### ISSUE THREAD

**Issue by jlundwebservices** [timber/timber#1031]
I am using your plugin because all I needed was simple routing to static page templates. I have since found that your plugin is more than capable of doing this. However, I spun my metaphorical wheels for 4 hours because your documents are incorrect. You do not mention, nor reference, the depreciation of the Timber::load_template() function. Nor do you reference that this function, and even more robust routing, is available via a Routes class that you bring in as a dependency.

Please review, revise and update your documentation so someone else doesn't go down this path.

I am pleased with the functionality otherwise. Thank you for your work.

**Comment by connorjburton** [comment]
Jared has sorted the routes one now, however it is on my list to manage the docs update better. We are pushing out lots of updates but documentation is slipping.

It's on the radar.
