### ISSUE TITLE
Q: Can I wrap my loop around multiple blocks?

### ISSUE THREAD

**Issue by swthate** [timber/timber#1033]
I have a view I'm working on which has `header` and `content` blocks that extend `base.twig`. The header block has some content in it that changes depending on the view. Some pages have big hero elements, some just a simple text header. The hero elements have a number of ACF fields. The content block is for everything else.

Can I wrap `{% for post in posts %}` around both my header and content blocks? When I try it I just get a white screen. But if I put the loop inside my header block, then my hero element shows up fine.

If I can only do the loop inside blocks, do I simply repeat the loop in each block? That seems fishy to me for some reason. I figure having the whole page in the loop would make more sense.

Am I going about or thinking about this the wrong way?

Thanks!

**Comment by luukdv** [comment]
When using `Timber::render('filename.twig', $context)`, you can use your context variables anywhere in the twig file. Maybe you can post some code snippets that can clarify your use case a bit?
