### ISSUE TITLE
How to debug whitescreen of death?

### ISSUE THREAD

**Issue by minthemiddle** [timber/timber#1034]
One of my templates stopped working from one second to the other and instead I get a blank site, sometimes a 500 error. There is nothing that would give me a hint about what goes wrong - debug bar and it's Timber extension don't work either because nothing gets loaded.

How can I debug such a situation?

**Comment by connorjburton** [comment]
Have you got WP_DEBUG turned on? And have you checked apache/error logs (for the 500 error)?

**Comment by minthemiddle** [comment]
Thanks for the advice. It was more of a general question. Because luckily I have an up-to-date multi dev env and could just pull in the staging database to get back to work. I have no clue what caused the error, but I will note that 500 should be in `WP_DEBUG` log.
