### ISSUE TITLE
Document documentation gaps

### ISSUE THREAD

**Issue by jarednova** [timber/timber#1035]
As reported in #1031 — the docs are out of sync between the code, wiki, [generated docs](http://timber.github.io/timber/), [website](http://upstatement.com/timber). Let's get these back together

For this ticket, we want to **document** the gaps. Once documented we can better determine what should be updated? how? and whether certain docs should be sunsetted.

On this ticket, please go through each source and itemize different components of each documentation source along with some sort of indication on what the state is (ie: "Totally great!" "a little off" "hopelessly bunk") — with this we can figure out what the best next steps are

**Comment by connorjburton** [comment]
I think we should change the WIKI to just redirect/provide links to the github pages docs. It's really confusing having 2 different set of documentation.

**Comment by lggorman** [comment]
I’d tend to agree.  There are a number of places where the wiki’s gotten ahead of the docs or vice versa, and it’d be simpler to maintain a single source of truth.  A few source specific notes:

- Wiki:
    - The getting started guides and video tutorial both reference cloning the repo into the plugins dir,     instead of installing directly in the theme via composer. 
    - In general the object reference pages don’t include everything that’s represented in the generated docs.
- Generated docs: 
    - Same note as above re: the getting started guide
    - There are some edits to the wiki that haven’t been propagated to these docs, eg. the changes regarding routing.  
    - There are also a few pages from the wiki that haven’t been added to the generated docs yet, the cheatsheet, Image cookbook etc.
- Readme.txt and Readme.md — These look good, but I’d note that they link to guides in the wiki, and I’m thinking we’ll ultimately want them to link to the generated docs instead

**Comment by lggorman** [comment]
Also -- I think that the generated docs would be easier to use with a few styling edits (ex. making the h4's bigger, adding more spacing around the code blocks).  A few examples of some really pretty slate docs:
- http://mozilla.github.io/localForage/
- https://clearbit.com/docs
- https://developers.coinbase.com/api/v2

**Comment by kmturley** [comment]
Some other documentation items which could've saved me time:

- when experiencing issues with Timber point users to the logging in wp-content/debug.log
- explain the dependancies required to use TimberImage e.g. php-gd library
- explain the behaviour of TimberImage falling back to the original image if the editor library does not exist

**Comment by palmiak** [comment]
@jarednova is this still on? Or should we close this?

**Comment by gchtr** [comment]
I added @kmturley’s points to the [Documentation Project](https://github.com/timber/timber/projects/3), so they can eventually be documented as well. I think it’s better to have documentation gaps listed there, in a central hub, rather than somewhere in issues.

From my side, this can be closed.

**Comment by palmiak** [comment]
Thanks @gchtr - I'm closing it.
