### ISSUE TITLE
MATERIAL DESIGN LITE - Uncaught TypeError

### ISSUE THREAD

**Issue by chieh301** [timber/timber#1039]
I install  timber  and  use material design lite as framework.
When add class ''mdl-js-layout " to div. 
throw error  "Uncaught TypeError: Cannot read property 'addEventListener' "
I know this is because mdl executes before the DOM fully loads, But I don't know how to fix it.
can anyone help?
Thanks~

**Comment by connorjburton** [comment]
Timber shouldn't effect this at all, it loads a page as every other web page loads a page. Looks like the JS is trying to attach an event to an element that doesn't exist.

I would try MDL on another theme without Timber and see if you get the same error.

**Comment by chieh301** [comment]
When i use xxx.php  MDL works fine.but if xxx.twig get error.....

**Comment by palmiak** [comment]
Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
