### ISSUE TITLE
Image resizing uppercase file extensions

### ISSUE THREAD

**Issue by commercial-hippie** [timber/timber#1043]
When resizing files that have uppercase extensions I'm running into an issue.

``` twig
// Original file: post.thumbnail = foo.JPG
{{ post.thumbnail | resize(400, 500) }}
// Resized file: foo-400x500-c-default.jpg
// Resized link: foo-400x500-c-default.JPG
```
As you can see above, the final link goes to the wrong image and turns into a 404.

#### Steps to reproduce behavior

Import a image with a uppercase extension.  You can't just upload a image because Wordpress converts it to a lowercase extension.  (I imported all my posts, images from a ExpressionEngine install).

WordPress 4.5.22, PHP 7.0.4, Timber 1.0.3

**Comment by commercial-hippie** [comment]
Such a quick update! Thanks for looking into it so quickly, really appreciate is! Great plugin :smile:

**Comment by jarednova** [comment]
Thanks @commercial-hippie! @connorjburton submitted a PR that I just merged. Look for a release to WP.org early next week!
