### ISSUE TITLE
Q: get_terms mysteriously returns absolutely nothing

### ISSUE THREAD

**Issue by swthate** [timber/timber#1046]
### Expected behavior
Return taxonomy data so I can do something like `{{department.name}}`.

### Actual behavior
Nothing gets returned. Nothing can be dumped.
It certainly appears, to me, like I've done everything I need to do. I can confirm that in the admin area the taxonomy is there and is being used by my team post type.

### Steps to reproduce behavior
Here's a gist with my archive PHP and Twig files, as well as the relevant snippet of my functions file: https://gist.github.com/swthate/90330c173f80d547f0eca986bf5c89d8

### What version of WordPress, PHP and Timber are you using?
Example: WordPress 4.5.2, PHP 5.6.10, Timber 1.0.3

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Wordpress dashboard

**Comment by connorjburton** [comment]
Would http://timber.github.io/timber/#terms work?

**Comment by swthate** [comment]
I did come across that, but to be completely honest, it doesn't make much sense to me 😕 

That's for usage in a .twig tempalte file, right? Would its usage look like this?

```
{{ terms( 'department', true ) }}
    {% for term in terms %}
        {{ term.name }}
    {% endfor %}
```

I'm guessing not, since when I do that it complains a lot:

```
Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'Unknown "terms" function in "archive-team.twig" at line 18.' in /Users/steven/Sites/branch/schmidt-timber/www/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/ExpressionParser.php:573 Stack trace: #0 /Users/steven/Sites/branch/schmidt-timber/www/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/ExpressionParser.php(351): Twig_ExpressionParser->getFunctionNodeClass('terms', 18) #1 /Users/steven/Sites/branch/schmidt-timber/www/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/ExpressionParser.php(144): Twig_ExpressionParser->getFunctionNode('terms', 18) #2 /Users/steven/Sites/branch/schmidt-timber/www/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/ExpressionParser.php(84): Twig_ExpressionParser->parsePrimaryExpression() #3 /Users/steven/Sites/branch/schmidt-timber/www/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/ExpressionParser.php(41): Twig_ExpressionParser->getPrimary() #4 /Users/steven/Sites/branc in /Users/steven/Sites/branch/schmidt-timber/www/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/ExpressionParser.php on line 573
```

I am loving Timber a lot, but obviously am still having a hard time wrapping my head around some key concepts. Thanks for all the help you guys have been. Hope I'm not much of a bother! What's the best way to donate to the project? I'd love to pitch in some way outside the code! :)

**Comment by connorjburton** [comment]
I don't really use terms to be honest, see what this returns:

`{{ dump(department.terms()) }}`

Reporting bugs/issues and promoting Timber is good enough donation for us 👍

**Comment by swthate** [comment]
Still nothing :(

Well, I wonder, if this is even the right scenario to be using a taxonomy. It might be, but I wonder if there's a different way to go about this. Maybe I can get your opinion on this, which would be interesting since you said you don't use taxonomies (terms and taxonomies are interchangeable? or are you refering to something else) all that often.

So if you take a look here http://branchind.com/proofs/schmidtmankato/team/ you'll see it's basically an archive with all the custom team member posts. These posts are separated according to which department taxonomy they belong to. This also allows me to show the related department members on various product pages, like this: http://branchind.com/proofs/schmidtmankato/product/helmet-heat/. If you scroll to the bottom you'll see that each product post will have a small loop showing the foremen (department members) for that product.

**Comment by connorjburton** [comment]
Ah, taxonomy is correct here.

Try ` {{ dump(post.terms('department')) }}`

**Comment by swthate** [comment]
Had to switch over to my pc, everything web related is on my mac... I'll try that out later today and get back to you.

**Comment by swthate** [comment]
```
{% for post in posts %}

    <pre>{{ dump( post.terms( 'department' ) ) }}</pre>

{% endfor %}
```

Returns the following: https://gist.github.com/swthate/bcf0db82741fa434a349143eb4954d59

**Comment by swthate** [comment]
Little bit of an update:

```php
    {% for term in post.terms('department') %}
        <h5>{{ term.name }}</h5>
    {% endfor %}
```

This successfully returns stuff. However, it very oddly returns the following:

Roofing Foremen
Gutter Foremen
Window Foremen
Window Foremen
Window Foremen
Window Foremen
Siding Foremen
Siding Foremen
Siding Foremen
Siding Foremen

I expected it to loop through each term and return this:

Door Foremen
Gutter Foremen
Leadership
Roofing Foremen
Siding Foremen
The Sales Team
Window Foremen

I don't see any logic to why it would output what it does (first list). It doesn't match the number of taxonomy terms or items, or the number of team posts using the taxonomy...

**Comment by connorjburton** [comment]
Hmm, yes not sure to be honest without jumping into the code myself. My guilty pleasure is using ACF for a lot of relationships like this...

If you think `.terms` isn't returning what it should be and you can put a detailed comment together about what you expect vs what it's returning I'll have a look at fixing it.

Cheers

**Comment by swthate** [comment]
Thanks @connorjburton 

I think what I'll do is try to get an ACF alternative working (it does just feel weird to have most of the site powered by ACF except this one tiny area) and maybe submit a more detailed comment about what's going on with the taxonomy. If I can get ACF to work for me, though, that detailed comment would be on the back burner for a rainy day, if you ever got reeeal bored :)

Thanks again!

**Comment by swthate** [comment]
Okay, I apologize.

I never even thought to add some arguments to my get posts context. Change posts_per_page, change the other, and there they all are! 😵 

I do think I will come up with an ACF solution still though.
