### ISSUE TITLE
Proposal: Instantiate custom classes through config

### ISSUE THREAD

**Issue by davidmaneuver** [timber/timber#1053]
I'm having a bit of trouble using the custom post classes as described [here](http://timber.github.io/timber/#extending-objects).

The problem is that upon doing `Timber::get_post()` or `Timber::get_posts()` the post type is not always clear yet. I have now implemented a workaround that'll do the trick.

My proposal is to tell Timber about the custom classes in advance. So whenever you retrieve posts through Timber you get the correct class instance.

```
Timber::config([
  'post_classes' => [
    'post' => 'MyCustomPost',
    'page' => 'MyCustomPage'
  ]
]);
```

Any thoughts on this?

**Comment by connorjburton** [comment]
Yes this something that @jarednova has mentioned a couple of times to me. Will work on this soon, but it will probably come with a host of other changes to how Timber itself is initialised. So we may be looking at `1.1.0`

**Comment by davidmaneuver** [comment]
Cool. Thanks. Looking forward to it.

Let me know if I can help in any way.

**Comment by jarednova** [comment]
I'm closing out old issues. Please open a fresh issue if this is still a live issue that we should investigate — thank you!

BTW this in particular of what we're doing with Factories in 2.x — stay tuned!
