### ISSUE TITLE
Error with TIMBER_LOADED constant being defined twice

### ISSUE THREAD

**Issue by steinbergh** [timber/timber#1054]
### Actual behavior

I have been seeing this error immediately after updating Timber through composer ```Notice: Constant TIMBER_LOADED already defined in path/to/theme/vendor/timber/timber/lib/Timber.php on line 56```

which is then fixed by commenting out ```define('TIMBER_LOADED', true);``` on line 102 of Timber.php

### What version of WordPress, PHP and Timber are you using?

timber version: 1.0.3 
wordpress version: 4.5.2
php version: 5.6.18

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

installed newest version of timber via composer.

**Comment by connorjburton** [comment]
This seems an odd error, could you please post a gist of your `Timber.php` file? All `define`s should be wrapper in `if(defined())`

**Comment by jarednova** [comment]
@connorjburton @steinbergh I think this is fixed in d4555ce9f912e8a0025c270a31d43eda0539f8bc. @steinbergh: can you confirm by updating to 1.0.4 or syncing with this commit?

**Comment by steinbergh** [comment]
@connorjburtonI can confirm this is fixed, thank you so much for your responsiveness!
