### ISSUE TITLE
WP_CONTENT_SUBDIR is wrong (causing `get_rel_path` to return an URL)

### ISSUE THREAD

**Issue by haroldangenent** [timber/timber#1056]
### Expected behavior

`WP_CONTENT_SUBDIR` should be `/app`.
### Actual behavior

`WP_CONTENT_SUBDIR` was defined as an URL: `http://www.example.com/app` on subdirectory installs (Multisite).
### Steps to reproduce behavior
1. Place `wp-content/` contents in another folder (for example, when [Giving WordPress Its Own Directory](https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory))
2. Create a subdirectory website
3. Check `WP_CONTENT_SUBDIR`, defined in `TimberImageHelper::add_constants` (Timber 0.22.5) for the subdirectory install

In my case, this causes `TimberImageHelpers::sideload_image` to return an URL instead of a path, **prefixed with a slash** (because of `TimberURLHelpers::preslashit()`).
### What version of WordPress, PHP and Timber are you using?

WordPress 4.5.2 **Multisite**, PHP 7, Timber 0.22.5. Using a [bedrock](https://github.com/roots/bedrock)-type setup.

Problem persists in Timber `dev-master`.
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Composer, via WPackagist.

**Comment by connorjburton** [comment]
Thanks for this, will investigate.

**Comment by haroldangenent** [comment]
This might be fixed when using `untrailingslashit(network_home_url())` instead of `home_url()` on Multisite, since uploads are served from the main website on subdirectory installs. However, `sideload_image` returns a relative path when the file exists. So the output is different the first time a file is sideloaded (you'll get a full URL). Returning a relative path works poorly on Multisite, since subdirectory websites wouldn't work (`www.example.com/sub/wp-content/uploads/...`).

_Notice `untrailingslashit()` on `network_home_url()`. While the [documentation](https://codex.wordpress.org/Function_Reference/network_home_url) claims a lack of trailing slash, it seems to return an URL **with** a trailing slash._

**Comment by palmiak** [comment]
@haroldangenent is this fixed? I see that some related PR was pushed in 2017 so it may fixed it.

**Comment by palmiak** [comment]
Thanks. I'll try to take a look soon. On the other hand I see you have made some research - maybe you will try to make a PR?

**Comment by haroldangenent** [comment]
Thanks, but currently we're not that invested in WordPress and Timber anymore, so I'm not able to invest too much time into this and WordPress-related projects. Also, I'm not too familiar with the codebase anymore, two years after filing the issue.

Also, the code is quite tangled right now and almost any change will break BC unwillingly (as I have experienced on several minor or patch releases already). I'm not sure that I'm the right person to judge past decisions and BC on this one. Hope you understand.

**Comment by jarednova** [comment]
I'm closing out old issues. Please open a fresh issue if this is still a live issue that we should investigate — thank you!
