### ISSUE TITLE
Cannot access private property Timber\Post::$_type 

### ISSUE THREAD

**Issue by jerome-quere** [timber/timber#1057]
Wordpress: 4.5.2
PHP: 5.6
Timber: 1.0.4

![image](https://cloud.githubusercontent.com/assets/526046/15896234/af6b59dc-2d8f-11e6-9166-a5d7d7da9d5a.png)

When Core::import is called with $info containing a field `_type` PHP throw an error because `Post::_type` is marked private since 0d218854642d243b8121843e78e51aba4dd645f4

**Comment by jarednova** [comment]
Closed by #1071
