### ISSUE TITLE
Timber Debug Bar doesn't show which php file a template is called from after 1.0.4 upgrade

### ISSUE THREAD

**Issue by hbrok** [timber/timber#1059]
### Expected behavior

Before 1.0.4 upgrade Timber Debug Bar showed which php file the twig template was called from:
![image](https://cloud.githubusercontent.com/assets/7627005/15911771/cd042940-2d96-11e6-9d78-0dcc07fe5289.png)

### Actual behavior

After upgrading to 1.0.4 this part is missing:
![image](https://cloud.githubusercontent.com/assets/7627005/15911975/9bdb8628-2d97-11e6-83f4-077af840df3a.png)

I thought this might be a Timber Debug Bar issue but it hasn't been updated recently, and the filter it's using to get the called from php file was removed [here](https://github.com/timber/timber/commit/0d218854642d243b8121843e78e51aba4dd645f4#diff-29bdb2cadf10c2dd9113be31487d6e67L250). This makes it seem more like a Timber issue, but I can move this issue to the Timber Debug Bar repo if needed!

### Steps to reproduce behavior

- Have Timber Debug Bar installed
- Look at the Timber Debug panel

### What version of WordPress, PHP and Timber are you using?

WordPress 4.5.2, PHP 5.6, Timber 1.0.4

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Updated through WordPress.

**Comment by jarednova** [comment]
#1127 — has a patch ready for this one

**Comment by jarednova** [comment]
Patch is in! @hbrok — take a look at the current `master` if you're interested (I'll release to wp.org tomorrow)
