### ISSUE TITLE
Making Timber Wordpress VIP Compatible

### ISSUE THREAD

**Issue by kala725** [timber/timber#1062]
I am willing to use timber as my templating engine for my wordpress VIP-GO site, but I can't find timber in the supportive plugin list. 

Is timber Wordpress VIP Compatible? What are the reasons, that you haven't submitted to wordpress VIP platform, Are there any obstacles ? 

If you can guide me for the same, I will submit a patch to them.

**Comment by connorjburton** [comment]
One for you @jarednova

**Comment by jarednova** [comment]
Hi @kala725 — I'm afraid this is would be a better question for the WordPress VIP team. I'd love to get it 100% VIP compatible, but I'm unsure what changes would be necessary. I know there's [another project](https://github.com/xwp/wp-vip-twig) with this specific aim. But based on the docs, it's _also_ not approved (at one point I heard that going through Twig to verify that the Twig library was VIP compatible was the big blocker)
