### ISSUE TITLE
User password hash from DB exposed in [user] object

### ISSUE THREAD

**Issue by streetyingyang** [timber/timber#1073]
### Expected behavior
Wasn't expecting to see my hashed password in an object available publicly.

### Actual behavior
In  [user] => Timber\User Object, the user_pass for my user is available.

### Steps to reproduce behavior
Login, display user_pass in twig template. Available for entire session.

{{ user.user_pass }}

### What version of WordPress, PHP and Timber are you using?
PHP 5.5.35 - MySQL 5.5.5 - WP 4.5.2 - Timber 1.0.3

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by jarednova** [comment]
Good point @streetyingyang — I see no reason why the user_pass should be returned by default. Any dissenting opinions?

**Comment by jarednova** [comment]
@streetyingyang — specifically are you concerned about someone in a template being able to retrieve via `{{ user.user_pass }}`? or is this more about someone doing a `print_r` on that object (for example, the [Timber Debug Bar](https://wordpress.org/plugins/debug-bar-timber/) would make that info available right now)

**Comment by streetyingyang** [comment]
Tough question. It's obviously not something somebody would want to use in a view. In some rare circumstances of someone being ignorant or having nefarious intentions, a list of users in a twig view could possibly expose user_pass.

I created a new user object via $context['user_test'] = new TimberUser(2); and got the same output my user has during my session (user_pass being printed). It's a stretch, but it might be attractive to crack a list of WP user hashes for particular sites through just an edited template.

I guess I'm not so concerned about WP Debug Bar showing my hash as an intern or human turd listing user hashes (sorted by username and email addresses as well) for fun.

**Comment by jarednova** [comment]
@streetyingyang thanks for highlighting this and your info. @lggorman made a PR that will be a part of the next release (#1084)
