### ISSUE TITLE
post.field_name now returns array instead of field

### ISSUE THREAD

**Issue by jesouhaite08** [timber/timber#1074]
### Expected behavior

post.field_name should return most recent field value.
### Actual behavior

post.field_name now returns an array of data when there have been more than one revisions to a page. if i change this to post.get_field('field_name') it correctly returns the most recent string of data.
### Steps to reproduce behavior

Install the advanced custom fields plugin. Create an ACF field and assign it to an existing page. Modify the data a few times so that the database has multiple revisions in the wp_postmeta table. Within your code type post.field_name and you will see it return an array of the values.
### What version of WordPress, PHP and Timber are you using?

WordPress 4.5.2, PHP 5.5.9, Timber 1.0.3.
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Timber already existed when I took the project over, I upgraded via WP.org.

**Comment by jarednova** [comment]
@jesouhaite08 can you give me the name and type of this custom field so that I can test against your scenario exactly? thanks!

**Comment by jesouhaite08** [comment]
@jarednova Sure! In one case I'm seeing it the name is _has_sidebar_ and the type is a _true/false_ field. I'm seeing it happen in any field with a revision, though. Thanks! :)

**Comment by lggorman** [comment]
@jesouhaite08 Which version of acf are you using?  Having trouble replicating.

**Comment by jesouhaite08** [comment]
@lggorman I'm using ACF version 5.3.9.1. Thank you!

**Comment by lggorman** [comment]
@jesouhaite08 I've been testing with your versions of WP, Timber, and ACF and haven't been able to reproduce the issue.  Are there any other specifics of your setup that might be useful to know about?  Other plugins maybe?

**Comment by cjke** [comment]
I'm experiencing something similar with ACF 5.3.9.2. 

I have the following plugins installed on WP 4.5.3:
- Paid Memberships Pro 1.8.9.3
- WP REST API 2.0-beta

The snippet I am using to access the field is as follows:

```
    {% for item in post.get_field('home_page_layout') %}
        {% if item.acf_fc_layout == 'layout_-_image_left' %}
            <h2>{{item.heading}}</h2>
            <img src="{{TimberImage(item.image).src}}" />
            <aside class="notes">{{item.text}}</aside>
        {% elseif item.acf_fc_layout == 'layout_-_image_right' %}
            <h2>{{item.heading}}</h2>
            <aside class="notes">{{item.text}}</aside>
            <img src="{{TimberImage(item.image).src}}" />
        {% endif %}
    {% endfor %}
```

Dumping out post, yields the following, pulling out the relevant section: 

```
  ["home_page_layout"]=>
  array(2) {
    [0]=>
    string(19) "layout_-_image_left"
    [1]=>
    string(20) "layout_-_image_right"
  }
  ["_home_page_layout"]=>
  string(19) "field_57807ba946da2"
  ["home_page_layout_1_text"]=>
  string(303) "lorem text"
  ["_home_page_layout_1_text"]=>
  string(19) "field_57807cb4a1910"
  ["home_page_layout_1_image"]=>
  string(0) ""
  ["_home_page_layout_1_image"]=>
  string(19) "field_57807cb4a190f"
  ["home_page_layout_0_heading"]=>
  string(33) "Grab a coffee"
  ["_home_page_layout_0_heading"]=>
  string(19) "field_5780810228671"
```

I have attached an export of that custom content type

[acf-export-2016-07-09.json.zip](https://github.com/timber/timber/files/355437/acf-export-2016-07-09.json.zip)

**Comment by jesouhaite08** [comment]
@lggorman The site I'm working on has 28 active plugins. Appreciate you trying.

**Comment by cjke** [comment]
@jesouhaite08 Ah, revisions right gotcha. I will use your tips re: get_field. 

@lggorman I want to second the above sentiment, and thank you for looking into this and trying.

**Comment by swthate** [comment]
I just noticed after updating from 1.0.5 to 1.1.1 the same issue. Using `get_field()` seems to do the trick for me, too. Thanks!

**Comment by jesouhaite08** [comment]
@swthate No problem!

**Comment by palmiak** [comment]
@jesouhaite08 is this issue fixed (using `get_field()`)? If so, please close it.
