### ISSUE TITLE
How to use wp_nav_menu?

### ISSUE THREAD

**Issue by joaoeduardo** [timber/timber#1076]
I call wp_nav_menu() inside a function in functions.php file.
Then I call this function on a twig file, but nothing was displayed.
I use WordPress 4.5.2, Timber 1.0.4 installed through wpackagist.

```php
function theme_menu()
{
    wp_nav_menu(array(
        'menu'           => 'primary',
        'theme_location' => 'primary',
        'depth'          => 2,
        'container'      => false,
        'menu_class'     => 'menu__list',
        'fallback_cb'    => 'wp_bootstrap_navwalker::fallback',
        'walker'         => new wp_bootstrap_navwalker()
    ));
}
```
```twig
{{ function('theme_menu') }}
```

**Comment by commercial-hippie** [comment]
Timber has its own way to print out navigation menus and it's a lot easier to customize that wp_nav_menu.

See the menu page in the Wiki for details: https://github.com/timber/timber/wiki/TimberMenu

**Comment by joaoeduardo** [comment]
I know, but I would like to use this way.

**Comment by connorjburton** [comment]
You could try adding the `'echo' => false` args to `wp_nav_menu` and then return it.

```php
function theme_menu()
{
    return wp_nav_menu(array(
        'echo' => false,
        'menu'           => 'primary',
        'theme_location' => 'primary',
        'depth'          => 2,
        'container'      => false,
        'menu_class'     => 'menu__list',
        'fallback_cb'    => 'wp_bootstrap_navwalker::fallback',
        'walker'         => new wp_bootstrap_navwalker()
    ));
}
```

**Comment by joaoeduardo** [comment]
@connorjburton Recently I tried again, with this args, and it worked. Thank you. Sorry for this silly question.
