### ISSUE TITLE
1.0.4 breaks media upload in multisite

### ISSUE THREAD

**Issue by davidallansson** [timber/timber#1078]
### Expected behavior

Image uploaded to the defined WP_CONTENT_DIR in wp-config
### Actual behavior

Image gets uploaded to the seperated core path under <core>/wp-content/
### Steps to reproduce behavior

Using Timber 1.0.4
In root folder of website use a index file to define Wordpress core path, common practice if using composer to install the core.
require( dirname( **FILE** ) . '/core/wp-blog-header.php' );
Also define WP_CONTENT_DIR in wp-config

When using Timber 1.0.3 all images gets uploaded correctly.
### What version of WordPress, PHP and Timber are you using?

Wordpress 4.5.2
PHP 5.5.34
Timber 1.0.4
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Installed with Composer/Packagist.

**Comment by jarednova** [comment]
Hi @davidallansson — I spent a big chunk of time trying to recreate this issue on my side, but was unable. That said, I don't doubt this is happening — there are lots of places where Timber is dancing around various media upload folders. I know I've been imperfect about implementing these for the types of setups you're on. Could you look into where the I might have gone astray and submit a PR?

**Comment by palmiak** [comment]
@davidallansson Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread

**Comment by davidallansson** [comment]
@palmiak No need to get this addressed. Closing it.
