### ISSUE TITLE
preg_match(): Compilation failed warnings

### ISSUE THREAD

**Issue by kirkov** [timber/timber#1080]
### Expected behavior

No warnings.
### Actual behavior

Got multiple warnings:

```
( ! ) Warning: preg_match(): Compilation failed: \k is not followed by a braced, angle-bracketed, or quoted name at offset 11 in [...]\vendor\timber\timber\lib\ImageHelper.php on line 246
```

Stack trace:

```
1   0.0009  442848  {main}( )   ...\upload.php:0
2   0.4023  21430736    wp_delete_attachment( string(4), ??? )  ...\upload.php:161
3   0.4053  21442560    do_action( string(17), string(4) )  ...\post.php:4868
4   0.4063  21442904    Timber\ImageHelper::Timber\{closure}( string(4) )   ...\plugin.php:525
5   0.4070  21515304    Timber\ImageHelper::delete_generated_files( string(77) )    ...\ImageHelper.php:178
6   0.4071  21515888    Timber\ImageHelper::process_delete_generated_files( string(20), string(3), string(52), string(13), string(24) ) ...\ImageHelper.php:221
7   0.4090  21518600    preg_match ( string(105), string(85) )  ...\ImageHelper.php:246
```
### Steps to reproduce behavior

Delete multiple images in the Media library.
### What version of WordPress, PHP and Timber are you using?

WordPress 4.5.3, PHP 7.0.3, Timber 1.0.3
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Composer

**Comment by jarednova** [comment]
@kirkov is this on a multisite or regular install?

**Comment by kirkov** [comment]
Regular install - and forgot to mention, on Windows 10.

**Comment by jarednova** [comment]
_We put the "Win!" in "Uninstall Windows!"_

.... sorry

**Comment by palmiak** [comment]
@kirkov Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread

**Comment by kirkov** [comment]
No worries 💯
