### ISSUE TITLE
Fatal error: Class 'Route' not found in

### ISSUE THREAD

**Issue by louisbeziau** [timber/timber#1082]
I'm using routes on Timber v1.0.5 with Wordpress to have nice url for my news.

`Route::map('news', function() {
    $query = 'post_type=post';
    Routes::load('archive-news.php', $query);
});

Route::map('news/page/:pg', function($params) {
    $query = 'post_type=post&paged='.intval($params['pg']);
    Routes::load('archive-news.php', $query);
});`

And I'm getting this error : Fatal error: Class 'Route' not found in

Any idea ?

**Comment by jarednova** [comment]
Try `Routes` vs `Route`

**Comment by louisbeziau** [comment]
Thanks a lot

**Comment by louisbeziau** [comment]
Thanks a lot
