### ISSUE TITLE
Dates rendering incorrectly

### ISSUE THREAD

**Issue by thedamon** [timber/timber#1085]
### Expected behavior
`{{ '1457395200' | date('Y-m-d') }} => 2016-03-08`
`{{ 1457395200 | date('Y-m-d') }} => 2016-03-08`
`{{ function('date_i18n', 'Y-m-d', 1457395200) }} => 2016-03-08`
`{{ function('date', 'Y-m-d', 1457395200) }} => 2016-03-08`

### Actual behavior
`{{ '1457395200' | date('Y-m-d') }} => 5200-06-24`
`{{ 1457395200 | date('Y-m-d') }} => 5200-06-24`
`{{ function('date_i18n', 'Y-m-d', 1457395200) }} => 2016-03-08`
`{{ function('date', 'Y-m-d', 1457395200) }} => 2016-03-08`

### Steps to reproduce behavior
Simply using the function. Most dates work fine, certain ones are rendering unexpectedly (with the last 4 digits coming out as the year and the day/month appearing to be today's month and day)
If I add ` | number_format(0, '.', '')` before `| date`, different dates will be messed up.

### What version of WordPress, PHP and Timber are you using?
WordPress 4.5.1, PHP 5.6, Timber 1.0.5 -->

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Downloaded from WP plugins page

**Comment by jarednova** [comment]
Closed by #1087
