### ISSUE TITLE
Fatal error: Uncaught Error: Cannot access property started with '\0' timber-core.php

### ISSUE THREAD

**Issue by johnstew** [timber/timber#1095]
### Expected behavior
Expecting for Timber to render complete homepage.

### Actual behavior
Currently the homepage of the site is only rendering about half the page. Whats weird is there are other pages on the site that render completely fine and work. 

`Fatal error: Uncaught Error: Cannot access property started with '\0' in /var/www/html/wp-content/plugins/timber-library/lib/timber-core.php:67`

Homepage only half rendering. Trying to diagnose why but getting the above error for it failing.

### What version of WordPress, PHP and Timber are you using?
WordPress 4.5.2, PHP 7.0.8-3, Timber 0.22.5

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WP Plugin

**Comment by jarednova** [comment]
@johnstew the newest version of Timber fixes this. @FlyingDR fixed this in #1067. If you need to stick with `0.22.5`, you can read through his commits to see what was changed to get that working again

**Comment by johnstew** [comment]
Awesome thanks a lot!
