### ISSUE TITLE
How can I get an arbitrary permalink within Timber?

### ISSUE THREAD

**Issue by matgargano** [timber/timber#1097]
### Expected behavior
I am trying to get a permalink for arbitrary posts that I have saved in a custom field for a post. It's saved as ` [{Post Object} , {Post Object} , {Post Object} ]`

When I loop through the array, which is saved in my context as `blog_posts` I have tried:

```
{% if blog_posts is not empty %}
    <div class="single-person--recent-articles">
        <ul>
            {% for blog_post in blog_posts %}

                Path: {{  blog_post.get_path }} !!
                <li><a href="{{ blog_post.get_path|e('url') }}">{{ blog_post.post_title|e }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
```

expecting the URL for the post to be output, however it is not.

### Actual behavior
It is returning blank, e.g. `Path: !!`

### Steps to reproduce behavior
Set a custom field equal to an array of valid WP_Post objects as `blog_posts` and try running the code

### What version of WordPress, PHP and Timber are you using?
Latest of both (I use composer to update)

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by matgargano** [comment]
I see I can just run 

```
{{ function('get_permalink', blog_post.ID) }}
```

is this the right way?

**Comment by jarednova** [comment]
@matgargano try:

```twig
{% if blog_posts is not empty %}
    <div class="single-person--recent-articles">
        <ul>
            {% for blog_post in Post(blog_posts) %}

                Path: {{  blog_post.path }} !!
                <li><a href="{{ blog_post.path | e('url') }}">{{ blog_post.post_title |e }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
```

... in the `{% for` loop you're declaring that items from the `blog_posts` array should be handled as `TimberPost` objects

**Comment by matgargano** [comment]
awesome!
