### ISSUE TITLE
External images are downloaded again each month

### ISSUE THREAD

**Issue by haroldangenent** [timber/timber#1098]
### Expected behavior

External images are downloaded to the uploads directory. Expected behaviour is that they are downloaded once and then served from this location in the future.
### Actual behavior

If an image is downloaded on 30-06-2016, it will be downloaded again on 01-07-2016. When a lot of images are involved, this can really fill up a hard drive.
### Steps to reproduce behavior
1. Use resize on an external image
2. Resize it again when a month passes
### Possible solution

If all images would be downloaded in the same folder, this wouldn't happen. You could also easily remove all sideloaded images that way.

This is not really a bug, but it would be great if this behaviour could be altered by filtering `get_sideloaded_file_loc()` or something.
### What version of WordPress, PHP and Timber are you using?

WordPress 4.5.3, PHP 7, Timber 1.0.5.
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Timber Library via WPackagist (but doesn't really matter).

**Comment by hbrok** [comment]
My solution (for now) was adding an action to [`ImageHelper::get_sideloaded_file_loc()`](https://github.com/timber/timber/blob/cbb8dc14ce47f5d7f24504675ea7390a8adca65b/lib/ImageHelper.php#L276):

```
public static function get_sideloaded_file_loc( $file ) {
		do_action('timber/img/external_upload_subdir'); // I added this line.
		$upload = wp_upload_dir();
		$dir = $upload['path'];
		$filename = $file;
		$file = parse_url($file);
		$path_parts = pathinfo($file['path']);
		$basename = md5($filename);
		$ext = 'jpg';
		if ( isset($path_parts['extension']) ) {
			$ext = $path_parts['extension'];
		}
		return $dir.'/'.$basename.'.'.$ext;
	}
```

Then in the action, I use the `upload_dir` filter to change the subdir to `external`.
```
add_action( 'timber/img/external_upload_subdir', function () {
	add_filter( 'upload_dir', function ( $upload ) {
		$upload['subdir'] = '/external';
		$upload['path']   = $upload['basedir'] . $upload['subdir'];
		$upload['url']    = $upload['baseurl'] . $upload['subdir'];
		return $upload;
	} );
} );
```

I did this so I would be editing as little of the Timber plugin files as possible so upgrades won't be a pain. But I'm referencing hundreds of external images so I needed a quick fix!

**Comment by haroldangenent** [comment]
@hbrok Thanks for the tip. I have a similar temporary fix, but this doesn't require to update Timber's source code (which is impossible when using a dependency manager like Composer). I have actually hooked into Twig to setup the `resize` filter to include my own object, so I can perform some checks before passing `resize` to Timber's object.

The code below also fixes uppercase extension problems reported in #829. **Remember that this is a hacky workaround and just a temporary fix.**

```<?php
/**
 * This class extends ImageHelper to attempt to fix some sideload issues
 * Timber\ImageHelper is still initialized and mostly used
 *
 * @see https://github.com/timber/timber/issues/829
 * @see https://github.com/timber/timber/issues/1098
 */
namespace <removed>;

use Timber\ImageHelper;
use Timber\URLHelper;

final class ImageHelperFixer extends ImageHelper
{
    /**
     * @see Timber\ImageHelper::resize
     */
    public static function resize($src, $w, $h = 0, $crop = 'default', $force = false)
    {
        if (URLHelper::is_external_content($src)) {
            // Fixes: external images are downloaded every month (#1098)
            add_filter('upload_dir', array(__CLASS__, 'setUploadDir'));

            // Fix sideload issue: uppercase image extensions (#829)
            $fileLoc = self::get_sideloaded_file_loc($src);
            $file = pathinfo($fileLoc);
            $lowercaseExtension = self::getLowercaseExtension($fileLoc, $file['extension']);

            if (file_exists($lowercaseExtension)) {
                // Return existing file URL
                $src = URLHelper::get_rel_path($lowercaseExtension);
            }
        }

        // Timber resize
        $result = parent::resize($src, $w, $h, $crop, $force);

        // Remove filter
        remove_filter('upload_dir', array(__CLASS__, 'setUploadDir'));

        return $result;
    }

    public static function setUploadDir($upload)
    {
        $upload['subdir'] = '/external';
        $upload['path'] = $upload['basedir'] . $upload['subdir'];
        $upload['url'] = $upload['baseurl'] . $upload['subdir'];

        return $upload;
    }

    private static function getLowercaseExtension($src, $extension)
    {
        return str_replace('.' . $extension, '.' . strtolower($extension), $src);
    }
}
```

The actual Twig filter is initialized like this:

```
$twig->addFilter(new \Twig_SimpleFilter('resize', array(__NAMESPACE__ . '\ImageHelperFixer', 'resize')));
```

Applied on the `timber/twig` filter.

**Comment by haroldangenent** [comment]
@hbrok By the way, don't forget to remove the filter after Timber is done resizing, so the filter is not executed later and / or multiple times.

**Comment by jarednova** [comment]
@haroldangenent @hbrok thanks for bringing this to my attention! @haroldangenent you mention that what you have is a workaround for now. What would it take to make it into a more stable PR? Are there any additional hooks/filters I could add that would help?

**Comment by haroldangenent** [comment]
@jarednova I currently have three ideas about a more stable solution:

1. Provide hooks before and after sideloading an image so a developer 'knows' when to hook into `wp_upload_dir` to change it
2. Provide a filter for a developer to change the sideloaded directory and change `wp_upload_dir` in Timber
3. Somehow fix entirely the issue another way or maybe even put all sideloaded files into one specific folder

Option 1 would be the easiest to implement, but still doesn't fix the issues and requires a more seasoned developer to read the code and understand how to use these hooks. Option 2 is a bit more work and makes Timber a bit more responsible. 

I'm not sure about backwards compatibility and impact when going for Option 3, but it would certainly be the best option, since users won't be bothered the inner workings of `resize()`.

@jarednova @hbrok What do you think?

**Comment by jarednova** [comment]
I'm closing out old issues. Please open a fresh issue if this is still a live issue that we should investigate — thank you!

**Comment by gchtr** [comment]
I’m reopening this.

I ran into the same issue and came up with a solution in #2376 that uses a combination of 2. and 3. from @haroldangenent’s suggestions.

> I currently have three ideas about a more stable solution:
> 
> 1. Provide hooks before and after sideloading an image so a developer 'knows' when to hook into `wp_upload_dir` to change it
> 2. Provide a filter for a developer to change the sideloaded directory and change `wp_upload_dir` in Timber
> 3. Somehow fix the issue another way or maybe even put all sideloaded files into one specific folder

- External images are loaded into a **sideloaded** folder in the uploads folder by default.
- The name can be controlled with a `timber/image_sideload/subdir` filter.

**Comment by Levdbas** [comment]
Since this issue has been open for so long without it getting much traction, I am going to close this. If anyone still runs into this in 2.x, please open a new ticket.
