### ISSUE TITLE
Question - how to get custom menu css class

### ISSUE THREAD

**Issue by Luckyfella73** [timber/timber#1100]
Hi,

I wonder if there is a way to get (only) the custom css class(es) defined in WP backend and assigned to a menu item.

The timber wiki tells us how to get all the classes when building the menu:
`
{{item.classes | join(' ')}}
`

but it would be great to be able to extract the custom classes from the onces dynamically created by WP.

Any ideas?

**Comment by connorjburton** [comment]
I don't think this is available through the `MenuItem` class, what are you trying to achieve with this? We could add a `custom_classes` attribute

**Comment by Luckyfella73** [comment]
I had to build a menu having an icon (custom icon-font) and textlink below icon. I needed the css class that can be set in WP backand / menu items for an element nested inside the li element (span class="menuicon ...")

`
 <nav id="menu" class="wrapper-menu-main">
	<ul class="nav-main">
		{% for item in main_menu.get_items %}

			<li class="nav-main-item {{ item.classes | join(' ') }}">
				{% set custom_icon_class = item.classes.0 %}
				<a href="{{ item.get_link }}"><span class="menuicon {{ custom_icon_class|build_menu_icon_css }}"></span></a>

				<a class="nav-main-link" href="{{ item.get_link }}">{{ item.title }}</a>
				{% if item.get_children %}
					<ul class="nav-drop">
					{% for child in item.get_children %}
						<li class="nav-drop-item">
							<a class="nav-sub-link" href="{{ child.get_link }}">{{ child.title }}</a>
						</li>
					{% endfor %}
					</ul>
				{% endif %}
			</li>

		{% endfor %}
		<span class="clearfix"></span>
	</ul>
</nav>
`

I found out that item-classes array allways start with the custom classnames, so I just grabbed the first array item to solve my problem. But it's more a hack so I wondered if there is a better way to substract the custom menu classes. For I get css issues if the li items have the same css class I need for the span tag, I did set other names in WP backend and rebuild the values using a filter ("build_menu_icon_css") for the span tag..

A 'custom_classes' attribute would be great of course =) My solution works but feels not right..

**Comment by palmiak** [comment]
@Luckyfella73  Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread

**Comment by Luckyfella73** [comment]
@palmiak Though I don't need that functionality right now it would be a nice feature being able to easily extract only the css classes for a menu item that we did set manually. If you agree with that idea and it's easy to implement that feature would be fine :)

**Comment by palmiak** [comment]
Thanks for the response @Luckyfella73 - take a look at https://github.com/timber/timber/issues/1820 - because as you some bigger changes to menu are coming so I'm not sure is now is the right moment for such a fix. I will leave this issue so we can come back to this later.

**Comment by Luckyfella73** [comment]
@palmiak thank you - and you are right, better first get the bigger changes done.

**Comment by jarednova** [comment]
I'm closing all 2+ year old tickets. This may be already resolved or in-progress based on what we're doing with Version 2.0. If someone wants to pick this up, let's make it a fresh issue
