### ISSUE TITLE
Extended Timber's Post object with custom methods, how to apply that to the main loop?

### ISSUE THREAD

**Issue by matgargano** [timber/timber#1102]
I added a [class](https://gist.github.com/matgargano/0bb78506044579571ccb2043c151b576) that extends `Timber\Post` for grabbing and returning connected fields using [Posts to Posts](https://github.com/scribu/wp-posts-to-posts)

If I want to use this class, you give a dead simple way when using Timber::get_posts() to tell it what class to use, e.g. `$context['posts'] = Timber::get_posts( $args, Connected_Posts::class );` which works beautifully.

However, if I'm not using `Timber::get_posts` when setting up my context and I want to use the main loop which is picked up via `Timber::get_context` [I believe] - how can I tell Timber to use my class instead of Timber\Post?

I'm quite new to Twig and Timber as a whole, but looking through your code I was able to put together:

```php
add_filter('timber/twig/filters', function($twig){

	$twig->addFunction(new \Twig_SimpleFunction('Connected', function( $pid, $PostClass = Connected_Posts::class ) {
		if ( is_array($pid) && !\Timber\Helper::is_array_assoc($pid) ) {
			foreach ( $pid as &$p ) {
				$p = new $PostClass($p);
			}
			return $pid;
		}
		return new $PostClass($pid);
	} ));

	return $twig;
});
```

and then in my template use:

```twig
{% for post in posts %}
    {% set post = Connected(post) %}
    {% set locations = post.get_connected('Lawyer_to_Office') %}
    {% if locations is not empty %}
        {% for location in locations %}
            <p>{{ location.post_title }}</p>
        {% endfor %}
    {% endif %}
{% endfor %}
```

But I am not sure if a) this is the right way to do it, or b) this will absolutely work, thought it appears that it does. Any help would be greatly appreciated.

**Comment by jarednova** [comment]
@matgargano what you have will work. My take is to usually override what's coming through with...

```php
$context['posts'] = Timber::get_posts( false, Connected_Posts::class );
```
... which will use the default query of that PHP loop

**Comment by matgargano** [comment]
👍

**Comment by TheMangoTrain** [comment]
For reference, this works in a single post context as well, where no particular args need to be passed:

`$context['post'] = Timber::query_post(false, MyPost::class);`
