### ISSUE TITLE
Use for Plugins

### ISSUE THREAD

**Issue by sajadghawami** [timber/timber#1103]
Hey Guys,

is it a good idea to use timber to develop new Plugins? 
I am looking for a neat Framework to do that, but timber seems to be a framework for theme development, and not plugins.

Thanks

**Comment by jarednova** [comment]
@leakingminds we've used it before in plugins! https://github.com/upstatement/stream-manager — that said, it's definitely more tested in a theme context

**Comment by leakingminds** [comment]
@jarednova thanks!

any recommedations what framework could be used in addition to timber, to develop plugins?

**Comment by palmiak** [comment]
Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread

**Comment by sajadghawami** [comment]
Thanks, i ll close this.
