### ISSUE TITLE
Undefined variable: current

### ISSUE THREAD

**Issue by nikola3244** [timber/timber#1104]
### Expected behavior

No notices.
### Actual behavior

Couple notices of undefined variables.
```
Notice: Undefined variable: current in /home/nikola/public_html/wphelium/wp-content/plugins/timber-library/lib/Timber.php on line 464
Notice: Undefined variable: current in /home/nikola/public_html/wphelium/wp-content/plugins/timber-library/lib/Timber.php on line 467
Notice: Undefined variable: current in /home/nikola/public_html/wphelium/wp-content/plugins/timber-library/lib/Timber.php on line 464
Notice: Undefined variable: current in /home/nikola/public_html/wphelium/wp-content/plugins/timber-library/lib/Timber.php on line 467
```
### Steps to reproduce behavior

I got this error while trying out "Helium" template from RocketTheme.
[Can be downloaded here](http://gantry.org/downloads#ci-builds).

### What version of WordPress, PHP and Timber are you using?

Wordpress 4.5.3, Apache/2.4.20 (Unix) OpenSSL/1.0.2h PHP/5.6.23, Timber 1.1.0 

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Fresh install from WordPress, "Add new plugin".

**Comment by jarednova** [comment]
Closed by #1105
