### ISSUE TITLE
Correct Wordpress admin bar location

### ISSUE THREAD

**Issue by arnisjuraga** [timber/timber#1107]
Did not found a solution or comments on this, may be I am doing something wrong, but the code is quite simple:

I have index.twig template and everything works fine, until I login into admin - 
1) Wordpress adds admin-bar HTML _before index.twig_ template code itself.
2) Wordpress does not adds additional admin classes for `<body>` tag

looks like this:
In `index.php` file:

``` php
...
Timber::render(array('/pages/index/index.twig'), $context, 1);
```

my `.twig` file:

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Klinta</title>
    <link rel="stylesheet" href="{{site.theme.link}}/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{site.theme.link}}/style.css">
    {{ function('wp_head') }}
  </head>
  <body>
```

Result in WEB page, with logged in admin:

``` html
...
        <li id="wp-admin-bar-edit-profile"><a class="ab-item"  href="http://wordpress/wp-admin/profile.php">Rediģēt savu profilu</a>      </li>
        <li id="wp-admin-bar-logout"><a class="ab-item"  href="http://wordpress/wp-login.php?action=logout&#038;_wpnonce=55f2e3325f">Atslēgties</a>        </li></ul></div>        </li></ul>          </div>
                        <a class="screen-reader-shortcut" href="http://wordpress/wp-login.php?action=logout&#038;_wpnonce=55f2e3325f">Atslēgties</a>
                    </div>

<!DOCTYPE html>
<html>
  <head>
...
...
</head>
<body>
...
```

**Comment by jarednova** [comment]
@arnisjuraga — that's really strange. The admin bar outputs via `{{ function('wp_head') }}` so it should come within those `<head>` tags. Can you remove that line (in the twig file) and see if you still see the admin bar output? My guess is you have a `wp_head()` call (or something calling it) in one of those PHP files

**Comment by jgierer12** [comment]
The HTML code for the admin bar actually outputs at the end of the document via `wp_footer()`. So check if you have that in your template.

**Comment by palmiak** [comment]
@arnisjuraga Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread

**Comment by arnisjuraga** [comment]
Hi! No, I am not working with Timber anymore, so - I cant tell anything new about this issue. If no one else is experiencing this, we can close it freely.
