### ISSUE TITLE
Conditional extends in templates

### ISSUE THREAD

**Issue by arnasziedas** [timber/timber#1108]
Is there a way to pass on a variable to be used in extends conditional? See example below:

```
{% extends ajax
         ? 'base_ajax.twig' 
         : 'base.twig' 
%}
```

This is for cases when you need a certain block or a child template to be passed on through AJAX.

I realise it's more of a Twig related issue than Timber but was wondering if there's any way to attach that wanted _ajax_ variable to any Timber objects.

**Comment by jarednova** [comment]
@arnasziedas, does this article help? http://twig.sensiolabs.org/doc/recipes.html#making-a-layout-conditional

I think it's as simple as sending a value into the template's data:

```php
/* single.php */
$data = Timber::get_context();
$data['ajax'] = true; //or however to determine
Timber::render('single.twig', $data);

**Comment by arnasziedas** [comment]
Thanks @jarednova, storing a variable in context object and then passing it later to extends tag conditional did the trick!
