### ISSUE TITLE
Extra redirects due to wrong pagination

### ISSUE THREAD

**Issue by xavivars** [timber/timber#1109]
### Expected behavior
When clicking on a pagination link, I would land on the final URL

### Actual behavior
There's a 301 redirect from the click on the pagination link to the actual page

### Steps to reproduce behavior
Due to https://github.com/timber/timber/blob/master/lib/Helper.php#L515, links to different pages are like

    htttp://example.org/page/2

instead of 

    http://example.org/page/2/

Because WordPress (usually) always adds a / at the end of the URLs, there's an extra redirect on every link that is generated in the using `Timber::get_pagination()`.

### What version of WordPress, PHP and Timber are you using?
WordPress 4.5.3, PHP 5.6, Timber 1.1.0

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WP.org

**Comment by jarednova** [comment]
@xavivars — is this as simple as changing `untrailingslashit` to `trailingslashit`? Does WordPress have a canonical rule for whether URLs should have a trailing slash?

**Comment by jarednova** [comment]
@xavivars fantastic! I didn't realize that method existed . Please do a PR when you can!

**Comment by xavivars** [comment]
I've just pushed #1112 so you can take a look, but it's not ready to be merged: tests are not passing.

Even if in my setup (with a very standard /%postname%/ setup) works now, a few tests (that I modified) are failing: some of the setups of the tests seem very weird to me (expecting links like http://example.org/page/5/?s=post ).

Also, even in the tests I wrote, the positive case (the one covering the case that works in my local install) is not passing.

I guess there's something missing in the test setup, but I'm not familiar enought with the permalinks area of WordPress

**Comment by mrgrain** [comment]
Seems fine, but you'll have to call `	resetPermalinks()` from `$this`:
`$this->resetPermalinks();`

:)

**Comment by jarednova** [comment]
Closed by #1112
