### ISSUE TITLE
Return primary category

### ISSUE THREAD

**Issue by dudewithamood** [timber/timber#1116]
Hi,

get_category() returns the first category where there are multiple.

Since Wordpress allows for making one category the primary category, would it make sense to return that?

Thank you

**Comment by jarednova** [comment]
@dudewithamood you bet it would! But I'm unfamiliar with "primary category" functionality (unless it comes from a plugin) can you point us to some docs?

**Comment by dudewithamood** [comment]
@jarednova ah, yes, I hear what you are saying. I didn't realise but it seems to have been introduced with the Yoast SEO plugin. I guess then I should try and use their breadcrumb rather than create my own.

**Comment by asecondwill** [comment]
i tried to do this using 

`{{ dump(post.terms( {query:{taxonomy:'category',  ID: post._yoast_wpseo_primary_category}})) }}`

but it does not filter by term id.  frustrating. 

I tried extending post

class MySitePost extends Timber\Post {
	public function primary() {
		return 64;  // TODO:  return the primary using a wp query

	}
}

but that doesnt extend the post object by default (right? or i'm doing it wrong). so it would require me to change all my single.php and category.php files etc to use that class.


instead I'm doing a loop. 

```
  {% for term in post.terms  %}      
    {% if term.id == post._yoast_wpseo_primary_category %}        
        <a href={{term.link}}  class="section-box"> {{  term }}</a>
    {% endif %}
  {% endfor %}
```

and occasionally using that value in php controllers where needed:

```
$args = [  
  'posts_per_page' => 4  ,
  'category' => $timber_post->_yoast_wpseo_primary_category ,
  'post__not_in' => [$timber_post->ID  ]
];


$context['related_posts'] = new Timber\PostQuery($args);
```
