### ISSUE TITLE
Unable to render the SiteOrigin's Page Builder (plugin) WYSIWYG editor content on any post or page

### ISSUE THREAD

**Issue by jared83** [timber/timber#1117]
### Expected behavior

After installing, activating and switching to SiteOrigin's Page Builder editor on any page or post, calling `{{ post.content }}` should render Page Builder's editor content with applied filters, shortcodes, widgets etc. to `{{ post.content }}`.
Timber's documentation states that calling `{{ post.content }}` does just that. However It doesn't seem to handle the Page Builder's content. I inquired SiteOrigin about this on Page Builder's github repo in [this](https://github.com/siteorigin/siteorigin-panels/issues/243) issue. They bounced the ball back to you.
If I investigate the output of `{{ post | print_r }}` I can see that the Page Builder  added additional fields `panels_data` and `panels_data_preview` that hold data needed to render Page Builder's content. By their github response to my issue as well as Timber's documentation, one would expect to find the Page Builder's content properly rendered in the `{{ post.content }}` variable, witch doesn't happen.
I tried various ways to process the `panels_data` field like:

```
{% filter shortcodes %}
        {{ aboutPost.panels_data ? aboutPost.panels_data : aboutPost.content }}
{% endfilter %}
```

or

```
{{ aboutPost.panels_data | apply_filters('siteorigin_panels_data') }}
```

where `siteorigin_panels_data` is a filter added to WP from the Page Builder `siteorigin-panels.php`
and even called the 
`siteorigin_panels_filter_content( $context->post );`
function (also defined within the `siteorigin-panels.php`) right before `Timber::render`, 
but no joy.
### Actual behavior

Timber renders the content of the standard WordPress editor rather that Page Builder's content created with the visual editor.
### Steps to reproduce behavior

Install/Activate [SiteOrigin Page Builder](https://wordpress.org/plugins/siteorigin-panels/) plugin.
Switch WYSIWYG editor to Page Builder on any post and add some content/grid/widgets.
Call `{{ post.content }}` on relevant post/page twig template.
### What version of WordPress, PHP and Timber are you using?

WordPress 4.5.3, PHP 5.6.23, Timber 1.0.5
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Installed 1.0.5 version via plugin installer in WordPress dashboard.

**Comment by bravebox** [comment]
Hi Jared, did you even figure out a solution? Thanks

**Comment by josephnle** [comment]
Also interested in a solution

**Comment by ctaity** [comment]
Any solution??? I Also interested in a solution

**Comment by Provo17** [comment]
This solution is pretty late and very simplistic (will build on it shortly) but I just started integrating timber into an existing WP theme that uses page builder and I've figured out how to access the page builder content. 

Here is a screenshot ot the data returned using `        <pre>
            <code>{{ greeting | print_r }}</code>
        </pre> ` in my `home.twig` file.

![screen shot 2018-04-10 at 2 20 43 pm](https://user-images.githubusercontent.com/16328525/38578744-6f8155a0-3cca-11e8-9efb-515a28830aa1.png)

As you can see the actual page builder content `[text]` (Lorem ipsum) is nested three level down in the panels_data array. To access the content I simply chained the arrays like so `<p>{{ greeting.panels_data.widgets.0.text }}</p>` . 

As stated above this is a very simplistic way of accessing the content. I will make a follow up post with a more dynamic way to loop through and select the wanted content.

**Comment by landwire** [comment]
Is there any more progress in getting timber to render the pages created with SiteOrigin's Page Builder properly?
