### ISSUE TITLE
Limit Pagination to category?

### ISSUE THREAD

**Issue by SlawaGurevich** [timber/timber#1119]
As everybody is aware, you can just include all categories with `$c['categories'] = $categories;` and then just get the posts belonging to that category with `{% for post in category.get_posts({"posts_per_page":4}) %}` and display them on the page, which works great.

But what if I would like to use multiple paginations for each of the post categories I got with the `category.get_posts`? As far as I understand, you have to include the pagination in the context, so there is obviously no way of getting it dynamically for the current posts I'm iterating over, is there? Is there?

**Comment by jarednova** [comment]
@SlawaGurevich right now it'd take some pretty serious acrobatics to get that to work. But what we're looking at with #1118 should help solve this

**Comment by SlawaGurevich** [comment]
Yes, I guess that would solve the problem. Looking forward for it to get implemented ;)

**Comment by jarednova** [comment]
I'm closing out old issues. Please open a fresh issue if this is still a live issue that we should investigate — thank you!
