### ISSUE TITLE
PHP notice being thrown when using Timber::get_pagination()

### ISSUE THREAD

**Issue by felipearosemena** [timber/timber#1120]
When calling `Timber::get_pagination()` on an index page, an PHP notice gets thrown.

```
Notice: Undefined variable: current in /Users/Felipe/Sites/base-project/wp-content/mu-plugins/timber-library/lib/Timber.php on line 464

Notice: Undefined variable: current in /Users/Felipe/Sites/base-project/wp-content/mu-plugins/timber-library/lib/Timber.php on line 467
```

**Comment by jarednova** [comment]
@felipearosemena — I believe this is fixed from #1105. Are you using the current version from WP.org, or `master`?

**Comment by felipearosemena** [comment]
@jarednova I'm using the one from WP.org.

**Comment by felipearosemena** [comment]
I see now that they are not the same version. Will stick to getting the plugin from Github instead, seems to be more up to date.
