### ISSUE TITLE
resize twig filter not working

### ISSUE THREAD

**Issue by wearemetabolism** [timber/timber#1122]
Twig filters require the use of namespace instead of the old class

```php
$twig->addFilter(new \Twig_SimpleFilter('resize', array('Timber\ImageHelper', 'resize')));
$twig->addFilter(new \Twig_SimpleFilter('retina', array('Timber\ImageHelper', 'retina_resize')));
$twig->addFilter(new \Twig_SimpleFilter('letterbox', array('Timber\ImageHelper', 'letterbox')));
$twig->addFilter(new \Twig_SimpleFilter('tojpg', array('Timber\ImageHelper', 'img_to_jpg')));
```

The problem is also present in the test files.

I'm using Timber as a simple vendor through Bedrock

BTW thank you for this awesome plugin, it should be integrated to WP natively !

**Comment by jarednova** [comment]
@wearemetabolism — thanks for the heads-up on that! There's an alias of `Timber\ImageHelper` to `TimberImageHelper` so it should still work. Regardless, I made it so that it's now pointing at the correct namespace
