### ISSUE TITLE
Relevanssi excerpt

### ISSUE THREAD

**Issue by commercial-hippie** [timber/timber#1125]
When using the [Relevanssi search plugin](https://wordpress.org/plugins/relevanssi/) you can have it modify the excerpts displayed, and pull the excerpt from custom fields.  Pretty neat!

Unfortunately Timbers `{{ post.get_preview(40) }}` doesn't give the same excerpt, and neither does `{{ post.post_excerpt }}`, so I'm using `{{ function('get_the_excerpt', post.id) }}`.

This is not really a big bug, I just wanted to make you aware of it and have it in the tracker in-case someone searches for it in the future.  Maybe we could add it to the WIki?

Cheers,
Mike

**Comment by palmiak** [comment]
@commercial-hippie  does this this bug still exists?

If you think this can be useful create an PR with a docs proposition (guide).

**Comment by commercial-hippie** [comment]
I have no idea.. Haven't used Timer or Relevanssi in a while.  I'll close this off - at least for now if someone searches in the issue tracker they will find this :smile:

**Comment by IHIutch** [comment]
This is still a thing. I dont know enough to know why its happening, but it seems like adding `add_filter('get_the_excerpt', 'custom_excerpt', 10, 2);` doesn't get picked up by `post.preview`.

`{{ function('get_the_excerpt', post.id) }}` does still work

**Comment by YourMark** [comment]
This also seems to be the case with Timber 2.0 The highlighting of Relevanssi doesn't work when using:
`{{ post.excerpt }}`. Using the function call, as suggested bij @IHIutch does work.

**Comment by gchtr** [comment]
Thanks for your insights 👍. I’m reopening this then so we can investigate this further.

**Comment by jameelmoses** [comment]
> This also seems to be the case with Timber 2.0 The highlighting of Relevanssi doesn't work when using: `{{ post.excerpt }}`. Using the function call, as suggested bij @IHIutch does work.

Can you try `{{ post.post_excerpt }}`?

**Comment by YourMark** [comment]
Yup, `{{ post.post_excerpt }}` seems to work. 👍

**Comment by YourMark** [comment]
Unfortunately it looks like I can't use `post.post_excerpt.read_more()`. Which does work on `post.excerpt.read_more()`.  So if I want the search word highlighting, I need to create my own read more link. Which, of course, is very well doable, but it'd be a nice things to have `post.excerpt` work with the search word highlighting :-)

**Comment by gchtr** [comment]
@YourMark Does it work if you add the following filter? (This will only work for Timber 2.x).

```php
add_filter( 'timber/post/excerpt/defaults', function( $defaults ) {
	if ( ! is_search() ) {
		return $defaults;
	}

	// Allow common highlight tags in post excerpts.
	$defaults['strip'] = '<em><mark><strong><span>';

	return $defaults;
} );
```

**Comment by YourMark** [comment]
That does the trick. Thanks @gchtr

**Comment by commercial-hippie** [comment]
Not a issue, but related so I might add this here.  If you want to highlight the title as well you can do something like this:
```
{{ fn('relevanssi_highlight_terms', post.post_title, search_query) }}
```
