### ISSUE TITLE
Incompatibility with Yoast SEO on multisite / network

### ISSUE THREAD

**Issue by jordant1089** [timber/timber#1129]
There is an incompatibility issue between Timber and [Yoast SEO](https://wordpress.org/plugins/wordpress-seo/). I've made a comment on a [similar issue in their repository](https://github.com/Yoast/wordpress-seo/issues/4989). 

The issue occurs on multisite installs where both plugins are active. It occurs because when saving a post, their metabox checks if the site is a multisite and if the site has switched in the process of saving, and if it has, the saving process bails. When instantiating a Site object in Timber on a multisite, the process switches sites even if the Site object being created is for the current site. 

It seems like the issue was introduced from changes for issue #568. 
### Expected behavior

Changes made in the Yoast SEO metabox would be saved.
### Actual behavior

Changes made in the Yoast SEO metabox are not being save.
### Steps to reproduce behavior

Have Timber plugin, a timber theme, and Yoast SEO plugin active and edit a post. In the Yoast SEO metabox, make changes to the title or description. Save the post and the changes to the title or description will not be saved. 
#### Reproduction From a clean install

I was able to reproduce the issue on a clean installation of everything, in case that is any help.
1. Setup new multisite
2. Add and activate Yoast SEO and Timber plugins
3. Copy the 'timber-starter-theme' directory from the Timber plugin directory to the themes directory
4. Activate the 'My Timber Starter Theme' theme on a site
5. Create or edit a post and make changes in the SEO metabox
6. Save the post
### What version of WordPress, PHP and Timber are you using?

WordPress 4.5.3
Timber 1.1.1
Yoast SEO 3.4
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

wordpress.org download and copy to plugins directory, however in my reproduction steps, the plugin was installed via the admin plugin search.

**Comment by leonmanifesto** [comment]
Any update with this?

Seems like a pretty major issue.

**Comment by kmmathis** [comment]
I can confirm this bug. Has anyone found a way to fix this?

**Comment by kmmathis** [comment]
As a temporary fix, I literally removed lines 113 through 118 of Site.php. Not sure what the repercussions of this are, as I don't really know what this code is doing.

```php
if ( is_multisite() ) {
  $blog_ids = self::switch_to_blog($site_name_or_id);
  $this->init();
  $this->init_as_multisite($blog_ids['new']);
  return switch_to_blog($blog_ids['old']);
} 
```

**Comment by alexandernanberg** [comment]
I've created a pull request that solves this issue. #1244

**Comment by alexandernanberg** [comment]
@jordant1089 & @kmmathis Can you test with the latest release now? My pull request got merged and solved the issues I had previously.

**Comment by jordant1089** [comment]
I tested the new version and it looks like the change corrected the issue. The changes made in the Yoast SEO Metabox stayed after saving. 

Thanks for looking into and correcting the issue.

**Comment by jarednova** [comment]
Woohoo! Sounds like we're good here. Thanks again to @alexandernanberg for his fix!

**Comment by helloeliza** [comment]
timber still conflicts with my yoast settings for meta

**Comment by filnug** [comment]
I used the yoast and SEO Framework plugin and the issue still there! 
When I add a description in the meta of a page, Timber doesn't work anymore. There is no error message. But content is empty.

I have:
WordPress 4.9.2
Timber Version 1.6.0
The SEO Framework Version 3.0.3

**Comment by gchtr** [comment]
@filnug Could you please open a new issue for this? It’s hard to track issues when they are closed.
