### ISSUE TITLE
Pagination in Search Results has Trailing Slash

### ISSUE THREAD

**Issue by Samsonator** [timber/timber#1130]
### Expected behavior
We are seeing a 404 error for the pagination on the search results page. This seems to be due to a trailing slash being added so that the URL looks like this:
http://example.com/page/2/?s=searchquerystring**/**

I tracked it down to a line in plugins/timber-library/lib/Helper.php.
Inside the paginate_links function on line 518:
$link = user_trailingslashit($link);

This seems to add the trailing slash after the search query (?s=) which results in a page not found.

### What version of WordPress, PHP and Timber are you using?
WordPress 4.5.3, PHP 7.0.8, Timber 1.1.1

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Fresh install of Timber Plugin and Latest WordPress

Pagination seems to work perfectly for the blog pages but the issue appears when the code from the Timber Documentation for pagination is used on search.twig. 

Great work on Timber by the way, has completely changed how we build WordPress sites.

**Comment by jarednova** [comment]
Thanks @Samsonator — I'll take a look!

**Comment by jarednova** [comment]
@Samsonator: I have a fix in #1134; could you confirm that it solves your issue? I'd like to deploy to wp.org tomorrow; thanks!

**Comment by Samsonator** [comment]
@jarednova Hi Jared, unfortunately it seems as though the trailing slashes are still present on the "Next and "Prev" buttons but have been removed from the page numbers.

I believe it is lines: 462 and 465 in Timber.php:
`if ( isset($current) && isset($data['pages'][$current + 1]) ) {
	$data['next'] = array('link' => user_trailingslashit($data['pages'][$current + 1]['link']), 'class' => 'page-numbers next');
} `
and
`if ( isset($current) && isset($data['pages'][$current - 1]) ) {
	$data['prev'] = array('link' => user_trailingslashit($data['pages'][$current - 1]['link']), 'class' => 'page-numbers prev');
}
`

Hope that helps!

**Comment by jarednova** [comment]
Thanks @Samsonator — I just added the fix for prev/next too! The result is now in master. Thanks again for your help reporting and checking on this

**Comment by DarrenTheDev** [comment]
I've had the same issue on other templates with a query string in the URL. Would be great if this fix was generalised to remove the trailing slash whenever a query string is present.

**Comment by chetzof** [comment]
The issue is still present with custom query string 
`/properties/page/2/?area=1;100&bedroom_from=1&bedroom_to=1/`

**Comment by sbaghdadi** [comment]
I can confirm that
