### ISSUE TITLE
Getting Custom Image Sizes

### ISSUE THREAD

**Issue by ChrisSargent** [timber/timber#1132]
Hi - thanks for making this plugin, in general is making life a lot easier and certainly code cleaner!
### Expected behavior

I see this issue has been closed but now I have an issue with the edge case mentioned here: https://github.com/timber/timber/issues/438

Let's say I have some code like this:

``` html
{% set image = TimberImage(post.hero_image) %}
  <img src="{{image.src('hero')}}" alt="{{image.alt}} {{post.title}}" width="{{image.sizes.hero.width}}" height="{{image.sizes.hero.height}}"/>
```

I would expect to correctly get the image src, width and height for that given size.
### Actual behavior

I correctly get the src and the sizes for an image, so long as the corresponding size has been generated in Wordpress (i.e., if the original image is large than all the sizes).

However, if the image was a smaller image than say a custom size of 'hero' which might be e.g. 1600px, then I do not get anything for the width and height because in the array of sizes, [hero] does not exist.

I'm pretty sure the default Wordpress behaviour is to give the correct sizes.
### What version of WordPress, PHP and Timber are you using?

WordPress 4.5.3, PHP 5.4, Timber Version 1.1.1
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Upgraded to newest version via plugin updater in WordPress dashboard

**Comment by jarednova** [comment]
I'm closing out old issues. Please open a fresh issue if this is still a live issue that we should investigate — thank you!
