### ISSUE TITLE
Question: Timber::query_post() vs new TimberPost()

### ISSUE THREAD

**Issue by xavivars** [timber/timber#1136]
What are the differences between doing  `$context['post'] = new TimberPost();` and `$context['post'] = Timber::query_post()`?

I realized I'm doing each of them on different templates in my theme, and I don't have a clear reason for that, but I'm not sure if I should replace, or which one I should use...

I don't see Timber::query_post() documented as a function, but it appears on many examples. Are them just "outdated" (but still working) examples?

**Comment by twentyfortysix** [comment]
new TimberPost is a new instance of the TimberPost object/Class.
whereas TimberPost:get_post() only sends value to the static function "query_class" inside TimberPost class.

This question relates to PHP not Timber or Twig it self.
https://github.com/timber/timber/blob/master/lib/PostGetter.php
http://php.net/manual/en/language.oop5.static.php

**Comment by xavivars** [comment]
Hi @twentyfortysix, 

Thanks for your reply. I understand the difference from the syntax point of view. I'm familiar with object oriented programming. 

My question was more about what is the "actual" difference between doing those two things: does one of them give you access to some data the other one does not? Is any of the two calls preferred over the other one? 

As I said, the static method is not documented at all in Timber's documentation, but it appears many times in code examples of other Timber features' documentation. On the other hand, the instantiation of a TimberPost is documented, but it appears much less in the code examples across the documentation. That's why I was asking which one is the preferred/recommended way to go.

**Comment by Beee4life** [comment]
In my search for the same answer I came across a good explanation to this question on https://stackoverflow.com/a/48367651/8275339. Thought I'd share it for those who look for the same.

**Comment by gchtr** [comment]
The methods `Timber::query_post()` and `Timber::query_posts()` methods will be deprecated in the upcoming version 2 of Timber. As far as I know, there were no real differences between using `query_post()` or using `new Timber\Post()`.

We’re always working on making the documentation better and more complete. For version 2, there will be a separate upgrade guide that shows you all the deprecated functionalities as well as the recommended practices.

The link that @Beee4life shared shows the correct way to do it in the future. I will repeat it here for others that stumble over this issue.

**Get a single post**

```php
$post = new Timber\Post();
```

**Get a collection of posts**

```php
$post = new Timber\PostQuery();
```
