### ISSUE TITLE
Timber 1.1.2 claims not to be active

### ISSUE THREAD

**Issue by Rocketpilot** [timber/timber#1143]
### Expected behaviour

When installed or activated, I expect that Timber will register itself correctly and be available to a theme.
### Actual behavior

When installed fresh or in existing site, updating to Timber 1.1.2 makes any theme return only the following error message `Timber not activated. Make sure you activate the plugin in /wp-admin/plugins.php`
### Steps to reproduce behavior

Fresh install of current WP, fresh install of Timber 1.1.2, fresh install of timber/starter-theme 
### What version of WordPress, PHP and Timber are you using?

4.5.2 / 5.5.30 / 1.1.2 
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Via plugin updater and also tried via wp-cli

**Comment by jarednova** [comment]
@Rocketpilot — can you send me a screenshot of your plugins page?

**Comment by Rocketpilot** [comment]
@jarednova happy to, but won't be back at work computer for a while as it's a public holiday now down under. In any case this is happening on a completely stock install with only Timber running or indeed loaded. I'll try and replicate on my home machine.

**Comment by Rocketpilot** [comment]
@jarednova addendum, I ran up a test install on my home Mac, PHP version 5.6.16; the theme and the plugin work fine, so it must be something to do with my local environment. I have wp_debug etc turned on and errors **should** be logging into php.log but **aren't**, can you advise on some troubleshooting steps I could follow?

**Comment by Rocketpilot** [comment]
Further addendum: on my clean install in my work localhost environment I removed the timber-library plugin I'd already installed, activated wp native debug logging and tried re-installing via WP-CLI. The following errors were logged:

```
Activating 'timber-library'...
Backtrace from fatal error "The Twig_Autoloader class is deprecated since version 1.21 and will be removed in 2.0. Use Composer instead."
In /usr/local/zend/apache2/htdocs/testblog/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Autoloader.php [line 12]
  <unknown file> <unknown line> calling process_error()
  /usr/local/zend/apache2/htdocs/testblog/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Autoloader.php 12 calling trigger_error()
  phar:///usr/local/bin/wp/vendor/composer/ClassLoader.php 412 calling include()
  phar:///usr/local/bin/wp/vendor/composer/ClassLoader.php 301 calling Composer\Autoload\includeFile()
  <unknown file> <unknown line> calling loadClass()
  <unknown file> <unknown line> calling spl_autoload_call()
  /usr/local/zend/apache2/htdocs/testblog/wp-content/plugins/timber-library/lib/Timber.php 75 calling class_exists()
  /usr/local/zend/apache2/htdocs/testblog/wp-content/plugins/timber-library/lib/Timber.php 56 calling test_compatibility()
  /usr/local/zend/apache2/htdocs/testblog/wp-content/plugins/timber-library/timber.php 21 calling __construct()
  /usr/local/zend/apache2/htdocs/testblog/wp-admin/includes/plugin.php 552 calling include_once()
  phar:///usr/local/bin/wp/php/commands/plugin.php 182 calling activate_plugin()
  phar:///usr/local/bin/wp/php/WP_CLI/CommandWithUpgrade.php 163 calling activate()
  phar:///usr/local/bin/wp/php/commands/plugin.php 445 calling install()
  <unknown file> <unknown line> calling install()
  phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php 52 calling call_user_func()
  <unknown file> <unknown line> calling WP_CLI\Dispatcher\{closure}()
  phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php 294 calling call_user_func()
  phar:///usr/local/bin/wp/php/WP_CLI/Runner.php 313 calling invoke()
  phar:///usr/local/bin/wp/php/WP_CLI/Runner.php 320 calling run_command()
  phar:///usr/local/bin/wp/php/WP_CLI/Runner.php 723 calling _run_command()
  phar:///usr/local/bin/wp/php/wp-cli.php 21 calling start()
  phar:///usr/local/bin/wp/php/boot-phar.php 5 calling include()
  /usr/local/bin/wp 4 calling include()
```

**Comment by jarednova** [comment]
Thanks @Rocketpilot — I assume that's with the current version of Timber? (v 1.1.2)?

**Comment by Rocketpilot** [comment]
@jarednova indeed! About to show the plugin screen as requested...

**Comment by Rocketpilot** [comment]
Dropbox link to screengrab https://www.dropbox.com/s/vbe6zazjop7ecc9/Screenshot%202016-08-11%2010.22.49.png?dl=0

**Comment by Rocketpilot** [comment]
I can confirm 1.1.3 also fails to run on my local development environment. It does work in my org's staging environment but that continues to make development difficult. Version 1.0.3 does work, however, so I have reverted to that for my active projects.

**Comment by drieschel** [comment]
I also have problems running version 1.1.3: The composer autoloading doesn't seem to work correctly, because it can't find the Timber classes (Maybe some namespace related changes?). Is there some news?

**Comment by Rocketpilot** [comment]
@drieschel could you document briefly how you fixed the problem? In my case it seems very specific to my local development environment's PHP version as I've deployed 1.1.3 elsewhere without issue.

**Comment by jarednova** [comment]
@drieschel You are correct that loading behaviors changed. In 1.0 this was the introduction of namespaces and in 1.1 this was removing autoloading for composer. This is documented in readme.txt, but is there a standard documentation format or location that would help publicize these changes better?

The thing is these changes _shouldn't_ cause the issues that @Rocketpilot is having as the distributed wp.org version includes autoloading (see `bin/timber.php`)

**Comment by drieschel** [comment]
@jarednova You could mention it in the upgrade guide (https://github.com/timber/timber/wiki/1.0-Upgrade-Guide). I also didn't realize that I have to instantiate a Timber object in the functions php additional to a Site inherited object. I probably don't need the Site inherited one anymore, because I don't have a multi site but it's working fine (using it for the default functions.php stuff).

**Comment by Rocketpilot** [comment]
Addendum that I've updated to the latest version of WP and Timber and also my Zend environment to PHP 5.6.23 and still having the same issues even on my completely vanilla local test installation. Very perplexing.

**Comment by parljohn** [comment]
Didn't really see a resolution to this issue.  I'm having the same problem.  I'm on a mac with php 5.6, installed a fresh copy of WP 4.7.3 and simply added the Timber plugin and upgraded it to 1.2.4.  Copied the timber-starter-theme to themes folder and all I get is Timber not activated error.  Not sure why autoloading is not working out of the box here or how to fix it?  Any help?  Running composer install and update are no help.  Functions.php file has the added autoload requirement.  
P.S.  If I walk through files and include USE statements in each file where classes are being used then it starts to work.  In some cases I have to alias to get it to work ie "use Timber\Menu as TimberMenu" but this is a worm hole and just keeps crashing down the line.  Also, I have tried using the same set of code that is working on Bluehost server with PHP 5.4, no beuno.  Any thoughts?

**Comment by Rocketpilot** [comment]
I've more or less worked around the issue on my existing theme and new ones don't appear to present the same challenges, but I continue to be dismayed by how thin the documentation is around this transition.
