### ISSUE TITLE
Clean up dependencies before release

### ISSUE THREAD

**Issue by szepeviktor** [timber/timber#1147]
Would it be possible to remove all files (tests, docs etc.) from the `vendor` directory during the plugin release process?

**Comment by jarednova** [comment]
I'd certainly love it. No reason tests, docs, etc. need to be there for all the dependencies in a production environment. Are you referring to the WP.org release?

**Comment by szepeviktor** [comment]
Yes.

**Comment by szepeviktor** [comment]
It is normal to have these files for a Laravel project as `/vendor` is above the document root. But WP sadly live on the public web.
