### ISSUE TITLE
Timber 1.1.2: get_post cannot handle post classmap array

### ISSUE THREAD

**Issue by vilpersson** [timber/timber#1149]
In Timber 1.1.2 you can't use classmap array when retrieving single post:
```
	Timber\Timber::get_post(1, array(
		'portfolio' => 'MyPortfolioClass',
		'alert'     => 'MyAlertClass'
	));
```
This gives you an error:
```
Fatal error: Class name must be a valid object or a string in /srv/www/xxxx.com/current/web/app/plugins/timber-library/lib/PostGetter.php on line 18
```

Mapping post types to classes worked previously also with `get_post` method. New behavior was introduced in this pull request: https://github.com/timber/timber/pull/1123

Classmapping is a superb feature, I can create appropriate classes for every post type. Now I have to know the post type of a post before querying it.

By the way, it would be very cool if I could map all classes with filters instead of overwriting class variables and using method parameters.

**Comment by jarednova** [comment]
closed by #1155
