### ISSUE TITLE
Sideloading files with uppercase extensions downloads file each view

### ISSUE THREAD

**Issue by haroldangenent** [timber/timber#1150]
### Expected behavior

When sideloading an image, it should be downloaded once and served from this location each consecutive time.
### Actual behavior

When using an image with an uppercase extension, it is downloaded _each page view_. This easily results in hundreds of images after only a few days.

_Quick fix for two issues, not recommended in production: https://github.com/timber/timber/issues/1098#issuecomment-233343096._
### Steps to reproduce behavior
1. Use resize on an external image with a uppercase extension;
2. Refresh;
3. One condition: The file system you're using _should be case-sensitive_.
#### Futher explanation and possible fix

See https://github.com/timber/timber/issues/829#issuecomment-229657744. Sorry to file a new issue, but this seems worthwhile to fix and the other issue was closed already.
### What version of WordPress, PHP and Timber are you using?

WordPress 4.5.3, PHP 7.0, Timber 1.1.2.
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

`timber/timber`, via Composer.

**Comment by Kwapi** [comment]
Any news on this? I'd be interested in a production-ready solution

**Comment by jarednova** [comment]
I'm closing out old issues. Please open a fresh issue if this is still a live issue that we should investigate — thank you!

**Comment by gchtr** [comment]
I’m reopening this so I can tackle it with the following todos:

- [ ] Add tests to confirm behavior.
- [ ] Add a fix.

I already worked on #1098 and feel like this is not too hard to fix.

**Comment by Levdbas** [comment]
Going to close this ticket since it's already pretty old. I did add this to a new ticket to catch PRs and tickets regarding Image handling.
