### ISSUE TITLE
Using Timber starter theme with Events Calendar Pro

### ISSUE THREAD

**Issue by codeforte** [timber/timber#1151]
I'm very new to Timber/Twig, but my company has started using it. In order to learn it better, I'm doing a side project that uses Events Calendar Pro. Right now, I just have a local MAMP Pro install running. I would've expected to create a "tribe-events" folder and a default-template.php in the starter theme folder, then create a twig file that incorporates the ECP functions from their default-template.php.

But, this did not work. It kept loading the default page.php/page.twig files.

I ended up modifying the page.php: Timber::render( array( 'page-' . $post->post_type . '.twig', 'page-' . $post->post_name . '.twig', 'page.twig' ), $context );

Then, I created a page-tribe_events.twig and used the Timber syntax for ECP's functions {{function('blah_blah')}}. And, this worked for the Month and List views. But, if I try to switch to the Day, Week, Map, or Photo views, I get the 404.twig.

This is a fresh install of WP, Timber, ECP, using all the latest versions.

I noticed the Timber docs have some info on integrating with WooCommerce, and I've already had good success working with Advanced Custom Fields, but any insight on a proper workflow to get Timber working with Events Calendar Pro would be greatly appreciated!

**Comment by chetzof** [comment]
I remember having a  problem with this plugin, turned out that timber is not calling all the necessary functions and hooks that plugins rely on. I think it was `get_header()` that was missing, but I may be wrong.

Make sure you've implemented this https://github.com/timber/starter-theme/blob/master/header.php
