### ISSUE TITLE
Use of "cat" makes the Timber query goes nuts

### ISSUE THREAD

**Issue by twentyfortysix** [timber/timber#1152]
### Expected behavior
I run this query in the index on the blog page:
```
$args = array(
			'post_type' => 'post',
			'posts_per_page' => 1,
			'post_status' => 'publish',
			'cat' => 88
		);
$data['zpravodajstvi'] = Timber::get_posts($args);
```

What I expect to see is 1 most recent post from category with id 88. Instead I got 10 latest posts without category preference (seams like the use of "cat" completely ruins the call, and the default is used instead).

On the contrary if  use this:
```
$args = array(
			'post_type' => 'post',
			'posts_per_page' => 1,
			'post_status' => 'publish',
			'tax_query' => array(
				array(
					'taxonomy' => 'category',
					'field'    => 'term_id',
					'terms'    => array(88),
				),
			),
		);
$data['zpravodajstvi'] = Timber::get_posts($args);
```

I receive 1 recent post from desired category

### What version of WordPress, PHP and Timber are you using?
WordPress 4.5.3,PHP Version => 5.6.20, Timber 1.1.2

**Comment by connorjburton** [comment]
#951 may be related, although at a quick glance, I experienced the opposite.

**Comment by twentyfortysix** [comment]
confirmed
`'category' => 88 `
works

**Comment by jarednova** [comment]
@twentyfortysix @connorjburton weird! I'm taking a look at this now.....

**Comment by connorjburton** [comment]
@jarednova it's an inconsistency in Wordpress core, I was amazed when I figured it out, I can't think of a good reason they accept different parameters for the same thing.

**Comment by jarednova** [comment]
Wow, that is maddingly stupid. I've got PR #1157 to fix this
