### ISSUE TITLE
Checking TimberPost.thumbnail against NULL in template prints warning message

### ISSUE THREAD

**Issue by paoloposo** [timber/timber#1154]
### Problem
When trying to check whether `post` (which is an instance of `TimberPost`) has a featured image / thumbnail, a warning is displayed on the site:

> Warning: preg_match(): Null byte in regex in {wordpress_dir}\wp-includes\functions.php on line 4948

My twig looks like this:

	{% if post.thumbnail is not null %}
		<div class="img-container post-image">
			<img src="{{ post.thumbnail.src }}">
		</div>
	{% endif %}

The warning is thrown by the conditional tag, where it says `post.thumbnail is not null`. The same goes, btw, for `post.thumbnail != null`. Two interesting things to notice:

0. This happened all of a sudden. The code above is in place for quite a while now and worked just fine, until today. I have no idea what could have caused this.
0. I can still access the thumbnail's attributes, like the image url, as shown above. When dumping `post.thumbnail`, it reveals that it's a `Timber\Image Object`.

The natural question: Why does this warning show and how do i get rid of it?

### What version of WordPress, PHP and Timber are you using?
Wordpress 4.5.3, PHP 7.0 (Windows), Timber 1.1.2

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Plugin manager within self-hosted site

**Comment by jarednova** [comment]
hmmmm, thanks for the note @paoloposo. I'll take a look. The code for thumbnails hasn't changed in quite a bit — I wonder if this might have to do with a new WP version? The warning comes from WP core, not Timber

**Comment by paoloposo** [comment]
The issue resolved itself in the meantime. I literally didn't do anything. When I got back to work, the warning didn't show anymore. As you said, must have been a problem in the core.
