### ISSUE TITLE
Create a new (or extend) the post.author objects

### ISSUE THREAD

**Issue by stacyk** [timber/timber#1158]
Hi there, 
My client is using the Co Authors Plus plugin and the author displayed via the post.author is often incorrect. I have tried many things but perhaps have implemented them incorrectly.

Here are a few things I have tried: 

1. Extending a Timber Object (which is the most confusing to me, but I think that is what I need). I followed the [Wiki](https://github.com/timber/timber/wiki/TimberPost) and [this issue](https://github.com/timber/timber/issues/766) and it didn't work for me (I know, not very specific). 

I used something [similar to this](https://github.com/jp1971/jp1971.com/blob/master/themes/_krnl/functions/timber.php) but I'm not sure if that needs something additional to get it to work. I called it in my functions.php file like this theme did: 
```
add_action( 'wp_loaded', function() {
  require_once( __DIR__ . '/inc/coauthors.php' );
  }, 11 );
```

I also tried following this [closed issue](https://github.com/timber/timber/issues/747) but had trouble with the next steps after creating this in my functions file. Do I then add a new context? 

Lastly, I tried [something similar to this](https://github.com/svn2github/wordpress-vip-plugins/blob/424a2a0d9f3540d1d430bbc9acbd35663e2c564f/facebook-instant-articles-3.0/compat/class-instant-articles-co-authors-plus.php) but again, wasn't sure if I haven't filtered it correctly, or added it to a context or what not.

Any help would be greatly appreciated.

**Comment by stacyk** [comment]
I am able to get the correct author's posts to show up on the author.php archive, but I think my issue is using {{ post.author.name }}. It is querying the correct posts, but then when it tries to display the author name using that format I can't seem to override that.

**Comment by jarednova** [comment]
@stacyk building you a fix now!

**Comment by jarednova** [comment]
@stacyk — I've begun work on a `{{ post.authors }}` method you could use. I'd love your feedback on #1171

**Comment by jarednova** [comment]
@stacyk if you wanted to jumpstart this for the project you're working on...

```php

class StacyPost extends TimberPost {

    function authors() {
        $authors = array();
        $authors[] = new Timber\User($this->post_author);
        $cauthors = get_coauthors( $post->ID );
	foreach($cauthors as $author){
		$authors[] = new \Timber\User($author);
	}
	return $authors;
    }
}
```

You could use it in your templates like so...

```twig
This post is by
{% for author in post.authors %}
    <a href="{{author.link}}">{{author.name}}</a>, 
{% endfor %}
```

**Comment by stacyk** [comment]
Hi @jarednova. Thank you so much for checking into this issue and providing these snippets. I have added everything and this is what I notice:

1. On my single page it now displays the original author and the person who was reassigned as the only author via the Co Authors Plus plugin. However, the original author shouldn't be listed anymore. Not sure if it is grabbing the original WP author and the co-authors plus data? If so, any suggestions of how to only show the co-authors-plus author?

2. I was able to get this to display on the single, but not on any of the archive pages... the swig templates I assume are the same, but would I need something different than just `$context['post'] = new StacyPost();` in my index.php? Currently I have:

```
$context = Timber::get_context();
$context['posts'] = Timber::get_posts();
$context['pagination'] = Timber::get_pagination();
$context['post'] = new TropPost();

$templates = array( 'index.twig' );

if ( is_home() ) {
  array_unshift( $templates, 'home.twig' );
}

if ( is_category() ) {
  array_unshift( $templates, 'category.twig' );
}

Timber::render( $templates, $context );
```

**Comment by jarednova** [comment]
@stacyk — almost there! The only other tweak you need is to use your `TropPost`s on the archive page...

```php
$context['posts'] = Timber::get_posts(false, 'TropPost');
```

... this will take resulting posts from Timber::get_posts and treat them as `TropPost`s, as for the original author being included, here's the modification to make...

```
class TropPost extends TimberPost {

    function authors() {
        $authors = array();
        $cauthors = get_coauthors( $this->ID );
        foreach($cauthors as $author){
                $authors[] = new \Timber\User($author);
        }
        return $authors;
    }
}
```

**Comment by stacyk** [comment]
You are my hero!!!! Thank you so much. Closing :)

**Comment by jarednova** [comment]
🎉 !!!
