### ISSUE TITLE
Shiny Updates Visual Bug

### ISSUE THREAD

**Issue by Daronspence** [timber/timber#1160]
### Expected behavior

The info should be in one line. I expect this is due to how 4.6 parses the info for shiny updates

### Actual behavior

![screen shot 2016-08-17 at 3 23 24 pm](https://cloud.githubusercontent.com/assets/4062087/17751890/dacf66fa-648e-11e6-8463-d15f49c5f690.png)

### Steps to reproduce behavior

Upgrade to WP 4.6, then rollback the timber version number manually to force an update to show.

### What version of WordPress, PHP and Timber are you using?

WordPress 4.6

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Plugin

**Comment by jarednova** [comment]
Closed by #1167
