### ISSUE TITLE
PHP Strict Error when setting template locations via Timber::$locations

### ISSUE THREAD

**Issue by portalzine** [timber/timber#1162]
Hi, 
PHP Throws an error ("Only variables should be passed by reference"), when setting Timber::$locations. 

Example:

```
Timber::$locations = array('my/template/location/views/'
);
```

Thanks
Alex

**Comment by jarednova** [comment]
@portalzine can you copy-and-paste the full error? (hopefully including a line number?) I'm not able to replicate yet....
