### ISSUE TITLE
Custom headers for different page templates. 

### ISSUE THREAD

**Issue by squibbleFish** [timber/timber#1163]
I suspect that the answer will be in using content blocks, but I wanted to get an idea from your team first. We are currently evaluating moving to Timber as a plugin as we have too many theme files to migrate at this time. So we want to start on a template by template basis. 

My question is about dynamic headers in Timber and in Wordpress. Normally, in the Wordpress template architecture, you can create many header.php files that follow the `{slug}-header.php` guideline. Then in your template file you would call `get_header('slug')` to load your specific header you want. While Timber allows me to call `{{ wp_head }}` and it works to pull the main header file, I am wondering if there is a good way to call dynamic header files in the same fashion without needing to rewrite these on a case by case situation, until we are fully integrated. 

I think I have a good solution, but I feel like there might be a cleaner way that I am missing. In my twig file I call `{{ function( 'get_header', 'slug' ) }}`

This is only a question for clarification. So far, love the plugin and love the work and support your team have put into it.

**Comment by twentyfortysix** [comment]
What if you specify the header in the base.twig
```
{% block head %}
<title>general head</title>
{{wp_head}}
{% endblock %}
```

and in what ever template you want to overwrite the base header by new one, for example in the archive.twig you would do:
```
{% block head %}
<title>archive head</title>
{{wp_head}}
{% endblock %}
```
This will overwrote the block head with the newly specified header content.
http://twig.sensiolabs.org/doc/functions/index.html

this way you can define what ever head (any content part) you like in what ever situation you like.

**Comment by juliekllimentova** [comment]
Hey, awesome, that sorted out my issue too. Thanks a lot!

**Comment by palmiak** [comment]
@squibbleFish I see that this issue is resolved - Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
