### ISSUE TITLE
[BUG] \Timber\TermGetter wrong default $TermClass

### ISSUE THREAD

**Issue by ogrosko** [timber/timber#1164]
Using \Timber\Term class I'm getting following error:
`Fatal error: Class 'Term' not found in /wp-content/plugins/timber-library/lib/TermGetter.php on line 82`

When I change default $TermClass from `Term` to `\Timber\Term` in `\Timber\TermGetter`

`public static function get_term( $term, $taxonomy, $TermClass = 'Term' )` -> `public static function get_term( $term, $taxonomy, $TermClass = '\Timber\Term' )`

and 

`public static function get_terms( $args = null, $maybe_args = array(), $TermClass = 'Term' )` -> `public static function get_terms( $args = null, $maybe_args = array(), $TermClass = '\Timber\Term' )`

it works

WordPress 4.5.3, PHP 5.6, Timber 1.1.3

**Comment by jarednova** [comment]
Closed by #1165
