### ISSUE TITLE
How do I display a 'sticky' post as the first entry in a list of posts with a specific category?

### ISSUE THREAD

**Issue by doifeellucky** [timber/timber#1177]
### Expected behavior

I have posts for 'news' and 'case studies' and would like to be able to have a 'sticky' 'case study' so that it is at the top of the list instead of by most recently added.  I can see no mention in the documentation relating to 'sticky' posts so don't know how this can be achieved.  I've tried using a 'sticky' category which is fine, except I then see duplicated entries as I'm just showing a list of sticky's (only one) and then a list of case studies.  I guess I want to show a list of sticky's and then a list of case studies, but not those case studies that also have the sticky category.  I'm a designer so this is a bit beyond me.  Also I'm using a %category%/%postname%/ in the permalink so my url is either 'case-studies' or 'news' then the post name, however where I've added a 'sticky' category to the case study the URL is 'sticky' and not the required 'case-study'.  Is there a way to specify this?  Thanks in advance.  Loz.

### Steps to reproduce behavior, this is fine, just don't know what to do to solve my issue.

`{% for post in stories %}
	<article>
		<h3><a href="{{post.link}}">{{post.post_title}}</a></h3>
		<div class="news medium-3 columns">	
			<img src="{{post.thumbnail.src|resize(300, 200)}}" />
		</div>
		<div class="news medium-9 columns">
			<p>{{post.get_preview(20)}}</p>
		</div>
	</article>
{% endfor %}`

### What version of WordPress, PHP and Timber are you using?
WordPress 4.4.2, PHP not sure, Timber 0.22.5

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Via GitHub

**Comment by doifeellucky** [comment]
I'm using advanced custom fields so if using that and having a 'feature' field is a better way of doing it I'm happy to do that instead of using categories.

**Comment by jarednova** [comment]
Hey @doifeellucky — this feels like a WP_Query problem more than a Timber issue. Everything we use is just based on the defaults from WP_Query. That said, here's a stab based on what you describe...

```php
$cat_id = 9; //whatever your "sticky" category ID is
$sticky_case_studies = Timber::get_posts(array('post_type' => 'case-study', 'category__in' => array($cat_id));
$regular_case_studies = Timber::get_posts(array('post_type' => 'case-study', 'category__not_in' => array($cat_id));
$context = Timber::get_context();
$context['posts'] = array_merge($sticky_case_studies, $regular_case_studies);
Timber::render('archive.twig', $context);
```

**Comment by doifeellucky** [comment]
Thanks very much.  I'll give this a try.
