### ISSUE TITLE
Timber 1.1.4 breaks API compatibility

### ISSUE THREAD

**Issue by mahagr** [timber/timber#1178]
### Expected behavior

Public API should not change on bugfix releases.
### Actual behavior

Public API change causes Gantry to break: https://github.com/gantry/gantry5/issues/1542
### Steps to reproduce behavior

Install Gantry and upgrade Timber from 1.1.3 to 1.1.4
### What version of WordPress, PHP and Timber are you using?

WordPress 4.6, PHP 7, Timber 1.1.4, Gantry 5.3.4
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Upgraded to newest version by using manual update

**Comment by mahagr** [comment]
One way to fix this would be to add a new function(s)/attribute which allows both `\Twig_Loader_Filesystem` and `\Twig_Loader_Chain` to be returned.

**Comment by mahagr** [comment]
We have changed (and released) a change in Gantry 5.3.5 that creates a new `\Twig_Loader_Filesystem` class and includes it into the chain if the loader is a chain. This will mostly fix the issue for having a chain, though it would be better if there was a mechanism to get instance of `\Twig_Loader_Filesystem` so I wouldn't need to do that.

We use filesystem loader to add extra namespaces, which isn't supported by Timber.

**Comment by palmiak** [comment]
@mahagr Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread

**Comment by mahagr** [comment]
I've worked around the issue, it was API change which could be adjusted by moving from TImber plugin to Timber composer dependency and handling the issue with a new release.
