### ISSUE TITLE
Timber and ACF Live Edit

### ISSUE THREAD

**Issue by ghost** [timber/timber#1179]
I use ACF Live edit plugin. https://wordpress.org/plugins/live-edit/
This plugin hase live_edit(); function, with some parameters of ACF Fields etc. live_edit('field_name1, field_name2, etc');

Hove I send live_edit('field_name1'); to .twig file and display?

**Comment by alicam** [comment]
Last updated 2 years ago? I think Elliott has abandoned it!

**Comment by palmiak** [comment]
I'm closing this - issue author became a ghost, plugin is abandoned.
