### ISSUE TITLE
Composer version of Timber won't retrieve data from ACF Repeaters (plugin version works fine)

### ISSUE THREAD

**Issue by fewerflatlands** [timber/timber#1181]
### Expected behavior
Trying to iterate over data from ACF Repeater fields using the orthodox syntax eg. `{% for item in post.get_field('products') %}`
It wasn't working with Timber installed via Composer, so I removed the Composer version and its dependencies and installed the plugin instead, and it all works fine.
Other ACF fields are not affected as far as I can see.

### Actual behavior
With the Composer version installed, `dump(post.products)` gives `string '3' (length=1)`.
With the plugin installed, the dump gives all the data.

### Steps to reproduce behavior
For example, create an ACF text field called `summary` and a Repeater called `products` with one text sub-field `title`, and assign to regular WP Pages.

 `page.php`
```
<?php
$data = \Timber\Timber::get_context();
$post = new \Timber\Post();
$data['post'] = $post;
\Timber\Timber::render('page.twig', $data);
```

`page.twig`
```
{% block content %}
	<main>
		<h1>{{ post.title }}</h1>
		{{ post.summary }}
		{% for item in post.get_field('products') %}
			<p>{{ item.title }}</p>
		{% endfor %}
	</main>
{% endblock %}
```

### What version of WordPress, PHP and Timber are you using?
WordPress 4.6, PHP 5.5.9, Timber 1.1.3 or 1.1.4

**Comment by mahagr** [comment]
Try initializing Timber in `functions.php` by calling `$timber = new \Timber\Timber();`.

That's the only thing what plugin does besides initializing autoloader..

**Comment by fewerflatlands** [comment]
This does indeed solve the problem – missed this in the documentation. Thanks for the quick answer and apologies for the wasted time.

**Comment by mahagr** [comment]
We're on the same boat on this one. Took me some time to figure it out.
