### ISSUE TITLE
Template locations priority

### ISSUE THREAD

**Issue by jusstinas** [timber/timber#1184]
Seems like from version 1.1.\* it's impossible to add template location and keep priority if location is in WP template dir. LocationManager method get_locations move theme locations to the end of array. I think if user set custom locations he done that by priority.

**Comment by palmiak** [comment]
@jusstinas Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread

**Comment by jusstinas** [comment]
@palmiak  This issue can be closed.
