### ISSUE TITLE
get_widgets misconception - documentation

### ISSUE THREAD

**Issue by twentyfortysix** [timber/timber#1187]
Hello,
I noticed one misconception in docs both, the docs here on Github (which I corrected) and the official docs 
http://timber.github.io/timber/#get_widgets

the function get_widgets is defined like so:
`get_widgets( mixed $widget_id )`

What it says is that you have to pass there the widget ID, which is nonsense, as the widget ID is almost uncatchable and "unstable". What you/we really ask for is the sidebar ID and its content (its widgets).

Technically there is nothing to fix, but conceptually it is misleading.

I think the function should be named get_sidebar_widgets, or at least it should be stated that what we are asked for is not widget ID but the **Sidebar ID**.

`get_widgets( mixed $sidebar_id )`

**Comment by gchtr** [comment]
I’m going to close this old issue. A pull request would be great if this is still an issue that should be solved.

**Comment by twentyfortysix** [comment]
I think it is solved .. at least the Doc for T2
 says widget_id means sidebar id
 
`$widget_id | int or string | Optional. Index, name or ID of dynamic sidebar. Default 1.`

 https://timber.github.io/docs/v2/reference/timber-timber/#get_widgets
