### ISSUE TITLE
resize() in loop with if-clause breaks theme

### ISSUE THREAD

**Issue by SlawaGurevich** [timber/timber#1191]
Hi Guys,

I have a strange problem with a loop in combination with an if-statement.

I have a loop, in which every picture is resized with the |resize()-function. It should resize the images and render them into the template.

However, when I include it in the template and reload the page, the whole theme breaks. Only the header is loaded and the Wordpress admin-topbar is also gone.

Part of the template file

``` twig
{% for category in categories %}
    <div class="category-title large-12 small-12 columns">
        {{ category.name }}
    </div>
    {% for post in category.get_posts('posts_per_page=4') %}
        {% include 'post.twig' %}
    {% endfor %}    
{% endfor %}

```

post.twig

``` twig
<div class="large-6 small-12 columns post-outer {% if loop.index == loop.length %} end {% endif %}">
    <div class="frontpage-post">
        <div class="post-image">
            <a href="{{ post.link }}">
                <img src="{{ post.thumbnail.src|resize(600, 400, 'center') }}" alt="{{ post.title }}" class="post-image">
            </a>
        </div>
        <div class="post-content">
            <h3 class="post-title"><a href="{{ post.link }}">{{ post.title }}</a></h3>
            <h5 class="post-date-user">
                <b>{{ post.author }}</b> - {{ post.date|date("j. M, Y") }}
            </h5>
            {% if loop.index == 1 %}
            <p class="post-excerpt">
                {{ post.post_excerpt }}
            </p>
            {% endif %}
        </div>
    </div>
</div>
```

If I remove either `<div class="large-6 small-12 columns post-outer {% if loop.index == loop.length %} end {% endif %}">` or `post.thumbnail.src|resize(600, 400, 'center') }}` everything works fine.

Any ideas?

WordPress 4.5.3
Timber 1.1.5 (installed Timber with the Wordpress Plugin manager)

**Comment by luukdv** [comment]
I'm not seeing any obvious faults in the code above, what error does your `wp-content/debug.log` give?

**Comment by jarednova** [comment]
I'm closing out old issues. Please open a fresh issue if this is still a live issue that we should investigate — thank you!
