### ISSUE TITLE
Timber throw exception when trying to convert TIFF to JPEG

### ISSUE THREAD

**Issue by chrisgherbert** [timber/timber#1192]
### Expected behavior

Timber is able to handle the same image formats that WordPress can, including TIFF. 
### Actual behavior

Timber throws an exception when a trying to convert a TIFF to JPG using the |tojpg filter.  I can understand not being able to do the conversion (not sure if PHP-GD can even do this), but an throwing exception seems like an extreme reaction.
### Steps to reproduce behavior

User uploads a TIFF file (terrible idea, but clients do it), and the site throws an exception when it attempts to convert the image to jpeg in a template.
### What version of WordPress, PHP and Timber are you using?

WordPress 4.6.1, PHP 7, Timber 1.1.5
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Loaded from Composer

**Comment by jarednova** [comment]
Tiffs? Those bastards. Is this something you could look into submitting a PR for? I agree that if WP does it, Timber should too. Hopefully it could follow the same conventions as the PNG tools

**Comment by chrisgherbert** [comment]
I'll check out the offending code and see if I'm comfortable enough with it to submit a PR.

**Comment by codesman** [comment]
@chrisgherbert , I did a little digging into this and I found that `gd` is not capable of converting tiff->jpg(or anything else). ` ImageMagick` is required to do this in PHP.

According to [the codex](https://codex.wordpress.org/Uploading_Files) `.tiff` is not a supported upload format, even though by default they are allowed to be uploaded. A common solution to the problem of users uploading .tiffs is to [remove .tiff from the allowed mimetypes](http://wordpress.stackexchange.com/questions/4142/how-can-i-prevent-uploading-bmp-image) and force the user to convert to a supported format before uploading. 

AFAIK, WordPress core does not do any format conversion (are there official WP themes that convert tiff->jpg in the view?).  Unless Timber adds `ImageMagick` as a dependency & implements it in the `tojpg` filter, it seems that an exception should be thrown to let us know that if we are going to let our users upload unsupported filetypes, that we should handle it and make sure we're not trying to convert an image that cannot be converted.

Perhaps you could check the filetype in your theme and only pass it to `tojpg` if it's a supported format?

I suppose another option would be for Timber to check and see if the filetype is tiff and if it is, do no conversion and return the original tiff, but that seems like a wrong behavior for a `tojpg` filter.

I'm not seeing a clean way to handle this. What do you think?

**Comment by chrisgherbert** [comment]
Uploading a tiff is something that would likely happen in response to an end-user action, rather than a developer's action.  If the site is correctly setup for production, the user wouldn't even see the error, so throwing an exception seems like a pretty harsh reaction.

Also, I don't think it throws an exception when you attempt to resize an SVG, which is equally unable to be resized.

**Comment by jarednova** [comment]
Closed by #1383
