### ISSUE TITLE
Post Pagination

### ISSUE THREAD

**Issue by corradomatt** [timber/timber#1194]
### Expected behavior

I would expect there to be something within the standard post object that handles paginated posts...or a method that can do that for us.
### Actual behavior

I don't see anything in the code for this functionality but maybe I'm blind.
### What version of WordPress, PHP and Timber are you using?

WordPress 4.6.1, PHP 5.6, Timber 1.1.6
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Composer

Sorry if this isn't the place for this type of question but I didn't see a forum or anywhere for support besides the issue tracker here. (I love Timber/Twig BTW...thanks!)

**Comment by corradomatt** [comment]
Oh, by pagination in the post...I'm referring to what you would get with `<!––nextpage––>` -- usually I would use `wp_link_pages();`

**Comment by corradomatt** [comment]
It appears I've duplicated this issue - #133

Should I leave this open as the other is closed?

**Comment by terrarum** [comment]
I had the same problem, I found issue #529 which explains how paging in multipage posts works.

**Comment by corradomatt** [comment]
Thanks @terrarum - I guess I should have closed this issue a while ago considering there is already an option issue for it on #529

**Comment by synapticism** [comment]
Post pagination seems to have been added to Timber since then. Here's a little blob of template code that may be of help to anyone trying to puzzle this one out nowadays.

```twig
{% if post.pagination %}
  <nav>Pages:
    {% for page in post.pagination.pages %}
      {% if page.current %}
        <span class="current">{{ page.title }}</span>{{ loop.last ? '' : ', ' }}
      {% else %}
        <a href="{{ page.link }}">{{ page.title }}</a>{{ loop.last ? '' : ', ' }}
      {% endif %}
    {% endfor %}
  </nav>
{% endif %}
```

**Comment by gchtr** [comment]
@CamelKing Did you try to follow the [Pagination Guide](https://timber.github.io/docs/guides/pagination/) yet?

**Comment by CamelKing** [comment]
@gchtr yes I did, and it works, for posts (as in for the index page with many posts and you need to paginate it).

However, for post with  which need to be paginated, the pagination property of the post object is always an empty array. Normally (without Timber/Twig) I would use wp_link_pages() to display the pages' links. In Timber case, I was expecting the pagination property within the post object would have been setup, but it has always been an empty array.

**Comment by CamelKing** [comment]
@gchtr , I have been looking at a few places ... I noticed the followings in the code:

File: test-timber-post.php
Function: testPagedContent()
Line: 404
>
> $this->go_to( get_permalink( $post_id ) );
> 
> // @todo The below should work magically when the iterators are merged
> setup_postdata( get_post( $post_id ) );
> 
> $post = Timber::get_post();
> $this->assertEquals( $page1, trim( strip_tags( $post->paged_content() ) ) );
>

This function made a call to setup_postdata(), which is the only place that will setup the $multipage global variables. Reading the @todo in the code, thinking may be something was bypassed in the testing? As it is now, $multipage will always be false, and as such, no **Pagination property** will be setup within the **Post object**.

Not sure if this is the issue.

**Comment by CamelKing** [comment]
@gchtr, just a follow up, I made a small change to the post.php as per followings:

> public function pagination() {
> 		global $post, $page, $numpages, $multipage;
> 		$post = $this;
> 		setup_postdata(get_post($this));  /* <<--- added this line to setup global vars for post */
> 		$ret = array(); 

This fixed the pagination issue I have with post (not query) that has ' tag in them, and the call to setup_postdata() sets up all global variables for posts accordingly, including the all important $multipage, which will allow this function (pagination) to run through the tags and setup the pagination object correctly.

As I am new to wordpress, php and timber as a whole, I am not sure if this is the right fix to the problem, or if there is any side effect (such as performance hit), I guess I will leave it for you guys to explore if this is the right thing to do.

**Comment by CamelKing** [comment]
@gchtr any comments?

**Comment by juliankoehn** [comment]
@CamelKing using it in my extends class, thanks!

additional: i added 

```
if ($page == 0)
			$page = 1;
```
to the content() function, page = 0 returns the entire content without paginating so it should default to 1. Has no tested side effect on the normal Post Pages.

**Comment by gchtr** [comment]
> However, for post with which need to be paginated, the pagination property of the post object is always an empty array. Normally (without Timber/Twig) I would use wp_link_pages() to display the pages' links. In Timber case, I was expecting the pagination property within the post object would have been setup, but it has always been an empty array.

@CamelKing Sorry for the late reply. I’m trying to improve documentation for the different types of pagination in #2295. Here you can find the draft documentation for paged content in posts: https://github.com/timber/timber/blob/2.x-docs-pagination/docs/v2/guides/pagination.md#paged-content-for-posts. The documentation for paged content should apply to Timber v1 as well, even though this will be added to 2.x.

I tested it with the Starter Theme and the current version of Timber (1.17.0) and it seems to work fine without having to use `setup_postdata()`. If it’s still an issue for you, I’d be glad if you could open a new issue so we can have look at it separately.
