### ISSUE TITLE
ACF with Timber::get_posts

### ISSUE THREAD

**Issue by hatzipanis** [timber/timber#1195]
I have a `who.php` which has the following setup:

``` php
<?php /* Template Name: Who */

$context = Timber::get_context();
$post = new TimberPost();
$context['post'] = $post;

$context['lead'] = get_field('lead');

$context['team_members'] = Timber::get_posts('post_type=staff');

Timber::render( 'who.twig', $context );
```

The `post_type` `staff` has a bunch of custom fields via ACF e.g. `age`. What is the correct way to send these to our Twig template so I can do things like `{{ team_member.age }}` similar to how I'm achieving `{{ lead }}` from the current post object? 

e.g.

``` twig
<ul>
    {% for team_member in team_members %}
    <li>
        {{ team_member.age }}
    </li>
    {% endfor %}
</ul>
```

Thanking you in advance and for one of the best WordPress plugins around!

**Comment by dptty** [comment]
Like this?
```
{{ team_member.get_field('age') }}
```
There is more about ACF in the [docs](http://timber.github.io/timber/#acf-cookbook).

**Comment by ashrayer** [comment]
Most clean way is to create your own class which extends TimberPost.
Then you create getters for the custom fields inside class.

More detailed docs are [here](https://github.com/timber/timber/wiki/Timber-docs#get_posts). See example of MyEvent class.

**Comment by halian-vilela** [comment]
Hi @hatzipanis !

This should work exactly as in your example. Unless the field you're trying to reach is inside a repeater field, Timber will provide you free access to the ACF just by calling it's by name. So, as in your example it should echo `{{ team_member.age }}` with no problem.

If you look at the `TimberPost` docs, in the properties section, this becomes crystal clear: https://github.com/timber/timber/wiki/TimberPost#properties

**Comment by palmiak** [comment]
@hatzipanis Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
