### ISSUE TITLE
Error when using constructor while Extending Timber\Post

### ISSUE THREAD

**Issue by corradomatt** [timber/timber#1197]
### Expected behavior
I expect Timber/Post to be extended and allow me to add to the constructor while returning the same data as when I don't extend the constructor

### Actual behavior
When the query of the page is in a loop of posts (like on the archive page) the query is hijacked and only returns the first result for all posts in the loop.

### Steps to reproduce behavior
Build a class to extend the Timber\Post class and call it when rendering a twig template. See this gist - https://gist.github.com/corradomatt/5742cede151c0e5f8cbf01cf03c3cc5f

### What version of WordPress, PHP and Timber are you using?
WordPress 4.6.1, PHP 5.6, Timber 1.1.6

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by RadoslavGeorgiev** [comment]
@corradomatt, the `__construct` method of `Timber\Post` expects a post ID as you can see in the [source code](https://github.com/timber/timber/blob/master/lib/Post.php#L176).

In PHP (your brackets suggest that you are used to something else), constructor arguments are not passed to the parent class automaticaly.

Your example shows that you are not receiving/forwarding that ID to the parent class, which leads to Timber always loading the global/first post of the query.

Use this constructor and your code should work properly:

```php
public function __construct( $pid = nill )
{
	parent::__construct( $pid );
}
```

**Comment by corradomatt** [comment]
duh! **me == dumb** -- I used to know that but since I don't extend classes while also overridding the constructor I guess I forgot. Thanks for the response @RadoslavGeorgiev
