### ISSUE TITLE
ACF Radio/True & False with if and else don't work properly with Timber

### ISSUE THREAD

**Issue by adamhoppinger** [timber/timber#1198]
So I currently have an ACF field running (tried both true and false and Radio) with 2 options where the user can pick a google maps or a slider as background for a page. If I use this code:

```
			{% if post.get_field('background_selector') == "false" %}
				{{function('masterslider', 3)}}
			{% elseif post.get_field('background_selector') == "true" %}
				<div id="map"></div>
			{% endif %}
```

For some reason it doesn't seem to work and it doesn't pick either choices even if you select one or the other in admin panel.

However, when I use this code:

```
			{% if post.get_field('background_selector') == "false" %}
				{{function('masterslider', 3)}}
			{% else %}
				<div id="map"></div>
			{% endif %}
```

It always picks the else (even switched it with the slider).

I'm using a very similar code somewhere else (but using classes rather than div/content) and works like it supposes to:

`{% if post.get_field('show_featured_image') == 'Show' %} featured-image {% else %} no-featured-image {% endif %}`

What am I doing wrong? The alias I'm using for the get_field() is correct and I can't think of any other reasons why it wouldn't work..

**Comment by lggorman** [comment]
@adamhoppinger What do you get if you `var_dump` the value of `post.get_field('background_selector')`?  With the true/false ACF field you may be able to use something like this: 
```
{% if not post.background_selector %} 
  {{function('masterslider', 3)}}
{% else %}
  <div id="map"></div>
{% endif %}
```

**Comment by adamhoppinger** [comment]
Alright.. for some reason post.background_selector didn't work but posts.background_selector did. I'm not sure why using posts over post worked, but it did. I used the latter (post) somewhere else in the same if/else setup and for some reason worked?
