### ISSUE TITLE
Duplicate terms in different taxonomies block each other from rendering 

### ISSUE THREAD

**Issue by emmagard** [timber/timber#1202]
### Expected behavior

I have the term `Cats` in 2 different taxonomies. When I use `new TimberTerm($term_slug, $taxonomy)`, I expect the the constructor to return an object of the term in the taxonomy I specify (like using the WP function `get_term_by('slug', $term_slug, $taxonomy_singular)`). 

`object(WP_Term)#492 (12) {
  ["term_id"]=>
  int(73)
  ["name"]=>
  string(4) "Cats"
  ["slug"]=>
  string(4) "cats"
  ["term_group"]=>
  int(0)
  ["term_taxonomy_id"]=>
  int(73)
  ["taxonomy"]=>
  string(5) "issue"
  ["description"]=>
  string(10) "Cats Issue"
  ["parent"]=>
  int(0)
  ["count"]=>
  int(0)
  ["filter"]=>
  string(3) "raw"
  ["ID"]=>
  int(73)
  ["id"]=>
  int(73)
}`
### Actual behavior

The following object is returned:
`object(Timber\Term)#491 (8) {
  ["PostClass"]=>
  string(11) "Timber\Post"
  ["TermClass"]=>
  string(4) "Term"
  ["object_type"]=>
  string(4) "term"
  ["_children"]=>
  NULL
  ["name"]=>
  NULL
  ["taxonomy"]=>
  string(5) "issue"
  ["id"]=>
  NULL
  ["ID"]=>
  NULL
}`
### Steps to reproduce behavior

See functions in first section.
### What version of WordPress, PHP and Timber are you using?

Wordpress 4.6.1
PHP 5.5.9-1ubuntu4.14
Timber 1.1.6
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Composer

**Comment by palmiak** [comment]
Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
