### ISSUE TITLE
Full implementation of WordPress comments??

### ISSUE THREAD

**Issue by alicam** [timber/timber#1205]
I may be missing something but I can find nowhere "in the wild" an implementation of Timber/TWIG that properly manages WordPress commenting, by which I mean both nested comments and the comment form.

I would have thought this would have been a pretty fundamental requirement?!

Has anyone got some code I could work off? Anyone seen anything?!

A

**Comment by luukdv** [comment]
You could try something like this (simplified):

```
{% if post.get_comment_count() > 0 %}
  {% for comment in post.comments %}
    {{ comment.author.name }} - {{ comment.date }}

    {{ comment.content }}

    {% if comment.children() %}
      {% for reply in comment.children() %}
        {{ reply.content }}
      {% endfor %}
    {% endif %}
  {% endfor %}
{% endif %}

{{ fn('comment_form') }}
```

**Comment by alicam** [comment]
Thanks @luukdv. I'm looking for a more thorough implementation that would not just use `fn('comment_form')` but instead would really break it out in to twig vars, etc. So I can style it, etc. I understand that's not trivial!

I've seen in another implementation of Twig (not Timber) that they've done nested comments and it also is not trivial.

A

**Comment by Leobaillard** [comment]
Hi! Any news on this?

**Comment by jarednova** [comment]
@Leobaillard if you're interested, I'd love to see a PR! I don't have time to code stuff like this from-scratch right now

**Comment by jarednova** [comment]
Thanks for your PR @Leobaillard! I uncovered another issue in writing a test so I'm gonna work on that a bit so that we can have Timber Comments be 💯

**Comment by jarednova** [comment]
I'm working on a new class for groups of comments attached to a post — `CommentThread` for a class name? Just `Thread`? taking suggestions....

**Comment by Leobaillard** [comment]
Seems good! It's more generic than Child, it reflects the comment mechanism better. Looking forward to seeing what you'll come up with!

**Comment by jarednova** [comment]
@Leobaillard @alicam — this is now ready, check out the current version of master!

**Comment by alicam** [comment]
@jarednova Sorry. Taken a while to realise this was here and done! Very exciting. I'll be implementing as soon as I get a free moment. Thanks!!

**Comment by synapticism** [comment]
I'm curious if anyone out there has an example of working comments pagination with the new `CommentThread` class...

**Comment by ChapeauDigital** [comment]
> I'm curious if anyone out there has an example of working comments pagination with the new `CommentThread` class...

Is there a working example? I'm currently busy making a theme but 1 post with 2019 comments is taking the page 45 seconds to load. And I can't find a proper way to paginate the Comments with Timber at the moment.

**Comment by palmiak** [comment]
@ChapeauDigital could you provide us with a code sample?

**Comment by ChapeauDigital** [comment]
@palmiak ofcourse. I'm using the out of the box features at the moment. I'm pretty new to Timber so be aware of the crappy code. It's a learning curve.

I did find the CommentThread functions but can't find any documentation or code examples.

**comments.twig**
`{% set number_of_comments = post.comments | length %}

{% if post.comment_status == "closed" %}
  <p> comments for this post are closed </p>
{% else %}
  <span class="rack-mod-heading__h2">Reactie plaatsen</span>
  <div class="cd-com-comments">
    {% include "/partial/modules/comment-form.twig" %}
  </div>
{% endif %}

{% if post.comments %}
  <span class="rack-mod-heading__h2">Reacties ({{ post.comments | length }})</span>
  <div class="cd-com-comments">
  {% for cmt in post.comments | reverse | slice(0, 200) %}
      {% include "/partial/modules/comment.twig" with {comment:cmt} %}
  {% endfor %}
{% endif %}

{% if post.comment_status == "closed" %}
  <p> U kunt niet meer reageren. </p>
{% endif %}

{% if number_of_comments > 6 %}
  {% include "/partial/modules/comment-form.twig" %}
{% endif %}`
**comment.twig**
`{% set depth = comment.depth %}

<div
	class="cd-com-comments__item
	{% if depth %}cd-com-comments__item--level-{{ depth }} {% else %} cd-com-comments__item--level-root {% endif %}
	{% if comment.user_id %}cd-com-comments__item--admin{% endif %}
	"
	id="blog-comment-{{ comment.ID }}">
	<div class="cd-com-comments__row">
		<span class="cd-com-comments__name">{{ comment.author.name }}</span>
		<span class="cd-com-comments__date">{{ comment.comment_date }}</span>
	</div>
	<div class="cd-com-comments__message">
		{{ comment.comment_content | wpautop }}
		<a href="{{ '#form-' ~ comment.ID|default('0') }}" class="cd-com-comments__button js-clickComment">Beantwoorden</a>
		<div class="cd-com-comments__childform">
			{% include "/partial/modules/comment-form.twig" %}
		</div>
	</div>
	{% if comment.user_id %}
		<img class="cd-com-comments__image" src="{{ comment.avatar | resize(60) }}" alt="">
	{% else %}
		<span class="cd-com-comments__image cd-com-comments__image--less">{{ comment.author.name | slice(0, 2) | upper }}</span>
	{% endif %}

</div>

{% if post.comments %}
	<div class="comments">
		{% for cmt in comment.children %}
			{% include "/partial/modules/comment.twig" with {comment:cmt} %}
		{% endfor %}
	</div>
{% endif %}
`

**Comment by palmiak** [comment]
First of all you're right - the documentation of comments isn't too great. We'll have to work on this.

Could just explain me one thing before we continue - are you trying to display about 200 comments at once? Or does it works slow even when you set the comments pagination to 10-20 comments per page?

**Comment by ChapeauDigital** [comment]
Too be completely transparent I didn't had a clue where to start to make the comments work with pagination. I tried to make it 'the WordPress way' with php but the 'native Timber' child and depth what I really like about Timber didn't work anymore so I kinda give up on that idea. My main goal was to show about 50 per page and start the pagination from there. I set a limit within the WordPress comment settings but Timber seems to ignore that part.

**Comment by palmiak** [comment]
Ok, everything is clear. I'll try to do this during the week. As I see,
Timber uses the query vars responsible  for pagination so the only problem
is to create the next and prev links.

wt., 23 paź 2018, 10:16 użytkownik Arno T <notifications@github.com>
napisał:

**Comment by ChapeauDigital** [comment]
@palmiak Hey Palmiak, I would love to know if you found any solution to it?

**Comment by ereinach** [comment]
Hello, same thing.

I'm very eager to know if there is any pagination progress and also, how to do a full comment form using twig as the one included in the starter_theme doesn't seem to work.

**Comment by jarednova** [comment]
For future searchers, the docs have been updated with more info on Comments:

https://timber.github.io/docs/guides/comments/

If you're looking to do more sophisticated manipulation of comments, check out the CommentThread class:

https://github.com/timber/timber/blob/master/lib/CommentThread.php

Comment pagination is something I'd love to formally codify and document. I'm going to close this issue in favor of #2034 which focuses just on that
