### ISSUE TITLE
A solution for grouping items in loop

### ISSUE THREAD

**Issue by lithiumlab** [timber/timber#1209]
Often i need to do some tricky layout on dynamic elements like galleries.
Here's one example:

```
<ul>
    <li class="slide">
        <img src="img_01.jpg">
        <img src="img_02.jpg">
    </li>
    <li class="slide">
        <img src="img_03.jpg">
        <img src="img_04.jpg">
    </li>
    <li class="slide">
        <img src="img_05.jpg">
        <img src="img_06.jpg">
    </li>
</ul>
```

I've managed to do it with the following snippet. But i wanted some suggestions if possible about how to make it more flexible or more simple, like grouping by any number. Maybe using cycle() or any other method. I was getting strange results using the slice() or array[1:2] notation.

```
<ul>
    {% for image in gallery %}
    {% set current = loop.index %}
    {% set next = current + 1 %}
        {% if current is odd %}
            <li class="slide">
                {% for image in gallery %}
                    {% if loop.index in [current,next] %}
                    {% set th = TimberImage(image) %}
                        <img src="{{th.src}}">
                    {% endif %}
                {% endfor %}
            </li>
        {% endif %}
    {% endfor %}
</ul>
```

Any suggestions are welcomed.
This library is the holy grail of templating in WP. Quick in and out fixes with Timber::compile or full routing its very intuitive to work with.
Kudos to creators.

**Comment by tnottu** [comment]
There is a [batch filter](http://twig.sensiolabs.org/doc/filters/batch.html) in Twig which should do what you're asking. For example: 

```
<ul>
    {% for slide in gallery | batch(2) %}
        <li class="slide">
            {% for image in slide %}
                <img src="{{ TimberImage(image).src }}">
            {% endfor %}
        </li>
    {% endfor %}
</ul>
```
