### ISSUE TITLE
Add support for WordPress Site Icon

### ISSUE THREAD

**Issue by piotrkulpinski** [timber/timber#1210]
Hi guys,
Does Timber support Site Icons that can be set in the Customization screen of WP?
https://developer.wordpress.org/reference/functions/get_site_icon_url/

If not, do you plan to implement such function?
I know that I can display it using Timber function wrapper, but I'd love to see this built into the global `site` `($this)` Timber object.

Thanks, Piotrek

**Comment by jarednova** [comment]
@piotrkulpinski — good idea! I made that happen today — check out #1228 (now in master)
