### ISSUE TITLE
Get ACF oEmbed url

### ISSUE THREAD

**Issue by mvaneijgen** [timber/timber#1211]
### Expected behavior

Get `url` with `{{post.get_field('video', FALSE, FALSE)}}`

### Actual behavior

Just get the whole oEmbed element `<iframe width="200" height="113" src="https://www.youtube.com/embed/fH62GWeyyJo?feature=oembed" frameborder="0" allowfullscreen></iframe>`

### What version of WordPress, PHP and Timber are you using?

`5.5.31`
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Downloaded the plugin via the Wordpress UI

**Comment by mvaneijgen** [comment]
Finally found it! You should give `$context['video_url'] = get_field('video', FALSE, FALSE);` to you page options. So for me this is `single.php` and it looks like this

```
<?php
$context = Timber::get_context();
$post = Timber::query_post();
$context['post'] = $post;
$context['video_url'] = get_field('video', FALSE, FALSE);
if ( post_password_required( $post->ID ) ) {
	Timber::render( 'single-password.twig', $context );
} else {
	Timber::render( 'single.twig', $context );
}
```

Than in side you can use `{{video_url}}` to get the url.

**Comment by halian-vilela** [comment]
Nice! Good to know!

**Comment by panfanky** [comment]
I got the URL just by using 
`{{post.video}}`
wanted the reverse, so thank you for
`{{post.get_field('video', FALSE, FALSE)}}`

**Comment by stefenphelps** [comment]
I found using a few twig filters was easiest for my use case:
```
{% if item.meta('oembed') %}
  <div class="category-featured-post">
    {% set videoSrc = item.meta('oembed')|split("src=") %}
    {% set videoUrl = videoSrc[1]|split('"') %}
    {{ videoUrl[1] }}
  </div>
{% endif %}
```

Then you can easily take it a step further to get the videoID out from the URL pretty easily if you wanted to.

**Comment by twentyfortysix** [comment]
item.meta('oembed') does not work on submeta like fields in repeaters or flexible_contents.
therefore I end up with this

```
function extractOembedUrl($string){
    preg_match('/src="([^"]+)"/', $string, $match);
    $res = null;
    if(isset($match[1])){
        $res = $match[1];
    }
    return $res;
}
```

and in template 
`{% set video = fn('extractOembedUrl', item.youtube) %}`

sure can be done as filter .) too

**Comment by stefenphelps** [comment]
@twentyfortysix you could still do it like so submeta fields with a couple split filters like so:
```{% set videoSrc = item.oembed_field|split("src=") %}
{% set videoUrl = videoSrc[1]|split('"') %}```

Then you can print the url with `{{ videoUrl[1] }}` :-)
