### ISSUE TITLE
Problem getting TimberHelper::function_wrapper to work with mc4wp_get_form

### ISSUE THREAD

**Issue by j-greig** [timber/timber#1212]
I'm trying to pass an array to the [mc4wp_get_form](https://mc4wp.com/kb/arguments-in-shortcode/) function that includes an element_id, but I can't get it to work.

Like so.... 

`$context['newsletter_signup'] = TimberHelper::function_wrapper( 'mc4wp_get_form', array(  
		'element_id' => 'extra-css-id-here',  
		'id' => '516',  
	)  
);`

Is something wrong with my syntax?

Thank you!

### What version of WordPress, PHP and Timber are you using?
WordPress 4.6.1, Timber Version 1.1.6

**Comment by luukdv** [comment]
I don't have any experience with `mc4wp`, but based on https://github.com/ibericode/mailchimp-for-wordpress/blob/master/includes/forms/functions.php#L12 it looks like it only accepts one argument (the form ID). Examples:

`$context['newsletter_signup'] = TimberHelper::function_wrapper('mc4wp_get_form', array(516));`, or `$context['newsletter_signup'] = mc4wp_get_form(516);`

Or from Twig:

`{{ fn('mc4wp_get_form', 516) }}`

**Comment by dannyvankooten** [comment]
Wrapping `mc4wp_show_form` instead should do the trick.

**Comment by j-greig** [comment]
@dannyvankooten Thanks for the fast reply. I made your change but now get an error message about using a string:

`[21-Oct-2016 08:08:20 UTC] PHP Warning:  Illegal string offset 'element_id' in /Users/james/Git/greigcc/wordpress/wp-content/plugins/mailchimp-for-wp/includes/forms/class-output-manager.php on line 110
[21-Oct-2016 08:08:20 UTC] PHP Warning:  Illegal string offset 'element_id' in /Users/james/Git/greigcc/wordpress/wp-content/plugins/mailchimp-for-wp/includes/forms/class-output-manager.php on line 130
[21-Oct-2016 08:08:20 UTC] PHP Catchable fatal error:  Argument 2 passed to MC4WP_Form::get_html() must be of the type array, string given, called in /Users/james/Git/greigcc/wordpress/wp-content/plugins/mailchimp-for-wp/includes/forms/class-output-manager.php on line 130 and defined in /Users/james/Git/greigcc/wordpress/wp-content/plugins/mailchimp-for-wp/includes/forms/class-form.php on line 190`

Here's my snippet again:
`$context['newsletter_signup'] = TimberHelper::function_wrapper( 'mc4wp_show_form', array(
		'element_id' => 'extra-css-id-here',
		'id' => '516'
	)
);`

**Comment by dannyvankooten** [comment]
I have no hands-on experience with Timber but the function signature of `mc4wp_show_form` is as follows:

```php
function mc4wp_show_form( $form_id = 0, $config = array(), $echo = true )
```

So the first parameter is the form ID, the second is an optional array of configuration values (same as shortcode parameters and the third is whether to immediately echo the form HTML.

Given that, I think the Timber wrapping code should look like this:

```php
$args = array(
    516,                                           // $form_id
    array( 'element_id' => 'extra-css-id-here' ),  // $config
);
$context['newsletter_signup'] = TimberHelper::function_wrapper( 'mc4wp_show_form', $args );
```

I might be wrong on the Timber syntax, but if they're calling `call_user_func_array` or something similar to call the actual function then this should work.

**Comment by j-greig** [comment]
@dannyvankooten Thanks Danny, this fixes it! 

Only problem is that using mc4wp_show_form makes the form be displayed twice — it's not an option to use mc4wp_get_form, correct?

**Comment by dannyvankooten** [comment]
Hi James,

In that case, Timber is also echo'ing the return value of the function. That's where the third parameter `$echo` comes into play. :-)

```php
$args = array(
    516,                                           // $form_id
    array( 'element_id' => 'extra-css-id-here' ),  // $config
    false,                                         // $echo
);
$context['newsletter_signup'] = TimberHelper::function_wrapper( 'mc4wp_show_form', $args );
```

**Comment by j-greig** [comment]
Yaaaas. Fixed. Thanks for your help.
