### ISSUE TITLE
ACF repeater rows, footer, and admin bar missing from page

### ISSUE THREAD

**Issue by mikehwagz** [timber/timber#1217]
### Expected behavior

Slowly, one page/ui component at a time, I am using Timber to rebuild a university political review site. First page to rebuild was the team page. I started by making a local copy of the site and creating a child of the current theme (Bucket by PixelGrade). Using an ACF Repeater (a row for each team member), I effortlessly created a beautiful team page whilst sipping coffee from my Timber coffee mug (Thanks Upstatement!!!). The entire page looks and functions as it should locally.
### Actual behavior

After deploying the new child theme, exporting and importing the Repeater field group, and manually inputting the content, the page does not display correctly. Details, screenshots, and code below:

With Timber 1.1.7.1 the following components are missing:
- wp admin bar
- site navigation dropdowns do not expand on hover as expected
- page content 
- footer

![Image of the page with Timber 1.1.7.1](http://i.imgur.com/e0lSnnZ.png)

Downgrading to Timber 0.22.6, I had a bit better luck, but still no dice. The following was still missing:
- wp admin bar
- site navigation dropdowns do not expand on hover as expected
- footer
- the last 2.5 team members (the .5 is a missing bio... see screenshot below)

![Image of the page with Timber 0.22.6](http://i.imgur.com/aq5jZR6.jpg)

Code below:
 [Review code in the repo if you prefer](https://github.com/mikehwagz/nupr)

**functions.php** - I copied most of this code from the Timber Starter Theme.

```
<?php

if ( ! class_exists( 'Timber' ) ) {
    add_action( 'admin_notices', function() {
            echo '<div class="error"><p>Timber not activated. Make sure you activate the plugin in <a href="' . esc_url( admin_url( 'plugins.php#timber' ) ) . '">' . esc_url( admin_url( 'plugins.php' ) ) . '</a></p></div>';
        } );
    return;
}

Timber::$dirname = array('templates', 'views');

class BucketChild extends TimberSite {

    function __construct() {
        add_theme_support( 'post-formats' );
        add_theme_support( 'post-thumbnails' );
        add_theme_support( 'menus' );
        add_filter( 'timber_context', array( $this, 'add_to_context' ) );
        add_filter( 'get_twig', array( $this, 'add_to_twig' ) );
        add_action( 'init', array( $this, 'register_post_types' ) );
        add_action( 'init', array( $this, 'register_taxonomies' ) );
        parent::__construct();
    }

    function register_post_types() {
        //this is where you can register custom post types
    }

    function register_taxonomies() {
        //this is where you can register custom taxonomies
    }

    function add_to_context( $context ) {
        $context['foo'] = 'bar';
        $context['stuff'] = 'I am a value set in your functions.php file';
        $context['notes'] = 'These values are available everytime you call Timber::get_context();';
        $context['menu'] = new TimberMenu();
        $context['site'] = $this;
        return $context;
    }

    function myfoo( $text ) {
        $text .= ' bar!';
        return $text;
    }

    function add_to_twig( $twig ) {
        /* this is where you can add your own fuctions to twig */
        $twig->addExtension( new Twig_Extension_StringLoader() );
        $twig->addFilter('myfoo', new Twig_SimpleFilter('myfoo', array($this, 'myfoo')));
        return $twig;
    }

}

new BucketChild();

// enqueue styles for child theme
function nupr_enqueue_styles() {

    // enqueue parent styles
    wp_enqueue_style('parent-theme', get_template_directory_uri() .'/style.css');

    // enqueue child styles
    wp_enqueue_style('child-theme', get_stylesheet_directory_uri() .'/style.css', array('parent-theme'));

}
add_action('wp_enqueue_scripts', 'nupr_enqueue_styles');
```

**page-3117.php** - Copied the page.php template from the parent theme, and replaced the contents of the container div with the Timber logic.

```
<?php

get_header(); ?>

    <div class="container container--main">

        <?php

            $context = Timber::get_context();
            $context['post'] = new TimberPost();
            Timber::render('team.twig', $context);

        ?>

    </div>

<?php
get_footer(); ?>
```

**team.twig** - And finally, the twig template which lives in a templates directory. There is a bit of conditional logic inside the repeater loop, which worked perfectly in my local environment.

```
<h2 class="page__title">{{post.title}}</h2>

<section class="team">

    {% for member in post.get_field('team_members') %}
      <div class="team-member">
            <div class="team-member__image">
                {% if member.bg_zoom %}
                <img class="team-member__background" src="{{TimberImage(member.background).src}}" />
                {% endif %}
            <img class="team-member__headshot" src="{{TimberImage(member.headshot).src}}" alt="{{member.name}}" />
        </div>
        <div class="team-member__body">
            <header class="team-member__header">
                <span class="team-member__position">{{member.position}}</span>
                <h4 class="team-member__name">{{member.name}}</h4>
            </header>
            <p class="team-member__bio">{{member.bio}}</p>
          </div>
      </div>
    {% endfor %}

</section>
```
### Steps to reproduce behavior

I have not been able to reproduce the issue locally. As mentioned above, downgrading to 0.22.6 helped slightly, but still not looking perfect as it did locally.
### What version of WordPress, PHP and Timber are you using?

Same for local and live:
WordPress 4.6.1
PHP 5.5
Timber 1.1.7.1 (and 0.22.6 for testing purposes as mentioned above. has no effect on appearance of page locally)
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

WP.org

**Comment by halian-vilela** [comment]
From your example what I would do at first is drop using `get_header()` and `get_footer()` and try to match the solution from the Timber Starter Theme as well, where the call for this parts of the structure are from within Timber itself ( in `base.twig` ).

Probably most of the issues you are facing are due to the lack of `wp_head()` and `wp_footer()` being propely fired, so you have no proper javascript being loaded nor wp-admin-bar being injected.

Give that a try and tell us if it solves the problem.

**Comment by mikehwagz** [comment]
@halian-vilela Thanks for the response. I will try to match the solution from the Timber Starter Theme and let you know if that helps.

Regarding your edit, the repo you are looking at is a child theme, so the header.php and footer.php templates are located in the parent theme.

**Comment by palmiak** [comment]
Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread

**Comment by mikehwagz** [comment]
Nope! Totally fine to close the thread.
