### ISSUE TITLE
Post->get_terms() not compatible with Post->terms()

### ISSUE THREAD

**Issue by haroldangenent** [timber/timber#1221]
### Expected behavior

`Post->get_terms()` (deprecated since 1.0) being backwards compatible.
### Actual behavior

Not compatible, `Post->get_terms()` doesn't receive the `$TermClass` parameter anymore.
### Steps to reproduce behavior
1. Use `Post->get_terms()` with another `$TermClass` before 1.0
2. Upgrade to 1.0+
### What version of WordPress, PHP and Timber are you using?

WordPress 4.6.1, latest Timber, PHP 7.
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Composer. Or any other.

**Comment by haroldangenent** [comment]
By the way, the issue seems to be created in https://github.com/timber/timber/commit/6b2f438d6ae6f2f889aea56e6cdd479f0d135d7b.

**Comment by jarednova** [comment]
Closed by #1222
