### ISSUE TITLE
Conditionally enqueue scripts based on route

### ISSUE THREAD

**Issue by moazam1** [timber/timber#1223]
I have following route:

`Routes::map('photo/:name', function($params){
    Routes::load('page-templates/template-photo.php');
});`

I would like to add scripts/styles for this route. I have created page template and then I am adding below code in my `wp_enqueue_scripts` action:

```
`if( is_page_template( 'page-templates/template-photo.php' ) ) {
    wp_enqueue_script( 'slick-script',  get_stylesheet_directory_uri().'/assets/js/slick.min.js', array( 'theme-script' ) );
    wp_enqueue_script( 'slider-script', get_stylesheet_directory_uri().'/assets/js/listing.js', 'theme-script');
}`
```

WordPress is not recognizing the photo template, I believe the reason is that I haven't created page and assigned page template to that. I do not want to do that and I solely want to rely on Route. Is there any possibility or a feature can be added to do something like this: Route::is('photo') inside `wp_enqueue_scripts` action?

Thanks

**Comment by moazam1** [comment]
I was able to get page name from `get_query_var('pagename')` Not sure if this is the best approach to do this task. Your feedbacks are highly appreciated.

**Comment by moazam1** [comment]
I solved this problem by using `get_query_var('name')` in my `wp_enqueue_scripts` action call. I would like to see this feature in Router i.e. Route::isPage('photos').

The above method does not work for URL structures like this:

```
//does not work
Routes::map('photos/gallery/12', function($params){
	Routes::load('page-photo-archive.php', $params);
});
//works
Routes::map('photos/12', function($params){
	Routes::load('page-photo-archive.php', $params);
});
```

**Comment by gchtr** [comment]
If you solely want to rely on Routes, then you could also add the `wp_enqueue_scripts` action inside the Route closure:

```php
Routes::map( 'photo/:name', function( $params ) {
    add_action( 'wp_enqueue_scripts', function() {
        wp_enqueue_script( 'slick-script',  get_stylesheet_directory_uri().'/assets/js/slick.min.js', array( 'theme-script' ) );
        wp_enqueue_script( 'slider-script', get_stylesheet_directory_uri().'/assets/js/listing.js', 'theme-script');
    } );

    Routes::load( 'page-templates/template-photo.php' );
} );
```

As long as you add `wp_enqueue_scripts` before the `wp_head` function, you could also place it in `page-templates/template-photo.php`.

**Comment by moazam1** [comment]
@gchtr Thanks for the answer. I thought about same but I wanted to keep my enqueue files in one place. I ended up creating a twig function for enqueue styles and scripts. I registered styles/scripts in my file and called them directly in the template files.

**Comment by adrienlamotte** [comment]
@moazam1 Hello ! Would you share your twig function please ? :-)

**Comment by moazam1** [comment]
Hey @adrienlamotte I have one enqueue file and based on conditions I register my enqueue files there.

**Comment by moazam1** [comment]
To solve my original question for this route: `Routes::map('photo/:name', function($params){ Routes::load('page-templates/template-photo.php'); });` I added [https://codex.wordpress.org/Rewrite_API/add_rewrite_rule](url) in my code and gave it a name i.e. photos and then in my enqueue code I did this `$page = get_query_vars('page')` `if($page == 'photos') wp_enqueue_script`

Hope it helps you.
