### ISSUE TITLE
Multiple Menu Issues

### ISSUE THREAD

**Issue by justalever** [timber/timber#1230]
### Expected behavior
I'm trying to implement multiple menus. One for the header and one for the footer. I have made both menus in WordPress. I have also registered both menus and issued their own specific locations. 

### Actual behavior
The Primary nav display correctly using the TimberMenu class. I make another call for the footer menu and the result is null.

### Steps to reproduce behavior

**functions.php**
```
function add_to_context( $context ) {
  $context['menu'] = new TimberMenu('primary-menu');
  $content['footer'] = new TimberMenu('footer-menu'); 
  $context['site'] = $this;
  return $context;
}
```

**footer.twig**
```	
<div class="sub-footer-menu">
 {% if footer %}
      <ul>
        {% for item in footer.get_items %}
         <li class="{{item.classes | join(' ')}}">
          <a href="{{item.get_link}}">{{item.title}}</a>
        </li>
       {% endfor %}
     </ul>
  {% endif %}
</div>
```

**base.twig**
```
{% block footer %}
   <footer id="footer">
     {% include "footer.twig" with {"footer": footer.get_items} %}
   </footer>
   {{ function('wp_footer') }}
{% endblock %}
```

I can include the menu fine if I use the regular `wp_nav_menu()` function but I'd rather not go that route. 

### What version of WordPress, PHP and Timber are you using?

+ WordPress 4.6.1
+ PHP Version 7.0.10
+ Timber 1.1.8
+ Environment = MAMP Local

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Upgraded to newest version via plugin updater in WordPress dashboard

**Comment by luukdv** [comment]
Seems like you include `footer.twig` with the `footer` variable set to `footer.get_items`. In `footer.twig` you call `get_items` on this variable _again_, which doesn't exist. Looks like `{% for item in footer %}` should work.

**Comment by justalever** [comment]
Thanks for the reply!

Unfortunately what you suggest still returns null. I updated `footer.twig` as shown below:

```
<div class="sub-footer-menu">
 {% if footer %}
      <ul>
        {% for item in footer %}
         <li class="{{item.classes | join(' ')}}">
          <a href="{{item.get_link}}">{{item.title}}</a>
        </li>
       {% endfor %}
     </ul>
  {% endif %}
</div>
```

**Comment by motia** [comment]
I have faced the same problem, it is because Timber don't get the menu by slug correctly.

 ```
$menu_id = get_term_by('slug', 'primary-menu', 'nav_menu')->term_id;
$context['menu'] = new TimberMenu($menu_id);
$footer_menu_id = get_term_by('slug', 'footer-menu', 'nav_menu')->term_id
$context['footer'] = new TimberMenu($footer_menu_id);
 ```
