### ISSUE TITLE
Menu Items post_name inconsistency

### ISSUE THREAD

**Issue by halian-vilela** [timber/timber#1231]
### Expected behavior
I would like to get the `slug` of a menu item by accessing `item.post_name` when looping over a TimberMenu array

### Actual behavior
I actually have 5 itens in my menu, but only **ONE** of them is displaying the `slug`, all other are displaying the item's `id`. I cannot tell what's the source of this inconsistency because all itens were inserted the same way in WP's menu.

### Steps to reproduce behavior
1. Create a WP Menu
2. Add menu to context `$context[items] = new TimberMenu("Main Menu")`
3. Dump WP items
```
{{dump(items)}} 
```
4. Search for `public 'post_name'`
5. Tell me if it's the `id` or the `slug`

### What version of WordPress, PHP and Timber are you using?
WordPress 4.6.1, PHP 5.6, Timber 1.1.8

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Upgraded to newest version via plugin updater in WordPress dashboard

**Comment by jarednova** [comment]
@halian-vilela this is a tricky one. I did some investigation and you're correct that `post_name` sometimes gives id values. That's because the `post_name` of `nav_menu_item` is the WP posts table _is_ a number like that. I'm hesitant to change this (but I'm open to a good argument).

That said you CAN use `.slug` (for example `menu_item.slug`) which will always return the slugifyed name you're looking for (`sample-page`, etc.)

**Comment by halian-vilela** [comment]
@jarednova 

Yeah, I had figured that out by taking a look at the source code from `TimberMenuItem` class. But I think that's not clear in the documentation. But I can add it myself as soon as I have some spare time.

Now, in regards to `post_name`, I guess any change would be welcome to guarantee a more robust value, regarding the fact that with the current implementation we cannot have a clue on which value the property will **really** return, so it's pretty much useless if anyone would depend on its value. What do you think?

**Comment by palmiak** [comment]
Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
