### ISSUE TITLE
switch_to_blog() in TimberPost extension.

### ISSUE THREAD

**Issue by ColeWelsome** [timber/timber#1236]
### Expected behavior
On the homepage of my multi site I want to see a list of posts from other sites. I'd like to be able to  call switch_to_blog() once then get the posts and their respective links then restore_current_blog(). The only way I can get this working is if I call switch_to_blog() in multiple places. See below code for my attempting at switching only once.

### Actual behavior
PHP runs into a fatal error:

> Fatal error: Call to a member function set_blog_id() on a non-object in wp-includes/ms-blogs.php on line 713

### Steps to reproduce behavior
Here's my current code:
```
class MySitePost extends TimberPost
{
    function __construct($pid = null) {
        switch_to_blog(42);
        parent::__construct($pid);
    }
    function __destruct() {
        restore_current_blog();
    }
}

$context['associate_news'] = Timber::get_posts('post_type=post&numberposts=6', 'MySitePost');
```

### What version of WordPress, PHP and Timber are you using?
WordPress 4.5.3, PHP 5.3, Timber 1.1.8

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Installed and updated via WP CLI

**Comment by jarednova** [comment]
@ColeWelsome just a stab, but try wrapping the code with `is_multisite()`?

**Comment by ColeWelsome** [comment]
Thanks for the reply jarednova,

Unfortunately, that didn't work. This is a multisite I'm developing on. I tried debugging restore_current_blog() in ms-blogs.php but I didn't get far. 

This is the code I currently have and it works but I'm new to Timber so I keep thinking there's a better way:

`// Fixes issue where the timber post object trys to get the link from the current blog
class fix_link extends TimberPost
{
    public function link($blog_id)
    {
        switch_to_blog($blog_id);
        $link = parent::link();
        restore_current_blog();

        return $link;
    }
}
    // TODO Not ideal
    switch_to_blog(42);
    $context['associate_news'] = Timber::get_posts('post_type=post&numberposts=6', 'fix_link');
    restore_current_blog();

`
And then in the twig file:
`    {% if associate_news %}
        <h2>Associate News</h2>
        <ul>
            {% for post in associate_news %}
                <li><a href="{{post.link(42)}}">{{post.title}}</a></li>
            {% endfor %}
        </ul>
        <p><a href="/v2/associate-news/">More Associate News</a></p>
        <p><a href="/v2/associate-news/submit-an-associate-story/">Submit Your News</a></p>
    {% endif %}
`

**Comment by jarednova** [comment]
I'm closing out old issues. Please open a fresh issue if this is still a live issue that we should investigate — thank you!
