### ISSUE TITLE
Updating to 1.1.9 causes open_basedir restriction warnings.

### ISSUE THREAD

**Issue by codytooker** [timber/timber#1241]
After updating to 1.1.9 I am receiving the following error on some pages of my sites.

Warning: realpath() [function.realpath]: open_basedir restriction in effect. File(/) is not within the allowed path(s): (/nfs:/tmp:/usr/local:/etc/apache2/gs-bin) in /nfs/c06/h06/mnt/154442/domains/onda.dodstaging.co/html/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 37

**Comment by jarednova** [comment]
Thanks @codytooker — someone else reported a similar issue. Can you try replacing your `vendor` directory with one from version 1.1.8? I think this is an issue with Twig (not blaming them, but it's how the two work together) but I want to confirm before going on a wild goose chase. Anyway, let me know if that solves the problem so I can focus on that connection, thanks!

**Comment by jarednova** [comment]
@codytooker — can you try out the code in this PR?

https://github.com/timber/timber/pull/1245

... easiest way is to copy-and-paste the contents of `lib/Loader.php` into your install — let me know if that does the trick!

**Comment by jarednova** [comment]
Closed by #1245
