### ISSUE TITLE
Post:comments() function crashes when no parent comment exist

### ISSUE THREAD

**Issue by shnam7** [timber/timber#1242]
### Expected behavior

[Situation] WordPress allows comments to be deleted, event when they have children. In that case, only the chosen comment is deleted with its child-comments remaining. (The comment count report also includes the orphaned child comments).
Even though parent comment is deleted, it should not crash, and need to work at leash in similar fashion as 'wp_list_comments()' function of WordPress.

### Actual behavior

If this [Situation] above happens, Timber:comments() crashes with error message "calling a function is_child() on null object" because it's not doing validity check for the existence of parent comment.

### Steps to reproduce behavior

Need to check validity of parent comment before doing array index access.

### What version of WordPress, PHP and Timber are you using?

WordPress 4.6.1, PHP 7.0.8, Timber 1.1.8

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Upgraded to newest version via plugin updater in WordPress dashboard

**Comment by palmiak** [comment]
Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
