### ISSUE TITLE
Help looping through ACF Pro flexible content fields

### ISSUE THREAD

**Issue by j-greig** [timber/timber#1246]
I've read all the examples and searched the issues here but I can't get my head around how the ACF flexible content fields work via Timber, or how to use acf_fc_layout correctly.

So far I've got as far as spitting out all of the field content, but this includes the layout names which obviously I dont want:

`            {% for flexi in post.get_field('flexi') %}`
`                   {% for rows in flexi %}`
`                        {{rows}}`
`                    {% endfor %}`
`           {% endfor %}`

Have tried things like `{% if rows.acf_fc_layout == 'thirtyseventy' %}` inside the inner for loop, but that doesn't work.

Here's a screenshot of the field names:
![fieldnames](https://cloud.githubusercontent.com/assets/616194/20430031/eee45ee0-ad89-11e6-8d6a-2aca8c412285.jpg)

And the vars
![dump](https://cloud.githubusercontent.com/assets/616194/20430304/7d5a3a0e-ad8b-11e6-9427-0e61fa0d5054.jpg)

Thanks for your time :)

James

**Comment by j-greig** [comment]
PS. One more q — how do you access the wrapper attributes?

**Comment by halian-vilela** [comment]
You don't need the inner loop. Just treat it as a normal repeater  and use only the first loop like `{% if flexi.acf_fc_layout == 'thirtyseventy' %}` and then go straight to the value of the field `{{flexi.thirty}}`.

I like to put the whole layouts inside their own templates, so its clear to see what is happening, just like:

```
{% for flexi in flexi.get_field('flex_layouts') %}
    {% if flexi.acf_fc_layout == "layout_1" %}
        {% include 'components/flex_layouts/layout_1.twig' %}
    {% elseif flexi.acf_fc_layout == "layout_2" %}
         {% include 'components/flex_layouts/layout_2.twig' %}
    {% endif %}
{% endfor %}
```

**Comment by j-greig** [comment]
Thank you @halian-vilela, working now :)

**Comment by jarednova** [comment]
@j-greig another link to help you out.... 

https://github.com/timber/timber/blob/master/docs/wiki/_acf-cookbook.md#flexible-content-field

**Comment by rBroneak** [comment]
From Timbers site -

{% for media_item in post.get_field('media_set') %}
    {% if media_item.acf_fc_layout == 'image_set' %}
        <img src="{{TimberImage(media_item.image).src}}" />
        <p class="caption">{{TimberImage(media_item.image).caption}}</p>
        <aside class="notes">{{media_item.notes}}</aside>
    {% elseif media_item.acf_fc_layout == 'video_set' %}
        <iframe width="560" height="315" src="http://www.youtube.com/embed/{{media_item.youtube_id}}" frameborder="0" allowfullscreen></iframe>
        <p class="caption">{{media_item.caption}}</p>
    {% endif %}
{% endfor %}
