### ISSUE TITLE
Image resize and cache

### ISSUE THREAD

**Issue by xtatanx** [timber/timber#1247]
Hello everyone,

I'm developing a [site](http://jhonnatangonzalez.com/) using timber, now we are close to release the site we have been trying to optimize the site using total cache plugin however, noticed that all the images using the resize filter never get cached. Was wondering if any of you guys have any feedback about this, is this an issue? is probably something I am missing? 

I appreciate if someone could point me in a good direction.

Best Regards

**Comment by halian-vilela** [comment]
@xtatanx 

Have you tried using the usual way? I mean declaring predefined thumbnail sizes in `functions.php` like:

```php
add_theme_support('post-thumbnails');
add_image_size( 'slider', 1200, '900', true );
```
And then calling it with `TimberImage('post.img').src('slider')` or `post.thumbnail.src('slider')` (the first one with `post.img`  returning a custom field image's ID.)

**Comment by xtatanx** [comment]
@halian-vilela 

I am going to try that this afternoon ant let you know!

Thanks

**Comment by xtatanx** [comment]
Hello @halian-vilela,

Tested adding thumbnails via functions.php and regenerating them but still having the same issue, images are not getting cached.

Regards

**Comment by corradomatt** [comment]
Hi @xtatanx, Sounds like it's an issue with your server setup and not Timber / Twig.

**Comment by xtatanx** [comment]
Hello @corradomatt ,

You were right, cache on images was working as expected. Closing this issue.

Regards
