### ISSUE TITLE
Pagination issue when using query string parameters

### ISSUE THREAD

**Issue by xavivars** [timber/timber#1249]
### Expected behavior
Given a page like this:

https://www.softcatala.org/noticies/?cerca=gimp

where `cerca` is defined as a query_var

```
function add_query_vars_filter( $vars ){
    $vars[] = "cerca";

    return $vars;
}
add_filter( 'query_vars', 'add_query_vars_filter' );
```
pages should get paginated as 

https://www.softcatala.org/noticies/page/2/?cerca=gimp

### Actual behavior
Pagination links are created like

https://www.softcatala.org/noticies/page/2/?cerca=gimp/

### Steps to reproduce behavior
The problem is in this line:
https://github.com/timber/timber/blob/master/lib/Pagination.php#L172

```
	public static function is_search_query( $url ) {
		if ( strpos($url, 's=') !== false ) {
			return true;
		}
		return false;
	}
```

where `s` is the only query var that is checked against.

### What version of WordPress, PHP and Timber are you using?
WordPress 4.6, PHP 5.6, Timber 1.1.10

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WP.org

**Comment by jarednova** [comment]
Closed by #1250
