### ISSUE TITLE
Unable to add additional Twig Filesystem Loaders

### ISSUE THREAD

**Issue by adamtomat** [timber/timber#1253]
### Expected behavior
We need to change the way twig handles file look-ups as we are using a pattern library with WordPress. We therefore would like to register our own Loader (that implements `Twig_LoaderInterface`, see example below) with Timber.

For example: Our file structure looks like this:

- <theme>/views/templates/
    - home/
        - template.twig

Given this command:

`Timber::render('templates/home', $context);`

We want it to find `views/templates/home/template.twig` in our theme.

I don't expect this exact use-case to be fixed. Instead, having a hook when Timber initialises the `Twig_Loader_Filesystem` class would enable us to extend it with our own loader.

### Actual behavior

The current behaviour, when trying to find `templates/home` gives this error:

```
Fatal error: Uncaught exception 'Twig_Error_Loader' with message 'Unable to find template "templates/home" (looked into: <some_dir>/themes/<theme_name>, <some_dir>/themes/<theme_name>/views, ).' in <some_dir>/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:247
```

### Steps to reproduce behavior

1. Create a twig file in `<theme>/views/templates/home/template.twig`

2. Register load paths for Timber (in `functions.php`)

```php
new Timber();

Timber::$dirname = [
    'views/templates',
];
```

3. In a controller, e.g. `page.php` add the following:

`Timber::render('templates/home', $context);`

### Suggested Fix

Add a hook in `lib/Loader.php` in the `getLoader()` method, after initialising the `Twig_Loader_Filesystem`.

*Current method (as of 1.1.0):*

```php
/**
 * @return \Twig_Loader_Filesystem
 */
public function get_loader() {
    $open_basedir = ini_get('open_basedir');
    $paths = array_merge($this->locations, array( $open_basedir ? ABSPATH : '/'));
    $paths = apply_filters('timber/loader/paths', $paths);

    $rootPath = '/';
    if ( $open_basedir ) {
        $rootPath = null;
    }
    $fs = new \Twig_Loader_Filesystem($paths, $rootPath);
    return $fs;
}
```

*Suggested fix (will submit a PR for this too):*

```php
/**
 * @return \Twig_Loader_Filesystem
 */
public function get_loader() {
    $open_basedir = ini_get('open_basedir');
    $paths = array_merge($this->locations, array( $open_basedir ? ABSPATH : '/'));
    $paths = apply_filters('timber/loader/paths', $paths);

    $rootPath = '/';
    if ( $open_basedir ) {
        $rootPath = null;
    }
    $fs = new \Twig_Loader_Filesystem($paths, $rootPath);
    
    // Allow the filesystem loader to be extended
    $fs = apply_filters('timber/loader/loader', $fs);
    return $fs;
}
```

We've been using a fork of Timber with this change in for about a year now. Thought it was time to look at getting it in the core. For context only, here is our custom twig loader that we are using to let Twig know that it should look for `templates/home/template.twig` when given `templates/home`:

```php
namespace App;

// Hook into when Timber initialises the Twig_Loader_Filesystem
add_filter('timber/loader/loader', function ($loader) {
    $customLoader = new \App\CustomLoader(get_stylesheet_directory() . '/views');
    // Add our loader to the end of the chain (i.e. Timber does its lookup, then runs ours)
    $chainLoader = new \Twig_Loader_Chain([$loader, $customLoader]);

    return $chainLoader;
});

class CustomLoader implements \Twig_LoaderInterface
{
    // Base path for patterns lib.
    protected $patternsPath;

    public function __construct($patternsPath)
    {
        $this->patternsPath = $patternsPath;
    }

    /**
     * Gets the source code of a template, given its name.
     *
     * @param  string $name string The name of the template to load
     *
     * @return string The template source code
     */
    public function getSource($name)
    {

        // Remove the extension at this point as we add it ourselves below
        $id = preg_replace('/\.twig$/', '', $name);

        // Add template.twig into path
        $path = $this->patternsPath . '/' . $id . '/template.twig';

        return file_get_contents($path);
    }

    /**
     * Gets the cache key to use for the cache for a given template name.
     *
     * @param  string $name string The name of the template to load
     *
     * @return string The cache key
     */
    public function getCacheKey($name)
    {
        return md5($name);
    }

    /**
     * Returns true if the template is still fresh.
     *
     * @param string    $name The template name
     * @param timestamp $time The last modification time of the cached template
     */
    public function isFresh($name, $time)
    {
        return true;
    }
}
```

### What version of WordPress, PHP and Timber are you using?
WordPress 4.6.1, PHP 5.4, Timber 1.1.0

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer (using Root's [Bedrock](https://roots.io/bedrock/))

**Comment by jarednova** [comment]
Closed by #1254
