### ISSUE TITLE
Make $wp_query->found_posts available through Timber::get_posts()

### ISSUE THREAD

**Issue by jphilung** [timber/timber#1257]
On queries that do not specify arguments related to posts_per_page and which uses the default posts_per_page value, I can't find a way of getting the total number of posts found.

#425 references this issue, but the count in the array returned is at maximum the number specified by the default posts_per_page.

For the moment, I've resorted to using the global $wp_query variable and get the value from the there.

I'd like to contribute to the repo by adding this feature, how would I contribute ?

**Comment by paulhuisman** [comment]
Funny you posted this yesterday, because it's exactly what i need as well.

**Comment by chrisvanpatten** [comment]
I need this as well. Here's how I'm hacking it for now:

```
<?php

class MyQuery extends \Timber\PostQuery
{

	/**
	 * Uses a hack to steal access to a private property, in this
	 * case, we need to access $this->queryIterator->_query
	 *
	 * @via https://ocramius.github.io/blog/accessing-private-php-class-members-without-reflection/
	 * @return query
	 */
	public function forceGetQuery()
	{
		$query = function ($iterator) {
			return $iterator->_query;
		};

		$found = \Closure::bind($query, null, $this->queryIterator);

		return $found($this->queryIterator);
	}

	/**
	 * Get the count of results
	 *
	 * @return int
	 */
	public function getResultsCount()
	{
		$query = $this->forceGetQuery();

		// Cast to an int
		return absint($query->found_posts);
	}
}
```

In your controller/theme file:

```
$posts = new MyQuery();
$posts->getResultsCount();
```

I'm not yet super familiar with Timber internals but I'd be happy to work up a PR with some guidance… cc @jarednova (hey dude, long time no chat!)

**Comment by gchtr** [comment]
I’m having this issue as well. Accessing query variables for a custom query is too hard now. And falling back to the `$wp_query` global doesn’t work when using a custom query in singular templates.

Would be great if you could work on this @chrisvanpatten.

**Comment by mibu31** [comment]
Bump - same issue.

I'm using `new \Timber\PostQuery($args);` with the `paged` argument and I'm unable to access the total number of posts returned before `paged` was applied (`$wp_query->found_posts`).

**Comment by mibu31** [comment]
@jarednova @chrisvanpatten 
Is there a reason this variable is set to private? (other than following best practice)
I might be able to help resolve it/PR if I'm given some insight as to why it's been done like this. 
I'm nearing a project completion but the above is still an issue for me unfortunately and I'd like to avoid doing something "dirty" to work around it.
Can this not be set to protected so that an extending class can access it?

**Comment by Josh68** [comment]
I think I have a question related to this issue. Isn't there supposed to be a [`get_query()`](https://timber.github.io/docs/reference/timber-postquery/#get-query) method (protected, not private) on `new Timber\PostQuery()`? I can't seem to get it to work.

**Comment by adrienlamotte** [comment]
Hello!
Same problem here, I need to get the real total posts of a search... 
@mibu31 how did you managed to do it finally ? :)

Thank you

**Comment by tmugford** [comment]
@adrienlamotte Just in case you haven’t found a solution yet.

```php
global $wp_query;

$context = Timber::get_context();
$context[ 'found_posts' ] = $wp_query->found_posts;

Timber::render( 'search.twig', $context );
```

**Comment by adrienlamotte** [comment]
@tmugford Thank you, but `found_posts` does not work with paged queries (it returns the total on the current page)
