### ISSUE TITLE
'nav_menu_css_class' filter in MenuItem::import_classes() is missing arguments

### ISSUE THREAD

**Issue by slimndap** [timber/timber#1263]
The `nav_menu_css_class` in WordPress can have up to 4 arguments:

```php
/* WP 4.1+ */
function filter_handler( $classes , $item, $args, $depth ){ ...... }

add_filter( 'nav_menu_css_class', 'filter_handler', 10, 4 ); 
```

Timber also applies this filter in `MenuItem::import_classes()` but it lacks the 3rd and 4th argument:

```php
$this->classes = apply_filters('nav_menu_css_class', $this->classes, $this);
```

Resulting in the following error message:

```
Warning: Missing argument 3 for filter_handler(), called in /path/htdocs/wp-includes/plugin.php on line 235 and defined in /path/htdocs/wp-content/themes/theme/functions.php on line 186
```

### Steps to reproduce behavior

Add this to `functions.php`:

```php
function filter_handler( $classes , $item, $args, $depth ){
  return $classes;
}

add_filter( 'nav_menu_css_class', 'filter_handler', 10, 4 ); 
```

### What version of WordPress, PHP and Timber are you using?
WP 4.6, Timber 1.1.10, PHP7.

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WP.org.

**Comment by certainlyakey** [comment]
Same here. Makes impossible to add say classes depending on menu location to via `nav_menu_css_class` filter.

**Comment by jarednova** [comment]
Thanks @slimndap and @certainlyakey, I have a PR that resolves this in #1382

**Comment by benedict-w** [comment]
$args is now an empty array. Am I missing something? 

I'd like to add a class depending on menu location, but $args is empty, so not possible as suggested e.g. here: https://developer.wordpress.org/reference/hooks/nav_menu_css_class/#div-comment-2962

**Comment by jarednova** [comment]
@benedict-w this is from April 2017, so this is my read based on looking at this code. It's true that the `$args` sent by `Timber\MenuItem` is empty here, but if you want to get info on the particular `$item`, that's being sent so you could explore its contents. Could you post a more particular example in a fresh ticket?
