### ISSUE TITLE
Incomplete Composer Package Update (1.1.11)

### ISSUE THREAD

**Issue by developer-lindner** [timber/timber#1266]
Your Fix for 'Deprecated Twig getExtension argument' is missing in latest (1.1.11) composer package of Timber. Maybe some other stuff too... Not cool!

Please fix this asap!

**Comment by jarednova** [comment]
Hey @developer-lindner — that PR came in after 1.1.11 had been released to WP.org. It will be a part of the next release for sure. Is there a particular urgency around that fix? As I understand, that will come into play with Twig 2.0 which is not yet released

**Comment by developer-lindner** [comment]
Hey @jarednova unfortunately your're wrong here. The fatal error already happens with Timber 1.1.11 or better say with Twig 1.26 which comes with the composer install of Timber 1.1.11. That's why i had to pull the fix out of the github repo. You should release it soon ;)
