### ISSUE TITLE
Incorrect URL for files uploaded to subsites when using TimberSite class in theme

### ISSUE THREAD

**Issue by feshin** [timber/timber#1267]
First off, just want to say how much we love using Timber. It's really helped us simplify our theme (and our lives). 

This is a bit of a complex problem, so will do my best to describe it. 

Background: We're running a multisite with about 200 sites on it (large intranet). We started the multisite at about WP version 3.4 (mentioning this as it means our file uploads for subsites is the legacy blogs.dir/[blog_id] variety). We're now running version 4.5.3.  Our subsites are setup as subfolders.

I have no idea of the actual cause of the problem, but I was able to work around it. 

Here's the issue: In the parent theme (the same theme that drives subsites) I used the basics of the starter theme from the timber library download. I declared "class StarterSite extends TimberSite" and went about my business. Everything worked perfectly fine. By pure chance I noticed files uploaded on subsites were getting the wrong url. I tried disabling all plugins and tons of other things, but finally tried a completely different (non-timber) theme and the uploads started getting the correct URLs. I went back to my theme and started commenting parts out, finally landing on the class. I moved all of the functions and whatnot from inside that class out of it and then removed the class and the URLs are working correctly. 

Hopefully this rather long post (sorry) will help someone else out with the same problem. 

### Expected behavior

On a subsite, when uploading to the media library the URL for the image should be of this pattern:
http://intranet-site-name.org/site-name/files/year/month/filename.png

### Actual behavior

Files uploaded to the media library have URLs following this pattern:
http://intranet-site-name.org/site-name/wp-content/blogs.dir/[blog_id]/files/year/month/filename.png

### Steps to reproduce behavior

Use a class per the example in the starter theme bundled with timber-library in a theme on a multisite and upload files in a subsite (same theme activated on both main site and subsites). I've not actually tested this on a fresh multisite install, so not 100% sure these are the exact steps to reproduce it. Could be that since a multisite that uses the legacy blogs.dir for uploading is only affected.

```
class StarterSite extends TimberSite {

	// code n' stuff

}

new StarterSite();
```

### What version of WordPress, PHP and Timber are you using?

Wordpress version 4.5.3.
PHP version 5.3.3.
Timber version 1.1.8.

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Used WP-CLI (wordpress.org).

**Comment by jarednova** [comment]
I'm closing out old issues. Please open a fresh issue if this is still a live issue that we should investigate — thank you!
