### ISSUE TITLE
CDN not working

### ISSUE THREAD

**Issue by moazam1** [timber/timber#1270]
I am using roots/bedrock and Timber/twig for my WP site. I am using CDN enabler plugin but it doesn't seem working with my current setup. I have another wordpress site non timber where it works fine. Any idea how do I debug this issue?

**Comment by corradomatt** [comment]
@moazam1 are you caching the output of the twig files? I'd look there first. Although it doesn't seem like that should be the issue. Typically a plugin like that would just filter the paths on all assets.

**Comment by moazam1** [comment]
@corradomatt thanks for the reply. No, I am not caching pages yet. Just wanted to ask if I cache pages how do I clear cache. I don't see any Timber option in WP backend that let me purge cache. Thanks!

**Comment by corradomatt** [comment]
I clear cache programmatically in PHP.

As to your original issue, I'm going to go out on a limb and say that it's probably not an issue with Twig/Timber. If you use something like phpStorm with xdebug you can put some breakpoints on parts of your CDN plugin that should be loading things.

**Comment by moazam1** [comment]
@corradomatt thanks. I used w3tc and it worked fine.
