### ISSUE TITLE
TimberPost causing time outs

### ISSUE THREAD

**Issue by Beee4life** [timber/timber#1274]
My site worked as expected. Coming back into work today, I noticed TimberPost is causing a time out.

This is my code:

    {% if content_type != 'iconblock' %}
        {% set item         = TimberPost(item_id) %}
        {% set image_id     = item.image %}
        {% set image        = TimberImage( function( 'wp_get_attachment_image_url', image_id, 'PHOTO_S' ) ) %}
    {% else %}
        {% set image_id     = item.image_id %}
        {% set image        = TimberImage( function( 'wp_get_attachment_image_url', image_id, 'PHOTO_S' ) ) %}
    {% endif %}

When I hide TimberPost from my code, the page loads as expected (but without an image of course since this depends on item being set). When it's active, I get a 504 time out.

I have to use the wp_get_attachement_url due to our media database which is on another domain than the website itself, but this works without issues.

Screenshot of time-out
![181219 timberpost time-out](https://cloud.githubusercontent.com/assets/4508731/21311151/10e1e89a-c5e6-11e6-8114-c146561766ff.png)

WP 4.7
Timber 1.1.10
PHP 7.0.11

Timber is installed through composer/wpackagist.

I've been debugging in /lib/Twig.php in the plugin, lines 97-105.
$pid is set so I'm fairly sure `new $PostClass($pid)` is properly returned, but I don't know where it goes next, so can't tell yet.

**Comment by Beee4life** [comment]
If I hardcode a post id in `{% set item = TimberPost(item_id) %}` it shows what I expect, but if I use a variable there, the time out occurs again.

**Comment by mdaliyan** [comment]
Are you using `new $PostClass($pid)` in your template?

try to use something like this `{{#<?php $item = new $PostClass($pid); ?>}}`

I think twig has propbem phrasing that. I read it somewhere I don't remember where, but the syntax was something like that.

**Comment by Beee4life** [comment]
No I am not... I am not quite sure what happened... I went back 2 or 3 commits and redid the changes and then it worked without a hitch...

I do get an occasional time out... but nothing serious anymore... If I only knew what caused it....
