### ISSUE TITLE
theme_url_to_dir() isn't returning the correct result - Undefined index: dirname

### ISSUE THREAD

**Issue by daviddarke** [timber/timber#1279]
Having issues loading / cropping images located inside the theme folder.

Drilled down to see that when using theme_url_to_dir() on line 378 of timber-library/lib/ImageHelper.php
```php
$tmp = self::theme_url_to_dir($tmp)
```
The $tmp var returns blank if loading an image from the theme directory. The previous release used:
```php
$tmp = str_replace(content_url(), '', $tmp);
```
and returned this "/placeholders/website-site-placeholder.jpg". This file name is related to this example, so inside a twig template I have this:
```twig
<div class="card__image border__radius--left float--left">
	{% if post.thumbnail %}
	    <img src="{{post.get_thumbnail.src|resize(170,230,'center')}}" class="featuredImage" />
	{% else %}
	    {% set placeHolder = site.url ~ '/wp-content/placeholders/website-site-placeholder.jpg' %}
	    <img src="{{placeHolder|letterbox(170, 230, '#070C22')}}" />
	{% endif %}
</div>
```
This returns from the second half of the if statement when generating a placeholder:
```
Undefined index: dirname in <b>/var/www/website/wp-content/plugins/timber-library/lib/ImageHelper.php</b> on line <b>383</b><br />&#10;<br />&#10;<b>Notice</b>:  
Undefined index: dirname in <b>/var/www/website/wp-content/plugins/timber-library/lib/ImageHelper.php</b> on line <b>383</b><br />&#10;<br />&#10;<b>Notice</b>:  
Undefined index: extension in <b>/var/www/website/wp-content/plugins/timber-library/lib/ImageHelper.php</b> on line <b>385</b><br />&#10;http://website.dev/wp-content/placeholders/website-site-placeholder.jpg
```

Again this is because the pathinfo($tmp) on line 384 is being passed a blank variable.

**Comment by jackmcpickle** [comment]
yes I have the same issue. 

digging deeper seems to be coming from here? 
https://github.com/timber/timber/compare/1.1.12...1.2.0#diff-46be88a6b330f3590d156d5879bfcf4bR398

calling `realpath()` on a url returns false.

**Comment by jarednova** [comment]
Thanks @jackmcpickle and @daviddarke! Can one of you guys post a test case for a scenario that worked before that now fails? I want to make sure I have the exact situation re-produced (since this is passing the automated tests). @daviddarke I notice you're calling something from inside `/wp-content/placeholders`? Is that scenario also a case where this fails?

**Comment by daviddarke** [comment]
@jackmcpickle, @jarednova Cool, yeah this:

```
{% set placeHolder = site.url ~ '/wp-content/placeholders/website-site-placeholder.jpg' %}
<img src="{{placeHolder|letterbox(170, 230, '#070C22')}}" />
```

Doesn't crop the image, yet not in 'wp-content':

```
{% set placeHolder = site.url ~ '/placeholders/website-site-placeholder.jpg' %}
<img src="{{placeHolder|letterbox(170, 230, '#070C22')}}" />
```

Does return a cropped Image.

In 1.1.12 everything works as expected and both of the above returned cropped images.

**Comment by jarednova** [comment]
@daviddarke @jackmcpickle thanks for your patience! This one took me down a rabbit hole I almost didn't come back from. Please check out #1317 and see if that resolves the issue for you and/or any other feedback

**Comment by daviddarke** [comment]
Hi @jarednova will test asap!

**Comment by jackmcpickle** [comment]
Will do.

**Comment by jackmcpickle** [comment]
Looks like a winner. 💯

**Comment by jarednova** [comment]
Victory!

**Comment by daviddarke** [comment]
:)
