### ISSUE TITLE
Theme->Link returns incorrect 

### ISSUE THREAD

**Issue by xavivars** [timber/timber#1280]
### Expected behavior
According to the documentation,

`get_stylesheet_directory_uri() => {{ theme.link }}`

### Actual behavior

In some case (for example, when a theme is registered in a different directory than the root one: `register_theme_directory(ABSPATH . 'themes');` ) 

The result of `theme.link` is incorrect (even though `theme.uri` is correct. I'm using theme.uri in the mean time).

Issue was introduced in https://github.com/timber/timber/commit/0534cca259e2aa1fca544f18cc0fa3495fa01af1

### Steps to reproduce behavior
* Install a theme in a different folder, after creating a mu-plugin containing `register_theme_directory(ABSPATH . 'themes');`
* Validate that the result is not correct.

In my case, ABSPATH is my-domain/wp/, and my themes folder is outside it ( `ABSPATH . "../themes"`), and `theme.link` returns

`http://my-domain.com/wp/wp-content/themes/my-theme/`

instead of 

`https://my-domain/wp/../themes/my-theme/`

### What version of WordPress, PHP and Timber are you using?
1.2.0

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WordPress repository

**Comment by xavivars** [comment]
I think Timber\Theme should be a thinner  wrapper on top of WP_Theme. For example, theme link should be just `return $wp_theme->get_stylesheet_directory_uri()`

**Comment by jarednova** [comment]
Closed by #1281
