### ISSUE TITLE
CommentThread class missing from release

### ISSUE THREAD

**Issue by jakub300** [timber/timber#1287]
### Expected behavior

`CommentThread` class included in Timber release on WP.org

### Actual behavior

There is no `CommentThread` class. Also files `Comment.php` and `Post.php` differ between git branch `1.2.0` and actual 1.2.0 release.

### Steps to reproduce behavior

1. Download zip from https://downloads.wordpress.org/plugin/timber-library.1.2.0.zip and unpack it
2. Look for `CommentThread.php` file in the `lib` folder
3. File is missing

**Comment by jarednova** [comment]
Thank you so much @jakub300 — I'm not sure what happened there. It's now fixed and I'll push out a 1.2.0.1 so that existing users of 1.2 get the patch
