### ISSUE TITLE
get_posts gets same post_content for every post

### ISSUE THREAD

**Issue by carstenwawer** [timber/timber#1291]
## Remark: Even I can't reproduce this behaviour on my development-machine. It only occurs on a Ubuntu-Server. But it is so specific, that perhaps someone here has a hint for me?

It drove me crazy today, so any help is appreciated! Thanks!

### Expected behavior
get_posts should get a number of posts with their corresponding content

### Actual behavior
get_posts gives a number of posts, with all data correct, but the post_content, post_content is the post_content of the first post for all posts in this loop.

### What version of WordPress, PHP and Timber are you using?
 WordPress 4.7, PHP 7.0, Timber 1.2

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by carstenwawer** [comment]
i tracked the problem down to PostCollection-Init-Function.

```
if ( is_a($post_object, $post_class_use) ) {
	$post = $post_object;
} else {
	$post = new $post_class_use($post_object);
}
```

I changed the code to:

```
if ( is_a($post_object, $post_class_use) ) {
	$post = $post_object;
} else {
	var_dump($post_object);
	$post = new $post_class_use($post_object);
	var_dump($post_object);
}
```

And the $post_content changes (magicaly) from the correct content in the first dump to the wrong content in the second dump.

Anything I am missing here? It's late im Germany :-(

**Comment by gchtr** [comment]
Can you give some more context and show how/where you use `get_posts`? What arguments do you pass? Do you use it in a template file (index, archive, category, front-page, …)?

**Comment by carstenwawer** [comment]
Hi gchtr,

thanks for your response.

Nothing special when using get_posts. The get_posts is located in archive.php, but the behaviour is the same on all loops.

Here is the code in the archive.php

```
$context = Timber::get_context();
$context['posts'] = Timber::get_posts('post_type=post', 'SozisPost');
``` 

But i tried the get_posts without arguments, with more arguments an with other Classes. The described behaviour remains the same.

**Comment by carstenwawer** [comment]
Hi,

finally i got to reproduce the behaviour. It seems that the WP3-Offload-Plugin does not work well with Timber.

https://de.wordpress.org/plugins/amazon-s3-and-cloudfront/

Any idea how to fix it or another way to sync my uploads with AWS S3?

Best Regards,
Carsten

**Comment by gchtr** [comment]
There are [other open issues that report having problems with using S3](https://github.com/timber/timber/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20s3) and especially with that plugin, namely https://github.com/timber/timber/issues/510 and https://github.com/timber/timber/issues/1156 and https://github.com/timber/timber/issues/429.

It’s interesting that with your error, which is related to post contents, it might not be related to images only, but to the way that [WP Offload S3 Lite](https://de.wordpress.org/plugins/amazon-s3-and-cloudfront/) works in combination with Timber.

**Comment by carstenwawer** [comment]
Hi gchtr,

i had a look at the code of Wp3Offload. The Plugin adds a function called filter_post_data to the 'the_post"-hook.

```
public function filter_post_data( $post ) {
		global $pages;
		$cache    = $this->get_post_cache();
		$to_cache = array();
		if ( count( $pages ) === 1 ) {
			// Post already filtered and available on global $page array, continue
			$post->post_content = $pages[0];
		} else {
			$post->post_content = $this->process_content( $post->post_content, $cache, $to_cache );
		}

		$post->post_excerpt = $this->process_content( $post->post_excerpt, $cache, $to_cache );
		$this->maybe_update_post_cache( $to_cache );
	}
```

Is it possible that Timber does not update the global $pages, when looping through the loop? My correct post_content is overwitten here with $pages[0], that contains the content of the first post in the loop.

**Comment by danburzo** [comment]
Hi everyone, just came here to second that enabling the AWS S3 plugins messed up the post.content on my pages instantly :)

**Comment by gchtr** [comment]
The changes we made in #1778 also address this issue. It will (hopefully) not occur as soon as Timber 2.x will be released. I’m going to close this for now. Feel free to comment on this issue or open a new one in case this won’t work in 2.x. There’s no definite release date for 2.x yet, but we’re working hard on it.

**Comment by rimager** [comment]
Just curious about the status of this. I too use WP Offload Media with Timber 1.19.1. WP Offload Media for S3 and the post.content isn't working in some instances. Is there a workaround for those of us on Timber 1?
