### ISSUE TITLE
Is there a reasonable way to disable the twig part of timber?

### ISSUE THREAD

**Issue by unstoppablecarl** [timber/timber#1297]
I'm interested in the data layer OO code that timber provides, but not the twig part. 

I want to use Timber with Themosis http://framework.themosis.com/ which already has a templating layer including twig.

**Comment by unstoppablecarl** [comment]
I've setup the following class which seems to work fine so far:

```php
namespace Theme\Services;

use Timber\ImageHelper;
use Timber\Integrations;

use \Timber\Timber as Base;

class Timber extends Base {

    protected static function init() {
        if ( class_exists('\WP') && !defined('TIMBER_LOADED') ) {
//            Twig::init();
            ImageHelper::init();
//            Admin::init();
            new Integrations();
            define('TIMBER_LOADED', true);
        }
    }
}
```

**Comment by halian-vilela** [comment]
I'm really curious on what Themosis offer that couldn't be achievable in a similar way with Timber. Could you give your 2 cents?

Thanks

**Comment by unstoppablecarl** [comment]
@halian-vilela 
Reasons I'm using Themosis:
- it uses illuminate/laravel modules that I like and am familiar with
  - view layer that is templating engine agnostic
  - router that I know inside and out
  - laravel app -ish filestructure I am familiar with, also using wp as a dependency
  - dependency injection
  - controllers, and controller routing with DI

Goto http://framework.themosis.com/docs/1.3/ and look at the list in the sidebar under Wordpress. All of those are either not in timber or are in timber and seem to be written to be integrated with twig not so much to be clean and simple.

Timber (like wp) seems to put undue importance on templating. This is somewhat reasonable as it is built into wp which does the same. I want something that is more MVC and avoids nonsense like the wp loop and its enigmatic routing system.

I do very much like the data layer parts of Timber that Themosis currently does not attempt to tackle other than wrapping them in model classes.

**Comment by nlemoine** [comment]
You can override the `Timber::init` method and remove the Twig parts to do that.
