### ISSUE TITLE
Pulling post on to static front page

### ISSUE THREAD

**Issue by frazerf** [timber/timber#1301]
Hi there, I'm trying to pull my posts on to a static front page but I'm not having much luck. I'm trying to show the most recent post in the hero section of the homepage and then have a link to the second most recent post at the bottom.

Similar to this - http://amory.premiumcoding.com/

I have a front-page.twig file and a front-page.php file.

**My front-page.php looks like this -** 

$context = Timber::get_context();
$post = new TimberPost();
$context['post'] = $post;
Timber::render( 'front-page.twig', $context );

**and my front-page.twig looks like this -** 

{% extends "base.twig" %}

{% block content %}
	{{post.title}}
	{{post.content}}
{% endblock %}

Could anyone lend me a hand? I've trawled through the docs but I just can't seem to see how to do this or if it's possible on a static front page.

**Comment by rideron89** [comment]
If I'm to understand you correctly, you probably want something like this:

**front-page.php**
```php
// these docs should help you,
// http://timber.github.io/timber/#get_posts
$context['posts'] = Timber::get_posts( /* insert query here */ );
```

**front-page.twig**
```twig
{# loop through the posts #}
{% if posts|length %}
    {% for post in posts %}
        Title: {{ post.title }}
    {% endfor %}
{% endif %}

{# or this will display only the first post  #}
{% set post = posts|first %}
Title: {{ post.title }}
```

**Comment by corradomatt** [comment]
also @frazerf - don't forget that you're likely dealing with the global $post object from the page request already. You might run into conflicts with that.

**Comment by halian-vilela** [comment]
@frazerf 

Yeah, @corradomatt is right. Do not forget that there is not a "post title" in your `post` object because the way you called it makes it a **set** of posts.

You need to loop through this object (just like @rideron89 said) to get the individual posts. 

**Tip:** when dealing with this kind of behaviour, always investigate your variable with `{{dump()}}`, it will show you the content of the entity you're trying to use.

**Comment by jmp909** [comment]
here's what I do


```php
$context = Timber::get_context();
$post = new TimberPost();
$context['post'] = $post;

$quote = getRandomQuote();
$context['quote'] = $quote;

$blog_entry = Timber::get_posts(
	array(
    	'post_type' => array('post'),
    	'posts_per_page' => 1
    )
);

$context['preview'] = true;
//$context['blog_entry'] = new TimberPost($blog_entry[0]);
$context['blog_entry'] = $blog_entry[0];


Timber::render( array( 'page-' . $post->post_name . '.twig', 'page.twig' ), $context );

**Comment by jmp909** [comment]
here's what I do

**front-page.php**
```php
$context = Timber::get_context();
$post = new TimberPost();
$context['post'] = $post;

$blog_entry = Timber::get_posts(
  array(
    'post_type' => array('post'),
    'posts_per_page' => 1
  )
);

$context['blog_entry'] = $blog_entry[0];
Timber::render( array( 'page-' . $post->post_name . '.twig', 'page.twig' ), $context );
```

**front-page.twig**
```php
... etc ...
{% include "partials/blog-tease.twig" %}
.. etc...

<!-- link to previous post -->
{% if blog_entry.prev %}
<a href="{{blog_entry.prev.link">{{blog_entry.prev.title}}</a>
{% endif %}
```

**tease-post.twig**
```php
.. etc..
<h1>{{blog_entry.title}}</h1>
```
theoretically you could use

```{% include "partials/blog-tease.twig with { 'post' : blog_entry } %}```

and just reference `post` from within your `tease-post.twig`

**Comment by frazerf** [comment]
Perfect! Thanks @jmp909 Exactly what I was after. Thanks everyone else for your help too.
