### ISSUE TITLE
Issue with ACF Flexible Content

### ISSUE THREAD

**Issue by garthreckers** [timber/timber#1302]
I am trying to use ACF Flexible Content with Timber but it seems that I can't get the examples in the documentation to work.

The issue I am seeing is that post.get_field('content') is an array of the layout names only (dont need to use .acf_fc_layout). I have been able to get the the conditionals to work but I have no idea how to access the sub fields. Here is the working code I have so far:

```
{% for con in post.get_field('content') %}
    {% if con == 'rich_text' %}
        {% include 'twigs/partials/_rich_text.twig' %}
    {% elseif con == 'team' %}
        {% include 'twigs/partials/_team.twig' %}
    {% elseif con == 'benefits' %}
        {% include 'twigs/partials/_benefits.twig' %}
    {% endif %}
{% endfor %}
```

Using Wordpress 4.6.1 on PHP7 with ACF (not pro) 4.4.11 and flexible content plugin 1.1.1.

Timber 1.2.1 installed via composer

**Comment by garthreckers** [comment]
Was able to get it to work like the documentation by downgrading to Timber 1.0.5. Anything about 1.1 seems to return the array of names. Is there an updated documentation for 1.1 and up?

**Comment by gchtr** [comment]
@garthreckers What if you use a different name than `content` for the flexible field, maybe `flexible_content`? I’ve run into strange problems with field names that are also methods of a TimberPost, like "content" or "title".

**Comment by jnssthl** [comment]
@gchtr Nope, doesn't seem to make a difference.

**Comment by mrcsmcln** [comment]
It looks like to me that the `Timber\Integrations\ACF` class isn't being instantiated. By simply adding `new Timber\Integrations\ACF` to an `init` hook, it worked for me.

**Comment by gchtr** [comment]
@mrcsmcln Does it also work if you initialize it directly in **functions.php** (like described in <http://timber.github.io/timber/#installation>)?

```
new \Timber\Timber();
```

**Comment by mrcsmcln** [comment]
Hah, didn't see that little bit. Yes, it works.

**Comment by gchtr** [comment]
@garthreckers @jnssthl Does it work for you if you use `new \Timber\Timber();` in your functions.php, too?

**Comment by palmiak** [comment]
Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
