### ISSUE TITLE
{{ fn('wp_nonce_field', 'action', 'name') }} produces double output

### ISSUE THREAD

**Issue by piotrkulpinski** [timber/timber#1314]
### Expected behavior
Should display 2 tags (nonce name and nonce referrer).

### Actual behavior
Displays 4 tags (name x2, referrer x2).

### Steps to reproduce behavior
{{ fn('wp_nonce_field', 'action', 'name') }} 

![](https://www.dropbox.com/s/nndskvpm46lzu1y/Screenshot%202017-01-31%2015.40.38.jpg?dl=1)

### What version of WordPress, PHP and Timber are you using?
Example: WordPress 4.7.2, PHP 5.6, Timber 1.2.1

### How did you install Timber?
Upgraded to newest version via plugin updater in WordPress dashboard

**Comment by piotrkulpinski** [comment]
Figured out the issue.
I needed to pass the fourth parameter as false, to prevent function from echoing the output:
`{{ fn('wp_nonce_field', 'action', 'name', false, false) }}`

**Comment by VincentLoy** [comment]
thanks ! It works
