### ISSUE TITLE
How to use ACF 'File' Field

### ISSUE THREAD

**Issue by elliottmangham** [timber/timber#1315]
Hello,

I have a ACF 'File' Field on my site but it is not outputting properly on my archive page.

I've tried with the setting to output 'File URL' and using the following code:
`$context['file_url'] = get_field( 'file_url' );`
And `{% for post in posts %}{{ post.file_url }}{% endfor %}` to display it.

I've also tried using an array:
```
$file = get_field( 'file' );
$context['file_url'] = $file['url'];
```
And `{% for post in posts %}{{ post.file_url }}{% endfor %}` to display it.

But none of the above work, I've even tried outputting the ID and using `$file = wp_get_attachment_url( $file )` but that doesn't work either.

How can I display my file field information on my archive template within the for each post?

Thanks in advance

**Comment by jarednova** [comment]
@elliottmangham from the code it looks like it's just an issue with how you're sending data, if you have...

```php
$file = get_field( 'file' );
$context['file_url'] = $file['url'];
```

It will be available in Twig as...

```twig
Download my file: {{ file_url }}
```

... as opposed to making it a child of the `post` object

**Comment by elliottmangham** [comment]
@jarednova I have tried that and while it does appear to post the file url, it is displaying the same one for all posts on the page. It is displaying the latest post on all of them as opposed to the relevant one. Any ideas?

Kind regards

**Comment by elliottmangham** [comment]
@jarednova I am having to do the following to find the guid, is there not a better Timber-based solution?

`foreach($context['posts'] as $post) {
	if($post->file) {
		$post->file = get_post($post->file)->guid;
	}
}`

This is in an 'archive-{custom-post-type}.php' file. I'm just trying to find the data for the 'ACF File Field' in each post.

Thanks in advance.

**Comment by jarednova** [comment]
Hey @elliottmangham this should also work if you want to skip the PHP...

```twig
{% for post in posts %}
    <a href="{{ post.get_field('file'}.guid }}">Download</a>
{% endfor %}
```

... give that a shot and let me know how it goes

**Comment by gchtr** [comment]
Hey @elliottmangham 

If you have the file ID, you can convert it to a TimberImage (you can think of a TimberImage as an attachment, you can also use it on non-images). Then you can access all the information you need.

**PHP**

```php
foreach ( $context['posts'] as &$post ) {
    // Convert attachment id to TimberImage object
    $post->file = new \Timber\Image( $post->file );
}
```

When you now look `$post->file`, the only field that has the URL in it is `guid`. But the purpose of `guid` is not to access the URL of a file. Instead, use the `src` method of your TimberImage object to get the URL. 

**PHP**

```php
$url = $post->file->src();
```

**Twig**

```twig
{% for post in posts %}
    {# Access the URL of the file through file.src #}
    <a href="{{ post.file.src }}">Download {{ post.file.title }}</a>
{% endfor %}
```

**Twig only**

```twig
{% for post in posts %}
    {% set file = TimberImage(post.file) %}
    <a href="{{ file.src }}">Download {{ file.title }}</a>
{% endfor %}
```

**Comment by elliottmangham** [comment]
@gchtr perfect, thanks! Worked straight off the bat.

**Comment by elliottmangham** [comment]
Hi @gchtr,

Unusually - while this does work... It converts the file (PDF) into a jpeg. So when the user clicks on the entry, I want it to open the PDF file that was uploaded. But by using your technique, it opens the PDF prepended with .jpeg. I.e. 'file_name.pdf.jpeg'.

Please help!

Kindest regards,

**Comment by gchtr** [comment]
@elliottmangham I think this is an error that was fixed in https://github.com/timber/timber/pull/1365.

Can you install the latest release 1.3.0-beta (https://github.com/timber/timber/releases/tag/1.3.0-beta) and check if that still happens?

**Comment by palmiak** [comment]
@elliottmangham Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
