### ISSUE TITLE
Images stored on S3 return NULL for width/height

### ISSUE THREAD

**Issue by jarednova** [timber/timber#1321]
Spun from #429 

### Expected behavior
`{{ image.width }}` should always return an integer based on the width of the image (same goes for height)

### Actual behavior
Images stored on S3 return `null`

**Comment by tvanantwerp** [comment]
Sorry for late response--was AFK for a bit. Is this in 1.2.4? I've upgraded locally and tested this with a new post and image upload and still get `NULL`.

**Comment by jarednova** [comment]
Ugh!!! can you let me know what steps you followed? I did a local test (see above) but got the values I was expecting

**Comment by tvanantwerp** [comment]
Running WordPress 4.7.2 on MAMP with Apache and PHP 7.0.12. I first tried WordPress's plugin updates. When that failed, I tried manually deleting and replacing all of Timber with the latest download from wordpress.org.

This:
```
{{dump(post.thumbnail.width)}}
{{dump(post.thumbnail.height)}}
```

Returns this:
```
NULL
NULL
```

**Comment by 75th** [comment]
Same here on 1.7.1. Workaround is to use `unserialize($post->thumbnail()->_wp_attachment_metadata)['width']` in PHP.

**Comment by piotrkulpinski** [comment]
Is this issue resolved?
I'm still experiencing this while using WP Offload Media plugin.

**Comment by gchtr** [comment]
Based on the reports it seems like this is still an issue. Reopening.

**Comment by Levdbas** [comment]
As discussed yesterday, we are going to close this since this is such an old issue. If anyone still runs into issues, please let us know.

**Comment by conwaydev** [comment]
@Levdbas this is till definitely an issue for users of https://github.com/humanmade/S3-Uploads

**Comment by Levdbas** [comment]
Hi @conwaydev , are you able to help us debug this issue?
