### ISSUE TITLE
Best ecommerce plugin

### ISSUE THREAD

**Issue by davidrhoderick** [timber/timber#1327]
I discovered Timber from working on a client's project and I truly love it.  I was messing around this weekend and tried to work with Woocommerce and found it wasn't too simple.  Has anyone found an ecommerce plugin that integrates well (cleanly and easily) with Timber?

**Comment by adamk22** [comment]
Unfortunately, I believe WooCommerce is still the way to go. I've managed to integrate it with my timber setup using the wiki and this example: https://github.com/niklasravnsborg/blender-shop. However, All WooCommerce/Timber integration issues in this repo all point to issue #79 for the most part and that one is closed as well, so I am not sure what the ETA is on a woo/timber start theme.
