### ISSUE TITLE
php 5.3 compatibility breaks with 1.2.3

### ISSUE THREAD

**Issue by FlickerBean** [timber/timber#1328]
Breaks functionality with syntax error. See #1320 

Also 

b1387e44 lib/PostGetter.php               124

uses the is_a function with the third parameter, which is not supported in php 5.3.3.

**Comment by jarednova** [comment]
Thanks @FlickerBean. Unfortunately I haven't found a PHP 5.3 workout for the `is_a` method — do you have any ideas? With PHP 5.3 end-of-life being 2014, I'm no longer officially supporting it (but if there are quick fixes to make it compatible, I'm def open to making those)

**Comment by FlickerBean** [comment]
I can totally appreciate not wanting to jump through lots of hoops to support 5.3.3. But there are 5.3.3 users of the plugin, and I didn't see a min supported version noted anywhere. People might get upset when they update their plugin and their site 500's!

If i'm entirely honest, I'm not fully clued up on the intricacies of `is_subclass_of()` vs `is_a()`.
But, if i'm understanding the php documentation, could we not just instantiate `$post_class_use` and drop the third `allow_string` parameter?

From:

```
if ( !class_exists( $post_class_use ) || !( is_subclass_of( $post_class_use, '\Timber\Post' ) || is_a( $post_class_use, '\Timber\Post', true ) ) ) {
    Helper::error_log( 'Class ' . $post_class_use . ' either does not exist or implement \Timber\Post' );
}
```

To:

```
$test_post = false;
if ( class_exists($post_class_use) ) {
    $test_post = new $post_class_use();
}
if ( !$test_post || !( is_subclass_of( $test_post, '\Timber\Post' ) || is_a( $test_post, '\Timber\Post') ) ) {
    Helper::error_log( 'Class ' . $post_class_use . ' either does not exist or implement \Timber\Post' );
}
```


This would fix `is_subclass_of()` also. As the documentation states that like `is_a()` you cannot pass it a string without passing `true` through to the third parameter in >=php5.3.9. Which we aren't doing currently.

Note I've just typed this out here, I haven't tested it at all but it should work.

**Comment by jarednova** [comment]
@FlickerBean thanks for the heads-up on this. One of the things that makes keeping things working with PHP 5.3 is that lots of the other dependencies also require PHP 5.6 or 7. That said, I did tests on a stripped-down version:

https://travis-ci.org/timber/timber/builds/204330766

.... and things are all-green now!

**Comment by jarednova** [comment]
If @anyone knows how the composer.json and travis file could be configured to use older versions of dependencies w PHP 5.3; let me know! I'd love to keep things working for 5.3 as long as possible
