### ISSUE TITLE
wp_link_pages not implemented

### ISSUE THREAD

**Issue by srajbr** [timber/timber#133]
WordPress provides the  quicktag to divide pages into multiple pages. Timber currently lacks this features.

**Comment by SlawaGurevich** [comment]
Is there a solution for this issue yet? I am also trying to use the pagination for a single post. However, Timber just ignores the . This is what I get from the pagination dump.

array(4) { ["current"]=> int(1) ["total"]=> float(1) ["pages"]=> array(0) { } ["prev"]=> string(0) "" }
