### ISSUE TITLE
How to stop a html element from rendering if a field is not present

### ISSUE THREAD

**Issue by NicolaSansom** [timber/timber#1333]
I am currently using Timber with ACF and I have an optional image field I have looked over the documentation but could not figure out if there is a way to not render the image element if the source is unknown(ie been left blank in the repeater).

Thanks 
Nicola

**Comment by hbrok** [comment]
You can wrap an if statement around the element you want to conditionally show:

```twig
{% if post.image %}
   <img src="{{ post.image }}" alt="">
{% endif %}
```

**Comment by NicolaSansom** [comment]
@hbrok That worked a treat thanks!
