### ISSUE TITLE
Unofficial Timber Help & Support Facebook Group

### ISSUE THREAD

**Issue by Infusednl** [timber/timber#1334]
Hi all,

This isn't directly a support issue however since support can take a while and the documentation can be confusing sometimes in my opinion, I have created an unofficial Facebook group called 'Timber Wordpress Framework' in the hopes it will help and grow the awesome Timber community.

Here's the link: https://www.facebook.com/groups/728465927323532/

I saw that systems like WooCommerce and Divi already have such Facebook groups for helping and sharing knowledge but couldn't find them for Timber.

I know this isn't the right place to post such a thing but except a few other Facebook groups I couldn't find a good/correct place to inform other users of this. If there is a better place to let other Timber users know then please send me a message before deleting this as I only want to help and grow the awesome Timber community. :)

Best regards,

Christiaan

**Comment by jarednova** [comment]
Hi @Infusednl — thanks for setting that up! We have a [Gitter channel](https://gitter.im/timber/timber) for discussion, quick questions and such. I wish it were more active (I _should_ participate more, but getting time...)

**Comment by Infusednl** [comment]
Hi @jarednova Thanks for the quick response! I know, everyone is quote occupied, that's exactly the reason I set the Facebook group up so me and other users can help eachother and hopefully you'll get a bit more rest. :p

But is it possible to add an extra section to the online documentation with links to the Gitter channel and Facebook group(And maybe others in the future too)?

Most Timber users will surely check the documentation regularly and by adding such section it will be much easier for others to find. For example I myself didn't knew about the Gitter channel as I am fairly new to Git.

**Comment by gchtr** [comment]
Closing this. If you want to have your community added to the documentation, please open a pull request :).
