### ISSUE TITLE
Problem with get_preview within <a> tag

### ISSUE THREAD

**Issue by stevebasford** [timber/timber#1335]
### Expected behavior
An ```<a>``` with ```<p>{{post.get_preview(25)}}</p>``` nested inside.

### Actual behavior
The ```<a>``` tag seems to fail to wrap the content. It works fine if the <a> tag is a div instead and it works fine if the get_preview helper isn't used inside the <p>. I can't work out the reason for this.

### Steps to reproduce behavior
```twig
{% for post in posts %}
  <a>
    <h2>Heading</h2>
    <p>{{post.get_preview(25)}}</p>
  </a>
{% endfor %}
```

### What version of WordPress, PHP and Timber are you using?
Wordpress 4.7.2, PHP 7.0, Timber 1.2.4

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Installed via Add Plugins in Wordpress dashboard

**Comment by jarednova** [comment]
@stevebasford check the actual output in View Source (not the Chrome inspector) I think the problem lies in that `get_preview` outputs a link to the article (ie `<a href="http://example.org/my-story">Read More</a>`) and in HTML you can't nest a tags in a tags.

**Comment by jarednova** [comment]
@stevebasford that said, I'm all for finding a solution: what about syntax like... `<p>{{ post.preview.link(false) }}</p>`

**Comment by stevebasford** [comment]
@jarednova ah I see what you mean, I've now removed the read more link to get it working. Thanks for your help :)
