### ISSUE TITLE
Timber excerpt does not strip content of <style> tags

### ISSUE THREAD

**Issue by pranksinatra** [timber/timber#1338]
### Expected behavior
Given a post with the content: 
`[gallery ids="1,2,3"] Hello world!`

I'd expect the following excerpt to be generated by `get_preview()`:
`Hello world!` or perhaps `Caption for attachment #1 ... Hello world!`

### Actual behavior
Excerpt contains a bunch of CSS selectors:
`.gallery { margin: 1em 0 0 -.5em; overflow: hidden; ...`

### Steps to reproduce behavior
Create a post that begins with a shortcode that outputs CSS before HTML. In my case, the `[gallery]` shortcode returns a Twig template like this: 
```html
<style>
.gallery { 
  margin: 1em 0 0 -.5em; 
  overflow: hidden;
}
.gallery__item { 
  margin: 0;
  ...
}
</style>
<section class="gallery">
...
</section>
```

Timber strips tags in excerpts, which is great, but it doesn't distinguish between tags that contain content (e.g. `<p>`, `<a>`, `<h2>`) and `<style>` or `<script>` tags. In this case, it strips the wrapping `<style>` but includes its content in the excerpt.

### What version of WordPress, PHP and Timber are you using?
WordPress 4.7.2, PHP 7.0, Timber 1.2.3

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Via WP.org as a plugin.

**Comment by jarednova** [comment]
@pranksinatra — good news! I made a fix for this in #1339. I'll push it out in the next version!

**Comment by pranksinatra** [comment]
Just a heads up that this is now fixed in the PostPreview, but not in the Post->get_preview() function.

**Comment by jarednova** [comment]
@pranksinatra thanks for that heads-up. I should have deprecated `get_preview` a while ago. I've added that note now (but have also applied the fix since I know it's used in plenty of places)
