### ISSUE TITLE
Patch for 5.3 compatibility makes TimberStream throws Exception, bailing meta fields save

### ISSUE THREAD

**Issue by tzkmx** [timber/timber#1341]
### Expected behavior
Users provide lots of meta fields in boxes and hooks provided by other plugins, on saving of the posts Streams are updated properly and people work without changes to their workflow.

### Actual behavior
- On saving the post through Publish action without saving meta fields first, site renders a 500 error response. Logs reveal TimberStream is instantiated without a Post ID, throws Exception because TimberPost recovered is not of 'sm_stream' custom post type.
- Debugtrace shows error is because PostGetter::get_post_class doesn't trust anymore $post_class argument passed, see upstatement/stream-manager#52 for trace dump

### Steps to reproduce behavior
- Install and activate plugins from wordpress.org: timber-library v.1.2.4 and Stream Manager 1.0.1
- In order to test meta fields not being saved, Yoast SEO plugin is a good option
- Create a post without saving it before Publish.
- Publish and see things break apart. Logs show error: `TimberStream of  is not of sm_stream post type` (yes, no $post_id passed on instantiation by line 123 of PostGetter class)

### What version of WordPress, PHP and Timber are you using?
WordPress 4.7.2, PHP 5.6, Timber 1.2.4, Stream Manager 1.0.1

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Timber and Stream Manager installed from WP.org

**Comment by palmiak** [comment]
Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
