### ISSUE TITLE
ACF Category Checkbox, Display post associated with selected Category

### ISSUE THREAD

**Issue by lance1572** [timber/timber#1342]
## **This is question**

Hi Really a noob with this. I'm trying to display posts asscociated with categories checked from ACF. I am able to grab the name of the category but not sure how to grab the posts that belong to them. In the doc it says you can grab posts from Displaying a term's associated posts. Am I misunderstanding this? 

I have this in my template-home.php file

    $context = Timber::get_context();
    $context['post']= new TimberPost();

    $args  = 'post_type=post&numberposts=2'; // for another loop
    $context['posts'] = Timber::get_posts($args); // for another loop

    $context['categories'] = Timber::get_terms('category');

    Timber::render('template-home.twig', $context);

My Twig File has this

    {% for featured_topic in post.get_field('featured_topics')  %}
		<div class="col-md-4 featured-topics-widget">
			<h4>{{featured_topic.name}}</h4>
				

				{% for topic in categories %}
					

					
				{% endfor %}

		</div>
		
	{% endfor %}

**Comment by jarednova** [comment]
@lance1572 looks like you also posted this to [StackOverflow](http://stackoverflow.com/questions/42570245/timber-twig-show-posts-associated-with-category) (thanks! that's the best place for questions like this) — I'll follow-up with more info there...
