### ISSUE TITLE
ACF Repeater field ONLY returns the number of elements in the repeater as string, instead of an array of each element.

### ISSUE THREAD

**Issue by Alfie-mx** [timber/timber#1351]
### Expected behavior
When using in twig `{% for logo in post.get_field('logos') %} {% endfor %}` , logo should be an array of each element in the repeater.

### Actual behavior
Doing a `{{ dump(post.get_field('logos') }}` or `{{ dump(post.logos) }}` only returns the number of elements in the repeater field as String, instead of an array with all elements in the repeater. 
I was using a very old version, I think 0.21, until few weeks ago when I decided to upgrade my theme and in that old version the excepted behaviour works like charm.
Unfortunately is not the same behaviour in the latest version.

FYI: I have two repeaters one of Image Fields and another one with Text Fields and both of them return ONLY the count of elements in the Repeater.

I have attached the JSON of my ACF fields.
[acf-export-2017-03-12.json.zip](https://github.com/timber/timber/files/836781/acf-export-2017-03-12.json.zip)

### Steps to reproduce behaviour
ACF setup:

I have a Repeater field of Image Fields and the Image Field with the Return Value setup to Image Array.

PHP file:
```
$context = Timber::get_context();
$post    = new TimberPost();
$context['post'] = $post;
```

Twig file:
```
{% for logo in post.get_field('logos') %}
    {{ dump('logo') }}
{% endfor %}
```
This loop doesn't return anything, I think because post.get_field('logos') is a String only so it is not an array.

And

```
{{ dump(post.get_field('logos')) }}
```
This dump returns `string(1) "2"` because I have two images in the Repeater field.

 

### What version of WordPress, PHP and Timber are you using?
WordPress 4.7.3, PHP 5.6, Timber 1.2.4, Twig 1.32.0, ACF PRO 5.5.10

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Via Composer

**Comment by Alfie-mx** [comment]
So I'll close this issue. The problem was that an instance of Timber wasn't created. So I just added `new Timber\Timber();`
The weird thing is that I wasn't getting any errors at all. So it was time consuming to debug it.

**Comment by markhowellsmead** [comment]
Meanwhile, three years later, with ACF Pro 5.8.8: if you're registering the field group in PHP, make sure you do so on the `init` hook, not `acf/init`. This will then give you the array you're expecting.
