### ISSUE TITLE
{{dump(post)}} output not formatted

### ISSUE THREAD

**Issue by pbolger** [timber/timber#1353]
For some reason {{dump(post)}} doesn't output formatted, see below. Any ideas on debugging the debugger?

` " ["post_parent"]=> int(0) ["post_status"]=> string(7) "publish" ["post_title"]=> string(61) "Pair of Italian Cherrywood Stools In The Manner of Ico Parisi" ["post_type"]=> string(7) "product" ["slug"]=> string(61) "pair-of-italian-cherrywood-stools-in-the-manner-of-ico-parisi" ["__type":protected]=> NULL ["_regular_price"]=> string(3) "975" ["_length"]=> string(3) ".62" ["_width"]=> string(3) ".31" ["_height"]=> string(3) ".45" ["_product_attributes"]=> array(1) { ["pa_seating-type"]=> array(6) { ["name"]=> string(15) "pa_seating-type" ["value"]=> string(0) "" ["position"]=> string(1) "2" ["is_visible"]=> int(0) ["is_variation"]=> int(0) ["is_taxonomy"]=> int(1) } } ["_sale_price"]=> string(0) "" ["_sale_price_dates_from"]=> string(0) "" ["_sale_price_dates_to"]=> string(0) "" ["_price"]=> string(3) "975" ["_sold_individually"]=> string(0) "" ["_manage_stock"]=> string(3) "yes" ["_backorders"]=> string(2) "no" ["_stock"]=> string(8) "1.000000" ["_upsell_ids"]=> array(0) { } ["_crosssell_ids"]=> array(0) { } ["_product_version"]=> string(6) "2.6.14" ["_product_image_gallery"]=> string(9) "2813,2813" ["_aviaLayoutBuilder_active"]=> string(0) "" ["_aviaLayoutBuilderCleanData"]=> string(0) "" ["layout"]=> string(0) "" ["sidebar"]=> string(0) "" ["footer"]=> string(0) "" ["header_title_bar"]=> string(0) "" ["header_transparency"]=> string(0) "" ["_product_hover"]=> string(0) "" ["_avia_hide_featured_image"]=> string(1) "0" ["_visibility"]=> string(7) "visible" ["_stock_status"]=> string(7) "instock" ["_enable_pep"]=> string(3) "yes" ["_enable_price"]=> string(3) "yes" ["_virtual"]=> string(2) "no" ["_tax_status"]=> string(7) "taxable" ["_tax_class"]=> string(0) "" ["_purchase_note"]=> string(0) "" ["_featured"]=> string(2) "no" ["_weight"]=> string(0) "" ["wccf_cached_price"]=> array(2) { ["p"]=> string(3) "975" ["h"]=> string(8) "50d3c640" } ["_downloadable"]=> string(2) "no" ["_enable_add_to_cart"]=> string(3) "yes" ["_thumbnail_id"]=> string(4) "2815" ["_edit_lock"]=> string(12) "148`

**Comment by sampohaavisto** [comment]
Wrap it in with `<pre class="dump">{{ dump(post) }}</pre>`. That's what I'm using in PHP. You can then stylize `.dump` with:

```
pre.dump {
  display: block;
  width: 100%;
  clear: both;
  color: #000 !important;
  background: #ccc !important;
  text-transform: none !important;
}
```

Better yet, try making this a filter or an extendable component. I'm not there yet as I just started with Timber but worth checking out.

**Comment by pbolger** [comment]
Thanks. I'm still curious as to why it's not working OOTB though.

**Comment by jarednova** [comment]
@pbolger if you did a "View Source" (command-U) you would see that it's all formatted. The issue is that Chrome (or a lesser web browser) is interpreting as HTML which ignores spaces/returns. While I can see the logic of pre-formatting for HTML output, this is a built-in Twig function so I'm hesitant to modify

**Comment by pbolger** [comment]
Yeah, it's Chrome. Maybe I'll switch back to FF. Although the reason I stopped was that it seemed be suffering from memory hogging JS issues last time I used it for development.
