### ISSUE TITLE
TimberImage src function will return NULL if the attachment is PDF

### ISSUE THREAD

**Issue by hoandang** [timber/timber#1362]
The behaviour was correct in version 1.2.1. However, in the version 1.2.4, it looks like the src function now handles only image attachment and returns false for pdf attachment.

    $attachment = new TimberImage(<image_id>);
    $attachment->src() // return correct path

    $attachment = new TimberImage(<pdf_id>);    
    $attachment->src() // return NULL

**Comment by jarednova** [comment]
PDFs!!!! what will they think of next???

**Comment by jarednova** [comment]
but yes, I agree it should return the correct src — @hoandang, is this something you'd be able to look at and submit a PR?

**Comment by jarednova** [comment]
Closed by #1365
