### ISSUE TITLE
Passing comment class as a parameter to get_comments function doesn't work

### ISSUE THREAD

**Issue by yantei** [timber/timber#1363]
### Expected behavior

My class should be used in dumped object (object MyOwnComment)

### Actual behavior

I always get object(Timber\Comment) no matter of fifth parameter of TimberPost get_comments function

### Steps to reproduce behavior

$post->get_comments(null, 'wp', 'comment', 'approve', 'MyOwnComment')

### What version of WordPress, PHP and Timber are you using?

Wordpress 4.7, PHP 7.0.4, Timber 1.1.12

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

I've installed with composer in theme directory

**Comment by jarednova** [comment]
That's no good! Thanks for the heads-up @yantei; I'll investigate and get back to you

**Comment by jarednova** [comment]
Thanks again for the report @yantei — this is solved in #1364
