### ISSUE TITLE
Image metadata from ACF gallery?

### ISSUE THREAD

**Issue by LinkinGeorge** [timber/timber#1368]
Hi there,

I wanted to display image metadata of images from a gallery added with Advanced Custom Fields, is that possible?
So far, I've tried this (and a few other things too which didn't work either):
**front-page.php** 
`<?php
/**
 * The front page template file
 */

$context = Timber::get_context();
$post = Timber::query_post();
$context['post'] = $post;
Timber::render( 'home.twig', $context );`

**home.twig**
`{% extends "base.twig" %}

{% block content %}
    {% for image in post.get_field('gallery') %}
        <img src="{{ TimberImage(image).src }}">
        <p>{{ post.wp_get_attachment_metadata(TimberImage(image).id)["aperture"] }}</p>
    {% endfor %}
{% endblock content %}`

Thanks for your answer, I hope you can help me! :)

**Comment by jarednova** [comment]
Hi @LinkinGeorge! I'm trying to keep the GH issues clean for bugs and other problems with the Timber code. Could you please post your issue to StackOverflow? Thanks!

http://stackoverflow.com/questions/tagged/timber
