### ISSUE TITLE
Resize filter not working on woocommerce product tease page

### ISSUE THREAD

**Issue by boochamoocha** [timber/timber#1369]
### Expected behavior
I want to resize thumbnail on woocommerce product tease view.

### Actual behavior
Nothing happens, crop image not created.

### Steps to reproduce behavior
`<img src="{{ TimberImage(post._thumbnail_id).src | resize(250, 250, '#FFFFFF') }}" />`

### What version of WordPress, PHP and Timber are you using?
WordPress 4.7.3, PHP 5.6, Timber 1.2.4

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Upgraded to newest version via plugin updater in WordPress dashboard

**Comment by gchtr** [comment]
@boochamoocha Does it still not work or was it resolved in https://gitter.im/timber/timber?at=58d256d16701410e5862fee4?

**Comment by gchtr** [comment]
Closing this. The problem seems to have been solved in the Gitter channel.
