### ISSUE TITLE
Autoloading not working on simple install

### ISSUE THREAD

**Issue by parljohn** [timber/timber#1377]
I'm on a mac with php 5.6, installed a fresh copy of WP 4.7.3 and simply added the Timber plugin and upgraded it to 1.2.4. Copied the timber-starter-theme to themes folder and all I get is Timber not activated error. Not sure why autoloading is not working out of the box here or how to fix it? Any help? Running composer install and update are no help. Functions.php file has the added autoload requirement.
P.S. If I walk through files and include USE statements in each file where classes are being used then it starts to work. In some cases I have to alias to get it to work ie "use Timber\Menu as TimberMenu" but this is a worm hole and just keeps crashing down the line. Also, I have tried using the same set of code that is working on Bluehost server with PHP 5.4, no beuno. Any thoughts?

**Comment by luism-s** [comment]
Is the plugin activated? If not, do it.
The `composer.json` from the starter theme only downloads the timber library to the plugins folder, and nothing more.


If that does not work, try to remove it and run `composer require timber/timber` on the theme, doing so will install timber in the vendor folder, then you can use autoload.

**Comment by parljohn** [comment]
Have tried both.  A simple install from wordpress and activiting (multiple times) and still getting the Timber is not loaded alert as well as running composer, neither get rid of the error or autoload correctly.  As I said, the only thing that gets remotely close is putting USE statements in the files.

**Comment by luism-s** [comment]
Please paste your composer.json file from the theme directory

**Comment by parljohn** [comment]
{
  "name": "upstatement/timber-starter-theme",
  "description": "Starter theme to build a Timber theme",
  "type":"wordpress-theme",
  "minimum-stability" : "stable",
  "authors": [
      {
          "name": "jarednova",
          "email": "jared@upstatement.com"
      }
  ],
  "repositories": [
    {
      "type": "composer",
      "url": "https://wpackagist.org"
    }
  ],
  "extra": {
  	"installer-paths": {
      "../../plugins/{$name}/": [
        "wpackagist-plugin/*",
        "type:wordpress-plugin"
      ]
  	}
	},
  "require": {
	  "wpackagist-plugin/timber-library": "1.*",
      "Upstatement/routes": "*",
    "timber/timber": "^1.2"
  }
}

**Comment by parljohn** [comment]
FYI, this Timber not Activated error only occurs once I select the template that is trying to use it.  Just by simply copying the Starter template into the themes folder and activating it then autoloading breaks.  With composer update or without.  It does appear to work if you use the old version of timber .02

**Comment by parljohn** [comment]
Turns out after a few hours of chasing this down, that I found a PHP bug, but only for php on a mac, not other operating systems.  The class_exists('WP') function in the wp_config.php file is totally broken on my mac with any version of php 5.6, haven't tried 7.  All I did to fix the problem for now is change the WP class to WP2 and alias it to WP and then the function suddenly worked.  Very strange and may help someone in the future.  Hopefully 7 just works.

**Comment by ieugen** [comment]
I'm seeing the same text `Timber not activated` on Debian Stretch with a docker setup - https://github.com/visiblevc/wordpress-starter . Plugin is not activated if I added in docker-compose as per instructions. If I install and activate the plugin manually, after docker-compose stop + start I see the above text.
