### ISSUE TITLE
Truth/Field only accessible using the element['field] notation

### ISSUE THREAD

**Issue by Kwapi** [timber/timber#1378]
I've got a Truth/False field in a Flexible Content field in a Repeater. I cannot access the value with this syntax `element.truth_false` whereas every other field works correctly. 
```
 // repeater
{% for row in post.get_field('rows') %}

  // flexible content 
  {% for element in row.elements %}


    // trying to access a Truth/False field
    {%  if element.full_width %}
      // THIS DOES NOT WORK
    {% endif %}

    {%  if element['full_width'] %}
      // THIS WORKS
    {% endif %}
    
    // any other fields can be accessed normally and work fine i.e.
    {{element.text}}

  {% endfor %}
{% endfor %}
```

### What version of WordPress, PHP and Timber are you using?
Wordpress 4.7.3 PHP 7.1 Timber 1.2.4

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WP-CLI

**Comment by luism-s** [comment]
Check in the ACF field configuratoon what type of response does it return (value, array, etc). For the purpuse you want it should be set to value.

**Comment by Kwapi** [comment]
@luism-s  thanks for the suggestion but in my version of ACF Pro (5.5.11) there is no option to set the type of return response.

**Comment by luism-s** [comment]
@Kwapi ah, yes you're right. I can't help then. Try to dump() the element variable

**Comment by jarednova** [comment]
@Kwapi I'm afraid I wasn't able to replicate the issue. I tried setting-up the fields as it seemed you have them and used this Twig code...

```twig
{% for row in post.get_field('repeater') %}
	{% for layout in row.elements %}
		{% if layout.full_width %}
			I AM TRUE
		{% endif %}
		{{ layout.texter }}
	{% endfor %}
{% endfor %}
```

This outputted `I AM TRUE
						sample text here` as expected. Can you post a gist of the ACF JSON file so I can replicate directly?
