### ISSUE TITLE
woocommerce.php  $product = wc_get_product( $context['post'] -> ID ) cannot get correct result

### ISSUE THREAD

**Issue by qycary** [timber/timber#1384]
I follow the doc to integrate woocommerce (https://github.com/jarednova/timber/wiki/WooCommerce-Integration) 
but in `single-product.twig` ` {% do action('woocommerce_single_product_summary') %}
` can not get the correct result (it always get the same product price, add cart button point the same product ) 
<hr>
I debug display my themes woocommerce.php the `$product = wc_get_product($context['post'] -> ID)` did not get the correct result(`$product` always point the same product), then I debug `plugins/woocommerce/templates/single-product
/price.php` found `global $product` always point the same product
<hr>
my `woocommerce.php` code

```
<?php

if (!class_exists('Timber')){
    echo 'Timber not activated. Make sure you activate the plugin in <a href="/wp-admin/plugins.php#timber">/wp-admin/plugins.php</a>';
    return;
}

$context            = Timber::get_context();
$context['sidebar'] = Timber::get_widgets('shop-sidebar');

if (is_singular('product')) {

    $context['post']    = Timber::get_post();
    $product            = wc_get_product( $context['post'] -> ID );
    $context['product'] = $product;

 
    Timber::render('views/woo/single-product.twig', $context);
  
    //echo '<pre>';
    //print_r($product );
    //echo '</pre>';
}

```
cart page, checkout page and my_account page are use `shortcode` to show, so `woocommerce.php` only add  single-product.

`$context['post']` display correct sing-product information,
`$context['post'] -> ID` display correct sing-product ID
but when do `wc_get_product( $context['post'] -> ID )` `$product` always show the same product info

<hr>
 my `single-product.twig`

```
{% extends 'template.twig' %}


{% block content %}

  <div style="max-width:1000px; margin:auto; padding-top:20px;">
    {% do action('woocommerce_before_single_product') %}
  </div>
  {% if post.get_field('product_hero_image') %}
    <div class="layout__block product-hero">
      <div class="wrapper">
        <div class="product-hero__wrapper">
          <div class="product-hero__wrapper__media">
            <img src="{{TimberImage(post.get_field('product_hero_image')).src}}"/>
          </div>
          <div class="product-hero__wrapper__action">
            {% do action('woocommerce_single_product_summary') %}
          </div>
          {% do action('woocommerce_after_single_product') %}
        </div>
      </div>
    </div>
  {% endif %}
  </div>

  {{ parent() }}
{% endblock %}

```

**Comment by jacobimpson** [comment]
I tested your code in a fresh project and `wc_get_product` was returning the correct product object without any issues. Are you running the latest version of Woocommerce (3.0 at the time of writing)? Some older versions will use `get_product($id)`, but that has since been depreciated.

**Comment by qycary** [comment]
Hi
Thank you for answering me.
woocommerce version is  2.6.14, woocommerce 3.0 and 3.0.1  dropdown button cannot display　normally, so  I use 2.6.14
I solved by add `{{ fn('the_post') }}` in single-product.twig

**Comment by AlexanderBMAS** [comment]
Also having this issue

**Comment by CaryQY** [comment]
Hi, @AlexanderBMAS 
try this demo
```
{% extends 'template.twig' %}


{% block content %}

  {{fn('the_post')}}  # this code is important to solve problem


  <div style="max-width:1000px; margin:auto; padding-top:20px;">
    {% do action('woocommerce_before_single_product') %}
  </div>
  {% if post.get_field('product_hero_image') %}
    <div class="layout__block product-hero">
      <div class="wrapper">
        <div class="product-hero__wrapper">
          <div class="product-hero__wrapper__media">
            <img src="{{TimberImage(post.get_field('product_hero_image')).src}}"/>
          </div>
          <div class="product-hero__wrapper__action">
            {% do action('woocommerce_single_product_summary') %}
          </div>
          {% do action('woocommerce_after_single_product') %}
        </div>
      </div>
    </div>
  {% endif %}
  </div>

  {{ parent() }}
{% endblock %}
```
compare my old `single-product.twig` in description, I just add `  {{fn('the_post')}}` then it can work

**Comment by gchtr** [comment]
I’m gonna go ahead and suggest that you try out the new [Timber integration for WooCommerce](https://github.com/mindkomm/timber-integration-woocommerce/releases/tag/0.5.1).

From what I see, your issue could be solved if you’d use the integration like this:

1. [Install the integration](https://github.com/mindkomm/timber-integration-woocommerce/blob/0.5.1/docs/installation.md).
2. After you’ve initialized the integration, [update the **woocommerce.php** file](https://github.com/mindkomm/timber-integration-woocommerce/blob/0.5.1/docs/installation.md#optional-add-woocommercephp).
3. Move your **views/woo/single-product.twig** file to **views/woocommerce/single-product.twig**.

Now this would probably break your sidebar. You could add it to the WooCommerce context:

**functions.php**

```php
add_filter( 'timber/woocommerce/context', function( $context ) {
    $context['sidebar'] = Timber::get_widgets( 'shop-sidebar' );
    
    return $context;
} );
```

Or, you could also add it to the top of **woocommerce.php**:

```php
add_filter( 'timber/context', function( $context ) {
    $context['sidebar'] = Timber::get_widgets( 'shop-sidebar' );
    
    return $context;
} );
```
