### ISSUE TITLE
Resolve FunctionWrapper regressions

### ISSUE THREAD

**Issue by jarednova** [timber/timber#1387]
From #1379, I think there are two possible routes here

### Make it work with Twig 2.0
- [ ] Adjust code to make it compatible with Twig 2.0 and maintain old functionality

### It won't work with Twig 2.0 so...
- [x] Describe outcome of #1379 as a breaking change in the Release notes
- [ ] Update documentation to reflect how `FunctionWrapper` should be used or how to include functions
- [x] Provide a deprecation error message through `Helper::warn` for developers
- [x] Remove from default context

**Comment by gchtr** [comment]
@jarednova Thanks for the explanation in https://github.com/timber/timber/pull/1379. I guess the discussion continues here now.

Hopefully I’ll find some time this week to think about a good solution and prepare some pull requests. With a quick search here on Github I found that there are a number of themes that use `function_wrapper` as it is suggested in the documentation.

**Comment by jarednova** [comment]
Closed by #1391
