### ISSUE TITLE
Add `Timber\TermClassMap` filter

### ISSUE THREAD

**Issue by doup** [timber/timber#1399]
It would be convenient to have a filter that works like `Timber\PostClassMap` where an array with the `term => class` mapping can be passed to Timber so it knows which class to use for each of the terms.

#1220 seems to solve this, but I'm not sure if it works with `Timber::get_post()/get_term()/…`.

**Comment by DarrenTheDev** [comment]
+1 for this. `Timber\PostClassMap` is an extremely useful way of extending posts and it would be great to be able to do this for terms too.

**Comment by jarednova** [comment]
This is a huge part of 2.x and will be resolved by the factories work that's in-progress

**Comment by acobster** [comment]
Docs for Class Maps, which solve this problem flexibly and generically in 2.x: https://github.com/timber/timber/blob/2.x-factories/docs/guides/class-maps.md
