### ISSUE TITLE
TimberArchives class not creating valid yearly archive links for HTTPS sites

### ISSUE THREAD

**Issue by chrisgherbert** [timber/timber#1403]
### Expected behavior

The TimberArchives class generates valid yearly archive links even when the site is HTTPS.

### Actual behavior
TimberArchives generates invalid yearly archive links on HTTPS sites - the second slash in the protocol is missing (eg, `https:/www.example.com` rather than `https://www.example.com`).

### Steps to reproduce behavior
```php
// Yearly Links
$archive_obj = new TimberArchives();

$archive_args = array(
  'post_type' => 'post',
  'type' => 'yearly'
);

$years = $archive_obj->get_items($archive_args);

return $years[0]['link']; // will return a link with a missing second slash for HTTPS sites.
```

### What version of WordPress, PHP and Timber are you using?
WordPress 4.7.4, PHP 7, Timber 1.3.0

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by jarednova** [comment]
Closed by #1448 — thanks for the report @chrisgherbert !
