### ISSUE TITLE
Menu items in menu not clickable/ or not working when clicked.

### ISSUE THREAD

**Issue by joethuoo** [timber/timber#1405]
Is this a support or usage question? Please post to [StackOverflow](http://stackoverflow.com/questions/tagged/timber) using the Timber tag

### Expected behavior

I'd like to have a page when i click one of the items in the menu.

### Actual behavior

I don't see any change or loading of page when i click the menu item. However, when i hover the menu item it portrays the page id of the menu item.
### Steps to reproduce behavior
In my index.php i have the following;
```
$context = Timber::get_context();
$menu_id = get_term_by('slug','menu','nav_menu')->term_id;
//$menu    = new TimberMenu(3);
$context['menu'] = new TimberMenu($menu_id);
$query   = array(
	//'numberposts' => 3,
	'category_name' => 'News',
);
$product = array('category_name' => 'Products');
$context['products'] = Timber::get_posts($product);

$context['news'] = Timber::get_posts($query);

$templates = array('index.twig');

if (is_home()) {
	array_unshift($templates, 'home.twig');
}

Timber::render($templates,$context);
```
While in menu.twig i have the following;
```
{% if menu %}
	<ul class="nav navbar-nav">
        {% for item in menu.get_items %}       	
		<li class="{{item.classes | join(' ')}}">
             <a href="{{item.get_link}}" data-toggle="dropdown">{{ item.title }} </a>
        </li>
          {% endfor %}
   </ul><!--/ Nav ul end -->
{% endif %}
```

You can view my project from the following github links.
https://github.com/joethuoo/theming-with-timber/blob/master/index.php
https://github.com/joethuoo/theming-with-timber/blob/master/templates/menu.twig
### What version of WordPress, PHP and Timber are you using?
wordpress 4.7.3, Timber 1.2.4

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Installed Timber via Wp.org

**Comment by gchtr** [comment]
(This would have been a good question to ask on Stackoverflow)

I see from https://github.com/joethuoo/theming-with-timber/tree/master/static/js that you’re using Bootstrap. In the HTML of your link you have a `data-toggle="dropdown"` attribute. With this attribute in place, Bootstrap will prevent the default events on the link to be triggered (which would be to follow the link) and instead will try to open the related dropdown, which doesn’t exist in your code. That’s why nothing happens.

You can read more on http://getbootstrap.com/javascript/#dropdowns on how to use Dropdowns with Bootstrap.

The easiest solution for you to make it work would probably be to remove `data-toggle="dropdown"` from your links in `menu.twig`.

**Comment by joethuoo** [comment]
@gchtr thank you. It worked.
