### ISSUE TITLE
ACF Pro Post Object doesn't have link available when used on options page

### ISSUE THREAD

**Issue by timknight** [timber/timber#1418]
### Expected behavior
When adding a Post Object using ACF Pro to show on an options page, I'd expected those Post Object to act as they do within a post to have a `link` available within the returned item.

### Actual behavior
The item `link` or `url` is not available from within the returned field. 

### Steps to reproduce behavior

1. Create an options page within functions.php and create a new ACF Pro group to show on the options page.
2. Create a Post Object file that returns a Post Object (not the Post ID). 
3. Link a Post Object to that field an access it within the template.
4. To access all of the options I have `$context['options'] = get_fields('options');` within my functions.php. 

### What version of WordPress, PHP and Timber are you using?
WordPress 4.7.4, PHP 5.6.30-1, Timber 1.2.4, ACF Pro 4.0.4

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Installed as plugin through wp.org

**Comment by corygibbons** [comment]
@timknight I think it's because Timber is just returning exactly what ACF is providing, which is the standard WP post object. If you want to use `.link` you can wrap it in `TimberPost`:

```twig
{{ TimberPost(options.post_object_field).link }}
```

**Comment by timknight** [comment]
Thank you @corygibbons that did it. It's been awhile since I've needed to use `TimberPost` I'm assuming that when I'm iterating over the custom fields normally a part of that iteration turns those Post Object fields into a TimberPost Object, where in this case because I'm not iterating that's not happening automatically. Either way, this solves my issue. Thanks for the help.
