### ISSUE TITLE
get the url of an oembed field inside a repeater

### ISSUE THREAD

**Issue by waltercruz** [timber/timber#1423]
Hi! I'm using Wordpress 4.7.5, ACF 5.5.14 and Timber 1.2.4

I have a oembed field, where I wish to get the url of it. But it's inside a repeater, so, I can't use get_field to get the raw value of oembed field. 

video_link is the oembed field.

Example:
`        {% for video in post.get_field('videos')|%}
          {{video|print_r}}
            <div class="item-video">
              <div class="item-video-content">
                <a href="{{video[video-link']}}" class="video-link">
                <span class="video-assunto">{{video['video-subject']}}: </span>
                {{video['video-titulo']}}
                </a>
              </div>
            </div>
        {% endfor %}`

There's some way to extract the url of a oembed field that it's inside a repeater?

**Comment by corygibbons** [comment]
@waltercruz You should be able to do it by using `function()` and the field id instead of `video_link`:

```
{% for video in function('get_field', 'videos', false, false) %}
    <a href="{{ video['field_1234567890'] }}" class="video-link">
{% endfor %}
```

**Comment by waltercruz** [comment]
ok, worked!

**Comment by anthonyivol** [comment]
Thanks @corygibbons ! 
But it is weird and confusing to have the same function name for different behaviors by the way :
`post.get_field('repeater', false, false)` outputs not the same than function('get_field', 'repeater', false, false)
