### ISSUE TITLE
timber - navigation problem

### ISSUE THREAD

**Issue by lupik2** [timber/timber#1426]
hi i have big problem with navigation:
in php:
$twigcontent['header_nav'] = array( 'theme_location' => 'header_menu'');

in twig:
{{ function('wp_nav_menu', 'header_nav') }}

problem is: args from array doenst work...

**Comment by gchtr** [comment]
You’re passing `header_nav` to the `wp_nav_menu` function as a string. If you want to pass it as a variable (which then contains your args), you have to omit the single quotes:

```twig
{{ function('wp_nav_menu', header_nav) }}
```

**Comment by lupik2** [comment]
Thank u, can u look on this too? https://github.com/timber/timber/issues/1424

**Comment by gchtr** [comment]
Yes, I can ☺️.

If your problem is solved, could you please close this issue?

**Comment by gchtr** [comment]
Closing this, as problem seems to be solved.
