### ISSUE TITLE
Suggestion: prefix generated filenames 

### ISSUE THREAD

**Issue by mgussekloo** [timber/timber#1427]
Generated filenames using the 'resize' filter are generally filename_[width]x[height].jpg. This makes it hard to tell them apart from "original" files in the uploads-folder.

I made a filter called 'prefix' that prefixes a filename. I use it to rename all my resized files, so they are 'resized_filename_widthxheight.jpg'.

I was wondering if anyone would find this useful. It might be standard behavior of the resize-filter.

```php
 $twig->addFilter('prefix', new Twig_Filter_Function(function($src, $prefix) {
	        $oldFile = ABSPATH . TimberURLHelper::get_rel_url($src);
	        $newFilename = dirname($oldFile) . '/' . $prefix . basename($oldFile);
	        if (file_exists($oldFile) && !is_dir($oldFile) && !file_exists($newFilename)) {
	            rename($oldFile, $newFilename);
	        }
	        $newSrc = dirname($src) . '/' . $prefix . basename($oldFile);
                return $newSrc;
  }));
```

**Comment by nlemoine** [comment]
@gchtr I also think Timber resizes should live in another folder but let's discuss this when we'll be removing the image resize part from Timber :)
