### ISSUE TITLE
Errors when clearing twig or timber cache using WP_CLI command (wp timber cache_clear_*)

### ISSUE THREAD

**Issue by vyarmolenko** [timber/timber#1429]
WP_CLI commands for clearing only twig or only timber cache fail to write output to console:

![image](https://cloud.githubusercontent.com/assets/3118280/26351291/bbfb3760-3fbf-11e7-8cdb-c81531afc37c.png)

### Steps to reproduce behavior
Running **wp timber cache_clear_twig** or **wp timber cache_clear_timber** produces error.

### What version of WordPress, PHP and Timber are you using?
WordPress 4.7, PHP 5.6.30, WP_CLI 1.2.0-alpha, Timber 1.2.4

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Timber and WP_CLI were installed using Composer.

**Comment by palmiak** [comment]
@vyarmolenko does this bug still exists? Because I see something merged.

**Comment by vyarmolenko** [comment]
@palmiak it's resolved, closing.

**Comment by columbian-chris** [comment]
Looking at this almost six years later, try `wp timber clear-cache`.
