### ISSUE TITLE
{{ post.link }} not working when retrieving posts from subsites in multisite

### ISSUE THREAD

**Issue by kamontander** [timber/timber#1434]
### Expected behavior
I am working on a multisite install and I'm trying to list most recent posts from subsites on the main site home page with links to posts on the respective subsites.

### Actual behavior
{{ post.link }} has no output.

### PHP
    $context = Timber::get_context();
    $context['posts'] = Timber::get_posts();
    $templates = array( 'index.twig' );

    if ( is_main_site() ) {
      $context['news'] = array();
      for ($id=2; $id <= get_site_count(); $id++) { 
        switch_to_blog( $id );
        $args = array(
          'orderby'        => 'post_date',
          'posts_per_page' => 1
        );
        $latest_post = Timber::get_posts($args);
        $context['news'][] = $latest_post[0];
        restore_current_blog();
      }
    }

    Timber::render( $templates, $context );

### Twig
    {% for news_item in news %}
      <h3>
        <a href="{{ news_item.link }}"> // this is blank
          {{ news_item.title }}
        </a>
      </h3>
      <p>{{ news_item.content }}</p>
    {% endfor %}

### What version of WordPress, PHP and Timber are you using?
WordPress 4.7.5, PHP 5.4.19, Timber 1.2.4

### How did you install Timber?
Upgraded to newest version via plugin updater in WordPress dashboard

**Comment by hatto** [comment]
not my preferred solution, but it does work
<a href="{{ TimberPost(news_item.ID).link }}">

**Comment by designrubenz** [comment]
I just encountered the same problem – not with a multisite but a regular wordpress install.
WordPress: 5.3.2
timber: 1.10.1

### page.php
```
$feed = get_posts(array(
    'posts_per_page'    => -1,
    'post_type'         => 'post',
    'category_name'     => $category_name
));
$context['feed'] = $feed;
```

### page.twig

```
{% for feed_item in feed %}  
        {{ feed_item | print_r }}
        <h4><a href='{{ TimberPost(feed_item.ID).link }}'>{{ feed_item.post_title }}</a></h4>
 {% endfor %}. 
```

### debugging output (`feed_item | print_r`)
`
WP_Post Object ( [ID] => 129 [post_author] => 1 [post_date] => 2020-02-10 18:40:31 [post_date_gmt] => 2020-02-10 17:40:31 [post_content] => [post_title] => Test 1 [post_excerpt] => [post_status] => publish [comment_status] => open [ping_status] => open [post_password] => [post_name] => test-1 [to_ping] => [pinged] => [post_modified] => 2020-02-10 18:41:15 [post_modified_gmt] => 2020-02-10 17:41:15 [post_content_filtered] => [post_parent] => 0 [guid] => http://fjz.localhost/?p=129 [menu_order] => 3 [post_type] => post [post_mime_type] => [comment_count] => 0 [filter] => raw )
`

As you can see, this object unexpectedly has no 'link' attribute. 
Is there anything I am doing wrong here?

@hatto's workaround works for me, too. thanks.

**Comment by palmiak** [comment]
@designrubenz could you replace get_posts with Timber::get_posts ?

**Comment by designrubenz** [comment]
thank you a lot @palmiak, this works. but, uhm, why?

**Comment by gchtr** [comment]
@designrubenz When you use `get_posts()`, you will use a core WordPress function that has no knowledge of Timber. Timber also doesn’t hook into that function.

 The `{{ .link }}` method is something that only exists in Timber. The `get_posts()` function will return an array of `WP_Post` objects, which have no `link` method. Only `Timber\Post` objects have a `link` method. That’s why you use `Timber::get_posts()`, to get `Timber\Post` object instead of `WP_Posts` objects.

When you use `{{ TimberPost(feed_item.ID).link }}`, you turn a post ID into a `Timber\Post` object and then call the `link` method on that object. It would also work with `{{ TimberPost(feed_item).link }}`, because the `TimberPost()` function in Twig can not only convert post IDs to `Timber\Post` objects, but also full `WP_Post` objects.

When you switch to `Timber::get_posts()`, then you can update your Twig file to this:

```twig
{% for feed_item in feed %}  
	<h4><a href='{{ feed_item.link }}'>{{ feed_item.title }}</a></h4>
{% endfor %}
```

Because a `feed_item` is already a `Timber\Post` object, you can directly call the `link` method, or the `title` method (instead of `feed_item.post_title`).

**Comment by designrubenz** [comment]
oh, sure – now i see! @gchtr, thank you so much for your brilliant explanation!

**Comment by gchtr** [comment]
@designrubenz You’re welcome!

@kamontander Yep, it’s obvious this doesn’t work. And I think the only way to work around this is to **prepare all the data you need** within `switch_to_blog()` and `restore_current_blog()`.

Here’s a snippet that should work.

```php
<?php

$context          = Timber::get_context();
$context['posts'] = Timber::get_posts();
$templates        = [ 'index.twig' ];

if ( is_main_site() ) {
    $news = [];

    for ( $id = 2; $id <= get_site_count(); $id ++ ) {
        switch_to_blog( $id );

        $latest_posts = Timber::get_posts( [
            'orderby'        => 'post_date',
            'posts_per_page' => 1,
        ] );

        // Prepare all the data you need in advance.
        foreach ( $latest_posts as $latest_post ) {
            $news[] = [
                'link'    => $latest_post->link(),
                'title'   => $latest_post->title(),
                'content' => $latest_post->content(),
            ];
        }

        restore_current_blog();
    }

    $context['news'] = $news;
}

Timber::render( $templates, $context );
```

The reason you need to prepare your data in advance is that certain methods in Timber will call WordPress functions that rely on the current blog. For example, `{{ post.link }}` will call `get_permalink()` internally, and this will always try to get the data from the current blog.

Now, I think we won’t change Timber to work around that. We would have to prepare all the data for posts in advance, but that would be a performance hit. The way it works now is that we fetch some of the data only when needed.

However, this case is actually a limitation in Timber that needs to be documented. I’m going to open a separate issue and close this one.
