### ISSUE TITLE
Code style and formatting in the documentation

### ISSUE THREAD

**Issue by artifex404** [timber/timber#1442]
PHP, Twig and HTML code should be written in one concise format and styling in the documentation. As of now, there is a lot of variations.

I thought about contributing with the clean up, but wanted to ask first a more official opinion which style/formatting to apply.

**Comment by jarednova** [comment]
@artifex404 that would be very helpful. A lot of hands over the years (including mine) have been in there over the years with some changing rationales. [This describes the PHP rules](https://github.com/timber/timber/blob/master/.scrutinizer.yml) (from Scrutinizer CI). In general, it's pretty close to WordPress's official standards.

For Twig and HTML, I'd like to stick to the official Twig standards where we can

**Comment by nlemoine** [comment]
Since 2.x and code standards auto fixing implementation, I think we can close this.
