### ISSUE TITLE
Image resize broken in version 1.3.0

### ISSUE THREAD

**Issue by MrsMrz** [timber/timber#1444]
Is this a support or usage question? Please post to [StackOverflow](http://stackoverflow.com/questions/tagged/timber) using the Timber tag

### Expected behavior

Image cropping
### Actual behavior

not cropping
### Steps to reproduce behavior

updated from 1.2.4 to  1.3.0 and in that update the image resize feature has broken.
### What version of WordPress, PHP and Timber are you using?

wordpress 4.7.3 and updated to 4.8
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

composer/Packagist

**Comment by chrisgherbert** [comment]
I see this happen when the site URL does not exactly match the site's actual URL. For example, if you're serving the site over HTTPS but the site URL is HTTP.

**Comment by MrsMrz** [comment]
Ok, I see how that would happen, we have a huge corporate site that has different URLS set up for different properties... but still why would this happen because of this version update? it still works on version 1.2.4. @chrisgherbert

**Comment by chrisgherbert** [comment]
I don't know exactly, but I think it's due to an issue in the Timber\Image class.  Any registered thumbnail sizes (eg 'full', 'large', 'medium', 'thumbnail', etc) should work fine even on the newer version, but scaling/cropping using Timber will not work correctly with a mismatched site URL.

**Comment by MrsMrz** [comment]
good to know. thank you for this, good to know for the future. I hope it gets fixed!

**Comment by jarednova** [comment]
@MrsMrz please try your setup with the newest version of Timber (1.3.2) to see if it resolves your issue. This will be pushed to WP.org tomorrow for easy download
