### ISSUE TITLE
Image Resize issues with HTTP vs HTTPs

### ISSUE THREAD

**Issue by jarednova** [timber/timber#1446]
Is this a support or usage question? Please post to [StackOverflow](http://stackoverflow.com/questions/tagged/timber) using the Timber tag

From @lmartins in [#1303](https://github.com/timber/timber/issues/1303#issuecomment-303975717)

Also having the same issue with similar circumstances. HTTPS site hosted on WPEngine, full sized images served to non logged in users and under HTTPS. Logged in users see resized images, without https everyone gets the resized images, so the problem seems to result from the combination of https and logged off.

EDIT: I've also tried version 1.3 and it also didn't fixed the issue for me.

**Comment by lmartins** [comment]
@jarednova I just wanted to report that I was also seeing the same issues under similar conditions. I know that I really didn't add much, if any, information to the ticket but still it might be helpful to know that it isn't an isolated incident and it is happening on multiple sites.

**Comment by 27Bslash6** [comment]
Similar issues, hosted locally in a docker instance ( https://hub.docker.com/r/funkygibbon/wordpress/ ).

http:// images work, https:// all return original unresized images, there doesn't seem to be any difference between users logged in or otherwise.

**Comment by jarednova** [comment]
@lmartins @27Bslash6 try out the new dev-master. I was able to replicate the issue and find a fix!
