### ISSUE TITLE
new TimberPost();  - Custom post type

### ISSUE THREAD

**Issue by lupik2** [timber/timber#1451]
hi, how can i get Custom post type?
something like that : $twigcontent['post'] = new TimberPost();

**Comment by jarednova** [comment]
Hi there! Sorry to hear you're having issues (but glad you're giving Timber a try!) We try to keep GitHub clear for just bugs with the Timber code itself. For questions like this, please post to the StackOverflow channel:

http://stackoverflow.com/questions/tagged/timber

... I'll try to follow-up there if there's an answer I can provide

**Comment by lupik2** [comment]
but this is bug, i cant do this!

**Comment by jarednova** [comment]
@lupik2 if it's a bug please fill out the complete Bug Reporting template you see when creating a new issue. That's the only way I can work to verify what you're experiencing
