### ISSUE TITLE
Values in repeater loops stay persistent if no new value is set in new loop

### ISSUE THREAD

**Issue by Luckyfella73** [timber/timber#1454]
Hi,

if we loop through repeater items values stay persistent in following loops in case the
items in the loop have no "new" value. In my template I have the following code:
```
{% set awards = post.get_field('repeater__awards') %}
{% if awards %}
<div class="box-awards">
	{% for award in awards %}
		<h4 class="headline-recommended">
			{{ award.headline }}
		</h4>
		{% if award.url %}
			{% set award_link_pre = '<a href="' ~ award.url ~ '" target="_blank">' %}
			{% set award_link_post = '</a>' %}
		{% endif %}
		{{ award_link_pre }}<img src="{{ TimberImage(award.image).src }}" class="thumbnail-award" alt="{{ award.headline }}">{{ award_link_post }}
	{% endfor %}
</div>
{% endif %}
```

Lets say the `award.url` is set in the first loop, if there is no `award.url` set in the second loop the value from the first loop is used.

I'm not sure if this is worth to be called an issue or if I'm doing wrong in checking for set values?

### What version of WordPress, PHP and Timber are you using?
Timber 1.2.4 , WP 4.7.5

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Installed Timber Plugin via WP plugins/install

**Comment by luism-s** [comment]
As you said, there's no `award.url` in the second loop, therefore, `award_link_pre` will have the value set in the first loop inside the `if` statement.

do something like this instead:

````
{% set awards = post.get_field('repeater__awards') %}
{% if awards %}
<div class="box-awards">
	{% for award in awards %}
		<h4 class="headline-recommended">
			{{ award.headline }}
		</h4>
		{% if award.url %}
			{% set award_link_pre = '<a href="' ~ award.url ~ '" target="_blank">' %}
			{% set award_link_post = '</a>' %}
		{% endif %}

		{% if award.url %}
		    {{ award_link_pre }}
                 {% endif %}

                <img src="{{ TimberImage(award.image).src }}" class="thumbnail-award" alt="{{ award.headline }}">

		{% if award.url %}
		    {{ award_link_post }}
                 {% endif %}
	{% endfor %}
</div>
{% endif %}
````
It should work as you intend

**Comment by Luckyfella73** [comment]
Seeing your code I realize that not the `award.url`value is persistent but the variable I did set (slightly ashamed now ..)

Thanks @luism-s for clarifying that for me
