### ISSUE TITLE
init_with_url() doesn't support wp core in a subdiretory

### ISSUE THREAD

**Issue by oxyc** [timber/timber#1458]
### Expected behavior

If you init a TimberImage by url it should set the correct `file_loc` so you can retrieve file dimensions.

>  "/var/www/wordpress/web/app/uploads/2015/10/cropped-512x5121.jpg"

### Actual behavior

As `init_with_url()` prefixes the relative path with `ABSPATH`, this breaks on a Bedrock file structure where WP core is in a subdirectory

>  "/var/www/wordpress/web/wp/app/uploads/2015/10/cropped-512x5121.jpg"

### Steps to reproduce behavior

Setup a Bedrock site.
```
{% set image = TimberImage(post.thumbnail.src|resize(400)) %}
<img src="{{image.src}}" width="{{image.width}}" height="{{image.height}}">
```

### What version of WordPress, PHP and Timber are you using?

WordPress 4.8, PHP 7.1, Timber 1.3.2

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Composer

**Comment by Levdbas** [comment]
Should be fixed in #2134
