### ISSUE TITLE
\Timber\Post get_field method returns wrong post object

### ISSUE THREAD

**Issue by JakubSzajna** [timber/timber#1462]
get_field method of `\Timber\Post` returns `\Timber\Post` even when default post class is overriden by `Timber\PostClassMap` filter.

This can be easily fixed by using `get_class($this)` instead of `__CLASS__` in `get_field` definition when method `convert()` is used.

**Comment by gchtr** [comment]
We’ve reworked how post class filtering works in Timber 2.0, see https://timber.github.io/docs/v2/guides/class-maps/. If this issue still exists in 2.0, please open a new issue.
