### ISSUE TITLE
Show multiple custom post types who have their own taxonomy but all contain one category with the same name

### ISSUE THREAD

**Issue by Infusednl** [timber/timber#1463]
Hi all,

**Introduction**
At the moment I am working on a website which shows multiple posts from 2 custom post types(More will be added later) called 'Wallpapers' and 'Podcasts' in a slideshow. These posts all share the same categories.

In the slideshow I call only posts with category 'spotlight'  from the default Wordpress categories. I retrieve these using the code below in my php file (To keep it simple I removed the rest which actually renders the page).

`
  $sliderArgs = array(
    'post_type' 	=> array(
      'wallpapers',
      'podcasts'),
    'category_name' => 'spotlight',
      'orderby' => 'rand'
  );
`

Note: The above works perfectly when the custom post types have acces to the default Wordpress categories used by the built in Posts.

**The problem**
I didn't want these custom post types to share the same categories except 'spotlight'.
So I added a custom taxonomy for each custom post type where I added their own categories.
Then I also added the category 'spotlight' for each post type as I want to show all posts which are in the category spotlight.

I did this because I don't want my client to accidentaly put a post from the 'Wallpapers' in the category of the 'Podcasts' and vice versa.

However, now the above code doesn't work anymore and I have got no clue how to get this to work anymore.

**The Question**
So how can I show posts from various custom post types in one loop while maintaining their own seperate Taxonomy(categories). As I said before I did add the 'spotlight' category to all custom post types. Is this possible?

Until now this has been the only thing I can't figure out on my own. If this is already mentioned somewhere in the online documentation and I missed it somehow then please let me know. :)

Best regards,

Christiaan

**Comment by Infusednl** [comment]
After hours of trying and googling I found the solution:

/**
 * Load Wallpapers & Podcasts for slideshow
 */

`
$sliderArgs = array(
  'post_type' => array(
    'wallpapers',
    'podcasts'),
  'tax_query' => array(
    'relation' => 'OR',
    array(
      'taxonomy' => 'wallpaper-categories',
      'field' => 'slug',
      'terms' => array( 'spotlight' )
    ),
    array(
      'taxonomy' => 'podcast-categories',
      'field' => 'slug',
      'terms' => array( 'spotlight' )
    )
  ),
  'orderby' => 'rand',
  'numberposts' => -1
  );

  $context['slider'] = Timber::get_posts($sliderArgs);
`

The above code loads all my custom post types and checks their taxonomies for the category 'spotlight'.

**Comment by chrisgherbert** [comment]
This doesn't really seem related to Timber.  Vanilla WordPress works exactly the same way.
