### ISSUE TITLE
pagination for 'post' archive.php bug - 404 error

### ISSUE THREAD

**Issue by lupik2** [timber/timber#1471]
hi im using code from https://github.com/timber/starter-theme
archive.php and archive.twig

when i click on second on thirrd and more page i have error 404 

this is code:
twig: http://wklej.org/hash/bbc6c43c6e4/
php: http://wklej.org/hash/377a8c11aa4/

**Comment by codemonkeynorth** [comment]
see this maybe
https://github.com/timber/timber/issues/369

**Comment by gchtr** [comment]
This is a really old issue that we won’t be able to reproduce. Please open a new issue if this still persists.
