### ISSUE TITLE
Publish 1.3.3 to Wordpress.org

### ISSUE THREAD

**Issue by tremby** [timber/timber#1473]
Is there a reason it's not there? Latest is 1.3.2. I install it via composer with wpackagist, which I believe pulls from Wordpress.org.

**Comment by jarednova** [comment]
Hi @tremby — I've been traveling for 🇺🇸 4th of July. But I'm back tomorrow (7/5) and will push to WP.org in the evening

**Comment by tremby** [comment]
Thanks!

Take your time; wanted to post just in case it had been forgotten.

**Comment by jarednova** [comment]
and we're live! https://wordpress.org/plugins/timber-library/
