### ISSUE TITLE
Implement Carbon Fields Integration

### ISSUE THREAD

**Issue by mindfullsilence** [timber/timber#1474]
Is this a support or usage question?
No

### Expected behavior
allow carbon fields as replacement for ACF fields. 

Would be great to see this as an integration. I imagine it would be pretty much equivalent to the ACF integration file.

**Comment by shaneoliver** [comment]
Add you sections to the page or global context 

```php
$context['sections'] = carbon_get_the_post_meta( 'your section name' );
```
Loop and include your section templates

```twig
{% for section in sections %}
	{% include "modules/sections/#{section['_type']}.twig" %}
{% endfor %}
```

**Comment by synapticism** [comment]
Since this issue is languishing here... I've got this in an extended post class and it's working fine:

```php
public function get_field( $field_name ) {
    $value = carbon_get_post_meta($this->id, 'crb_' . $field_name);
    $value = $this->convert($value, __CLASS__);
    return $value;
  }
```

I haven't seen a need to override the rest of the ACF-specific methods but it doesn't seem all that tricky.

**Comment by jarednova** [comment]
Thanks @synapticism — are you interested in submitting a PR for this? I think you could follow the patterns in the `Integrations/ACF` class for reference:

https://github.com/timber/timber/blob/master/lib/Integrations/ACF.php

**Comment by synapticism** [comment]
I'll take a look and see if my skills are up to the task!

**Comment by carstenwawer** [comment]
Hi @synapticism - did you have a look? Don't want to steal your possibility to contribute, but i would love to take the task, if dont find time for it!

Need a CarbonFields-Integration in project in some weeks.

**Comment by xsynaptic** [comment]
@carstenwawer I had a stab at it... not entirely sure if it's really this simple (my experience with both CF and Timber is still pretty limited), but there's a PR to have a look at/build on/etc.!

P.S. also made a small username change. Sorry for the at-reply confusion here :)

**Comment by mindfullsilence** [comment]
I used this PR on my last site build. Did great!

For posts and options pages it worked exactly as it should. I didn't use it on menu items so can't speak to its stability in that arena. But everything else seems on the money.

**Comment by dimitriBouteille** [comment]
Hey @mindfullsilence and @jarednova , 

Just out of curiosity, did that ticket make any progress ?
If the ticket is in neutral, I will be able to propose a solution :)

**Comment by jarednova** [comment]
@dimitriBouteille I don't believe it was ever picked up. If you're interested, check out how some of the other integrations have been handled ...

https://github.com/timber/timber/tree/2.x/lib/Integrations

... we're in the midst of finishing up our 2.0 beta/release right now. But after that's clear I'd gladly review a PR if you're interested in working on it.

**Comment by nlemoine** [comment]
I just submitted a PR about that here: https://github.com/timber/timber/pull/2400

**Comment by Levdbas** [comment]
As mentioned in the PR @nlemoine  created, we are not going to ship this in core. If anyone wants to take the PR code and create an extension for Timber, feel free to do so.
