### ISSUE TITLE
Testing for template existence should be delegated to twig.

### ISSUE THREAD

**Issue by heino** [timber/timber#1475]
### Expected behavior

The filter 'timber/loader/loader' allows customization to Timber’s default Twig loader. This way it is possible to make alterations of the template paths or even replace the default loader, but such modifications are ignored by Timber during testing for template existence, since Timber does its own testing.

Testing for template existence should be delegated to Twig via Twig_LoaderInterface::exists().

```
--- Loader.orig.php	2017-06-19 16:24:56.000000000 +0200
+++ Loader.php	2017-07-06 22:19:15.000000000 +0200
@@ -111,13 +111,7 @@
 	 * @return bool
 	 */
 	protected function template_exists( $file ) {
-		foreach ( $this->locations as $dir ) {
-			$look_for = $dir.$file;
-			if ( file_exists($look_for) ) {
-				return true;
-			}
-		}
-		return false;
+		return $this->get_loader()->exists($file);
 	}
```
 
### What version of WordPress, PHP and Timber are you using?
Timber 1.3.2

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Not relevant

**Comment by jarednova** [comment]
Thanks @heino — could you submit a PR for this? I'd much prefer to use Twig's magic than the (current) roll-your-own

**Comment by heino** [comment]
I would rather first address a related issue, and suggest an alternative.

The patch would generate some overhead due to multiple calls to get_loader(), which generates a new loader object for each call. This is also the case in get_twig(). Shouldn't the Loader use a singleton pattern?

Also, if I am not mistake template_exists() is called from only choose_template(), which could instead delegate to twig directly, and thus only call get_loader() once.

While at it, the phpdoc related to choose_template() is partially incorrect. According to the doc the method will return the first file that exists. But if none exists, the first file is returned. Wouldn't it be better if the method returned false, if no template file was found? This way Timber::compile() could take relevant action in failure to select template file way earlier.

**Comment by heino** [comment]
An example of an altered compile() based on such boolean return from choose_template():
```
public static function compile( ... ) {
	if ( !defined('TIMBER_LOADED') ) {
		self::init();
	}
	$caller = LocationManager::get_calling_script_dir(1);
	$loader = new Loader($caller);
	$file = $loader->choose_template($filenames);

	$caller_file = LocationManager::get_calling_script_file(1);
	apply_filters('timber/calling_php_file', $caller_file);

	// This is moved up here to allow filtering $file == false
	if ( $via_render ) {
		$file = apply_filters('timber_render_file', $file);
	} else {
		$file = apply_filters('timber_compile_file', $file);
	}

	$output = false;

	// If Only handle data and rendering, if template file exists.
	if ($file !== false) {

		if ( is_null($data) ) {
			$data = array();
		}

		if ( $via_render ) {
			$data = apply_filters('timber_render_data', $data);
		} else {
			$data = apply_filters('timber_compile_data', $data);
		}

		$output = $loader->render($file, $data, $expires, $cache_mode);
	}

	do_action('timber_compile_done');
	return $output;
}
```


```
--- Timber.orig.php	2017-07-07 00:22:54.000000000 +0200
+++ Timber.php	2017-07-07 00:31:10.000000000 +0200
@@ -292,22 +292,35 @@
 		$caller = LocationManager::get_calling_script_dir(1);
 		$loader = new Loader($caller);
 		$file = $loader->choose_template($filenames);
+
 		$caller_file = LocationManager::get_calling_script_file(1);
 		apply_filters('timber/calling_php_file', $caller_file);
-		$output = '';
-		if ( is_null($data) ) {
-			$data = array();
+
+		// This is moved up here to allow filtering $file == false
+		if ( $via_render ) {
+			$file = apply_filters('timber_render_file', $file);
+		} else {
+			$file = apply_filters('timber_compile_file', $file);
 		}
-		if ( strlen($file) ) {
+
+		$output = false;
+
+		// If Only handle data and rendering, if template file exists.
+		if ($file !== false) {
+		
+			if ( is_null($data) ) {
+				$data = array();
+			}
+
 			if ( $via_render ) {
-				$file = apply_filters('timber_render_file', $file);
 				$data = apply_filters('timber_render_data', $data);
 			} else {
-				$file = apply_filters('timber_compile_file', $file);
 				$data = apply_filters('timber_compile_data', $data);
 			}
+
 			$output = $loader->render($file, $data, $expires, $cache_mode);
 		}
+		
 		do_action('timber_compile_done');
 		return $output;
 	}
```
