### ISSUE TITLE
Removing upstatement/router as a dependency

### ISSUE THREAD

**Issue by adamtomat** [timber/timber#1482]
### Expected behavior
We are currently writing [our own router package](https://github.com/Rareloop/wp-router) to use instead of upstatement's router (which supports named routes and route groups. - still alpha atm). It has a dependency on Altorouter too, but because we are using timber we are limited to using Altorouter at v1.1.0 - due to timber requiring upstatement's router.

I'm wondering if Timber has a hard requirement on upstatement's router, or whether it's been included for convenience / backwards compatibility? Are there any plans to remove the dependency?

### What version of WordPress, PHP and Timber are you using?
Timber 1.3.4 - installed via composer

**Comment by jarednova** [comment]
Indeed, I feel indebted to the backwards compatibility of it being there from the start. I'm planning on removing that in 2.x. Are there any temporary workarounds that are worth considering?

**Comment by joelambert** [comment]
FYI, our Router is now stable and ready for use if this is of interest. As @adamtomat mentioned, it still uses AltoRouter under the hood but gives a more expressive API, along with PSR compliant support for Message objects (requests/responses) and Middleware.

https://github.com/Rareloop/router

**Comment by gchtr** [comment]
I do agree that we should make Routing optional. Most problems that I see people trying to solve with routing can be solved with what WordPress already offers – even without having to update rewrite rules.

I’m adding this to the list for 2.x:

- [ ] Remove Composer dependency `upstatement/routes` in 2.x.
- [ ] Move content from Routing Guide over to [Upstatement/routes](https://github.com/Upstatement/routes).
- [ ] Replace Routing Guide content with hint about why routing was disabled by default and a list of Routing libraries that can be used if routing should be required, like [Rareloop/router](https://github.com/Rareloop/router), or still [Upstatement/routes](https://github.com/Upstatement/routes).

A pull request should be made against the 2.x branch.

**Comment by gchtr** [comment]
The relevant pull request #1869 was merged. As of Timber 2.x, routing is optional.

If somebody has more routing libraries that work with Timber and that we could add to the documentation: pull requests are welcome!

**Comment by drzraf** [comment]
Is it something that could be "backported"(?) to 1.x ?
`upstatement/routes` has, itself, some other dependencies and it seems it's not needed in the context of WordPress.

**Comment by jarednova** [comment]
@drzraf I think this is something that we can only support for 2.x going forward. We want to be as as carful as possible to limit any breaking changes we introduce in 1.x. I totally agree with you in spirit, but we've felt a lot of (unexpected) pain/fallout for pulling deprecated functionality
