### ISSUE TITLE
Question about object_type and representation fields

### ISSUE THREAD

**Issue by corradomatt** [timber/timber#1484]
On Timber/Post I see the following....

```php
        /**
	 * @var string $object_type what does this class represent in WordPress terms?
	 */
	public $object_type = 'post';

	/**
	 * @var string $representation what does this class represent in WordPress terms?
	 */
	public static $representation = 'post';
```

And I'm wondering what these are used for under the covers? I'm wondering if I can safely override these on custom post types?

My use case is that I have a few different post types that should all share the same templates because they're related. For what I'm wanting to do, it will make my life easier if I can have a field on the object which each of these separate post types share. Currently I'm using a custom field of `$this->obj_type` but I'm wondering if utilizing one of these predefined fields would make more sense.

Any guidance or suggestions would be greatly appreciated.

**Comment by jarednova** [comment]
@corradomatt you're safe to override those. Those go back to ye-olde days when I wanted to add some kind of reliable way of checking what type the class was meant to represent (`post`, `term`, `user`, etc.) for themes

**Comment by corradomatt** [comment]
awesome, thanks @jarednova
