### ISSUE TITLE
Function_wrapper is deprecated and will be removed

### ISSUE THREAD

**Issue by NikolaGrdanjski** [timber/timber#1499]
Hi, i use Polylang and Theme and plugin translation for Polylang (TTfP) for string translation in my theme.

Author Theme and plugin translation for Polylang (TTfP) say to put this

$context['pll_e'] = TimberHelper::function_wrapper('pll_e');
$context['pll_'] = TimberHelper::function_wrapper('pll_');

in add_to_context function

and this in my .twig file

{{ pll_e("Test text on TWIG template 1.") }}
{{ pll__("Test text on TWIG template 2.") }}

but i got a errors

Warning: function_wrapper is deprecated and will be removed in 1.4. Use {{ function( 'function_to_call' ) }} instead or use FunctionWrapper directly.

How can i fix this problem?
Tnx.

**Comment by gchtr** [comment]
Hey @NikolaGrdanjski 

Yes, `function_wrapper` was deprecated and you should use other ways to expose your functions to Twig. You can read more about this in the [Functions guide](https://timber.github.io/docs/guides/functions/#make-functions-available-in-twig).

The most convenient solution for you would probably be to use the `timber/twig` filter to add the functions you want to use:

**functions.php**

```php
/**
 * My custom Twig functionality.
 *
 * @param Twig_Environment $twig
 * @return $twig
 */
add_filter( 'timber/twig', function( \Twig_Environment $twig ) {
    $twig->addFunction( new Twig_Function( 'pll_e', 'pll_e' ) );
    $twig->addFunction( new Twig_Function( 'pll_', 'pll_' ) );

    return $twig;
} );
```

That way, you don’t have to change anything in Twig. You can also remove the part where you add the `pll_e` and `pll_` entries to `$context`, you don’t need that anymore.

**Comment by NikolaGrdanjski** [comment]
Tnx @gchtr 
I try this. But I have php errors.

1.Fatal error: Uncaught Error: Cannot instantiate abstract class Twig_Function
2.Error: Cannot instantiate abstract class Twig_Function

Tnx

**Comment by gchtr** [comment]
@NikolaGrdanjski Then it might depend on the version of Timber that you are using. If you’re using a version **below 1.3.4**, then try to replace `Twig_Function` with `Twig_SimpleFunction` and see if that works.

**Comment by NikolaGrdanjski** [comment]
Tnx @gchtr

It's doing fine now!

**Comment by gchtr** [comment]
Very good! 👍

**Comment by mvaneijgen** [comment]
@gchtr I am getting the same error as @NikolaGrdanjski and using version 1.4.1 replacing  `Twig_Function` with `Twig_SimpleFunction` results in 
```
Fatal error: Uncaught Error: Call to a member function addFunction() on null in /public_html/wp-content/plugins/timber-library/lib/FunctionWrapper.php:75
``` 

Am I missing something?

**Comment by gchtr** [comment]
@mvaneijgen `Twig_SimpleFunction` was deprecated in **1.3.4**, so if you use **1.4.1** you should use `Twig_Function`. Which error message does show when you use `Twig_Function`? And can you show how you use `add_function()` in `timber/twig` so that I can try to reproduce your error?
