### ISSUE TITLE
ACF Image Crop + TimberImage

### ISSUE THREAD

**Issue by Kwapi** [timber/timber#1501]
I'm trying to figure out the best workflow to utilise ACF Image Crop Add-on and alt tags for accessibility. The best solution so far seems to be to return the Image Crop field as an array. The structure of that array is as follows (when called with the `get_field()` method)
```
array (size=11)
  'id' => int 297
  'alt' => string 'test alt on the original' (length=24)
  'title' => string '1024x512' (length=8)
  'caption' => string 'test caption on the original' (length=28)
  'description' => string '' (length=0)
  'mime_type' => string 'image/jpeg' (length=10)
  'url' => string '//localhost:3000/wp-content/uploads/2017/07/1024x512_150x150_acf_cropped-1.jpeg' (length=84)
  'width' => int 150
  'height' => int 150
  'sizes' => 
    array (size=18)
      'thumbnail' => string '//localhost:3000/wp-content/uploads/2017/04/1024x512-150x150.jpeg' (length=70)
      'thumbnail-width' => int 150
      'thumbnail-height' => int 150
      < MORE SIZES FOLLOW>
  'original_image' => 
    array (size=10)
      'id' => int 297
      'alt' => string 'test alt on the original' (length=24)
      'title' => string '1024x512' (length=8)
      'caption' => string 'test caption on the original' (length=28)
      'description' => string '' (length=0)
      'mime_type' => string 'image/jpeg' (length=10)
      'url' => string '//localhost:3000/wp-content/uploads/2017/04/1024x512.jpeg' (length=62)
      'width' => int 1024
      'height' => int 512
      'sizes' => 
        array (size=18)
          'thumbnail' => string '//localhost:3000/wp-content/uploads/2017/04/1024x512-150x150.jpeg' (length=70)
          'thumbnail-width' => int 150
          < MORE SIZES FOLLOW>

```
This is great because I have access both to the cropped url  (`url`) and the alt tag that I set on the original image (`alt` and `original_image[alt]`).

The only issue with this approach is that TimberImage doesn't process this entity properly. It picks up the `id` on the array which points to the original image and populates the TimberImage object with the original image's properties (like urls).

This means I cannot instantiate TimberImage in twig like `{{Image(post.get_field('cropped_image')}}` because the object will not have the new url reference.

Would it be possible to add a check in the constructor of TimberImage that would overwrite the `url` property if `original_image` is found? Maybe there's a way for me to extend TimberImage and be able to call my custom class in Twig like this `{{CustomImage(post.get_field('cropped_image'))}}`?

Thanks

### What version of WordPress, PHP and Timber are you using?
ACF 5.6.0
Timber  1.2.4
ACF Image Crop Add-on 1.4.12

**Comment by Kwapi** [comment]
Solved it by creating my own Image class that extends TimberImage and added this:

```
 public function init( $iid = false){
        parent::init($iid);

        if ( $this->is_cropped($iid)){
           $this->init_with_url($iid['url']);
        }
    }

    public function is_cropped($iid){
        return is_array($iid) && isset($iid['original_image']);
    }
```

Now it works perfectly. I also made sure I can instantiate my new class from twig by adding this in `functions.php`
```
 function add_to_twig( $twig ) {
    $twig->addFunction(new Twig_SimpleFunction( 'MadeImage', function( $post_id ) {
                    return new MadeImage( $post_id );
                } )
            );
   return $twig;
}
```

Maybe this will help someone else :)

**Comment by roryheaney** [comment]
Do you have an example of where you put that public function? or how you're adding it?  as well as you using the MadeImage ?

**Comment by Kwapi** [comment]
@roryheaney 

I created a `MadeImage.php` file and put it in a `features` folder in my theme (could be any folder really).

Here's what the class looks like:
```
class MadeImage extends \Timber\Image{
    public function __construct($iid)
    {
        parent::__construct($iid);
    }

    public function init( $iid = false){
        parent::init($iid);

        if ( $this->is_cropped($iid)){
           $this->init_with_url($iid['url']);
        }
    }

    public function is_cropped($iid){
        return is_array($iid) && isset($iid['original_image']);
    }
}
```

In order for this class to work we need to include it in `functions.php` like so:
```
include get_template_directory() . '/features/MadeImage.php';
```
I usually put it near the top of the file.

Now, in order to instantiate it in a similar way to the standard Timber approach -  `{{ Image(post.get_field('image') }} we need to add this to the `add_to_twig()` function  in `functions.php`:
```
 $twig->addFunction(new Twig_SimpleFunction( 'MadeImage', function( $post_id ) {
                    return new MadeImage( $post_id );
                } )
            );
```

That way I can do this with a cropped image in a Twig template:

```
   {% set image = MadeImage(post.image) %}
                <img src="{{ image.src }}" alt="{{ image.alt }}" title="{{ image.caption }}">
```

Hope that helps :)

**Comment by gchtr** [comment]
Using a custom class for this is a good way to do it 👍. This should also work in newer versions of Timber. Closing this.
