### ISSUE TITLE
Document hooks used in Timber

### ISSUE THREAD

**Issue by gchtr** [timber/timber#1504]
As @dseidl mentioned in [#1481](https://github.com/timber/timber/issues/1481#issuecomment-319700603), it would be nice if filters used in Timber were documented. I agree with that. And I think that we should also document actions.

Here’s a crazy idea: What if we could document filters the same way as they are documented in WordPress and follow the [Inline Documentation Standards for Hooks](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#4-hooks-actions-and-filters) and then auto-generate a Filter Reference in the documentation?

It would mean that we could add DocBlocks right in front of where filters and actions are used in the code base. Here’s an example for a filter:

```php
/**
 * Filters the Twig environment.
 *
 * Makes it possible to add custom functionality to Twig. Examples are exposing functions
 * to Twig or adding custom filters.
 *
 * @since 1.x.x
 *
 * @api
 * @example
 * ```php
 * // Possibility to add an example
 * ```
 *
 * @param \Twig\Environment $twig The Twig Environment.
 */
$twig = apply_filters( 'timber/twig', $twig );
```

It doesn’t seem to be possible to read out DocBlocks *inside* functions with the [ReflectionClass](http://php.net/manual/en/class.reflectionclass.php) that is already used when generating the current documentation. However, it would be possible with [token_get_all](http://php.net/token_get_all). We could check if the DocBlock starts with `Filters …` for filters and `Fires …` to detect actions. These are the same keywords that you see for hooks in WordPress core.

In the same way as tags like **@api** (for public methods) or **@example** (to provide example code) are already used for class methods for the [Reference](https://timber.github.io/docs/reference/), we could also use these for hooks.

The benefit of having the documentation right in the code is that it’s way easier to keep track of changes. For example: when a filter is deleted, it will be removed from the filter reference automatically. However, I guess we can’t document every aspect of hooks inside DocBlocks. [Guides](https://timber.github.io/docs/guides/) are still a good place to show how filters can help *in a workflow* across different functionalities that Timber provides.

I can start working on this when I finished deprecating the wiki.

Opinions?  
Who wants to help?

**Comment by dseidl** [comment]
@gchtr great idea! auto generated docs all the way.
if you start here let me know. im in. 👍

**Comment by gchtr** [comment]
Hey @dseidl 

I almost forgot about this. The [Documentation for Hooks](https://github.com/timber/timber/blob/master/CONTRIBUTING.md#documenting-hooks) is now defined in CONTRIBUTING.md.

So if you still like to chip in and help us out, you’re more than welcome 😎. Filters are not yet documented in the master branch, but they are in the `2.x` branch. I already defined some `@todo` tags in the DocBlocks of some hooks. And if you have any questions, just ask!
