### ISSUE TITLE
Weird behaviour when using conditional tags in control structure

### ISSUE THREAD

**Issue by almai** [timber/timber#1512]
### Expected behavior
The code in the screenshot should generate a headline (h1 on single pages and h2 in the loop) and a separate "Edit Post" link.

![entry_twig_ ___code_fdk](https://user-images.githubusercontent.com/402692/29042342-d56a7eb2-7bb6-11e7-95b5-156bfe9d765b.jpg)

### Actual behavior
The code creates a headline and puts the following elements between the heading tags.

![fdk_project_ _welcome_to_fabrica_dev_kit](https://user-images.githubusercontent.com/402692/29042417-1ec195aa-7bb7-11e7-869f-fde22864ce61.jpg)

When I replace the function containing the conditional tag `fn('is_singular')` with something that evaluates to true like `1==1` or put the headline in another html tag, then it works as expected.

### What version of WordPress, PHP and Timber are you using?
WordPress 4.8.1, PHP 7.1.7, Timber 1.3.4

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Installed via [Fabrica Dev Kit](https://github.com/fabrica-wp/fabrica-dev-kit)

**Comment by gchtr** [comment]
Hey @almai 

And what is the output if you look at it in the source code view (not in the *Elements* tab of the dev tools, but with right click > View source code)? When you look at the code in the dev tools, that’s [after the browser applied its error correction](http://www.456bereastreet.com/archive/201009/inspect_element_is_not_the_same_as_view_source/).

**Comment by almai** [comment]
Hi @gchtr 

I can't find a closing heading tag in the source code. It doesn't get displayed.

![view-source_localhost_3000](https://user-images.githubusercontent.com/402692/29058538-1a8f9e00-7c11-11e7-8b4b-104fb5573c93.jpg)

**Comment by gchtr** [comment]
Alright, so then apparently `{{ fn('is_singular') ? '</h1>' : '</h2>' }}` is not generating any output.

- From which PHP file in your theme do you call that Twig file?
- Do you have `WP_DEBUG` set to `true`? Are there any warnings or notices in your PHP error log?
- Is there an output if you use a string other than a closing HTML tag, e.g. `'Yes'` and `'No'` instead of `'</h1>'` and `'</h2>'`?

**Comment by almai** [comment]
- entry.twig is included in index.twig and this file is called by index.php.
- Full logging is enabled. There are no entries in debug.log so far.
- If I replace the tags with plain text they will get displayed! I checked my html markup once again but it seems to be right to me...

![entry_twig_ ___code_fdk](https://user-images.githubusercontent.com/402692/29060759-72bdc05c-7c1b-11e7-8caf-8c40a999ffff.jpg)

![view-source_localhost_32769](https://user-images.githubusercontent.com/402692/29060752-65041704-7c1b-11e7-8ea2-b49228fb8b2a.jpg)

**Comment by gchtr** [comment]
It could be that this happens because of the [Escaper extension](https://twig.symfony.com/doc/2.x/api.html#escaper-extension), which is enabled in Timber. 

Does it work if you don’t use the shorthand for the closing tags?

```twig
{% if fn('is_singular') %}
    </h1>
{% else %}
    </h2>
{% endif %}
```

Or the shorthand but not with HTML tags:

```
{{ set closing = fn('is_singular') ? 'h1' : 'h2' }}
</{{ closing }}>
```

**Comment by almai** [comment]
No, I tried all of those variations but none of them worked, except...

    {% if fn('is_singular') %}
      <h1 class="entry-title">
        <a href="{{ post.link }}" title="{{ post.title | apply_filters('esc_attr') }}" rel="bookmark">
          {{ post.title }}
        </a>
      </h1>
    {% else %}
      <h2 class="entry-title">
        <a href="{{ post.link }}" title="{{ post.title | apply_filters('esc_attr') }}" rel="bookmark">
          {{ post.title }}
        </a>
      </h2>
    {% endif %}

But that's not very DRY.

First I suspected the escape filter to mess with the HTML tags but even when I replace the link with plain text the same happens.

**Comment by almai** [comment]
Regarding your second suggestion. This was my first approach:

    {{ set level = fn('is_singular') ? '1' : '2' }}
    <h{{ level }} class="entry-title">
      <a href="{{ post.link }}" title="{{ post.title | apply_filters('esc_attr') }}" rel="bookmark">
        {{ post.title }}
      </a>
    </h{{ level }}>

But when I try this I encounter this error:

`Parse error: syntax error, unexpected '$data' (T_VARIABLE) in /var/www/html/wp-content/themes/fdk/index.php on line 4`

I'm not sure if you're allowed to do sth. like this in twig anyway. So I tried the 2nd approch with two if/else.

**Comment by almai** [comment]
Ok, I tested it on a fresh WP installation with the Timber plugin and the starter theme. It works just fine! Seems to be an issue with the Fabrica stack or a local problem. Sorry for bugging you.

**Comment by gchtr** [comment]
That’s funny, because I can totally replicate your error when using

```twig
{{ fn('is_singular') ? '</h1>' : '</h2>' }}
```

It doesn’t output anything for me as well. But I’m not a Twig expert either, so I don’t know why it can’t handle these HTML tags 🙈.

And well, my shorthand example contains an error. It should be:

```
{% set closing = fn('is_singular') ? 'h1' : 'h2' %}
</{{ closing }}>
```

Sorry about that. For me it also works if I use the `raw` filter:

```twig
{{ fn('is_singular') ? '</h1>'|raw : '</h2>'|raw }}
```

But cool if it now works for you! So I guess we’ll leave it like that :).

**Comment by almai** [comment]
Just for the record: I've found the cause of this problem. It's the posthtml-bem plugin that interferes with the twig code. It confuses everything within angle brackets as an attribute-value pair and tries to render it.

https://github.com/fabrica-wp/fabrica-dev-kit/issues/14
