### ISSUE TITLE
Fatal Error - Can't use function return in write context

### ISSUE THREAD

**Issue by danFWD** [timber/timber#1518]
### VERSION
Wordpress 4.8, Timber 1.4.0, PHP 5.6.24

### ERROR
Can't use function return in write context on line 130 of /timber-library/lib/URLHelper.php
```
	public static function is_local( $url ) {
		if ( !empty(self::get_host()) && strstr($url, self::get_host()) ) {
			return true;
		}
		return false;
	}
```
As mentioned here:
https://stackoverflow.com/questions/1075534/cant-use-method-return-value-in-write-context
...this issue was supposedly corrected in PHP 5.5+, but I experienced it with 5.6.x.

### MY FIX
```
	public static function is_local( $url ) {
		$v = self::get_host();
		if ( !empty($v) && strstr($url, $v) ) {
			return true;
		}
		return false;
	}
```

### How did you install Timber? 
Upgraded to newest version via plugin updater in WordPress dashboard

**Comment by danFWD** [comment]
Or a little more succinct fix:
```
	public static function is_local( $url ) {
		$v = (string) self::get_host();
		return !empty( $v ) && strstr( $url, $v ) ? TRUE : FALSE;
	}
```

**Comment by jarednova** [comment]
@danFWD thanks for alerting me to this. That's .... annoying! PR/fix coming right up based on your suggestion

**Comment by jarednova** [comment]
This is fixed in #1518 — thanks again @danFWD for the heads-up and the ready-made fix!

**Comment by danFWD** [comment]
I appreciate the quick response. This is my favorite plugin of all time. 
Regards,
Dan

**Comment by jarednova** [comment]
Wow, thanks @danFWD! Please "Star" the project on GitHub to help spread the word!
