### ISSUE TITLE
Can't get the menu item.is_external to work

### ISSUE THREAD

**Issue by duezerouno** [timber/timber#1523]
Both methods always return _self. Can't really understand why... I am selecting the _blank target option from the menu editor in WP. Any idea?

```
<li class="menu_link">
  <a href="{{item.link}}" target="{{ item.is_external ? '_blank' : '_self' }}" class="{{item.classes | join(' ')}} {% if 'current-page-ancestor' in item.classes or 'current-menu-item' in item.classes %} active {% endif %} ">{{item.title}}</a>
</li>
```
```
<li class="menu_link">
  <a href="{{item.link}}" target="{% if item.is_external %}_blank{% else %}_self{% endif %}" class="{{item.classes | join(' ')}} {% if 'current-page-ancestor' in item.classes or 'current-menu-item' in item.classes %} active {% endif %} ">{{item.title}}</a>
</li>
```

**Comment by gchtr** [comment]
Hey @duezerouno 

Do you use a full URL for the external link (starting with `http://`)?

And can you provide some more information on the environment that you are using?

- What version of WordPress, PHP and Timber are you using?
- How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
- Does this happen on your local machine or on a server?

**Comment by duezerouno** [comment]
@gchtr thanks for your reply! I actually used a non full URL but I just noticed that Wordpress automatically adds http:// on menu save.  WP 4.8.1, Timber 1.4.1, Installed from wp.org and it's happening on a server.

**Comment by gchtr** [comment]
Can you do a `var_dump( $_SERVER );` somewhere in your PHP and check if either `$_SERVER['HTTP_HOST']` and/or `$_SERVER['SERVER_NAME']` are set and contain the hostname to your website hosted on the server?

**Comment by duezerouno** [comment]
Yes they both contain the right domain name. I have wp installed on a subdirectory, could that be causing the issue?

**Comment by duezerouno** [comment]
I see...tried and it returns `NULL`

**Comment by duezerouno** [comment]
@gchtr well. just found the solution in the _s starter theme: using `{{ item.target }}` did the trick 🥇
