### ISSUE TITLE
Timber documentation links are broken

### ISSUE THREAD

**Issue by oskari** [timber/timber#1525]
Links to Timber Documentation seem to be broken on readme.md, 404 Github Pages error is shown.

**Comment by gchtr** [comment]
The links are ok, but the documentation is **currently down**. We’re looking into this.

In the meantime, you can always navigate the docs in the `docs/` folder: https://github.com/timber/timber/tree/master/docs. Except for the reference for PHP classes, which is auto-generated when building the docs.

**Comment by jarednova** [comment]
@oskari thanks for the heads-up! I inadvertently unpublished them last night when I was trying to fix something, totally my b. Everything should be good now!
