### ISSUE TITLE
AFC repeater values from custom post type returned as strings and not arrays.

### ISSUE THREAD

**Issue by neutraltone** [timber/timber#1527]
### Expected behavior
When assigning custom post type to the `Post()` object, repeater ACF fields should be output as an array with it's keys values of those set in wordpress admin.

### Actual behavior
The output data is assigning the names of my custom fields as strings making them inaccessible in my twig template

### Steps to reproduce behavior
- Enable ACF pro and timber.
- Create a repeated field associated with a custom post type (in this case MyCustomPostType)
- Assign both the post and the custom post type to the `post()` object.
- `var_dump` the data from the custom post type and look at the references to a repeated field. (in the dump below my repeater field is represented by the `book_source` field)

**front-page.php**
```
<?php

use Timber\Timber;
use Timber\Post;

$context = Timber::get_context();

$context['post'] = new Post();
$context['MyCustomPostType'] = new Post(10);

var_dump($context['MyCustomPostType']);
die;

Timber::render('layouts/article.twig', $context);
```

**From `var_dump($context['MyCustomPostType']);`**

```
...
public 'book_sources_0_source_text' => string 'Financial Times – PPI claims boosted by value of interest payouts' (length=67)
  public '_book_sources_0_source_text' => string 'field_599aba777a8e3' (length=19)
  public 'book_sources_0_source_link' => string 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjflaqfrdvVAhXJCMAKHZwBCH0QFggmMAA&url=https%3A%2F%2Fwww.ft.com%2Fcontent%2F54bd0d52-fb3d-11e5-b3f6-11d5706b613b&usg=AFQjCNEJy4g_vCz8Xm7hfw1w252SPrRzFA' (length=240)
  public '_book_sources_0_source_link' => string 'field_599abaae7a8e4' (length=19)
  public 'book_sources' => string '2' (length=1)
  public '_book_sources' => string 'field_599ab90a7a8e2' (length=19)
  public 'book_sources_1_source_text' => string 'another test' (length=12)
  public '_book_sources_1_source_text' => string 'field_599aba777a8e3' (length=19)
  public 'book_sources_1_source_link' => string 'http://google.com' (length=17)
  public '_book_sources_1_source_link' => string 'field_599abaae7a8e4' (length=19)
...
  public 'status' => string 'publish' (length=7)
  public 'custom' => 
    array (size=12)
      '_edit_last' => string '1' (length=1)
      '_edit_lock' => string '1503321243:1' (length=12)
      'book_sources_0_source_text' => string 'Financial Times – PPI claims boosted by value of interest payouts' (length=67)
      '_book_sources_0_source_text' => string 'field_599aba777a8e3' (length=19)
      'book_sources_0_source_link' => string 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjflaqfrdvVAhXJCMAKHZwBCH0QFggmMAA&url=https%3A%2F%2Fwww.ft.com%2Fcontent%2F54bd0d52-fb3d-11e5-b3f6-11d5706b613b&usg=AFQjCNEJy4g_vCz8Xm7hfw1w252SPrRzFA' (length=240)
      '_book_sources_0_source_link' => string 'field_599abaae7a8e4' (length=19)
      'book_sources' => string '2' (length=1)
      '_book_sources' => string 'field_599ab90a7a8e2' (length=19)
      'book_sources_1_source_text' => string 'another test' (length=12)
      '_book_sources_1_source_text' => string 'field_599aba777a8e3' (length=19)
      'book_sources_1_source_link' => string 'http://google.com' (length=17)
      '_book_sources_1_source_link' => string 'field_599abaae7a8e4' (length=19)
```

### What version of WordPress, PHP and Timber are you using?
WordPress 4.8.1, PHP 7.1, Timber 1.4

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by gchtr** [comment]
Thanks for taking the time to fill in the issue template!

When look at the `$post` variable, you see a lot of fields like `book_sources_1_source_link` and `_book_sources_1_source_link`. That’s the way the custom field data is saved in the `wp_postmeta` table in the database. Timber will take all the post meta data assigned to a post and make them available as properties. It’s true that this is not very convenient to work with when you have a repeater field.

When [working with repeater (and flexible content) fields in ACF](https://timber.github.io/docs/guides/acf-cookbook/#repeater-field), you always need to use the `get_field` method on the `Timber\Post` object, so that the correct ACF filters are applied that convert the data into an array to work with. Try it with the following to see how it works:

```php
$context = Timber::get_context();

$post = Timber::get_post();

$repeater = $post->get_field( 'book_sources' );
var_dump( $repeater );
```

But you don’t need to do that in PHP for every repeater field. When you have this in PHP:

```php
$context = Timber::get_context();
$context['post'] = Timber::get_post();

Timber::render( 'layouts/article.twig', $context );
```

You can do the following in Twig:

```twig
{% for source in post.get_field('book_sources') %}
    {{ source.text }}
{% endfor %}
```

**Comment by neutraltone** [comment]
Thanks for taking the time to reply. It seems that `get_field` is not working in this case. I have following in my `front-page.php` this time. (books being my custom post type):
```
var_dump($context['books']->get_field('books_sources'));
die;
```
only to be returned the following:
```
/home/vagrant/Code/neutraltone.com/web/app/themes/neutraltone/front-page.php:25:string '2' (length=1)
```

**Comment by gchtr** [comment]
Is your field called `books_sources` or `book_sources`?

**Comment by neutraltone** [comment]
That was in fact a typo in my example naming above, I meant to put `book_sources`, which results in the aforementioned dump.

**Comment by gchtr** [comment]
What if you use `Timber::get_post()` instead of instantiating a new `Timber\Post` object directly? 

```php
$context['post'] = Timber::get_post();
$context['books'] = Timber::get_post( 10 );
```

**Comment by neutraltone** [comment]
Unfortunately that results in the same result, nothing being rendered from the for loop in the twig template.

Here's what I include in my front-page.php, just so we're on the same page:
```
use Timber\Timber;

$context = Timber::get_context();

$context['post'] = Timber::get_post();
$context['advertorial'] = Timber::get_post(10);

Timber::render('layouts/article.twig', $context);
```

**Comment by neromaki** [comment]
Having the same issue, have tried both methods outlined here: https://github.com/timber/timber/issues/1527#issuecomment-323755822

but both return the number of items in the repeater:

```
$context = Timber::get_context();
$post = Timber::get_post();
$repeater = $post->get_field( 'a_repeater' );
var_dump( $repeater ); // returns string '2' (the number of items in the repeater)
```

Am I missing a crucial step or something.?

**Comment by neutraltone** [comment]
OK i've solved my issue. Stupidly I had omited `new Timber\Timber` from my functions file causing mixed results when rendering values from ACF. Sorry for wasting anyones times.

**Comment by robindarlington** [comment]
> OK i've solved my issue. Stupidly I had omited `new Timber\Timber` from my functions file causing mixed results when rendering values from ACF. Sorry for wasting anyones times.

Thanks for this. I'm learning how to use Timber, and thanks to you I found my way out of the same situation you had been in.
