### ISSUE TITLE
Warning: Wrong parameter count for class_alias()

### ISSUE THREAD

**Issue by danFWD** [timber/timber#1530]
I just moved my WP site from my local dev server which has PHP version 7.0.15 to the live hosting environment which has PHP 7.0.22. All of a sudden, every single included class file is throwing the warning
`Wrong parameter count for class_alias() in /home/etc...`

There isn't much information to be had googling this issue, but one reference said that some versions of PHP throw this warning when the third argument for 'autoload' is included. So I tested this theory and changed:
`class_alias('Twig_Token', 'Twig\Token', FALSE);`
  to 
`class_alias('Twig_Token', 'Twig\Token');`
...and sure enough, the warning disappeared. 

The problem with this is that it appears that the 3rd argument 'autoload' defaults to TRUE, but all these class_alias autoloads are set to FALSE. 

Obviously this problem goes away as soon as I set WP_DEBUG to false (and everything appears to work fine), but my questions are, why is it behaving this way and what can be done about it? Does it harm anything if autoload is set to TRUE?

#### What version of WordPress, PHP and Timber are you using?
Wordpress 4.8.1, Timber 1.4.1, PHP 7.0.22

#### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Installed via WP.org

**Comment by venutip** [comment]
I'm having the same issue. Removing the third argument to `class_alias` also resolved the warning with no apparent side effects. In my case, however, the problem seems to be when Timber was upgraded to 1.4.1 and WordPress was upgraded to 4.8.1.

**What version of WordPress, PHP and Timber are you using?**

Wordpress 4.8.1, Timber 1.4.1, PHP 5.3.29

**How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)**

I didn't do the upgrade, but I believe it was done from within the WordPress admin dashboard.

**Comment by jarednova** [comment]
@venutip @danFWD — thanks for the note on this! Based on what you're describing it sounds like an issue within Twig itself. This appears to be a very recent addition to Twig:

https://github.com/twigphp/Twig/commit/5420a5e3f8a7a36022e8a7cccdde7f99ec0e14f3

I perused their issues but didn't see anything. If you want to file an issue with them, Timber 1.4.1 on WP.org uses Twig 1.34.4 (most recent release of 1.34.*)

**Comment by Sean3llis** [comment]
Probably too late, but for any wayward google searchers with the `Warning: Wrong parameter count for class_alias() ` errors - I had the same issue and saw on the [twig install](https://twig.symfony.com/doc/2.x/intro.html#installation) you need PHP 7.0.0. Woops. My server was at 5 something, updated and fixed the bug for me.

**Comment by brandonokk** [comment]
dddfdf
