### ISSUE TITLE
query_post and PostClassMap?

### ISSUE THREAD

**Issue by Kwapi** [timber/timber#1533]
I can override the PostClassMap and add my own mapping so that each custom post type has their own extended TimberPost class but unfortunately this doesn't work in the single.php view where the post is obtained using the `query_post` function. That function needs to have the PostClass passed directly which goes against the PostClassMapping in the first place. Is there a way to use that mapping with `query_post`?

Alternatively, are there any other ways I could achieve this?

Timber 1.4.1

**Comment by corradomatt** [comment]
I just ran into the same issue. I'm mapping posts with the `Timber\PostClassMap` filter but have to pass the mapping directly to `query_post` as well. It would be nice to have the filter just work for any query out of Timber.

**Comment by webaware** [comment]
If you replace `Timber::query_post()` with `Timber::get_post()` in your single.php template, it will correctly call the PostClassMap filter.

**Comment by gchtr** [comment]
`Timber::query_post()` will be removed in future versions of Timber. The correct way is indeed to use `Timber::get_post()`.

Thank you, @webaware, for pointing to the right solution in this older issue 👍.
