### ISSUE TITLE
Preview just break my site

### ISSUE THREAD

**Issue by chaimaech** [timber/timber#1534]
Hello ! 😄 
On my homepage (and all the categories), I display a list of my posts, using "get_preview". But last week, I noticed that on my local, I had a 500 on every page (but single posts pages). When I commented the "get_preview" line, my site worked perfectly (but I had no preview on my list)... 

I saw that "get_preview" was deprecated so I tried to use preview, instead but I still have an error.

```twig
{# the line I've used before #}
{{ post.get_preview(15, true, false, true) }}

{# the lines I tried to use instead #}
{{ post.preview }}
{{ post.preview.read_more('More!') }}
{{ post.preview.length(15).force.read_more(false).strip }}
```
I also tried to replace all my template with the one from the timber starter theme but nothing works !

**Comment by jarednova** [comment]
@chaimaech can you post more info on the error? Check the error logs so we can see what lead to the 500 error

**Comment by palmiak** [comment]
@chaimaech which version are you using? I've just tested your code and It works fine.

Probably the problem is located somewhere else.

**Comment by chaimaech** [comment]
@palmiak @jarednova It's only on dev environment and I ended ignoring it because I couldn't gather more information ^^ Sorry :'(
