### ISSUE TITLE
[Improvement] Building the context hierarchically

### ISSUE THREAD

**Issue by danburzo** [timber/timber#1536]
Tangential to #1526, and a funny coincidence. 

I'm currently looking for ways to hack the WordPress template hierarchy for cleaner working with WP + Timber, specifically: have a way to augment the Context based on the template hierarchy.

E.g. if I were to render a single page (`page-foo.php`), I want to hierarchically call some code for:

```
1. index.php
2. singular.php
3. page.php
4. page-foo.php
```

To keep adding more and more specific properties to the context object, and keep the theme DRY. 

It has come to my attention that [Brain-WP/Context](https://github.com/Brain-WP/Context) aims to do something similar. If included in Timber, this kind of functionality would be 💯 developer comfort.

**Comment by gchtr** [comment]
I’m closing this.

We probably won’t add this to Timber itself, because there are libraries like https://github.com/Brain-WP/Context out there that already solve this.
