### ISSUE TITLE
The rendered content via template_include action is not displayed after get_footer() function is called.

### ISSUE THREAD

**Issue by kataskeviwebsite** [timber/timber#1553]
I use a rockettheme template called Gemini and also i use a plugin for rent cars and when somebody went to use the forms and put the submit button it must show a general resume form and it didn't show it.
It is a bug in the timber theme, we debugged it and everything is ok until wp_footer is called, there is a timber theme function which not render previously loaded content. The theme used is gantry5 framework so it is not easy to debug something else there. why the rendered content via template_include action is not displayed after get_footer() function is called.

**Comment by kataskeviwebsite** [comment]
can you answer please?

**Comment by blizam** [comment]
bump

**Comment by gchtr** [comment]
Hey there

Sorry, there’s a lot of work going on in different areas of Timber. It would definitely help if you could provide more detailed instructions for how to reproduce the error. That’s also why there is an issue template with information that we’d like to know.

It would be good to see how that plugin for renting cars is hooking into the theme. Is it in the official plugin directory? Can you give a link to that? Or is it not specially related to that plugin? Do you have some example code that illustrates the problem?

**Comment by kataskeviwebsite** [comment]
It is defined as:

add_action('template_include', array('CarRental', 'carrental_summary'));

where is our template file included.

**Comment by gchtr** [comment]
Hey @kataskeviwebsite 

It’s really hard to reproduce the error with the information that you’ve given. If you can’t provide us with the steps to reproduce the error, I’m afraid we can’t help you.

Usually, the `template_include` hook is a filter and not and action. If it’s added as an action and doesn’t return a value, it may break your theme.

> there is a timber theme function which not render previously loaded content

So what function is this? Is in the Gantry 5 theme? I’m afraid we can’t provide support for issues that are directly related to theme.

Does the error also occur if you use the [Starter Theme](https://github.com/timber/starter-theme)?
