### ISSUE TITLE
Clearly document the escaping strategy of Timber

### ISSUE THREAD

**Issue by johnbillion** [timber/timber#1557]
The Timber library does't clearly state its strategy for escaping. This means developers who are new to Twig but are familiar with other templating engines might expect that a `{{` double brace expression `}}` has its output automatically escaped. For example, [Handlebars](http://handlebarsjs.com/) automatically escapes expressions in double braces, and triple braces need to be used to output raw HTML.

The [Escapers documentation](https://timber.github.io/docs/guides/escapers/) doesn't really clarify things. #615 gives us the definitive answer, as does reading the code in the `Timber\Timber\get_twig()` method.

The readme file or the documentation should be updated to clearly state Timber's escaping strategy, along with how to enabled `autoescape` via adding `Timber::$autoescape = true;` to your theme's `functions.php`.

**Comment by mahagr** [comment]
In addition to this, it would be nice if the examples used `|raw` filter on variables which are known to be escaped and `|e` when they should be escaped. This would be a good practice as then all the examples would work with both settings.

**Comment by johnbillion** [comment]
I've just discovered that vanilla Twig _does_ escape by default, and Timber disables this. Ref: https://twig.symfony.com/doc/2.x/templates.html#html-escaping

This increases the need for documentation that clarifies the situation.

**Comment by jarednova** [comment]
@johnbillion thanks for the heads-up on this. There are reasons good and bad for this default (mostly bad). But regardless, I agree this should be clearly documented.

I've added #1562 to resolve the documentation gap. 

However, given your experience (and the fact that this is Twig's default behavior) I think it makes sense to consider making escaping the _default_. However, I'm nervous about rolling out a potential breaking change like that. Do you have any advice or recommendation here?

**Comment by johnbillion** [comment]
That's a big change to make :-)

I'm currently investigating some weird behaviour on a client site with autoescaping enabled. I'll report back soon.

**Comment by johnbillion** [comment]
It looks like the issue I mentioned above is an anomaly, but we're still looking into it.

In the meantime, yes I could support switching to escaping by default in Timber as I think it's expected behaviour given that's how Twig works.

Given that Timber seems to support semver, a version 2.0 could be released which switches to escaping by default as a breaking change. This would potentially cause issues for users who are using the Timber Library plugin via the w.org plugin directory, though. There's not really a good way to deal with that.

**Comment by mahagr** [comment]
I think that the good start would be to add proper escaping (or rather `|raw`) to all fields that require it. After you've confirmed that everything still works, it may be time to get 2.0 out with escaping turned on by default.

**Comment by tapetersen** [comment]
I would also like the default to be autoescape but Having changed it in one project I can kindof see the reasons for not having it be the default. Nearly all of wordpress's functions and tags returned pre escaped data which necessitates an explicit '|raw' for things such as titles and fields to avoid having them double escaped and this is true for Timbers own helper functions such as TimberPost and such as well. While autoescaping propably *is* the better alternative in a vacuum the prevalence of pre escaped values being the norm in this eco system will propably lead to blanket insertions of raw everywhere and the same security issues as having it turned off like now.

While I agree that most people working with template engines would expect them to escape their values most would also expect their api layer *not to* escape them which places Timber in a kind of awkward position. Even if Timber changes their apis to return unescaped values by default people would still get escaped values from wordpress functions and put in their templates.

Not sure deviating from the wordpress standard here is the best idea even if that standard propably isn't the best idea in the first place.

Personally I would welcome the change to update the default to autoescaping but I'm not sure it actually changes that much more than force people to put a raw filter on 95% of their values and thus make this the habit and get the security bugs anyway.

**Comment by gchtr** [comment]
I think @tapetersen raises a very good point here: 

> While autoescaping propably is the better alternative in a vacuum the prevalence of pre escaped values being the norm in this eco system will propably lead to blanket insertions of raw everywhere and the same security issues as having it turned off like now.

I really don’t know what the best way would be. While I personally would also like to see the values to be escaped by default, I’m torn between following the WordPress standard of escaping as late as possible and the Twig standard, to escape by default.

But either way, I think it’s clear that we could address this better throughout the documentation:

- **With autoescaping enabled**: Update all examples in DocBlocks and in Markdown documentation files with `|raw` filters, where needed.
- **With autoescaping disabled**: Update all examples in DocBlocks and in Markdown documentation files with the proper `|e` filters.

Whatever we do, it would be nice if we could at least document in the method DocBlocks whether the Timber methods return escaped values or not. I didn’t see yet a standard way how WordPress core documents this. I see two possibilities here:

**Explicitly write it into the description of the `@return` tags.**

An example:
    
```
/**
 * Summary.
 *
 * Description.
 *
 * @param type $var Optional. Description. Default.
 * @return type Description. Escaped.
 */
```

For unescaped values we could write `Unescaped.`.

**Use special tags**

We could use special tags to mark functions that return escaped values, maybe `@escaped` and `@unescaped`, or `@escaped Yes` and `@escaped No`. The advantage of this would be that it’s easier to list and style them in the [reference](https://timber.github.io/docs/reference/). An example:

```
/**
 * Summary.
 *
 * Description.
 *
 * @escaped Yes
 *
 * @return type Description.
 */
```

**Comment by jarednova** [comment]
@gchtr have been talking about this over email and here's what we've come to: It's very expensive (where expense = a lot of considerations from us, and a lot of change from Timber users) to make this switch to default escaping. Further, it's unclear how it really "helps." The comment from @tapetersen puts a good point on it, basically: "Timber is stuck between Twig and WP — both have diff't opinions on auto escaping." 

Here's where we plan to take things
- [ ] First, to the title of this ticket: document this VERY CLEARLY AND LOUDLY. Document it as an explicit decision of Timber, not just an accident.
- [ ] Document the recommended route for those who want to 
  - [ ] a) escape fields
  - [ ] b) make this default behavior
- [ ] Demonstrate in the starter theme that "raw" is the default behavior and how to (easily!) override.

**Comment by chrisvanpatten** [comment]
Perhaps a dumb question, but is there a reason Twig's `is_safe` option couldn't be used? That _should_ allow you to mark Twig functions as pre-escaped, so they bypass global escaping. It would require reworking some things to be functions (rather than vars passed through global context) but it could be an option…

Barring that, documenting the hell out of this seems like a fair fallback given the situation.

**Comment by mahagr** [comment]
I'm using `is_safe` option in my own filters etc to make things simpler, so yeah, it is totally worth it. Unfortunately it doesn't work with object methods.

**Comment by jarednova** [comment]
I have to admit that `is_safe` is news to me. I took a look though and like @mahagr says it seems to only apply to filters. @chrisvanpatten do you have a usage example as you use it (that could be adapted here)?

**Comment by jarednova** [comment]
I just submitted a PR to the starter theme to hopefully resolve this. Also, I've verified that the docs now make this clear:

https://timber.github.io/docs/guides/escapers/#universal-escaping

Once tests pass on starter theme, I'm going to merge that in and call it done. I'm still open to exploring the `is_safe` method in the future, but I'm prepared to call this done based on the original prompt: "Clearly document the escaping strategy of Timber"
