### ISSUE TITLE
HTTP Error on Image Upload 

### ISSUE THREAD

**Issue by stirtingale** [timber/timber#1559]
### Expected behavior

Media Library > Upload New Image > Image Created and added to library

### Actual behavior

Unable to upload images to Wordpress with Timber enabled/active

Returns error message

![screen shot 2017-09-25 at 15 44 46](https://user-images.githubusercontent.com/25981099/30814645-ac6318d0-a208-11e7-8ed3-903f52a09808.jpg)

`Fatal error: Uncaught Error: Cannot access empty property in /srv/users/serverpilot/apps/wearekiosk/public/wp-content/plugins/timber-library/lib/Image.php:285 Stack trace: #0 /srv/users/serverpilot/apps/wearekiosk/public/wp-content/plugins/timber-library/lib/Image.php(100): Timber\Image->init(4630) #1 /srv/users/serverpilot/apps/wearekiosk/public/wp-content/plugins/timber-library/lib/ImageHelper.php(205): Timber\Image->__construct(4630) #2 /srv/users/serverpilot/apps/wearekiosk/public/wp-content/plugins/timber-library/lib/ImageHelper.php(177): Timber\ImageHelper::_delete_generated_if_image(4630) #3 /srv/users/serverpilot/apps/wearekiosk/public/wp-includes/class-wp-hook.php(298): Timber\ImageHelper::Timber\{closure}(Array, 4630) #4 /srv/users/serverpilot/apps/wearekiosk/public/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #5 /srv/users/serverpilot/apps/wearekiosk/public/wp-admin/includes/image.php(292): apply_filters('wp_generate_att...', Array, 4630) #6 /srv/users/serverpilot/apps/wearekiosk/public/wp- in /srv/users/serverpilot/apps/wearekiosk/public/wp-content/plugins/timber-library/lib/Image.php on line 285`

(Possibly similar to #1346)

### Steps to reproduce behavior

With Timber enabled; add any jpg/png/gif image to library. HTTP error returned. 

### What version of WordPress, PHP and Timber are you using?
Wordpress Version 4.8.2
Timber Version 1.4.1 
PHP 7
LAMP Stack

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Plugin from Wordpress Repo. Custom theme

**Comment by stirtingale** [comment]
This looks to be the same issue as #1269 which was unresolved in December 2016. 

This breaks the front-end, as well as image ingestion into the media library, and deleting images from the media library

**Comment by gchtr** [comment]
To boil this down, probably more info is needed.

What plugins do you have installed? Does the error still occur if you deactivate all of the other plugins?

**Comment by stirtingale** [comment]
@gchtr 

_With all other plugins deactivated it still fails._ 

Switching to Twenty Seventeen allows me to upload successfully which means something is wrong with my custom theme. (I am maintaining an existing design rather than the initial dev) 

However; I cannot anything that would hook into the image ingestion process. 

I understand why it would fail when it hits the resize(XXX) code on a single-template but I don't understand what would hook into the initial upload and delete (which are both failing). 

My working assumption is incorrectly declared but my understanding is that image sizes are declared 'on the fly' within each twig rather than globally for the theme?

**Comment by gchtr** [comment]
> I understand why it would fail when it hits the resize(XXX) code on a single-template but I don't understand what would hook into the initial upload and delete (which are both failing).

This sounds very much like it’s something in your custom theme causing the error. Sometimes the culprit can be where you wouldn’t expect it. Try to look for filters and actions that are used in the theme. You could search for `add_filter` and `add_action` in your theme’s folder to get a list of all hooks. Try to deactivate them and see if any of these is causing the error.

Does the theme overwrite [pluggable functions](https://codex.wordpress.org/Pluggable_Functions)? They might also affect the backend, though it’s more unlikely that it would have something to do with images.

> … my understanding is that image sizes are declared 'on the fly' within each twig rather than globally for the theme?

Yes, they are. When the template is loaded and `resize()` is called, Timber checks for the image to exist and generates the new size on the fly if it doesn’t. When you upload them, sizes defined in the resize filter won’t be generated.

**Comment by stirtingale** [comment]
Thanks for the point -- it looks like the original developer was hooking into @ add_attachment to set orientation data on upload. This was the cause of it initially borking the ingestion

However, what I have noticed is that the error persists on image delete for images that I uploaded with Timber disabled. I assume because it is looking for ID's/sizes that were never generated and crashes with that same error.

I am able to delete images that are uploaded with Timber enabled? 

Not a site breaking issue but a bit of a quirk? My initial is resolved. Should I close the ticket?

**Comment by gchtr** [comment]
Great that you found the cause of the issue! And yes, if your initial problem is resolved, you can close the ticket.

It could very well be that there’s data missing that WordPress is trying to delete. If it’s not too many images, you could manually delete the entries in the `wp_posts` table and the files in the uploads folder and then use [WP-Sweep](https://de.wordpress.org/plugins/wp-sweep/) to delete all orphaned entries in other database tables.

As usual, always **create a backup** of your website before doing that.

**Comment by stirtingale** [comment]
@gchtr thanks for your help
