### ISSUE TITLE
Posts from a category menu item not showing as expected in front end

### ISSUE THREAD

**Issue by kamontander** [timber/timber#1560]
### Expected behavior
I've created a function that adds posts from a category as submenu items to a category menu item. The posts may be assigned multiple categories, such as this:
```
Post 1 (Categories: A, B, C)
Post 2 (Categories: A, B)
Post 3 (Categories: A, C)
Post 4 (Categories: B, C)
Post 5 (Categories: A)
```
This is what I'm hoping to get from Timber:
```
<ul>
  <li>
    Category A
    <ul>
      <li>Post 1</li>
      <li>Post 2</li>
      <li>Post 3</li>
      <li>Post 5</li>
    </ul>
  </li>
  <li>
    Category B
    <ul>
      <li>Post 1</li>
      <li>Post 2</li>
      <li>Post 4</li>
    </ul>
  </li>
  <li>
    Category C
    <ul>
      <li>Post 1</li>
      <li>Post 3</li>
      <li>Post 4</li>
    </ul>
  </li>
</ul>
```

### Actual behavior
While the code works well in plain PHP, the following problem appears using Timber's `item.get_children` function: when a post is assigned multiple categories, with all of them listed in the menu, it will be shown only under the most recent category menu item. When Timber calls `order_children()`, duplicate entries (i.e. posts belonging to more than one of the menu categories) get overwritten, so this gets output:
```
<ul>
  <li>
    Category A
    <ul>
      <li>Post 5</li>
    </ul>
  </li>
  <li>
    Category B
    <ul>
      <li>Post 2</li>
    </ul>
  </li>
  <li>
    Category C
    <ul>
      <li>Post 1</li>
      <li>Post 3</li>
      <li>Post 4</li>
    </ul>
  </li>
</ul>
```

### Steps to reproduce behavior
[Here is the function](https://gist.github.com/kamontander/4d02fb9744872b448017dc2717cbde22) I'm using to add the posts from a category menu item to a submenu in Wordpress, and this is [the Timber menu template](https://gist.github.com/kamontander/ee1341fe049456d126c78f776171cfd3).

### What version of WordPress, PHP and Timber are you using?
WordPress 4.8.2, PHP 7.0.3, Timber 1.4.1

### How did you install Timber?
Freshly installed the newest version via plugin updater in WordPress dashboard.

**Comment by Levdbas** [comment]
Stale, closing
