### ISSUE TITLE
I need help 

### ISSUE THREAD

**Issue by Emtree** [timber/timber#1565]
Hello guys, I need some help. I think this is not an issue but more like a question on how to do it. 
I'm using WordPress's theme Hydrogen (Gantry Framework) and I have a problem with image thumbnail.
I want to use srcset for thumbnail images and I want the image to be loaded with a different size and path from the original (not to be HTML re-sized) like in the example attached.
![example](https://user-images.githubusercontent.com/16117229/31033883-0cf7033a-a562-11e7-9d74-6dea72cf800d.jpg)
![example1](https://user-images.githubusercontent.com/16117229/31034225-731f46e4-a563-11e7-9371-eec54a2b9ad1.jpg)
![example2](https://user-images.githubusercontent.com/16117229/31034226-73215542-a563-11e7-8a77-b003549641bb.jpg)
I don't know if you understood me or not, but if not I'll try to explain it better.
Thank you for your time :)

**Comment by marciojc** [comment]
Hi, did you see the https://timber.github.io/docs/guides/cookbook-images/ documentation? `Arbitrary resizing of images ` maybe helps you.

**Comment by Emtree** [comment]
Yes, and I have no idea how to do that, I don't know which files to edit to achieve that. Can you help me?

**Comment by marciojc** [comment]
Is your theme a Timber template?

**Comment by Emtree** [comment]
Yes, it uses twig and timber.

**Comment by marciojc** [comment]
You need to find the twig of that page or block

**Comment by Emtree** [comment]
Yeah.. that's what I was asking for... I was lost in the files trying to find the image property and make changes.

**Comment by jarednova** [comment]
Hi @Emtree, since this is a support question I'd recommend posting your question to StackOverflow:

https://stackoverflow.com/questions/tagged/timber

... there, it's easier to follow-up on a specific usage issue. Thanks!
