### ISSUE TITLE
Duplicate folders in 1.5.0 release

### ISSUE THREAD

**Issue by Arno33** [timber/timber#1566]
The plugin zip file available for version 1.5.0 on Wordpress plugin repository contains extra folders.

### Expected behavior
- timber-library
  - lib
    - Cache
    - Image
    - Integrations
  - timber-starter-theme
    - bin
    - static
    - templates
    - tests
  - vendor
    - altorouter
    - asm89
    - composer
    - twig
    - upstatement

### Actual behavior
- timber-library
  - lib
    - Cache
    - Image
    - Integrations
    - **lib (duplicate of parent folder)**
  - timber-starter-theme
    - bin
    - static
    - templates
    - tests
    - **timber-starter-theme (duplicate of parent folder)**
  - vendor
    - altorouter
    - asm89
    - composer
    - twig
    - upstatement
    - **vendor (duplicate of parent folder)**

### Steps to reproduce behavior
Download zip file on [Wordpress plugin page](https://wordpress.org/plugins/timber-library/) 
or
install/update plugin from Wordpress BO
or
install/update via composer (wpackagist)

### What version of WordPress, PHP and Timber are you using?
Timber 1.5.0

**Comment by jarednova** [comment]
Thanks for the heads-up @Arno33 — I just cleaned those out
