### ISSUE TITLE
Using Guzzle within Timber

### ISSUE THREAD

**Issue by timknight** [timber/timber#1567]
I'm just curious if anyone has any experience implementing guzzle within Timber.

I have guzzle installed with Timber using composer.

Then just to test it out I added the following within page.php:

```
use GuzzleHttp\Client;
$client = new Client();
$response = $client->request('GET', 'https://api.github.com/repos/guzzle/guzzle');
$context['feed'] = $response->getBody();
```

In the template I dump the feed:

```
<pre>{{ dump(feed) }}</pre>
```

Which produces:

```
object(GuzzleHttp\Psr7\Stream)#255 (7) {
  ["stream":"GuzzleHttp\Psr7\Stream":private]=>
  resource(259) of type (stream)
  ["size":"GuzzleHttp\Psr7\Stream":private]=>
  NULL
  ["seekable":"GuzzleHttp\Psr7\Stream":private]=>
  bool(true)
  ["readable":"GuzzleHttp\Psr7\Stream":private]=>
  bool(true)
  ["writable":"GuzzleHttp\Psr7\Stream":private]=>
  bool(true)
  ["uri":"GuzzleHttp\Psr7\Stream":private]=>
  string(10) "php://temp"
  ["customMetadata":"GuzzleHttp\Psr7\Stream":private]=>
  array(0) {
  }
}
```

Any thoughts on how I can pull the content from the guzzle request correctly into the Timber context? Ideally, it would also involve converting the JSON data to an array that can be looped through in Twig.

**Comment by marciojc** [comment]
Did you try `json_decode($response->getBody(), true);` ?

**Comment by timknight** [comment]
Ah perfect, that's exactly what I needed to do.  Thanks @marciojc!
