### ISSUE TITLE
Timber 1.5, PHP 7, Twig 1 errors

### ISSUE THREAD

**Issue by jasperrooduijn** [timber/timber#1579]
I keep getting this error when using php71 and Timber. On composer update Twig updates from version 1 to version > 2. Since then i've been getting this error. I found this issue which seems to fix the problem https://github.com/timber/timber/issues/1299. I updated to the latest version of Timber. But the error is still there. The only thing that helps for now is forcing composer to install version 1 of Twig. Any solutions? Or should i just stick with Twig 1 until this is merged into a release?

`Fatal error: Uncaught TypeError: Argument 1 passed to Twig_Filter::__construct() must be of the type string, array given`

**Comment by mralessio** [comment]
I've also ran into the same issue. Then I found that a filter in Twig 2 should be added in a different way.
Try this:
```php 
$twig->addFilter( new Twig_Filter( 'myfoo', array( $this, 'myfoo' ) ) );
```
instead of (taken from timber/starter-theme):
```php 
$twig->addFilter( 'myfoo', new Twig_SimpleFilter( 'myfoo', array( $this, 'myfoo' ) ) );
```

**Comment by jasperrooduijn** [comment]
Great! That worked. Thanks.
