### ISSUE TITLE
post.date|date or post.post_date|date?

### ISSUE THREAD

**Issue by waltercruz** [timber/timber#1584]
Is this a support or usage question? Please post to [StackOverflow](http://stackoverflow.com/questions/tagged/timber) using the Timber tag

### Expected behavior

when I format a date with |date, I get a incorrect value (today)

### Actual behavior

I have a post from march 28. When I try to format the date with |date, it gets incorrect. But it's correct if I use post.post_date. So, maybe I should use post.post_date|date and not post.date|format|

### Steps to reproduce behavior

post date on database: 2017-03-28 13:58:46

trying to format:

{{post.date}}

return 28 de março de 2017 (correct).

{{post.date | date("d \\d\\e F")}} returns 23 de outubro, which is today date, on pt_BR (incorrect)

{{post.post_date | date("d \\d\\e F")}} returns 28 de março, which is correct.

### What version of WordPress, PHP and Timber are you using?
Wordpress: 4.8.2
PHP: 7.1
Timber: 1.5.2

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Upgraded to newest version via plugin updater in WordPress dashboard

**Comment by jarednova** [comment]
Hi @waltercruz you should be able to do....

`{{ post.date("d \d\e F") }}`

... and have it return what you're looking for. Give it a shot and let me know!

**Comment by waltercruz** [comment]
Ouch! Awesome. So simple!

Will test id today.

**Comment by waltercruz** [comment]
Maybe is good to suggest using the function instead of filter [here](https://timber.github.io/docs/reference/timber-post/#date)?

**Comment by jarednova** [comment]
@waltercruz — yep, good call. I'll update those in the next few days. Assigning to myself to remember

**Comment by jarednova** [comment]
docs are now up-to-date; thanks again for the question + suggestion @waltercruz 

![screen shot 2017-10-25 at 6 36 03 pm](https://user-images.githubusercontent.com/1298086/32026689-67b4d9fe-b9b3-11e7-87cb-9eca4741de82.png)
