### ISSUE TITLE
Timber\ImageHelper::process_delete_generated_files causing timeouts when adding files to Media Library

### ISSUE THREAD

**Issue by webinista** [timber/timber#1588]
When trying to upload files to the Media Library, I get HTTP 502 errors. I'm using WPEngine, and the 502 errors appear to be caused by a long-running script (but only on installations that are tagged as "Production" environments; I've raised that issue with WPEngine).

According to WPEngine's support team, the problem is caused by `Timber\ImageHelper::process_delete_generated_files` running for an absurd number of milliseconds. A screenshot of the stack trace follows.

![whatsgoingwrong](https://user-images.githubusercontent.com/354277/32195886-fe761a6c-bd7b-11e7-9d9b-7ba661fd355b.png)

This happens even when Timber is the only plugin enabled and the active theme is a bundled WordPress theme (twentyseventeen). 

**EDITED TO ADD:** This may be similar to #1559. I've scanned our custom code for `add_filter('add_attachment'`. Disabling that function did not fix the problem, however.

### Expected behavior

Expected to be able to upload files to the Media Library without errors.

### Actual behavior

The upload script hits the server's `max_execution_time` limit of 60 seconds, and `/wp-admin/async-upload.php` returns a 502 error. 

### Steps to reproduce behavior

1. Use a "production" install of WPEngine (I realize the logistical hurdles of doing so. Including this as a step in case others have experienced this problem and have some advice)
2. Install and enable Timber, and use a default WordPress theme.
3. Upload images to the media library.

### What version of WordPress, PHP and Timber are you using?

- WordPress 4.8.2
- PHP 7.0 
- Timber 1.5.2

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Initial install of 1.4.1 was via WordPress.org and the WordPress Dashboard. For the upgrade to 1.5.2, I downloaded the files and used Git to push them to the server.

**Comment by jarednova** [comment]
Yikes, thank you for the report @webinista! Definitely will look into this. I have a WP Engine contact who I can talk to about setting up a test install

**Comment by webinista** [comment]
Thank you! 

To offer some additional information: smaller files -- under 50KB seem to upload fine. However, we use a lot of large images -- large dimensions and larger file sizes. Uploading those files fails pretty consistently. If you have any ideas about what else to look for, I'd appreciate the suggestion.

**Comment by jarednova** [comment]
@webinista — can you post a link to an image that fails? I just want to make sure I test with as much the same as possible

**Comment by webinista** [comment]
Sure. Here's one: https://webinistadev.com/gfy/california-poppies.jpg. It doesn't upload every time.

**Comment by webinista** [comment]
Have heard from WPEngine regarding this, and I think this may be a case of us running low on disk space (and not fully understanding how LargeFS works). I'm going to fix that problem first. If that resolves things, I'll close this issue.

**Comment by webinista** [comment]
Yep. This was 100% on our end. We had too many files stored on disk.

**Comment by jarednova** [comment]
@webinista drats! Glad to hear you got it solved
