### ISSUE TITLE
fn(is_admin_bar_showing) returns error 

### ISSUE THREAD

**Issue by michaelmano** [timber/timber#1589]
### Expected behavior
expected truthy falsy.

### Actual behavior
```
Warning: call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /wp-content/plugins/timber-library/lib/Twig.php on line 310
```
### Steps to reproduce behavior
```
{{ fn(is_admin_bar_showing) }}
```
or if you do an if statement you get nothing.
```
{% if fn(is_admin_bar_showing) %}

{% endif %}
```
### What version of WordPress, PHP and Timber are you using?
Wordpress: Version 4.8.2
Timber: Version 1.5.2
PHP: 7.1.8

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer/Packagist

**Comment by jarednova** [comment]
so close! just needs to be a string @michaelmano:

```
{{ fn('is_admin_bar_showing') }}
```

**Comment by michaelmano** [comment]
Ahhhhhhh damn! so sorry, cheers for the reply.
