### ISSUE TITLE
Retrieve attachments while using SearchWP

### ISSUE THREAD

**Issue by angtheod** [timber/timber#1590]
### Expected behavior
Expect to see get_posts return value to include posts of post_type attachment.

### Actual behavior
If I pass an array with options to the get_posts() function then it does not include attachments. It does include them only without passing any argument at all.

### Steps to reproduce behavior
```
$context['posts'] = Timber::get_posts( [

  's' => $search,
  'post_type' => [
    'post',
    'page',
    'attachment',
  ],
  'post_status' => 'any',
  'orderby' => 'post_date',
  'order' => 'DESC',
] );
```

### What version of WordPress, PHP and Timber are you using?
WordPress 4.8.3, PHP 7.1.10, Timber 1.5.0

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by angtheod** [comment]
Well, I apologize this does not have to do with Timber solely but when working together with the SearchWP plugin.

The issue seems like it is related with Timber and SearchWP not collaborating very well here. After investigating this with @tcrsavage he found that when we provide parameter to Timber::get_posts() (e.g. to sort results by date) then since Timber does **not** use the main WP_Query, SearchWP is not aware of that and this results to not search within Attachments (PDFs, ..).

For anyone interested a solution is to proceed without passing query options to get_posts at all
  and instead use the `edit_searchwp_query_orderby` of searchwp to edit the order by part of the main WP_Query directly.

**Comment by palmiak** [comment]
Hi Some time ago I wrote a small plugin for Ajax Load More and SearchWP. From what I remember the safest method to make SWP working with anything is to:
- make a Query using https://searchwp.com/docs/swp_query/ (set fields to ID)
- pass the IDs to WP_query using `post__in` parameter.

It's not the best way (2 queries) but it's the safest and should always work

**Comment by angtheod** [comment]
@palmiak Hey there,
thank you for the insight and for your plugin.

I was just looking into that! I have to make some more complex queries now so that I can filter results and I believe this was you suggest will come in handy.

**Comment by palmiak** [comment]
@angtheod can we mark this issue as solved and close it?
