### ISSUE TITLE
How set timer cache ignore all get params from URL

### ISSUE THREAD

**Issue by jakubkaderavek** [timber/timber#1592]
Hi,

I use Timber on middle size website. There are many URL generate with get params - utm, google adwords, atd.
Is there a way, how exclude all pages from creating new timber cache (with transient) and serve cache from page without this param(s).

My code is:
Timber::render( array( 'template-home.twig' ), $context, 600 );

Eg. 
for URL example.com?utm_source=example.com serve Timber cache from this page: example.com

It would be very nice if I can set for which params create custom cache, but its not important for me.

Thanks for help

**Comment by nlemoine** [comment]
Page cache should preferably handled by a cache plugin.
