### ISSUE TITLE
Timber Menu : small Incompatibility with Polylang

### ISSUE THREAD

**Issue by maximebj** [timber/timber#1593]
Hello

I noticed than there is a small issue with the Timber\Menu Class when using Polylang. 
It can be a problem as more and more people prefer Polylang instead of WPML.

Getting a menu from a location doesn't work anymore. And after digging in the code I found than this code makes the problem :  (Menu.php L128)

`
if ( function_exists('wpml_object_id_filter') ) {
  $menu_id = wpml_object_id_filter($locations[$slug], 'nav_menu');
}
`

It's because Poylang also create function wpml_object_id_filter to convert it to its internal equivalent. But it's always returning the first menu found. 

Commenting the "if" statement make it work again (Polylang achieves somehow to make the relation between languages without further code). 

You may tell me than the issue is mostly due to Polylang and you may be right, but I prefered tell you about this issue. 
Maybe the solution is to test `function_exists('wpml_object_id_filter')` and not polylang activated. 

--

I'm using Timber since a while and you guys made a fantastic work ! Hope I'll talk about it in newt WordCamp, in France.

**Comment by maximebj** [comment]
After further investigations I think only Polylang is responsible for the bug : 
I tried elsewhere with an old Timber version and by updating Polylang and the bug is there. 

I think it's the way they handle wpml_object_id_filter function

**Comment by maximebj** [comment]
Just to let you know : I've reached the polylang team and they are aware of the issue. Will be fixed in nexte release ;)

**Comment by jarednova** [comment]
@maximebj thanks for taking that on! Glad to hear they can take care of it. Good luck at WC France, that's awesome to hear!
