### ISSUE TITLE
Menu slug error when Using Woocommerce

### ISSUE THREAD

**Issue by mariosmaselli** [timber/timber#1595]
### Expected behavior
$context['menu'] = new TimberMenu('main');

```
{%  for el in menu.get_items %}
    {{el.slug}} // This doesn't work / breaks the site
    {{el.post_name}} // This returns IDs
    {{el.title}} // This works
 {% endfor %}
```

### Actual behavior
Get a bunch of errors in different files. (Tmber and Woocommerce)
Timber // /plugins/timber-library/lib/Twig.php(43): call_user_func_array('do

### What version of WordPress, PHP and Timber are you using?
WP: 4.8.3
Timber: 1.5.2
Woocommerce: 3.2.3

**Comment by Levdbas** [comment]
Closing since this is quite an old issue. Let us know if this issue still persists by opening in a new issue.
