### ISSUE TITLE
Grouping Output Based on an ACF Field

### ISSUE THREAD

**Issue by timknight** [timber/timber#1602]
# Grouping Output Based on an ACF Field

I've seen others bring up similar questions, but it hasn't been clear to me how to best solve this. Most of what I've seen though is really about using Twig's `batch` filter to group fields or to change how associate items within the post group can be accessed. What I'm really after is more of a categorized list.

What I'm hoping to accomplish is a list of all of the items within a Custom Post Type grouped by an ACF field called "state" for their location that's in alphabetical order. So the results would be like:

```html
<h1>Arizona</h1>
<ul>
  <li><a href="{{ post.link }}">Location 1</a></li>
  <li><a href="{{ post.link }}">Location 2</a></li>
</ul>

<h1>Arkansas</h1>
<ul>
  <li><a href="{{ post.link }}">Location 3</a></li>
  <li><a href="{{ post.link }}">Location 4</a></li>
</ul>
```

I know that Upstatement also works on Craft sites in addition to WordPress work, so essentially what I'm hoping to get to is like Craft's Twig `group` filter, but using Timber.

```twig
{% set locations = craft.entries.section('locations').find() %}
{% set locationsByState = locations|group('state') %}

{% for state, entriesInLocation in locationsByState %}
	<h2>{{ state }}</h2>
	<ul>
		{% for entry in entriesInLocation %}
			<li><a href="{{ entry.url }}">{{ entry.title }}</a></li>
		{% endfor %}
	</ul>
{% endfor %}
```

Any thoughts on the best approach to pull this off?

**Comment by timknight** [comment]
I wanted to add too that my query for the data is already using the modified groupby like so:

```php
function  query_group_by_filter($groupby){
    global $wpdb;
    return $wpdb->postmeta . '.meta_key = "state"';
}

add_filter('posts_groupby', 'query_group_by_filter');
$communities = array(
    'numberposts'    =>   -1,
    'post_type'      =>   'community',
    'post_status'    =>   'publish',
    'meta_key'       =>   'state',
    'orderby'        =>   array(
        'meta_value' =>   'ASC',
        'title'      =>   'ASC'
    ),
);
remove_filter('posts_groupby', 'query_group_by_filter');
```
For the most part I'm really just trying to tackle how to output this in Timber within the template.

**Comment by palmiak** [comment]
@timknight I think that this not a job for Timber/Twig (because Twig is a templating engine so it's not a place for some more complicated logic).

I would do a query that would got me all the posts and than would go post by post and add to array like `$array[get_field('state')] = $post`.

Having this array than you can do a for (states) and inside another for (posts).

**Comment by jarednova** [comment]
I'd agree with @palmiak here. There could be some Twig/Timber acrobatic to make this _possible_ but the real spot to take care of this is PHP. I recommend making classes for your CPTs so you can do something like..

```php
<?php

# lib/MyCommunity.php

class MyCommunity extends Timber\Post {

    function states() {
        $states = get_field('states');
        //do your sorting magic here to properly sort and group
        return $states;
    }
}
```

You'll need to load this in `functions.php`

```php

# functions.php

require_once('lib/MyCommunity.php');
```

... and make sure your `single.php` (or other file) is using it:

```php
#single.php

$context['post'] = new MyPostType();
```

I realize that it might seem like a lot, but it allows you to keep very clean Twig templates optimized for readability:

```twig
{% for state in community.states %}
  	<h2>{{ state.name }}</h2>
	<ul>
		{% for entry in state.locations %}
			<li><a href="{{ entry.url }}">{{ entry.title }}</a></li>
		{% endfor %}
	</ul>
{% endfor %}

**Comment by timknight** [comment]
Oh, of course not, I wasn't thinking about doing this in Twig. I think when I was looking at this a year ago it was just trying to determine if there was a "Timber Way" of approaching this in terms of providing the grouped query into the context. Extending `Timber\Post` seems like a great idea. That makes complete sense. Thank you for the clarity and examples on this @jarednova!
