### ISSUE TITLE
PostPreview needs a way to filter content (based on semantic tagging)

### ISSUE THREAD

**Issue by tomas-eklund** [timber/timber#1604]
The `Timber\PostPreview` class is too limited in functionality to be useful in real world scenarios. We need more powerful methods to instruct `PostPreview` what information to extract and what to discard.

### Expected behavior
PostPreview should return a _sensible_ excerpt of the content of a page. This should not include sidebars, navigation etc. which is often embedded in the content when page builders such as Elementor are used. 

Even though it might be considered bad practice to embed navigation and sidebars in page content, I'm only using that as a simple example. More reasonable examples might include "widgets" included on pages (boxed images with captions, news feeds, calendars etc.) which should be excluded when a text-only excerpt is extracted.

The PostPreview class has a protected property called `$destroy_tags` which by default is set to:

`protected $destroy_tags = array('script', 'style')`

I get the desired behavior (for my particular use case) if this is changed to:

`protected $destroy_tags = array('script', 'style', 'nav', 'aside')`

This will strip any `<nav>` and `<aside>` containers completely, leaving only actual, context-meaningful content.

However, I can't seem to accomplish this without hacking the `PostPreview` class itself. There is no public method to manipulate the `$destroy_tags` property or otherwise specify what content to discard and what to keep.

### Actual behavior
Using the Timber Starter Theme and Elementor page builder plugin for editing content I've marked up content-embedded navigation elements with `<nav>` and sidebars with `<aside>` while the actual, meaningful content is wrapped in `<article>` tags. 

The `PostPreview` object is used to present an excerpt of each hit on the search result page and the result is a massive mess of seemingly random text including words from navigational elements, widgets and sidebar content.

Assuming the following pseudo code 
```
<nav>
    <h3>Sub navigation</h3>
    <ul>
        <li>Homepage</li>
        <li>Products</li>
        <li>Contact</li>
    </ul>
</nav>
<article>
    <h1>Interesting article</h1>
    <p>The text that we want to display on search result pages etc.</p>
</article>
<aside>
    <div class="widget">
        <h2>Widget header</h2>
        <div>Widget content</div>
    </div>
</aside>
```

Calling `{{ post.preview() }}` in a template will usually result in something like this:

> Sub navigation Homepage Products Contact Interesting article The text that we want to display on search result pages etc. Widget header Widget content.

### Proposal
I would appreciate being able to use like something like this to produce:

`{{ post.preview().discard('nav aside') }}` 

> Interesting article The text that we want to display on search result pages etc. 

Or even better

`{{ post.preview().keep('article').discard('h1') }}` 

> The text that we want to display on search result pages etc. 

Here we first discard everything outside of `<article>` tags, keeping only content within. Then we discard `<h1>` tags within those containers as the headings are often redundant on the search result page.

### Discussion
Of course, I'm open to a discussion on how this kind of functionality would best be implemented. My proposal is only a suggestion. It would certainly solve my use case, but perhaps not all.

### What version of WordPress, PHP and Timber are you using?

WordPress: 4.9.1
Timber: 1.5.2

### How did you install Timber? 

WP.org

**Comment by Levdbas** [comment]
I think this is out of scope for Timber. 
Let me know if you think otherwise.

**Comment by tomas-eklund** [comment]
Wow, I had completely forgotten this feature request from 5½ years ago. I'm actually rather impressed of how well formulated the request is, and how sensible it sounds. It's regreattable that you are discarding it as not planned, seing as I believe it would be rather easy to implement such a useful feature. 

However, I can also see your need for cleaning up your issue tracker. Noone else seemed to care and I'm not using Timber anymore, so apparently it's not a big loss.
