### ISSUE TITLE
WooCommere variable or grouped product display sample? 

### ISSUE THREAD

**Issue by stromi** [timber/timber#1605]
Does anyone has a sample code/gist for recreating all WooCommerce functions and behavior for Timber? 

### Expected behavior
I would like to show variations of a product on `single-product.twig`, but I can't make it work.  

### Actual behavior
Dumping the current product (post) does show some attributes at `_custom`, but this just won't be enough I think :) 

### What version of WordPress, PHP and Timber are you using?
WP: 4.8, PHP: 7.1.1,  Timber: 1.5 (integrated into the theme)

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer --> integrated into the theme (everything else works just fine)

**Comment by aureliendebord** [comment]
Hello @jake46a , any news about your guide? I am struggeling to work with variations product : like display only the price of the current variations or display the product gallery.

**Comment by jarednova** [comment]
@aureliendebord here's his guide:

https://github.com/timber/timber/pull/1747

Could you take a spin and see if this helps to answer your Qs? It'd be great to get a second set of eyes on what he's written (I'm not a WC user, so I'm not much help) before we merge it in

**Comment by Levdbas** [comment]
Closing this as stale. If you want to expand the Woocommerce documentation, please open a PR.
