### ISSUE TITLE
How do I render a twig file into a variable?

### ISSUE THREAD

**Issue by sgu1** [timber/timber#1608]
Something that's similar to render string.
$twigTemplate = Timber::render('myTwig', ['hi', 'hi']);

**Comment by sgu1** [comment]
Never mind I figured it out. You can simply use output buffering.
Like this:
ob_start();
Timber::render('myTwig', ['hi', 'hi']);
$template = ob_get_contents();

**Comment by gchtr** [comment]
Hey @sgu1 

You’re probably looking for [Timber::compile()](https://timber.github.io/docs/reference/timber/#compile). Instead of using `ob_start()` and `ob_get_contents()`, you could use:

```php
$compiled = Timber::compile( 'my_twig_file.twig', [ 'hi' => 'hello' ] );
```

**Comment by sgu1** [comment]
Thanks, Timber::compile() was exactly what I was looking for.
