### ISSUE TITLE
[Improvement?] Set custom class to be used instead of TimberTerm

### ISSUE THREAD

**Issue by Kwapi** [timber/timber#1630]
We can override the Timber\PostClassMap to provide our own mapping between the custom classes and post types. Is there a similar thing for Timber\Term? I want to be able to specify my own custom class to be used instead of Timber\Term. I know I can provide it as a third argument to for example `get_term()` function but I'd like to be able to set it only once.

Cheers!

**Comment by oxyc** [comment]
I'd like to extend this request for all timber classes :) I extend Timber\Image for example and it's a hassle with all the hardcoded class names everywhere.

**Comment by gchtr** [comment]
I agree. We could add additional filters for this.

**Comment by oxyc** [comment]
For reference there are some related issues to this:
- https://github.com/timber/timber/pull/659
- https://github.com/timber/timber/pull/1232

**Comment by gchtr** [comment]
Related/Duplicate: #1399

**Comment by acobster** [comment]
Docs for Class Maps, which solve this problem flexibly and generically in 2.x: https://github.com/timber/timber/blob/2.x-factories/docs/guides/class-maps.md
