### ISSUE TITLE
Twig_Function will be final in Twig 3.0

### ISSUE THREAD

**Issue by StuartFeldt** [timber/timber#1632]
I am getting this notice whenever calling Timber::render

> Overriding Twig_Function is deprecated since version 2.4.0 and the class will be final in 3.0.

\Timber\Twig_Function extends \Twig_Function, which will be final in 3.0 of Twig.

### What version of WordPress, PHP and Timber are you using?
PHP 7.0.25, Timber 1.6.0, WordPress 4.9.1

**Comment by nlemoine** [comment]
I adressed this issue in the PR mentioned above. You can still grab my fork if you want to fix it ASAP.

**Comment by StuartFeldt** [comment]
Awesome, thanks!

**Comment by 7php** [comment]
I get this error too.
`PHP 7.0.x, Timber 1.6.0, WordPress 4.9.3`

Will this merge be in the next release of Timber 1.6.x ?

**Comment by jarednova** [comment]
@7php; yep! prepping a release for this week

**Comment by 7php** [comment]
Awesome thanks @jarednova
