### ISSUE TITLE
Polylang function pll_the_languages()

### ISSUE THREAD

**Issue by theamnesic** [timber/timber#1640]
Hi!

### Expected behavior
Show the language switcher with the `pll_the_languages()` [function](https://polylang.wordpress.com/documentation/documentation-for-developers/functions-reference/#pll_the_languages).

### Actual behavior
`{{ fn('pll_the_languages') }}` return the language switcher twice.

### Steps to reproduce behavior
Install Polylang and Timber plugins, and add `{{ fn('pll_the_languages') }}` in your template.

### What version of WordPress, PHP and Timber are you using?
WordPress 4.9.2, Timber 1.6.0 and Polylang Pro 2.2.8

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WordPress.org version 

Any idea?
Thanks!

**Comment by gchtr** [comment]
What if you set `echo` to `false`?

```twig
{{ fn('pll_the_languages', {
    echo: 0
}) }}
```

Or try it with [Twig’s `do`](https://twig.symfony.com/doc/2.x/tags/do.html)?

```twig
{% do fn('pll_the_languages') %}
```

**Comment by theamnesic** [comment]
Both work!

Thank you @gchtr.
