### ISSUE TITLE
Wordpress SEO plugin (Yoast and SEO Framework) create a conflict with Timber plugin

### ISSUE THREAD

**Issue by filnug** [timber/timber#1643]
I'm using the Timber plugin with Underscores.me template (https://github.com/timber/starter-theme) to create a website (manual install).

I used the Yoast and SEO Framework plugin and both create an issue! When I add a description in the meta of a page, Timber doesn't work anymore. There is no error message. But content is empty.

I have: 
WordPress 4.9.2 
Timber Version 1.6.0 
The SEO Framework Version 3.0.3

Do you have an idea why?

**Comment by palmiak** [comment]
Are you using any other plugins?

Is this problem exist on pages or on every post type?

Could you provide us with your theme (I suspect you have made some changes).

**Comment by filnug** [comment]
I'm not using post type, but only pages. And I noticed this problem only on pages. 

I'm actually using this starter theme : https://github.com/timber/starter-theme

Maybe should I look in this direction

**Comment by palmiak** [comment]
Is this still an issue?

**Comment by filnug** [comment]
Yes. It is.
I really haven’t found the source of the bug :-/

Since then, I left it behind me. It is frustrating for me, but I might close the issue.

Thank you anyway for asking me!

Filippo

**Comment by jarednova** [comment]
@filnug it appears that this issue has to do with `$post` being used by Yoast in ways not visible to Timber. As discussed in this thread ...

https://github.com/timber/starter-theme/issues/78

... try renaming your PHP vars from `$post` to `$timber_post` so the two don't conflict
