### ISSUE TITLE
Lazy loading of custom fields

### ISSUE THREAD

**Issue by pieterbeulque** [timber/timber#1647]
Hi, I noticed that removing the `custom` property on `Timber\Post` was on your roadmap for 2.0.

At [my agency](https://github.com/mrhenry), we have built a nice _lazy loading_ approach for the ACF support, avoiding the usage of `get_fields` (which is expensive and considered bad practice). This means that only the custom fields that are actually used in your Twig templates are fetched from the database & formatted.

Would you be open for a PR for this?

**Comment by gchtr** [comment]
Hey @pieterbeulque 

There will be changes to how Timber handles custom field data. [Here’s the answer](https://github.com/timber/timber/pull/1618#issuecomment-354627351) that you might be interested in. In short:

- We won’t remove the `custom` property.
- The `get_field()` method will probably be deprecated. Instead, the `meta()` method should be used.

There will be three different ways for getting custom values:

- `{{ post.my_field }}` Filtered by ACF.
- `{{ post.custom.my_field }}` Unfiltered value, straight from the postmeta table.
- `{{ post.meta('my_field') }}` Filtered by ACF, no conflicts when a custom field might have the same name as a method on `Timber\Post`.

Now to your lazy loading approach. That sounds very interesting! A pull request for a technique that improves performance is always welcome.  
I guess your technique is very specific to ACF? In that case, I think it would be good if it could live in the [`Integrations` namespace](https://github.com/timber/timber/tree/master/lib/Integrations). We try to decouple functionality related to third-party plugins from Timber’s core (That’s also the reason why we’d like to deprecate the `get_fields()` method).

**Comment by pieterbeulque** [comment]
Thank you! That clears some things up 🙂 

The lazy loading pattern we have developed is not exactly tied to ACF but our current implementation is, yes. I'll try to find some time to play around with the ACF class inside the `Integrations` namespace.

What's the current timeline on 2.0, if any? It might be worth it to wait & see how the deprecation of `get_field()` works out for us and if the added complexity of our changes is still needed.

**Comment by gchtr** [comment]
In general, Timber 2.0 loads custom fields only when requested, see https://timber.github.io/docs/v2/guides/custom-fields/#performance.

If somebody still wants to share their custom lazy-loading solution, please feel free to do so in the [Show and tell](https://github.com/timber/timber/discussions/categories/show-and-tell) section in discussions.
