### ISSUE TITLE
Problem with letterbox

### ISSUE THREAD

**Issue by rumpelsepp** [timber/timber#165]
Hi,
it seems that the problem in #156 is already there. I have my Wordpress setup in `~/public_html/wordpress` and the letterbox does not generate any links or images. The `resize` filter works as expected.

How can I help you with this problem? What variables etc. should I dump?

**Comment by lmartins** [comment]
Im having this problem on a new site with the latest version of Timber. @jarednova Did you get to any conclusion about this?

**Comment by connorjburton** [comment]
Have re-opened this for investigation @lmartins

**Comment by lmartins** [comment]
What can I do to help figure it out?

**Comment by connorjburton** [comment]
I don't know anything about this issue so a guide to replicate the issue and what you expect to happen would be good :) (I know this may already be somewhere, just helps to have fresh info)

We are in the middle of a big transition at the moment so I may be slightly delayed investigating but it's on the list so I will get round to it.

:+1:

**Comment by lmartins** [comment]
Thanks for the feedback. The problem and what was expected is quite easy to explain. WordPress seems to able to generate all other images except those that are declared using `letterbox`. Those never show up in the file structure. 

This happens on Rackspace Cloud Sites hosting account. I wonder if that image transformation needs any particular PHP library enabled in order to work properly?

**Comment by connorjburton** [comment]
Hmm, looks like the letterbox feature is a wrapper around wordpress' media library, that uses GD or Imagick - could you check if the server has those libraries? Or even could you check that you can edit images via the wordpress admin correctly?

**Comment by lmartins** [comment]
Yes, I can crop images in the editor without any apparent problem.

**Comment by jarednova** [comment]
Closing for now, a lot w Images have been re-written since this was opened. If anyone sees issues please file a new ticket with a ref to this one
