### ISSUE TITLE
AFC repeater values from custom post type returned as a number not text

### ISSUE THREAD

**Issue by JakeHenshall** [timber/timber#1652]
Is this a support or usage question? Please post to [StackOverflow](http://stackoverflow.com/questions/tagged/timber) using the Timber tag

### Expected behavior

To see the list of text from the repeaters and not how many items are in the repeater.

### Actual behavior

Just shows the total number of items in the repeater, it does display the title which is good.

### Steps to reproduce behavior

https://gist.github.com/JakeHenshall/32f583b03a0df0de2ad324068e2bb8b9

### What version of WordPress, PHP and Timber are you using?

WordPress 4.9.2, PHP 7.1.8, Timber 1.6.0 

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Via Composer/Packagist

**Comment by gchtr** [comment]
Did you initialize Timber in **functions.php**?

```php
new Timber\Timber();
```

If you don’t initialize Timber, it will not register the proper filters for ACF and load the value directly from the database and you won’t have any values in your repeater field.

Related issues: #1351, #1527

**Comment by JakeHenshall** [comment]
@gchtr Yes I have added new Timber\Timber(); to my functions.php file.

Do I need to loop through the repeater to display the text / type fields. If I var_dump($context['changelog']); it has all of the correct text that I need.

I can add my functions.php file to the gist.

Thanks Jake.

**Comment by chrisgherbert** [comment]
I have run into this many times. How are you defining the ACF fields - through the GUI or using PHP?  Are you reusing a meta key for the ACF field that was used for something else previously?

**Comment by JakeHenshall** [comment]
@chrisgherbert I'm just using the plugin to create the fields, if i var dump they are all there.

**Comment by chrisgherbert** [comment]
@JakeHenshall Have you used the meta keys ('type' or 'changes') for any other custom fields?

**Comment by JakeHenshall** [comment]
@chrisgherbert No there is only 2 ACF (Changelog -> Type / Changes) & (Documentation)

**Comment by chrisgherbert** [comment]
@JakeHenshall What do you get when you search the post meta table for all instances of those keys?  `SELECT * FROM wp_postmeta WHERE meta_key = 'type'` and `SELECT * FROM wp_postmeta WHERE meta_key = 'changes'`

Are they all items that are using the ACF fields that you've set up, or is there some other thing using those keys as well?

**Comment by JakeHenshall** [comment]
The database seems to be saving the value twice not sure why it is doing this though?!

**Comment by ErikFontanel** [comment]
@JakeHenshall it's been a while but… 

Assuming you're `$context['changelog']` query contains posts, the `change` variable in your twig template contains each individual post, right? So `change.changes` is an array containing your repeater field values. You need to call `change.get_field('changes')` to retrieve the repeater. Then you can loop over the `changes` in your twig template.

```
{% for change in changelog %}
    <h1>{{ change.title }}</h1>
    {{ change.type }}

    {% for repeater_field· in change.get_field('changes') %}
      {{ repeater_field.value1 }}
      {{ repeater_field.value2 }}
      {{ repeater_field.value3 }}
    {% endfor %}
{% endfor %}
```

**Comment by Levdbas** [comment]
Issue is from a while ago. The solution provided should provide a fix for this. If you still run into this issue, please open a new ticket with a code example.
