### ISSUE TITLE
PostGetter::get_post_class unnecessarily instantiates return PostClass

### ISSUE THREAD

**Issue by StuartFeldt** [timber/timber#1660]
### Expected behavior
I expect the class wrapper for the returned post class in Timber::get_post to only be instantiated once.

### Actual behavior
The class wrapper is instantiated twice.

### Steps to reproduce behavior
Create a class wrapper which extends TimberPost, the constructor will be called twice.

### What version of WordPress, PHP and Timber are you using?
WordPress 4.9.4, PHP PHP 7.0.27, Timber 1.7.0

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by jarednova** [comment]
Closed by #1663 and #1661
