### ISSUE TITLE
Consider CDN-based images as internal in resize method

### ISSUE THREAD

**Issue by toddholmberg** [timber/timber#1664]
I am using Timber with the WPRocket caching plugin.  I set WPRocket to rewrite all post image URLs to use a CDN CNAME. Timber's ImageHelper::resize method uses this CDN URL in determining whether or not the image is internal (resize the existing local image) or external (sideload and save a new resized version with a hashed filename).

I need Timber to resize the local image file rather than sideload a duplicate, and then the CDN will pick it up from this local origin. Is this possible? I have tried to override the URLHelper/is_external_content method at the root of the ImageHelper/resize() method, but this did not seem to work:

```
add_filter('timber/URLHelper/is_external_content', 'foo_is_external_content', 10, 1);

function foo_is_external_content($url) {
    // I use a more complex logic
    return false;
}
```

**Comment by Levdbas** [comment]
Closing this as stale.
