### ISSUE TITLE
LocationManager.php is_dir() with false parameters

### ISSUE THREAD

**Issue by Sirlefou1** [timber/timber#1667]
On line 114 and 136 of LocationManager.php

If realpath() return false is_dir(false) make a warning adding a test on $caller_sub or $tloc before is_dir()
if ( is_dir($tloc) ) >> if ($tloc && is_dir($tloc) )
if ( is_dir($caller_sub) ) >> if ($caller_sub && is_dir($caller_sub) )

**Comment by Levdbas** [comment]
Issue is stale, if you still run in to this issue let us know!
