### ISSUE TITLE
Interaction with Gravity Forms causing jQuery to switch positions

### ISSUE THREAD

**Issue by Soben** [timber/timber#1668]
Is this a support or usage question? Please post to [StackOverflow](http://stackoverflow.com/questions/tagged/timber) using the Timber tag

### Expected behavior
jQuery should remain in header, regardless of interactions.

### Actual behavior
With Gravity Forms enabled. If you have a page in which there's a Gravity Forms widget in the sidebar, and a Gravity Forms form in the page/post content... the content's form will be set to display: none; and there are jQuery warnings on the page as the wp_enqueue_script for jQuery has been somehow switched to the footer instead of the header.

This problem does not exist if sidebar is switched to one without a widget, or if included themes such as twentysixteen is activated.

### Steps to reproduce behavior
Install gravity forms, set up a page in which the sidebar and post both have a form enabled.

Use `Timber::get_widgets( 'events-sidebar' );` in sidebar.php ... Issue happens upon call of that function, regardless if output in Twig files.

### What version of WordPress, PHP and Timber are you using?
Wordpress 4.9.4, PHP 7.2.1 and 5.6, Timber 1.7.0

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Wordpress Plugin.

**Comment by antonyjsmith** [comment]
I'm also experiencing some weird gravity form behaviours, if I include the gravity form widget in a sidebar say, the GF styles are dequeued from everywhere on the site. If I include the form as a shortcode directly in a template it's fine, ditto with the form via the block editor. It's really bizarre.

**Comment by Soben** [comment]
@antonyjsmith it's not a perfect solution, but I believe I found that you can disable the sidebar widget for Gravity Forms from including it's script, which resolved the issue. I believe it's in the "Advanced" area of the settings when managing the widget.

I don't have a current copy of WP set up anywhere that uses Timber and GF anymore, so I can't confirm, but could at least get you in the right direction.
