### ISSUE TITLE
Is it possible to grab custom fields (ACF) in a category taxonomy (namely a repeater field) via a Timber method?

### ISSUE THREAD

**Issue by adrianocr** [timber/timber#1669]
### Expected behavior
I have a repeater field that I assigned to every post category (standard posts, not custom post types). This repeater field lets you choose a post object that I want to use in a slider at the top of archive.php as "featured posts".

### Actual behavior
N/A, I need help because the docs don't seem to cover this (I think)

### Steps to reproduce behavior
Add repeater field to category taxonomy and then try to grab posts in archive.php from this repeater field.

### What version of WordPress, PHP and Timber are you using?
PHP 7.1, WordPress 4.9

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WP.org

**Comment by palmiak** [comment]
One way is to get the field in archive.php using `get_field` - https://www.advancedcustomfields.com/resources/adding-fields-taxonomy-term/ . Than pass the value to context and your're done. This will work for sure.

On the other hand I would try getting the Term object and than `{{ Term.get_field('name') }}` - this might not work, I would just go that way.
