### ISSUE TITLE
Problem with Fieldname-Prefix from Types Custom Fiels Plugin

### ISSUE THREAD

**Issue by motionVector** [timber/timber#169]
I’m trying to use Timber with the Custom Fields Plugin from http://wp-types.com/. 
Because the plugin prefixes all fieldnames with “wpcf-”, the dash causes a problem, when I want to output a field with TWIG. I know I could use the attribute function {{ attribute(page, 'wpcf-fieldname') }} , but I’d rather not have to use it all the time, because its so much more complicated. 
Is there a workaround for this problem, maybe with a subclass of TimberPost or adding an apply_filter that removes the prefix, when the meta info is loaded into TimberPost?

**Comment by xavivars** [comment]
Wouldn't be good to add this as an integration, similar to the one with ACF?

**Comment by connorjburton** [comment]
Hey everyone. Am I missing something here, can you not just do `{{ post['my-thing'] }}`?
