### ISSUE TITLE
How should I add a feature to TimberImage?

### ISSUE THREAD

**Issue by mgussekloo** [timber/timber#1690]
Is there a way to add Operations (e.g. Watermarking images) to TimberImage, other than modifying the core? I tried making a plugin, but Timber\ImageHelper has some important private methods that I can't hook into without duplicating a lot of code. Why are those methods private? Can they be made public? (Utility methods such as _get_file_url, _get_file_path, and the main _operate method).

Currently, I have solved my problem by modifying the core. I've added a Watermarking-operation to Timber, added a helper method to Timber\ImageHelper, and added the Twig filter to Timber\Twig. 

What would be the preferred way of making this less hacky?
- Make a pull request, to get this included in the core?
- Create a Wordpress plugin, but how can I add Operations to TimberImage in a regulated way?

Kind regards.

**Comment by jarednova** [comment]
Hi @mgussekloo good question! Better extension is something I want to figure out. I think the best way to proceed is to try and put watermarking in its own custom class for your project and then do a PR for the hooks/filters needed in core to make it work.

I imagine the same hooks you'd need for watermarking are the same others could use for various types of custom image manipulation

**Comment by mgussekloo** [comment]
This is a basic proposal, can probably be improved upon, but it would help me out a lot for a project I'm working on atm.

It allows me to register a custom operation through a filter, and to call said filter by catching non-existing methods on Timber\ImageHelper. I'm not sure if this would introduce non-desirable side effects, maybe someone with more skills could look at that.

These minimal additions in Timber\ImageHelper would enable me to call custom Operations.
https://gist.github.com/mgussekloo/54802a17b7788e851196b492a6db4d59

This is a plugin with the Watermark-operation to demonstrate the usage:
https://github.com/mgussekloo/Timber-Image-Watermark

In my template, I can simply use 
{{ post.get_field('acf_image') | watermark('company_logo.png') }}

Other (small) benefit: The existing Operations could be also rewritten as "plugins", and extensions could enhance the core functionality without much hassle.

**Comment by mgussekloo** [comment]
I created a plugin that adds a Twig filter for watermarking. It duplicates some code that's already in Timber, but I guess it's cleaner than extending Timber\ImageHelper. Maybe this is better than letting people extend Timber? In any case, my problem is solved, issue can be closed.

This is the plugin I made:
https://github.com/mgussekloo/timber-image-twig-watermark

**Comment by jarednova** [comment]
Thanks @mgussekloo for sharing. That looks like a great resource for others looking to do watermarking or other similar image manipulation
