### ISSUE TITLE
Bug: Cloned repeaters don't return arrays

### ISSUE THREAD

**Issue by benfurfie** [timber/timber#1692]
`get_field()` fails to return an array when you pass in a repeater called through a clone field type.

I have created a field group, which consists of a repeater and an image subfield. This is then saved as a hidden fieldgroup. I have then create a clone of that fieldgroup to pull it through to a field group specific to a template (in this case, front-page). It is in this clone field that I have entered the content.

### Expected behavior
When dumping the repeater, I expect to see an array of keyed arrays, which I can loop through using twig's `{% for %}` function.

### Actual behavior
The dump reveals that Timber is returning a field with the value of null. However, they fields are returned in the parent scope as `field_0_subfield` and so on.

![screen shot 2018-03-13 at 16 15 07](https://user-images.githubusercontent.com/10786699/37355115-18a21e04-26db-11e8-87e5-e14997893e03.png)

### Steps to reproduce behavior
I am using ACF Pro 5.6.8. Create a field group and within it, create a repeater and a single subfield within it. Set it to hidden and save.

Then create a new fieldgroup and create a clone field. Call in the field you created. Save it to a specific template (it doesn't matter which, as it seems to be template agnostic).

Create another field on the same template page and make it similar to the cloned group (i.e. a repeater with a single subfield).

Fill in the fields and save.

Then `{{ dump('post') }}`, `{{ post('post.get_field('cloned_field_name')' }}` and `{{ post('post.get_field('standalone_field_name')' }}`.

You should see that the field that was cloned returns as `fieldname_0_subfield`, `fieldname_1_subfield` etc, while the standadlone will return – correctly – as an array.

### What version of WordPress, PHP and Timber are you using?
* WordPress 4.4.2 _(I know)_
* PHP 7.0
* Timber 1.70
* ACF Pro 5.6.7

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
The website is based on Bedrock and installed Timber via wpackagist (so composer) and overrode it to be installed in the mu-plugins folder. Other than that, it's a standard approach to a bedrock install.

**Comment by 75th** [comment]
Same issue here, with a clone of a field group with a clone of a Flexible Content field.

**Comment by 75th** [comment]
@benfurfie Did you find a workaround for this? If it's even possible for me to use the fieldname_0_otherfieldname setup, it would be torture to do so.

**Comment by benfurfie** [comment]
@75th – I'm afraid not. I've run into the issue again. Going to try and figure out a work around.

**Comment by jarednova** [comment]
@benfurfie if you're able to figure things out, I'd love a PR — I definitely see how this can be frustrating and unexpected

**Comment by benfurfie** [comment]
The issue is with how Elliot's designed the clone feature.

From the docs:
> Values are not saved as an array, but are saved as normal individual field values. This means that meta queries are possible as per normal.

I'm looking now into ACF's code base to see if there's a way of adding an option that reverts clone field to return as arrays. If that's not possible, I'll ask Elliot, as he's pretty responsive.

**Comment by jarednova** [comment]
Sounds good, thanks @benfurfie !

**Comment by tedw** [comment]
FYI, if you enable “Prefix Field Names” when inserting a cloned field, ACF will return an array. You can then get the data with `get_field('field_name')['field_name']`.
