### ISSUE TITLE
How to handle Ajax requests with Timber ? 

### ISSUE THREAD

**Issue by DanDvoracek** [timber/timber#1696]
I'm facing an issue at the moment as I try to include some ajax filtering on my website. It's the first time I try Timber extensively, my apology if this sounds obvious.

I'm simply wondering where I can find some informations about how to handle Ajax requests using Timber with Wordpress. Or if it is in any documentation at all.

I basically do the same kind of implementation as here (using WP built-in ajax features):
http://www.geekpress.fr/tuto-ajax-wordpress-methode-simple/

PS: _Article is in french but should be self-explanatory with the code blocks_

I've been trying a few things already, but it seems I got something wrong. Not really sure what. Can somebody point me to an "official" Timber documentation or some useful resources? I have to say I haven't been very successful by googling about this.

Many thanks

**Comment by hbrok** [comment]
You can use the [compile](https://timber.github.io/docs/reference/timber/#compile) or [render](https://timber.github.io/docs/reference/timber/#render) functions in your ajax function.

Here is a quick rewrite of the `mon_action` function as an example:

```php
function mon_action() {

	$posts = Timber::get_posts( array(
	    'post_type' => 'post',
	    'posts_per_page' => 10
	) );

	Timber::render( 'partials/my-template.twig', array( 'posts' => $posts ) );

	die();
}
```

**Comment by DanDvoracek** [comment]
Nice, thanks!

**Comment by iamkevingreen** [comment]
@DanDvoracek This doesn't have to be timber specific, you can write a little bit of javascript using the wp-json api that's cooked directly into wordpress now. I wrote a lil [article](https://labs.redantler.com/load-more-for-wordpress-via-an-api-1757fa678471) a while back (I was also using timber in the article) if you want an example of doing it with some vanilla js

**Comment by DanDvoracek** [comment]
Thanks for sharing this article @iamkevingreen ! I'll have a look soon. 👍

**Comment by palmiak** [comment]
@DanDvoracek did @iamkevingreen solved your problem?
