### ISSUE TITLE
Render twig views from a plugin?

### ISSUE THREAD

**Issue by stefanlesik** [timber/timber#1697]
Is it possible to load twig views from a plugin. I can't seem to render these views in a theme. 

Timber::$dirname = '/wp-content/plugins/custom-plugin/templates';

Can anyone please show me how this might work please?

**Comment by StuartFeldt** [comment]
You can specify a path to a twig file when running the render function. For instance:

`Timber::render('path/to/your/template.twig', $context);`

**Comment by gchtr** [comment]
You can set additional [template locations](https://timber.github.io/docs/guides/template-locations/) where Twig should look for template files. I’d load the absolute path to your templates folder in your plugin. The [plugin_dir_path](https://developer.wordpress.org/reference/functions/plugin_dir_path/) function might help. In the main file of your plugin, you could probably use something like the following:

```php
add_action( 'init', function() {
	if ( ! class_exists( 'Timber\Timber' ) {
        return;
	}

    Timber::$locations = plugin_dir_path( __FILE__ ) . 'templates/';
} );
```

The folder would then be available when you render a view in your theme. The reason I’d add the folder in the plugin and not in the theme is that there’s not an easy way to determine the absolute path to a plugins directory from a theme (or maybe there is, but I couldn’t find one until now).

**Comment by stefanlesik** [comment]
Ok, so I've set the different locations as an array when the plugin loads.

`Timber::$locations = array(
    __DIR__ . '/public/partials/templates',
    get_stylesheet_directory().'/resources/views/templates',
    get_template_directory().'/resources/views/templates'
);

Timber::$dirname = array('templates', 'component');`

I now have a 'component' directory in 'templates' in the plugin and the theme. The components will be added to the plugin but if I wanted to overwrite a component file in the theme, how can I achieve this?

**Comment by conwaydev** [comment]
cc: @ericmikkelsen

**Comment by nbs** [comment]
We have Twig views that are rendered from a plugin but the cache isn't busting when the files change. Has anyone else run into this?

**Comment by Levdbas** [comment]
For plugin overrides I think you need to list the theme location before the plugin location in `Timber::$locations`
Cache busting issues can be reported in a separate ticket if still relevant.

Closing this, but please reply if this issue is still relevant for you.
