### ISSUE TITLE
QueryIterator/PostCollection doesn't handle $wp_query->posts when it is strictly false

### ISSUE THREAD

**Issue by ByronSpencer** [timber/timber#1698]
### Expected behavior
No warning when $wp_query->posts is false (rather than an empty array). This can be triggered if you return a 410 HTTP status, for example through various redirect plugins ("Redirection" in this case).

### Actual behavior
Warning is attributed to PostCollection.php init function. The is_null check is insufficient when $posts is actually set to false. QueryIterator.php also has an insufficient check in the get_posts function in which it uses isset to check the posts value.

Presumably using is_array in both these circumstances would be more appropriate.

### Steps to reproduce behavior
1. Install Redirection and set a URL to 410, or force a URL to return a 410 status via .htaccess or your method of choice.
2. Go to the URL and output the value $wp_query, inspect the value of the posts property.

If warnings are printed the following message is displayed (and will at the very least be in the logs):

**Warning: Invalid argument supplied for foreach() in /wp-content/plugins/timber-library/lib/PostCollection.php on line 44**

### What version of WordPress, PHP and Timber are you using?
WP: 4.9.4
Timber: 1.7.0
PHP: 7.1

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WP plugin manager on a multi network installation.

**Comment by drobin03** [comment]
@ByronSpencer This actually appears to be due to an issue in the Redirection plugin. I submitted a PR which was just merged, so this should be fixed in the next release.

**Comment by jarednova** [comment]
Thanks for that follow-up @drobin03! Glad to hear you've got a fix in there.

Thanks as well for the clean issue @ByronSpencer. Even though the answer is an issue with Redirection here, it's good to have this out there for future Googlers
