### ISSUE TITLE
Feature Request -> Timber\Menu->getCurrent()

### ISSUE THREAD

**Issue by waltercruz** [timber/timber#1704]
### Expected behavior
Hi! I think that adding a getCurrent to Timber Menu could be a good idea. What do you guys think about it?

**Comment by waltercruz** [comment]
It would return the current menu from Timber\Menu-> items

I'm currently making a single page application, and the menu items of the page are wordpress items. When I click though items, it moves to the target (anchor) and changes the class of the current section to current-menu-item. 

I'm using vue.js to do this, and I need to initialize the first state of the menu though vue.

It's a similar pattern to "Utilising beforeMount and data attributes to inject data" on this article: https://nehalist.io/directly-injecting-data-to-vue-apps-with-symfony-twig/

By current pattern is like this:

`{% for item in items %}`
`// print menu items`
`{% if item.current %}<input type="hidden" ref="active" data-value="{{item.slug}}" />{% endif %}`
`{% endfor %}`

It feels weird that I need to test for current on each iteraction of the loop, would be nice to have this outside of the loop, I think.

What do you guys think about it?

**Comment by acobster** [comment]
@waltercruz I think what you are looking for is something like:

```
<input type="hidden" data-value="{{ menu.get_current_item.slug }}">
```

Right?

(Here I'm using the name `get_current_item`, since `get_current` is ambiguous - it seems like it might refer to the current _menu_, whatever that would mean. :smiley: )

I actually implemented this in a library plugin I'm working on that's built on top of Timber, but I'm thinking more and more that this would be a great bit of logic to push down into Timber layer. All that is to say, if I understand what you're asking for, +1!

**Comment by gchtr** [comment]
@waltercruz 

> It feels weird that I need to test for current on each iteraction of the loop, would be nice to have this outside of the loop, I think.

I agree. I actually also stumbled over a use case for this recently, when I wanted to display child menu items of the current page outside the loop of the main menu.

@waltercruz I think it would be a great addition for Timber. If you already have a solution that you’re willing to share, could you do a pull request for it? Naming it `get_current_item` would make sense to me, too.

**Comment by waltercruz** [comment]
As I was in a hurry, I did with a loop by now.

If I think about a good implementation I will submit it

**Comment by gchtr** [comment]
@waltercruz Sorry, I first referenced you for the second paragraph, but actually it was intended for @acobster, so I changed the mention.

But anyways, if anyone of you wants to come up with a solution, that would be great!

**Comment by acobster** [comment]
> I actually also stumbled over a use case for this recently, when I wanted to display child menu items of the current page outside the loop of the main menu.

Yup, that is exactly the pattern we use it for. :smile: 

I'm in the middle of refactoring a bunch of menu-related code, but when I have it in a spot that feels acceptable for a PR I will send it your way!
