### ISSUE TITLE
space -> WSOD

### ISSUE THREAD

**Issue by arunaseva** [timber/timber#1705]
Hi

archive-custom_type.php (my template file in theme):

```
<?php
$context = Timber::get_context();
Timber::render( [ 'archive-custom_type.twig ' ], $context );
```
Give ^^^ white screen error. 

The error reason: see space after the twig template filename.

-------------
```
<?php
$context = Timber::get_context();
Timber::render( [ 'archive-custom_type.twig' ], $context );
```

Works!

--------------

I spend a lot of time to find the error. There was nothing in error log.

I suggest using trim() function in render function to remove space around template's filenames.

Thanks
Adam

**Comment by jarednova** [comment]
Hi @arunaseva thanks for the heads-up on this. Like you said, seems like a pretty quick fix with a well-placed `trim()` — interested in submitting a PR and living on in infamy?
