### ISSUE TITLE
Feature Request: overrideable way to instantiate MenuItems

### ISSUE THREAD

**Issue by acobster** [timber/timber#1709]
I'd like to be able to override how `MenuItem` instances are created. Right now, `new $this->MenuItemClass($item)` is bound up inside `Menu::order_children`. If it were in its own method, I could override that in order to, for instance, polymorphically create different kinds of `MenuItem`s:

```php
class CustomMenu extends Timber\Menu {
  protected function create_menu_item($item) {
    if ($this->is_login_nav_item($item)) {
     return new LoginMenuItem($item);
    }

    return new $this->MenuItemClass($item);
  }
}
```

In this example, `LoginMenuItem` might return a different title/URL depending on the user's login state. But we don't necessarily want all items to be instances of that class.

**Comment by gchtr** [comment]
Thanks for providing a pull request for this 💪. I guess we can close this now.
