### ISSUE TITLE
Incorrect casing in autoloader class map, causes installation failure on Linux (1.7.x)

### ISSUE THREAD

**Issue by MarkMaldaba** [timber/timber#1714]
I have just upgraded Timber to the latest version, and am getting a lot of error messages on our deployment server (Linux) which don't occur with an identical setup on my dev machine (Windows).

This appears to be an issue with the casing of paths in the autoloader class map that is included in the .zip file.

I suspect that the class map file simply needs regenerating with the correct file casing.

### Expected behavior

I should see my website home page.

### Actual behavior

I see a white page containing the following errors:

````
Warning: include([wp-content]/plugins/timber_library/lib/URLHelper.php): failed to open stream: No such file or directory in [wp-content]/plugins/timber_library/vendor/composer/ClassLoader.php on line 412

Warning: include(): Failed opening '[wp-content]/plugins/timber_library/lib/URLHelper.php' for inclusion (include_path='.:/usr/local/php56/lib/php') in [wp-content]/plugins/timber_library/vendor/composer/ClassLoader.php on line 412

Warning: include([wp-content]/plugins/timber_library/lib/Integrations/Command.php): failed to open stream: No such file or directory in [wp-content]/plugins/timber_library/vendor/composer/ClassLoader.php on line 412

Warning: include(): Failed opening '[wp-content]/plugins/timber_library/lib/Integrations/Command.php' for inclusion (include_path='.:/usr/local/php56/lib/php') in [wp-content]/plugins/timber_library/vendor/composer/ClassLoader.php on line 412

Warning: include([wp-content]/plugins/timber_library/lib/Integrations/ACF.php): failed to open stream: No such file or directory in [wp-content]/plugins/timber_library/vendor/composer/ClassLoader.php on line 412

Warning: include(): Failed opening '[wp-content]/plugins/timber_library/lib/Integrations/ACF.php' for inclusion (include_path='.:/usr/local/php56/lib/php') in [wp-content]/plugins/timber_library/vendor/composer/ClassLoader.php on line 412

Warning: include([wp-content]/plugins/timber_library/lib/Integrations/Timber_WP_CLI_Command.php): failed to open stream: No such file or directory in [wp-content]/plugins/timber_library/vendor/composer/ClassLoader.php on line 412

Warning: include(): Failed opening '[wp-content]/plugins/timber_library/lib/Integrations/Timber_WP_CLI_Command.php' for inclusion (include_path='.:/usr/local/php56/lib/php') in [wp-content]/plugins/timber_library/vendor/composer/ClassLoader.php on line 412

Warning: include([wp-content]/plugins/timber_library/lib/Integrations/ACF.php): failed to open stream: No such file or directory in [wp-content]/plugins/timber_library/vendor/composer/ClassLoader.php on line 412

Warning: include(): Failed opening '[wp-content]/plugins/timber_library/lib/Integrations/ACF.php' for inclusion (include_path='.:/usr/local/php56/lib/php') in [wp-content]/plugins/timber_library/vendor/composer/ClassLoader.php on line 412

Fatal error: Class 'Timber\Integrations\ACF' not found in [wp-content]/plugins/timber_library/lib/Integrations.php on line 28
````

### Steps to reproduce behavior

1. Download [Timber 1.7.0](https://downloads.wordpress.org/plugin/timber-library.1.7.0.zip) from [Wordpress site](https://wordpress.org/plugins/timber-library/).
2. Extract to plugins folder on Linux server.
3. Visit homepage.

Note that there may be more steps if setting up from scratch - this was an upgrade to an existing site that already had an old version of Timber installed, so the plugin was already enabled and a theme was already set up to use it.

Note that the same steps on a Windows machine, from the same starting point, did not cause any problems.

### What version of WordPress, PHP and Timber are you using?

WP 4.9.1, PHP 5.6.13, Timber 1.7.0

**Comment by MarkMaldaba** [comment]
This problem still persists in 1.7.1.  Any chance of fixing it?

**Comment by MarkMaldaba** [comment]
This issue was raised half a year ago since which time there have been several new releases and no additional bug reports or confirmations that anyone else is experiencing this issue.

Given the problem is so immediately fatal, there are only two conclusions from this: either no-one else is running the library on Linux or I made a mistake in reporting this.

I've gone back to our setup where we encountered the issue (and which has, since then, been using an older version of Timber) and, sure enough, I've found that there are casing issues in that deployment, whereby the file names don't match what is provided in the main Timber distro.

I have no idea how this happened, but I can confirm that the issue reported here was purely down to user error and so have closed the ticket.

Many, many apologies for the noise.

**Comment by gchtr** [comment]
Hey @MarkMaldaba 

Surely, we wouldn’t consider this as noise. *We* are sorry for not replying to this when you were still figuring out what’s wrong. Even after the nudge we somehow missed this 🙀.

I’m glad you’ve found a solution – and even better: you came back and reported why it happened to you. This can help in case someone runs into this. Thanks so much for this!
