### ISSUE TITLE
[Feature Request] Use timber inside WP Content / Widget / Shortcode

### ISSUE THREAD

**Issue by KimchaC** [timber/timber#1717]
Hi,

I tried searching to see if this is already supported, but I haven't found anything.

I'd like to use timber and twig inside of WP posts and pages instead of in the theme. Is that possible and if not could this be implemented?

Alternatively, do you have any tips on how I could implement this myself?

Thanks, Kim

**Comment by jarednova** [comment]
@KimchaC you could use WP's filters on `the_content` to process tags that someone might include through `Timber::compile_string($data);`. Here's a quick snippet (untested, so there's likely other stuff you'd have to do to implement ...

```php

/* functions.php */

add_filter('the_content', function($content) {
   $data = array('foo' => 'bar'); //add or retrieve whatever data you need 
   return Timber::compile_string($content, $data);
}, 10, 1);
```
