### ISSUE TITLE
$post->comments() function ignores WP's comment order.

### ISSUE THREAD

**Issue by kiiraklis94** [timber/timber#1731]
### Expected behavior
In the docs it say that the comments function takes an $order parameter.
Default is "wp" which it says is meant to use the wordpress option found in settings>discussion.

### Actual behavior
I've set this everything from 'wp' to 'wordpress' and even tried 'asc' and 'desc' but nothing seems to work. It just ignores it and displays the comments with the older comments on the top.

### What version of WordPress, PHP and Timber are you using?
WordPress 4.9.6, PHP 7.2, Timber 1.7.1

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by alicam** [comment]
This FIX for this is to change CommentThread.php, line 45. From:

`return array_merge($base, $args, $overrides);`

to

`return array_merge($base, $args);`

In other words, there is currently a forced override of the comment ordering. 

Why?!

**Comment by jarednova** [comment]
Thanks @alicam! I've applied your suggested fix in #2015

**Comment by jarednova** [comment]
Closed by #2015 — release coming soon!
