### ISSUE TITLE
Problems with WooCommerce menu item active element

### ISSUE THREAD

**Issue by ghost** [timber/timber#1732]
### Expected behavior
I wanna use `{% if item.current %}active{% else %}nav-item{% endif %}` on WooCommerce menu items. But active element in WooCommerce main page didn't work.
Also tried `{% if item.slug == post.post_name %}active{% endif %}` but same thing, didn't work.
All other page type menu item active elements (page.twig, also single product, product archive, cart and so on) works perfectly, but not WooCommerce main page.
When in example Cart page parent page is WooCommerce main page then Cart active element's also didn't work, but when I use Cart page without parent page then it's working perfectly.

So... If I visit WooCommerce shop main page (/shop), then this page active element didn't work.

### Actual behavior
My menu navigation twig file:
https://i.imgur.com/SlLOito.png

### What version of WordPress, PHP and Timber are you using?
WordPress 4.9.6, PHP 7.2, WooCommerce 3.4.2 and Timber 1.7.1

### AND WHEN I INSTALL WOOCOMMERCE STEP BY STEP:
https://timber.github.io/docs/guides/woocommerce/
THEN I GET 500 ERRORS WHEN I VISIT WOOCOMMERCE MAIN PAGE...

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WP.org / starter theme from Github

**Comment by palmiak** [comment]
I just tested `item.current` in our Woo and it works.

I'm looking at your code and it looks like you forgot `get_items`. This is an example from our webiste:
```
{% for item in menu_header.get_items %}
<li {{ item.current ? 'class="active"' }}><a href="{{item.link}}">{{item.name}}</a></li>
{% endfor %}```

**Comment by pascalknecht** [comment]
@ghost I have this problem too. Will investigate further.
