### ISSUE TITLE
Multiple Menu : How to?

### ISSUE THREAD

**Issue by gkatsanos** [timber/timber#1733]
Could you add an example to how to add a second menu to Timber? Or add it here and I will convert it to a documentation and make a Pull Request.
Thanks

**Comment by jesperwestlund1** [comment]
In function.php

`	
## Filters/Actions
add_action( 'init', array( $this, 'register_menus' ) );
add_filter( 'timber_context', array( $this, 'add_base_timber_context' ) );

## Functions
public function register_menus() {
		register_nav_menu( 'main-menu', __( 'Main', 'your-theme' ) );
		register_nav_menu( 'site-footer__column1', __( 'Site Footer column1', 'your-theme' ) );
		register_nav_menu( 'site-footer__column2', __( 'Site Footer column2', 'your-theme' ) );
		register_nav_menu( 'site-footer__column3', __( 'Site Footer column3', 'your-theme' ) );
}

public function add_base_timber_context( $context ) {
		$context['primary_menu'] = new TimberMenu('main-menu');
		$context['footer_column_1'] = new TimberMenu('site-footer__column1');
		$context['footer_column_2'] = new TimberMenu('site-footer__column2');
		$context['footer_column_3'] = new TimberMenu('site-footer__column3');
}

`
