### ISSUE TITLE
Display all reviews/rating from Woocommerce Products on landingpage using Timber

### ISSUE THREAD

**Issue by wezzou1** [timber/timber#1734]
Hi, I'm trying to display all rating/comments on landingpage using Timber, I got it to display with this 

```
<?php
/**
 * Template Name: Home Template
 */

$context = Timber::get_context();

$args = array (
	'post_type' => 'product',
);
$context['comments'] = Timber::get_posts( get_comments( $args ) );

Timber::render('views/home/home.twig', $context);
```
But it's just the **comments**, **no rating displays**... 

If I write this, it's working

```
    $args = array ('post_type' => 'product');
    $comments = get_comments( $args );
    wp_list_comments( array( 'callback' => 'woocommerce_comments' ), $comments);

```

But it's display before the header, I want it in a loop, so I can style it etc..

**Comment by jarednova** [comment]
Hey @wezzou1 I'm going to close this b/c it's a support issue. If you found a solution through some of the stuff we were talking about on Gitter please share here as well, thanks!

**Comment by davidrhoderick** [comment]
@wezzou1 You didn't post your solution....

**Comment by fatihtoprak** [comment]
> @wezzou1 You didn't post your solution....

any solution ?
