### ISSUE TITLE
Fatal error: Cannot declare class StarterSite (multisite)

### ISSUE THREAD

**Issue by bobhuf** [timber/timber#1744]
I'm working on a subdirectory-based multisite setup with 3 sites, 2 of which have child themes based on the main site's theme. After completing work on the first 2 sites, I cloned the site running the child theme and copied the theme folder.

This results in a fatal error:
**Fatal error: Cannot declare class StarterSite, because the name is already in use in /xxx/wp-content/themes/PARENT_THEME/functions.php on line 48**

I'm wondering if this error appears on the 3rd site, why not the second? Could it be because I cloned it?

### What version of WordPress, PHP and Timber are you using?
WordPress 4.9.7, PHP 7.1, Timber 1.7.1

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
GitHub

**Comment by jarednova** [comment]
Hmmm, tough to say why it might be working in one place but not the other, but the fix is pretty simple. Basically, you can't have two classes with the same names. So just by changing it (I'd pick something more descriptive that "StarterSite" should do the trick...

```twig
{#  /xxx/wp-content/themes/PARENT_THEME/functions.php on line 48 #}

class MyParentSite {
 ...
}
```

```twig
{#  /xxx/wp-content/themes/CHILD_THEME_A/functions.php on line 48 #}

class ChildSiteA {
 ...
}
```

```twig
{#  /xxx/wp-content/themes/CHILD_THEME_B/functions.php on line 48 #}

class ChildSiteB {
 ...
}
```
