### ISSUE TITLE
Feature Request: User::update_meta()

### ISSUE THREAD

**Issue by acobster** [timber/timber#1751]
I'd like to be able to do something like this:

```php
$user = new Timber\User();

// with ACF enabled, this caches the field value
$user->meta('my_custom_field');

$user->update_meta('my_custom_field', 'NEW CUSTOM VALUE');

// a long time from now, in a PHP file far, far away...
$user->meta('my_custom_field');
```

Implementing this on top of Timber is pretty trivial...until you try to do this with ACF, in which case the `my_custom_field` value gets cached on the first call, and isn't updated unless you call ACF's `update_field` instead of the vanilla `update_user_meta`. This was surprising and took me a while to figure out.

I have a bandaid solution for now, which checks `function_exists('update_field')` and calls the appropriate function accordingly. But it'd be nice to have this in `Timber\User` along with some smooth `Timber\Integrations\ACF` functionality.

Happy to start another PR in the somewhat-near future. :) Thoughts?

**Comment by jarednova** [comment]
Hi @acobster — believe it or not, something like that _sorta_ exists with Post. I deprecated it for a couple of reasons...

1) It wasn't universal (I think Post and Term had it, but not site or user)
2) Was anyone else using it or want it? Your issue here tells me: at least one person!
3) It was the only *write*-type action in Timber. Everything else is read. This is the biggest hairball. For example, why should a user only be able to update meta, but not title, content, name, etc.? If "write" is going to become a part of the library I think it needs to be comprehensive.

Interested in your thoughts here

**Comment by acobster** [comment]
Hmm. These are good points that I didn't really consider. I don't think they're necessarily show-stoppers, but they do kind of open up a can of worms (or three). I do agree that write should be comprehensive if it's there at all.

That said, I don't think these are reasons _not_ to implement write. We'd just need to be careful to make it cohesive across Post/Term/User. (Let's call them **The Big Three**, 'cuz that's fun!) I don't think that'd actually be that hard with our old friend polymorphism by our side.

> why should a user only be able to update meta, but not title, content, name, etc.?

Now that you mention it, this is an opportunity to abstract away some confusing things about the WP API. If there were a polymorphic `update` method across the three types, then each implementation could be responsible for distinguishing between `meta` and "native" fields. For example, you might call:

```php
$user->update([
  'user_email' => 'new@example.com',
  'my_custom_field' => 'hello'
]);
```

`User` knows that `user_email` is a native `wp_user` column, while `my_custom_field` obviously lives in `wp_usermeta`. We wouldn't _necessarily_ have to make it this high-level - we could instead choose to just pass on the mental complexity of this distinction to Timber users and implement `update()` and `update_meta`. But the WP API is not even consistent, e.g. `first_name` is a meta field but [can be updated via `wp_update_user`](https://codex.wordpress.org/Function_Reference/wp_update_user). We might as well "reduce the WordPress-specific knowledge required to theme a website" here if we can. ;)

The one design challenge that brings up in my head is: how does this change the interface? We obviously wouldn't want to break `CoreInterface` by adding new methods on it. But what if The Big Three implemented a new `Timber\WriteableInterface`? Then other things that don't need to know about `Post` etc. can still write to Timber objects. Just kinda thinking out loud at this point.

Of course, the big reason not to do this is, y'know, time. But much of my time is _probably_ going to be spent rolling this out in Conifer anyway if it doesn't land in Timber.

**Comment by chrisvanpatten** [comment]
I don't think it makes a ton of sense for writability to be enabled on default Timber models; I'm of the strong opinion that if you want to do writable models, you probably should have your own abstraction of models (per-post type or whatever) and you probably also want getters/setters/etc.

But that said, it could be interesting to have a separate project or class available as a trait, so you could do something like…

```php
<?php

class MyModel extends \Timber\Post
{
    use \Timber\Writable\PostMeta;

    public function setMyValue($value)
    {
        $this->update_meta('my_value', $value);
    }
}
```

But at that point, it's also questionable whether that's any better than just referencing `update_{$objectType}_meta` (I've gone back and forth on this in various projects and don't know that I have a strong opinion at this point).

**Comment by acobster** [comment]
@chrisvanpatten I see two key benefits over raw `update_*_meta`:

* Encapsulation: ID doesn't have to be in scope for calling code
* ACF integration can be implemented in one place, abstracting the caching issue described in the original writeup

I think having it in a trait as you propose makes a lot of sense, and I generally favor getters/setters/CPT-specific data logic too. So your example is exactly the kind of use-case I imagine. :)

**Comment by palmiak** [comment]
I think that Timber should mostly be for read operations - it's mostly an implementation of Twig for WP. And Twig is also read only. 

On the other hand I don't see any reason why not make an Integration or an extra library that would extend Timber the way that @chrisvanpatten mentioned. Some people might be interested (me for example).

In short - it can be very useful, but I don't see this as a part of core.

**Comment by acobster** [comment]
Thanks everyone for the feedback. You've convinced me: this shouldn't be part of Timber's core. I'll likely move forward with adding this to Conifer's [Post API](https://coniferplug.in/posts.html) at some point.
