### ISSUE TITLE
ACF Group fields

### ISSUE THREAD

**Issue by code23-isaac** [timber/timber#1763]
There's nothing in the docs about using ACF Group fields, how do you go about outputting these?

**Comment by wonkeythemonkey** [comment]
If you use `{{ post.get_field('group_name') }}` to access the group, all of its child fields become children of the new Timber object.

For example, if you have a group called "page_header" and a sub-field called "intro_text", you would call it like so:
```
{{ post.get_field('page_header').intro_text }}
```

If you are accessing multiple sub-fields throughout your template, you can save some function calls by assigning the processed group field to a variable, like so:
```
{% set page_header = post.get_field('page_header') %}

{{ page_header.intro_text }}
{{ page_header.hero_image }}
{{ page_header.button_link }}
```

**Comment by code23-isaac** [comment]
Ah awesome, thank you!

What about if you had nested repeaters in that group?

**Comment by palmiak** [comment]
Sorry for late answer - probably you've figured it out already, but it maybe useful for others:
```twig
{% for row in post.get_field('group').repeater %}
  {{ row.some_field }}
{% endfor %}
```

**Comment by szepeviktor** [comment]
> There's nothing in the docs about using ACF Group fields

Here you are https://github.com/timber/timber/blob/master/docs/guides/acf-cookbook.md

**Comment by gchtr** [comment]
The documentation about the group field can now be found in the documentation: <https://timber.github.io/docs/guides/acf-cookbook/#group-field>
