### ISSUE TITLE
can't get fields without an ID

### ISSUE THREAD

**Issue by rehat101** [timber/timber#1764]
I'm using ACF custom fields but I cannot seem to get the fields without an ID anymore. I have to explicitly add a post id to retrieve the data inside the field.

`get_field('main_text', 323);` 

I remember in my older Timber projects I could've just done `get_field('main_text');` and I would get the value. 

I'm doing this on front-page.php

**Comment by jake46a** [comment]
Have you tried {{post.main_text}}.  If that does not work I would need to see your pho file calling context.

**Comment by rehat101** [comment]
@jake46a  That doesn't work. Below is the file of how I'm calling context.

```$args = array(
	'numberposts' => 3,
	'post_type' => 'post',
	'post_status' => 'publish',
	'category_name' => 'updates'
);

$data = Timber::get_context();
$post = new TimberPost();
$context['post'] = $post;
$data['posts'] = Timber::get_posts($args);

$data['main_text'] = get_field('main_text', 323);
$data['main_image'] = get_field('main_image', 323);

Timber::render('front-page.twig', $data );```

**Comment by jake46a** [comment]
> 

So from what I gather you are trying to put 3 posts from updates on the front page?

But you are defining the front page content as “post” and the 3 blog entries as “posts” also. This is why you need to define the post Id. 

I would suggest defining the posts from updates as such
$data[update_posts] = Timber::get_posts($args);

And I think you need to change your context line from

$context['post'] = $post; 

To

> $data['post'] = $post;

**Comment by rehat101** [comment]
Did exactly what you said and it still doesn't work. 

```
$args = array(
	'numberposts' => 3,
	'post_type' => 'post',
	'post_status' => 'publish',
	'category_name' => 'updates'
);

$data = Timber::get_context();
$data['update_posts'] = Timber::get_posts($args);

$post = new TimberPost();
$data['post'] = $post;

$data['main_text'] = get_field('main_text');
$data['main_image'] = get_field('main_image');

Timber::render('front-page.twig', $data );
```

**Comment by jake46a** [comment]
$data['main_text'] = get_field('main_text'); $data['main_image'] = get_field('main_image');
The above section I do not use.  In the twig file when I want to call the data from the front page I use 

{{ post.main_text}}

For the blog entries I loop for update_post in update_posts
Then call that content with 
{{update_post.FIELDNAME}}
Let me know I should be back to my computer on an hour.

**Comment by rehat101** [comment]
It still doesn't work. When I dump the variable `$post` I see the last post entry details. I have also inspected in the db and my custom field is associated to an id 332 which is a page id and not a post id.

**Comment by jake46a** [comment]
Ok I am at my computer now.  I will set up a test here. So the page id is the front page correct?

**Comment by rehat101** [comment]
page id 332 is the frontpage

**Comment by jake46a** [comment]
ok

**Comment by rehat101** [comment]
It used to work for me. Where is your custom field stored? Inside a post or a page?

**Comment by rehat101** [comment]
Which location are you setting up your custom field?

**Comment by jake46a** [comment]
In this case, the custom data is set up in both the page article and the posts.  I use debug bar with the timber addon and it helps immensely.  I use {{post.main_text}} to pull from the page itself:
$context['post'] = Timber::query_post();

and for the custom fields in the posts i would use {{update_post.FILEDNAME}}  in the loop and it set through
$context['update_posts'] = Timber::get_posts($args);  

The only time I need to use the post id is when i am pulling data from a post or page that is not part of the current $context.

For example:  I have a client for which I built an Ad component to show ads in various regions.  I did this cause the ones out there are resource hogs.  In this case, I created a post(s) that had the layouts for different types.  And had to call the post ID in the php file to set up the fields.

Here is the php code:

``` $global_ad_layouts_page_id = 453;
$context['global_ad_layouts_page_id']     = $global_ad_layouts_page_id;
$context['enable_home_page_fixed_top_ad'] = get_field( 'enable_home_page_fixed_top_ad', $global_ad_layouts_page_id );
$context['enable_parallax_3_ad']          = get_field( 'enable_parallax_3_ad', $global_ad_layouts_page_id );
$context['enable_parallax_5_ad']          = get_field( 'enable_parallax_5_ad', $global_ad_layouts_page_id );
$context['enable_before_content_ads']     = get_field( 'enable_before_content_ads', $global_ad_layouts_page_id );
$context['enable_after_content_ads']      = get_field( 'enable_after_content_ads', $global_ad_layouts_page_id );
$context['enable_footer_ads']             = get_field( 'enable_footer_ads', $global_ad_layouts_page_id );
```

**Comment by rehat101** [comment]
I'm not sure why I can't get the fields directly. Should I try it on a new WP db?

**Comment by jake46a** [comment]
That may worth a try.  What version of Wordpress , Timber, and ACF are you running now.

**Comment by rehat101** [comment]
It works! I'm not sure what was wrong with the previous database. I did a fresh install and I can just do get_field() without an ID

**Comment by jake46a** [comment]
Glad to hear
