### ISSUE TITLE
Extra character when call `dynamic_sidebar` inside .twig

### ISSUE THREAD

**Issue by bludnic** [timber/timber#1765]
When using `function('dynamic_sidebar', 'navbar_widgets')` in `.twig` files, an extra `1` character appears after the sidebar. But if I call `dynamic_sidebar('navbar_widgets')` from a `.php` file, there is no problem.

### Actual behavior
Screenshot: https://prnt.sc/kiww6n

### Steps to reproduce behavior
1. Install this sample theme: https://github.com/bludnic/sample-timber
1. Go to Appearance -> Widgets.
2. Add `Text Widget` with some text to `Navbar Widgets`.

### What version of WordPress, PHP and Timber are you using?
WordPress 4.9.8, PHP 7.0.30-0ubuntu0.16.04.1, Timber 1.7.1

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
From WP.org: https://wordpress.org/plugins/timber-library/

**Comment by gchtr** [comment]
The `dynamic_sidebar()` function returns `true`, when it found and called the widget sidebar. That’s the `1` you’re seeing.

If you do

```twig
{{ function('dynamic_sidebar', 'navbar_widgets') }}
```

then you’re **echoing the return value** of the `dynamic_sidebar()` function, which is `true`. If you just want to run the function, but not echo it’s return value, use [do](https://twig.symfony.com/doc/2.x/tags/do.html):

```twig
{% do function('dynamic_sidebar', 'navbar_widgets') %}
```

**Comment by bludnic** [comment]
Thanks
