### ISSUE TITLE
Override Timber templating sytem

### ISSUE THREAD

**Issue by redsoxfan2499** [timber/timber#1769]
I am new to Timber and I have inherited a site that is using Timber and Twig. I need to know if there is a way to overide or skip over the Timber system for one template. I have a very complicated custom template I need to create and I want to bypass the system for this one template.  I have tried in both the functions, index file to check for if the template is being used to not load all of the Timber files but not having success.  

Thanks in advanced for any help.

**Comment by jeremypetersen** [comment]
Hi,

Just write your template (php file) as usual, without calling any twig file. Your template will render correctly in accordance with the usual WordPress template hierarchy.

Timber is powerful as it allows you to "twig" the files you want and to use the classic full php method when needed.

**Comment by redsoxfan2499** [comment]
Thanks for the quick response. 

So I create a custom template and for testing I grab the normal WP Page code. 

`<?php
/**
 * Template Name: Test Page
 */
 get_header(); ?>
 <div id="primary" class="content-area">
   <main id="main" class="site-main" role="main">

   <?php
   // Start the loop.
   while ( have_posts() ) :
     the_post();

     // Include the page content template.
     <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
     	<?php
     		// Post thumbnail.
     		twentyfifteen_post_thumbnail();
     	?>

     	<header class="entry-header">
     		<?php the_title( '<h1 class="entry-title">', '</h1>' ); ?>
     	</header>

     	<div class="entry-content">
     		<?php the_content(); ?>
     		<?php
     			wp_link_pages(
     				array(
     					'before'      => '<div class="page-links"><span class="page-links-title">' . __( 'Pages:', 'twentyfifteen' ) . '</span>',
     					'after'       => '</div>',
     					'link_before' => '<span>',
     					'link_after'  => '</span>',
     					'pagelink'    => '<span class="screen-reader-text">' . __( 'Page', 'twentyfifteen' ) . ' </span>%',
     					'separator'   => '<span class="screen-reader-text">, </span>',
     				)
     			);
     		?>
     	</div>

     	<?php edit_post_link( __( 'Edit', 'twentyfifteen' ), '<footer class="entry-footer"><span class="edit-link">', '</span></footer>' ); ?>

     </article>

     // If comments are open or we have at least one comment, load up the comment template.
     if ( comments_open() || get_comments_number() ) :
       comments_template();
     endif;

     // End the loop.
   endwhile;
   ?>

   </main>
 </div>

 <?php

 get_footer();
`


And I get 500 white screen error with This page isn’t working. 

any suggestions?

**Comment by redsoxfan2499** [comment]
So it is just printing our get_template_part. 

{% extends "base.twig" %}

{% block content %}

get_template_part('test.php')
{% endblock %}

**Comment by jarednova** [comment]
You can't use PHP like that in a template. To call methods like that you need to tell Twig that it's a PHP call and not merely a piece of text...

```twig
{% extends "base.twig" %}

{% block content %}

    {{ function('get_template_part("test.php")') }}

{% endblock %}
```

**Comment by jeremypetersen** [comment]
@redsoxfan2499 exactly :) And in your template part, you just have to write what needs to be output in the main content of the page, as the global things (eg. header, footer, sidebar...) should be rendered by extending the `base.twig` file. So don't call usual `get_header`, `get_footer`... functions.

**Comment by redsoxfan2499** [comment]
Guys, thanks for all the input and help. So I am using Jareds exact code.  I have the test.php file in same directory as my test.twig file and nothing is printing out. 

{% extends "base.twig" %}

{% block content %}

{{ function('get_template_part("test.php")') }}

{% endblock %}
 

test.php file . I am just echoing out Test. 

<?php 
echo 'Test';
?>

**Comment by jarednova** [comment]
@redsoxfan2499 it's possible that there could be path issues (I've never tried to call a template_part from within a Twig file). Try making a function in your `functions.php` file that you can call that also echos "TEST" or something; then go from there to debug where the fault might lie

**Comment by redsoxfan2499** [comment]
Well, I have tried multiple things without success. So since I a new to Timber, I went to learn using the Video Tutorials which are out of date.  So then I went to the Documentation. Of course I have downloaded Timber plugin and activated it. I also downloaded the starter theme from the docs. The docs are out of date a bit from what I am seeing on in the starter theme. So following directions trying to learn template inheritance, I  tried to extend the single.twig file and then created a single-test.twig file. The single.twig file of course extends the base.twig file. then following the directions, I added this to the single.twig 

`  {% block title %}
				  	<h1 class="article-h1">{{ post.title }}</h1>
                    <h2 class="article-h2">{{ post.subtitle }}</h2>
				{% endblock %}` 

here is my single-test.twig file. 
`{% extends "single.twig" %}

  {% block title %}
        <h1>TEST</h1>
    {% endblock %}` 

It does not work. I also noticed in the docs it states create files in the views folder but in the starter theme it is called templates. 

I am using Timber 1.7.1, WP 4.9.8, and ACF 4.4.12 and ACF Pro 5.7.2.

**Comment by jake46a** [comment]
@redsoxfan2499 

Yes some of the docs are out of date, but we are working on fixing that. here is some code that I use for my base in my template.

In the ```single.php``` located in the template directory, for example:
```mytemplate/single.php```
I have:

```<?php
use Timber\Timber;
$context         = Timber::get_context();
$context['post'] = Timber::query_post();

Timber::render( 'pages/single.twig', $context );
```

**Comment by redsoxfan2499** [comment]
thanks for the help. I am using the timber starter theme from github. The link provided in the docs. The single.php is located in the starter theme root. then there is a templates directory where all of the twig files are located. There is the single.twig which extends base and works. Then following the directions from Timber, https://timber.github.io/docs/getting-started/theming/ .  
Nesting Blocks, Multiple Inheritance . section:

I am trying to extend the single twig following the directions. I added the code in single.twig and then created a new file called single-test.php  

I have also tried in the footer. I created a footer-test.twig which extends footer and created a block and nothing. I also went to the Twig documentation and it seems I am doing everything correctly. It does not want to extend pass the base twig

**Comment by jake46a** [comment]
@redsoxfan2499 

Also, do not give up.  The learning curve on Timber is not that bad.  I used it originally in a project where the load times were ridiculous. Once Timber was used, load times went from 35 seconds to 5-6 seconds.  After that I never looked back. 

I use my starter theme on all of my projects and my creatings separate partials I just call the ones I need.

In your original code, it looks like you are extending the single.twig file, instead of the base file.  It has been a while since I worked with the starter template.

If you can zip up and send me your full template file for the starter theme, I can take a quick look.  I have a free area in my local host right now.

let me know

**Comment by redsoxfan2499** [comment]
[starter-theme-master.zip](https://github.com/timber/timber/files/2311834/starter-theme-master.zip)

**Comment by jake46a** [comment]
Ok thanks will get to it in a few minutes. But I think the problem may be this from the starter theme

	Timber::render( array( 'single-' . $post->ID . '.twig', 'single-' . $post->post_type . '.twig', 'single.twig' ), $context );

As it does not call the post name. I will get back to you soon

**Comment by jake46a** [comment]
@redsoxfan2499 

Yes that was the problem.
in single.php change this line

```Timber::render( array( 'single-' . $post->ID . '.twig', 'single-' . $post->post_type . '.twig', 'single.twig' ), $context );```

to


```Timber::render( array( 'single-' . $post->slug . '.twig', 'single-' . $post->post_type . '.twig', 'templates/single.twig' ), $context );```

**Comment by jake46a** [comment]
@redsoxfan2499 

On a side note I use debug bar whenever working with timer as it gives me the template files being called and all of the content variables.

Install these two plugins:

Debug Bar
Timber Debug Bar

Then in wp-config.php set from 

```define('WP_DEBUG', false);```

to

```define('WP_DEBUG', true);```

**Comment by jake46a** [comment]
@jarednova 

Jared,

Maybe this should be noted to whoever is redoing the new starter templae

**Comment by redsoxfan2499** [comment]
jake and everyone thanks again for all of the help. I changed the line single.php file as noted. But this did not fix my issue. I still cannot extend the single.twig template. 

Also, thanks for the advice on the Timber Debug Bar. 

I will attach screenshots. In the single.twig. I had the block headline in the single.twig.   The title was already being displayed without the suggested changes.  I then create a file called single-test.twig which I extend single and then add a echo TEST inside the block headline.  when my page renders I am not seeing TEST. 

![singlephpshot](https://user-images.githubusercontent.com/1205420/44495599-2be9fd80-a636-11e8-99ba-f81088a97067.png)
![singletestshot](https://user-images.githubusercontent.com/1205420/44495600-2be9fd80-a636-11e8-91c5-d470d40263ed.png)
![singletwigshot](https://user-images.githubusercontent.com/1205420/44495601-2be9fd80-a636-11e8-818f-cfe08f227ff3.png)
![frontendshot](https://user-images.githubusercontent.com/1205420/44495604-32787500-a636-11e8-8f17-0347af2cc28f.png)

**Comment by jake46a** [comment]
Strange.  Here are my screen shots. Single.php

![a1](https://user-images.githubusercontent.com/37761061/44496644-97ca6700-a632-11e8-9937-cd7fb7426d8b.png)

Single-test.twig
![a2](https://user-images.githubusercontent.com/37761061/44496650-9f8a0b80-a632-11e8-994b-b9060c133eef.png)

single.twig
![a3](https://user-images.githubusercontent.com/37761061/44496656-a6b11980-a632-11e8-8a7b-97917bc05140.png)

Post on front end
![a4](https://user-images.githubusercontent.com/37761061/44496662-b0d31800-a632-11e8-8254-70cc78f22a44.png)

Debug Bar
![a5](https://user-images.githubusercontent.com/37761061/44496666-b6306280-a632-11e8-9dd0-56103d0c8068.png)

**Comment by redsoxfan2499** [comment]
This is strange. So, I download a new copy of WP and spun up a fresh instance of WP on my local MAMP. I installed TImber and the starter theme I have been using since you can get it working on your local abut ti still does not work.   What version of Timber plugin are you using? I am using version 1.7.1.  I have minimal plugins now and still nothing. Using the Timber debug, it shows the single template and not the single-test one like your screen shot thus that is why TEST is not showing. The issues is WHY does the single-test.twig not work.

![screen shot 2018-08-22 at 8 15 29 pm](https://user-images.githubusercontent.com/1205420/44499142-31e8da00-a648-11e8-9488-7fd4348e3485.png)
![screen shot 2018-08-22 at 8 15 43 pm](https://user-images.githubusercontent.com/1205420/44499143-31e8da00-a648-11e8-9843-3f538e8a5165.png)

**Comment by redsoxfan2499** [comment]
OK. that worked. When I title the new Post Test. It uses the single-test.twig template. When I create another new post and title it, it does NOT work and use the single-test.twig template.  Does it have to do with the name of my twig file?   I would except the single-test.twig to be used for all single posts?

**Comment by jake46a** [comment]
It has to do with the fact that that override is based upon the name of the WordPress post, hence the slug as explained in the documentation you read.  What exactly are you trying to do?

**Comment by jake46a** [comment]
For all single posts, you would modify just single.twig. Then ALL single posts would change to that.  The way you were setting it up, the post with the name "test" is the only one that would get modified.

**Comment by redsoxfan2499** [comment]
Light Blub just went off!  I gotcha. I thought that this would just extend every single post. In this current website I inherited, the previous developers has like 5 twig files making up one page. So I am just trying to learn Timber/Twig so I can support this website and was trying to follow directions. So if I wanted to create a file to be include in single I would need to use the includes function.  Plus when I started watching the videos and then realized they were out of date. Then I started reading the docs and grabbed the starter theme and saw it was also some what out of date, I thought it was not working because the docs were out of date. Thus I reached out for help. I totally get it now. Makes total sense. Sorry for all of the confusion. Thanks so much for all fo your help. FYI, if I was a developer just checking out Timber I would have already jumped ship with the outdated videos and docs and starter theme out of date and then ran into an issue. I have to learn Timber so I am in it. I am sure after I finish this learning curve which does not seem to bad, I will really like Timber. Jake46a thanks so much for all fo your help thanks to everyone else who jumped in early.

**Comment by jake46a** [comment]
@redsoxfan2499  
You are welcome.  No thanks is necessary as it is my way of giving back to the community that wrote this magnificent plugin.  I want everyone using it.  If you need any additional help just ask.

**Comment by redsoxfan2499** [comment]
BTW, my original issue was there is a complicated template I need to create and I wanted to do it outside of Timber since I know normal WordPress and knew I could get it done faster.  But without success, I then started to learn Timber and ran into that issue. So I am going to give it a try using Timber. So far I like this better then Genesis. Thanks again!
