### ISSUE TITLE
Timber::get_widgets() returns string(0) "" 

### ISSUE THREAD

**Issue by sirmacik** [timber/timber#1770]
### Expected behavior
Timber returns contents of widget area

### Actual behavior
`` {{dump(footleft)}} gives string(0) "" ``

### Steps to reproduce behavior
**functions.php**

`` 
function wfp_widgets_init() {
    register_sidebar( array(
        'name'          => __('Lewa stopka', 'wfp'),
        'id'            => 'footleft',
        'before_widget' => '<div class="widget">',
        'after_widget'  => '</div>',
        'before_title'  => '<h3>',
        'after_title'   => '</h3>',
    ) );
    register_sidebar( array(
        'name' => 'Mobile menu',
        'id' => 'mobilemenu',
        'before_widget' => '<div class="widget">',
        'after_widget'  => '</div>',
        'before_title'  => '<h4>',
        'after_title'   => '</h4>',
    ) );
}
add_action( 'widgets_init', 'wfp_widgets_init' );
``

and later

``
$context['footleft'] = Timber::get_widgets('footleft');
$context['mobilemenu'] = Timber::get_widgets('mobilemenu');
``

**footer.twig**
``
{{dump(footleft)}}
``
### What version of WordPress, PHP and Timber are you using?
Example: WordPress 4.49.8, PHP 7.0, Timber 1.7.1

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
 Upgraded to newest version via plugin updater in WordPress dashboard

**Comment by jake46a** [comment]
@sirmacik 

I copied your code into my theme and I did get ```string(0) "" ```

But, then I went into Appearance -> Widgets, and assigned a html to that widget area.  After doing that the output was  

```string(66) "
test
test
"
```

Do you assign some content to that widget area?

**Comment by sirmacik** [comment]
Yes, I have "Meta" widget assigned there. Still getting empty string :/ 
I'm out of ideas how to debug it.

**Comment by jake46a** [comment]
@sirmacik 

I put in the Meta widget and now in the footer I get this.
```
string(573) "
meta
Site Admin
Log out
Entries RSS
Comments RSS
WordPress.org
"
```

Any debugging I do when using TImer I use these 2 plugins:
Debug Bar
Timber Debug Bar

Then in wp-config.php set from

```define('WP_DEBUG', false);```

to

```define('WP_DEBUG', true);```

This way I can see the variable passed via content.


I used a page to test it on. But here are my files I tested with:

```functions.php```

``` 
function pwa_widgets_init() {
register_sidebar( array(
    'name' => __('Lewa stopka', 'wfp'),
    'id' => 'footleft',
    'before_widget' => '
    
    ',
    'after_widget' => '
    ',
        'before_title'  => '<h3>',
        'after_title'   => '</h3>',
    ) );
}
add_action( 'widgets_init', 'pwa_widgets_init' );
```

```page.php```

```
<?php


use Timber\Timber;

$context         = Timber::get_context();
$context['post'] = Timber::query_post();
$context['footleft'] = Timber::get_widgets('footleft');
Timber::render( 'pages/page.twig', $context );
```

```page.twig```  I make the call to the footer section in my base file, not in this file

```
{% extends 'layouts/timber-boot-base.twig' %}

{% block content %}
    {% include 'partials/post-card.twig' %}
{% endblock content %}
```

```timber-boot-base.twig```  The part of my base file that matters to you is:

```
    {% block footer %}
    {{dump(footleft)}}
    {% endblock footer %}
```

The only thing I can think of is did you do these calls in your php file:

```
$context         = Timber::get_context();
$context['post'] = Timber::query_post();
```

Maybe try the code I used and see what happens.

**Comment by sirmacik** [comment]
It was caching problem on my side. Sorry for bothering and thank you very much for all the help. Your input helped me greately in solving all other problems! (:

**Comment by jarednova** [comment]
Thanks so much to @jake46a for helping out here. @sirmacik glad you were able to resolve this!
