### ISSUE TITLE
Timber not fully compatible with Elementor

### ISSUE THREAD

**Issue by norman-pixelkings** [timber/timber#1772]
I'v build 10+ website with Timber and Elementor as page builder. So far no problem. But the new Header / Footer templates feature gives me the "missing the_content function" as long as I use Timber based templates. Switching to a default theme fixes the issue.
Elementor on normal pages and section templates are no problem though.

### Actual behavior
Elementor can't find "the_content" function?  (https://go.elementor.com/the-content-missing/)

### Steps to reproduce behavior
Dashboard > Elementor > Templates : create header or footer template

### What version of WordPress, PHP and Timber are you using?
Everything up to date. Latest versions.

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
In the backend > plugins download...

### error log
log file: (not really errors just notices)
[apache-errors.txt](https://github.com/timber/timber/files/2331056/apache-errors.txt)

Any help is appreciated. I tried everything like disabling al plugins, installing the Timber startertheme etc. I asked the same question on the Elementor Github and the could not help me.

**Comment by jarednova** [comment]
@norman-pixelkings it's hard to say for sure, this really seems more like an Elementor issue (since as you note, it comes from a new template setup from them). Here's my best guess:

The doc you link to says that Elementor needs `the_content()` to fire. The problem is, Timber never calls this function. You could try "faking" the call but preventing it's output. Somewhere in your `single.php` file (or whatever relevant template) try...

```php

ob_start();
the_content();
ob_end_clean();
```

This *might* solve the issue (if indeed, the only issue is the warning you get)

**Comment by norman-pixelkings** [comment]
Hi Jared,

Thanks for your reply. I tried to add those functions before but no luck. The funny thing is that other templates like sections or pages are no problem. I have to contact Elementor again. 

Thanks again!

Norman

**Comment by noel-byT** [comment]
Hi Norman,

I know this comment is a little bit dated - but have you reached out to Elementor? I'm actually facing the same problem right now. 😅

**Comment by norman-pixelkings** [comment]
> Hi Norman,
> 
> I know this comment is a little bit dated - but have you reached out to Elementor? I'm actually facing the same problem right now. 😅

Hi Noel, unfortunately I don't have a solution. And yes I did reached out to Elementor. For now I'm not using the Elementor header functionality. It looks I'm not using it in the near future so It's not a dealbreaker to me. Funny is that the new popup template does work. So I can create popups within my Timber theme. Still not understanding why the header templates does not work.
Good Luck!

**Comment by gidehault** [comment]
as Timber can call PHP functions, you just have to replace 

{{post.content}}

within your Twig script with :

{{ function('the_content') }}

Elementor will find it as a regular the_content() call, and then will work

**Comment by mrcodefinger** [comment]
> as Timber can call PHP functions, you just have to replace
> 
> {{post.content}}
> 
> within your Twig script with :
> 
> {{ function('the_content') }}
> 
> Elementor will find it as a regular the_content() call, and then will work

Hi, that doesn't work either, has anyone found or developed another solution by chance?

**Comment by norman-pixelkings** [comment]
> {{ function('the_content') }}

Sorry for the late reply :)  But it stil does not work with single product templates. I can't figure out which template is used there. I added the function as you suggested in every template of my theme. But no luck...

**Comment by giordanovi** [comment]
It still not working for me with Elementor Header/Footer creation.
How can I solve?
Thanks

**Comment by Reaper88** [comment]
You may use this bit of code to make it work with elementor for header and footer from Pro version.
```twig
{% if not function( 'function_exists', 'elementor_theme_do_location' ) or not function( 'elementor_theme_do_location', 'header' ) %} 
    {% include 'parts/header.twig' %}
{% endif %}
```

**Comment by avblink** [comment]
Elementor requires get_header() and get_footer() to load its scripts and templates.

Add this to functions.php

```
 use ElementorPro\Modules\ThemeBuilder\Module;

function render_elementor_header() {
    if ( function_exists('elementor_theme_do_location') ) {
        elementor_theme_do_location('header');
    }
}

function render_elementor_footer() {
    if ( function_exists('elementor_theme_do_location') ) {
        elementor_theme_do_location('footer');
    }
}
```

And this inside base.twig file of your Timber theme:
```
<body class="{{body_class}}" data-template="base.twig">
	{{ function('wp_body_open') }}
	<a class="skip-link screen-reader-text" href="#content">{{ _e( 'Skip to content') }}</a>
	{{ function('render_elementor_header') }}
	<header class="header" >
.
.
.

{% block footer %}
	{{ function('render_elementor_footer') }}
	{{ function('wp_footer') }}
{% endblock %}

```

This should get your Elementor Headers and Footers working.
