### ISSUE TITLE
Timber and WooCoomerce Sensei incompatibility 

### ISSUE THREAD

**Issue by bawpcwpn** [timber/timber#1776]
I have an issue with the WooCommerce plugin [Sensei](https://woocommerce.com/product-category/themes/sensei-themes/) that doesn't happen on non-Timber based themes. A function is attached to`wp_head` which updates a lesson status, and then a button is conditionally displayed on a value updated by said function in the render. This happens on the `page-plugin.twig` template. 

### Expected behavior
"Complete Lesson" button is pressed and page reloads hiding the button, and displaying an alert.
Functions attached to `wp_head` are run before functions inside the php template. 

### Actual behavior
"Complete Lesson" button still displays, however a subsequent press and page load evaluates correctly.
Running a counter alongside each of the functions shows the functions that are attached to `wp_head` are run after the function inside the template body is run. 

### Steps to reproduce behavior
1. With Sensei installed and setup, under a specific lesson, click "Complete Lesson"
2. Page reloads, and "Complete Lesson" button is still visible.

### What version of WordPress, PHP and Timber are you using?
Wordpress 4.9.8
PHP 7.1.11
Timber 1.7.1

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Upgraded to newest version via plugin updater in WordPress dashboard

**Comment by palmiak** [comment]
@bawpcwpn it might be difficult to test, because the price of the plugin. I'm not sure could you share this plugin with us (from the legal point of view).

**Comment by bawpcwpn** [comment]
@palmiak yeah that's a fair point. Wondering what the legality of me creating a test case site in a private GitHub repo and inviting particular people in?

**Comment by palmiak** [comment]
I'm not sure. I think that you can share the code(it's GPL) but not the
serial number for support. But it would be better if someone smarter could
say something about this matter.

pt., 7 wrz 2018, 09:29 użytkownik Thomas Huxley <notifications@github.com>
napisał:

**Comment by aharl** [comment]
The Sensei plugin is available on Github for download. https://github.com/Automattic/sensei

**Comment by Levdbas** [comment]
Stale and 3-rd party. Can probably be closed.
