### ISSUE TITLE
Update Starter Theme for 2.x

### ISSUE THREAD

**Issue by jarednova** [timber/timber#1784]
- [ ] Ensure calls to all Timber classes are namespaced
- [ ] Ensure there are no deprecation warnings from any methods/classes called

**Comment by marciojc** [comment]
Hi,
I did some improves, https://github.com/timber/starter-theme/pull/72.

**Comment by jarednova** [comment]
Awesome, thanks @marciojc ! I'll check them out in the next few days

**Comment by jarednova** [comment]
Thanks again @marciojc — I've now merged your changes into the starter theme. I'm going to leave this issue open as we work to get the starter theme to use the new 2.x syntax and classes

**Comment by marciojc** [comment]
Thanks @jarednova. I will continue working on updating the starter theme when possible.

**Comment by gchtr** [comment]
With the updates in https://github.com/timber/starter-theme/pull/142, I think we can close this.
