### ISSUE TITLE
Make phpcs a dev requirement in composer.json

### ISSUE THREAD

**Issue by gchtr** [timber/timber#1795]
Picking up on the comments in #1561.

We should probably make `phpcs` a dev requirement in **composer.json**. We already check for the coding standards in new pull requests, so it would make sense to have `phpcs` ready when somebody wants to contribute code and run code sniffing as well.

**Comment by jarednova** [comment]
Totally! Would that be something that runs in Travis? or is that another external integration (like Coveralls or Scrutinizer) that we'd need to setup?

**Comment by marciojc** [comment]
What about the wpcs?

**Comment by marciojc** [comment]
@jarednova and @gchtr about the phpcs, do you want to have all the files covered? 
As this https://github.com/marciojc/timber/commit/36286c561ef43ca98557b504e919b834268cfd2a?

**Comment by gchtr** [comment]
@jarednova I’m not sure. Here’s an example where they use it in Travis: <https://github.com/BracketSpace/Notification/blob/develop/.travis.yml>. But it could also be set up in Scrutinizer: <https://scrutinizer-ci.com/docs/tools/php/code-sniffer/>. I think we already discussed that in https://github.com/timber/timber/pull/1603#issuecomment-354039295.

@marciojc Yes, `phpcs` is supposed to be used with the WordPress Coding Standards. We have a custom config file (<https://github.com/timber/timber/blob/master/phpcs.xml>), where we try to stay as close to the WordPress Coding Standards as possible (see #1603). The standards are not applied to the codebase yet, though. We’ll do it in one bunch, before we release version 2.0. After that release, we want to be more strict about the standards. So, for the moment, we’d rather not have pull requests that fix coding standards in the code itself. **But!** The coding standards will also require DocBlocks to be complete and I like the work you did for the DocBlocks in https://github.com/marciojc/timber/commit/36286c561ef43ca98557b504e919b834268cfd2a 😎. We could really use some help for the inline documentation, there’s a lot that can be improved. Method summaries and descriptions, examples, type hints, parameter and return descriptions, etc. Would you be willing to help us there? I could give you some guidance about how it will be translated into the [Reference](https://timber.github.io/docs/reference/).

**Comment by marciojc** [comment]
@gchtr yes I can do the inline documentation. Is there a list of priorities?

**Comment by gchtr** [comment]
Closed by #1933.
