### ISSUE TITLE
Router : wrong redirection, showing image instead of the page

### ISSUE THREAD

**Issue by hatto** [timber/timber#1801]
Using Timber routes, I'm having trouble with certain links.

if the url contains same word as an image within wordpress media, the router will redirect me to the image url.

for example:
the link mysite.com/category/books/ where "books" is a slug of the category, it should redirect me to the detail page of the category.
except there is an image "Books.jpg" within the wp media, in that case it will redirect me to the 
mysite.com/wp-content/uploads/2018/09/Books.jpg.

as soon as I remove or rename the image, it works as it supposes to.

if I debug variables, everything's fine before the call Routes::load()

**Comment by hatto** [comment]
I'm posting it to Routes git, it's more suitable there

**Comment by jarednova** [comment]
@hatto — have you set-up custom links using the router, or are you saying that normal WP paths (like `mysite.com/category/books/`) are not working properly in their "default" WordPress state even w/o any custom pieces from you?

**Comment by hatto** [comment]
custom links using router
I have few links for categories for example
/category/books/
/category/cars/
/category/computer/
...

by calling Routes::Load() it works well, unless there is an image in wordpress with the name books.jpg. in this case the link /category/books/ will be redirected to the /wp-content/uploads/2018/09/Books.jpg

I've probably found a solution, so i created a pull request in the Router repo. it works for me now. 

in the case of same parameter as the image name, this action wasn't call
add_action('template_redirect', function(){...}
