### ISSUE TITLE
Get_field for ACF_block and Gutenberg

### ISSUE THREAD

**Issue by palmiak** [timber/timber#1818]
**Is your feature request related to a problem? Please describe.**
With ACF Blocks we can easily create blocks in Gutenberg - with Timber it's even easier, but ACF is now using `get_field` function in two way:
- for posts/users/terms it loads the data from meta - `{{ post.get_field( 'example' ) }}`
- for blocks it loads the block data - not avaiable in Timber right now

**Describe the solution you'd like**
I can think of 3 ideas:
- creating a global function {{ get_field( 'example' ) }}
```
public function add_to_twig( $twig ) {
        $twig->addFunction(new \Timber\Twig_Function('get_field', function( $field ) {
        return get_field( $field );
     } ));
return $twig;
}
```
and adding to constructor
`add_filter('timber/twig', array( $this, 'add_to_twig' ) );`
- let's just use `get_fields` like in my example in https://github.com/timber/timber/issues/1645#issuecomment-430037660 
- creating a `Block` object so it will work just like post or term object - than we could use it like this `{{ block.get_field() }}` 

and a very simple example:
```
<?php

namespace Timber;

use Timber\Core;
use Timber\CoreInterface;

class Block extends Core implements CoreInterface {

	public $PostClass = 'Timber\Block';
	public $TermClass = 'Block';

    public $block;

	public function __construct( $block ) {
        if( $block ) {
            $this->block = $block;
        }
	}

	public function __toString() {
		return $this->block_data['name'];
    }
    
    public function get_field( $key = '' ) {
        return self::meta( $key );
    }

	public function meta( $key ) {
        if( $key != '' && isset( $this->block['id'] ) && $this->block['id'] != '' ) {
            return get_field( $key, $this->block['id'] );
        }
    }
}
```
the callback:
```
function my_acf_bock_render_callback( $block ) {
    $context['block'] = new Timber\Block( $block );
    Timber::render( '/template-parts/block/content-testimonial.twig', $context );
}
```

and than in the block we can use this in twig file:
```
{{ block.get_field( 'testimonial' ) }}
```

The last solution looks more future proof. It will work at start and will be easy for other to add features.

**Describe alternatives you've considered**
All the alternatives are above.

**Comment by hrsetyono** [comment]
Thanks for sharing this. I was just testing ACF Block and stuck with the Timber integration.

I like the implementation with `Timber/Block`, but for now I will settle with global `get_field` temporarily.

My one major problem with ACF Block is how huge the fields and labels are. Also when in Preview mode, the fields are pushed to the sidebar and it become unusable especially if I have Repeater. What do you think on this issue?

**Comment by palmiak** [comment]
@hrsetyono you're right about the preview mode and sidebar, but on the other hand I really love that I can see how the block looks like (I'm sure that many of my client will love this feature too). I think there still a lot of work on the Gutenberg end in terms of usability and UX. ACF is just utilizing what Gutenberg has to offer.

**Comment by hrsetyono** [comment]
@palmiak I noticed that I can't save any fields that are inside Metabox.

I have also tested in fresh installation with no other plugins except ACF 5.8 and Gutenberg.

I will let the author know

**Comment by gillesgoetsch** [comment]
Thanks @palmiak for your work.

This is really exciting! I used to build something similar into the tinymce 3 years ago, with custom callbacks and timber rendering directly into the editor.

Here we go. I'm implementing this in a new and big project right now.
I want to use blocks for every single content-element in combination with acf and the preview-mode.
I will try to share the insights afterwards.

**Comment by palmiak** [comment]
Because of the upcoming changes with `get_fields` and integrations I rethinked this a bit and:
- first of all this should be a part of ACF Integration
- second of all - the `get_field` method should be removed

```php
<?php

namespace Timber;

use Timber\Core;
use Timber\CoreInterface;

class Block extends Core implements CoreInterface {

	public $PostClass = 'Timber\Block';
	public $TermClass = 'Block';

    public $block;

	public function __construct( $block ) {
        if( $block ) {
            $this->block = $block;
        }
	}

	public function __toString() {
		return $this->block_data['name'];
    }
    
	public function meta( $key ) {
        if( $key != '' && isset( $this->block['id'] ) && $this->block['id'] != '' ) {
            return get_field( $key, $this->block['id'] );
        }
    }
}
```

and the usage whould be
```twig
{{ block.meta( 'testimonial' ) }}
```

@gchtr what do you think about this?

**Comment by gchtr** [comment]
@palmiak Yeah, this should probably be part of the ACF integration!

I first had the same thought about changing the name of `get_field` to `meta`. But when this is a specific integration for ACF, it would be valid to keep the name `get_field`. However, when «accessing custom field values» is handled through `meta` in Timber, it would probably be better to call it `meta` here as well. So I’m good with not using `get_field` 👍. If we have proper documentation, this won’t be a problem.

When this class is specific to ACF, should we call it `ACF_Block` instead of `Block`? But then again, when this class is added to the ACF integration, it would probably live in the `Timber\Integrations\ACF` namespace, which would allow for calling it `Block` again:

```php
use Timber\Integrations\ACF\Block;

function my_acf_bock_render_callback( $block ) {
    $context['block'] = new Block( $block );

    Timber::render( 'block/content-testimonial.twig', $context );
}
```

**Comment by palmiak** [comment]
Ok, so I'll prepare PR for this. Which branch to use as a base one?

sob., 3 lis 2018, 12:40: Lukas Gächter <notifications@github.com>
napisał(a):

**Comment by gchtr** [comment]
@palmiak Sorry for the late reply! This is functionality that doesn’t really depend on 2.x, right? Except for the naming methodology, because as of 2.x, we only use `meta()` and not `get_field()`. But I still think it would be fine to make a pull request against the master branch for this.

**Comment by joelambert** [comment]
Just wondering if this was still active and whether it was targeting Timber v1?

We’re about to implement something on a project that would really benefit from the proposed `Block` class.

**Comment by palmiak** [comment]
@joelambert maybe try https://github.com/palmiak/timber-acf-wp-blocks it a library that makes using blocks much easier

**Comment by joelambert** [comment]
@palmiak thanks, that looks great!

We have a slightly different usecase so we’ll probably implement the above `Block` class in our app code in the first instance to test the implementation.

**Comment by Levdbas** [comment]
If someone wants to make a PR to implement this in Timber, or create an extension for Timber, feel free to do so.
