### ISSUE TITLE
Blank screen when trying to use Timber without composer

### ISSUE THREAD

**Issue by paulhuisman** [timber/timber#1821]
Hey guys,

I'm trying to setup a WordPress site without composer/autoload (in Plesk) but i can't get Timber to work.

The front-page keeps returning a blank screen.

I've done the following:

- Downloaded Timber 1.8.1 from Wordpress
- Enabled the plugin in the backend
- add `$timber = new Timber\Timber();` to functions.php
- edit front-page.php so it includes:

```
<?php
if ( ! class_exists( 'Timber' ) ) {
	echo 'Timber not activated. Make sure you activate the plugin in <a href="/wp-admin/plugins.php#timber">/wp-admin/plugins.php</a>';
	return;
}

$context = Timber::get_context();

$post = new TimberPost();
$context['post'] = $post;
Timber::render( [ 'front.twig' ], $context );
```

But i keep coming back to the blank page, i feel like i am missing something but don't know what :(

When i var_dump($timber) in functions.php it says:
`object(Timber\Timber)#3055 (0) { }`

**Comment by acobster** [comment]
Can you add `error_reporting(E_ALL);` to the top of front-page.php? It may also be helpful to enable [WP Debugging](https://codex.wordpress.org/Debugging_in_WordPress). Let us know what your site outputs after taking those steps.

**Comment by paulhuisman** [comment]
I think it might has to do with the templates location.

Is it true you can only set the templates locations when using composer?

`Timber::$dirname = 'templates';`

**Comment by acobster** [comment]
Without seeing some actual error messages it's impossible to say whether it has to do with template locations, or something completely different. I don't know of any reason it wouldn't be possible to change `$dirname` or add to context without having installed via composer. I almost always use the plugin installation approach.

You can use the `timber/context` filter to add to the context array. It's surprisingly not well-documented but there's an example [here](https://timber.github.io/docs/guides/menus/#setting-up-a-menu-globally).

Anyway, please follow the steps outlined in my last comment and we'll be better able to point you in the right direction. It's not possible to diagnose a White Screen of Death without a proper error message. :)

**Comment by paulhuisman** [comment]
Thanks!

I think I’ll be able to continue from here.

Op wo 17 okt. 2018 om 17:55 schreef Coby Tamayo <notifications@github.com>

**Comment by acobster** [comment]
Thanks @paulhuisman ! I'll consider this resolved. If you find evidence that this is actually a bug in Timber, feel free to reopen and post your repro steps. If you need further support for Timber usage, the best channel for that is stackoverflow using the [`timber` tag](https://stackoverflow.com/questions/tagged/timber). Thanks for using Timber!
