### ISSUE TITLE
Better documentation for timber/context filter

### ISSUE THREAD

**Issue by acobster** [timber/timber#1822]
**Is your feature request related to a problem? Please describe.**

In fishing around the docs for an example to post to #1821, I realized that the `timber/context` filter is not very well documented. It's a pretty fundamental concept, in my experience there's a use-case for it on pretty much every site I build, but the most concrete example I found was for [Setting up a menu  @globally](https://timber.github.io/docs/guides/menus/#setting-up-a-menu-globally), which does not make it clear that this is a general-purpose filter.

**Describe the solution you'd like**

I'd expect to see this in a Guide or on one of the Getting Started pages. [Theming](https://timber.github.io/docs/getting-started/theming/) is the best place for it IMO.

**Describe alternatives you've considered**

*Not* documenting it further?

**Additional context**

I'd add additional context if I knew how. See what I did there?

**Comment by gchtr** [comment]
Good thinking! It’s not very well documented in version 1 of Timber, but it will be in version 2 in a new [Context Guide](https://github.com/timber/timber/blob/2.x/docs/guides/context.md) as well as a filter description for `timber/context`:

https://github.com/timber/timber/blob/5101648dd78bdb0b3546864e6674cd284327af9c/lib/Timber.php#L323-L367

The documentation for version 2 will generate a separate Hooks section with an action and filter reference from the DocBlocks of filters. Here’s a preview for the context filter:

![bildschirmfoto 2018-10-17 um 18 11 06](https://user-images.githubusercontent.com/2084481/47100572-1d842080-d238-11e8-9899-b17a6d6a632e.png)

**Comment by acobster** [comment]
Brilliant! I'll close this out in that case, sounds like it's covered.

I did make a [small tweak](https://github.com/timber/timber/commit/1f0598b3753829995416b829482254bcdf3f5e2d) to the filter's doc comment, to use `Timber::context()` instead of the deprecated `get_context()`. I thought doing so through via the GH editor would create a PR from our fork, but I guess since I'm officially on the timber/timber repo now, it just committed directly on the 2.x branch. It's a tiny change but just thought I'd call that out since it didn't go through the normal flow, and I'll be more careful with that in the future! :stuck_out_tongue:
