### ISSUE TITLE
Deprecate Timber::fetch() and its filter timber_compile_result

### ISSUE THREAD

**Issue by jarednova** [timber/timber#1824]
The current behavior and function layering doesn't really do anything but add extra functions/filters. This should be simplified for 2.x

**Comment by palmiak** [comment]
I just took a look a this and have some questions:
- `timber_compile_result` won't have a replacement, as what needs to be filtered will be filtered in `compile` 
- why does render have both echo and return? I thought it's for tests but they use `ob_start();`

**Comment by jarednova** [comment]
**`timber_compile_result` won't have a replacement, as what needs to be filtered will be filtered in `compile`**
We'll definitely want to deprecate that filter, if only for its "old style" format. I think it makes sense to have _some_ filter for the output of the Twig compilation in there though

**Why does render have both echo and return? I thought it's for tests but they use `ob_start();`**
I think just the messiness of the paleolithic-era Timber cod. I can't think of any good reason to leave them there, can you? This seems like the right time to pull them out

**Comment by jarednova** [comment]
@palmiak is this a ticket you'd like to pick up?

**Comment by palmiak** [comment]
Of course - I'll have a WordCamp Nordic contributor's day to deal with this and some others I left :)
