### ISSUE TITLE
Deprecate custom debugging methods

### ISSUE THREAD

**Issue by jarednova** [timber/timber#1826]
- Deprecate debugging filters in Twig: https://github.com/timber/timber/blob/e7a2701be4f6d895ae5784787799a5b8f0e40cdb/lib/Twig.php#L208-L213

**Comment by acobster** [comment]
@jarednova so turns out `get_type()` is not a native PHP function...`gettype()` is. Which means the only time removing this will break anything is if people implemented their own `get_type()` function. Maybe we should just remove that filter?

**Comment by jarednova** [comment]
@acobster yeah, let's kill 'em. That means this has essentially been busted (and not documented, anyway) for years.

**Comment by acobster** [comment]
I was just talking about `get_type`, are you talking all three?

**Comment by jarednova** [comment]
Let's keep it at removing `get_type` for now. I think `get_class` is undocumented, but that's a story for another time
