### ISSUE TITLE
Timber seems to strip enqueued URL parameters (wp_enqueue)

### ISSUE THREAD

**Issue by a-camacho** [timber/timber#1831]
Hi everyone.

Since the last updates of Timber we see a problem in all our websites.
We use a combination of Wordpress + Timber + Elementor.

### Expected behavior
When some plugin or theme includes (enqueues) a CSS file with `wp_enqueue_style` the second parameter is the SRC of file. When giving a string with URL of script or CSS, it should be enqueued as it is.

We are using this code in theme : 
`wp_enqueue_style( 'google-fonts-99', 'https://fonts.googleapis.com/css?family=Mali' );`
Elementor is generating this line dynamically.

We are using `{{ function('wp_head') }}` to display wp_head.

### Actual behavior
When using an URL with parameters `(https://fonts.googleapis.com/css?family=Mali)` the URL is cutted after CSS (as soon as `?` appears). The same behaviour is seen of Elementor.

The problem is : the fonts can't be loaded anymore, so an error is showed in Chrome Inspector and fonts do not work if we do not include them manually.

The result is, the code included in source code looks like : `<link rel='stylesheet' id='google-fonts-99-css'  href='https://fonts.googleapis.com/css' type='text/css' media='all' />`. `?family=Mali` is missing.

### Steps to reproduce behavior
- Install last version of WP
- Install last version of Timber
- Enqueue style with `wp_enqueue_style` and with URL with parameters
- Check in source code if parameters were kept when output results

### What version of WordPress, PHP and Timber are you using?
Wordpress 4.9.8
Timber 1.8.1
Elementor 2.2.6

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Using last version from Wordpress Plugins Repository.

**Comment by a-camacho** [comment]
By the way, we just observed that this issue does not happen with Timber Starter Theme.
This should not be treated as a TImber issue.

Regarding this observed behaviour, if someone can give any clue about how to debug this.

Thank you very much.

**Comment by palmiak** [comment]
Hey @a-camacho 
 
I just tested this on a fresh Timber installation - it's definetly not Timber's fault. If I were you I would checked if there are extra filters connected with `wp_enqueue_scripts` - it looks a bit like this.

**Comment by palmiak** [comment]
I'm labelling it as 3rd party, because this is probably some plugin fault. Inform us if you'll find an answer.

**Comment by stljeff1** [comment]
I'd like to add to this. I had a similar problem where I was trying to add a version to my CSS includes (to prevent caching). IE:
`
    $v = 'v'.filemtime(get_stylesheet_directory() . '/site.css');
    wp_enqueue_style( 'site', get_stylesheet_directory_uri() . '/site.css', array(),  $v);
`

At first, I was using a child theme of Timber Starter Starter theme... Basically, the code was in my functions.php file (Well, I am using `require_once` to keep functions.php clean.) - I was enqueuing scripts and styles in the traditional WP way. The result was as OP described - resource was included in source code, but no version.

Then I stumbled on [this issue](https://github.com/timber/timber/issues/750), which shows how to enqueue scripts when Timber is initialized. After I changed my code to enqueue scripts / styles from inside Timber, the version for the enqueued resources were correctly showing in the source code.

**Comment by stljeff1** [comment]
I apologize, but please disregard everything I said in my previous post. The reason I did not see the version number on my enqueued resources was because I had a filter to filter them away.

`
  add_filter( 'style_loader_src', 'site_remove_wp_ver_css_js', 9999 );
  add_filter( 'script_loader_src', 'site_remove_wp_ver_css_js', 9999 );
`

Once I got rid of that, my versions started showing up. My apologies for my previous post.

However, now I see a version on all my styles and scripts, even when I explicitly set the version variable to false when enqueuing.

**Comment by Levdbas** [comment]
Thank you for the follow-up on your ticket! I will close this for now.
