### ISSUE TITLE
Parse error: syntax error, unexpected '[' 

### ISSUE THREAD

**Issue by vanekj** [timber/timber#1838]
### Expected behavior
It should display the website, but after upgrade it leads to an PHP error.

### Actual behavior
`Parse error: syntax error, unexpected '[' in /data/www/wp-content/plugins/timber-library/lib/ImageHelper.php on line 155`

Using an `array()` fixed the issue for me.

### Steps to reproduce behavior
Use the latest version of Timber when running an older PHP version (eg. 5.3 in my case)

### What version of WordPress, PHP and Timber are you using?
- WordPress 4.9.8
- PHP 5.3
- Timber 1.8.1

### How did you install Timber?
Upgraded to newest version via plugin updater in WordPress dashboard

**Comment by palmiak** [comment]
@vanekj I've created a pull request to fix this - https://github.com/timber/timber/pull/1839 . Check is this fixes your problem.

**Comment by vanekj** [comment]
Yep, this solution fixes the issue
