### ISSUE TITLE
ACF image in post object not returning proper value

### ISSUE THREAD

**Issue by Toxyc** [timber/timber#1840]
### Expected behavior
I expect the post object to return the proper image value as selected in ACF. And assign it to the context variable I selected for the post object as an attribute.

### Actual behavior
Instead it returns a string with what I assume is an ID. If I proceed to call another instance of .get_field('image'); on this post object it does return the proper return value.
All other attributes are properly returned, it's just the image field that seems to act in a strange way.

### Steps to reproduce behavior
Create custom post type with image field
Create ACF field post object within page

### What version of WordPress, PHP and Timber are you using?
Wordpress 4.9.8
ACF 5.8.0-beta2
Timber 1.8.1

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Upgraded to newest version via plugin updater in WordPress dashboard

**Comment by palmiak** [comment]
Try `{{ Image( post.get_field('image').src ) }}`

**Comment by Toxyc** [comment]
@palmiak Thanks for trying to help but I think you misunderstood the bug report.
I am able to get the image via using another instance of get_field, but this shouldn't be the case if I'm not mistaken. It should be assigned to the attribute with the proper value, so right now {{ employee.image }} returns string(2) "26" and the employee.get_field('image') returns the proper url that I require. 

``
{% for employee in employees %}
                    <div class="container-fluid no-padding">
                        <div class="row">
                            <div class="col-md-4">
                                <img src="{{ employee.get_field('image') }}" alt="{{ employee.name }} afbeelding">
                            </div>
                            <div class="col-md-8">
                                <strong>{{ employee.name }}</strong>
                                <p class="primary-color">{{ employee.job }}</p>
                                <ul>
                                    <li>
                                        <i class="fas fa-phone"></i>
                                        <a href="tel:{{ employee.phone }}" target="_blank">{{ employee.phone }}</a>
                                    </li>
                                    <li>
                                        <i class="fab fa-linkedin-in"></i>
                                        <a href="{{ employee.linkedin }}" target="_blank">Linked In</a>
                                    </li>
                                    <li>
                                        <i class="fal fa-envelope"></i>
                                        <a href="mailto:{{ employee.email }}" target="_blank">{{ employee.email }}</a>
                                    </li>
                                </ul>
                                <p>
                                    {{ employee.specialism }}
                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
``

And for relevance here is how I get the employees

``
    // Get all employees
    $args = array(
        'numberposts' => -1,
        'post_type' => 'employees'
    );
    $context['employees'] = Timber::get_posts($args);
``

**Comment by palmiak** [comment]
The best way is to return ID - it's the most universal way for the future usage. 

Why the post object get's the ID? Take a look at your DB - ACF stores image data as ID. But when you select return value to url than get_field converts the ID to url.

**Comment by palmiak** [comment]
@toxyc is everything clear and we can close the topic?
