### ISSUE TITLE
Idea: change escaping functions to use Twig filters

### ISSUE THREAD

**Issue by danielpost** [timber/timber#1848]
Currently, Timber implements custom WordPress escapers in the following way:

```
{{ my_content|e('wp_kses_post') }}
```

This works great when autoescaping is turned off. However, when autoescaping is enabled (which in my opinion should always be the case, but that's not relevant right now), Twig applies the default escaping strategy after applying the custom escaper, which leads to double escaping and wrong output.

To fix this, the escaper needs to be piped through the raw filter:

```
{{ my_content|e('wp_kses_post')|raw }}
```

This works, but feels wrong. Unfortunately, from my research there seems to be no way to mark custom escaper output as safe/raw. However, [it is possible to mark filter output as safe](https://twig.symfony.com/doc/2.x/advanced.html#automatic-escaping).

This means that it would be possible to implement the escapers we have in this way:

```
{{ my_content|wp_kses_post }}
```

To me, this better communicates intent and as a bonus is easier to write. Implementation would be trivial, and current escapers could be kept in place for backwards compatiblity. What do you think?

Note: this was [almost implemented](https://github.com/twigphp/Twig/pull/2441) in Twig itself but the PR was closed due to inactivity.

**Comment by danielpost** [comment]
@jarednova @gchtr Any thoughts on this?

**Comment by gchtr** [comment]
I think this is a cool idea! I agree with you that it’s way easier to write, and also to read. And it would make it easier for both developers who enable autoescaping and those who don’t. It would also be in line with #1787.

Do you want to add a pull request against the master branch for this?

**Comment by perruche** [comment]
👍  great idea !
