### ISSUE TITLE
Better debugging options

### ISSUE THREAD

**Issue by boris-djemrovski** [timber/timber#1852]
Lately I inherited a WP project which uses Timber, and at first I was pleasantly surprised with the possibilities it offers. But, the more I had to dig into the project and learn its structure, I am again surprised but not so pleasantly. The **only** option for debugging is `{{ dump() }}`?

My recommendation is to add support for two things:

1. When `WP_DEBUG` is set to `true`, make twig behave as it does in Drupal: add HTML comments before and after each template file loaded or included. It doesn't have to be suggestions, as it is not applicable here, but at least so we can know when one template file ends and where the next begins. When you work on the project you started, you know from the beginning what is where, but as I inherited a project with 100+ Twig files and no directory structure, it is really painful.

I tried to investigate if this is possible, but couldn't find a solution other that creating a helper function and manually pasting this at the beginning and the end of each Twig file:
`{{ fn('twig_begins', _self.templateName.__toString()) }}`
`{{ fn('twig_ends', _self.templateName.__toString()) }}`
This functions check if `WP_DEBUG` is set to `true`, and then echoes a HTML comment with the relative file path.

2. The second recommendation is to enable support for setting a `{{ breakpoint() }}` in Twig files, as it works with Drupal extension [Twig Xdebug](https://www.drupal.org/project/twig_xdebug)

**Comment by boris-djemrovski** [comment]
**Add HTML comments**
I am not really sure how to do this with a custom Twig Extension. I went through the TokenParser\Include and Node\Include, as well as Twig\Compiler and Twig\Parser, and I think I have a general picture how this works, but I don't know how to hook into this process. Since the `include` is not a function, it is a tag I believe, I don't know how to override it.

**Setting breakpoints in Twig**
Thank you Lukas! That actually works. I already tried using this extension, but with just autoloading it wouldn't work. I missed loading it into the `timber/twig` filter.

So, please do, add this to the Debug Guide! Thank you very much.

**Comment by boris-djemrovski** [comment]
I have just did it. I couldn't leave it alone, so I copied two Classes, `Twig_TokenParser_Include` and `Twig_Node_Include`, and with minimal changes added two `$compiler` commands to print something before and after every `include` tag. What isn't covered by Twig's documentation, we can easily override the Tags as well, which is great. So, when the `WP_DEBUG = true`, I add to twig my new `TokenParser` for `include` tag which overrides the default one.

How do you suggest I publish this? Do you want to include this in the Timber itself?

**Comment by gchtr** [comment]
> So, please do, add this to the Debug Guide! Thank you very much.

I will surely add this to the documentation! 👍

> I have just did it. I couldn't leave it alone, so I copied two Classes, `Twig_TokenParser_Include` and `Twig_Node_Include`, and with minimal changes added two `$compiler` commands to print something before and after every `include` tag.

So did you create a new extension for this? I think it would be a great addition to Timber! We could add it as a Twig Extension already included in Timber, that has to be activated in the same way as the breakpoint extension in the `timber/twig` filter. So something like this:

```php
add_filter( 'timber/twig', function( Twig_Environment $twig ) {
    $twig->addExtension( new Timber\Twig\Extension\IncludeComments() );

    return $twig;
} );
```

> How do you suggest I publish this? Do you want to include this in the Timber itself?

I think we should leave this as a separate extension, because it seems to me that this could also work Twig projects that don’t use Timber. It also makes it easier to maintain and release new fixes or versions.

I suggest you publish this in a new repository of yours and then add it to [Packagist](https://packagist.org/), in the same way as the [breakpoint extension](https://github.com/ajgarlag/AjglBreakpointTwigExtension) does it. We can then list it in the [Related Projects section](https://github.com/timber/timber#related-timber-projects) as well as in a new section in the [Debugging Guide](https://timber.github.io/docs/guides/debugging/). And you can earn all the fame 😉.

**Comment by boris-djemrovski** [comment]
I added it not as an extension, but as a TokenParser:

```PHP
if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
    add_filter( 'timber/twig', function( Twig_Environment $twig ) {
        $twig->addTokenParser( new Debug_Twig_TokenParser_Include() );

        return $twig;
    } );
}
```

Also, this doesn't cover the initial `Timber::render()` case, so I had to add additional filter to cover the template file as well:

```PHP
add_filter( 'timber/output', function( $output, $data, $file ) {
    return "\n<!-- Begin output of '" . $file . "' -->\n" . $output . "\n<!-- / End output of '" . $file . "' -->\n";
}, 10, 3 );
```

Agreed, I will notify you when I get this done. Thanks for the input. :)

**Comment by gchtr** [comment]
Hey, this is cool! Thanks for digging into this!

I guess when the `timber/output` filter is required, it won’t work with other Twig projects. But I still think that having this as a separate package is better.

> I added it not as an extension, but as a TokenParser

Okay, I think then you could still wrap this in an Extension: https://twig.symfony.com/doc/2.x/advanced.html#id4.

**Comment by boris-djemrovski** [comment]
Btw, I created a new package to make it easier when I want to use all of the debugging options... 😄 

It simply registers and applies all three Twig Extensions: dump, breakpoint, and commented includes.

I did it for myself, but feel free to include it in the documentation as well, if you think it is worth mentioning. 

https://github.com/djboris88/timber-debugger

**Comment by gchtr** [comment]
@boris-djemrovski I just added your package in #1891. I’m sure it’s going to help a lot of developers!

With this, I’m going to close this issue. Thanks again for digging into this and creating something that others can profit from, too! Very much appreciated! 🔥😎
