### ISSUE TITLE
WooCommerce Cart Not Emptying

### ISSUE THREAD

**Issue by bawpcwpn** [timber/timber#1862]
Hi, came across this issue on my Timber site, and managed to reproduce it in a clean setup. Can supply a repo if it would assist. Haven't been able to investigate further yet what the conflict is (suspecting some filter priority issue possibly), but this only happens on Timber themes and not default WP themes. 

### Expected behavior
The item is removed from the cart after checking out a $0 product, or product with 100% discount applied.

### Actual behavior
The item is not removed from the cart after checking out a $0 product or product with 100% discount applied. 

### Steps to reproduce behavior
1. Add item to the cart
2. Apply coupon of 100% discount
3. Checkout
4. Check cart to see if product is still there

### What version of WordPress, PHP and Timber are you using?
Wordpress 4.9.8
Timber 1.8.3
WooCommerce 3.5.1
Timber Starter Theme (https://github.com/timber/starter-theme)
PHP 7.1.23

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Upgraded to latest version via Wordpress Dashboard

**Comment by Levdbas** [comment]
Stale issue, closing
