### ISSUE TITLE
Consider adopting type declarations

### ISSUE THREAD

**Issue by acobster** [timber/timber#1863]
PHP 5.1+ allows for declaring arrays and class/interface names in method signatures, e.g.

```php
class Post {
  public function my_method( Post $post ) {
    return $post->meta('whatever');
  }

  public function other_method( array $data ) {
    return $data['some_index'];
  }
}
```

This results in much clearer error messages when the caller passes something other than the declared type. For example, **Uncaught TypeError: Argument 1 passed to Post::my_method() must be an instance of Post, null given** instead of **Uncaught Error: Call to a member function meta() on null.** Whereas the latter error tells the caller "there's an error happening somewhere in my_method()", which could imply a bug in the library code, the former says definitively "you're doing it wrong."

Another benefit is much greater leverage from PHPStan, which we've already adopted.

We should consider adopting this as much as possible across the Timber codebase for 2.0. A major upgrade is really the only appropriate time to do this, as this is fundamentally a breaking change.

Here are some changes we should consider making:

* Require PHP 7.3 or 7.4 (7.2 to be EOL'd November 2020)
* Nullable types in the top-level API/Factories - requires 7.1+, returning `null` instead of `false` in "unhappy path" situations, e.g. from `::get_post()` when no post found
* Declare types of object properties
* Declare `object` param types in certain Factory methods

All of this would be a pain to do manually, but with [Rector](https://github.com/RectorPHP/Rector) we might be able to automate a lot of this as outlined in #2339.

**Comment by gchtr** [comment]
I like this! Clearer error messages always help. And it’s probably better for code hinting in the various IDEs. Can we define some rules/guidance, when we would apply it?

- Would we apply it for all parameters that accept a single type only?
- Would we apply it for optional parameters?
- Would we apply it only for arrays and classes, or for [all types](https://mlocati.github.io/articles/php-type-hinting.html)?

If we use more types than arrays, classes or callables, then we will have to raise the minimum required PHP version for Timber to 7.0. I don’t know if we already defined this, but I think it would be the right step for 2.0 to drop support for PHP 5.x.

**Comment by acobster** [comment]
I looked and didn't find any prior discussion of increasing the minimum PHP version. I wasn't sure how far down that road folks would want to go, so I kept my proposal to types that 5.3 already supports. But if 7.x is on the table, I'm all for that. Would be curious to hear @jarednova's thoughts.

If we do go with 7.x, it's probably worth looking into annotating return types as well. This can be especially powerful in a library you're expecting people to extend, because it won't let them extend a method without returning the right thing.

To your questions, here's what I'm thinking:

* Yes, at least on public methods with single-type params. I wish we could apply it to all public methods, but PHP sadly doesn't support union types...
* Yes, for optional params you can specify a default of `null`, or for primitives like `string` you can also do things like set default to the empty string. I think this is flexible enough to meet our needs, although we might have to refactor in places to make it work.
* If we went with 7.x, I don't see any reason not to declare all the types we can.

**Comment by gchtr** [comment]
I think there wasn’t really a discussion prior to this.

We might have all heard it, but for completeness, I’m adding the link here: [WordPress will probably update the minimum PHP Version to 5.6](https://make.wordpress.org/core/2018/12/08/updating-the-minimum-php-version/.). The required PHP version might even be bumped to 7.0 by the end of 2019:

> Depending upon feedback and effectiveness, we can follow up by bumping the required PHP version to 7 as early as December 2019.

Because Timber is used mainly by developers, I think we would be safe to do this. If someone couldn’t use PHP 7.0 for some reason, there would still be Timber 1.x.

Your thoughts seem very reasonable to me. I didn’t work with return types yet. But in general, I think adding more type declarations will make error messages easier to understand, because there’s more information, am I right? So I fully agree when you say:

> If we went with 7.x, I don't see any reason not to declare all the types we can.

**Comment by pascalknecht** [comment]
@acobster I really second the typehints for the function. Whenever possible we should use interfaces there for good OOP style. The return types would also be great but are a little problematic as we cannot use void type and nullable types for php < 7.1. The typehints pull request would be an easy start for someone new to contribute.

**Comment by acobster** [comment]
@pascalknecht I agree about the nullable/void types, and 7.1 would probably be a little too aggressive. Also agree about using interfaces rather than concrete classes wherever possible. As for return types, my thought is to only annotate return types when we're sure we're going to return something other than `null`.

**Comment by gchtr** [comment]
Timber 2.0 will require PHP 7.0. So it should be clear which type hints we can add.

**Comment by szepeviktor** [comment]
When analyzing WP nav menu stuff use these two gems (classes)
https://github.com/szepeviktor/phpstan-wordpress/tree/master/example
There are the proper value objects.

**Comment by FlyingDR** [comment]
@jarednova @gchtr is there is any plans to raise minimum supported version for Timber 2.x to 7.1 or 7.2? Even 7.1 had reached its end of life [over a month ago](https://www.php.net/eol.php) and Wordpress itself [recommends 7.3](https://wordpress.org/about/requirements/) on its official site.

Having 7.1 as a minimum requirement will open ability for Timber to use [nullable types declaration](https://www.php.net/manual/en/migration71.new-features.php#migration71.new-features.nullable-types) that was major improvement into PHP types system over 7.0.

**Comment by jarednova** [comment]
@FlyingDR. Not immediately, but I'm very open to it.

Right now PHP 7.0 and 7.1 are used on about [25% of installed WordPress sites](https://wordpress.org/about/stats/). This factors into my thinking when it comes to stuff like adding nullable types. My order of operations right now is to get the current workload for 2.0 complete as soon as we can (some remaining stuff on factories, clean-up of overall formatting and a few other issues — we're damn close!). Then we can move on to things like type declarations and return types. If it becomes necessary to say 7.1, 7.2 or 7.3 and above only — I'm very open to those limitations (esp. since we're dropping plugin support)

**Comment by FlyingDR** [comment]
@jarednova Of course you know it better, but since it is new major version - it opens a possibility to uplift environment requirements. 

From same statistics it can be seen that over 30% of installs are running on PHP 5.x which will not be compatible with Timber 2.x anyway. It is also most likely true that new sites (that will utilize Timber 2.x) will be built using more recent versions of PHP. 

Moreover, since Wordpress supports definition of PHP version restriction - it is possible to use this feature to let sites that runs on new PHP versions to use new Timber and let sites that run on old versions of PHP to use older version of Timber.

**Comment by szepeviktor** [comment]
> Moreover, since Wordpress supports definition of PHP version restriction

WordPress :)

**Comment by acobster** [comment]
> My order of operations right now is to get the current workload for 2.0 complete as soon as we can....Then we can move on to things like type declarations and return types.

@jarednova you're still talking about before the official 2.0 release, right? (I agree that should be the order of operations.)

**Comment by acobster** [comment]
@jarednova also, do we have any data about what versions of PHP Timber is currently running on in production?

**Comment by jarednova** [comment]
@acobster I wish. WordPress doesn't give any kind of plug-in level breakdown that I could find, just the [platform-wide stats](https://wordpress.org/about/stats/). Packagist shows you a nice graph of daily installs ...

https://packagist.org/packages/timber/timber/stats

... but no further info on what environments those are in

**Comment by acobster** [comment]
@jarednova oh well, that's kinda what I figured.

Anyway, for the reasons brought up on #2093, I'm actually leaning towards requiring 7.1. That would give us nullable types and iterable, which is exactly what I'd want from the new public API. Lacking hard data, my sense is that Timber users are generally ahead of the WordPress curve, so I don't think it's a big ask over 7.0. There are also 7.0 end-of-life considerations. My priority is still getting factories out the door (I'm still chipping away!) but I'm throwing this out there as a suggestion.

**Comment by jarednova** [comment]
Yeah, Factories is still where the money's at right now; but I agree this could be a sensible follow-up from there to round-out the "clean up" of the API

**Comment by szepeviktor** [comment]
In PHP 7.4 we could also typehint properties. Please see #2339

**Comment by acobster** [comment]
> In PHP 7.4 we could also typehint class properties.

@szepeviktor I like this idea, and it would also help get a **lot** more value out of PHPStan. I've been slowly integrating it on Conifer and it has already found several bugs.

@jarednova @gchtr see updated issue description. These are pie-in-the-sky ideas and I want to come to a consensus.

**Comment by acobster** [comment]
PS I wish I could use union types right now. That would make my job a lot easier. :crying_cat_face:

**Comment by szepeviktor** [comment]
> found several bugs

👍

**Comment by szepeviktor** [comment]
Please consider writing Timber in PHP 7.4 and release it on PHP 7.*
See _Modern code in the repo_ #2339

**Comment by acobster** [comment]
@gchtr @jarednova any further thoughts about this? Any serious doubts about officially bumping the PHP requirement up to 7.4+?

**Comment by szepeviktor** [comment]
LGTM!

**Comment by gchtr** [comment]
@acobster Quite some passed has passed again. I think a good reference is always the [versions](https://www.php.net/supported-versions.php) page, where we see that active support for PHP 7.3 has already ended. The [WordPress requirements](https://wordpress.org/about/requirements/) lists PHP 7.4 as the recommended version as well. And as you said yourself in https://github.com/timber/timber/issues/2339#issuecomment-709600634, 7.4 isn’t such a big step from 7.3. So, I would **feel good about going with 7.4 for Timber 2.x**.

**Comment by jarednova** [comment]
I like as well — seems like a stable place to start from

**Comment by gchtr** [comment]
We already started using type declarations in lots of places in Timber and will add more in the future. Considering what this issue was initially about, I think we can close this.
