### ISSUE TITLE
Truncate filter does not work for character based languages

### ISSUE THREAD

**Issue by kirdia** [timber/timber#1874]
Truncate filter does not work for character based languages, even though excerpt filter (which uses wp_trim_words) works correctly.

Truncate and excerpt filters seems like providing identical funcionality, but I will open a PR to sync trim_words function with that of wp_trim_words

### Expected behavior
{{ '寒くなってきましたね。14日には北海道でも記録的に遅い初雪が降ったそ'|truncate( 5, true ) }}

Output:
寒くなってきましたね。14日には北海道でも記録的に遅い初雪が降ったそ… 

### Actual behavior
Output:
寒くなって… 

### What version of WordPress, PHP and Timber are you using?
WordPress 4.9.8, PHP 7.0.28, Timber 1.83

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by jarednova** [comment]
Some questions were left on #1875

**Comment by jarednova** [comment]
I've merged a test into `master` through #1880 that confirms that `truncate` and `wp_trim_words` are currently in-sync. 

@kirdia I'd love your feedback on whether the output is correct based on the rules for WP and East Asian languages in the newest version

**Comment by Levdbas** [comment]
Since we haven't heard back from the reporter, I will close this issue.
