### ISSUE TITLE
Add `$post_template` to `Timber\Post`

### ISSUE THREAD

**Issue by hacknug** [timber/timber#1879]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to access de post's selected template from inside my Timber views.

**Describe the solution you'd like**
`Timber\Post` should include `$post_template` to allow theme authors to do stuff conditionally based on the template selected on the post's Page Attributes. This feature is available for all post types (not just pages like it was a while ago).

**Describe alternatives you've considered**
- Passing a string to my context containing the slug of the template the current post is using `str_replace( get_template_directory() . '/', '', get_single_template() )` (this returns the equivalent of `get_page_template_slug()` no matter the post type since there's no `get_single_template_slug()` method available)
- Passing a boolean to my context using WordPress' `is_page_template( 'templates/about.php' )`.

**Comment by palmiak** [comment]
Hi could you provide an example how do you think it should work.

I think I get it but I would like to be sure.

wt., 18 gru 2018, 22:25: Jesse Janowiak <notifications@github.com>
napisał(a):

**Comment by hacknug** [comment]
Single posts can be set to use a pre-defined post-template.

I have a Contact post-template for pages. If the current page is using this template it should add some elements after the post's content.

This is what I added to my `functions.php`:

```php
if ( ! function_exists( 'get_single_template_slug' ) ) {
	function get_single_template_slug() {
		return str_replace( get_template_directory() . '/', '', get_single_template() );
	}
}
```

This is what I pass to my context:
```php
$context['template'] = get_single_template_slug();
```

And this is how I use it on my template:

```twig
{% if template == 'templates/contact.php' %}
  <div>My conditional content would go here</div>
{% endif %}
```

**Comment by hacknug** [comment]
That function only works for the post-type page. WordPress supports templates for all post types but only provides `get_single_template()` and not the equivalent for `get_page_template_slug()` but core functions are outside of the scope of this issue.

Extending `Timber\Post` seems a better alternative to what I had in place but I still think this should be added since it's something everyone would benefit from and as useful to have around as `$post_type` and other post properties.

Thanks for your insight and the snippet!

**Comment by palmiak** [comment]
The docs says Get the specific template name for a page or any post type.
So it should work. The template name is kept in meta so the the post type
shouldn't matter. Of course that's theory. I'll try to check this later

śr., 19 gru 2018, 16:41: Nestor Vera <notifications@github.com> napisał(a):

**Comment by hacknug** [comment]
It does work. I was only suggesting to add this to `Timber\Post` so no one ever has to add this manually to their templates.

The only reason I suggested adding `str_replace( get_template_directory() . '/', '', get_single_template() )` instead of simply using `get_single_template()` was so theme developers don't have to write the full path to the template or split the string or anything like that.

**Comment by gchtr** [comment]
I think it makes sense to add a new `template()` method to `Timber\Post` for this 👍. Until now, I always used `$post->_wp_page_template` for this, but it does feel a little dirty. There should be a proper way to do this in Timber.

@palmiak Your example looks good! Do you want to go ahead and create a pull request for this?

**Comment by Levdbas** [comment]
Do we still considering this in Timber @gchtr ? In a Gutenberg era this might be less relevant.

**Comment by gchtr** [comment]
@Levdbas I think you’re right here. With the block editor, page template are surely less relevant. For developers who still want to have a function that works better for them, they can [extend Timber](https://timber.github.io/docs/v2/guides/extending-timber/) by using a solution proposed in https://github.com/timber/timber/issues/1879#issuecomment-448634392.

I’m going to close this for now.
