### ISSUE TITLE
`list` filter forces a space before its `second_delimiter`

### ISSUE THREAD

**Issue by hacknug** [timber/timber#1887]
### Expected behavior
The `list` filter shouldn't impose users to have spaces around the `second_delimiter`. This would allow us to have all strings separated by a single comma or support formatting like the Oxford comma and such. Right now it's too opinionated without any option to opt-out of this behavior.

### Actual behavior
The `list` filter forces one space before the `second_delimiter`: https://github.com/lggorman/timber/blob/master/lib/Twig.php#L315

### Steps to reproduce behavior
Try using the `list` filter passing a comma (`,`) as the second argument.

### What version of WordPress, PHP and Timber are you using?
Latest everything. Unrelated to the issue.

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WordPress.org. Unrelated to the issue.

**Comment by jarednova** [comment]
Totally agree! This seems like a quick fix if you're interested (or someone else watching this thread) is interested in submitting a PR!
