### ISSUE TITLE
Wrong URL from URLHelper::file_system_to_url

### ISSUE THREAD

**Issue by iSenne85** [timber/timber#1895]
In the file URLHelper.php there is a piece of code that should get the URL to an image:

```
public static function file_system_to_url( $fs ) {
    $relative_path = self::get_rel_path($fs);
    $home = site_url('/'.$relative_path);
    $home = apply_filters('timber/URLHelper/file_system_to_url', $home);

    return $home;
}
```

This function returns the site_url('/'.$relative_path);, but that is not always the same as where the content_url() is specified.

Using version: 1.8.3

**Comment by palmiak** [comment]
As I understand - if you set the content url to different directory the function above return wrong $url.

**Comment by palmiak** [comment]
For a quick workaround - as you see there is a filter - maybe try using it.

**Comment by iSenne85** [comment]
@palmiak Already did, so no hurry :)

**Comment by Levdbas** [comment]
I think this is out of scope for Timber itself and since there is a filter available there is a workaround available.
