### ISSUE TITLE
Pagination 404 error for single-cpt.php but not for archive-cpt.php

### ISSUE THREAD

**Issue by myicicle** [timber/timber#1906]
I can use Timber pagination in archive-law.php for the archive page (/law/page/2) of my custom post type, "law", but with the same codes in single-law.php, the second page (/law/cpt-post-slug/page/2) shows the 404 error. How can I fix that?

**Comment by gchtr** [comment]
Hey @myicicle 

That’s how it’s supposed to work. Pagination only works for archive templates like `archive.php` or `home.php`, where you have a query with multiple results that can be paginated. It will not work for singular templates like `single.php`.

**Comment by gchtr** [comment]
Let’s continue this [over on StackOverflow](https://stackoverflow.com/questions/54188776/pagination-works-for-archive-of-cpt-but-throws-404-error-for-single-cpt-php/54206603) if there are further questions.
