### ISSUE TITLE
Gutenberg: Nested calls to Post::content() cause wpautop filter to be enabled again

### ISSUE THREAD

**Issue by gchtr** [timber/timber#1907]
This is a bug when working with Timber and Gutenberg.

Some background first: Gutenberg removes the `wpautop` filter when it renders content that contains Gutenberg blocks: https://github.com/WordPress/gutenberg/blob/14aa7d7d8adf4a3683bdaaf6a7cf154cd598f5fd/lib/blocks.php#L179-L182. After the blocks are parsed, Gutenberg adds the filter back through `_restore_wpautop_hook()`. The description of that function explains what it does:

> If do_blocks() needs to remove wpautop() from the `the_content` filter, this re-adds it afterwards, for subsequent `the_content` usage.

In Timber, we get the content through `{{ post.content }}`. When anything in that content calls `Timber\Post::content()` again, it will re-apply the `wpautop` filter too early, causing the whole content of the post to be «auto-peed».

So, for example, if you have a block that renders a list of posts (e.g. a latest posts block) that contain a preview generated through `Timber\PostPreview`, that preview might call `$post->content()` to fetch a posts content to generate the preview. After all content filters are applied, it will call `_restore_wpautop_hook()`, causing `wpautop` to be activated again, which then causes your the HTML of the outermost call to `{{ post.content }}` to be wrapped in `<p>` tags. This leads to very unexpected results and seemingly random `<p>` tags, that the browser doesn’t know how to handle.

For now, I can circumvent the issue by removing the `wpautop` filter globally.

```php
remove_filter( 'the_content', 'wpautop' );
```

This only works well if Gutenberg is enabled for all post types. However, if somebody needs to enable Gutenberg only for some post types, this should be solved differently.

**Comment by palmiak** [comment]
@gchtr could you provide me with a block that can cause this bug? I would test it a bit.

**Comment by gchtr** [comment]
Sorry, very busy right now… But I saw that others reported the same issue with different use cases over at https://github.com/WordPress/gutenberg/issues/12530. A better workaround than mine can be found in https://github.com/WordPress/gutenberg/issues/12530#issuecomment-443736873.

Let’s wait for the resolution of the issue in the Gutenberg repo.

**Comment by csalmeida** [comment]
I have also experienced this issue an used @gchtr's suggestion as a fix for now. It seems adding `<p>` tags was on preview used to be a bug #748 sometime ago and got patched, although I'm not sure if it was happening for quite the same reason.

```
// functions.php
remove_filter( 'the_content', 'wpautop' );
```

**Comment by gchtr** [comment]
That issue was resolved in https://core.trac.wordpress.org/ticket/45495 and made it into WordPress 5.2.
