### ISSUE TITLE
Add title attribute to 'read more' link in get_preview

### ISSUE THREAD

**Issue by crzzano** [timber/timber#1911]
Pretty straightforward. I think the read more link generated by get_preview should include a modifiable title attribute with the post name as the default value, for SEO purposes.

**Comment by palmiak** [comment]
Hi 

From what I see the get_preview function is deprecated - you should use https://timber.github.io/docs/reference/timber-postpreview/ . You can use it like this:
```{{ post.preview.length(10).read_more('More!') }}```

**Comment by twocatszerokarma** [comment]
Thanks. I don't think that addresses the lack of support for the title attribute though.
