### ISSUE TITLE
`term.posts` not sorted by `menu_order` by default

### ISSUE THREAD

**Issue by hacknug** [timber/timber#1917]
I'm using `Timber::get_terms` to get non-empty terms for a given taxonomy. Each one of those terms is correctly sorted (given their `menu_order`). After looping over this, I need to print the posts using the current term. This is were things don't work _as expected_.

Somewhat related to #1366 maybe?

### Expected behavior
I'd expect `work.posts` to be returned according to their `menu_order` just like the default WP_Query would do when using one of these plugins:
- https://es.wordpress.org/plugins/intuitive-custom-post-order/
- https://es.wordpress.org/plugins/simple-custom-post-order/

### Actual behavior
Returned posts are ordered by some other parameter, I guess it must be because the class has some kind of default arguments in case they're not provided.

### Steps to reproduce behavior
Here's a simplified version of what I'm doing:

```php
$data['works'] = Timber::get_terms(
	array(
		'taxonomy'   => 'category',
		'hide_empty' => true,
	)
);
```

```twig
{% for work in works %}
    <ol>
        {% for project in work.posts %}
            <li>{{ project.title }}</li>
        {% endfor %}
    </ol>
{% endfor %}
```

### What version of WordPress, PHP and Timber are you using?
WordPress 5.0.3, PHP 7.2, Timber 1.8.4.

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Upgraded to newest version via plugin updater in WordPress dashboard.

**Comment by palmiak** [comment]
There is a way to make it working:
```
public function posts( $numberposts_or_args = 10, $post_type_or_class = 'any', $post_class = '' ) {
	return $this->get_posts($numberposts_or_args, $post_type_or_class, $post_class);
}
```

so you can pass `$args` to this method:
```
{% for work in works %}
    <ol>
        {% for project in work.posts( ARGS_GOES_HERE ) %}
            <li>{{ project.title }}</li>
        {% endfor %}
    </ol>
{% endfor %}
```

**Comment by gchtr** [comment]
I just had exactly the same use case this morning. But I had no problems using the [Simple Custom Post Order](https://wordpress.org/plugins/simple-custom-post-order/) plugin. When I change the menu order for the posts, they appear in the correct order when looping with `$term->posts()`.

There could be something that affects the query. I’ve found that this is usually very specific to a project. It could be a plugin that is not working well with Timber. If you can find out what exactly it is that’s breaking the order, that would help a lot. Timber does some things that breaks compatibility and we are trying to make it better. But we’d need a case that we can reproduce and test.

@palmiak I think there’s no way we can provide arguments used in the query, except for the **number of posts** and the **post type**. So it’s not possible to provide the `orderby` argument for the query that would be needed for this. Or am I missing something?

Thinking of this, I guess this is pretty much the same case as https://github.com/timber/timber/pull/1845, where we updated the "opposite" function (getting the terms for a post) to make it possible to have full control over the query. Going forward, I would refactor the `Term::posts()` function to make it easier to control what it’s doing.

**Comment by palmiak** [comment]
```
$args = $numberposts;
$new_args = array();
parse_str($args, $new_args);
$args = $new_args;
$args['tax_query'] = $default_tax_query;
if ( !isset($args['post_type']) ) {
	$args['post_type'] = 'any';
}
```

or 

```
//they sent us an array already baked
$args = $numberposts;
if ( !isset($args['tax_query']) ) {
	$args['tax_query'] = $default_tax_query;
}
if ( class_exists($post_type) ) {
	$PostClass = $post_type;
}
if ( !isset($args['post_type']) ) {
	$args['post_type'] = 'any';
}
```

I think that we can pass all the parameters. I of course I'm writing this during my coffee break without testing, but in theory it should be ok. Correct me if I'm wrong.

I'll investigate a bit more after work how the plugins work and why they won't work with Timber by default.

**Comment by gchtr** [comment]
@palmiak Oh yeah, now I see 🙈! I guess I only saw `$numberposts` for `Term::get_posts()` and thought that was the only thing it accepts.

In that case, I think we should make it more clear that arguments can be passed directly. I’ll take care of adding more documentation for this 👍.

Of course that doesn’t solve the issue that it should work without passing in any special arguments.

**Comment by Levdbas** [comment]
Documentation was updated related to this issue and solutions provided in the second reply. Closing this.
