### ISSUE TITLE
Adding data to context within foreach

### ISSUE THREAD

**Issue by Infini7y** [timber/timber#1919]
Hey, that was actually a bit of a trick, sorry. Please post your question to [StackOverflow](http://stackoverflow.com/questions/tagged/timber) using the Timber tag. To help us keep (or start to keep) the Issues section a bit cleaner, we're going to close support question-ish issues. StackOverflow is the best place for these — thanks!

**Comment by gchtr** [comment]
Hey @Infini7y, you didn’t actually post an issue here. If you have a support question, please post it on [StackOverflow](https://stackoverflow.com/questions/tagged/timber).
