### ISSUE TITLE
Batch not dividing to n "columns" but by n "items"

### ISSUE THREAD

**Issue by twentyfortysix** [timber/timber#1920]
Is this a support or usage question? Please post to [StackOverflow](http://stackoverflow.com/questions/tagged/timber) using the Timber tag

### Expected behavior
So I have 5 items and want to break them in to 3 columns like so

```
{% for row in view.courses|batch(3) %}
	<div class="col-md-4">
		{% for course in row %}
			<div class="in">
				<h3>
					{{ course.title }}
				</h3>
			</div>
		{% endfor %}
	</div>
{% endfor %}

```

### Actual behavior
But instead of heaving 3 columns like this
1 | 2 | 3 |
4 | 5 |

I got this:
1 | 2 |
3 | 4 |
5 |

which kinda makes sense. but that is not what it should do, it should break "any" number items into 3 columns

### What version of WordPress, PHP and Timber are you using?
WP 5.0.3 
Timber 1.8.4

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
from WP repository

**Comment by twentyfortysix** [comment]
this is returning expected result

```
{% set CoursesPerColumn = (view.courses|length / 3)|round(0, 'ceil') %}
{% for course in view.courses %}
	{% if loop.index0 == 0 %}
		<div class="col-md-4">
	{% elseif (loop.index0 is divisibleby(CoursesPerColumn)) %}
		</div><div class="col-md-4">
	{% endif %}
		<h3>
			{{ course.title }}
		</h3>
	{% if loop.last %}
		</div>
	{% endif %}
{% endfor %}
```

1 | 2 | 3 |
4 | 5 |

**Comment by palmiak** [comment]
Maybe I don't know the whole context but you don't need `batch` in your example.
```
{% for row in view.courses %}
	<div class="col-md-4">
		<div class="in">
			<h3>
				{{ row.title }}
			</h3>
		</div>
	</div>
{% endfor %}
```

CSS will take care of this.

**Comment by twentyfortysix** [comment]
Actually CSS in not enough in this case. as the result should be sort of masonry like layout.
But that doesn't matter anyway.
The point is that the batch is not dividing content in to n defined chunks, but rather output batches with the defined number of items.

The https://twig.symfony.com/doc/2.x/filters/batch.html description is misleading as well.
