### ISSUE TITLE
Deprecate remaining update() methods

### ISSUE THREAD

**Issue by jarednova** [timber/timber#1921]
As documented on the [2.0 Project](https://github.com/timber/timber/projects/4), we're fully deprecating `update` methods. Why? They were never fully implemented leaving them only to cover metadata and nothing else. Timber is primarily a "read" tool (cleaner themes/templates and what not) — "fixing" how WP handles the create/update/delete process is literally 3x the scope

**Comment by chrisvanpatten** [comment]
Also very easy to add yourself — in a way that makes sense for each use-case — by extending Timber's models :)

**Comment by jarednova** [comment]
that too!

**Comment by jarednova** [comment]
Closed by #1922
