### ISSUE TITLE
`URLHelper::is_external` not working for URLs without protocol

### ISSUE THREAD

**Issue by hacknug** [timber/timber#1924]
### Expected behavior
`URLHelper::is_external` returns false for external URL's with no protocol.
- `URLHelper::is_external('//github.com/')` => true
- `URLHelper::is_external('https://github.com/')` => true

### Actual behavior
- `URLHelper::is_external('//github.com/')` => false
- `URLHelper::is_external('https://github.com/')` => true

### Steps to reproduce behavior
```php
var_dump( Timber\URLHelper::is_external( '//github.com/' ) );       // false
var_dump( Timber\URLHelper::is_external( 'http://github.com/' ) );  // true
var_dump( Timber\URLHelper::is_external( 'https://github.com/' ) ); // true
```

### What version of WordPress, PHP and Timber are you using?
WordPress 5.0.3, PHP 7.2, Timber 1.8.4.

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Upgraded to newest version via plugin updater in WordPress dashboard.

**Comment by palmiak** [comment]
I took a look at the code and your are right. I think we need to change checking for `http` to checking for `array('//', 'http')` at the beginning of the url.

If you would like to make a pull request it would very appreciated.

**Comment by hacknug** [comment]
Sure thing! Will open a PR with the changes today, just wanted to make sure it made sense to change this.

**Comment by palmiak** [comment]
Great, thanks.
