### ISSUE TITLE
Problems with Loco Translate configuration because of en_US.po file

### ISSUE THREAD

**Issue by dariokueffer** [timber/timber#1926]
The file en_US.po in timber/tests/assets/languages/ disturbs the configuration in the Loco Translate plugin.

**Comment by gchtr** [comment]
You can use the [**Blocked paths**](https://localise.biz/wordpress/plugin/manual/bundle-config#exclude) option in the **Advanced** settings of the bundle settings in Loco:

> #### Blocked Paths
> 
> This is a list of locations that will be excluded across all projects in the bundle. It's useful for adding folders you never want to search for anything, such as "vendor" or "node_modules". Note that Loco automatically blocks all "dot files" so ".git" and ".svn" will never be scanned.

So, for example, when Timber is located in the **vendor** folder of your theme, you can use the following setting for **Blocked paths**:

```
vendor
```

**Comment by dariokueffer** [comment]
Nice, Thank you very much.
