### ISSUE TITLE
Question: Performance tricks for timber?

### ISSUE THREAD

**Issue by stefanos82** [timber/timber#1935]
I have downloaded two themes from @laras126's profile, her [website](https://github.com/laras126/notlaura.com)'s and [karenmcgrane](https://github.com/laras126/karenmcgrane)'s.

I have noticed that both of them have a slow response for each URL with a TTFB twice or even sometimes thrice times slower than a standard designed theme.

Is there anything I could do to match the traditional loop's performance?

I'm just learning Timber, I found it last week and I'm experimenting with it.

Any feedback would be greatly appreciated.

Cheers.

**Comment by laras126** [comment]
@stefanos82 That might not be Timber related issues - both of those themes were originally built several years ago, so I can't say for sure what's going on. It could be due to inefficient queries that are outside Timber's responsibility. 

Have you taken a look at this documentation? https://timber.github.io/docs/guides/performance/

**Comment by stefanos82** [comment]
I haven't reached that part of docs yet, but I'm getting there. Do you have any updated demo you could share so I could experiment with it? It's really nice to use my existing Django / Flask template knowledge to WordPress theme development.

**Comment by palmiak** [comment]
@stefanos82 I would recommend using https://wordpress.org/plugins/query-monitor/ (or similar tool) - with this you'll see what is having the biggest impact on site speed.

**Comment by stefanos82** [comment]
I do use it, but it doesn't work due to an error the theme causes to the plugin:

![image](https://user-images.githubusercontent.com/1777466/53914448-4af62d00-4066-11e9-85ee-55318ef6d950.png)

From inside the dashboard the plugin works as expected.

**Comment by palmiak** [comment]
I see few causes of this error:
- do you have wp_head and wp_footer functions in your header footer?
- maybe you used jquery directly in the theme not by enqueue_script
- maybe some plugin or code is disabling jquery from loading?

**Comment by stefanos82** [comment]
I didn't use or edit anything myself. All I did was to download the theme and activate it, that's all.

For the moment I'm just reading the source code and taking notes, nothing more.
