### ISSUE TITLE
PHP Catchable fatal error:  Object of class WP_Error could not be converted to string

### ISSUE THREAD

**Issue by hrsetyono** [timber/timber#1937]
## Steps to reproduce behavior

I don't know how to reproduce, but here's the story:

**Suddenly my site become only plain text**, no CSS, no JS. But WP-Admin works fine.

I disabled all plugins and the site works (with Twentyseventeen theme). Then I proceed to reactivating them one by one to see. But after all is reactivated, no more error and the site works fine just like before.

## What version of WordPress, PHP and Timber are you using?

- WordPress 
- Timber 1.8.4
- PHP 5.6.40

My hosting is [INMOTION](https://www.inmotionhosting.com/) with this specs:

| Hosting Package | default
| -- | --
| Server Name | vps36227 |
| cPanel Version | 78.0 (build 13) |
| Apache Version | 2.4.38 |
| PHP Version | 5.6.40 |
| MySQL Version | 10.2.22-MariaDB |
| Architecture | x86_64 |
| Operating System | linux |
| Shared IP Address | 172.81.119.xxx |
| Path to Sendmail | /usr/sbin/sendmail |
| Path to Perl | /usr/bin/perl |
| Perl Version | 5.16.3 |
| Kernel Version | 3.10.0-042stab127.2 |

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

From WordPress dashboard

## Cause of Error

I checked the **Error Log** and saw tons of these errors:

```
PHP Catchable fatal error: 
Object of class WP_Error could not be converted to string in
/home/mysite/public_html/mysite.com/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Environment.php(462) : eval()'d code on line 58
```

Followed by occasional Memory limit error:

```
PHP Fatal error: 
Allowed memory size of 67108864 bytes exhausted (tried to allocate 81 bytes) in
 /home/mysite/public_html/mysite.com/wp-includes/functions.php on line 5213
```

I believe Memory limit is the reason why the site became broken. But I'm not sure whether Timber's bug is related to it.

But I still want to fix the Timber's bug because I still get that message every few minutes in my Error Log.

Anyone else experience this before?

Thanks

**Comment by jarednova** [comment]
@hrsetyono thanks for providing such thorough information. From the looks of it, something in the WP/PHP layer is triggering an error which Twig is trying to output in one of your templates (something within `{{ }}`). Because the error can't be converted to a string you get a fatal.

Take a look and see if there's a specific theme PHP or Twig file listed in the error stack. You might have to narrow in on the specific chunk using a [wolf fence](http://coreygoldberg.blogspot.com/2008/12/wolf-fence-debugging.html)

**Comment by hrsetyono** [comment]
Hi thanks for the reply!

Just for an update, I have narrowed out the cause of the error. It's apparently the **WP Super Cache plugin.** 

When I reactivated WP Super Cache, the setting is set to off. After turning it on, I get that same error.

So the Twig error is not related to my site being broken. But I will still check what cause it using wolf fence.
