### ISSUE TITLE
asm89 throwing exception after update twig/twig to 2.7.0

### ISSUE THREAD

**Issue by andrejpavlovic** [timber/timber#1950]
## Expected behavior
Normal rendering of wordpress template.

## Actual behavior
Fatal error: Declaration of Asm89\Twig\CacheExtension\TokenParser\Cache::parse(Twig_Token $token) must be compatible with Twig\TokenParser\TokenParserInterface::parse(Twig\Token $token) in vendor\asm89\twig-cache-extension\lib\Asm89\Twig\CacheExtension\TokenParser\Cache.php on line 59

## Steps to reproduce behavior
composer require twig/twig:2.7.0

## What version of WordPress, PHP and Timber are you using?
PHP 7.1.11, WP 4.9.9, Timber 1.9.1

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by gchtr** [comment]
Yep, saw that, too. Twig v2.7 was just released today. This error doesn’t seem to be caught by our tests, because when I ran them after the release, they looked find. Looks like this is related to #1941.

Because this is related to the https://github.com/asm89/twig-cache-extension dependency, we maybe need to file an issue there.

For everyone who runs into this issue and wants to fix it temporarily, use:

```
composer require twig/twig:~2.6
```

@jarednova Should we restrict the Twig version to `~2.6` in Timber’s composer.json and release a hotfix in the meantime?

**Comment by jezemery** [comment]
@gchtr problem there is that it now conflicts with the roave/security-advisories package due to vulnerabilities.

**Comment by palmiak** [comment]
Btw I see there is https://github.com/twigphp/twig-cache-extension which is almost the same but it looks like this should be the official one (https://github.com/twigphp/twig-cache-extension/commit/cdea66eccd13d9d20fb745df7d7d7ca7136bd9fa).

**Comment by pascalknecht** [comment]
Just ran into this problem too. We definitely need to lock the package to 2.6 until this is resolved. 
@jezemery Can you please elaborate further what you mean with that conflict?
@jarednova can you do this.

**Comment by jezemery** [comment]
I've looked. This issue can be resolved by replacing the deprecated instances of Twig_TokenParser in \Asm89\Twig\CacheExtension\TokenParser\Cache.php with instances of AbstractTokenParser.
End result looks like 
`<?php

/*
 * This file is part of twig-cache-extension.
 *
 * (c) Alexander <iam.asm89@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Asm89\Twig\CacheExtension\TokenParser;

use Asm89\Twig\CacheExtension\Node\CacheNode;
use Twig\Token;
use Twig\TokenParser\AbstractTokenParser;

/**
 * Parser for cache/endcache blocks.
 *
 * @author Alexander <iam.asm89@gmail.com>
 */
class Cache extends AbstractTokenParser
{
    /**
     * @param Token $token
     *
     * @return boolean
     */
    public function decideCacheEnd(Token $token)
    {
        return $token->test('endcache');
    }

    /**
     * {@inheritDoc}
     */
    public function getTag()
    {
        return 'cache';
    }

    /**
     * {@inheritDoc}
     */
    public function parse(Token $token)
    {
        $lineno = $token->getLine();
        $stream = $this->parser->getStream();

        $annotation = $this->parser->getExpressionParser()->parseExpression();

        $key = $this->parser->getExpressionParser()->parseExpression();

        $stream->expect(Token::BLOCK_END_TYPE);
        $body = $this->parser->subparse(array($this, 'decideCacheEnd'), true);
        $stream->expect(Token::BLOCK_END_TYPE);

        return new CacheNode($annotation, $key, $body, $lineno, $this->getTag());
    }
}
`

**Comment by jezemery** [comment]
Problem is that the maintainer appears to be no longer active.
I'm happy to rewrite this package, however the dependencies within Timber would need to be updated. Would this be possible?

**Comment by jezemery** [comment]
> Just ran into this problem too. We definitely need to lock the package to 2.6 until this is resolved.
> @jezemery Can you please elaborate further what you mean with that conflict?
> @jarednova can you do this?

`roave/security-advisories` is a composer package which reduces security problems by auto-conflicting with package versions which have known vulnerabilities. https://github.com/Roave/SecurityAdvisories

**Comment by pascalknecht** [comment]
I think we should probably change to a supported version of the cache extension. Probably a change to https://github.com/twigphp/twig-cache-extension would be a good idea.

My idea for an action plan:
1) Release a quickfix for Timber with a fixed Twig Version 2.6
2) Drop the `asm89/twig-cache-extension` and replace it with `twigphp/twig-cache-extension` (Needs checking if this breaks backwards compatibility). Reupdate Twig to version 2.7 (but leave it locked just in case something like this happens again. Will need more updates to Timber but will be worth it.)

@jarednova @gchtr @palmiak Any thoughts on this?

**Comment by jezemery** [comment]
@pascalknecht concern there is that `https://github.com/twigphp/twig-cache-extension` hasn't been updated in 2 years...

**Comment by palmiak** [comment]
@pascalknecht for sure we need a quick fix.

Imo next we should go with @jezemery fix(if he would create a report) until the fix won't be added to official repo.

**Comment by pascalknecht** [comment]
@jezemery yes you are right. We will need to decide whether we want to take this one or check why it is not supported anymore (Does nobody use it?). But first thing should now be that we fix the current issue so that we can use Timber for the next months. Then we can go and decide on replacements.
@jezemery Do you want to take this into your hands and check if there are viable alternatives and what symfony, etc are using for this?

**Comment by jezemery** [comment]
I've created a PR to the twigphp repo. Hopefully somebody, somewhere gets an email and takes a look.
https://github.com/twigphp/twig-cache-extension/pull/6

**Comment by gchtr** [comment]
Twig 2.7.1 was just released a couple of minutes ago. With this update, I don’t see the error anymore. How is it for you all?

To go further, I agree with @pascalknecht’s action plan in https://github.com/timber/timber/issues/1950#issuecomment-472045177.

**Comment by jezemery** [comment]
https://github.com/twigphp/twig-cache-extension/pull/6#issuecomment-472064244

**Comment by gchtr** [comment]
Here’s the offical response from fabpot: https://github.com/twigphp/twig-cache-extension/pull/6#issuecomment-472064244:

> fixed upstream in Twig 1.38.1 and 2.7.1 (which I've just released).

So I guess there’s no need for a hotfix, but still a need for a strategy to prevent running into issues like these.

> We will need to decide whether we want to take this one or check why it is not supported anymore (Does nobody use it?)

- **twigphp/twig-cache-extension** – doesn’t seem to have any public dependents: https://packagist.org/packages/twig/cache-extension/dependents.
- **asm89/twig-cache-extension** – Of the 17 dependents that use it, Timber is by far the most popular: https://packagist.org/packages/asm89/twig-cache-extension/dependents.

It seems to me that we could fork this and maintain our own version.

**Comment by pascalknecht** [comment]
@gchtr Yes the update fixed it for me too. Hence we don't need to do anything from our side for a quick fix.
