### ISSUE TITLE
Localize date

### ISSUE THREAD

**Issue by tlygnersjo** [timber/timber#1956]
Is there any way (like a filter) to output a date in a localized format?

What i'm looking for is a alternative to {{ custom_field.date|date("F Y", "sv_SE") }}

Lets say that my custom field has the data 2019-03-22, i would like to output date format "F Y" which is month name and year (march 2019) but in localized format for Swedish month name (Mars 2019).

Is this possible? Maybe that would be a good filter to include in Timber?

**Comment by palmiak** [comment]
The date uses language set in admin panel. So the right way would be to set
site language as Swedish, and than if you want different language in admin
panel just set in profile.

Also take a look at date_i18n - as you see it's not possible to change the
language per usage. It always use the wordpress site language.




pt., 22 mar 2019, 13:32 użytkownik Tony <notifications@github.com> napisał:

**Comment by gchtr** [comment]
Working with localized dates is sometimes kinda hard throughout WordPress. I would advise you to use `date_i18n()` whenever you can. @palmiak is right, you should always set the language you’ll use for your website under Settings > General.

The `|date` filter uses `date_i18n()` in the back, but when you provide a date that is not an instance of `DateTime`, it will try to convert your date through `strtotime()`, which I’ve found to be very unreliable.

What I’ve found to work better is to use `DateTime::createFromFormat()`, where you can pass your date format.

A custom filter (that you can use now by copying it to **functions.php**) could look like this:

```php
add_filter( 'timber/twig', function( $twig ) {
    $twig->addFilter( new Twig_SimpleFilter( 'date_from_format', function( $date, $input_format, $output_format ) {
        return date_i18n(
            $output_format,
            DateTime::createFromFormat( $input_format, $date )->getTimeStamp()
        );
    } ) );

    return $twig;
} );
```

And you could use it like this:

```twig
{{ custom_field.date|date_from_format('Y-m-d', 'F Y') }}
```

**Comment by tlygnersjo** [comment]
Thank you both for the quick reply!

Thats a logic and great way. You may be right that I should be using for the website. Right now the website would in english, but maybe later on translated with WPML or such plugin. Would that also be supported? So if i add additional languages and switch to lets say Swedish, then the date will be localized as well?

**Comment by tlygnersjo** [comment]
Thanks @gchtr i'll try it out!

**Comment by gchtr** [comment]
> Right now the website would in english, but maybe later on translated with WPML or such plugin. Would that also be supported? So if i add additional languages and switch to lets say Swedish, then the date will be localized as well?

Yes. As far as I know, if you use a translation plugin, `date_i18n()` will work fine with the correct translation.
