### ISSUE TITLE
1.9.4 breaks WPML

### ISSUE THREAD

**Issue by portalzine** [timber/timber#1961]
After switching to 1.9.4 content language switching with WPML breaks completely.

I am using a standard Timber::get_posts to get custom post_type data. 

```
$args = array(
        'post_type' => 'inhalte',
        'posts_per_page' => -1,
      'orderby' => 'menu_order', 
    'order' => 'ASC', 
      'tax_query' => array(
            array(
                'taxonomy' => 'Area',
                'field' => 'slug',
                'terms' => $post_name,
            ),
          ),
 );
 $inhalte =  Timber::get_posts($args);
```

Back to 1.9.3 and all is working perfectly.

**Comment by gchtr** [comment]
In 1.9.4, `Timber::get_posts()` was updated to match what WordPress’s `get_posts()` does. WPML filters the query results, but `get_posts()` suppresses this by using `suppress_filters` by default.

So you have two possibilities here:

1. Use `new Timber\PostQuery( $args )` instead of `Timber::get_posts( $args )`.
2. Add `'suppress_filters' => false` to your `$args`.

@jarednova I’m wondering whether the changes introduced in #1813 should be considered as breaking changes because of effects like these?

**Comment by jarednova** [comment]
@gchtr that's what I was thinking too. That said, 1.9.3 to 1.9.4 only has the spelling correction. Regardless, I should have treated this "fix" as something that could cause a breaking change.

@portalzine when you say "WPML breaks completely," what is that you see — an error message? no data from WPML?

**Comment by portalzine** [comment]
@gchtr Will most likely be updating to new Timber\PostQuery( $args ) than ;) Thanks!

@jarednova In case of WPML, it does not pull the correct & current active language data anymore. Not sending any errors, that is why I did not suspect Timber at first  ;)

**Comment by portalzine** [comment]
@gchtr Just did a testdrive with 1.9.4 again. `new Timber\PostQuery( $args )` fails as a replacement, while `'suppress_filters' => false` works.

**Comment by gchtr** [comment]
@portalzine How did it fail? Was the result the same as when you used `Timber::get_posts()` or did you get an error message of some kind?

**Comment by CDSTek** [comment]
Just came across a similar issue, `'suppress_filters' => false` worked for me.

I am using `Timber::get_posts($args);` as well; one of my args is the Wordpress search paramter (`'s' => "search string"`). A search that was previously returning results no longer returns any results after updating to 1.9.4. I should note that I am searching for values that are in custom fields and have enabled a custom `post_search` filter to include those in the search.

The problem only seems to occur when I search for values that are only present in custom fields ie. searches that rely on the `post_search` search filter. (Search strings that match part of a post title return results as expected.) If this is default Wordpress query behaviour now then the problem may not be specific to Timber but, rather, to the changes in Wordpress core that Timber is mirroring.

**Comment by kisabelle** [comment]
Just came across a similar issue, 'suppress_filters' => false worked for me.

I am using Timber::get_posts($args); as well; one of my args is the Wordpress search paramter ('s' => "search string"). A search that was previously returning results no longer returns any results after updating to 1.9.4. I should note that I am searching for values that are in custom fields and have enabled a custom post_search filter to include those in the search.

The problem only seems to occur when I search for values that are only present in custom fields ie. searches that rely on the post_search search filter. (Search strings that match part of a post title return results as expected.) If this is default Wordpress query behaviour now then the problem may not be specific to Timber but, rather, to the changes in Wordpress core that Timber is mirroring.

**Comment by mibu31** [comment]
Oh no... this is causing issues for me too unfortunately :(

`\Timber\Timber::get_posts($args);` is returning posts for all languages rather than just the current language. Adding the arg `'suppress_filters' => false` resolves the issue.

**Comment by jarednova** [comment]
This is followed-up on #2016 and #2020;

tdlr; use 1.9.2 with WPML until they release a new version that uses a more recent version of Twig
