### ISSUE TITLE
Current Date Displayed on Front-End of Blog Posts Instead of Published Date

### ISSUE THREAD

**Issue by jenclickspring** [timber/timber#1962]
## Expected behavior
Published date should be displayed on front end of blog posts. 

## Actual behavior
Current date displayed on front end of blog posts. 

## Steps to reproduce behavior

Example here: `https://www.chrisapappas.com/2019/02/11/grammys-2019-best-dressed/`
See how this posts shows the date as 4/3/2019 (current date). The date published should be 2/11/2019. All the individual posts show this. However, the back end and post archive is fine. 

This is the code in single.php:

```php
$context                 = Timber::get_context();
$post                    = Timber::query_post();
$context['timberPost']   = $post;
$context['post']         = getSinglePost('post', $post->ID);
$context['comment_form'] = TimberHelper::get_comment_form();
$context['instagram']    = $instagramCachedResults;
if (post_password_required($post->ID)) {
Timber::render('single-password.twig', $context);
} else {
Timber::render(array('single-' . $post->ID . '.twig', 'single-' . 
$post->post_type . '.twig', 'single.twig'), $context);
```

In a file called functions--custom-posts.php I see this code:

```php
function getSinglePost($posttype = null, $id = null)
{
if ($id != null) {
    $postId = $id;
} else {
    $postId = get_the_id();
}

$attachedimage = new TimberImage(get_post_thumbnail_id());
$categories    = get_the_category();

// setup an array to change the post data returned
$singlePostArray = array(
    'date'       => strtotime(get_the_date()),
    'id'         => get_the_id(),
    'title'      => get_the_title(),
    'categories' => $categories,
    'content'    => get_the_content(),
    'excerpt'    => get_the_excerpt(),
    'tags'       => get_the_tags(),
    'post_type'  => $posttype,
    'image'      => $attachedimage,
    'link'       => get_permalink(),
);
if ($posttype == 'post') {
    $singlePostArray['custom'] = prepareBlogPostFields();
}

// Restores original Post Data
wp_reset_postdata();

return $singlePostArray;
}

```

Might be the update to PHP 7.2 that is causing it. But cannot figure out where the problem is. 

## What version of WordPress, PHP and Timber are you using?
WordPress 5.0.4, PHP 7.2, Timber 1.8.4

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
This website was recently handed over to us and I did not build the theme. But it is currently activated as a plugin. I already posted this question in Wordpress Stack Exchange, but cannot tag it with "Timber" because I don't have enough reputation. Thanks.

**Comment by marciojc** [comment]
@jenclickspring at the post shows the date as 2/11/2019.

**Comment by jarednova** [comment]
Yeah, I think we're good here. FWIW this line ...

```php
'date'       => strtotime(get_the_date()),
```

in `functions--custom-posts.php` suggests that there might be some assumptions in the code about being in-loop for certain templates. Without seeing the whole theme, it's hard to know for sure, but it suggests the original authors of the theme aren't taking advantage of some natural behaviors of `Timber\Post`
