### ISSUE TITLE
Timber\Post method get_post_custom accounts for arrays only 1 level deep 

### ISSUE THREAD

**Issue by bdanzer** [timber/timber#1966]
## Expected behavior
For the Timber\Post method get_post_custom, I would expect to have the ability to force single value like get_metadata https://developer.wordpress.org/reference/functions/get_metadata/.

## Actual behavior
If there are multiple of the same post meta_keys (https://gyazo.com/e95bab2fac97301b45170bdda7d5a0e1) it will only force on arrays with a count of 1 with no additional control 

line: 540 lib/Post.php
`if ( is_array($value) && count($value) == 1 && isset($value[0]) ) {
	$value = $value[0];
}`

Is there a reason this needs to be set with count and not just force the value[0] to be set and remove the count or maybe add a filter to allow for customizations like forcing value[0]?

`if ( is_array($value) && isset($value[0]) ) {
	$value = $value[0];
}`

or

`$customs[$key] = apply_filters('timber_post_custom_value', maybe_unserialize($value));`

## Steps to reproduce behavior
Make multiple meta_keys in the database and with twig output the post meta {{post.test_meta}} and see that you get an array on the page

## What version of WordPress, PHP and Timber are you using?

Timber 1.9.2
WordPress 5.1.1
PHP 7.2

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by Levdbas** [comment]
The default behavior of `get_post_custom()` which is now `meta()` will be changing. Closing this here since it is no longer relevant for current development and we are not going to change this behavior anymore in 1.x
