### ISSUE TITLE
Post preview length is affected by link

### ISSUE THREAD

**Issue by rgm267** [timber/timber#1968]
So I've been working on this website, and found out that the post preview length does not match the number of words I've set it to be.

Currently, just for example purposes this is what I have in my gutenberg editor. This paragraph, with a "more" block just under.

"This is an example post that it should be all displayed in the post preview because it has only 21 words."

With this line outputing the preview, I should be able to see this whole sentence 

```{{ post.preview.length(25).read_more(false).force }} ```

Which I can! But the problem starts when I had a link to the paragraph with the option - "open in new tab"
![image](https://user-images.githubusercontent.com/36971106/55719182-86816f80-59f5-11e9-96d4-6feaca8c152f.png)

This is what the preview looks like with the link.

![image](https://user-images.githubusercontent.com/36971106/55719204-9731e580-59f5-11e9-9cac-7fddf8403326.png)

Now, I've discovered that when I check the HTML preview of this paragraph, it has all sorts of extra values (see image):
![image](https://user-images.githubusercontent.com/36971106/55719318-d6f8cd00-59f5-11e9-8ae1-0d9b4c49a57d.png)

These extra values (target, rel, aria-label) are what is causing the preview to not match the words that I've set.

I've tried the strip setting also, but made no effect, as it is enabled by default anyways. Not sure what more I can do to solve this, so that's why I made this bug report. Looking forward for some answers regarding this issue. Thanks in advance.

**Comment by palmiak** [comment]
Kind of strange because preview should strip those extra HTML tags first. I'll look into this. Probably there is wrong of operations somewhere

**Comment by palmiak** [comment]
I've checked the code and I was right with the operation order.

As you use `<!--more-->` first we use
```
if ( !strlen($text) && preg_match('/<!--\s?more(.*?)?-->/', $this->post->post_content, $readmore_matches) ) {
			$pieces = explode($readmore_matches[0], $this->post->post_content);
			$text = $pieces[0];
			if ( $force ) {
				if ( $allowable_tags ) {
					$text = TextHelper::trim_words($text, $len, false, strtr($allowable_tags, '<>', '  '));
				} else {
					$text = TextHelper::trim_words($text, $len, false);
				}
				if ( $chars !== false ) {
					$text = TextHelper::trim_characters($text, $chars, false);
				}
				$trimmed = true;
			}
			$text = do_shortcode($text);
		}
```

`$allowable_tags` is false so we `trim_words` first. Later, as `$strip` is true we launch:
```
if ( $strip ) {
	$text = trim(strip_tags($text, $allowable_tags));
}
```

In short we have to fix some stuff here:
- the order of operations (first strip, than `trim_words` or `trim_characters`)
- I'm not sure about `do_shortcode` - shouldn't we launch it before trimming?

@jarednova I rembember that there were some plans about rewritting this - did something was done or not yet?

**Comment by marciojc** [comment]
Actually, these tags are allowed by default 
`p a span b i br blockquote`

so to override this you can do `{{ post.preview.strip("i").length(25).read_more(false).force }}` or you can add a filter to `add_filter('timber/trim_words/allowed_tags', function() { return "i"})`

**Comment by rgm267** [comment]
@marciojc Thanks, your solution works well! Sorry for taking so long to respond.
