### ISSUE TITLE
Does not work Resize if there is a question mark?

### ISSUE THREAD

**Issue by Vanguger** [timber/timber#1970]
Timber is used in Gantry 5 and I can't do the following: In developer mode, do images have code after the sign ? and such images are not changed through resize

`{{ 'http://site.com/wp-content/themes/g5_hydrogen/images/img/img.jpg?19485'|resize(300,150) }}`

**Comment by palmiak** [comment]
Shouldn't it be Image(URL)|resize  ?

**Comment by DamirPecnik** [comment]
Nope not working for me also!

If images have Asset Timestamps on it like this:
`'http://site.com/wp-content/uploads/2019/05/GoldenGateBridge.jpg?5ccc9a0c'|resize(480)`

This works!
`'http://site.com/wp-content/uploads/2019/05/GoldenGateBridge.jpg'|resize(480)`

**Comment by palmiak** [comment]
I have a small clue - in short the `?` is not a problem if we are using external images - the problem only exists with local images.

**Comment by Levdbas** [comment]
Closing this as a stale issue. Please let us know if you still run into this issue by opening a new ticket.
