### ISSUE TITLE
Comment threads/nesting - Still no examples? How do we do this?

### ISSUE THREAD

**Issue by randymwebdev** [timber/timber#1971]
I've seen people on here asking since 2015 for examples on how to get threaded/nested comments working, and still not a single example or clear solution has been posted. Apparently CommentThread has been added, but how do we use this? Any example please?

The starter pack theme for timber doesn't support threaded comments. And even when I use
    `{{ function('comments_template') }}`
I don't get any threaded/nested comment behavior. It's like Timber is stopping it. Any ideas?

**Comment by randymwebdev** [comment]
I found out I needed the wordpress **comment-reply.js** file to run. I never included that in my custom theme.

`function theme_queue_js(){
if ( (!is_admin()) && is_singular() && comments_open() && get_option('thread_comments') )
  wp_enqueue_script( 'comment-reply' );
}
add_action('wp_print_scripts', 'theme_queue_js');`

adding that to my functions.php file fixed the issue. But still documentation on comments could be a little better, or at least show a working example.

**Comment by jarednova** [comment]
I agree @randymwebdev — something I'll come up with an example for and add to the docs
