### ISSUE TITLE
found_posts on new PostQuery()

### ISSUE THREAD

**Issue by Grafikart** [timber/timber#1973]
## Is your feature request related to a problem? Please describe.

There is no way to get the total number of post from the PostQuery object which forces users to write things like this : 

```php
$query = new WP_Query([
    'cat'            => $category->id,
    'post__not_in'   => get_option('sticky_posts'),
    'posts_per_page' => $context['offset']
]);
$context['posts'] = new PostQuery($query);
$context['found'] = $query->found_posts;
```

## Describe the solution you’d like

A method (`total()` or `found()`) on `PostQuery` to get the total number of post found.

## Questions

Is there a reason why this feature is not implemented ? I may be able to submit a PR to implement this myself but I want to know if there was a reason for not including this in the PostQuery class. 

Thanks

**Comment by marciojc** [comment]
@Grafikart 
```
$context['found'] = count($context['posts']);
```

**Comment by MouadDB** [comment]
The count() function returns the number of elements in an array.
https://www.php.net/manual/en/function.count.php

**Comment by marciojc** [comment]
oh, we want the total of posts of the query.
Don't know what is original code.
But as his already using new WP_Query he can use his solution or calling the global $query

**Comment by j-masci** [comment]
> The count() function returns the number of elements in an array. https://www.php.net/manual/en/function.count.php

Thanks, but he wants the total number of posts not including pagination parameters, ie. what you get back from SQL when using SQL_CALC_FOUND_ROWS selector.
