### ISSUE TITLE
Documentation site down

### ISSUE THREAD

**Issue by opengeekv2** [timber/timber#1976]
## Expected behavior
I expect to get into the documentation website when acessing https://timber.github.io/docs/

## Actual behavior
I get either timeout or 404 from github.

## Steps to reproduce behavior
Several options
Access http://timber.github.io/docs/
Take a screenshot useing an online screenshot utility or check it in
downforeveryoneorjustme.com

## What version of WordPress, PHP and Timber are you using?
None but using Chrome 73 and Firefox 66

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
I think t
<img width="721" alt="Captura de pantalla 2019-04-23 a les 15 38 08" src="https://user-images.githubusercontent.com/901282/56585679-9f397a00-65de-11e9-9b58-5395276660d9.png">
his is irrelevant for the issue

**Comment by palmiak** [comment]
It's ok at my end.

wt., 23 kwi 2019, 15:44 użytkownik Marc Mauri Alloza <
notifications@github.com> napisał:

**Comment by jarednova** [comment]
Yeah me too — I think the confusion (and the error from istidownforeveryoneorjustme) is that `https://http://timber.github.io/` is a 404. We should probably redirect that to the docs or upstatement.com/timber

**Comment by opengeekv2** [comment]
Well it looks I can get into docs through my phone connection. It might be an issue of our fiber provider or local network.

Thanks anyway

**Comment by palmiak** [comment]
I'm closing this one :)
