### ISSUE TITLE
Timber & webp converts not working

### ISSUE THREAD

**Issue by vyskoczilova** [timber/timber#1978]
## Expected behavior

Convert JPG to WebP properly.

## Actual behavior

I have the following code and get empty/damaged webp files (attached). Don't know what's wrong GD library is enabled, I can catch the following error.

```
<picture>
    {% if webp %}
        <source type="image/webp" srcset="
        {{ image.width >= 248 ? image.src('thumbnail')|towebp|resize(248) ~' 248w,' }}
        {{ image.width >= 320 ? image.src('thumbnail')|towebp|resize(320) ~' 320w,' }}
        {{ image.width >= 540 ? image.src('medium')|towebp|resize(540) ~' 540w,' }}
        " sizes="248px"
        />
    {% endif %}
    <source srcset="
        {{ image.width >= 248 ? image.src('thumbnail')|resize(248) ~' 248w,' }}
        {{ image.width >= 320 ? image.src('thumbnail')|resize(320) ~' 320w,' }}
        {{ image.width >= 540 ? image.src('medium')|resize(540) ~' 540w,' }}
        " sizes="248px"
    />
    <img src="{{ image.src('thumbnail') }}" alt="{{alt}}" class="{{class}}" width="248" height="{{ (image.height/image.width*248)|round(0, 'ceil') }}"/>
</picture>
```

`gd_info` returns the following:

```array(13) {
			["GD Version"]=>
			string(5) "2.2.5"
			["FreeType Support"]=>
			bool(true)
			["FreeType Linkage"]=>
			string(13) "with freetype"
			["GIF Read Support"]=>
			bool(true)
			["GIF Create Support"]=>
			bool(true)
			["JPEG Support"]=>
			bool(true)
			["PNG Support"]=>
			bool(true)
			["WBMP Support"]=>
			bool(true)
			["XPM Support"]=>
			bool(true)
			["XBM Support"]=>
			bool(true)
			["WebP Support"]=>
			bool(true)
			["BMP Support"]=>
			bool(true)
			["JIS-mapped Japanese Font Support"]=>
			bool(false)
		  }
```

and in the WP debug.log:

```
[24-Apr-2019 16:27:31 UTC] WP_Error Object
(
    [errors] => Array
        (
            [invalid_image] => Array
                (
                    [0] => Soubor není obrázek. (the file is not a picture)
                )

        )

    [error_data] => Array
        (
            [invalid_image] => /var/www/html/wordpress/wp-content/uploads/2019/04/134_small-320x226.webp
        )

)
[24-Apr-2019 16:30:38 UTC] WP_Error Object
(
    [errors] => Array
        (
            [image_no_editor] => Array
                (
                    [0] => Pro obrázek nemohl být použit žádný editor. (for the file no editor could be used)
                )

        )

    [error_data] => Array
        (
        )

)
```

## What version of WordPress, PHP and Timber are you using?

WP 5.1.1, Timber 1.9.4, PHP PHP Version: 7.2.14-1+ubuntu16.04.1+deb.sury.org+1

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

WP.org

**Comment by palmiak** [comment]
Could you make a simple test - convert a jpg to webp. Just a simple image |
towebp without any resizes etc.

śr., 24 kwi 2019, 18:47 użytkownik Karolína Vyskočilová <
notifications@github.com> napisał:

**Comment by vyskoczilova** [comment]
Hi! I've tried it, the result is still very same :(. I'm attaching the created files if you'll spot something. The JPGs
[webp.zip](https://github.com/timber/timber/files/3113700/webp.zip)
 are resized properly.

**Comment by palmiak** [comment]
Let's try a bit different:

```
{{ Image( image_id ).src | towebp | resize(320) }}
```
so we're taking a full image, than we convert it webp and resize it at the end.

also try:
```
{{ Image( image_id ).src | resize(320) }}
```

Also one question - are you trying to convert webp to webp? Because if you have a webp image already don't use the `towebp` filter.

**Comment by vyskoczilova** [comment]
I'm sure that is just jpgs. I will test what you propose, but it's really weird - it should work, because the same image is resized properly without the towebp filter. 

What I have tested so far (moved back to post.thumbnail so it's easy to replicate):

```
{{ post.thumbnail.src|towebp }} works
{{ post.thumbnail.src|resize(1400)|towebp }} works

{{ post.thumbnail.src|towebp|resize(1400)}} // doesn't resize, returns large
{{ post.thumbnail.src('large')|towebp }} doesn't work
{{ post.thumbnail.src('large')|resize(1600)|towebp }} 
```

It looked promising, so I moved to resize to all sizes I use for jpgs and there was a big surprise for me, it looks like some sizes work properly, some doesn't. I have no good explanation for this behavior (JPGs are fine), I regenerated them many times with the very same results.

```
{{ post.thumbnail.src|towebp }} works
{{ post.thumbnail.src|resize(1400)|towebp }} works
{{ post.thumbnail.src|resize(320)|towebp }} doesnt
{{ post.thumbnail.src|resize(540)|towebp }} doesnt
{{ post.thumbnail.src|resize(1024)|towebp }} works
{{ post.thumbnail.src|resize(1280)|towebp }} works
{{ post.thumbnail.src|resize(1600)|towebp }} doesnt
{{ post.thumbnail.src|resize(1920)|towebp }} doesnt
{{ post.thumbnail.src|resize(2240)|towebp }} works
{{ post.thumbnail.width }} works 2500
{{ post.thumbnail.height }} works 703
```

[Here you go with the result and original image.](https://github.com/timber/timber/files/3120409/Pivovar.zip)

**Comment by palmiak** [comment]
Now I'm on small holiday but when I'll come back I'll check this, as this is quite weird.

**Comment by vyskoczilova** [comment]
Thanks a lot, I'm on holidays as well but somewhat with intrenet, just drop me a line and I'm happy to assist, I would say I must do something wrong, but not sure what.

**Comment by vyskoczilova** [comment]
@palmiak Hi, I'm back if you have time we could have a look at the issue. If you wish, I can give you access to FTP in order to check it (the site is still under development). Just drop me an email to karolina@kybernatu.cz.

**Comment by boldium-eric-mikkelsen** [comment]
Dealing with the same issue, any movement on this?

**Comment by vyskoczilova** [comment]
@boldium-eric-mikkelsen Hi, I haven't found either the cause or the solution myself and @palmiak probably didn't have time to look after it.

**Comment by jarednova** [comment]
@boldium-eric-mikkelsen @palmiak @vyskoczilova thanks for keeping this alive. There's definitely an issue with the order in which `towebp` comes in the filters. In my tests, as long as it comes at the _end_ it works fine. Perhaps this is because of limitations from what GD can/can't manipulate?

It definitely warrants further investigation. For whoever is interested in pursuing this further, I imagine some debug time with `Image/Operation/Resize.php` would yield answers (if not solutions)

**Comment by vyskoczilova** [comment]
@jarednova I don't know, the weird thing is that it fails even on small images and it looks quite random to me, without any special error or so. I'm too busy at the moment (preparing for my Ph.D. exams at the end of September), but I will try to get back to it afterward.

**Comment by antoinehenrich** [comment]
Some weeks passed again. Was anybody able to solve the problem?

**Comment by Levdbas** [comment]
As this is quite an old issue and hasn't had any recent activity I think it's time to close this one. If anyone still runs into this issue, please let us know.
