### ISSUE TITLE
Update Pagination Documentation

### ISSUE THREAD

**Issue by ricardo-lewis** [timber/timber#1979]
## Is your feature request related to a problem? Please describe.

I recently got Pagination working after dealing with the infamous /page/2 Error 404 problem.

## Describe the solution you’d like

Please add something like this to the Timber Documentation page for Pagination: 
Go to WordPress Settings > Reading > "Blog pages show at most" and set the value to be less than or equal to your argument for  **posts_per_page** in your \Timber\PostQuery.

## Describe alternatives you’ve considered

I tried the plugin **Category pagination fix** which didn't work, and neither did any of the other suggestions that a Google Search result will give you for this problem. I have confirmed this is the solution by altering the value for "Blog pages show at most" and this will make the problem appear/disappear.

## Additional context

Thanks to @chaimaech and https://github.com/timber/timber/issues/1352

EDIT: The value for **Blog pages show at most** needs to be <= **posts_per_page**

**Comment by marciojc** [comment]
Did you follow https://timber.github.io/docs/guides/pagination/#what-if-i-m-not-using-the-default-query ???

**Comment by ricardo-lewis** [comment]
Yes absolutely. And it did not work. The pre_get_posts trick is used by the aforementioned plugin and also suggested separately on about a dozen different web pages.

**Comment by firstchair** [comment]
Coudnt make it work, tried a lot of different things but this did the trick, next to the custom query:

`        Routes::map('blog/page/:pg', function($params){
            $query = 'post_type=blog&paged='.$params['pg'];
            Routes::load('archive.php', null, $query, 200);
        });`
