### ISSUE TITLE
Timber\User() - can't add role to user

### ISSUE THREAD

**Issue by alicam** [timber/timber#1980]
Quick one.

When I compare Timber\User with WP_User...

The former doesn't allow $user->add_role('role'), but of course it works with the latter.

Generally I'm a little suspicious about how Timber's User object handles roles.

Is this a known thing or am I looking at a possible bug?

(I discovered this today, as I was unable to add a role to a user using Timber\User.)

Cheers

A

**Comment by gchtr** [comment]
Hey @alicam 

Timber is mainly used for reading data, not for updating data. While there are `update()` methods for some of the Timber classes, we decided to drop support for them in Timber 2.x. In a similar manner, you can’t change roles through the `Timber\User` object. We think there are already sufficient methods for that in WordPress core.

> Generally I'm a little suspicious about how Timber's User object handles roles.

Timber just reads the roles and translates them to the current locale. Nothing more.

If you need a `WP_User` object, you can always get the ID from the `Timber\User` object and request the object through `get_user_by_ID( 'ID', $user->ID )`.

**Comment by gchtr** [comment]
I’m going to close this. If you still have any questions, feel free to ask!
