### ISSUE TITLE
Timber collides with the ACF on admin side

### ISSUE THREAD

**Issue by twentyfortysix** [timber/timber#1981]
## Problem
I just discovered that the ACF is not capable insert image via classical [add media] in to wysiwyg while the Timber plugin is activated.
If I try to insert image into wysiwig it does nothing. Console shows no error.
If I disable Timber it works.. which is weird as Timber "does not run in admin area". There might be possibly some collision while running call to ajax.php or who knows what.

I have contacted ACF team and gave them key to sandbox. Later they asked me to ask you for help, as they haven't found a problem on their side.

## Steps to reproduce behavior
I can give keys to sandbox, if need be.

## What version of WordPress, PHP and Timber are you using?
WP 5.1.1
TImber 1.9.4
ACF PRO 5.7.13 

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
I do not remember, most likely over wp-cli

**Comment by palmiak** [comment]
What other plugins are you using?

wt., 30 kwi 2019, 07:41 użytkownik twentyfortysix <notifications@github.com>
napisał:

**Comment by twentyfortysix** [comment]
I have turned all the plugins off and kept only the ACF and Timber and were able to reproduce that behavior.

**Comment by palmiak** [comment]
And what will happen if you will change the theme?

wt., 30 kwi 2019, 08:51 użytkownik twentyfortysix <notifications@github.com>
napisał:

**Comment by twentyfortysix** [comment]
Oki

so the problem caused by this filter..
I don't know why, but.. 

`add_filter( 'image_send_to_editor', 'remove_thumbnail_dimensions', 10 );`

in other words, it is not a problem of Timber but ACF not being able to handle this filter.
