### ISSUE TITLE
Make PHPunit setup more robust outside of VVV

### ISSUE THREAD

**Issue by aj-adl** [timber/timber#1982]
## Is your feature request related to a problem? Please describe.

Running the supplied `bin/install-wp-tests.sh` within VVV works, but this takes probably the 'happiest' path through the script.

It looks like this started out as a copy of the script from [WP CLI Scaffold Command](https://github.com/wp-cli/scaffold-command/blob/master/templates/install-wp-tests.sh) which has since also received some updates that fix the `sed` problems on Mac OS.

Features which would be great
- use the system temp directory
- ensure the paths are all correct and do not feature trailing slashes, even if set via environment variables
- fix sed command syntax for `darwin` machines
- update the download logic to deal with betas and RC's like in the above linked script

## Describe the solution you’d like
 
PR will be submitted to resolve all issues

## Describe alternatives you’ve considered

Can use in VVV, this is for people running things like laravel valet etc, overall it makes it more robust to run anywhere.

**Comment by jarednova** [comment]
@aj-adl's PR #1983 was worked on in #1995 which we merged in
