### ISSUE TITLE
Timber Menu: order_children adding extra classes to custom menu item

### ISSUE THREAD

**Issue by mgarabedian** [timber/timber#1985]
## Expected behavior
Add a custom menu item that is NOT of type _WP_Post_ and have it parse correctly with Timber.

## Actual behavior
Extra class names are added from the last menu item in the array, via order_children method in Menu.php.  Also, _order_children_ is requiring an ID for the menu item to be added.

## Comments
I do not understand the purpose of importing classes from the last menu item. 

## Steps to reproduce behavior
Filtering a menu with add_filter('wp_get_nav_menu_items').  Adding a custom StdClass menu.

## What version of WordPress, PHP and Timber are you using?
Wordpress 5.1, PHP 7

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
GitHub

**Comment by jarednova** [comment]
This is solved by #2013
