### ISSUE TITLE
Changes in 1.9.4 break WooCommerce My Account Page

### ISSUE THREAD

**Issue by aj-adl** [timber/timber#1987]
Changes in #1813 break the WooCommerce My Account Orders Page by setting defaults on the Query that WooCommerce is not expecting - specifically `'no_found_rows' => true`.

When `no_found_rows` is `true` the query object's `found_posts` will ALWAYS be 0 unless we hook in and alter it.

When using the `[woocommerce_my_account]` shortcode to display the WooCommerce account section they check `found_posts`

See [this template file](https://github.com/woocommerce/woocommerce/blob/master/templates/myaccount/orders.php#L23-L27) and [this data store function](https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-order-data-store-cpt.php#L772-L780) for the relevant lines of WooCommerce code.

## Expected behavior
I would expect that the order section displays.

## Actual behavior
The orders section displayed no orders, even if there are customer orders in the DB.

## Steps to reproduce behavior
 Install the latest timber + WooCommerce.

Visit the account section, usually `http://mysite.com/my-account/`

Visit the orders tab, no orders will be displayed..

Overall, I feel like setting defaults on EVERY WordPress query, as this PR has done, is very dangerous. Anecdotally, we've had to downgrade Timber on other sites recently due to misc issues and weird behaviour, I'd suspect that these issues too were cause by these changes.

Fine to set those defaults for all Timber Queries, but the current method sets it for ALL queries. 

## What version of WordPress, PHP and Timber are you using?
WordPress 5.1.x, Timber 1.9.4, WooCommerce 3.6.2+

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by gchtr** [comment]
> Overall, I feel like setting defaults on EVERY WordPress query, as this PR has done, is very dangerous. Anecdotally, we've had to downgrade Timber on other sites recently due to misc issues and weird behaviour, I'd suspect that these issues too were cause by these changes.

I agree. Timber sets it for queries that come **after you use `Timber::get_posts()`**. It shouldn’t be the case when you use `new Timber\PostQuery()`. For now, can you try to use `new Timber\PostQuery()` for the page that displays your WooCommerce account page?

Adding a filter that affects global queries can have very strange effects in different environments. So it can very well be that your other issues are caused by this as well.

@jarednova What do you think, should we reverse this breaking change? There have been other issues, like #1961. Or can we find another solution?

Related: #1957

**Comment by palmiak** [comment]
@gchtr It all comes down to one thing - are we using **Timber::get_posts** as **get_posts** clone or not. If we are than we should keep it and inform people better. If not - than maybe we should reverse it as it's causing problems.

The last solution would be adding a filter/flag so to user could go back to original Timber::get_posts untill he rewrites his code. And after few version we would deprecated it.

**Comment by gchtr** [comment]
@palmiak But it doesn’t help developers when we introduce a change that on the one hand mimicks WordPress’s behaviour, but on the other hand introduces a breaking change. Simply informing people is not a good solution if it means that everybody would have to check **every Timber query on every site** to see whether it still does what it should. Yes, it fixes a deviation we had. But for me, this is a breaking change that should probably not have been introduced in a patch version. This is major change.

> The last solution would be adding a filter/flag so to user could go back to original Timber::get_posts untill he rewrites his code. And after few version we would deprecated it.

I’d actually prefer to have it the other way round: use a filter that allows you to **opt into** that behaviour. And then make that behaviour the default in a major version.

What is strange here is also that it seems to affect WooCommerce queries, even though the `pre_get_posts` filter is removed after it was used once.

**Comment by aj-adl** [comment]
Also just in case some people land here via google etc...

Regardless of the outcome of this ticket we were able to fix this via the following code..

```php
<?php

// In your functions.php or similar

function my_namespace_order_query_args( $args ){

    $args['no_found_rows'] = true;

    return $args;

}

add_filter( 'woocommerce_my_account_my_orders_query', 'my_namespace_order_query_args' );
```

**Comment by jarednova** [comment]
Hey all, I'm just back from vacation and really want to figure out a way to solve this and #1961. It would seem that the best strategy is to "undo" this release is to at once ...

- Remove 1.9.4
- Re-release 1.9.4 as 1.10.0
- Release the current `master` as 1.10.1

This way, the prior behavior is captured for anyone using WPML/WooCommerce (and other similar plugins) with `1.9.x` — we can then investigate the proper _final_ resolution to these issues in 1.10 or 1.11 (and of course, 2.x).

I didn't seen any info in the [Semantic Versioning docs](https://semver.org/) about pulling a release. Does anyone know of proper procedure here (esp. for packagist) or even what this is called (Pulling? Undoing? Yanking?)

**Comment by gchtr** [comment]
@jarednova I guess you could remove the `1.9.4` tag manually in Packagist. There’s a delete button next to each tag listed in the right column:

![](https://user-images.githubusercontent.com/2084481/57910899-a3c41c00-7886-11e9-821a-1c39d9a2b5df.png)

And you can [delete releases in GitHub](https://help.github.com/en/articles/editing-and-deleting-releases#deleting-a-release).

But what does speak against releasing a version `1.9.5` as a «hotfix» that reverts the change introduced in `1.9.4`? We can still release a version `1.10.0` once we figure out the best way to handle this.

**Comment by jarednova** [comment]
FYI, I'm working on this today with the `1.9.5` hotfix path suggested by @gchtr

**Comment by jarednova** [comment]
Alright, version 1.9.5 is ready as a pre-release:

https://github.com/timber/timber/releases/tag/1.9.5

Here's my plan from here:
- Release to WP.org
- Publish as an official release
- Pull the 1.9.4 release from packagist (I think it makes sense to leave as a record on GitHub)

Timber 2.0 removes the distinction anyway by depreciating `Timber::get_posts` — so I think the behavior or 1.9.5 should stand for future versions

**Comment by jarednova** [comment]
... just wanted to note the big reminder/lesson. When in doubt, make things a "bigger" release. I thought because this was correcting a bug, to make it just a "patch" version — but in reality, changes in behavior (even to the way they "should" be) is still a change in behavior

**Comment by gchtr** [comment]
@jarednova I think that plan works.

I added the example for the filter in the release notes (https://github.com/timber/timber/releases/tag/1.9.5), because the name of the filter is not the same as the opening description of the pull request.

> Alright, version 1.9.5 is ready as a pre-release

It’s now already a released version. Is this intended?

> Timber 2.0 removes the distinction anyway by depreciating `Timber::get_posts` — so I think the behavior or 1.9.5 should stand for future versions

@jarednova I don’t know if understand you correctly when you say «should stand for future versions». If we deprecate `Timber::get_posts()` in 2.0 (#1957), we would have to deprecate the newly introduced `timber/get_posts/mirror_wp_get_posts` again, right?

**Comment by jarednova** [comment]
@gchtr composer didn't seem to recognize it as a pre-release, so I went ahead and made it "real" on GitHub too.

In regards to your second question, my point was since we're deprecating `Timber::get_posts` (at least, right now) — changing the underlying behavior of `get_posts` seems unnecessary. If someone needed to get `get_posts` behavior, the preferred method should be to set those arguments as-such. We should also deprecate the newly-introduced filter
