### ISSUE TITLE
Illegal offset type in isset or empty in taxonomy.php when using Timber\Menu

### ISSUE THREAD

**Issue by yingban** [timber/timber#1988]
Hi,

I am using Timber(1.9.4) installed with Composer, in a Wordpress project version 5.1.1, with ACF plugin last version.

In my recent projects, I got a Wordpress warning which is:
"Warning:  Illegal offset type in isset or empty in wp-includes/taxonomy.php" in a custom post type content with a custom taxonomy.

When I comment the line in the foreach loop to retrieve all the menus, the warning disappears

   ` foreach (get_registered_nav_menus() as $key => $value) {
$context[$key] = new Timber\Menu( $key );
}`

Does somebody have the same issue? 

Thanks!

**Comment by palmiak** [comment]
Hi

Does this problem also exists in new versions of Timber? There were some changes with the menu so maybe it was fixed.

Also do you have any menus created?

And finally I can't find the timber-menus file? Are you sure about the version that you are using?

**Comment by yingban** [comment]
Sorry palmiak, I edited my comment.

I updated timber to version 1.9.4.
We use a foreach loop to retrieve all menus, and add each menu to the global Timber context.

**Comment by yingban** [comment]
I updated Timber to version 1.10.

When I add menu to the global context like below 
`foreach (get_registered_nav_menus() as $key => $value) {
		$context[$key] = new Timber\Menu( $key );
	}`

in some page, it throws an error from the wp core taxonomy.
If I comment this line 
`$context[$key] = new Timber\Menu( $key );`
there is no more error.

**Comment by palmiak** [comment]
Fist of all - could you paste the error code here?

Could you show me what will this code output:
```
var_dump( get_registered_nav_menus() );
```

It will should show you all the `$keys`. For example let's say it will output:
- menu_1
- menu_2
- menu_3

next define all those menu manually - without the loop:
```
$context['menu_1'] = new Timber\Menu( 'menu_1' );
$context['menu_2'] = new Timber\Menu( 'menu_2' );
$context['menu_3'] = new Timber\Menu( 'menu_3' );
```

next go to the page where the error appears and start commenting all the menus one after another to see which one is causing the error.

**Comment by yingban** [comment]
Hi Palmiak, sorry for my late reply, just came back form holidays.

Here is the error
`<b>Warning</b>:  Illegal offset type in isset or empty in <b>/wp-includes/taxonomy.php</b> on line <b>294</b><br />`

If I dump the $taxonomy variable in WP function taxonomy_exists, I got this
`string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
array(1) {
  [0]=>
  string(2) "23"
}

Warning: Illegal offset type in isset or empty in /wp-includes/taxonomy.php on line 294
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
array(1) {
  [0]=>
  string(2) "23"
}

Warning: Illegal offset type in isset or empty in /wp-includes/taxonomy.php on line 294
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
string(8) "nav_menu"
array(1) {
  [0]=>
  string(2) "23"
}

Warning: Illegal offset type in isset or empty in /wp-includes/taxonomy.php on line 294
string(8) "nav_menu"
string(8) "post_tag"
string(8) "post_tag"
string(8) "post_tag"
string(8) "post_tag"
string(8) "post_tag"
string(8) "category"
string(8) "category"
string(8) "category"
string(8) "category"
string(8) "category"
Startseite
kommunizieren
fotografieren
wirso
blog
kartenschreiben
kontaktieren
 string(15) "travel-blog-tag"
string(15) "travel-blog-tag"
string(15) "travel-blog-tag"
string(15) "travel-blog-tag"
string(15) "travel-blog-tag"
string(15) "travel-blog-tag"
string(15) "travel-blog-tag"
string(15) "travel-blog-tag"
string(15) "travel-blog-tag"
string(15) "travel-blog-tag"
string(15) "travel-blog-tag"
string(15) "travel-blog-tag"
string(15) "travel-blog-tag"
string(15) "travel-blog-tag"
string(15) "travel-blog-tag"
string(15) "travel-blog-tag"
string(15) "travel-blog-tag"
string(15) "travel-blog-tag"
string(15) "travel-blog-tag"
string(15) "travel-blog-tag"`

**Comment by Levdbas** [comment]
Stale issue, closing
