### ISSUE TITLE
How to get post Using SWP_Query

### ISSUE THREAD

**Issue by rvpatel** [timber/timber#1991]
Hey, that was actually a bit of a trick, sorry. Please post your question to [StackOverflow](http://stackoverflow.com/questions/tagged/timber) using the Timber tag. To help us keep (or start to keep) the Issues section a bit cleaner, we're going to close support question-ish issues. StackOverflow is the best place for these — thanks!

> 
> $swp_query = new SWP_Query(array('s' => get_search_query(),'posts_per_page' => -1,) );
> $context['posts'] = $swp_query->posts;
> 

We can not customize data with Timber::get_posts() Please help for this

**Comment by palmiak** [comment]
Take a look at
https://github.com/timber/timber/issues/1590#issuecomment-346571429

Get posts ids from swp_query and pass them to timber::get_posts

czw., 9 maj 2019, 16:53 użytkownik Ravi Patel <notifications@github.com>
napisał:

**Comment by rvpatel** [comment]
Thanks but what's happens when ids list more then >500? 
I hope maybe a solution arrived in the future when having customization Query.

**Comment by palmiak** [comment]
You can set posts_per_page in SWP_Query so you can prevent too much ids.

Either way 500 posts at once is a bad idea. Better get them batch by batch
and either use pagination or some infinite scroll


pt., 10 maj 2019, 16:37 użytkownik Ravi Patel <notifications@github.com>
napisał:
