### ISSUE TITLE
Rendered template called with AJAX doesn't include content in if statements

### ISSUE THREAD

**Issue by dnnsjsk** [timber/timber#1993]
Hey,

I need to reload my header.twig dynamically with AJAX and noticed that it is getting rendered without any if statements. 

Here is my AJAX function:
```
add_action('wp_ajax_spx_replace_header', 'spx_replace_header');
add_action('wp_ajax_nopriv_spx_replace_header', 'spx_replace_header');

function spx_replace_header()
{
    $context = Timber::get_context();
    Timber::render('templates/header.twig', $context);
}
```

And for reference my JS:
```
window.addEventListener('load', function() {
    jQuery.ajax({
        type: "POST",
        url: "/wp-admin/admin-ajax.php",
        data: {
            action: 'spx_replace_header',
        },
        success: function (data) {
            console.log(data);
        }
    });
})
```
The part that is not getting rendered by the call is inside an if statement:

```
{% embed "objects/header.twig" with {'hamburger': 'hamburger--spring'} %}
{% endembed %}

{% if fn('is_single') %}
    <div class="progress"></div>
{% endif %}

{% embed "objects/header.twig" with {'id': '--sticky', 'hamburger': 'hamburger--spring'} %}
{% endembed %}
```

Am I missing something or is this a bug?

## What version of WordPress, PHP and Timber are you using?
Wordpress 5.1, Timber 1.9.4

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Installed via composer

Best,
Dennis

PS: Thanks for this amazing plugin!

**Comment by aj-adl** [comment]
Hey Dennis, 

You're making a call to `wp-admin/admin-ajax.php`, so conditionals like `is_ajax()` will return true but `is_single()` will definitely not.

Remember that PHP shuts down at the end of each request, discarding state etc, so the call to the `admin-ajax.php` script is a completely isolated process from the one that's delivered the initial markup for the page, and doesn't know what page it's being called from etc

For this reason, you'd want to pass in any data you'd need for conditionals, probably as a query string parameter.
 
```php
add_action('wp_ajax_spx_replace_header', 'spx_replace_header');
add_action('wp_ajax_nopriv_spx_replace_header', 'spx_replace_header');

function spx_safe_get_string( $key )
{
    if ( ! isset( $_GET[ $key ] ) ) return '';
   return sanitize_text_field( $_GET[ $key ] );
}

function spx_replace_header()
{
    $context = Timber::get_context();
    // Set this in the context, so we can access it in our twig file easily
    $context[ 'type' ] = spx_safe_get( 'my_page_type' );
    Timber::render('templates/header.twig', $context);
}
```

```javascript
window.addEventListener('load', function() {
    jQuery.ajax({
        type: "POST",
        url: "/wp-admin/admin-ajax.php",
        data: {
            action: 'spx_replace_header',
            my_page_type: 'single',
        },
        success: function (data) {
            console.log(data);
        }
    });
})
```

```twig
{% embed "objects/header.twig" with {'hamburger': 'hamburger--spring'} %}
{% endembed %}

{% if type == 'single' %}
    <div class="progress"></div>
{% endif %}

{% embed "objects/header.twig" with {'id': '--sticky', 'hamburger': 'hamburger--spring'} %}
{% endembed %}
```

Hope the code is ok, githubs editor leaves a bit to be desired. Pretty safe to say this is unrelated to Timber, as this would happen in vanilla WordPress or any PHP cms.

Cheers

**Comment by dnnsjsk** [comment]
Thanks!
