### ISSUE TITLE
ACF custom menu fields not included in TimberMenu object

### ISSUE THREAD

**Issue by bramkorsten** [timber/timber#2000]
## Expected behavior
When I add custom fields to a Menu object (not the MenuItem object), I would expect to find these custom fields in `{{menu.field}}` or `menu.meta('field')`. For example, I've added a custom field that includes the logo in the menu for easy changing.

## Actual behavior
I can't find where these custom fields are stored. There seems to be no documentation on this, so researching is difficult. 

I'm using Wordpress 5.2 with ACF 5.7.9 and Timber 1.9.4

Thanks in advance for any help! If i can find the solution, I'd like to try and update the documentation for this!

EDIT: Issue #2000, what an amazing community ❤️

**Comment by bobhuf** [comment]
Looking for an answer to this myself. These menu fields (not menu item fields) are stored in the wp_termmeta table. Per the docs:
> WP stores each Menu as a term object in the wp_terms table. ACF will store all custom field values in the wp_termmeta table.

[https://www.advancedcustomfields.com/resources/adding-fields-menus/](https://www.advancedcustomfields.com/resources/adding-fields-menus/)

**Comment by jarednova** [comment]
@bramkorsten @bobhuf thanks for the notes on this — looking into it now!

**Comment by jarednova** [comment]
@bramkorsten @bobhuf this might be a very simple fix. Check out #2043 and please let me know if that resolves the issue for you (it did in my tests)

**Comment by bobhuf** [comment]
It does. Thanks, Jared!

**Comment by bramkorsten** [comment]
Works like a charm! Looking good Jared 👌👌
