### ISSUE TITLE
Adding own functions to twig

### ISSUE THREAD

**Issue by palmiak** [timber/timber#2004]
## Expected behavior

According to docs on https://timber.github.io/docs/guides/functions/  after adding

```
add_filter('timber/twig', 'add_to_twig_test');

function add_to_twig_test($twig) {
    $twig->addFunction(new Twig_SimpleFunction('test_function', 'test_function'));
    return $twig;
}

function test_function() {
	return 'tralalla';
}
```

I should be able to use `{{ test_function }}` in twig template.

## Actual behavior

But I doesn't work. It only works when I use it like this `{{ test_function() }}`.

I'm not sure is there a small bug in docs or I'm doing something wrong.

## Steps to reproduce behavior

Just add this code and try both version - with and without `()`.

## What version of WordPress, PHP and Timber are you using?

PHP 7.3, WordPress 5.2, Timber 1.9.4
## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Composer

**Comment by gchtr** [comment]
Yes, it doesn’t work, but I think that’s how it’s supposed to work. I guess it’s the difference between functions and methods that would allow you to omit parenthesis for `post.link`, but not for `get_permalink()`. Check out the Implementation Box in the [Variables section of Twig for Template Designers](https://twig.symfony.com/doc/2.x/templates.html#variables):

> ### Implementation
>
> For convenience's sake `foo.bar` does the following things on the PHP layer:
>
> - check if `foo` is an array and `bar` a valid element;
> - if not, and if `foo` is an object, check that `bar` is a valid property;
> - if not, and if `foo` is an object, check that `bar` is a valid method (even if `bar` is the constructor - use `__construct()` instead);
> - if not, and if `foo` is an object, check that `getBar` is a valid method;
> - if not, and if `foo` is an object, check that `isBar` is a valid method;
> - if not, and if `foo` is an object, check that `hasBar` is a valid method;
>if not, return a null value.
>
> Twig also supports a specific syntax for accessing items on PHP arrays, foo['bar']:
> 
> - check if `foo` is an array and `bar` a valid element;
> - if not, return a null value.

So that tells me that when Twig sees `post.link`, it would first check if `link` is a property and then check if it’s a method.

**Comment by palmiak** [comment]
I wanted to be sure. They ommited the example of function on
https://twig.symfony.com/doc/2.x/advanced.html and in some places I saw
examples without the (). I'll grab the laptop and push a small fix to the
docs example

niedz., 19 maj 2019, 19:33 użytkownik Lukas Gächter <
notifications@github.com> napisał:
