### ISSUE TITLE
Cannot redeclare twig_array_batch()

### ISSUE THREAD

**Issue by tlygnersjo** [timber/timber#2016]
## Expected behavior
I expect the website to work without errors.

## Actual behavior
Error page with the following message:
```
The site is experiencing technical difficulties.

Fatal error: Cannot redeclare twig_array_batch() (previously declared in /path/to/website/wp-content/plugins/woocommerce-multilingual/vendor/twig/twig/lib/Twig/Extension/Core.php:1557) in /path/to/website/wp-content/plugins/timber-library/vendor/twig/twig/src/Extension/CoreExtension.php on line 1667
```

## Steps to reproduce behavior
Run a WordPress website with WPML (including WooCommerce Multilingual) with Timber plugin. Update from Timber 1.9.4 to 1.9.5

## What version of WordPress, PHP and Timber are you using?
WordPress 5.2.1
PHP 7.1.29
Timber 1.9.5

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Upgraded to newest version via plugin updater in WordPress dashboard

**Comment by tlygnersjo** [comment]
Could it be a function name (twig_array_batch) which is the same in WooCommerce Multilingual and Timber?

**Comment by gio00** [comment]
Yes, same error here. I reinstalled the 1.9.4 and everything works again. I guess must be some twig version loaded twice.

**Comment by jarednova** [comment]
Thanks @tlygnersjo, @gio00  — I think this is related to #2020. I'm investigating today ...

**Comment by tlygnersjo** [comment]
Thanks @jarednova sounds like The sme issue. I can confirm that downgradingto 1.9.4 solves the issue

**Comment by jarednova** [comment]
@tlygnersjo @gio00 I'm pretty confident this is an issue with a collision of Twig versions. Can you replace your `wp-content/plugins/timber-library` directory with this test version and see if that resolves the issue?

https://www.zipshare.com/download/eyJhcmNoaXZlSWQiOiI3YzVhMjY0NS0yNGQwLTQ3NjQtYmQyZC1mMWQxNjBkNTYzMzYiLCJlbWFpbCI6ImphcmVkQHVwc3RhdGVtZW50LmNvbSJ9

**Comment by coreylafferty** [comment]
@jarednova That fixes the issue for me (tested on a new WP install with just my theme and the Timber plugin installed).

**Comment by gio00** [comment]
@jarednova I get `Fatal error: Uncaught Error: Class 'Twig\Loader\FilesystemLoader' not found in /home/polione/Projects/gast/wp-content/plugins/timber-library/lib/Loader.php....`. I removed the 1.9.4 and extract the zip in `/wp-content/plugins/`

**Comment by jarednova** [comment]
So after further investigation, it seems that the issues here are overlapping but down to a central problem: WPML's Twig conflicts with Timber's Twig. From my testing, the issue only manifests itself with the WooCommerce and WooCommerce Multilingual plugin running.

Unfortunately, attempting to rollback our Twig version (which seems to solve the issue under some limited circumstances) creates a chain of other issues that need to be resolved.

I'm going to release 1.10.0 as a version that does NOT work with these plugins (at least, for the time being). I'll note in the release notes to hopefully prevent developers from upgrading and then getting frustrated. So what should you/they do? I recommend using 1.9.3 — this seems to be stable before these various WPML / WooCommerce issues started. 

We're in talks via email with the WPML team to hopefully figure out a long-term solution to this for 1.10 and beyond

**Comment by jarednova** [comment]
Good news! A new WPML release is coming very soon to resolve Twig version conflicts. I'll post once it's released (and I've had a chance to test)

**Comment by jarednova** [comment]
Great news to anyone following this thread! As of 4.2.8 WPML no longer ships with Twig — which means no more version conflicts!
