### ISSUE TITLE
TimberPost should use PostGetter::get_post_class instead of relying on second argument

### ISSUE THREAD

**Issue by kshaner** [timber/timber#2033]
When using {{TimberPost}} inside a twig file, an instance of `\Timber\Post` is returned regardless of whether a PostClassMap filter exists.

Ideally, the TimberPost php implementation would make the `$PostClass` argument optional and call `PostGetter::get_post_class` as a default while still retaining the ability to specify the class manually.

Would you welcome a pull request for this feature?

**Comment by jarednova** [comment]
@kshaner I'm totally open to seeing a PR. If it's pretty simple — go for it! But if you're finding it's a big re-write to make it happen, take a look at maybe doing the PR against the 2.x branch. We're trying to really shift our focus over there so we can get it released soon

**Comment by jarednova** [comment]
@kshaner more thoughts — I'd be interested to see where else the class map could be used. Is this something where defaults could be set at the theme level, and then (probably via a filter) used throughout Timber so a dev doesn't have to constantly re-send the value?

**Comment by kshaner** [comment]
@jarednova, Agreed wholeheartedly with this approach.  We're attempting to use it that way and have run into some strange class override scenarios, such as when using `{{post.parent}}`. It would be nice to get rid of all the $PostClass properties of the various classes and instead reply on the class map.

With this route, it may be a bigger PR and should probably target 2.x.

**Comment by jarednova** [comment]
Yeah, `{{ post.parent }}` is another good example of where that appears. I think going for 2.x makes sense. Thanks for taking this on!

**Comment by gchtr** [comment]
Hey all!

Making sure that the post class map is used in all Timber functionality while still being able to use custom classes in certain situations will be part of the object factory refactor in #1793. That would speak against making a separate pull request for this.

**Comment by kshaner** [comment]
Thanks @gchtr. That's exactly the route I would have gone. Thanks for letting me know before I started.

**Comment by jarednova** [comment]
NOW I get why the object factory PRs matter so much — thanks for clarifying @gchtr

**Comment by acobster** [comment]
See also #2073, #2090
