### ISSUE TITLE
Add pagination support to comments

### ISSUE THREAD

**Issue by jarednova** [timber/timber#2034]
## Is your feature request related to a problem? Please describe.
#554 #1205 both discuss the need for formal comment pagination

## Describe the solution you’d like
We should probably follow the pattern of `{{ post.comments({ comments_per_page: 20, page: 6}) }}` — rather than new arguments

**Comment by kilianso** [comment]
Any update on this one? I'm trying to get comment pagination done by limiting the output of the comments like this:

```
{% for comment in post.comments(10) %}
     {{comment.content}}
{% endfor %}
```
Below that, i try to call `{{function('previous_comments_link', 'More comments')}}` (or the next link) but no button gets shown.

And if i check how many comment pages there are like this: `{# {{function('get_comment_pages_count', post.comments, 10)}} #}` – i get the correct number.

What am i missing?

**Comment by Levdbas** [comment]
Since 2019 this ticket did not get that much traction. I have a feeling that comments aren't really used by loads of Timber users so I am doubting that we need to put more time into this. If anyone still feels a need to implement this, feel free to submit a PR against the 2.x branch.

**Comment by kilianso** [comment]
For anyone stumbling across this issue. I was never able to solve pagination directly in Timber. But i found a workaround calling `{{function('comments_template')}}` in my Twig file to use the default Wordpress comments including pagination.
