### ISSUE TITLE
__toString() must not throw an exception

### ISSUE THREAD

**Issue by Beee4life** [timber/timber#2035]
## Expected behavior
Not seeing errors thrown :)

## Actual behavior
An error is thrown.

`PHP Fatal error:  Method Timber\FunctionWrapper::__toString() must not throw an exception, caught Error: Call to undefined function get_current_screen() in /Users/Beee/HTML/pgt/web/app/plugins/timber-library/vendor/twig/twig/src/Environment.php(497) : eval()'d code on line 0`

## Steps to reproduce behavior
I updated to 1.10.0 with ACF activated. I noticed when I opened a page which had a [front-end editing form](https://www.advancedcustomfields.com/resources/create-a-front-end-form/).

## What version of WordPress, PHP and Timber are you using?

WP 5.2.1 - installed with composer
Php 7.2 - installed with composer
Timber 1.10.0 - installed with composer

**Comment by palmiak** [comment]
`get_current_screen` only works in admin panel - it should wrapped in ` if( is_admin() ){}` to be sure it won't be loaded on the front - more info https://codex.wordpress.org/Function_Reference/get_current_screen .

It look's like it's loaded somewhere by the ACF or there is some bug in your code which leads to loading this function.

**Comment by Beee4life** [comment]
ACF support replied to me in a few separate emails...

```
We came across a similar error in the plugin but this should be fixed in the latest version that you are currently running.
I believe that the guys from Timber will be able to patch this from their end too.
```
Not sure where the error lies exactly since they speak about both plugins doing some sort of fix.

AFAIK they (ACF) made a fix to a 'active' version. So they patched v5.8.1 if I understood correctly.

**Comment by palmiak** [comment]
Are you using the acf pro version or the free one?

śr., 19 cze 2019, 09:46 użytkownik Beee <notifications@github.com> napisał:

**Comment by Beee4life** [comment]
PRO (of course) :)

**Comment by palmiak** [comment]
I just did a quick test - it works on 5.7.x and 5.8.x (PRO) - I have added `{{ function('acf_form')}}` to front-page.twig and of course acf_head to header. No errors.

I would need some more help to replicate this bug.

**Comment by Beee4life** [comment]
ACF said they fixed it... And from their reply I deduce they have intel about the the Timber people being in on it ? 

So why do you want to replicate it ?

**Comment by palmiak** [comment]
Oh I thought you still have this problem even with the newest version.

śr., 19 cze 2019, 10:03 użytkownik Beee <notifications@github.com> napisał:

**Comment by Beee4life** [comment]
Nope... I haven't been able to test anything yet...
