### ISSUE TITLE
ACF Flexible content

### ISSUE THREAD

**Issue by GydoVerbeek** [timber/timber#2036]
Hi,

I've created a flexible content group with a repeater.
When I debug the `post.meta('content_section')` it's only returning an array of the layout.
When I try to `{% if media_item.acf_fc_layout == 'intro_video' %}` it's not working.

What is going wrong? Is this a bug?
Please help...

**Versions**
Wordpress: 5.2.1
ACF: 5.8.1
Timber: 1.10.1

**Comment by palmiak** [comment]
Could you show us the PHP and twig code?

pon., 17 cze 2019, 12:39 użytkownik GydoVerbeek <notifications@github.com>
napisał:

**Comment by GydoVerbeek** [comment]
Hi Palmiak,

We use the MVC framework of Spinion.
getPost uses the default Timber::get_post();

**PHP**
`$this->addContext( 'post', $this->getPost() );
$this->render( 'page/home' );`

**Twig**
`{% for media_item in post.meta('content_sections') %}`
    `{% if media_item.acf_fc_layout == 'intro_video' %}`
        {{ media_item.title }}
    {% endif %}
{% endfor %}`

**Comment by gchtr** [comment]
Did you initialize Timber with `new Timber\Timber();` in functions.php (https://timber.github.io/docs/getting-started/setup/#via-github-for-developers)? This will set up the proper filters for ACF, and it looks like those filters don’t work in your case.

**Comment by GydoVerbeek** [comment]
Thanks alot @gchtr
