### ISSUE TITLE
Pagination not working anymore?

### ISSUE THREAD

**Issue by Kreativschnittstelle** [timber/timber#2037]
## Expected behavior
I am having a timber pagination for a custom post type and it works without problems with older versions, for example 1.8.4. The code is equal to the one in the docs (the one without the default query).

## Actual behavior
It seems to have stopped working with latest version(s). The pagination doesn't show anymore, because it doesn't contain the pages. Output of a dump:

`object(Timber\Pagination)#9519 (5) { ["current"]=> int(1) ["total"]=> float(0) ["pages"]=> array(0) { } ["next"]=> string(0) "" ["prev"]=> string(0) "" }`

## Steps to reproduce behavior
Just follow tutorial for non default query:
https://timber.github.io/docs/guides/pagination/

## What version of WordPress, PHP and Timber are you using?
WordPress 5.2.2, PHP 7.0.32, Timber 1.9.2

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Download the plugin from wp.org

**Comment by marciojc** [comment]
Its working fine at last version 1.10.1

**Comment by Kreativschnittstelle** [comment]
> Its working fine at last version 1.10.1

When will it be available on wp.org?

**Comment by jarednova** [comment]
@Kreativschnittstelle we're waiting for an WPML that will align Twig versions — then everything will be deployed to WP.org

**Comment by gchtr** [comment]
Since version 1.10.1 has long been released, I guess this can be closed.
