### ISSUE TITLE
Minify html output 

### ISSUE THREAD

**Issue by raphaguasta** [timber/timber#2038]
Hello guys!

I wish to minify the html output of my website, to improve performance and loading time.

I didn't found anything in the docs to do this, can you help me?

Thanks! :)

**Comment by jarednova** [comment]
@raphaguasta this is something that seems best for a caching plugin or another tool that's focused on performance optimizations. If this is something you're up for looking into, I'd love to add a section to the docs that explains some best practices to help others in the future!

**Comment by palmiak** [comment]
I also agree this is more plugin territory, but if you prefer to do it with twig than there is https://github.com/nochso/html-compress-twig/. I didn't test it but I would love here is working correct.

**Comment by bobhuf** [comment]
It won't compress everything (JS e.g.) but could use the spaceless twig filter or tag: https://twig.symfony.com/doc/2.x/tags/spaceless.html

**Comment by danburzo** [comment]
I'm of the opinion you should not bother to minify your HTML — as long as the server GZIPs the request, you'll get _very little_ extra by minifying the HTML. Especially on a WordPress website, that would be my least concern. 

If you were to do it, I second the opinion this should happen at a level above Twig, possibly with a plugin dedicated to performance optimizations. Intuitively: at the Twig level, you're incurring more work for the library and you might end up with poorer performance; the problem with Twig extensions / filters / tags is you're looking to minify the _dynamic_ content as well, so even enabling the Twig cache won't (I think) preclude it from doing runtime minification of the content you place in your Twig templates.

**Comment by gchtr** [comment]
> It won't compress everything (JS e.g.) but could use the spaceless twig filter or tag: [twig.symfony.com/doc/2.x/tags/spaceless.html](https://twig.symfony.com/doc/2.x/tags/spaceless.html)

That filter is specifically *not meant to minify your output*, as the documentation says itself:

> This tag is not meant to "optimize" the size of the generated HTML content but merely to avoid extra whitespace between HTML tags to avoid browser rendering quirks under some circumstances.
> 
> If you want to optimize the size of the generated HTML content, gzip compress the output instead.

@danburzo sums it up very well 👍.

I totally agree that we could add some more clarifications in the doc with a list of useful caching plugins and a hint about the spaceless tag in Twig and why you shouldn’t use it.

I assigned this to myself so I can eventually take care of it. If somebody else wants to take this over, feel free to comment here so that we know you’re working on this.

**Comment by jl-a** [comment]
A solution is to use the `timber/output` filter with html-compress https://packagist.org/packages/wyrihaximus/html-compress

Once the html-compress package is installed with Composer, use:

```
class Minify {

    private $parser;

    function __construct() {
        add_filter( 'timber/output', [ $this, 'minify' ], 3, 10 );
        $this->parser = \WyriHaximus\HtmlCompress\Factory::constructSmallest();
    }

    function minify( $output, $data, $file ) {
        return $this->parser->compress( $output );
    }

}
new Minify();
```

The `timber/output` filter is run at the completion of each twig compilation, so this simply minifies the compiled HTML.
