### ISSUE TITLE
Install instructions with composer do not work if followed exactly

### ISSUE THREAD

**Issue by joepetrakovich** [timber/timber#2039]
## Expected behavior
I expect if I use:

`composer require timber/timber`

that Timber will be added to my plugins directory.  The setup instructions suggest that if using the starter theme, that I will be able to activate Timber via wp-admin/plugins.php, but I cannot because it is not there.

## Actual behavior
composer only installs files to vendor/ but the starter-theme is not able to be activated.

## Steps to reproduce behavior
run composer require timber/timber
notice that it simply pulls everything into the vendor/ directory
download the starter-theme and put it in the /themes directory
attempt to activate the theme via the admin panel
you'll get an error that Timber is not activated but there is no way to activate it.
 
## What version of WordPress, PHP and Timber are you using?
WordPress 5.2.2, PHP 7.2.9, Timber 1.10.1

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
`composer require timber/timber`

**Comment by jarednova** [comment]
@joepetrakovich thanks for this issue. I can see how that could be confusing. When you said you followed the "setup instructions" can you point me to the particular URL? There are a few out there, so I want to make sure we review/edit the right one

**Comment by joepetrakovich** [comment]
https://timber.github.io/docs/getting-started/setup/

**Comment by jarednova** [comment]
Totally hear you @joepetrakovich. That's one of those things that we can get blind to because we've done it 100x times. I think you've got the right idea in your comment. Would you be up for taking a pass at the markdown and submitting a PR?

https://github.com/timber/timber/blob/master/docs/getting-started/setup.md

That way, your name can live in infamy! (that is, the GitHub contributor statistics)

**Comment by joepetrakovich** [comment]
Okay, yes let me test my theory and then I'll make the changes later today.

**Comment by jarednova** [comment]
sounds good! Your basic idea there that the theme is the composer "project" is correct. Command line stuff like `composer require`... works similar to `npm install`

**Comment by jarednova** [comment]
Closed via #2040
