### ISSUE TITLE
Gutenberg plugin and timber error

### ISSUE THREAD

**Issue by MDSilviu** [timber/timber#2044]
I'm using timber with the gutenberg plugin https://wordpress.org/plugins/gutenberg/ . 
While the plugin is activate i'm getting this fatal error in the frontend

```
( ! )  Fatal error: Uncaught Error: Call to a member function query() on null  in  D:\xampp\htdocs\wordpress79\wp-content\plugins\gutenberg\lib\client-assets.php  on line 58
--
1 | 0.2015 | 386528 | {main}(  ) | ...\index.php:0
2 | 0.2019 | 388264 | require( 'D:\xampp\htdocs\wordpress79\wp-blog-header.php' ) | ...\index.php:17
3 | 0.5153 | 23547248 | require_once( 'D:\xampp\htdocs\wordpress79\wp-includes\template-loader.php' ) | ...\wp-blog-header.php:19
4 | 0.5176 | 23549016 | include( 'D:\xampp\htdocs\wordpress79\wp-content\themes\mds-rwinvest\page.php' ) | ...\template-loader.php:78
5 | 0.5712 | 23716160 | Timber\Timber::render(  ) | ...\page.php:15
6 | 0.5712 | 23716160 | Timber\Timber::fetch(  ) | ...\Timber.php:404
7 | 0.5712 | 23716160 | Timber\Timber::compile(  ) | ...\Timber.php:377
8 | 0.5752 | 23779648 | Timber\Loader->render(  ) | ...\Timber.php:333
9 | 0.5920 | 24737984 | Twig\Environment->render(  ) | ...\Loader.php:74
10 | 0.7128 | 26048832 | Twig\TemplateWrapper->render(  ) | ...\Environment.php:318
11 | 0.7128 | 26048832 | __TwigTemplate_7a3554c3afee6855d7e1397cba8caeb9b32a7eca08264e975076cad68c515daa->render(  ) | ...\TemplateWrapper.php:45
```

The problem comes from 
```php
global $wp_scripts;
$script = $wp_scripts->query( $handle, 'registered' );
```

In the page.php i only have 
```php
$context = \Timber\Timber::get_context();
\Timber\Timber::render('page.twig', $context );
```
Is there any way to fix this without deactivating the plugin?

**Comment by jarednova** [comment]
@MDSilviu based on what you have here, I'm not sure where the problem lies. You mention that you're suing the Gutenberg plugin. Is there a reason you're not using the one that ships with WP core in 5.x?

**Comment by gchtr** [comment]
@MDSilviu For me, it works fine when I use the latest version of the Gutenberg plugin. Can you check if you have other plugins installed that might conflict with Gutenberg? If `$wp_scripts` is `null`, it could be that a plugin or some functionality (an action or a filter) in your theme overwrites that global.

**Comment by MDSilviu** [comment]
@jarednova I'm using the plugin because it has the latest release, the latest wp doesn't include it yet and it's really behind really and want to use the latest features and improvements because i'm creating custom blocks and the core library it's missing some nice stuff.

@gchtr i'm only using carbon-fields and safe-svg in a custom startert theme based on underscore. If i remove timber render from the page.php everything works fine even with those plugins activated.

As a quick fix i edited the plugin and remove the action that was including the scripts and styles in the frontend too

**Comment by gchtr** [comment]
@MDSilviu It makes sense that everything works if you remove `Timber::render()`, because that’s where a lot of things happen. A lot of actions are being called here, including `wp_enqueue_scripts` for example, which handles most of the script logic.

If you’ve deactivated your plugins and the problem still exists, it might very well be in your theme. To figure what exactly causes the problem, you need to try and deactivate theme functionalities one by one and see whether the error goes away.

It’s never a good idea to edit plugins or core files, because then you’re just solving symptoms of your problems.

**Comment by Levdbas** [comment]
As a gutenberg core and plugin user I never ran into this. Can probably be closed.
