### ISSUE TITLE
post.preview not showing any preview for pages

### ISSUE THREAD

**Issue by joezimdelta** [timber/timber#2045]
## Expected behavior
When using `{{ post.preview }}` on my search results page, it should show some content like `{{ post.get_preview() }}` does for excerpts of pages.

## Actual behavior
I get an empty string or nothing (not really sure) from `{{ post.preview }}` but `{{ post.get_preview() }}` gives me the excerpt as I'd expect. This is only happening for pages. For blog posts, `post.preview` works just fine.

## Steps to reproduce behavior
In search.php I have 

```php
global $s;

$context = \Timber\Timber::get_context();
$context['posts'] =  new \Timber\PostQuery();
$context['pagination'] = \Timber\Timber::get_pagination();
$context['search_term'] = $s;
$context['seo_noindex'] = true;

\Timber\Timber::render('search.twig', $context);
```

In my Twig template I have

```twig
{% for result in posts %}
  <h2 class="h3">{{ result.title }}</h2>
  <p>{{ result.get_preview(40, false, '', true, '...') }}</p>
  <p><a href="{{ result.link }}">Read More</a></p>
{% endfor %}
```

If I replace the `get_preview` call with `{{ result.preview(40).read_more('').end('...') }}` then for the results of Pages, I'll see an empty paragraph.

I'm using Elementor for the pages and not for the posts, so that might have something to do with it, but as far as I can tell, it shouldn't matter since `get_preview` works.

## What version of WordPress, PHP and Timber are you using?

Wordpress 5.1.1
PHP 7.1.26
Timber 1.9.4

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
A previous dev installed it. I assume using the functionality built into WP. I've updated it since then using the built-in updater on WP.

**Comment by palmiak** [comment]
Hi, just to be sure. If you turn off elementor does the problem still exist?



śr., 17 lip 2019, 22:49 użytkownik Joe Zim <notifications@github.com>
napisał:

**Comment by joezimdelta** [comment]
Yes, the problem still persists.

**Comment by jarednova** [comment]
@joezimdelta thanks for the report — looking into this now!

**Comment by jarednova** [comment]
@joepetrakovich I've copied-and-pasted your code and, unfortunately, I haven't been able to replicate the issue. As you can see the attached screenshot, content is showing up using the Twig:

`{{ result.preview(40).read_more('').end('...') }}`

![Screen Shot 2019-08-11 at 10 36 19 PM](https://user-images.githubusercontent.com/1298086/62843543-84bc0700-bc88-11e9-923d-a21aea4c9a41.png)

Not calling you crazy, but I think the problem lies somewhere else in your stack

**Comment by joepetrakovich** [comment]
@jarednova I think you tagged the wrong joe! :)

**Comment by jarednova** [comment]
doh! sorry @joepetrakovich 

@joezimdelta: please see above!

**Comment by joezimdelta** [comment]
@jarednova I tried again and it seems to be working... except changing the number doesn't change the number of words showing up... so whether I type in `preview(10)` or `preview(100)`, the preview doesn't change.

**Comment by jarednova** [comment]
yes! Well the "good" news there is I'm seeing the same issue; I'll investigate that today!

**Comment by jarednova** [comment]
Sorry, looks like that was just bad copy-and-pasting on my part:

`{{ result.preview(40).read_more('').end('...') }}` is the wrong syntax

`{{ result.preview.length(40).read_more('').end('...') }}` returns the correct result

**Comment by joezimdelta** [comment]
Alright. That's working now. I still have an odd issue though, as you can see in the screenshot: https://screencast.com/t/jLtoe1qB2Ts The first listing has 25 fewer words shown than what is configured (e.g. I say 40 and it shows 15 words. The screenshot shows 1 word since it is configured to show 26).

The culprit seems to have something to do with the 5 stars at the top of many of our pages since  every page I saw with this issue had those stars and the pages that didn't have this issue didn't have the stars.

https://screencast.com/t/ke0HtJYChd
