### ISSUE TITLE
`$data['options'] = get_fields('option');`  + WPML not working in second language

### ISSUE THREAD

**Issue by dianavila** [timber/timber#2047]
I'm working on a site using ACF for theme options and WPML for translations into a second language.
`$data['options'] = get_fields('option');` works perfectly for the first language (English), but for the second language (French), the context does not have anything for the theme options in [options].

**Comment by jarednova** [comment]
@dianavila based on the code sample here, this seems to be an ACF issue. Can you check the contents of `get_fields("option")`? That should supply the correct data to Timber's context
