### ISSUE TITLE
Set cache option globally for the render method 

### ISSUE THREAD

**Issue by Colir** [timber/timber#2052]
## Is your feature request related to a problem? Please describe.

It could be very long to turn on cache by setting expire time on each wp template.
I'm looking for a way to set cache expire time on the render method globally

## Describe the solution you’d like

Set render option in function.php like 
Timber::render_cache( $expire, $cache_mode)

## Describe alternatives you’ve considered

Or use a wp filter hook

Thank you

**Comment by danburzo** [comment]
Until this lands as a feature, what you can do is wrap `Timber::render` into a function and use that instead. For example:

```php
<?php
function my_render($templates, $context) {
  return Timber::render($templates, $context, ...cache options...);
}
```

And do a global replace of `Timber::render(` with `my_render(`.

**Comment by Colir** [comment]
@danburzo nice simple trick. 
Thank you.

**Comment by Levdbas** [comment]
Closing this as there is a solution provided.
