### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by fabdelgado** [timber/timber#2057]
It's possible render forms?, for example edit posts?

**Comment by jarednova** [comment]
@fabdelgado you mean the edit posts screen within `wp-admin`? I've never tried but you should be able to using hooks/filters ex:

```php

add_action('edit_form_after_title', function( $post ) {
  $timber_post = new Timber\Post($post);
  // do stuff
  Timber::render('my_file.twig', array( 'post' => $post) );
});
```

^^ not tested, but you get the idea
