### ISSUE TITLE
Cloned fields not being attached inside ACF Flexible Content Loop

### ISSUE THREAD

**Issue by metadiv** [timber/timber#2058]
## Expected behavior
I have created an acf field group which is then cloned into the fields of a flexible content layout. I then run 

```
{% for content in post.meta(flexible_content_field) %}
    {{content.fieldFromCloneId }}
{% endfor %}
```

This should show the content from the cloned field.

## Actual behavior
having dumped out the contents of the `content` node, none of the fields that are part of the clone are being added to its array thus no content is being displayed. (fields that are added directly to the layout are attached)

Using timber debug bar I can see that the nodes are being saved correctly to the main post context object but neither the post.meta() or post.get_field() functions are attaching them when called in the loop.

## What version of WordPress, PHP and Timber are you using?
WordPress 5.2.2, PHP 7.2, Timber  1.9.4,  ACF 5.8.3

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WP.org

**Comment by gchtr** [comment]
Some questions:

1. Is `flexible_content_field` in your Twig code a variable or is "flexible_content_field" the name of the field?
2. What do you get when you use `{{ dump(fn('get_field', flexible_content_field, post.ID)) }}`?
3. Are you using ACF Pro or the free version? The latest version of ACF seems to be 5.8.3, but you are using 1.2.1? Is that correct?

**Comment by metadiv** [comment]
HI gchtr...

1. Above code is s demo so field names given are descriptive of function. In my actual code the flexible content fields is called "blocks" so the actual call would be..

```
{% for content in post.meta('blocks') %}
...
```

2. I get the exact same result as {{dump(post.meta(flexible_content_field)}}
it returns an array showing each of the layouts created but minus nodes added via the clone field)

3. I am using pro. I seem to have gotten the wrong ACF v number, I am indeed using ACF 5.83

UPDATE: So I tried something and have found a work around. When making my clone field I was selecting the "All fields from this field group" option in ACF. I have just found that if I attach each field individually to the clone it all works. Not ideal but will get me going for the moment!

**Comment by gchtr** [comment]
> I get the exact same result as {{dump(post.meta(flexible_content_field)}}
>    it returns an array showing each of the layouts created but minus nodes added via the clone field)

When you get the very same result, it would mean that the error might not be with Timber and that it could be a limitation in ACF itself.

I usually set up a single field group for each of my layouts in the flexible field group. Here’s an example for a flexible content layout for a heading. As you can see, I only added one clone field for the layout and selected *All fields from NAME field group*.

![Bildschirmfoto 2019-08-19 um 17 53 02](https://user-images.githubusercontent.com/2084481/63280021-5c489400-c2aa-11e9-969b-0c038e3f9bb5.png)

An added benefit is that you could reuse your field groups in other contexts or create flexible content field groups for different context, like for different post types.

**Comment by metadiv** [comment]
@gchtr Yes thats exactly what I am doing. I have a field group for the layout then I clone that into a flexible content field layout.

If I use the All Fields From.. though it just doesn't seem to work. I am having to add each field individually

**Comment by gchtr** [comment]
@metadiv I remember that I also had this problem once, but unfortunately I can’t remember at all how I solved it 🙈.

Are you using another plugin that might interfere with this? A plugin for multilingual support maybe?

**Comment by metadiv** [comment]
@gchtr No I don't think so... not for multilingual anyway. Oh well I guess its not the end of the world if I have to include all the fields individually but hopefully this can be patched at some point int he future.

**Comment by dnnsjsk** [comment]
Hey, just thought I chime in with some code that works for me, using cloned groups inside flexible content and nested flexible content fields.

`{% for item in post.meta('sp_home_pages') %}
                {% if item.sp_home_pages_settings.sp_home_pages_settings_toggle == 0 %}
                    <section class="c-page tabs-panel {{ item.acf_fc_layout }}"
                             id="{{ item.sp_home_pages_settings.sp_home_pages_settings_name|lower|replace(' ', '-')|replace('#', '-') }}"
                             data-index="{{ loop.index }}">
                        {% if (item.acf_fc_layout == 'sp_home_pages_lp') %}
                            {% include "layouts/l-lp.twig" %}
                        {% endif %}
                        {% if (item.acf_fc_layout == 'sp_home_pages_gallery') %}
                            {% include "layouts/l-gallery.twig" %}
                        {% endif %}
                        {% if (item.acf_fc_layout == 'sp_home_pages_music') %}
                            {% include "layouts/l-music.twig" %}
                        {% endif %}
                        {% if (item.acf_fc_layout == 'sp_home_pages_hero') %}
                            {% include "layouts/l-hero.twig" %}
                        {% endif %}
                        {% if (item.acf_fc_layout == 'sp_home_pages_wysiwyg') %}
                            {% include "layouts/l-wysiwyg.twig" %}
                        {% endif %}
                        {% if (item.acf_fc_layout == 'sp_home_pages_group') %}
                            {% include "components/menu.twig" with {'nested': 'yes'} %}
                            <div class="c-page__wrap c-page__wrap--nested tabs-content"
                                 data-tabs-content="{{ item.sp_home_pages_settings.sp_home_pages_settings_name|lower|replace(' ', '-')|replace('#', '-') }}-nested">
                                {% for item in item.sp_home_pages_group_fc %}
                                    {% if item.sp_home_pages_settings.sp_home_pages_settings_toggle == 0 %}
                                        <div class="c-page c-page--nested tabs-panel {{ item.acf_fc_layout }}"
                                             id="{{ item.sp_home_pages_settings.sp_home_pages_settings_name|lower|replace(' ', '-')|replace('#', '-') }}-nested-{{ loop.parent.loop.index }}-{{ loop.index }}"
                                             data-index="{{ loop.index }}">
                                            {% if (item.acf_fc_layout == 'sp_home_pages_group_lp') %}
                                                {% include "layouts/l-lp.twig" %}
                                            {% endif %}
                                            {% if (item.acf_fc_layout == 'sp_home_pages_group_gallery') %}
                                                {% include "layouts/l-gallery.twig" %}
                                            {% endif %}
                                            {% if (item.acf_fc_layout == 'sp_home_pages_group_hero') %}
                                                {% include "layouts/l-hero.twig" %}
                                            {% endif %}
                                            {% if (item.acf_fc_layout == 'sp_home_pages_group_wysiwyg') %}
                                                {% include "layouts/l-wysiwyg.twig" %}
                                            {% endif %}
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </section>
                {% endif %}
            {% endfor %}`

`sp_home_pages_settings.sp_home_pages_settings_name` - that is the cloned group followed by the field name, it works as expected for every normal and nested layout.

**Comment by Levdbas** [comment]
Closing this as stale
