### ISSUE TITLE
TimberImage returns same orginal url

### ISSUE THREAD

**Issue by firstchair** [timber/timber#2060]
Hi, 

First, best plugin there is.
Second, I have problems with resizing and converting images on production environment.
Could somebody give me a hand where I could look?

PHP 7.3 with gd
WP 5.2.2
Timber plugin 1.9.5

This:

`    <img src="{{ image.src }}"/>
    <img src="{{ image.src|resize(100 , 100) }}"/>`

 returns:

`<img src="../content/uploads/2019/08/Adviesgroep.jpg">
<img src="../content/uploads/2019/08/Adviesgroep.jpg">
`

**Comment by palmiak** [comment]
Hi

Try Image(image.src).src | resize( 200, 200 ) .

Although it would be better if you would use image id.

śr., 21 sie 2019, 15:10 użytkownik firstchair <notifications@github.com>
napisał:

**Comment by firstchair** [comment]
Thanks for the quick reply! The other developer used urls indeed instead of id's like i always do...

**Comment by palmiak** [comment]
@firstchair did changing to `{{ Image(image) | resize(100 , 100) }}` helped or do you still need assistance?

**Comment by firstchair** [comment]
@palmiak no, worked perfectly 👍
