### ISSUE TITLE
Issue with custom query and pagination

### ISSUE THREAD

**Issue by keefyhub** [timber/timber#2061]
I have a problem with Timber and paginating posts when the `posts_per_page` is higher than what the default `posts_per_page` is set at in the CMS.

EG if you have your Wordpress option set at 10 and then do a custom query (using `PostQuery()`)with 50 posts at 5 per page you will get to page 6 and get a 404 (as it is expecting pagination on 50 posts by 10 per page)

## Steps to reproduce behavior
```
$query = $GLOBALS['wp_query']->query_vars;
$query['posts_per_page'] = 4;
$posts = new PostQuery($query);
$context['posts'] = $posts;
```
also tried this
```
$context['posts'] = new PostQuery([
    'posts_per_page' => 4,
    'paged' => $paged,
    'ignore_sticky_posts' => 1
]);
$context['posts']->pagination(['mid_size' => 4]);
```

## What version of WordPress, PHP and Timber are you using?
WordPress 5.2.2, PHP 7.3, Timber dev-master

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by palmiak** [comment]
Did you thought about using pre_get_posts? It's the best solution for main
queries.

czw., 22 sie 2019, 16:08 użytkownik Keith Light <notifications@github.com>
napisał:

**Comment by keefyhub** [comment]
@palmiak,

yes overriding the `posts_per_page` in `pre_get_posts` does work. Is there a reason setting `posts_per_page` in a `PostQuery()` doesn't do this automatically for that query?

**Comment by palmiak** [comment]
No WP first detects it is out of posts so it shows a 404. Using pre gets
posts tell WP at the right moment that it should paginate be a selected
post number

czw., 22 sie 2019, 16:19 użytkownik Keith Light <notifications@github.com>
napisał:
