### ISSUE TITLE
Can not get acf field from custom post types

### ISSUE THREAD

**Issue by muuvmuuv** [timber/timber#2067]
## Expected behavior

I have created a custom post type with the "CPT UI"-Plugin and have added some custom fields with ACF. Now when I try to get the value of a field with `v.meta('video_file')` I get nothing, not even an error. Printing the hole post type shows no custom fields.

I'm querying my CPT with a simple `get_posts` but have also tried to use `WP_Query` directly. Only when I query the CPT's with `have_posts` and `get_field('video_file')` I get my custom field and when I choose "File URL" in ACF and with `{{ function('get_field', 'video_file', v.ID) }}`.

## Actual behavior

Should show custom fields.

## Steps to reproduce behavior

page-home.php
```php
<?php

/* Template Name: Homepage */

$context = Timber::get_context();

// https://developer.wordpress.org/reference/classes/wp_query/parse_query/
$filter = [
  'post_type' => 'video',
  'post_status' => 'publish',
];

$videos = get_posts($filter);
$context['videos'] = $videos;

Timber::render('pages/home.html.twig', $context);
```

home.html.twig
```html
  {% for v in videos %}
    <ul>
      <li>
        {{ v.post_title }}
      </li>
      <li>
        {{ v.post_content }}
      </li>
      <li>
        <pre>
        {{ dump(v.video_file) }}
        {{ function('get_field', 'video_file', v.ID) }}
        {{ dump(v.get_field('video_file')) }}
        {{ dump(v.meta('video_file')) }}
        </pre>
      </li>
    </ul>
  {% else %}
    No videos found.
  {% endfor %}
```

**This works** page-home.php:
```php
$the_query = new WP_Query($filter);
?>
<?php if ($the_query->have_posts()) : ?>
  <?php while ($the_query->have_posts()) : $the_query->the_post(); ?>
    <h2><?php the_title(); ?></h2>
    <div class="entry-content">
      <?php the_content(); ?>
      <?php echo "<pre>";
          var_dump(get_field('video_file'));
          echo "</pre>"; ?>
    </div>
  <?php endwhile; ?>
  <?php wp_reset_postdata(); ?>
<?php else :  ?>
  <p><?php _e('Sorry, no posts matched your criteria.'); ?></p>
<?php endif; ?>
```

## What version of WordPress, PHP and Timber are you using?

Wordpress: 5.2.3
PHP: 7.3
Timber: 1.11.0

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

via Wordpress plugin installer

**Comment by gchtr** [comment]
When you’re using `get_posts()` or `WP_Query`, you’ll get `WP_Post` objects, and not `Timber\Post` objects. Only `Timber\Post` objects have a `meta()` method that you can call directly. So, instead of

```php
$videos = get_posts( $filter );
$context['videos'] = $videos;
```

you probably want to use `Timber::get_posts()`, or `new Timber\PostQuery()`:

```php
$context['videos'] = new Timber\PostQuery( [
  'post_type'   => 'video',
  'post_status' => 'publish',
] );
```

Then, in your Twig file, you won’t have to use `post.post_title` or `post.post_content`, but you can use the optimized `post.title` and `post.content` functions.

```twig
{% for v in videos %}
    <ul>
        <li>
            {{ v.title }}
        </li>
        <li>
            {{ v.content }}
        </li>
        <li>
            <pre>
                {{ dump(v.meta('video_file')) }}
            </pre>
        </li>
    </ul>
{% else %}
    No videos found.
{% endfor %
```

**Comment by muuvmuuv** [comment]
Damn, you are right. I have totally forgotten that Timber has its own Posts query...
