### ISSUE TITLE
Recursive reference in menu object

### ISSUE THREAD

**Issue by ramiroazar** [timber/timber#2071]
## Expected behavior

The `json_encode` function should return a JSON encoded string of the menu object.

## Actual behavior

The `json_encode` function returns a boolean with the value `false`.

The `json_last_error` function returns a constant with the value `JSON_ERROR_RECURSION`.

The `var_dump` function returns a `menu` property with the value `*RECURSION*` within every menu item.

## Steps to reproduce behavior

`json_encode(new Timber\Menu());`

## What version of WordPress, PHP and Timber are you using?

WordPress 5.2.3, PHP 7.2.9, Timber 1.11.0 

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

WordPress plugin repository.

**Comment by jarednova** [comment]
@ramiroazar thanks! looking into this now ...

**Comment by jarednova** [comment]
I think this can be a pretty simple fix (albeit, with a few breaking changes that we should be mindful of). A fix is in on #2083
