### ISSUE TITLE
Timber::get_terms(): cannot get more than 10 posts from its category term

### ISSUE THREAD

**Issue by thanhsst** [timber/timber#2076]
I am using the latest version of Timber (1.11) and Wordpress (5.2.3).

This is super weird, as i don't know if it is Timber's bug. I have a custom post type and I am listing out all posts, which belong to its category term, but i don't get more than 10 posts. 

I know that the ```posts_per_page```, ```orderby``` work only on 
```Timber::get_posts();```, but why doesn't it list all the posts, even if i remove the ```posts_per_page``` or modify to ```1000```  ?

This is the query on my php file:

```php
   $args = array(
      'post_type' => 'events',
      'posts_per_page' => -1,
      'post_status'    => 'publish',
      'taxonomy' => 'event_category',
      'orderby'           => 'menu_order',
      'order'             => 'DESC'
    );
    $context['events'] =  Timber::get_terms($args);
```

This is the twig:

```twig
    {% for item in events %}
          <div id="{{item.slug}}"  class="event-wrap">
            {% for post in item.posts %}
              <h1>{{post.title}}</h1>
              <div class="agenda-content">{{post.content}}</div>
            {% endfor %}
          </div>
        {% endfor %}
```

**Comment by palmiak** [comment]
First of all - `Timber::get_terms($args);` - shouldn't you use `Timber::get_posts()` ?

On the other hand by default WP shows number of posts you set in admin panel (10 by default). So if you remove `posts_per_page` it will use 10. So setting it to `-1` should do the trick.

I'm also not sure about `'taxonomy' => 'event_category',` - you have set a taxonomy, but not a term.

All in all - first check if this will work:
```
   $args = array(
      'post_type' => 'events',
      'posts_per_page' => -1,
      'post_status'    => 'publish',
      'orderby'           => 'menu_order',
      'order'             => 'DESC'
    );
    $context['events'] =  Timber::get_posts($args);
```

**Comment by thanhsst** [comment]
`posts_per_page` not working on `Timber::get_terms($args);` and I want to use `Timber::get_posts($args);` as i cannot get term name before the for loop

**Comment by jarednova** [comment]
@thanhsst, I think what's going on here is just a confusion between these different methods:

* `Timber::get_terms` returns data on WP taxonomy items (categories, tags, custom taxonomies);
* `Timber::get_posts` returns data on WP post items (posts, pages, custom post types)

You are correct that `posts_per_page` doesn't work on `Timber::get_terms` as it's based on WordPress's [`get_terms`](https://developer.wordpress.org/reference/functions/get_terms/) method which has no concept of posts at this point. What I _think_ you might want is something with `term.posts`, this allows you to get posts within a certain taxonomy item:

```twig
{{ term.name }}
{% for item in term.posts(1000) %}
    <h1>{{ item.title }}</h1>
    <p class="agenda-place">{{ item.agenda_place }}</p>
    <div class="agenda-content">{{ item.content }}</div>
```

hope that helps!
