### ISSUE TITLE
404 template included in every session?

### ISSUE THREAD

**Issue by hamannjames** [timber/timber#2077]
This seems like a bug, but maybe it is expected behavior.

I am using Timber v1.11.0 and Wordpress v5.2.3

I am using Xdebug and qcachegrind to look for bottlenecks and I am seeing the 404.php template file being included in every session. This is causing an extraneous post object to be created in every session.

Just wondering why this template is included by default if the query is not a 404? Seems like a bug to include it before calling is_404. Is this something inherent to Wordpress?

**Comment by jarednova** [comment]
Thanks for the heads-up on this @hamannjames. I did a quick search through the relevant code and didn't see anything that _looked_ like it would call/load the 404 template (if there was going to be such a file it would probably be `lib/LocationManager.php`). If you run `twentysixteen` or another similar default WP theme, do you see the same thing occur?

**Comment by Levdbas** [comment]
Can be closed in my opnion, stale.
