### ISSUE TITLE
Twig deprectation - setEscaper

### ISSUE THREAD

**Issue by braders** [timber/timber#2081]
## Expected behavior
Timber should fully support the most recent version of Twig

## Actual behavior
We are getting hundreds of occurrences of the following deprecation in our logs:

`The  "Twig\Extension\CoreExtension::setEscaper" method is deprecated since  Twig 2.11; use "Twig\Extension\EscaperExtension::setEscaper" instead.`

This is being called 4 times per page load (as Timber sets 4 escapers). I would expect the most recent version of Timber to be using the correct method. I can see no easy way of working around this problem to suppress the issue in our log files.

## What version of WordPress, PHP and Timber are you using?
Timber 1.10.1, Twig v2.11.3, WordPress 5.2.2, 

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by jarednova** [comment]
Good news @braders ! I think we've got you covered in #2075

**Comment by gchtr** [comment]
@jarednova We covered it in #2070, but I realized it’s only for 2.x. We should probably backport this to master, too.

**Comment by jarednova** [comment]
@gchtr yes! I see — I'll get to work ...

**Comment by jarednova** [comment]
#2091 closes this; thanks for the heads-up @braders. We'll release to WP.org early next week
