### ISSUE TITLE
Implement Timber::get_menu() and Timber::get_user() methods.

### ISSUE THREAD

**Issue by acobster** [timber/timber#2089]
## Is your feature request related to a problem? Please describe.

Per #2073 and #2088, we're making `Menu`, `User`, and `Comment` constructors protected.

For more context, see the linked issues.

## Acceptance Criteria

- [x] Implement static `Timber::get_menu()` method which in turn call the appropriate factory methods (factory implementations themselves are out of scope here)
- [x] Ditto `Timber::get_user()`
- [x] Ditto `Timber::get_comment()`
- [x] Implement `Timber::get_users()` methods for getting collections. 
- [x] Ditto `Timber::get_comments()`
- [x] Determine whether we need a `::get_menus()` method? (No - see discussion.)
- [x] Determine which hooks, if any, we need to apply before instantiating `Menu` or `User` objects (should they get their own class maps?)
- [x] Implement Class Maps for `MenuItem`
- [x] Implement tests for these methods.

## Describe alternatives you’ve considered

The alternative is having an inconsistent API, which I personally don't find acceptable.

## Additional context

See #1793 for how this all got started.

**Comment by gchtr** [comment]
> * Do we need a `::get_menus()` method?

If we want to strive for completeness and consistency, we should add it. Currently, I can’t think of a use case, through. It’s going to be hard to come up with meaningful examples. Any idea?

> * Determine which hooks, if any, we need to apply before instantiating `Menu` or `User` objects (should they get their own class maps?)

In #2073, I’ve already considered a Class Maps for `User` objects, but not yet for `Menu` objects. In the same way as user objects are not associated with anything in WordPress default, menu objects are agnostic as well. The Class Map could then look like this:

```php
use MenuExtended;

add_filter( 'timber/menu/classmap', function( $class, \WP_Menu $menu ) {
    return MenuExtended::class;
}, 10, 2 );
```

More logic could also be included through Conditional Tags.

What do you think, @acobster, should I add this to #2073?

**Comment by gchtr** [comment]
I added the relevant documentation for menus in #2197. But let’s keep the main discussion and tracking of todos in here.

## Function signature for `Timber::get_menu()`

When thinking about what parameters should be allowed for `Timber::get_menu()`, I remembered there was an issue when nothing is passed to `new Timber\Menu()` in #1440. I propose to deprecate that functionality and always be explicit about which menu we want to get. I already documented that in the [Upgrade Guide](https://github.com/timber/timber/blob/2.x-docs-api-menus/docs/upgrade-guides/2.0.md#a-parameter-is-always-required) and the [Menus Guide](https://github.com/timber/timber/blob/2.x-docs-api-menus/docs/guides/menus.md#getting-menus). So the function signature could look like this:

```php
public static function get_menu( $menu, $options = [] ) {

}
```

I’m not yet sure about the other possible inputs for `Timber::get_menu()`, which are listed in the [Menus Guide](https://github.com/timber/timber/blob/2.x-docs-api-menus/docs/guides/menus.md#getting-menus).

When we introduce `Timber::get_post_by()`, we could also restrict `Timber::get_menu()` to term IDs only and introduce `Timber::get_menu_by()` for the following cases:

```php
$menu = Timber::get_menu_by( 'title', 'Primary Navigation' );
$menu = Timber::get_menu_by( 'slug', 'primary-navigation' );
$menu = Timber::get_menu_by( 'location', 'primary' );
```

That would be more consistent with the rest of the methods. What do you think?

## `Timber::get_menus()`

> > * Do we need a `::get_menus()` method?
> 
> If we want to strive for completeness and consistency, we should add it. Currently, I can’t think of a use case, through. It’s going to be hard to come up with meaningful examples. Any idea?

I actually found a use case that we use in our own projects and that I documented in https://github.com/timber/timber/blob/2.x-docs-api-menus/docs/guides/menus.md#set-up-all-menus-globally.

When we have the following code:

```php
<?php

add_filter( 'timber/context', 'add_to_context' );

/**
 * Global Timber context.
 *
 * @param array $context Global context variables.
 */
function add_to_context( $context ) {
    // Set all nav menus in context.
    foreach ( array_keys( get_registered_nav_menus() ) as $location ) {
        // Bail out if menu has no location.
        if ( ! has_nav_menu( $location ) ) {
            continue;
        }

        $menu = Timber::get_menu( $location );

        $context[ $location ] = $menu;
    }

    return $context;
}
```

It could be slightly shortened to this:

```php
<?php

add_filter( 'timber/context', 'add_to_context' );

/**
 * Global Timber context.
 *
 * @param array $context Global context variables.
 */
function add_to_context( $context ) {
    // Set all nav menus in context.
    foreach ( Timber::get_menus() as $menu ) {
		// Bail out if menu has no location.
        if ( ! $menu->theme_location ) ) {
            continue;
        }

        $context[ $menu->theme_location ] = $menu;
    }

    return $context;
}
```

I’m still not sure whether we really need `Timber::get_menus()`. I think it’s still not really necessary.

## Menu Class Maps

> In #2073, I’ve already considered a Class Maps for `User` objects, but not yet for `Menu` objects. In the same way as user objects are not associated with anything in WordPress default, menu objects are agnostic as well. The Class Map could then look like this:
> 
> ```
> use MenuExtended;
> 
> add_filter( 'timber/menu/classmap', function( $class, \WP_Menu $menu ) {
>     return MenuExtended::class;
> }, 10, 2 );
> ```
> 
> More logic could also be included through Conditional Tags.

I figured that there’s no `WP_Menu` class in WordPress that we could make use of in a Menu Class Map 😄. Instead, we maybe have a location available for the menu (See [Menu Class Maps](https://github.com/timber/timber/blob/2.x-docs-api-menus/docs/guides/class-maps.md#the-menu-class-map) documentation).

**Comment by acobster** [comment]
Hey @gchtr ! Good to be back on Timber.

> I’m still not sure whether we really need Timber::get_menus(). I think it’s still not really necessary.

Eh, I kind of agree. The other `Timber::get_*` methods for collections are really about dealing with collections of objects that exist as such across the full stack, like lists of posts. This is a nifty use-case, but it's different from those in that it's not really exposing the result of `::get_menus()` anywhere: it goes out of scope as soon as the loop finishes. So I'm not totally convinced it justifies the extra complexity. I say we keep it out for now; we can always add it later if we find a more compelling use-case. I'm going to mark that specific AC complete.

BTW, most of the links in your last comment are 404ing, did you delete the branch or something?

**Comment by acobster** [comment]
> I figured that there’s no WP_Menu class in WordPress that we could make use of in a Menu Class Map :smile: . Instead, we maybe have a location available for the menu (See Menu Class Maps documentation).

Can't find the docs you're referring to, so I assume you mean that the second arg to the hook would be something like `string $location`? That's a decent proxy for Menu, but it would couple menu implementations to specific locations, and if I understand correctly it would also mean that callbacks could not distinguish between multiple menus that don't have locations set.

Wouldn't it be more generic to dispatch on what `wp_get_nav_menu_object()` returns? Apparently this is actually a `WP_Term` object, which is a little weird, but hey, being honest about what WP is doing under the hood is not necessarily a bad thing. This also means that `MenuFactory` can be super thin and just forward the `$options` to the hook/constructor. I'm going to try this approach out and report back.

**Comment by gchtr** [comment]
> I say we keep it out for now; we can always add it later if we find a more compelling use-case. I'm going to mark that specific AC complete.

That sounds good to me 👍 

> BTW, most of the links in your last comment are 404ing, did you delete the branch or something?

The branch was already merged into #2073 in #2197. I added some link updates to my answer abvoe.

> That's a decent proxy for Menu, but it would couple menu implementations to specific locations, and if I understand correctly it would also mean that callbacks could not distinguish between multiple menus that don't have locations set.

That’s true, I didn’t think of that yet! I like your proposal to get a `WP_Term` object in return. 👍

It will still be possible to compare with theme location. I will add an example in the documentation.

Updates come in a separate pull request.

**Comment by acobster** [comment]
@gchtr so there's a bit of a snag with this approach. Take a look at the current `Menu` constructor:

```php
public function __construct( $slug = 0, $options = array() ) {
		// do a bunch of stuff to try to figure out $menu_id

		if ( $menu_id ) {
			// ok great
			$this->init($menu_id);
		} else {
			// not as great :/
			$this->init_as_page_menu();
		}
	}
}
```

The `init_as_page_menu` method doesn't actually pull a `nav_menu` term from the database, it just queries for pages in menu order:

```php
	protected function init_as_page_menu() {
		$menu = get_pages(array('sort_column' => 'menu_order'));
		if ( $menu ) {
			foreach ( $menu as $mi ) {
				$mi->__title = $mi->post_title;
			}
			// btw this function is marked as internal and not part of WP's API
			_wp_menu_item_classes_by_context($menu);
			if ( is_array($menu) ) {
				$menu = $this->order_children($menu);
			}
			$this->items = $menu;
		}
	}
```

The problem here isn't with representing the "menu" as a list of pages per se, it's just that we don't really have a `WP_Term` to pass to `build` - and more importantly to the `timber/menu/classmap` hook - anymore. I guess the next best thing is to just drop the type hint from the `$term` argument from `build`, and document that it'll be either a `WP_Term` instance or an array of pages that get passed to the hook? Or is there a way we can still get a `WP_Term` object without getting too hacky? Not really sure what to do here.

**Comment by gchtr** [comment]
@acobster I see. I think I wouldn’t use the `timber/menu/classmap` filter for this. And I wouldn’t mock a `WP_Term` object either.

Getting menus from pages is quite a special case. Maybe we should handle that separately. My hunch is that `init_as_page_menu()` should never be called automatically when you use `Timber::get_menu()`. We should probably call it explicitly, maybe through `Timber::get_menu_from_pages()` or `Timber::get_pages_menu()`. That would also solve #1440. You could predict much better what you get in return. If a menu can’t be found with the parameter you pass in, you should get nothing in return.

And then, we could maybe add another class map for menus that are built from pages. We could call it `timber/menu/classmap/pages` or `timber/menu/pages/classmap`.

What do you think? Also, what does @jarednova think about a separate API for building a menu from pages?

**Comment by acobster** [comment]
> And then, we could maybe add another class map for menus that are built from pages. We could call it timber/menu/classmap/pages or timber/menu/pages/classmap.

Ah, that did occur to me as well, and I dismissed it as surprising/unwieldy. But paired with your explicit `Timber::get_menu_from_pages()` idea, I find it more convincing. I'd also be curious to hear what Jared thinks.

I like the separate hook idea as well. What about `timber/pages_menu/classmap`? That would match up with a `Timber\PagesMenu` class. If we go that route, I think should `PagesMenu` should _not_ extend `Menu`, since `Menu` extends `Term` and in this case there's no underlying WP term.

**Comment by gchtr** [comment]
> I like the separate hook idea as well. What about `timber/pages_menu/classmap`? That would match up with a `Timber\PagesMenu` class. If we go that route, I think should `PagesMenu` should _not_ extend `Menu`, since `Menu` extends `Term` and in this case there's no underlying WP term.

Yeah, using a separate class to handle this would make sense to me, too. 👍

So:

- A `Timber\PagesMenu` class.
- A `timber/pages_menu/classmap` filter.
- A `Timber::get_pages_menu()` function.

When we get @jarednova’s go, I’ll come up with the relevant documentation as well as the notes in the Upgrade Guide for this.

**Comment by jarednova** [comment]
@acobster of course! there's always something, huh? I think it's correct to observe the pages menu as a special case that shouldn't interfere with the "main" use of the Menu class. WP handles them very differently, and I don't think it's wise/worthwhile to bend heaven + earth to make them somehow act the same in Timber (which could be nice in some cases; and annoying in just as many).

All of this is to say, the list that @gchtr lays out is 👍 
> * A `Timber\PagesMenu` class.
> * A `timber/pages_menu/classmap` filter.
> * A `Timber::get_pages_menu()` function.

The key is consistency, so we should always use `pages_menu` in both code and documentation so that we can keep this nuance easy to find and follow (which makes me think, should the class be named `Timber\Pages_Menu`)?

**Comment by acobster** [comment]
> should the class be named `Timber\Pages_Menu`

I don't think so. The convention in Symfony, Ruby on Rails, and many other ecosystems is that `words_in_snake_case` get translated to `WordsInCamelCase` and I don't see a reason to break from that.

**Comment by jarednova** [comment]
Touche! Just want to make sure we're following convention and not going alone. `Timber\PagesMenu` is good w me then!

**Comment by acobster** [comment]
> there's always something, huh?

If it's not one thing, it's another! :laughing:

**Comment by acobster** [comment]
@gchtr @jarednova OK, one more thing to do on this issue before I open a PR: `MenuItem`. 1.x uses the old `Menu::$MenuItemClass` construct which I'd like to replace with a Factory/Class Map for consistency. However, since `MenuItem` is not "top-level" in the sense that e.g. `Menu` and `Post` are, I am **_not_** going to implement a `Timber::get_menu_item()` method, and instead call the Factory directly from within `Menu` for setting up items internally. Sound ok to you?

**Comment by gchtr** [comment]
> I am **_not_** going to implement a `Timber::get_menu_item()` method, and instead call the Factory directly from within `Menu` for setting up items internally. Sound ok to you?

Sounds good to me! I think we don’t need a `Timber::get_menu_item()` method.

**Comment by jarednova** [comment]
yup good with me too @acobster !
