### ISSUE TITLE
Eliminate all direct instantiations of Timber\Core objects outside of Factories

### ISSUE THREAD

**Issue by acobster** [timber/timber#2094]
As part of the new API proposed in #2073, we're [making Core constructors protected](https://github.com/timber/timber/issues/2088). But first, we need to make sure we're not directly instantiating these objects outside of factories, or else...

✨ **Everything Will Break!** ✨

Replace all direct instantiations with calls to `Timber::get_post()` and friends.

**Comment by acobster** [comment]
@jarednova @gchtr how would y'all feel about dropping the default `'hide_empty' => false` param when querying for terms, e.g.

```php
Timber::get_terms('tags');
Timber::get_terms(['taxonomy' => 'tags']);
```

I get where this is coming from, but keeping track of two levels of defaults makes things trickier from a user's perspective. If folks want to include "empty" terms they can always pass `'hide_empty' => false` explicitly, and we'd just need to make a note of that in the upgrade guide.

**Comment by jarednova** [comment]
Yeah, I think I included that for Very Good Reasons™ at some point, but this feels like a great time to simplify things and use WP defaults (yeah, keeping track of "two sets of defaults" highlights that it's just adding complexity) — I say drop it!

**Comment by acobster** [comment]
Alright - assuming you're on board, @gchtr, can you add that to the upgrade guide?

**Comment by gchtr** [comment]
> Alright - assuming you're on board, @gchtr, can you add that to the upgrade guide?

I agree with Jared. Dropping it feels like the right thing to do. I already added a note to the Upgrade Guide.

**Comment by acobster** [comment]
```
⚙ (2.x-posts-api) ~/vvv/www/timber $ grep -r --include=*.php --exclude-dir=wordpress --exclude=test-timber-post-getter.php 'new \\\?\(Timber\\\)\?Post( \?' .
⚙ (2.x-posts-api) ~/vvv/www/timber $ grep -r --include=*.php --exclude-dir=wordpress --exclude=test-timber-post-getter.php 'new \\\?\(Timber\\\)\?Attachment( \?' .
⚙ (2.x-posts-api) ~/vvv/www/timber $ grep -r --include=*.php --exclude-dir=wordpress --exclude=test-timber-post-getter.php 'new \\\?\(Timber\\\)\?Image( \?' .
⚙ (2.x-posts-api) ~/vvv/www/timber $ 
```

Done on `2.x-posts-api` branch.
