### ISSUE TITLE
Document migration from plugin version to Composer version

### ISSUE THREAD

**Issue by gchtr** [timber/timber#2095]
As mentioned in https://github.com/timber/timber/pull/2005#issuecomment-518356963, we should a better migration docs for migrating from the plugin version to the Composer version of Timber.

> ... and of course as @gsalkin notes, we'll be sure to document a migration path and on-boarding materials.

@jarednova What exactly do you mean with "on-boarding materials"?

**Comment by jarednova** [comment]
"on-boarding materials" = the things that intro people to Timber: the readme, getting started guide, docs main page (and even articles / tutorials we might promote or create)

**Comment by gchtr** [comment]
Solved by #2240.
