### ISSUE TITLE
composer update : Illegal byte sequence

### ISSUE THREAD

**Issue by romainmenke** [timber/timber#2099]
## Expected behavior
Expected `composer update timber/timber` to pass without errors or notices.

## Actual behavior
```
$ composer update timber/timber
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating timber/timber (1.11.0 => 1.12.0): Downloading (100%)    Failed to execute unzip -qq  'wp-content/vendor/timber/timber/5f32a2f4faf825ba723993113dedf75a' -d 'wp-content/vendor/composer/00146520'

error:  cannot create wp-content/vendor/composer/00146520/timber-timber-25e91be/tests/assets/-�Robocop.jpg
        Illegal byte sequence
error:  cannot create wp-content/vendor/composer/00146520/timber-timber-25e91be/tests/assets/����ά���?-������-��������.jpg
        Illegal byte sequence

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class

Writing lock file
Generating autoload files
PHP CodeSniffer Config installed_paths set to ../../wp-coding-standards/wpcs
```

## Steps to reproduce behavior
`composer update timber/timber`

When trying to update to : https://github.com/timber/timber/releases/tag/1.12.0

Composer : 

> Composer version 1.9.0 2019-08-02 20:55:32

System :

> macos 10.14.6

Filesystem :

> APFS
> Case Insensitive

## What version of WordPress, PHP and Timber are you using?
WordPress 5.2.4, PHP 7.2, Timber 1.12.0

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

## Related commit :

https://github.com/timber/timber/commit/6c2797f958fee88f0fdb5f46de0282074e9545e9

## Related code in composer :

https://github.com/composer/composer/blob/2528654c53b88b490c3b78e111d068bcbe7fef61/src/Composer/Downloader/ZipDownloader.php#L105

## Thoughts :

Not sure if this is something the can/should be fixed in composer or if a better test case is possible in timber.

**Comment by danburzo** [comment]
This might be an issue with the `unzip` command: 

```
Unzip with unzip command failed, falling back to ZipArchive class
```

I can reproduce the error, but it seems ultimately the ZipArchive class handles the names well. It seems a Composer issue IMHO, but definitely if there's something we can do on the Timber side we can spare a lot of users a scare.

**Comment by romainmenke** [comment]
I agree with this not being a code bug in Timber, but more likely in Composer.

The upgrade to Timber 1.12.0 did seems successful to me, even with the notice.

**Comment by danburzo** [comment]
Maybe we can store the files in an ASCII format and rename them as part of the tests, using the _dest_ argument in TestTimberImage? 

https://github.com/timber/timber/blob/83cf568539a273dd3cfa24fecddf32246c00fc92/tests/test-timber-image.php#L23-L31

**Comment by jarednova** [comment]
I was thinking: do we really need to distribute the tests via Composer? Apparently, I'm not the first to have asked, but it's such a non-problem, there's no plan for a workaround:

https://github.com/composer/composer/issues/1750

Your solution seems pretty clean @danburzo, and pretty quick to implement

**Comment by palmiak** [comment]
I also think distributing docs and tests is a bit useless. 

Maybe we should have two repos - one "timber-dev" with everything and "timber" which is automatically build (I mean remove the stuff mentioned) on every push to master for example.

I think WP does it in the same way:
https://github.com/WordPress/wordpress-develop
https://github.com/WordPress/wordpress

**Comment by romainmenke** [comment]
Works fine now! thank you for the fast response!
