### ISSUE TITLE
500 error on upgrade to 1.12.0

### ISSUE THREAD

**Issue by daviddarke** [timber/timber#2101]
## Expected behavior
Not to throw this error on frontend or admin

## Actual behavior
I'm getting a 500 on every page. This is the error on update to 1.12.0

<img width="786" alt="Screenshot 2019-10-19 at 13 10 14" src="https://user-images.githubusercontent.com/1636310/67144829-38d2a300-f273-11e9-90a9-e3dd7848d7b3.png">

I've rolled back to  1.11.0 and everything is fine.

## What version of WordPress, PHP and Timber are you using?
Wordpress: 5.2.4
PHP: 7.1
Timber: 1.12.0

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Installed via composer

**Comment by jarednova** [comment]
@daviddarke thanks for the report! Unfortunately, I was not able to replicate. If I had to guess, this could be as simple as a Composer download that failed to complete. However, it could also be related to #2099 which we just patched. I'm about to re-deploy which will resolve if that was indeed the underlying issue
