### ISSUE TITLE
Timezone for twig date function not working as expected

### ISSUE THREAD

**Issue by columbian-chris** [timber/timber#2104]
I'm using Pacific timezone in daylight savings time in my example, which is UTC-7 hours.

Out of the box, both `{{ date('now')|date('F j, Y @ g:i a') }}` (the date _function_) and `{{ 'now'|date('F j, Y @ g:i a') }}` (the date _filter_) return UTC time with no timezone applied to them.

When I stick `date_default_timezone_set('America/Los_Angeles');` at the top of my `functions.php` theme file, the date _filter_ displays the correct current time (UTC-7), but the date _function_ is displaying UTC-14, almost like the equivalent timezone offset is being applied twice.

After reading [the Twig docs on the `date()` function](https://twig.symfony.com/doc/2.x/functions/date.html), I thought adding the following in my `functions.php` file might work, but it isn't affecting my date variables in twig:

```php
function add_to_twig( $twig ) {
	$twig->getExtension(\Twig\Extension\CoreExtension::class)->setTimezone('America/Los_Angeles');
	return $twig;
}
```

I couldn't find anything in the Timber docs about timezone usage or manipulation.  I have tried this on two different servers producing the same results.

**Comment by jarednova** [comment]
Thanks @columbian-chris — I'll take a look!

**Comment by jarednova** [comment]
@columbian-chris I can't say it makes a ton of sense, but I think this might be working as intended. Consider the following test:

```php
update_option('timezone_string', 'America/Los_Angeles');
$tz = get_option('timezone_string');
$date_format   = 'F j, Y @ g:i a';
date_default_timezone_set('America/Los_Angeles');
$pid = $this->factory->post->create(array('post_date' => '2019-10-31 12:46:41'));
$post = new TimberPost($pid);
$post_date = Timber::compile_string("{{ post.date('".$date_format."') }}", array('post' => $post));
$date_function = Timber::compile_string("{{ date('2019-10-31 12:46:41')|date('F j, Y @ g:i a', 'America/Los_Angeles') }}");
$date_filter   = Timber::compile_string("{{ '2019-10-31 12:46:41'|date('F j, Y @ g:i a') }}");
error_log('$tz = '.$tz);
error_log('post_date ='. $post_date);
error_log('date_function = '.$date_function);
error_log('date_filter = '.$date_filter);
$this->assertEquals($post_date, $date_filter);
```

You and me (normal humans) would expect that all three of these would return the same output. However, the actual output is:

```
post_date =October 31, 2019 @ 7:46 pm
date_function = October 31, 2019 @ 12:46 pm
date_filter = October 31, 2019 @ 7:46 pm
```

You'll notice that in the date_function line I explicitly say  'America/Los_Angeles' as the timezone. Yet it has no effect. Why? There's likely a Very Good Reason from the Twig folks, but I wouldn't want to hazard a guess (perhaps the difference of trying to interpret a DateTime object vs. a string?)

**Comment by columbian-chris** [comment]
@jarednova So you're suggesting this is maybe something we should be bringing to the Twig folks?

**Comment by gchtr** [comment]
The thing I found when working with dates in WordPress is, that you should always use `date_i18n()` if you can. Don’t bother with other functions that set timezones etc. And don’t bother with using Twig extensions.

**Don’t** use `time()`, `date()`, or `DateTime()` to get the current localized date and time. You always need to set the proper timezone as well. You can do this by getting the current localized timestamp by using `date_i18n`:

```php
// Get the timestamp.
$now = date_i18n( 'U' );

// Get the current time as a DateTime object.
$now = ( new DateTime() )->setTimestamp( date_i18n( 'U' ) );
```

In the background, `date_i18n()` uses `current_time`, when you don’t provide `date_i18n()` with a timestamp.

I’ve also found that `strtotime()`, which the `|date` filter uses, doesn’t always work reliably. But I didn’t investigate it further. I always switched to using `date_i18n`, which always worked.

In Twig, what I’d currently use is:

```twig
{{ fn('date_i18n', 'F j, Y @ g:i a')) }}
```

For WordPress 5.3, there will be [a new `wp_date()` function](https://make.wordpress.org/core/2019/09/23/date-time-improvements-wp-5-3/).

Could we add a new `wp_date()` function to Twig? Or maybe overwrite Twig’s `date()` function? And we definitely need some better documentation for working with dates.

**Comment by palmiak** [comment]
@gchtr what would you say about something like this:
```php
public function date( $date_format = '' ) {
	$df = $date_format ? $date_format : get_option('date_format');
	$the_date = date_i18n($df, strtotime($this->post_date));
	return apply_filters('get_the_date', $the_date, $df);
}
```

in WP 5.3 `date_i18n` uses `wp_date` (Converted into a wrapper for wp_date() - from the docs) so it looks like a very universal approach.

And we can do the same for `time()`

**Comment by jarednova** [comment]
It seems that @palmiak has resolves some of the issues caught by him and @gchtr. Ultimately, the weirdness that @columbian-chris points out is because we're overriding Twig's default `date` filter with our own. This should be removed in 2.x — this is in PR #2127
