### ISSUE TITLE
custom sort : Unexpected token "operator" of value ">"

### ISSUE THREAD

**Issue by twentyfortysix** [timber/timber#2105]
## Expected behavior
```
{% set fruits = [
    { name: 'Apples', quantity: 5 },
    { name: 'Oranges', quantity: 2 },
    { name: 'Grapes', quantity: 4 },
] %}

{% for fruit in fruits|sort((a, b) => a.quantity <=> b.quantity)|column('name') %}
    {{ fruit }}
{% endfor %}
```

**this should normally resort array and output in this order: Oranges, Grapes, Apples**

## Actual behavior
instead it returns an error on line 

`{% for fruit in fruits|sort((a, b) => a.quantity <=> b.quantity)|column('name') %}`

Fatal error: Uncaught Twig\Error\SyntaxError: Unexpected token "operator" of value ">". in ../wp-content/themes/almond-milk-master/twig/frontpage.twig:137
Stack trace:
#0 ../wp-content/plugins/timber-library/vendor/twig/twig/src/ExpressionParser.php(183): Twig\ExpressionParser->parsePrimaryExpression()
#1 ../wp-content/plugins/timber-library/vendor/twig/twig/src/ExpressionParser.php(78): Twig\ExpressionParser->getPrimary()
#2 ../wp-content/plugins/timber-library/vendor/twig/twig/src/ExpressionParser.php(91): Twig\ExpressionParser->parseExpression(21)
#3 ../wp-content/plugins/timber-library/vendor/twig/twig/src/ExpressionParser.php(161): Twig\ExpressionParser->parseExpression(0)
#4 ../wp-content/plugins/timber-library/vendor/twig/twig/src/ExpressionParser.php(74): Twig\ExpressionParser->parseArrow() in ../wp-content/themes/almond-milk-master/twig/frontpage.twig on line 137

## What version of WordPress, PHP and Timber are you using?
WordPress 5.2.4, PHP 7+, Timber 1.12.0

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
zip upload

## related links
https://github.com/symfony/symfony/issues/33895

**Comment by palmiak** [comment]
I just tested it and it works 1.12.0 and 1.12.1 - but it's more important which Twig version do we have - because with Twig older than 2.12 the error mention above will appear.

**Comment by jarednova** [comment]
Yeah, looks like the issue here is Twig with that operator. I get this error when running it in an incompatible version:

```1) TestTimberTermTwigFilters::testTwigSort
Twig\Error\SyntaxError: An opened parenthesis is not properly closed. Unexpected token "punctuation" of value "," ("punctuation" expected with value ")") in "__string_template__3b87df5cc526ad643d30c0659eefe08a51a0b4abfb180748cf91e64d347c37ac" at line 7.```

**Comment by jarednova** [comment]
... here's a link to a PR with that test added: https://github.com/timber/timber/pull/2107

**Comment by jarednova** [comment]
After a little more reading: the example you included has the "Spaceship" operator, which is only available as of PHP 7:

https://www.php.net/manual/en/language.operators.comparison.php

It appears from the [tests](https://travis-ci.org/timber/timber/builds/606192125?utm_source=github_status&utm_medium=notification) that the example you posted will only work in PHP 7+ with Twig 2.12+. That said, your install details would suggest this _should_ work, so could you double-check the installed Twig version to see what's running there?

**Comment by twentyfortysix** [comment]
I see the error with:
Timber Version 1.12.0
PHP Version 7.3.7

the problem persists with Timber Version 1.13.0
---
I have read that the old WPML version has its own twig that collides, I don't the WPML on this site

**Comment by jarednova** [comment]
@twentyfortysix can you peek inside the `/vendor` folder to see what version of Twig is running? The `CHANGELOG` file is usually where I look

**Comment by twentyfortysix** [comment]
vendor/twig/twig/CHANGELOG

* 1.42.4 (2019-11-11)

 * optimized "block('foo') ?? 'bar"
 * added supported for exponential numbers

**Comment by jarednova** [comment]
cool, thanks @twentyfortysix. I've confirmed that unfortunately that version of Twig simply doesn't support the spaceship operator (even when running in PHP 7) so unfortunately not much we can do from the Timber end. If you're installing with composer in PHP 7, you should get Twig 2.x which will support the code you have above

**Comment by twentyfortysix** [comment]
thanks for reply.
What is that that Timber from WP repository has older version of Twig?

**Comment by jarednova** [comment]
Yeah we use Twig 1.x with the WordPress.org version so that it's compatible with PHP 5.x
