### ISSUE TITLE
Not able to pass a context object to a macro, include, embed

### ISSUE THREAD

**Issue by elbit** [timber/timber#2108]
Hi, I'm trying to use dynamic context for macros, embeds or includes for components.
For example I want to pass the src value of a thumbnail from diferent contexts "post.thumbnail.src", "Image(post.meta('hero_image')).src". I've tried everything but I allways get "(unknown)" value.

The context is passing ok when I put {{item.thumbnail.src}} direct inside the macro but I'm not able to pass as a variable.

````
<div>{{ _self.img-list(posts,item.thumbnail.src) }}</div>

{% macro img-list(items,src) %}
 <ul class="bit-list-none bit-flex bit-w-full bit-justyfy-between">
        {% for item in items %}
        <li class="bit-pr-2"><img src="{{src}}" alt=""></li>
        {% endfor %}
</ul>
{% endmacro %}
````

**Comment by palmiak** [comment]
Could you provide me with some more code? I don't now what are `posts` or `item` (this probably in some php file). I used macros and didn't had any problems with them, so probably there is some simple mistake that we could fix.
