### ISSUE TITLE
Sending several hundred requests

### ISSUE THREAD

**Issue by rhm-dennis** [timber/timber#2110]
**What version of WordPress, PHP and Timber are you using?**
Wordpress version : 5.3
PHP version : 7.3
TImber version : 1.12.0

**How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)**
Installed the latest version via WP plugin

Hi Support,

We are using the Timber on our WP site which has 4k - 5k articles and hosted on WP Engine. We are using the native WP search ( native WP Query, no any search plugin ) to create a search feature on the site. But it is causing the slow performance on the search because of the timber-library is sending several hundred requests for display.

Do you have any idea or plugin settings to make this run a little faster?

Here is the screen shot provided from WP Engine
<img width="999" alt="Screen Shot 2019-11-13 at 1 39 17 AM" src="https://user-images.githubusercontent.com/57740361/68825986-12b7eb80-06d7-11ea-8b1a-1e02d5c7f529.png">

And code example
search.php
<img width="903" alt="Screenshot 2019-11-14 at 12 07 20 PM" src="https://user-images.githubusercontent.com/57740361/68826099-6cb8b100-06d7-11ea-99dd-6711501ef5e4.png">

search.twig
<img width="1130" alt="Screenshot 2019-11-14 at 12 07 49 PM" src="https://user-images.githubusercontent.com/57740361/68826106-7215fb80-06d7-11ea-849c-3c89d44a3ba0.png">

Let me know you need more information.

Thanks

**Comment by jarednova** [comment]
@rhm-dennis hmmmm, nothing comes to mind immediately. But some ideas ...

1) Try some [wolf-fencing](https://news.ycombinator.com/item?id=11514347) to see if you can isolate which segment of code is driving the requests
2) I notice `rushhour_` functions in there? Also another thing to isolate. I've found that more plug-ins than you might expect use Twig so it _could_ be something unrelated it to Timber
3) Disable the various includes that you have in search.twig. I've sometimes screwed up and had unintended include loops in sites I've built

hope that helps!
