### ISSUE TITLE
View details link is not relative

### ISSUE THREAD

**Issue by Beee4life** [timber/timber#2112]
## Expected behavior
When I click the "View details" link in the Wordpress plugins screen, I expect to see the plugin details/info, but since the link doesn't take into account that some sites are run from a sub folder, this gives a 404.

## Actual behavior
I get a 404 screen, see below gif.

![LlaDMLbAAp](https://user-images.githubusercontent.com/4508731/69048050-d3eaa400-09fc-11ea-8663-ee3679b8a5af.gif)

## What version of WordPress, PHP and Timber are you using?
WP 5.3
PHP 7.2
Timber 1.12.0

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer/packagist

SOLUTION: 
Change  line 24 in /lib/Admin.php

    $links[] = '<a href="/wp-admin/plugin-..." class="thickbox" aria-label="More information about Timber" data-title="Timber">View details</a>';

to 

    $links[] = '<a href="' . get_site_url() . '/wp-admin/plugin-..." class="thickbox" aria-label="More information about Timber" data-title="Timber">View details</a>';

**Comment by palmiak** [comment]
Could you try making a pull request for this? It looks ok.

pon., 18 lis 2019, 12:18 użytkownik Beee <notifications@github.com> napisał:

**Comment by Beee4life** [comment]
As you can see I did...

**Comment by Beee4life** [comment]
@palmiak I saw some new stuff,  like codegov and so... Do I need to do anything else ?

**Comment by jarednova** [comment]
Thanks @Beee4life — just merged this in. Thanks so much for raising the issue and the fix. I'm getting things set now to release a new version later today/tonight
