### ISSUE TITLE
double execution / index.php as route

### ISSUE THREAD

**Issue by twentyfortysix** [timber/timber#2116]
## behavior
I accidentally realized while running a wp_insert_post on index.php which is the only php file (except the functions.php) in the template with timber "init"  serving as route that the function/s are running twice, or they are called twice:

index.php code, it inserts one post into db:

```
$data = Timber::get_context();
$post_data = array(
            'post_content' => '',
            'post_title' => date('c'),
            'post_status' => 'publish'
        );
$p = wp_insert_post($post_data, true);
```

while with this code, it inserts two records in db

```
$data = Timber::get_context();
if(is_front_page()){
	$data['post'] = new TimberPost();
	Timber::render('frontpage.twig', $data);
}
 $post_data = array(
            'post_content' => '',
            'post_title' => 'date('c'),
            'post_status' => 'publish'
        );
$p = wp_insert_post($post_data, true);

```

which means the function/s is executed twice for some reason (in this case wp_insert_post).
What I see as a problematic is that it points to a "fact" that the function/s executed along Timber::render() are executed multiple times thus wasting resources.. 
In small website with simple queries it might not be a problem, but with large data queries...?
Sure people do not save new posts in db on index page call but if any script on that place is called twice...

note: the frontpage.twig does not call the insert function too ;)

## What version of WordPress, PHP and Timber are you using?
wp 5.3. Timber installed via composer a day a go

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Timber installed via composer a day a go

**Comment by jarednova** [comment]
@twentyfortysix I tried to replicate the issue on my end but couldn't get the same behavior to occur. Could you post the entirety of your `index.php` file (or anything else that's relevant for your setup)? I want to make sure I can try to get to the same issue you're experiencing

**Comment by twentyfortysix** [comment]
Hi 
I have created new installation, copied over all plugins, template activated all, created similar acf fields (just in case) and I'm not able reproduce the error.
So I'd say forget about it.
Sorry for the false issue.

**Comment by jarednova** [comment]
all good, thanks for checking and closing!
