### ISSUE TITLE
Relative urls + WordPress in subdirectory + plugins

### ISSUE THREAD

**Issue by domtra** [timber/timber#2117]
I have one specific issue with the relative path that is added to `wp_upload_dir()` which lead me to a more general observation that I want to address and discuss. First comes the issue, and at the bottom the general topic.

## Expected behavior

When calling `wp_upload_dir()`, there should be a relative path added to the return value.

## Actual behavior

The relative path is absolute.

## Steps to reproduce behavior

Install WPML, set up a minimum of two languages, set **Different languages in directories** and **Use directory for default language**. Then call `wp_upload_dir()` anywhere.

## What version of WordPress, PHP and Timber are you using?

WordPress 5.3, PHP 7.3, Timber 1.13.0

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Composer

## Fix

Instead of relying on the static `$home_url` in ImageHelper, you can implement the same functionality as in the URLHelper in `get_content_subdir()`. However, all of this functionality should be extended with calling `untrailingslashit()` on the result to avoid inconsistencies introduced by other plugins.

## General

There are several locations where Timber uses relative paths. This has lead to several issues in the past. Especially when WordPress is located in a subdirectory, as in Bedrock, and when WPML is used and is set to use subdirectories for languages. Also multisites might be a source of trouble but I haven't had time lately to look at that again.

The reason for these issues is the following:

Normally `home_url()` will return `https://example.com` and `site_url()` will also return `https://example.com`. 

When you (install WordPress in a subdirectory)[https://wordpress.org/support/article/giving-wordpress-its-own-directory/], lets say this subdirectory is **wp**, `site_url()` will return `https://example.com/wp`.

When you install WPML and server languages in directories, it will modify `home_url()` to include the current language, for example `https://example.com/en/`. (Note the inconsistency. Normally, `home_url()` does not include a trailing slash, with WPML it does.)

When multisites come into play, these function behave differently.

Also, it is possible for any plugin to modify the home or site_url, which can lead to even more issues. 

At the moment there are specific integration fixes included in Timber for WPML. I am wondering if there is a more general way to fix all of the underlying issue once and for all.

I haven't had time enough yet to go through the code, if the relative paths / urls are actually needed at all. If not and it would be possible to drop all this functionality, I would suggest to go ahead and do this.
If they are needed, maybe it would make more sense to not make use of WordPress functions, but of PHP ones.

Let me explain:

Normally, if you need a relative URL, you want a URL relative to the schema + domain + port. Because you usually want to use this URL in the browser and not specify the host info again. 
If you need a relative path, this should usually be needed relative to the docroot of the current script because you would normally server only those files.
There might be exceptions to these common use cases but for those I would offer the developer a Timber specific constant or filter to modify them.

Can you see any benefit in my suggestions? 

I would really like to see all of the related and maybe even unforeseeable issue relating to the relative url / path generation solved. This is giving us headaches again and again. I would possibly also be available to help making these changes. However, I am not completely familiar with the entire codebase and what the functions are used for. Also this should not introduce any breaking changes, only if you decide to remove the entire relative functionality.

Cheers.

**Comment by jarednova** [comment]
@domtra I completely agree. Timber was formulated based on the most simple setups and behavior (where a site is a site, there's only one language in the world and everyone uses the same WP install plan). However, WordPress and Timber are used all over the world (hooray!) and increasingly, that's using non-traditional setups (Bedrock, etc.).

So short answer, I'm all for removing places where relative URLs are relied upon. If you or another passerby wants to work on this, the places in the codebase to probably examine are ...

- Images: attachments, resizing etc.
- Pagination: parsing page URL formats
- Archives: parsing page URL formats

**Comment by parisek** [comment]
I was able to fix wrong WPML URLs with filters (I'm also changing location of images, but that is not needed)

```
add_action( 'timber/image/new_url', 'timber_image_new_url' );
add_action( 'timber/image/new_path', 'timber_image_new_path' );

function timber_image_new_url($location) {
    $upload_dir = wp_upload_dir();

    $new_dir = str_replace($upload_dir['relative'], '/wp-content/cache/image', $upload_dir['basedir']);
    if(!file_exists($new_dir)) {
      wp_mkdir_p($new_dir);
    }

    $location = str_replace($upload_dir['relative'], '/wp-content/cache/image', $location);
    // Resolves issues with wrong relative URLs with WPML
    // Without this we cannot generate unique images from non default languages
    // https://github.com/timber/timber/issues/2117
    if(strpos($location, '/wp-content/') === 0) {
      $location = str_replace('/wp-content', content_url(), $location);
    }

    return $location;
  }

function timber_image_new_path($location) {
    $upload_dir = wp_upload_dir();

    // Resolves issues with wrong relative URLs with WPML
    // Without this we cannot generate unique images from non default languages
    // https://github.com/timber/timber/issues/2117
    if(strpos($upload_dir['relative'], 'http') === 0) {
      $upload_dir['relative'] = str_replace(content_url(), '/wp-content', $upload_dir['relative']);
    }

    $new_dir = str_replace($upload_dir['relative'], '/wp-content/cache/image', $upload_dir['basedir']);
    if(!file_exists($new_dir)) {
      wp_mkdir_p($new_dir);
    }

    $location = str_replace($upload_dir['relative'], '/wp-content/cache/image', $location);

    return $location;
  }
```

**Comment by Levdbas** [comment]
Since this issue didn't get much traction in the past few years I am going to close this. If anyone still runs into this issue, please let us know.
