### ISSUE TITLE
resize twig filter ads `\` to the url

### ISSUE THREAD

**Issue by asolopovas** [timber/timber#2118]
## Expected behavior

```
src=https://host.test/wp-content/uploads/img.jpg
<source data-srcset="{{ src |towebp|resize(width, height) }}" type="image/webp">
```
i expect it to be 
```
`src=https://host.test/wp-content/uploads/img-310x465-c-default.webp`
```
## Actual behavior
`src=https://host.test/wp-content/uploads\/img-310x465-c-default.webp`

## What version of WordPress, PHP and Timber are you using?

Wordpress 5.3, PHP 7.4, 1.12.0
## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Composer

**Comment by palmiak** [comment]
Could you check it on PHP 7.3?

**Comment by asolopovas** [comment]
After inspecting the issue if found that ImageHelper.php lines 499 to 501 are causing it.
```
		if ( !empty($subdir) ) {
			$url .= $subdir;
		}
```
If I comment it out it does not add this slash

**Comment by asolopovas** [comment]
With PHP 7.3 it generates `//localhost:3000/wp-content/uploads//img-WidthxHeigh-c-defaultt.webp`, but not for all files the ones that are located in subdirectories for examples `//localhost:3000/wp-content/uploads/sub/img-WidthxHeigh-c-defaultt.webp` it works without a hitch

**Comment by asolopovas** [comment]
If I change line 437 in ImageHelper.php to `$result['subdir'] = ($parts['dirname'] === '/' || $parts['dirname'] === '\\') ? '' : $parts['dirname'];`  it fixes the problem..

**Comment by asolopovas** [comment]
The culprit is in the function on line 25 PathHelper.php
If I understand correctly it tries to replace all `\` with `/`  ?
As clearly it doesn't do that 
```
public static function pathinfo( $path, $options = PATHINFO_DIRNAME |
		PATHINFO_BASENAME | PATHINFO_EXTENSION | PATHINFO_FILENAME
	) {
		$info = pathinfo(
			str_replace(
				array( '%2F', '%5C' ),
				array( '/', '\\' ),
				rawurlencode( $path )
			),
			$options
		);
```

**Comment by asolopovas** [comment]
The search parameter in str_replace should be starting with `%5C` rather than `%2F` like so
```php
$name = "C:\code\\3oak.test\\wp-content\\themes\\3oak\\archive.php";
$search  = [ '%5C', '%2F',];
$replace = ['/', '\\'];
$subject =  rawurlencode($name);
echo "Result: \n" . str_replace($search, $replace, $subject) . "\n";
```

**Comment by danburzo** [comment]
Hi @asolopovas, I will be able to look at the issue tomorrow. In the meantime, can you let me know if the problem happens only if you chain two image filters (`webp` + `resize`), or does it happen with either of these filters when used by themselves?

**Comment by asolopovas** [comment]
Yes happens when I chain `webp` and `resize`. I don't know where that extra slash pop out from. 
![phpstorm64_ZyGVUvhU7A](https://user-images.githubusercontent.com/6893216/70465591-2decff80-1ab9-11ea-81d6-05c28ec79a9d.png)
I can't understand where this `\` sneaks in

**Comment by asolopovas** [comment]
with just resize I get extra `/` attached after uploads., so it looks something like that  `//localhost:3000/wp-content/uploads//image-310x465-c-default.jpg`

**Comment by danburzo** [comment]
What's the operating system on the environment where this issue reproduces? Although I was not able to install WebP support on my (MAMP-powered) macOS, I couldn't reproduce your problem with using the `resize()` filter by itself.

**Comment by asolopovas** [comment]
My operating system is Windows 10x64 Professional, I am using IIS for local development and PHP FastCGI.

**Comment by asolopovas** [comment]
PHP 7.2, 7.3, 7.4 tested all result in the same problem

**Comment by asolopovas** [comment]
$parts['dirname'] returns '\' instead of '/' probably when its done on windows
