### ISSUE TITLE
Proposal: Support using Lando as the local dev environment

### ISSUE THREAD

**Issue by acobster** [timber/timber#2119]
## Is your feature request related to a problem? Please describe.

For various reasons I've had to reinstall Vagrant and/or VirtualBox several times over the last couple years. I've come to the conclusion that the VVV architecture (and Vagrant setups in general) is inherently brittle. Timber's [VVV setup process](https://timber.github.io/docs/guides/testing/), while lightyears ahead of any ad-hoc local LAMP setup, is still slow and manual compared to what I'm now used to on client projects and from working with the [Conifer dev environment](https://coniferplug.in/dev-setup.html#using-lando-recommended).

From my own personal experience and the experience of the SiteCrafting dev team, we've found that Vagrant-based dev setups break often, are hard(er) to understand, and often diverge into states that are difficult to reproduce There's got to be a better way!

## Describe the solution you’d like

[Lando](https://docs.devwithlando.io/) is the best local dev tool in the galaxy.

On Lando, the local Timber dev environment setup steps will be:

1. [Install Lando](https://docs.lando.dev/basics/installation.html)
2. Clone Timber and run `lando start`
3. Profit.

### What this involves

1. Create a [Landofile](https://docs.lando.dev/config/lando.html) that lives at the root.
2. Build and test any scripts that Lando must run internally to set up databases, test libraries, dependencies, etc.
2. Provide Lando setup instructions in [docs/testing.md](https://timber.github.io/docs/guides/testing/)

### Transition period

**Using Lando as your dev environment would be opt-in,** at least at first. Ideally we'd only _add_ code to support this, and any refactoring necessary would be done in such a way that folks who are happy with VVV don't have to change anything.

## Describe alternatives you’ve considered

1. Continue using VVV and wanting to rip my hair out every six months :sob: 
2. Docker Compose? Way more verbose and harder to understand - Lando is basically an abstraction over Docker Compose.
3. Another local dev environment tool such as [DDEV](https://www.ddev.com/) or [Docksal](https://docksal.io/). I don't have anything against these tools per se, we just don't have the same level of experience with them.

## Additional context

We have in-house expertise converting complex projects from Vagrant to Lando. If there's interest enough, it's extremely likely we can book out capacity to roll this out fairly quickly.

**Comment by jarednova** [comment]
I'm all for giving Lando a shot (I also have less hair than when I started using Vagrant / VirtualBox — though, not sure if I can blame it *all* on that). Especially because `We have in-house expertise converting complex projects from Vagrant to Lando. If there's interest enough, it's extremely likely we can book out capacity to roll this out fairly quickly.` If it will help modernize us and improve development cycles — let's do it!

**Comment by jarednova** [comment]
... I've yet to set Lando up for myself so if @acobster when you have the start to either a Landofile and/or a new step-by-step — I'm happy to test 'em out

**Comment by palmiak** [comment]
👍 for Lando too - I really love how simple it is. Great idea @acobster
