### ISSUE TITLE
Nested group field inside a group field 

### ISSUE THREAD

**Issue by CristianIbanez43** [timber/timber#2125]
Hopefully someone can help me out.
How do you grab the fields from a group nested inside another group?

The following works if you only have the one group:

{% set group = post.get_field('my_group') %}

	{{ group.title }}

**Comment by palmiak** [comment]
Could you share with us your ACF structure?

**Comment by CristianIbanez43** [comment]
Hi Palmiak,

I've figured it out. Groups are within a repeater which had me stumped.

While in a repeater I had to make sure all my groups were within context.
If I wanted to grab the 'title' field from group2 I would do something like this:

{% for item in item.my_repeater %}
{{ item.group1.group2.title }}
{% endfor %}

Thanks for responding
