### ISSUE TITLE
Incompatibility with PHP 7.4 caused by TWIG

### ISSUE THREAD

**Issue by tareksamni** [timber/timber#2129]
##  Expected behavior
I had a WP website that was running perfectly on 7.1 and when moved to 7.4 a lot of whitespaces in `twig` templates started to disappear and break HTML everywhere around the website.

After some investigation, I found that TWIG has an issue with PHP 7.4 concerning whitespaces that got fixed with:
https://github.com/twigphp/Twig/commit/1fb0f9701d8443083495cd2645e8a0c45d54c34d in 1.41.0 (2019-05-14)

## Actual behavior
I expect whitespaces in twig templates to print as whitespaces in rendered HTML.

## Steps to reproduce behavior
As 
```
<header class="header {% do action('header_class') %}"></header>
```

Should render to:
```
<header class="header fixed"></header>
```

Instead, it is rendered as:

```
<header class="headerfixed"></header>
```
## What version of WordPress, PHP and Timber are you using?

WordPress 5.2.3, PHP 7.4, Timber 1.0.5

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by jarednova** [comment]
Thanks for the heads-up on this @tareksamni! I'll add in some tests to verify and test against PHP 7.4

**Comment by jarednova** [comment]
@tareksamni thanks again for the note on this. I updated composer to use Twig > 1.41 so that this doesn't recur. It looks like there are a bunch of issues with Travis/WP Unit Tests/Timber Unit Tests in PHP 7.4 though. I'll open up a separate ticket to track those
