### ISSUE TITLE
Add test helpers for temporarily adding filters/actions

### ISSUE THREAD

**Issue by acobster** [timber/timber#2153]
Test code that involve adding filters or actions gets noisy because you have to manually remove them at the end of each test, or else the hook spills over into other tests. This also makes it error prone because it's easy to forget to remove the hook.

Add helper methods to `Timber_UnitTestCase` for temporarily adding filters or actions. These methods should store a reference to the params they were passed. In `tearDown()`, loop through all the stored references of added filters/actions and remove them using the same params.

**Comment by gchtr** [comment]
@acobster So in #2158 you added a function to add filters, but actions are still missing, am I right?

**Comment by acobster** [comment]
@gchtr correct, I only found a handful of places we call `add_action` directly in the tests, and I don't see a need for us to add any more in the near future:

```
$ grep --include=*.php -r add_action tests
tests/test-timber-post-iterator.php:            add_action( 'loop_end', array( $this, 'loop_end' ) );
tests/test-timber-post-getter.php:              add_action( 'the_post', function( $post ) {
tests/test-timber-context.php:          add_action( 'the_post', function( $post ) {
tests/test-timber-wp-functions.php:                     add_action('jared_action', function(){
tests/test-timber-wp-functions.php:                     add_action('wp_footer', 'echo_junk');
tests/test-timber-twig.php:                     add_action('my_action_foo', function(){
tests/test-timber-twig.php:                     add_action('my_action_args', function($bar){
tests/test-timber-twig.php:                     add_action('timber/compile/done', function(){
tests/test-timber-meta-deprecated.php:          add_action( 'timber_post_get_meta_pre', $action, 10, 3 );
tests/test-timber-meta-deprecated.php:          add_action( 'timber_comment_get_meta_pre', $action, 10, 2 );
```

**Comment by Levdbas** [comment]
From what I can see this issue seems to be dealt with by @acobster
