### ISSUE TITLE
Password Protected Posts / Pages

### ISSUE THREAD

**Issue by Jaace** [timber/timber#217]
This functionality doesn't seem to be working. I believe it's tied into the loop in WordPress and because Timber avoids the loop it doesn't adhere to the normal password flow.

I'm not exactly sure how WordPress implements this functionality in the loop but I do see that when password is set on a post it is sent through post.post_password. This is only one part of the solution though as a form is usually shown and a password is asked for before the content is visible.

**Comment by felipearosemena** [comment]
What's the status on this issue? Is there any plan to enable the default Wordpress password protected form?

**Comment by connorjburton** [comment]
Hey,

We will most likely be looking at this post 1.0, which will land in the next couple of weeks.

**Comment by jeremyzahner** [comment]
@connorjburton Any news on this?

**Comment by felipearosemena** [comment]
@connorjburton +1

**Comment by hrsetyono** [comment]
@connorjburton +1. Would appreciate this feature or temporary solution. Thanks

**Comment by jarednova** [comment]
Hey @hrsetyono @felipearosemena @jeremyzahner @Jaace — check-out #1170

**Comment by jarednova** [comment]
Closed by #1170 — release on Tuesday!
