### ISSUE TITLE
ACF Image Gallery Field inside Flexible Content returning `false` within the loop.

### ISSUE THREAD

**Issue by metadiv** [timber/timber#2173]
## Expected behavior
ACF Gallery field within a Flexible content template type should return an array of images (or ids)

## Actual behavior
When looping the flexible content the gallery field is returns a bool value of `false`.

## Steps to reproduce behavior
Create an ACF flexible content field with an ACF image gallery field within one of the content templates.

Loop the the flexible content field and for that template type return an array of images from the gallery field.

## What version of WordPress, PHP and Timber are you using?
WordPress 5.3.2, Timber 1.14.0, ACF PRO 5.8.7

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WP Plugins Interface

**Comment by Levdbas** [comment]
Closing this as stale.
