### ISSUE TITLE
There are 4 year old issues

### ISSUE THREAD

**Issue by szepeviktor** [timber/timber#2176]
See https://github.com/timber/timber/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc+

What can be done to clean up "baby" issues?
I've cleaned up mine.

4 years old humans are pretty big babies :)

**Comment by jarednova** [comment]
Yup — I'm cleaning some stuff up now. I think it'd help bring focus to what we're actively working on

**Comment by szepeviktor** [comment]
> I'm closing all 2+ year old issues.

I'm happy that my puny issue produces such an issue-avalanche.
