### ISSUE TITLE
Using multiple Timber::compile() in one script crashes because of re-declarations in functions.php 

### ISSUE THREAD

**Issue by bramkorsten** [timber/timber#2179]
## Expected behavior
I expect it to be possible to make multiple Timber::compile calls in a single script. This is (for example) great for sending multiple emails using twig templates as the HTML for these emails (my usecase).

## Actual behavior
The second compile command re-runs functions.php, which has custom functions declared like this:
```php
$twig->addFunction(new Timber\Twig_Function('load_js', 'load_js'));
```
This crashes the script, as these functions are already declared. A solution could be to check if these functions have been declared before, but the documentation is unclear to me. It also seams that using the built in check from twig: `$twig->getFunction()` also doesn't work, as this function first tries to init the custom functions again.

## Steps to reproduce behavior
Setup a timber installation, with custom functions declared in functions.php. The code for this looks something like this:

```php
add_filter( 'get_twig', array( $this, 'add_to_twig' ) );

function add_to_twig( $twig ) {
	$twig->addFunction(new Timber\Twig_Function('whatever', 'whatever'));
	function whatever($handle) {
		echo("It's-a-me, Mario");
	}
};
```
then, run a script that runs two `Timber::compile()` commands. This should crash the script with the following error:

`Cannot redeclare whatever() (Previously declared in .../functions.php)`

## What version of WordPress, PHP and Timber are you using?
WordPress 5.2.- PHP 7.2, Timber 1.9.2 -->

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Upgraded to this version via plugin updater in WordPress dashboard. (didn't update yet because i'm still working on the theme, but it shouldn't matter)

**Comment by gchtr** [comment]
What if you don’t define the `whatever` function inside the filter, but outside of it?

**functions.php**

```php
add_filter( 'get_twig', array( $this, 'add_to_twig' ) );

function add_to_twig( $twig ) {
	$twig->addFunction( new Timber\Twig_Function( 'whatever', 'whatever' ) );
};

function whatever( $handle ) {
    echo( "It's-a-me, Mario" );
}
```

**Comment by bramkorsten** [comment]
@gchtr You're a legend! No idea why I even did that in the first place, as the docs agree with you! Thanks for the tip!

**Comment by gchtr** [comment]
@bramkorsten Cool, I’m glad it works now!
