### ISSUE TITLE
User->id/ID is string instead of int

### ISSUE THREAD

**Issue by rubas** [timber/timber#2187]
## Expected behavior
The User `id`/`ID` should be an [integer](https://github.com/timber/timber/blob/master/lib/User.php#L63).

## Actual behavior
The User `id`/`ID` is a **string**. 

## Steps to reproduce behavior
```
use Timber\User;

$user = new User(15);

echo \gettype($user->id);
echo \gettype($user->ID);
```

## What version of WordPress, PHP and Timber are you using?
Timber 1.14
PHP 7.3
Wordpress 5.3.2

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer/Packagist

**Comment by jarednova** [comment]
@rubas good call! Is this happening on all data types or just User?

**Comment by rubas** [comment]
We noticed this behaviour only with the `User` class and not with others.

Not sure when it was introduced but I guess lately as it broke our code `$user->id === 15`.
