### ISSUE TITLE
Allow for 'vendor' directory to be in non-public directory

### ISSUE THREAD

**Issue by jarednova** [timber/timber#2191]
Current workflow is something like this (suggested by an emailer)

```
Update your theme’s require_once() code in functions.php like this example:
https://pastebin.com/s0RueXMG
In ~/.bash_profile, set COMPOSER_VENDOR_DIR by adding a new entry to the file:
export COMPOSER_VENDOR_DIR=$HOME/composer
In the ~/public/.htaccess, set COMPOSER_VENDOR_DIR by adding a new entry to the file:
SetEnv COMPOSER_VENDOR_DIR /home/my-username/composer
Install your composer vendors in the normal way:
cd ~/public/wp-content/themes/my-theme && composer install
```
I'm betting we can use the `COMPOSER_VENDOR_DIR` constant to negate extra work on a users' end

**Comment by Levdbas** [comment]
I doubt we want this in Timber core. If you really want to secure your vendor folder Bedrock or Wordplate are both projects that can be used as a way to harden your WordPress installation. I use this in all my projects and it works great. The vendor folder is then located outside the sites root folder. Closing this for now, but if you think we still need to provide this as a feature, please reopen again @jarednova .
