### ISSUE TITLE
dirname has issues with depths greater than 2

### ISSUE THREAD

**Issue by radovanobal** [timber/timber#2198]
## Expected behavior

render twig

## Actual behavior

Blank screen, no errors, no HTML output

## Steps to reproduce behavior

```
        Timber::$dirname = [
            'build/',
            'build/templates/',
            'build/templates/common/',
            'build/templates/component/',
            'build/templates/layout/',
            'build/templates/page/',
            'build/assets/',
            'build/assets/images/',
            'build/assets/images/vector/'
        ];
```

putting twigs in build/ or in build/templates renders the file but it does not in build/templates/page/

## What version of WordPress, PHP and Timber are you using?

Wordpress 5.3,
PHP 7.2,
Timber 1.15.0,

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Installed it from the wordpress store on the one that it does not work and from composer on the one that it does

**Comment by jarednova** [comment]
VERY interesting @radovanobal. Can you clarify `Installed it from the wordpress store on the one that it does not work and from composer on the one that it does`. As I go to investigate I want to make sure I can replicate. Can you provide some more info on the **failing** environment, such as?

- Server software and version (nginx, Apache, Windows)
- Type (local, Docker, MAMP) or Host (WPEngine, Flywheel, Dreamhost)

The other thing that strikes me to take a look at on your side is the Permissions on those subdirectories. I usually just set everything to `777` (not good for security, just for debugging) to rule that out as a permissions issue

**Comment by palmiak** [comment]
@jarednova @radovanobal I did a quick test and I wasn't able to replicate it on Xampp.

But one thing came to my mind. The order of `$dirnames`  - maybe it finds the wrong file or something like this?

If not the Permissions might by a good place to start.

**Comment by jarednova** [comment]
Thanks for taking a look @palmiak. Closing for now until we can narrow-in on more specifics
