### ISSUE TITLE
reset() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by jhhazelaar** [timber/timber#2199]
When editing page or post in admin we get an error: 
```
reset() expects parameter 1 to be array, null given in vendor/timber/timber/lib/PostGetter.php:32
```

In the PostGetter on line 31 the `get_posts` function returns null and `reset` expects an array. Maybe extra check if `posts' is an array like this:

```
$posts = self::get_posts($query, $PostClass);
if ($posts && $post = reset($posts)) {
        return $post;
}
```
 
## What version of WordPress, PHP and Timber are you using?
Wordpress 5.3.2, PHP 7.2.27, Timber 1.15.0

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer/Packagist

**Comment by jarednova** [comment]
Thanks for that report @jhhazelaar ! Can you try replacing that line with ...

```php
$posts = self::get_posts($query, $PostClass);
if ( is_iterable($posts) && $post = reset($posts)) {
        return $post;
}
```

... and let me know if that solves the issue?

**Comment by jhhazelaar** [comment]
That's a much better solution and it works! Thanks

**Comment by jarednova** [comment]
great, @jhhazelaar — I'm adding as a PR right now so it can be in the next version
