### ISSUE TITLE
Timber\MenuItem->master_object returns wrong object for WooCommerce product categories

### ISSUE THREAD

**Issue by montagmorgens** [timber/timber#2204]
## Expected behavior
When calling the function `master_object` on a `Timber/MenuItem`, the object that the menu item represents is returned.

## Actual behavior
When the `Timber/MenuItem` is a WooCommerce product category archive, the `master_object` contains an arbitrary WooCommerce product, not the product category.

## Steps to reproduce behavior
Install WooCommerce
Set up product category
Set menu item with product category archive

## What version of WordPress, PHP and Timber are you using?
WordPress 5.3.2, PHP 7.3, Timber 1.15.0, WooCommerce 3.9.2

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by jarednova** [comment]
@montagmorgens thanks so much for this issue. I'm not much of a WooCommerce expert (or user) so I'd love your help on this. Would you be up for investigating a fix and submitting a PR?

**Comment by gchtr** [comment]
This could be one of the weird issues that is related to #1639.

@montagmorgens Just to figure out what’s wrong: Could you try and remove the following line in the `get_info()` method of the `Timber\Post` class and check whether that changes anything?

https://github.com/timber/timber/blob/5c9c55dc47590d6a078f800e4c9de132b669b98d/lib/Post.php#L612

**Comment by montagmorgens** [comment]
I think what causes the problem is that in https://github.com/timber/timber/blob/master/lib/MenuItem.php#L177, `PostClass` returns `Timber\Post` for WooCommerce product categories (which is essentially a custom taxonomy with the registered name `product_cat`), where it should return `Timber\Term`.

This leads Timber to try and construct a Timber\Post with the ID of the product category term, which apparently returns a random post?

**Comment by selim13** [comment]
I can confirm that master_object returns Post instead of Term for custom taxonomies and this is not related to Woocommerce.

**Comment by Levdbas** [comment]
This should be fixed nowaydays in [Timber 2.0](https://github.com/timber/timber/blob/e6a8957afeed29aebf8fecc3fb2fecddbd8ea89c/src/MenuItem.php#L280)
