### ISSUE TITLE
Question: Server gets a huge spike load every day due to Timber 

### ISSUE THREAD

**Issue by jagoncalves14** [timber/timber#2209]
Hello!

I'm having an issue with a website where I'm using Timber.

The website is a really old blog — with more than 10 years old. Due to that, it brings an awful legacy to it. The bigger one is the huge number of posts and, even worst, it occupies 17.2 GB of storage in the server alone.

According to my server hosting, the website is sending the server down every day, usually at the exact same time period:

![image](https://user-images.githubusercontent.com/17235977/75665911-d4860e00-5c6c-11ea-82b4-40f5735700ef.png)

It seems like Timber is the main responsible for this, which is "inserting a large amount of data into the database, which in turn continually increases the time for transactions to be processed.".

My suspicion is that this is being caused by Timber's cache system. I don't have a full understanding of Timber's cache really works since I don't find it completely explicit on the documentation.
Is Timber filling every day and during that time period the database with cache information with transients?

What would be your suggestion on handling this issue?
Would disabling the Timber cache completely solve the issue? But how could it impact the website's performance? I'd really love to get help to get a better understanding of Timber.

Thanks in advance!

**Comment by jarednova** [comment]
@jagoncalves14 thanks for the Q and supporting information. There's nothing turned on by default that caches or would have those major (daily) uses of server resources (esp. database inserts).

If I had to guess, somewhere in your code a developer used the Transient helper which wraps WP's normal transient behaviors in a simpler interface:

https://timber.github.io/docs/guides/performance/#cache-the-php-data

We recommend putting expensive queries inside of these so they aren't performed on every page load (this is good practice for not just Timber, but all WordPress sites). Do you see any calls in your site's theme or code that uses these?

**Comment by jagoncalves14** [comment]
Hi @jarednova , thanks for the reply!

You're probably right by mentioning that this website is doing a lot of calls on every page load. Since it has so content in the database, all queries are probably really expensive by now.

Regarding the Transient helper, there are no instances of `TimberHelper::transient` in the whole code so that is not being used.

All the Timber's `render()` functions are being called like in the following example:

```
$context = Timber::get_context();
$context['post'] = new TimberPost();

$args = array (
  'order' => 'ASC',
  'orderby' => 'display_name',
  'meta_query' => array(
    array(
      'key'     => 'cb_show_author',
      'value'   => 1,
    )
  )
);

$authorsQuery = new WP_User_Query($args);

$context['authors'] = $authorsQuery;
Timber::render(array('templates/about.twig'), $context , 0);
```

The cache expiration time is always being set to 0, so it seems that there is no cache being applied at all.
One thing that I haven't fully understand from your reply: do you suggest me to wrap the queries (or at least the most used ones) in a Transient Helper?

Basically, the last example should come up to like this (see below)?

```
$context = Timber::get_context();
$context['post'] = new TimberPost();

$args = array (
  'order' => 'ASC',
  'orderby' => 'display_name',
  'meta_query' => array(
    array(
      'key'     => 'cb_show_author',
      'value'   => 1,
    )
  )
);

**$authorsQuery = TimberHelper::transient( 'authors_query', function(){
	new WP_User_Query($args);
}, 600 );**

$context['authors'] = $authorsQuery;
Timber::render(array('templates/about.twig'), $context , 600);
```

Another question: You mentioned that "There's nothing turned on by default that caches or would have those major (daily) uses of server resources (esp. database inserts).". But in the documentation, it says the following:

"As a fourth parameter for Timber::render(), you can set the $cache_mode." … "Use whatever caching mechanism is set as the default for Timber\Loader, the default is CACHE_TRANSIENT."

Since we're never calling the $cache_mode parameter, isn't the CACHE_TRANSIENT being set and, registering cache in transients in the database?

Thanks for all the help, and sorry for having so many questions: I just want to get a full understanding. 🙂

**Comment by chads2000** [comment]
Related to https://github.com/timber/timber/issues/1834 ?

**Comment by opengeekv2** [comment]
I'm having the same issue we'll put the new version in production 1.16.0 today. Do you know if it fixes this?

I've found #2280 while trying to hunt down this problem in a site my thought was about the options table getting too big and the transaction getting longer because of many uncleared timeout rows I had caused when forcing timber cache deletion. I don't know if you think that's possible and might be another cause or a factor that has been making this problem worse.

**Comment by Levdbas** [comment]
Closing this as stale

**Comment by opengeekv2** [comment]
Hey I think than more than stale this was fixed by my commit
