### ISSUE TITLE
Sideloaded image tmp files are not cleaned up

### ISSUE THREAD

**Issue by oxyc** [timber/timber#2216]
## Expected behavior

After having sideloaded an external image, the temporary file created by `download_url` should be deleted.

Timber downloads the image using [`download_url`](https://developer.wordpress.org/reference/functions/download_url/) here https://github.com/timber/timber/blob/1.15.1/lib/ImageHelper.php#L376. If you read the docs of the function, it says:

> Please note that the calling function must unlink() the file.

This is never done and should be added below this line https://github.com/timber/timber/blob/1.15.1/lib/ImageHelper.php#L388.

## Actual behavior

Temporary files are never deleted.

## Steps to reproduce behavior

Sorry, i dont have a real example at the moment but I can come back to this issue and update this later.

## What version of WordPress, PHP and Timber are you using?

PHP 7.2
Timber: master

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Github

**Comment by jarednova** [comment]
Thanks @oxyc! This hit as soon as we were scrambling to react to Covid over here in the US so sorry I'm just getting to it now.

You served this one up wonderfully with the info on `download_url` and `unlink`. Please feel free to submit a PR since you've got all the details!
