### ISSUE TITLE
Check WP_DEBUG before calling dump function

### ISSUE THREAD

**Issue by andy-blum** [timber/timber#2217]
## Is your feature request related to a problem? Please describe.
When using the `{{dump()}}` function with WP_DEBUG set to false, the site throws `Fatal error: Uncaught Twig\Error\SyntaxError: Unknown "dump" function.`

This causes a problem if one of these statements is accidentally committed and then rendered in an environment that does not have debug set to true - whether that's production, staging, or even another dev's local install.

## Describe the solution you’d like
While best practice would obviously be to remove these dump functions before committing, it would be nice if they didn't cause the entire page that template is rendered on to crash entirely. Would it be possible for Timber to check for `WP_DEBUG == false` and/or the existence of the dump function before attempting to call it?

## Describe alternatives you’ve considered
I've gotten around this in the past with
```twig
{% if function('function_exists', 'dump') %}
  {{ dump() }}
{% endif %}
```
but that gets really repetitive and it would be DRY-er to include the check in the twig extension itself.

## Additional context
Thanks for a great project, this makes WP development _so much easier_

**Comment by palmiak** [comment]
@jarednova this is quite valid point - I see two in which we can solve this:
either add a dummy function if `wp_debug == false` 
```php
/** Debug if WP_DEBUG is off */
if ( ( !( defined( WP_DEBUG ) ) || WP_DEBUG === false ) && ! class_exists( 'DebugExtension' ) ) {
	$twig->addFunction(new Twig_Function('dump', function() {
		return null;
	}));
}
return $twig;
```

or currently we load debug like this:
```
if ( WP_DEBUG ) {
	$twig->addExtension(new \Twig\Extension\DebugExtension());
}
```

and we set debug in `new \Twig\Environment($loader, $params);` - so if we would always loaded the extension nothing bad would happen because the `debug` function also has `is_debug` check:
```
function twig_var_dump(Environment $env, $context, ...$vars)
{
    echo 'plum';
    if (!$env->isDebug()) {
        return;
    }

    ob_start();

    if (!$vars) {
        $vars = [];
        foreach ($context as $key => $value) {
            if (!$value instanceof Template && !$value instanceof TemplateWrapper) {
                $vars[$key] = $value;
            }
        }

        var_dump($vars);
    } else {
        var_dump(...$vars);
    }

    return ob_get_clean();
}
}```

I think the always loading of `$twig->addExtension(new \Twig\Extension\DebugExtension());` is a much better solution and I don't see any bigger drawbacks.

I can create a PR of course but I'm not sure which way you prefer.

**Comment by jarednova** [comment]
@palmiak @andy-blum first off — apologies for my tardiness! But I'm here now and agree with the premise and routes. From what I can see, I'd like to pursue the simplest/least-code solution. 

As I understand from @palmiak's proposal, we could safely load the debug extension and then use the `WP_DEBUG` value in creating the `Twig\Environment`. My only concern is not knowing the performance hit of loading the extension. I imagine it's quite minimal, but with performance I've found that every. single. little. thing. adds. up. 

I'm thinking a modification to the first idea. What if we used this existing code with an `else`?:

```php
if ( WP_DEBUG ) {
    $twig->addExtension(new \Twig\Extension\DebugExtension());
} else {
    $twig->addFunction(new Twig_Function('dump', function() {
        return null;
}));

would this accomplish the intended result?

**Comment by andy-blum** [comment]
That seems like it should work as anticipated

**Comment by Djules** [comment]
In 2.x version, with WP_DEBUG set to false, a PHP error is thrown:
`PHP Fatal error:  Uncaught Error: Class 'Timber\\Twig_Function' not found`

This line is the culprit (Loader.php:436):
```php
$twig->addFunction(new Twig_Function('dump', function() {
```

The doc states the use of `Twig_Function` is deprecated and `Twig\TwigFunction` should be used instead.

**Comment by jarednova** [comment]
Thanks so much for the note @Djules (and taking an early spin with 2.x). Since you've got the fix identified, I want to give you first crack at the PR opportunity — infamy and riches await if you're up for it!

**Comment by gchtr** [comment]
@Djules @jarednova Apparently, this was already fixed in https://github.com/timber/timber/pull/2327.

**Comment by jarednova** [comment]
@Djules @gchtr well look at that, like magic!

**Comment by jarednova** [comment]
Closing this with resolutions in #2282 and #2327

**Comment by tkfv** [comment]
this solution is a bit controversial: It took me some time with figuring out what was going on with dump not printing anything. And it also does not seem possible to have dump with WP_DEBUG false if that is what you want: #2710
