### ISSUE TITLE
Post date time as DateTime

### ISSUE THREAD

**Issue by flip111** [timber/timber#2225]
In the `Timber\Post` class instead of offering date and time separately, could they be offered as a single `\DateTime` object? Then own styling can be applied with `|date()` function.

**Comment by gchtr** [comment]
When you use [`Timber\Post::date()`](https://timber.github.io/docs/reference/timber-post/#date), you can already provide the date format, including the time, e.g. `{{ post.date('d.m.Y – H:i:s') }}`. The `{{ post.time }}` function is a shorthand to get the time part only.

Btw, there’s a big update coming to Date and Time handling in Timber 2.0 through the following pull requests:

- Add compatibility for Twig date functionality in #2135
- Add a Date/Time guide in #2136
- Update post.date in #2137

**Comment by flip111** [comment]
Sorry opening this issue is my mistake. I mistakenly thought that `date` was just a property. Thank you for the improvements in 2.0
