### ISSUE TITLE
v2 ETA

### ISSUE THREAD

**Issue by jenkoian** [timber/timber#2233]
Sorry, I hate raising tickets like this, I know you're all doing a wonderful job and this isn't a demand or anything, merely a question.

When do you think v2 will likely be ready? Or is there a beta release or anything I can try out? 

The reason I ask is because I'm really keen to try out timber but am blocked with lack of twig namespace support [which has been added to the v2 branch](https://github.com/timber/timber/pull/1811).

I'd just like to know if I can try this out on a new project I'm about to start or if it's still some time away?

Alternatively, I could re-do the PR above backported to v1?

Thanks for your time :)

**Comment by szepeviktor** [comment]
[Elephants do it 95 weeks](https://www.livescience.com/33086-what-animal-has-the-longest-pregnancy.html), we supersede elephants!

**Comment by jarednova** [comment]
@jenkoian thanks for your note! I appreciate that you recognize we're doing the best we can to find time and make this happen.

I really think that we will have 2.x out on by the end of June. We've got one last "feature" to complete and then we can start with last-step code cleanup and other testing/release steps.

In regards to re-doing a back-ported PR, I'd of course be happy to take a look — but I'm trying to be judicious with 1.x PRs to help manage merge conflicts. Is there a lot of code changes for this particular issue?

**Comment by jenkoian** [comment]
Thanks for the update @jarednova - don't want to distract from the excellent work you're doing so will hold off on a backporting PR 👍
