### ISSUE TITLE
Image relative path returns wrong path

### ISSUE THREAD

**Issue by trompx** [timber/timber#2241]
When requesting the relative path of an image, an incorrect path is returned.

## Outputs
`{{ Image(item.image).src }}` -> `http://192.168.0.105:13006/wp-content/uploads/2020/01/cover.jpg`
`{{ Image(item.image).path }}` -> `/wp-contenthttp://192.168.0.105:13006/wp-content/uploads/2020/01/cover.jpg`

## What version of WordPress, PHP and Timber are you using?
Wordpress: 5.4
PHP: 7.3.16
Timber: 1.15.2

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
From github

**Comment by trompx** [comment]
For those having the same problem, until it is solved, I created a twigfilter to strip the home_url from the path.

```
function add_to_twig($twig) {
  $twig->addFilter( new Twig_Filter( 'relpath', 'relpath' ) );
  return $twig;
}
function relpath($path){
  $path = str_replace(get_home_url(), '', $path);
  return $path;
}
```

Usage: `{{ image.src|relpath }}`

**Comment by jarednova** [comment]
@trompx is there anything unique going on with your setup either in the domains (subdirectory install?) or server paths (bedrock? etc.). Unit tests cover what you're showing so it should be working under "normal" conditions

**Comment by trompx** [comment]
Hello @jarednova,

In fact I have a non standard configuration.
I need to host some wordpress websites on non root urls, like `subdomain.domain.com/project1` or `domain.com/projects/project1`. I have SPA applications (custom framework) so in order to make all the routing work, I went the **base meta tag** path.

So in my website I have links like:
`<a href="about">About</a>`
and I have a script that automatically gets the base url according to where the website is hosted:
`<base href="{{ function('get_base_url') }}" />`

I had problems in wordpress which was outputting wrong urls when enqueing assets. To make this work I had to use **script_loader_tag** and do something like `ltrim(str_replace( site_url(), '', $href ), '/')`. Using **script_loader_src** was not enough as wordpress was still escaping urls after that hook.

In javascript I detect the base path and handle that in my router (solutions has been found for well known frameworks such as react / angular).

I wanted a system so that I just have to change the base path according to where I host my websites. I didn't find a better way to do this for now.

Do you think the problem may come from the base path ?

**Comment by jarednova** [comment]
Definitely. The relative URLs are constructed by doing some logic to strip out the base paths and return just the `/parts/after/that.jpg`. 

I'd be interested in whether you're able to use WP's native base URL functions rather than your custom script. My hope is that if you're relying on (and interacting with) the default WP for controlling this, Timber _should_ be able to use the same information to help with relative paths. Of course if it doesn't, that's where we can target a fix to help you (and likely, many other users)
