### ISSUE TITLE
Adding Blog Posts to footer 

### ISSUE THREAD

**Issue by rsmal** [timber/timber#2251]
Hey, 
I'm new to Timber and at this point i'm batteling with adding posts to footer section. I made it work on front-page and blog page, but footer is too much for me. 

Can someone please guide me how to add blog posts to footer section in a way posts will be showing on every type of page so to speak 'globaly'?

**Comment by rsmal** [comment]
I figured it out! Please tell me if it's right way.

`	$timber_post = new Timber\Post();
		$context['post_glob'] = $timber_post;
		$args = array(
			'posts_per_page' => 3
		);
		$context['posts_glob'] = Timber::get_posts($args);`

I added code above to function.php file and public function add_to_context($context)

**Comment by jarednova** [comment]
Many ways to do it — what you have totally works @rsmal !
