### ISSUE TITLE
Dark background on <pre> tag in documentation - timber.github.io

### ISSUE THREAD

**Issue by jbbouchet** [timber/timber#2253]
## Expected behavior
Readable examples

## Actual behavior
All `<pre>` tags in documentation have style attribute with `background-color:#272822;`. Examples are not readable.

## Steps to reproduce behavior
Read the docs at https://timber.github.io/
Tested on Safari (Mac and IOS), Chrome, Firefox.

<img width="859" alt="timber-doc-pre-background" src="https://user-images.githubusercontent.com/4848626/82360993-7f0b0300-9a0a-11ea-867b-73a765406773.png">

Thanks Timber team 🙏

**Comment by gchtr** [comment]
@jbbouchet Thanks for reporting this!

I fixed it in https://github.com/timber/docs/commit/3c39e263c9319e9db6e01a8d891d5b2575d2f97b.
