### ISSUE TITLE
Connecting an application (plugin) to the theme

### ISSUE THREAD

**Issue by szepeviktor** [timber/timber#2255]
Hello!

I'm planning implement our application as a WordPress plugin plus some Composer packages including Timber v2.
What would you suggest to send content (HTML output) from the plugin to the theme?
I'd like something better (something OOP) than shortcodes or actions.
What mechanism Timber has to offer?

Cc: @Jony-Shark

**Comment by jarednova** [comment]
@szepeviktor good questions! And probably one with a bunch of answers depending on the exact situation and what sorts of interactions you're planning between plugin and theme. My initial take would be ...

- **Plugin** generates filterable HTML output via various `Timber::compile`s inside of a PHP class. This way you could structure calls like so (let's pretend it's an event plugin):

- `MyPlugin->getEventPreview($event_id);`
- `MyPlugin->getCalender($month, $year);`

- **Theme** can manage these inside of a custom post class and provide to Twig certain functions for usage directly in the template (and handle any internal logic to help manage what's sent to the plugin). 

How does this sound to you?

**Comment by szepeviktor** [comment]
Thank you for your answer.

Ahh! So you suggest to split two tiny parts "MVC" in a way that the Plugin includes everything except the first half of the _controller_ and the actual printing of the _view_?

**Comment by jarednova** [comment]
Much better way of putting it! Of course, it still depends on the plugin's functionality and ways you imagine having users customize and interact with it

**Comment by szepeviktor** [comment]
> ways you imagine having users customize

:-D I only work in agency-type projects and I'm not a developer (I secretly write code here on GitHub but not on request but on **need**)
