### ISSUE TITLE
[Seeking Feedback] Date API

### ISSUE THREAD

**Issue by jarednova** [timber/timber#226]
So I'm looking to clean-up the way dates are referenced in templates. Curious for people's feedback on different approaches.

The current/old way of doing this was all the date properties from the WP database were attached to the `TimberPost` object:
- `TimberPost->post_date`
- `TimberPost->post_date_gmt`
- `TimberPost->post_modified`
- `TimberPost->post_modified_gmt`

To use the date in a template you would most likely use the `display_date` method:

``` php
<p class="dateline">Posted on {{post.display_date}}</p>
```

... which used the date format set in the WordPress admin. However #224 simplifies this, so you can just do..

``` php
<p class="dateline">Posted on {{post.post_date|date}}</p>
```
## From here...

I want to continue making the twig api for this cleaner. As we have `post.title`, `post.content`, I think it makes sense to have `post.date`
#### Approach 1: Properties

This could be as simple as taking all 4 date properties (listed above) and removing the `post_` prefix. Thus in a template you could do:

``` php
<p class="dateline">Posted on {{post.date|date}}</p>
```

or:

``` php
<p class="dateline">Last updated: {{post.modified|date}}</p>
```
###### Questions
- Is `{{post.modified}}` intuitive? Does `{{post.date_modified}}` make more sense?
#### Approach 2: Objects

This would involve transforming the date properties into little objects so that templates could use dot syntax:

``` php
<p class="dateline">Posted on {{post.date|date}}</p>
```

``` php
<p class="dateline">Posted on {{post.date.modified|date}}</p>
```

``` php
<p class="dateline">Posted on {{post.date.gmt|date('M jS, Y')}}</p>
```
###### Questions
- Does `{{post.date.modified}}` or `{{post.modified}}` make more senese?
- Is this needlessly complicated?

Interested to hear some feedback. After writing this up I'm leaning towards approach 1 as it seems much simpler and just as good as writing an object-based approach. But maybe there are benefits/opportunities I'm overlooking.

**Comment by teohhanhui** [comment]
WordPress allows manual timezone offset, so it might not be possible to create a PHP DateTime object with proper timezone set in all cases... This is unfortunate, as I have to be careful when to use post_date vs post_date_gmt, which are both just strings!
