### ISSUE TITLE
Shortcodes filter not working when used include_once or require_once under the ob_start inside callback function

### ISSUE THREAD

**Issue by nkmaurya-dev** [timber/timber#2268]
I have a shortcode say [show_list] and it is not working when used inside the custom field content if I used **include_once** or **require_once** for template loading under ob_start inside callback function. Whereas it is working fine when it is used in the main content i.e the_content() without using of filter shortcodes in twig template.

```
add_shortcode("show_list", "show_list_cb");
function show_list_cb() {
  ob_start();
  include_once '{some_file}'; // This is not working
  return ob_get_clean();
}

function show_list_cb() {
  ob_start();
  include '{some_file}'; // This is  working
  return ob_get_clean();
}
```
This is the same behaviour with require and require_once.

Again a content can have multiple shortcodes, so my query is not about single shortcode. It should work like, how the main content does. 

## Expected behavior
It should work as written in the document. https://timber.github.io/docs/guides/filters/#shortcodes

## Actual behavior
It is not working at all, not outputting anything.

## Steps to reproduce behavior
```
Not working
{{ post.custom_field|shortcodes }}

Working
{{ post.content }}
```

## What version of WordPress, PHP and Timber are you using?
WordPress 5.4.1, PHP 7.4, Timber 1.1.12

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WP.org

**Comment by jarednova** [comment]
@nkmaurya-dev thanks for the issue. I've verified the basic behavior of the `shortcodes` filter in #2274. This is a pretty specific circumstance with how the requires/includes are called within your function. I'm happy to help with review if you'd like to investigate and submit a PR

**Comment by Levdbas** [comment]
Stale issue, so I will close this as well.
