### ISSUE TITLE
realpath() throws warnings

### ISSUE THREAD

**Issue by lesnyrysiek** [timber/timber#228]
Version:  0.18.1
After update I receive a warning:

```
Warning: realpath(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/home/*****/:/tmp:/usr/share/pear) in /home/****/domains/*****.***/public_html/folder/folder/wp-content/plugins/timber-library/functions/timber-loader.php on line 209 
Warning: realpath(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/home/*****/:/tmp:/usr/share/pear) in /home/****/domains/*****.***/public_html/folder/folder/wp-content/plugins/timber-library/functions/timber-loader.php on line 209 
```

That may cause this problem?

**Comment by penguinstampede** [comment]
This seems to have returned in 1.1.9?  I'm using bedrock, not sure if that makes a difference or not.  Rolling back to 1.1.8 removes these warnings.

`Warning: realpath(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/srv/www/:/tmp) in /srv/www/*****/current/web/app/plugins/timber-library/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 37`

**Comment by jarednova** [comment]
@penguinstampede mrrrrrrgggg. I think it's actually an update to Twig (and how it interacts with Timber). Could you try using the `vendor` directly from 1.1.8 in Timber 1.1.9 and see if that resolves the issue? It's not a permanent fix, but it will help confirm where the issue lies

**Comment by penguinstampede** [comment]
Ahh I didn't realize the error messages were slightly different.  But, my version of Twig did not update with Timber as it's held at 1.13 (composer is installing both phpbb and wordpress, in this particular setup).

Will try this on a much simpler WP setup in a bit.

**Comment by halian-vilela** [comment]
@jarednova 

I've managed to circunvent it by changing the hardcoded base_path in `lib/Loader.php` on line 127 from `/` (which explodes) to my `home` (just the usual base_path from my host).

I guess a good option would be to apply a filter that would permit us to change this option, depending on how strict the host is with this `open_basedir` stuff.

**Comment by brettwise** [comment]
I also am using Bedrock and Sage 8.42 and tried using 1.1.9 of Timber with them and received the same warnings. Downgrading to 1.1.8 removed the warnings.

Let me know if I can provide any more info.

**Comment by jarednova** [comment]
@brettwise @halian-vilela @penguinstampede can you try out the code in this PR #1245?

... easiest way is to copy-and-paste the contents of lib/Loader.php into your install — let me know if that does the trick!
