### ISSUE TITLE
_transient_timeout_timberloader wp_options entries not being cleared on clear_cache_timber_database()

### ISSUE THREAD

**Issue by opengeekv2** [timber/timber#2280]
## Expected behavior
I'd expect clear_cache_timber_database() to delete not only _transient_timberloader_ but also _transient_timeout_timberloader_ so those entries do not pollute the database.

## Actual behavior
Wordpress automatic transient cleanup expects to find matching transient and  transient_timeout matching entries in wp_options. If any of the entries aren't there they do not get deleted as you can see in
wp-includes/option.php delete_expired_transients

## Steps to reproduce behavior
1. Install timber
2. Create a template and a twig template that uses Timber::render('template.twig', $context, 600);
3. Ensure that the Timber cache mode is TRANSIENT and no Object Caches are installed or denabled.
5. Access that template in wordpress.
6. Check that new _transient_timeout_timberloader and _transient_timberloader have been created.
7. Create a second template, this time just .php that clears Timber cache: i. e:
`<?php
$loader = new TimberLoader();
$loader->clear_cache_timber();
$loader->clear_cache_twig();`
8. Access that template in wordpress
9. Check how _transient_timberloader entries have been deleted.
10. Access wp-cron.php
11. Check how _transient_timeout_timberloader are not deleted

## What version of WordPress, PHP and Timber are you using?
Wordpress 5.4.1, PHP 5.4, Timber 1.15.2

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer/Packagist

**Comment by opengeekv2** [comment]
I may want to fix this myself and do a pull request this weekend if you find no inconvenience and you think this problem should be adressed.

**Comment by jarednova** [comment]
Thanks for laying out the problem and submitting a PR. I just reviewed and merged. This will be part of the next release (later on this week)
