### ISSUE TITLE
Stopping everyone outputting HTML

### ISSUE THREAD

**Issue by szepeviktor** [timber/timber#2291]
While watching _Building sane, reusable WordPress templates with Twig and Timber - WPCampus 2017_ it came up in my mind.
Could we add a switch that prevents core/hooks/plugins/mu-plugins etc. outputting (echo, print, var_dump ...) HTML?

```twig
<!doctype html>
<html>
{{ our.output }}
</html>
```

**Comment by gchtr** [comment]
Would that be something similar that we already do in the Starter theme with https://github.com/timber/starter-theme/blob/cc8e530a9cd5ece12467dd1a95e1bf47e4b618a8/header.php#L15 and https://github.com/timber/starter-theme/blob/cc8e530a9cd5ece12467dd1a95e1bf47e4b618a8/footer.php#L19?

**Comment by szepeviktor** [comment]
Thank you Lukas.

Should I close this one?

**Comment by wonkeythemonkey** [comment]
I have nothing to add, but I'm glad my WPCampus talk inspired you @szepeviktor !
