### ISSUE TITLE
Implement new PagesMenu API

### ISSUE THREAD

**Issue by acobster** [timber/timber#2292]
Per discussion on #2089, implement the following:

- [x] A `Timber\PagesMenu` class.
- [x] A `timber/pages_menu/classmap` filter.
- [x] A `Timber::get_pages_menu()` function.
- [x] A `Timber\PagesMenuFactory` class - used under the hood in `::get_pages_menu()`, calls the `timber/pages_menu/classmap` filter.
- [x] Make `Menu` and `MenuItem` constructors protected.
- [x] Draft the relevant documentation as well as the notes in the Upgrade Guide for this.

There is already a `test-timber-pages-menu.php` test file. We may want to flesh this out with a few more tests, or redesign some of the existing tests.

**Comment by gchtr** [comment]
I think the documentation is already done for this with #2254.

**Comment by gchtr** [comment]
Implemented in #2562.
