### ISSUE TITLE
Timber breaking WP-backend

### ISSUE THREAD

**Issue by flowjow** [timber/timber#2298]
With Timber activated several styles and functions in the overall WP-backend are broken (see screenshots). E.g. all checkboxes look broken and the screen options are no longer available.

When plugin is deactivated, everything is back to normal.

WordPress 5.4.2
PHP 7.4.7
Timber 1.17.0

Installed approx. one year ago.

Thank you for helping!

<img width="96" alt="Screenshot 2020-07-29 at 17 18 51" src="https://user-images.githubusercontent.com/68960370/88819029-b8f14600-d1bf-11ea-98ba-94b1528e1c8e.png">
<img width="181" alt="Screenshot 2020-07-29 at 17 19 02" src="https://user-images.githubusercontent.com/68960370/88819031-b989dc80-d1bf-11ea-8e1c-31d418b33a4c.png">
<img width="308" alt="Screenshot 2020-07-29 at 17 19 36" src="https://user-images.githubusercontent.com/68960370/88819033-ba227300-d1bf-11ea-88d7-cfd5f487e92b.png">

**Comment by gchtr** [comment]
This could very well be related to a functionality in your theme. Could check whether it’s something that’s called from the **functions.php** file of your theme to narrow the problem down?

**Comment by flowjow** [comment]
Ok, thanks. How/where can I figure out if the issue called by the functions.php?

**Comment by gchtr** [comment]
@flowjow First, I’d remove everything in **functions.php** and check if you still see the error in the backend. If the error is gone, it’s probably something in there. In that case, you could slowly start to add different functionality and check whether that causes the issue. Of course this also depends on how your **functions.php** looks like.

If styles are affected, it could be that your theme loads a CSS file not only in the frontend, but also in the backend.

**Comment by szepeviktor** [comment]
Does Timber have any functionality for WordPress admin?

**Comment by jarednova** [comment]
@szepeviktor very light. There's a bit of customization for the plugin updating, but that's pretty much it

**Comment by szepeviktor** [comment]
Okay, so @flowjow will have an easy job to detect what theme stuff infiltrated the admin.

**Comment by flowjow** [comment]
@gchtr @szepeviktor Thanks guys. For some reason the functions.php was loading the style.css on the backend. I disabled that line and voilà – everything went back to normal.

Problem solved, thanks again for your help!

**Comment by szepeviktor** [comment]
@flowjow You're welcome.

Please close this one.

**Comment by gchtr** [comment]
@flowjow I’m glad you could resolve it 👍 

I’m closing this issue, then.
