### ISSUE TITLE
Twig 2.13.1 introduces a third parameter for twig_array_filter()

### ISSUE THREAD

**Issue by gchtr** [timber/timber#2301]
This issue was raised in https://wordpress.org/support/topic/args-passed-to-twig_array_filter-must-be-an-instance-of-twigenvironment/.

In [this commit](https://github.com/twigphp/Twig/commit/d8259519c057360d1ba0fcb4ae9c3808977915d6#diff-6a6b43ace196ec261ae9f552264f9443R1696), they changed the parameters from

```php
function twig_array_filter($array, $arrow) {}
```

to

```php
function twig_array_filter(Environment $env, $array, $arrow) {}
```

Yes, they prepended a parameter. This now conflicts with the patch we introduced in [Timber 1.14.0](https://github.com/timber/timber/releases/tag/1.14.0), in #2124 to be exact. The tricky thing would be to get the Twig environment in there. Or maybe we need to take a completely different approach.

@palmiak Any idea how we could solve this?

**Comment by palmiak** [comment]
Prepending the parameter was a great idea...

TBH - the only thing that comes to my mind would be to check Twig version and based on it use 2 or 3 params. I think it sucks a bit, but can't think of anything better.

**Comment by jarednova** [comment]
Ugggggggh. I think we might want to consider splitting the solution between 1.x and 2.x here. My proposal would suggest ...

### Version 1.x
1. Introduce a kludge like what @palmiak suggests. Ugly but workable. BUT what about the `Environment`? is that available to the static function `Helper::filter_array()`? I don't believe it is. Hopefully it still performs if sent a null value. 
2. If the above is not true (it fails when sent a `null` value for `$env`) — we'll need to issue some kind of error or warning when `Helper::filter_array()` is called with Twig >= 2.13.1

### Version 2.x
1. Assume/require that Twig 2.13.1+ as the minimum version and go to 3 args. BUT what about the `Environment`? is that available to the static function `Helper::filter_array()`? I don't believe it is. Hopefully it still performs if sent a null value. 
2. If the above is not true, I don't think it's worth doing heroics. Better instead to remove and require that users rely on either custom or native Twig filters for similar behaviors.

**Comment by jarednova** [comment]
Update: just ran a test and sending `null` does NOT work. Without going through the history of that commit/issue, it's hard to understand why this breaking change suddenly landed in the code? 

However, the good news is that we can bypass the call to Twig in the first place by replacing the line to ...

```php
return array_filter( $list, $arrow, \ARRAY_FILTER_USE_BOTH );
```
In looking at the [function definition](https://github.com/twigphp/Twig/blob/81e0746b95cca89adce2c04ecb5cfc42e60cf345/src/Extension/CoreExtension.php#L1572-L1588) I don't see what calling this function in Twig is really giving us besides the cleanliness of going through Twig (and some extra checks, etc. in there)

**Comment by gchtr** [comment]
> ### Version 2.x
> 
>     1. Assume/require that Twig 2.13.1+ as the minimum version and go to 3 args. BUT what about the `Environment`? is that available to the static function `Helper::filter_array()`? I don't believe it is. Hopefully it still performs if sent a null value.
> 
>     2. If the above is not true, I don't think it's worth doing heroics. Better instead to remove and require that users rely on either custom or native Twig filters for similar behaviors.

I thought we were going to remove Timber’s `|filter` anyways:

https://github.com/timber/timber/blob/ab8ae9e96a27127fca663a0546db0d32c72f766c/lib/Twig.php#L219-L225

As I see it, the remaining Todos for 2.x are to remove it and add it to the upgrade guide in https://timber.github.io/docs/v2/upgrade-guides/2.0/#deprecated-twig-filters.

> However, the good news is that we can bypass the call to Twig in the first place by replacing the line to ...
> 
> ```
> return array_filter( $list, $arrow, \ARRAY_FILTER_USE_BOTH );
> ```

I think that’s a good approach and an elegant solution 👍 .

**Comment by jarednova** [comment]
@gchtr good call, I had forgotten that it was slated for removal. So for now, let's bring this into 1.x and then make sure to give things the final 🔪  in 2.x!
