### ISSUE TITLE
THE PURGE

### ISSUE THREAD

**Issue by acobster** [timber/timber#2323]
Once #2316 and #2178 are wrapped up, delete any old code and tests we don't need anymore.

- [x] #2316 
- [x] #2178 

Potential purge candidates:

- [x] `PostGetter` & tests
- [x] `TermGetter` & tests
- [x] Any old `$CommentClass` props and the like
- [x] `QueryIterator` & tests
- [x] `Post::determine_id()` and possibly other methods
- [ ] `Timber_WP_CLI_Command.php` (or move to its own repo)

**Comment by sdunham** [comment]
![THE PURGE](https://media.giphy.com/media/7ZpJgAQAyCKVa/giphy.gif)

**Comment by jarednova** [comment]
🔪

**Comment by jarednova** [comment]
Closing! A follow-up @todo is possibly moving Timber_WP_CLI_Command into its own repo. I want to check to see if there's a current best practice for what those files/repos/packages look like. But also: is it ever used? @szepeviktor I see your a contributor for WP-CLI. Have you ever used the Timber command?

**Comment by szepeviktor** [comment]
> moving Timber_WP_CLI_Command into its own repo

+1

The _Keyboard User_ is a rare bird 🐦

**Comment by szepeviktor** [comment]
> Have you ever used the Timber command?

I'm not a developer! :) and I haven't been is a Timber-based project up to now.
I just like to contribute here ❤️ 

BTW Monorepos are getting popular nowadays. We could have two (or more) Composer packages in one repository.

**Comment by acobster** [comment]
> I just like to contribute here :green_heart:

Spotted: _Contributorus alrtuis_, one of the rarest birds of all! :)

Personally I don't really see a reason to separate `Timber_WP_CLI_Command` out to its own repo, and I like it when plugins implement their own WP-CLI commands. Having it in a separate repo seems like a barrier to entry for not much gain (and IMO Timber's barrier to entry from vanilla WP is already relatively high). Coordinating separate repos is also a lot more maintenance work. You need a good reason.

> We could have two (or more) Composer packages in one repository.

There are some cases where this is advantageous but even this presents a higher maintenance cost and I just don't see a compelling reason to do this here.

All that said, I have literally never run a `wp timber` command (except just now, to kick the tires) and I highly doubt any of my co-workers have either. I know we don't have reliable usage numbers, but do we have a channel for broadcasting out a survey or something, to get some kind of picture of what our usage looks like, and what users want?

**Comment by szepeviktor** [comment]
> and IMO Timber's barrier to entry from vanilla WP is already relatively high

You mean people like to create WordPress themes

- in plain greater-than-less-than PHP without a templating language
- without custom routing
- without custom templates
- without any structure?

**Comment by gchtr** [comment]
It’s not just the WP CLI command, I think we need to think about how we handle all integrations. I proposed to separate repos for each integration a couple of years ago, but I’m not sure that’s a good idea anymore. As Coby mentioned, there’s a lot of maintenance work. Just think about the testing environment we’d have to set up and maintain for each repo 😱. On the other hand, if Timber becomes filled with integrations that are only ever used in a couple of projects, then Timber could become cluttered.

**Comment by szepeviktor** [comment]
+1 for Monorepo.
