### ISSUE TITLE
get_comment_count returns comments+trackpack+pingbacks but post.comments only comments

### ISSUE THREAD

**Issue by errand** [timber/timber#2326]
## Expected behavior
{{ post.get_comment_count }} should return only comments count without trackpacks and pingbacks
because post.comments return only comments

## Actual behavior
post.comments return only post comments

## Steps to reproduce behavior
Add trackbacks and pingback, render {{ dd(post.comments) }}

## What version of WordPress, PHP and Timber are you using?
WordPress  5.5.1
PHP 7.2, 
Timber 1.18.0

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WP.org

**Comment by jarednova** [comment]
Thanks for this info @errand! I'll investigate and follow-up

**Comment by jarednova** [comment]
@errand I realize that I'm really jammed between (regular) work and getting 2.x wrapped up. In case you're interested, I want to give you first crack at the PR opportunity here!

**Comment by marciojc** [comment]
@jarednova I was checking the get_comment_count and is using the native get_comments_number of wp

**Comment by Levdbas** [comment]
This is fixed in 2.0 with the new `Timber\Post::comment_count`. Closing this since we are not going to actively maintain 1.x

**Comment by errand** [comment]
> @errand I realize that I'm really jammed between (regular) work and getting 2.x wrapped up. In case you're interested, I want to give you first crack at the PR opportunity here!

OMG man! I just saw your comment thanx to @Levdbas ! Of course let's close it.
