### ISSUE TITLE
Timber\Twig : issue with 'towebp' filter

### ISSUE THREAD

**Issue by magalieyang** [timber/timber#2331]
Hello,

I am using **Timber\Twig** with Wordpress and I have an issue with the filter "**towebp**".
my part is pretty commun (i guess) :

```
                <picture>
                  <source type="image/webp" media="(min-width:897px)" srcset="{{ member.image.url | towebp }}">
                  <img class="" src="{{ member.image.url }}" alt="{{ member.image.alt }}">
                </picture>
```
I have no visible image is displayed on the final rendering, in fact I have the .webp file created on uploads/ but if I open it on the Chrome web browser, I have no image visible (but if I open the webp on Firefox, I have an image displayed.)
member.image.url is never empty and always have the right path.

My Chrome web browser does support webp format, I have a banner with the same script and it works well.

I don't know where and why sometimes the towebp filter doesn't work well ...
Is there a way to avoid or fix this issue ?

Thank you for any reply and help!

**Comment by jarednova** [comment]
@magalieyang thank you for the issue! The fact that the file is viewable in Firefox, but not Chrome leads me to think the problem lies outside of Timber. That said, you're welcome to post an example image and we can see if there's any clues from its generation/source that might help us understand if there are Timber things going haywire.

**Comment by magalieyang** [comment]
hi @jarednova , (sorry for the late reply)
It seems the issue came from my settings on Docker , more precisely the version of php ... I change it from **5.x** to **7.2** and it works well on Chrome (as well as Firefox).
Thank you anyway!
