### ISSUE TITLE
Gutenberg "Read More" Block option to hide excerpt is not working

### ISSUE THREAD

**Issue by Keysaw** [timber/timber#2337]
"Read More" Block in Gutenberg has an option to hide the excerpt when displaying full content. Toggling that option doesn't affect `{{post.content}}` at all.

This issue was supposedly resolved by https://github.com/timber/timber/pull/2256, but still does not work for me. However, changing the line https://github.com/timber/timber/blob/0a98324a5574484b4b9ccab1fec5fba7abeb20cd/lib/Post.php#L1244 to `if ( strpos($content, '"noTeaser":true') !== false ) {` (notice the double quotes around "noTeaser") fixes it.

## Expected behavior
The HTML output of `{{post.content}}` should be stripped of any tag above the `<!--more-->` tag from Gutenberg if "noTeaser" option is true.

## Actual behavior
Toggling the option in Gutenberg does affect the output.

## Steps to reproduce behavior

- Add "Read More" block in Gutenberg to separate content.
- Check the option "Hide the excerpt on the full content page".
- Print the output using `{{post.content}}` in Twig file.

## What version of WordPress, PHP and Timber are you using?
WordPress 5.5.1, PHP 7.3.20, Timber 1.18.1.

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Installed via Composer.

**Comment by jarednova** [comment]
Thanks @Keysaw! Sounds like it's possible that there are some instances of WP where single vs. double quotes are used. Probably easiest is just to watch for both single and double quotes. Are you interested in doing a PR for this?

**Comment by Keysaw** [comment]
Thanks for the reply, that seems to be the way to fix it indeed. Since I'm fairly new to GitHub I didn't want to go beyond reporting the bug, but I think I could take this opportunity to learn how to make a PR!

I will look into it very soon!

**Comment by jarednova** [comment]
Excellent, glad you're up for the challenge! There are lots of guides out there, but in this case it's a pretty easy fork/edit/submit workflow. If you can get the ball started, I'm happy to add a unit test to confirm

**Comment by errand** [comment]
Hello, for some reason i don't see `noTeaser":true` in the content output, but there is `<!--noteaser-->`, so why not to use it for detection?

I changed fuction to this:
```
protected function content_handle_no_teaser_block( $content ) {
		if ( strpos($content, '<!--noteaser-->') !== false ) {
			$arr = explode('<!--noteaser-->', $content);
			print_r($arr);
			return $arr[2];
		}
		return $content;
	}
```

**Comment by errand** [comment]
![image](https://user-images.githubusercontent.com/1334432/120785053-6bf3a400-c535-11eb-9af5-f0ccb0238815.png)
Hello, did anyone consider that when after using `noTeaser `tag,` $content = $this->content_handle_no_teaser_block( $content );` outputs `{{ post.content }}` with block markup. This sometimes breaks other blocks.

**Comment by Levdbas** [comment]
Since this ticket did not get much traction the last few years I think it is safe to say this is not happening often. That's why I am going to close this issue for now.
