### ISSUE TITLE
PHP4-style private properties

### ISSUE THREAD

**Issue by szepeviktor** [timber/timber#2338]
![kép](https://user-images.githubusercontent.com/952007/95691175-787d6200-0c1d-11eb-9791-86d4d55fc402.png)

Why does 2.x still has PHP4-style properties starting with an underscore?

They are not even all private!
Please advise.

**Comment by szepeviktor** [comment]
`$_wp_using_ext_object_cache` is a core thing.

**Comment by gchtr** [comment]
Hey @szepeviktor

> Why does 2.x still has PHP4-style properties starting with an underscore?

We will fix this as a part of https://github.com/timber/timber/pull/2332. The WordPress Coding Standards don’t allow variables starting with an underscore anyway, so we won’t need to add a special check for that.
