### ISSUE TITLE
Modern code in the repo

### ISSUE THREAD

**Issue by szepeviktor** [timber/timber#2339]
> "php": "^7.0"

Although we plan to support PHP 7.0 we could write PHP 7.4 code and use Rector in the release process.

What do you think?

**Comment by szepeviktor** [comment]
I didn't mean using [fart (`=>`)](https://twitter.com/szepeviktor/status/1313388920919461890) anywhere in Timber!

**Comment by acobster** [comment]
Personally I'm inclined to bump the PHP requirement up to 7.3 or 7.4, given that even 7.2 is [about to](https://www.php.net/supported-versions.php) get EOL'd. And 7.4 is not a very big leap from 7.3.

Rector looks pretty swanky, and if I'm understanding correctly, it wouldn't be a runtime dependency, nor even a _permanent_ dev dependency - we'd only need it for the duration of a hypothetical migration. (Of course we could keep it around for more ongoing/sustainable maintenance, but the point is that we don't really have to think about it outside the context of migrations.) Is that right?

My only reservation is some potential subtlety in an automated change breaking the API in a hard-to-detect way. So once the 2.x is totally solidified, I'd want to run Rector in at least two phases - first for production code (`lib`) and then make sure all the completely unchanged tests still pass. Then and only then would we run a migration on `tests`. Seems like it's designed for that kind of incremental migration so I don't see this being a problem in theory.

All that is to say, I'm open to it, and Rector seems like it could be a game-changer in terms of the feasibility of actually getting such a migration done. That said, this should be part of the discussion already happening on #1863.

**Comment by szepeviktor** [comment]
> if I'm understanding correctly,

No @acobster, we would write code in PHP 7.4 and commit in the repo.
At release time we would run Rector and downgrade the code to PHP 7.0, so Composer and GitHub releases would *only* contain code that runs on PHP 7.0+

Sorry for not being clear.

**Comment by szepeviktor** [comment]
Please see it action: https://blog.logrocket.com/coding-in-php-7-4-and-deploying-to-7-1-via-rector-and-github-actions/
