### ISSUE TITLE
Question: Upgrade to v2

### ISSUE THREAD

**Issue by papazetis** [timber/timber#2346]
As v2 is still in development, will be easy to update v1 to v2 when it will go live?
I am planning to create a theme with v1.

Thanks

**Comment by jarednova** [comment]
Hi @papazetis! We're in the midst of last steps right now on V2. The big stuff is conquered and we're moving forward with the little stuff and code cleaning. "Easy" is a tough call. But we've been very conscious of backwards compatibility in the new version. While there are changes to the API, it's the sort of thing that might take a few hours (at most) to update/convert — not wholesale "throw it out" changes between versions. Hope that helps!

(And if you really want to be a Master of the Universe, start using V2 while it's in development and help us shake out last bugs?)
