### ISSUE TITLE
asm89/twig-cache-extension is deprecated

### ISSUE THREAD

**Issue by romainmenke** [timber/timber#2347]
From composer : 

```
asm89/twig-cache-extension       1.4.0     1.4.0     Cache fragments of templates di...
Package asm89/twig-cache-extension is abandoned, you should avoid using it. Use twig/cache-extension instead.
```

Seems to have moved too https://github.com/twigphp/twig-cache-extension

Can the dependency be replaced here?

**Comment by jarednova** [comment]
Thanks so much for the issue and identifying the fix? I want to give you first crack at the PR opportunity; are you interested in submitting a quick patch?
