### ISSUE TITLE
The content splitted by Read more block isn't rendered correct

### ISSUE THREAD

**Issue by jhhazelaar** [timber/timber#2348]
After the content is split by the option 'Hide the excerpt on the full content page' the content isn't rendered correct, because there is still a close tag of the more block in the content. The content return starts with the `<!-- /wp:more -->` and the rest of content isn't processed by gutenberg.

## What version of WordPress, PHP and Timber are you using?
WP 5.4, PHP 7.4, Timber dev-master

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by jhhazelaar** [comment]
Related ticker: #2218 and #2337

**Comment by gchtr** [comment]
I guess this can be closed.
