### ISSUE TITLE
ACF Forms (functions) Relationship posts are loading only by mouseover event

### ISSUE THREAD

**Issue by fadichmn** [timber/timber#2352]
### Expected behavior
Relationship posts should be loaded immediately.

### Actual behavior
The correct posts in relationship are loading in the form but the posts are loaded only after a mouseover event on the form. 

### What version of WordPress, PHP and Timber are you using?

WordPress: 5.5.1, PHP tested with different 7+ versions, Timer 1.18.2

### How did you install Timber?
Installed through WordPress admin panel.

### Function code (in reference.controller.php)
```php
$context['acf_reference'] = array(
  'fields' => array('field_5f80674e8a092', 'field_5f7dbf51164eb'),
  'submit_value'  => 'Update',
 );
```
### Twig 
```twig
{{ function('acf_form', acf_reference) }}
```

**Comment by jarednova** [comment]
@fadichmn thanks for the issue. Based on this: ` but the posts are loaded only after a mouseover event on the form.` — it would seem to be some kind of JS issue? I'd recommend comparing the output in "naked" WordPress versus what Timber delivers. I can't say we've tested against `acf_form()` before, so there could be other dependencies or assumptions related to that function that require investigation.

**Comment by fadichmn** [comment]
Hi Jared, thanks for your answer.
This is tested with a fresh setup of WordPress, ACF and Timber.
I have tested this locally using Local and on a centos 7 webserver.

**Comment by fadichmn** [comment]
Hi again @jarednova
I have noticed that this code is triggering the mouseover event, in file:
`/plugins/advanced-custom-fields-pro/assets/js/acf-input.js` line 3129

```javascript
this.$el.one( 'mouseover', delayed );
```
I have changed the `one()` function into `load()` and now the posts are loading immediately. Though this bug is only triggered when the Timber plugin is activated. Which is really weird.

**Comment by gchtr** [comment]
This sounds like a jQuery compatibility bug with your WordPress version and ACF to me. The jQuery version shipped with WordPress was [changed in WordPress 5.5](https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/).

> Though this bug is only triggered when the Timber plugin is activated. Which is really weird.

If you use `{{ function('acf_form', acf_reference) }}` to load your form, then deactivating the plugin would mean that you won’t get any HTML output for the form, right? It looks like you’re merely calling `acf_form()` through Twig, which doesn’t necessarily mean that there’s a bug in Timber. To test whether Timber would really affect this, you would have to call the `acf_form()` in PHP.

**reference.controller.php**

```php
acf_form( array(
    'fields' => array( 'field_5f80674e8a092', 'field_5f7dbf51164eb' ),
    'submit_value'  => 'Update',
) );
```

And the other question is: does this also happen with WordPress 5.4 and are you using the latest version of ACF?
