### ISSUE TITLE
Get height of the scailed image

### ISSUE THREAD

**Issue by errand** [timber/timber#2355]
## Is your feature request related to a problem? Please describe.
When we do {{ slide.thumbnail.height|resize(1000) }} the original image height is being used of course.

## Describe the solution you’d like
I'd like to have the way of knowing the height after image is being resized

## Describe alternatives you’ve considered
I have to use for example resize(0, 1000) to get fixed height

**Comment by jarednova** [comment]
Agreed! I find a good place to start with something like this is to imagine the API you'd expect (or desire) to work with in Twig. Then it becomes easy(er) to reverse engineer and figure out how to supply the correct values. Do you have thoughts on that Q? @errand ?

**Comment by errand** [comment]
For now i ended up with an extra function for calculating future dimentions of the image:

`function getScaledDimentions($originalHeight, $originalWidth, $newWidht = 1, $newHeight = 1, $val = 'w'){
	$aspectRatio = $originalWidth/$originalHeight;
	if($val == 'w'){
		return floor($newHeight * $aspectRatio);
	} else {
		return floor( $newWidht / $aspectRatio);
	}
}`

Eventually i'm not so sure that timber is lacking of the function i'm demanding. We can extend it ourselve.

**Comment by acobster** [comment]
Seems like this can be closed?

**Comment by jarednova** [comment]
@acobster agreed. We got plenty of open issues; something that can always be revisited should the universe demand
