### ISSUE TITLE
file_system_to_url() returns wrong url in Bedrock

### ISSUE THREAD

**Issue by Levdbas** [timber/timber#2356]
file_system_to_url() returns wrong url on specific WP installations, for example a bedrock based WP install where site_url returns domain.com/wp/ and the content lives in domain.com/app/

## Expected behavior
file_system_to_url() will return proper home url instead of site url.

## Actual behavior
Returns site url. When changing site_url in this function to home_url the issue is resolved.

## Steps to reproduce behavior
This breaks for example a bedrock based installation.  When an image has to be sideloader bij ImageHelper the image it tries to download resolves to http://yoururl.domain/wp/app/uploads/.... instead of http://yoururl.domain/app/uploads/.

## What version of WordPress, PHP and Timber are you using?
Timber 1.18.2
WordPress 5.5.1

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
composer package

**Comment by jarednova** [comment]
Thanks so much for the issue and identifying the problem point! We've tested against Bedrock setups but there are some corners (like this) that we might have missed. Since you found the issue, I want to give you first crack at the PR opportunity
