### ISSUE TITLE
Term returning false if we have equal slug in different taxonomies.

### ISSUE THREAD

**Issue by emanuellopes** [timber/timber#2362]
## Expected behavior
Term Class should return the term searched by slug.

## Actual behavior
If we have to terms from different taxonomy this will return always the first based on SQL Query.

**What I did to fix this issue on my side:**

```php
<?php

namespace App\Models\Term;

use Timber\Term as TermModel;

class Category extends TermModel {

	public function __construct( $slug = null ) {
		$term = get_term_by( 'name', $slug, 'category' );
		if ( ! isset( $term->term_id ) ) {
			$term = $slug;
		}

		parent::__construct( $term, 'category' );
	}
}

```
## Steps to reproduce the behavior

1. Create a tag with name security and slug security
2. Create a category with name security and slug security.

Do the following:
new Timber\Term('security', 'category'); this will return false because we have two terms with the same name.

The Sql Query on Term Class
```php
/**
	 * @internal
	 * @param int $tid
	 * @return int
	 */
	protected function get_tid( $tid ) {
		global $wpdb;
		if ( is_numeric($tid) ) { // if is an ID exit here;
			return $tid;
		}
		if ( gettype($tid) == 'object' ) {
			$tid = $tid->term_id;
		}
		if ( is_numeric($tid) ) { // never enter here
			$query = $wpdb->prepare("SELECT * FROM $wpdb->terms WHERE term_id = %d", $tid);
		} else {
			$query = $wpdb->prepare("SELECT * FROM $wpdb->terms WHERE slug = %s", $tid);
		}
		$result = $wpdb->get_row($query);
		if ( isset($result->term_id) ) {
			$result->ID = $result->term_id;
			$result->id = $result->term_id;
			return $result->ID;
		}
		return 0;
	}
```
![Screenshot_2020-11-03 16 02 58_KGdoWM](https://user-images.githubusercontent.com/6977270/98009986-149a2380-1dee-11eb-8665-74656f50606a.png)
 

## What version of WordPress, PHP and Timber are you using?
- WordPress 5.5.3
- Timber 1.18.2

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Installed using Composer/Packagist

**Comment by jarednova** [comment]
Thank you @emanuellopes for the issue and clear test case. I was able to confirm the issue in 1.x. However, in 2.x the syntax for getting a specific term like the one you show is via the new Factories classes and the issue does not occur.

I created a patch for the issue you describe for 1.x which I'll add to a new PR
