### ISSUE TITLE
Fatal error: Uncaught Error: Cannot instantiate abstract class Requests_Utility_CaseInsensitiveDictionary

### ISSUE THREAD

**Issue by marcofacheris** [timber/timber#2371]
Hi guys,

I came across this error with Timber 1.18.2:

`Fatal error: Uncaught Error: Cannot instantiate abstract class Requests_Utility_CaseInsensitiveDictionary`

Looks like it only occurs when logged in, but only on the frontend.

Complete stack trace:

`Fatal error: Uncaught Error: Cannot instantiate abstract class Requests_Utility_CaseInsensitiveDictionary in /public_html/wp-content/plugins/timber-library/vendor/twig/twig/src/ExpressionParser.php:93 Stack trace: #0 /public_html/wp-content/plugins/timber-library/vendor/twig/twig/src/Parser.php(166): Twig\ExpressionParser->parseExpression() #1 /public_html/wp-content/plugins/timber-library/vendor/twig/twig/src/Parser.php(122): Twig\Parser->subparse(NULL, false) #2 /public_html/wp-content/plugins/timber-library/vendor/twig/twig/src/Environment.php(735): Twig\Parser->parse(Object(Twig\TokenStream)) #3 /public_html/wp-content/plugins/timber-library/vendor/twig/twig/src/Environment.php(793): Twig\Environment->parse(Object(Twig\TokenStream)) #4 /public_html/wp-content/plugins/timber-library/vendor/twig/twig/src/Environment.php(482): in /public_html/wp-content/plugins/timber-library/vendor/twig/twig/src/ExpressionParser.php on line 93`

The only way to get rid of this is to roll back to version 1.18.1

I'm on WordPress 5.5.3 with PHP 7.3.23

Thanks

**Comment by jarednova** [comment]
Thanks @marcofacheris! It appears that [Requests_Utility_CaseInsensitiveDictionary](https://developer.wordpress.org/reference/classes/requests_utility_caseinsensitivedictionary/) is actually something in WordPress. Not to say that there couldn't be a bad interaction from within Timber or Twig. Has this persisted since you originally filed the issue? Is anyone else seeing something similar?

**Comment by marcofacheris** [comment]
Hi, the issue is gone, I think it was something related to the PHP version: the hosting provider told us that the website was using a new / experimental version of PHP (sorry I don't have more info), which probably caused the issue. Upgrading to a newer / stable version of PHP fixed this.

**Comment by jarednova** [comment]
cool, thanks!
