### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by romanmartushev** [timber/timber#2385]
## Is your feature request related to a problem? Please describe.
This is an example of an error I am getting : `Deprecated: Required parameter $data follows optional parameter $sidebar in vendor/timber/timber/lib/Timber.php on line 462`

## Describe the solution you’d like
PHP 8 has deprecated required parameters after optional parameters.
for example: `public static function get_sidebar_from_php( $sidebar = '', $data )` the `$data` param can be given a default value to fix the error I am getting. This is the function I am getting an error on.

## Describe alternatives you’ve considered
At least the minimum amount of work done so that PHP 8 is supported throughout the project.

**Comment by jarednova** [comment]
Thanks @romanmartushev ! PHP 8 is definitely something we'll be getting ready for. It feels like there should be a pretty limited number of these parameter issues, so please feel free to create a PR!
