### ISSUE TITLE
Resolve existence of `Term::from()` method

### ISSUE THREAD

**Issue by jarednova** [timber/timber#2386]
As I was starting to work on #2360 I noticed this. It looks like there may be an older semi-implementation of a factories pattern partially in Timber to resolve or remove in the method `Term::from()`. Based on the other 2.x Factories this is located in the object's `Factory` class (e.g.: `CommentFactory::from`, `PostFactory::from`). Indeed, there's a `TermFactory::from` that seems fully-functional.

Right now, this seems to be non-functional in 2.x, but I want to confirm before I remove. It appears to have been added in #1969. I'll push a branch to demonstrate the applicable tests that should also be pulled

**Comment by jarednova** [comment]
Please see this branch/commit: https://github.com/timber/timber/commit/2138a2b9f99d77a8a179291a2fe810a6ce9d0eb2

**Comment by acobster** [comment]
Yeah I noticed that too on my last sweep but forgot to write it down - I don't see any reason to keep it.

**Comment by jarednova** [comment]
Cool, what I thought! Just wanted to make sure there wasn't any secret grand plan not immediately apparent.

**Comment by jarednova** [comment]
Closed by #2413
