### ISSUE TITLE
Warning: call_user_func() expects parameter 1 to be a valid callback,

### ISSUE THREAD

**Issue by tanmoy-web** [timber/timber#2387]
HI, 

`add_action('woocommerce_after_add_to_cart_button', array( $this, 'ci_cart_text'), 10, 0 );`

Warning: call_user_func() expects parameter 1 to be a valid callback, class 'Ci_Simple_Features' does not have a method 'ci_cart_text' in C:\xampp\htdocs\theme\wp-includes\class-wp-hook.php on line 285

**Someone, please help** 

**Thanks in advance**

**Comment by jarednova** [comment]
Hi there! Sorry to hear you're having issues (but glad you're giving Timber a try!) We try to keep GitHub clear for just bugs with the Timber code itself. For questions like this, please post to the StackOverflow channel:

http://stackoverflow.com/questions/tagged/timber

Based on what you've posted though, this seems to be an issue unrelated to Timber
