### ISSUE TITLE
Timber Community 

### ISSUE THREAD

**Issue by joworeiter** [timber/timber#2396]
Hi Guys! 
Is there some kind of community in the timber universe? 
Can't find anything, so I'm asking here!

Keep the great work going!

**Comment by jarednova** [comment]
Hi @joworeiter! Alas, we haven't been getting together for Timber bar nights amidst the pandemic (but once I get my vaccine all bets are off).

Most of the main contributors tend to be on Twitter sharing articles, talks, links, etc. we've got the handle [@TimberWP](https://twitter.com/TimberWP). I just added a quick ["community" subheading to the readme](https://github.com/timber/timber/blob/master/README.md#contributing--community) to link out.

There's also GitHub's new Discussions feature:

https://github.com/timber/timber/discussions

... haven't used it yet, but it's fertile ground (and all connected right here) if you had some ideas with what to seed with!

**Comment by joworeiter** [comment]
Thanks for the response!
