### ISSUE TITLE
Improved Menu/Item API

### ISSUE THREAD

**Issue by acobster** [timber/timber#2403]
## Is your feature request related to a problem? Please describe.

I recently had to implement a somewhat advanced frontend pattern:

![Example page with side nav](https://i.imgur.com/gs76NRm.png)

* The main nav contains first-level items (Find a Doctor...) only, appearing at the top of every page
* On interior page templates, a sidebar appears corresponding to the current _second-level subtree_ of the main nav
* Only the relevant second-level item (Cancer) is visible in the side-nav - this is because the nav tree on this site is huge and presenting second-level siblings in this context would have just been information overload
* Third-level items (About Us, Cancer Research & Clinical Trials...) are presented underneath the second-level one in the sidebar
* Fourth-level items (Our Cancer Care Team, Advanced) below the _current_ third-level item are expanded; in other words, only one fourth-level piece of the tree is displayed at any given time

The implementation ended up being pretty generic, with a number of pieces that are useful on their own. It won't be the last time such pieces are useful to us, and I feel like I've finally arrived at an API design that is small but powerful enough to capture many cases like this.

## Describe the solution you’d like

Introduce a `Menu::items()` method with an optional `$options` (array) arg. Options:

- `depth`: max depth of the tree 
- `root_level`: the highest level of items to be displayed. Default 1
  (top level)
- `root_siblings`: whether to get siblings of the current item or its corresponding ancestor at `root_level`. Setting to `false` can be useful for displaying a subset of the tree from root_level downward, for example when displaying a main nav with only top-level items, and more dynamic sidebar displaying only the current second-level item and its descendants. Default `true`.
- `descendants`: string; the name of the specific strategy to employ for determining whether to display any given descendant MenuItem based on that descendant's relationship with the current item. If a valid strategy is not passed, defaults to "all". Valid strategies are:
  - `all`: expand the entire nav tree, regardless of ancestry
  - `none`: display only the top level of the tree (i.e. current and its siblings)
  - `shared_ancestry`: display descendants that share ancestry with the current item. At descendant nodes, unlike `current`, displays siblings of the current item but NOT its "cousins."

Usage from Twig:

```twig
{% set side_nav_items = menu.items({
  root_level: 2,
  root_siblings: false,
  descendants: 'shared_ancestry',
}) %}
<ul class="side-nav">
  {% for item in side_nav_items %}
    <li>
      <a href="{{ item.link }}">{{ item.title }}</a>
      {% if item.children %}
        <ul>
          {% for child in item.children %}
            <li><a href="{{ child.link }}">{{ child.title }}</a></li>

              {% if child.children %}
                <ul>
                  {% for grandchild in child.children %}
                    <li><a href="{{ grandchild.link }}">{{ grandchild.title }}</a></li>
                  {% endfor %}
                </ul>
              {% endif %}

          {% endfor %}
        </ul>
      {% endif %}
    </li>
  {% endfor %}
</ul>
```

The key piece here is that your Twig code _doesn't have to worry about_ the complex logic of which items to display; just loop over them like you normally would. This is because the call to `Menu::items()` is smart enough to return only a subset of the tree.

## Describe alternatives you’ve considered

???

## Additional context

I have a partial implementation that handles every option except `depth`. That will require reworking some Menu internals so that we can more easily traverse the ancestry of an arbitrary node.

For consistency we should tackle #2401 first.

**Comment by Levdbas** [comment]
I though about this for a while but I think your described use case is pretty unique and I am not sure that this will benefit a lot of users in the end legitimizing the implementation of this. So I am going to close this for now. If anyone things otherwise, please let me know!
