### ISSUE TITLE
Get field label 

### ISSUE THREAD

**Issue by garabedium** [timber/timber#241]
Is there any documentation / way to pull a Field Label for a given field into a template?

**Comment by williamsiuhang** [comment]
> Twig Template
> {{ acf.your_field_name_here.label }}

Can't seem to get label data from a repeater inside a group.

```
    {% for category in post.get_field('categories') %}
      <span>{{ category.label }}</span> // Not returning anything. Expecting the repeater label.
      {% for detail in category %}
        <li>{{ detail.product_name }}</li>
        <li>{{ detail.product_description }}</li>
      {% endfor %}
    {% endfor %}
```

Any help is appreciated.

**Comment by gchtr** [comment]
@williamsiuhang
Is the repeater label that you mention a field inside the repeater or the label that you set in your field group?

If it’s a setting that you set in your field group, you cannot access the label from the repeater values that you get through `post.get_field('categories')`. You’re in luck though. There was just a new version released that let’s you do it in an easier way than the one that is mentioned in the ACF Cookbook: https://github.com/timber/timber/releases/tag/1.6.0.

I haven’t tested this, but can you try:

```twig
{% for category in post.get_field('categories') %}
    <span>{{ post.field_object('categories').label }}</span>
    {# … #}
{% endfor %}
```
