### ISSUE TITLE
Error when querying other posts in single product (WC)

### ISSUE THREAD

**Issue by langhenet** [timber/timber#2423]
Hi,
when I query another post in a WC single product context using Timber class methods, WooCommerce (or TImber) treats it as the current product, causing a fatal error.

For example the following code is hooked into the description tab and I use it to query another post:

```
 $content_block_args = array(
    'name'   => 'disco-vetture',
    'post_type'   => 'fe_block',
    'no_found_rows' => true,
    'suppress_filters' => true
  );
  $content_block = Timber::get_post($content_block_args);
```

The `Timber::get_post` causes a fatal error, while if I use wordpress default WP function like `get_posts()` with the same args, everything works fine :-)

## What version of WordPress, PHP and Timber are you using?
 WordPress 5.6.1, PHP 7.3, Timber 1.18.2

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WP.org

**Comment by Levdbas** [comment]
Closing this issue as stale
