### ISSUE TITLE
Controller doesn't find views in child theme

### ISSUE THREAD

**Issue by a-camacho** [timber/timber#2426]
## Expected behavior

- Assuming parent_theme and child_theme, timber is installed in parent_theme/vendor
- I would expect a parent_theme/page.php controller that Timber:render('base/page.html.twig') to look inside child_theme/views first, and then parent_theme/views after.

## Actual behavior
It only uses the view from parent theme.
If I create a child_theme/page.php controller, it works and get the view from child_theme

## Steps to reproduce behavior
Described above

## What version of WordPress, PHP and Timber are you using?
WordPress 5.6.2, PHP 7.4, Timber 2.0-dev

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer inside theme

**Comment by a-camacho** [comment]
Another way (probably better) to say it is that I have to declare in parent theme the Timber::$dirnames like this 👍 

```
if ( is_child_theme() ) {
	Timber::$dirname = array(
		'../../' . basename(dirname(get_stylesheet_directory(), 1)) . '/views',
		'../views'
	);
}
```

Even if I use `../views` in child theme it seems to redirect to parent theme views folder.
Only way I found to make it work is this.

Thanks a lot !

**Comment by Levdbas** [comment]
I use a parent/child setup with Timber everyday and never ran into this issue. Child templates do override parent twig templates. Only difference is that I installed Timber in the site root (I use Bedrock as my starting point). Can you make a repo where you reproduce this issue?

**Comment by pgnd** [comment]
@Levdbas 

> I use Bedrock ...

So am I atm, with WP 6.2 + PHP 8.2 + Timber 2 + Twig 3

currently seeing similar can't-find-views-in-child here:

https://github.com/timber/starter-theme/issues/140

Not clear yet if it's starter-theme, child theme usage, or timber itself :-/

I'll try @a-camacho 's suggestion ...

**Comment by Levdbas** [comment]
@pgnd, did you manage to fix your issue?
