### ISSUE TITLE
TranslatePress compatibility issues

### ISSUE THREAD

**Issue by bilogic** [timber/timber#2427]
## Expected behavior

After installing Timber, I added TranslatePress which redirects http://example.com to http://example.com/en
I'm expecting to see the default English page like when default WordPress theme or Elementor is used.

## Actual behavior

However, http://example.com/en now returns 404 instead of the default page.

## Steps to reproduce behavior

1. Install WordPress
2. Install Timber, now we can see the default Timber theme at http://example.com
3. Install TranslatePress, under `TranslatePress Settings`, set `Use a subdirectory for the default language` to `Yes`
4. Loading http://example.com now will redirect to http://example.com/en which causes a 404

## What version of WordPress, PHP and Timber are you using?

WordPress Version 5.6.1/5.7
Timber Version 1.18.2
TranslatePress Version 1.9.6

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Upgraded to newest version via plugin updater in WordPress dashboard

**Comment by Levdbas** [comment]
Closing this as stale
