### ISSUE TITLE
strip_teaser for the {{post.content}}

### ISSUE THREAD

**Issue by errand** [timber/timber#2428]
## Is your feature request related to a problem? Please describe.

Sometimes we need to split the teaser and the content on the page.

Example:

```
<div class="tease">{{ post.preview.read_more('') }}</div>
<div class="flex">
  <div>{{ post.thumbnail }}</div>
  <div>{{ post.content.strip_teaser(1) }}</div>
</div>

```

We have issue with read_more tag (#2337) so maybe the alternative decision could be implementing `the_content()` function with `$strip_teaser = true`

## Describe the solution you’d like

I tried to rewrite the `public function content( $page = 0, $len = -1, $strip_tease = 0 )` but didn't get the right output. No wonder... I'm going to check how the PostPreview is made..

## Describe alternatives you’ve considered

Alternative solution is here #2337

**Comment by Levdbas** [comment]
I think it would be pretty easy to make this yourself by extending the Post class. We are not going to support this unfortunately because we want to keep Timber core not too feature rich. We hope for your understanding.
