### ISSUE TITLE
ACF flexible field - Check layout existence outside of a for loop

### ISSUE THREAD

**Issue by francesco-bizen** [timber/timber#2442]
Use case:
Among the layouts in a flex field I have an "anchor" one which i use to generate a secondary menu. 

Is there any way of checking if a specific flexible layout exists outside of a loop? I tried all sorts of iteration but i can't figure out a way to do it properly and in the end i just added another field on the page to either show/hide the menu.

I currently have this:
```
{% set extra_menu = post.meta('flex_field') %}

{% if post.show_menu %} // that's the extra field but it's not optimal
  <nav class="secondary-menu">
    {% for anchor in extra_menu if anchor.acf_fc_layout == 'anchor' %}
      <a class="anchor" href="#{{ anchor.title|slugify }}">{{ anchor.title }}</a>
    {% endfor %}
  </nav>
{% endif %}
```

And I'd love to have this:
```
{% set extra_menu = post.meta('flex_field') %}

{% if acf_fc_layout == 'anchor' exists in extra_menu %} // this is ofc wrong syntax it's just to illustrate the need
  <nav class="secondary-menu">
    {% for anchor in extra_menu if anchor.acf_fc_layout == 'anchor' %}
      <a class="anchor" href="#{{ anchor.title|slugify }}">{{ anchor.title }}</a>
    {% endfor %}
  </nav>
{% endif %}
```

**Comment by wonkeythemonkey** [comment]
I don't know of any way to do that entirely in Timber – though if there is one, I'd love to know about it. What I would probably do is modify the context in the PHP file for the template instead. This is pseudo-code, but it would be something like:

```
$context = (get context)

$extra_menu = get_field('flex_field')

if ( none of the fields in $extra_menu has the layout 'anchor' ) {
    $extra_menu = false
}

$context['extra_menu'] = $extra_menu
```

Then in the Twig, you could simply check for the existence of `post.extra_menu` instead of testing against a specific property.

**Comment by nlemoine** [comment]
Use Twig [`filter`](https://twig.symfony.com/doc/3.x/filters/filter.html) filter. 

```twig
{% set extra_menu = post.meta('flex_field')|filter(a => a.acf_fc_layout == 'anchor') %}

{% if extra_menu %}
{# do stuff #}
{% endif %}
```

**Comment by francesco-bizen** [comment]
> Use Twig [`filter`](https://twig.symfony.com/doc/3.x/filters/filter.html) filter.
> 
> ```
> {% set extra_menu = post.meta('flex_field')|filter(a => a.acf_fc_layout == 'anchor') %}
> 
> {% if extra_menu %}
> {# do stuff #}
> {% endif %}
> ```

Hero!! Thanks a lot!

**Comment by gchtr** [comment]
I think this was reopened by mistake? Closing it again :).
