### ISSUE TITLE
Pagination and offset query

### ISSUE THREAD

**Issue by francesco-bizen** [timber/timber#2443]
Basically the design of the blog page is like so:

Page 1
---
POST1
post2 post3 post4

Page 2
--- 
post5 post6 post7

I made a variable to just retrieve the latest post like so:

```
$context['last'] = new Timber\PostQuery(
	array(
		'post_type' => 'post',
		'numberposts' => 1,
	)
);
```

And then offsetted the posts query to account for the extra post
```
$context['posts'] = new Timber\PostQuery([
	'offset' => 1
]);
```

On the first page the result works as intented:

```
{% if posts.pagination.current == 1 %}

{% for post in last %}
{% include 'components/tease-latest.twig' %}
{% endfor %}

{% endif %}

<section class="related-posts">
    <div class="container">

        {% for post in posts %}

        {% include ['components/tease-'~post.post_type~'.twig', 'components/tease.twig'] %}

        {% endfor %}

        {% include 'partial/pagination.twig' with { pagination: posts.pagination({show_all: false, mid_size: 3, end_size: 2}) } %}
    </div>
</section>
```

But the pagination is not working. When i go to page 2 it still shows me the content of page 1.
I tried making separate queries for page 1 and the rest and i spent the last couple hours searching for a solution on SO without any success...
What is the correct approach to achieve correct pagination with offsetted queries?

**Comment by francesco-bizen** [comment]
Edit.
I tried to steer the thing toward the usage of sticky posts which added another whole level of complexity and doesn't seem to really play well with timber and its pagination.

In the end i gave up and i added an ACF field to the blog page to select a specific post to display bigger than the others. The rest of the loop and the pagination work as intended per default and the selected post still appears in the grid, no big deal.
I also hid the whole wordpress "sticky post" functionality from the dashboard to avoid making a mess with the posts order..

Not the most elegant solution but it was the only one i could implement to respect the design.

**Comment by gchtr** [comment]
Aaah, the good old sticky posts with pagination problem. You’ll find that quite a few other developers stumbled into this. I’m not even sure that’s a problem with Timber, but probably with how WordPress queries work. WordPress uses the `offset` parameter itself to create the pagination, so messing with it can actually break pagination.

I think the solution you ended up with isn’t actually all that bad. Thanks for sharing it.

I’m going to close this. If anybody finds a better way to solve this, they are welcome to add it here.

**Comment by brycekirkcalm** [comment]
Is the answer here just that there is no answer?

I have a situation with a featured post at the top of a page, and then 12 posts below, paginated. All I want to do is offset by one, so that the featured post at the top doesn't repeat itself in the 12 posts below. I don't think that's possible to achieve with an ACF field: either the featured post repeats, or there's one featured post and 11 smaller ones.

**Comment by KingWebsites** [comment]
In these situations I always find it easier to **exclude the featured blog post** from the query. No need for offset and the pagination will work just as expected.

```
// Get Timber Context
if ($highlighted_news_id > 0)
{
  // Custom Timber Context
  // On all archive pages remove the Highlighted News from query results
  $context = Timber::context([
    'news_teasers' => Timber::get_posts
    (
      [
        'post__not_in' => array($highlighted_news_id),
      ],
      [
        'merge_default' => true,
      ]
    )
  ]);
}
else // Normal Timber Context
{
  $context = Timber::context();
  $context['news_teasers'] = Timber::get_posts();
}
```
I would also create a separate function that got the post's teaser details from either the query's returned post objects (Timber::get_posts() result) or its ID (featured blog post ID) to be used for all the posts.
