### ISSUE TITLE
is_image() function not working with URL params appended to an image src

### ISSUE THREAD

**Issue by thetoine** [timber/timber#2444]
## Expected behavior

Image class method `is_image()` should return `true` when is called for supported file extensions. 

https://github.com/timber/timber/blob/384f130c7b5dc34363b8bea60eff8b50503b6f9f/lib/Image.php#L535

## Actual behavior

When the attachement SRC includes URLs parameters, `is_image()` method returns `false`.

Example :

https://cdn-name.imgix.net/2021/04/photo-1434871619871-1f315a50efba-scaled.jpeg?auto=format&fit=scale&h=1361&ixlib=php-3.3.0&w=2048&wpsize=2048x2048&s=fd1fd431490df94d4d338e1b1729f3fa

This is happening because WP internal method `wp_check_filetype()` does not support URL params. A 6 years old ticket is still open about this specific issue :

https://core.trac.wordpress.org/ticket/30377

## Possible fix and patch :

Strip URL params in `PathHelper` methods, check out my commit here :

https://github.com/thetoine/timber/commit/97390e202853ed783c0cc9508cc7eb4899ee83e9

## What version of WordPress, PHP and Timber are you using?

WP 5.7.1
Timber 1.18.2

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

WP.org

**Comment by nlemoine** [comment]
Salut @thetoine, 

This issue has been fixed in https://github.com/timber/timber/pull/2730. Unfortunately, we're probably not going to backport this change to Timber 1.x. 

Timber 2.x is almost out and we're putting all our efforts to make it happen ASAP.

**Comment by thetoine** [comment]
Bonjour @nlemoine, thanks for the update!
