### ISSUE TITLE
tojpg function not working with URL query params appended to an image src

### ISSUE THREAD

**Issue by therealgilles** [timber/timber#2447]
The tojpg function does not seem to work if an image src has URL parameters, like a version number for instance. It would be great if it were supported. I am guessing this is also true for other Timber Image functions.

Example: 'https://mysite.com/wp-content/uploads/something/myimage.jpg?ver=1.0'

The '?ver=1.0' part prevent tojpg from working.

**Comment by Levdbas** [comment]
Hi, since this is such an edge-case and didn't get traction I am going to assume that is not something we are going to fix in timber core.
