### ISSUE TITLE
Composer install Timber 2.0 with PHP > 8

### ISSUE THREAD

**Issue by cedricDevWP** [timber/timber#2448]
## Expected behavior

I can't install timber 2.X with php 8 : 

```
timber/timber[2.0.0-alpha.1, ..., 2.x-dev] require php ^7.0 -> your php version (8.0.3) does not satisfy that requirement.
Root composer.json requires timber/timber ^2.0 -> satisfiable by timber/timber[2.0.0-alpha.1, 2.0.0-alpha.2, 2.x-dev].
```

## Steps to reproduce behavior

Create env with PHP 8 and try to install Timber 2.x

## What version of WordPress, PHP and Timber are you using?
PHP 8.0.3, Timber ^2.0

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

```
"require": {
...
"timber/timber": "^2.0",
...
}
```

**Comment by 19h47** [comment]
Hello @cedricDevWP 

You can use `--ignore-platform-reqs` option to ignore PHP requirement and force the installation. [See](https://getcomposer.org/doc/03-cli.md#install-i)
