### ISSUE TITLE
Support for i18n

### ISSUE THREAD

**Issue by JosefJezek** [timber/timber#245]
Could you add support for i18n?
- http://codex.wordpress.org/I18n_for_WordPress_Developers

Nice Drupal 8 Solution
- https://drupal.org/node/1927584
- https://drupal.org/node/2047135
- http://twig.sensiolabs.org/doc/extensions/i18n.html

```
<p class="submitted">
{% trans %}
  Submitted by {{ author.name }} on {{ node.date }}
{% endtrans %}
</p>
```

**Comment by connorjburton** [comment]
Hi @JosefJezek - was this ever resolved?

Thanks
