### ISSUE TITLE
tojpg seems to strip exif data resulting in incorrect orientation

### ISSUE THREAD

**Issue by therealgilles** [timber/timber#2451]
I am having an issue with tojpg processing resulting in an incorrectly rotated image. Looking at the generated jpg file, I see that the EXIF data, including the orientation information, is gone. This seems like a problem, maybe a bug?

PS: I think ideally in my case, it would leave the file alone (as it's already a jpeg file) but my file has a .jpeg extension an tojpg uses .jpg, so it does not see that the jpeg file already exists. That could be another issue to improve maybe?

## Expected behavior
tojpg should preserve EXIF data so that image orientation is preserved.

## Actual behavior
tojpg generates new image without original image EXIF data.

## Steps to reproduce behavior
Any JPEG image with EXIF data processed by tojpg should do.

## What version of WordPress, PHP and Timber are you using?
WordPress 5.7.2
PHP 7.4
Timber 1.18

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by Levdbas** [comment]
Hi @therealgilles , Did you know if you used the GD or ImageMagick extension back then? It seems that the GD lib removes the data by default while the ImageMagick preserves the data by default.

**Comment by therealgilles** [comment]
@Levdbas Sorry I cannot remember and I don't have access to the server anymore. My best guest is that both GD and Imagick were installed. How does Timber decide which one to use?
