### ISSUE TITLE
Class method for post/page siblings

### ISSUE THREAD

**Issue by tlygnersjo** [timber/timber#2452]
## Describe the solution you’d like
I would love to have a class method such as "children" on post that gets all siblings. If parent page is called "Services" and it has "Service 1", Service 2", "Service 3" i.e. and i visit the page for Service 1 i would like to output siblings (Service 2 and Service 3) on that sub page.

Is that something you'd consider adding to Timber?

## Describe alternatives you’ve considered
I can make a custom query (WP Query) or use:
```
wp_list_pages(array(
    'child_of' => $post->post_parent,
    'exclude' => $post->ID
))
```

But it would be much cleaner and easier to output through a class method and do some simple conditionals (if needed) in Timber.

## Additional context
In this case i would like to show a dynamic sidebar menu for the visitors based on siblings (similar services).

**Comment by Levdbas** [comment]
Probably not something we want to implement on Timber core. Thoughts?

**Comment by nlemoine** [comment]
No, this is something that belongs to user land.
