### ISSUE TITLE
Timber::get_term() doesn't fail gracefully if no term is found

### ISSUE THREAD

**Issue by marijnvdwerf** [timber/timber#2455]
## Expected behavior
```php
$unusedID = 123456;
$term = get_term($unusedID);
assert($term === null);
```

## Actual behavior
<table class="xdebug-error xe-notice" dir="ltr" border="1" cellspacing="0" cellpadding="1">
<tbody><tr><th align="left" bgcolor="#f57900" colspan="5"><span style="background-color: #cc0000; color: #fce94f; font-size: x-large;">( ! )</span> Notice: Trying to get property 'term_id' of non-object in /Users/hamster/Projects/ZuidWest/wp/wp-content/themes/streekomroep/vendor/timber/timber/lib/TermGetter.php on line <i>16</i></th></tr>
<tr><th align="left" bgcolor="#e9b96e" colspan="5">Call Stack</th></tr>
<tr><th align="center" bgcolor="#eeeeec">#</th><th align="left" bgcolor="#eeeeec">Time</th><th align="left" bgcolor="#eeeeec">Memory</th><th align="left" bgcolor="#eeeeec">Function</th><th align="left" bgcolor="#eeeeec">Location</th></tr>
<tr><td bgcolor="#eeeeec" align="center">1</td><td bgcolor="#eeeeec" align="center">0.0027</td><td bgcolor="#eeeeec" align="right">367432</td><td bgcolor="#eeeeec">{main}(  )</td><td title="/Users/hamster/.composer/vendor/laravel/valet/server.php" bgcolor="#eeeeec">.../server.php<b>:</b>0</td></tr>
<tr><td bgcolor="#eeeeec" align="center">2</td><td bgcolor="#eeeeec" align="center">0.0108</td><td bgcolor="#eeeeec" align="right">392920</td><td bgcolor="#eeeeec">require( <font color="#00bb00">'/Users/hamster/Projects/ZuidWest/wp/index.php</font> )</td><td title="/Users/hamster/.composer/vendor/laravel/valet/server.php" bgcolor="#eeeeec">.../server.php<b>:</b>219</td></tr>
<tr><td bgcolor="#eeeeec" align="center">3</td><td bgcolor="#eeeeec" align="center">0.0109</td><td bgcolor="#eeeeec" align="right">393200</td><td bgcolor="#eeeeec">require( <font color="#00bb00">'/Users/hamster/Projects/ZuidWest/wp/wp-blog-header.php</font> )</td><td title="/Users/hamster/Projects/ZuidWest/wp/index.php" bgcolor="#eeeeec">.../index.php<b>:</b>17</td></tr>
<tr><td bgcolor="#eeeeec" align="center">4</td><td bgcolor="#eeeeec" align="center">0.9498</td><td bgcolor="#eeeeec" align="right">10161864</td><td bgcolor="#eeeeec">require_once( <font color="#00bb00">'/Users/hamster/Projects/ZuidWest/wp/wp-includes/template-loader.php</font> )</td><td title="/Users/hamster/Projects/ZuidWest/wp/wp-blog-header.php" bgcolor="#eeeeec">.../wp-blog-header.php<b>:</b>19</td></tr>
<tr><td bgcolor="#eeeeec" align="center">5</td><td bgcolor="#eeeeec" align="center">1.0993</td><td bgcolor="#eeeeec" align="right">10233080</td><td bgcolor="#eeeeec">include( <font color="#00bb00">'/Users/hamster/Projects/ZuidWest/wp/wp-content/themes/streekomroep/page-front-page.php</font> )</td><td title="/Users/hamster/Projects/ZuidWest/wp/wp-includes/template-loader.php" bgcolor="#eeeeec">.../template-loader.php<b>:</b>106</td></tr>
<tr><td bgcolor="#eeeeec" align="center">6</td><td bgcolor="#eeeeec" align="center">1.8538</td><td bgcolor="#eeeeec" align="right">11412168</td><td bgcolor="#eeeeec">Timber\Timber::get_term( <span>$term = </span><span>123456</span>, <span>$taxonomy = </span>???, <span>$TermClass = </span>??? )</td><td title="/Users/hamster/Projects/ZuidWest/wp/wp-content/themes/streekomroep/page-front-page.php" bgcolor="#eeeeec">.../page-front-page.php<b>:</b>96</td></tr>
<tr><td bgcolor="#eeeeec" align="center">7</td><td bgcolor="#eeeeec" align="center">1.8538</td><td bgcolor="#eeeeec" align="right">11412168</td><td bgcolor="#eeeeec">Timber\TermGetter::get_term( <span>$term = </span><span>123456</span>, <span>$taxonomy = </span><span>'post_tag'</span>, <span>$TermClass = </span><span>'Timber\\Term'</span> )</td><td title="/Users/hamster/Projects/ZuidWest/wp/wp-content/themes/streekomroep/vendor/timber/timber/lib/Timber.php" bgcolor="#eeeeec">.../Timber.php<b>:</b>200</td></tr>
</tbody></table>
<font size="1"><table class="xdebug-error xe-notice" dir="ltr" border="1" cellspacing="0" cellpadding="1">
<tbody><tr><th align="left" bgcolor="#f57900" colspan="5"><span style="background-color: #cc0000; color: #fce94f; font-size: x-large;">( ! )</span> Notice: Trying to get property 'taxonomy' of non-object in /Users/hamster/Projects/ZuidWest/wp/wp-content/themes/streekomroep/vendor/timber/timber/lib/TermGetter.php on line <i>16</i></th></tr>
<tr><th align="left" bgcolor="#e9b96e" colspan="5">Call Stack</th></tr>
<tr><th align="center" bgcolor="#eeeeec">#</th><th align="left" bgcolor="#eeeeec">Time</th><th align="left" bgcolor="#eeeeec">Memory</th><th align="left" bgcolor="#eeeeec">Function</th><th align="left" bgcolor="#eeeeec">Location</th></tr>
<tr><td bgcolor="#eeeeec" align="center">1</td><td bgcolor="#eeeeec" align="center">0.0027</td><td bgcolor="#eeeeec" align="right">367432</td><td bgcolor="#eeeeec">{main}(  )</td><td title="/Users/hamster/.composer/vendor/laravel/valet/server.php" bgcolor="#eeeeec">.../server.php<b>:</b>0</td></tr>
<tr><td bgcolor="#eeeeec" align="center">2</td><td bgcolor="#eeeeec" align="center">0.0108</td><td bgcolor="#eeeeec" align="right">392920</td><td bgcolor="#eeeeec">require( <font color="#00bb00">'/Users/hamster/Projects/ZuidWest/wp/index.php</font> )</td><td title="/Users/hamster/.composer/vendor/laravel/valet/server.php" bgcolor="#eeeeec">.../server.php<b>:</b>219</td></tr>
<tr><td bgcolor="#eeeeec" align="center">3</td><td bgcolor="#eeeeec" align="center">0.0109</td><td bgcolor="#eeeeec" align="right">393200</td><td bgcolor="#eeeeec">require( <font color="#00bb00">'/Users/hamster/Projects/ZuidWest/wp/wp-blog-header.php</font> )</td><td title="/Users/hamster/Projects/ZuidWest/wp/index.php" bgcolor="#eeeeec">.../index.php<b>:</b>17</td></tr>
<tr><td bgcolor="#eeeeec" align="center">4</td><td bgcolor="#eeeeec" align="center">0.9498</td><td bgcolor="#eeeeec" align="right">10161864</td><td bgcolor="#eeeeec">require_once( <font color="#00bb00">'/Users/hamster/Projects/ZuidWest/wp/wp-includes/template-loader.php</font> )</td><td title="/Users/hamster/Projects/ZuidWest/wp/wp-blog-header.php" bgcolor="#eeeeec">.../wp-blog-header.php<b>:</b>19</td></tr>
<tr><td bgcolor="#eeeeec" align="center">5</td><td bgcolor="#eeeeec" align="center">1.0993</td><td bgcolor="#eeeeec" align="right">10233080</td><td bgcolor="#eeeeec">include( <font color="#00bb00">'/Users/hamster/Projects/ZuidWest/wp/wp-content/themes/streekomroep/page-front-page.php</font> )</td><td title="/Users/hamster/Projects/ZuidWest/wp/wp-includes/template-loader.php" bgcolor="#eeeeec">.../template-loader.php<b>:</b>106</td></tr>
<tr><td bgcolor="#eeeeec" align="center">6</td><td bgcolor="#eeeeec" align="center">1.8538</td><td bgcolor="#eeeeec" align="right">11412168</td><td bgcolor="#eeeeec">Timber\Timber::get_term( <span>$term = </span><span>123456</span>, <span>$taxonomy = </span>???, <span>$TermClass = </span>??? )</td><td title="/Users/hamster/Projects/ZuidWest/wp/wp-content/themes/streekomroep/page-front-page.php" bgcolor="#eeeeec">.../page-front-page.php<b>:</b>96</td></tr>
<tr><td bgcolor="#eeeeec" align="center">7</td><td bgcolor="#eeeeec" align="center">1.8538</td><td bgcolor="#eeeeec" align="right">11412168</td><td bgcolor="#eeeeec">Timber\TermGetter::get_term( <span>$term = </span><span>123456</span>, <span>$taxonomy = </span><span>'post_tag'</span>, <span>$TermClass = </span><span>'Timber\\Term'</span> )</td><td title="/Users/hamster/Projects/ZuidWest/wp/wp-content/themes/streekomroep/vendor/timber/timber/lib/Timber.php" bgcolor="#eeeeec">.../Timber.php<b>:</b>200</td></tr>
</tbody></table></font>
<table class="xdebug-error xe-warning" dir="ltr" border="1" cellspacing="0" cellpadding="1">
<tbody><tr><th align="left" bgcolor="#f57900" colspan="5"><span style="background-color: #cc0000; color: #fce94f; font-size: x-large;">( ! )</span> Warning: assert(): assert($term === null) failed in /Users/hamster/Projects/ZuidWest/wp/wp-content/themes/streekomroep/page-front-page.php on line <i>97</i></th></tr>
<tr><th align="left" bgcolor="#e9b96e" colspan="5">Call Stack</th></tr>
<tr><th align="center" bgcolor="#eeeeec">#</th><th align="left" bgcolor="#eeeeec">Time</th><th align="left" bgcolor="#eeeeec">Memory</th><th align="left" bgcolor="#eeeeec">Function</th><th align="left" bgcolor="#eeeeec">Location</th></tr>
<tr><td bgcolor="#eeeeec" align="center">1</td><td bgcolor="#eeeeec" align="center">0.0027</td><td bgcolor="#eeeeec" align="right">367432</td><td bgcolor="#eeeeec">{main}(  )</td><td title="/Users/hamster/.composer/vendor/laravel/valet/server.php" bgcolor="#eeeeec">.../server.php<b>:</b>0</td></tr>
<tr><td bgcolor="#eeeeec" align="center">2</td><td bgcolor="#eeeeec" align="center">0.0108</td><td bgcolor="#eeeeec" align="right">392920</td><td bgcolor="#eeeeec">require( <font color="#00bb00">'/Users/hamster/Projects/ZuidWest/wp/index.php</font> )</td><td title="/Users/hamster/.composer/vendor/laravel/valet/server.php" bgcolor="#eeeeec">.../server.php<b>:</b>219</td></tr>
<tr><td bgcolor="#eeeeec" align="center">3</td><td bgcolor="#eeeeec" align="center">0.0109</td><td bgcolor="#eeeeec" align="right">393200</td><td bgcolor="#eeeeec">require( <font color="#00bb00">'/Users/hamster/Projects/ZuidWest/wp/wp-blog-header.php</font> )</td><td title="/Users/hamster/Projects/ZuidWest/wp/index.php" bgcolor="#eeeeec">.../index.php<b>:</b>17</td></tr>
<tr><td bgcolor="#eeeeec" align="center">4</td><td bgcolor="#eeeeec" align="center">0.9498</td><td bgcolor="#eeeeec" align="right">10161864</td><td bgcolor="#eeeeec">require_once( <font color="#00bb00">'/Users/hamster/Projects/ZuidWest/wp/wp-includes/template-loader.php</font> )</td><td title="/Users/hamster/Projects/ZuidWest/wp/wp-blog-header.php" bgcolor="#eeeeec">.../wp-blog-header.php<b>:</b>19</td></tr>
<tr><td bgcolor="#eeeeec" align="center">5</td><td bgcolor="#eeeeec" align="center">1.0993</td><td bgcolor="#eeeeec" align="right">10233080</td><td bgcolor="#eeeeec">include( <font color="#00bb00">'/Users/hamster/Projects/ZuidWest/wp/wp-content/themes/streekomroep/page-front-page.php</font> )</td><td title="/Users/hamster/Projects/ZuidWest/wp/wp-includes/template-loader.php" bgcolor="#eeeeec">.../template-loader.php<b>:</b>106</td></tr>
<tr><td bgcolor="#eeeeec" align="center">6</td><td bgcolor="#eeeeec" align="center">1.8630</td><td bgcolor="#eeeeec" align="right">11415032</td><td bgcolor="#eeeeec"><a href="http://www.php.net/function.assert" target="_new">assert</a>( <span>$assertion = </span><span>FALSE</span>, <span>$description = </span><span>'assert($term === null)'</span> )</td><td title="/Users/hamster/Projects/ZuidWest/wp/wp-content/themes/streekomroep/page-front-page.php" bgcolor="#eeeeec">.../page-front-page.php<b>:</b>97</td></tr>
</tbody></table>

## Steps to reproduce behavior
Attempt to get a non-existing term

## What version of WordPress, PHP and Timber are you using?
WordPress 5.7.2, PHP 7.4.19, Timber 1.18.2

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by gchtr** [comment]
Hey @marijnvdwerf 

Thanks for reporting. That’s something we saw as well with `Timber::get_post()`. And it’s one of the reasons we started working on [Timber v2](https://github.com/timber/timber/releases/tag/2.0.0-alpha.1). In the new version, we changed a lot of things under the hood to make handling issues like these easier.

For `Timber::get_term()`, there will be a specific check in the Term Factory that returns `false` if no term could be found with a certain ID:

https://github.com/timber/timber/blob/95e6cebf31c3b238f568507bfed029e75b407158/lib/Factory/TermFactory.php#L49-L57

Unfortunately, we won’t solve this for Timber 1.x.

I’m going to close this, because the solution for this has already been implemented in the [`2.x` branch](https://github.com/timber/timber/tree/2.x).
