### ISSUE TITLE
Change destination folder for Resize.

### ISSUE THREAD

**Issue by KevinDias91** [timber/timber#2462]
Hi ! 

I'd like to change the destination directory for the Resize filter.

So I went to the Resize.php file, and made the changes directly in it, to test. But now i'd like to override the function run() of that file. Is it possible to do it in the functions.php of my theme ? 

`<public function run( $load_filename, $save_filename ) {
   -> $save_filename = (str_replace('uploads', 'resized', $save_filename));

        // Attempt to check if SVG.
		if ( ImageHelper::is_svg($load_filename) ) {
			return false;
		}

....
`

Thank you for your help !

**Comment by twentyfortysix** [comment]
is this what you are looking for
https://timber.github.io/docs/v2/hooks/filters/#timber/sideload_image/subdir

**Comment by Levdbas** [comment]
Closing as stale
