### ISSUE TITLE
using 2.0.0-alpha.2, what's the purpose of $context['post'] in context on home page?

### ISSUE THREAD

**Issue by usamamuneerchaudhary** [timber/timber#2470]
<img width="754" alt="Screenshot 2021-07-19 at 12 41 26 PM" src="https://user-images.githubusercontent.com/24513380/126154854-906730ff-c991-41c6-adad-6b1eb840f2dc.png">

**Comment by nlemoine** [comment]
When you set a static page as home page, WordPress will have a loop filled with `posts` **AND** a page stored in `queried_object`. 

You can access `posts` with `{{ posts }}` (recent posts) and the page (the `queried_object`) with `{{post }}`

**Comment by usamamuneerchaudhary** [comment]
It's actually giving me an error on `setup()` method on bool, I had to revert back to version 1.18. 
<img width="429" alt="Screenshot 2021-07-19 at 1 45 35 PM" src="https://user-images.githubusercontent.com/24513380/126161699-f851dbc4-5cf5-41e8-b6bf-e74e16712525.png">


> When you set a static page as home page, WordPress will have a loop filled with `posts` **AND** a page stored in `queried_object`.
> 
> You can access `posts` with `{{ posts }}` (recent posts) and the page (the `queried_object`) with `{{post }}`

**Comment by nlemoine** [comment]
What's your "reading" settings?

**Comment by usamamuneerchaudhary** [comment]
It's the fresh WP install, I've not changed anything yet.

<img width="673" alt="Screenshot 2021-07-19 at 1 52 34 PM" src="https://user-images.githubusercontent.com/24513380/126162503-9e138372-5179-442f-8d3a-0768fef0becb.png">

**Comment by gchtr** [comment]
@usamamuneerchaudhary Thanks for trying out 2.0.0-alpha.2. I too think this is a bug.

We will probably have to check first what `get_option( 'show_on_front' )` returns.

**Comment by nlemoine** [comment]
Yes, Yoast has a good class for handling current context: https://github.com/Yoast/wordpress-seo/blob/8d93a5ad2f16628bb240c00ecb4e37203e320d00/src/helpers/current-page-helper.php#L40-L62

**Comment by gchtr** [comment]
Hey @usamamuneerchaudhary. I just merged in a fix for this in #2490. This will be in the next 2.x release.
