### ISSUE TITLE
Wrong base url prepend position in Timber\Archives 

### ISSUE THREAD

**Issue by fgdaniel** [timber/timber#2472]
## Expected behavior
When use `new Timber\Archives` with base param, the url of each link must have this structure `domain.tld/{base}/{year}/{month}/{day}/`

## Actual behavior
The url structure now is `domain.tld{base}/{year}/{month}/{day}` when the wp installation is on a folder ex if wp is located in `domain.tld/{wp-folder}` then the url structure is like `domain.tld{base}/{wp-folder}/{year}/{month}/{day}`

## Steps to reproduce behavior

```php
$context['archives'] = new Timber\Archives([
	'type' => 'monthly',
	'show_year' => true,
	'post_type' => 'cpt',
	'nested' => false,
], 'base');
```

## What version of WordPress, PHP and Timber are you using?
Wordpress 5.8, Timber 1.18

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

## My solution

My solution was to clone Class Archives with different namespace, the code who has modified was method `get_archives_link` from Archive class

Below have full method with old code commented

```php
/**
 * @internal
 * @param string $url
 * @param string $text
 * @return mixed
 */
protected function get_archives_link( $url, $text, $post_count = 0 ) {
	$ret = array();
	$ret['text'] = $ret['title'] = $ret['name'] = wptexturize($text);
	// $ret['url'] = $ret['link'] = esc_url(URLHelper::prepend_to_url($url, $this->base)); // Old not working as expected, we expected domain.tld/{base}/{year}/{month}/{day}
	$ret['url'] = $ret['link'] = esc_url(str_replace(home_url(), home_url($this->base), $url)); // this output domain.tld/{base}/{year}/{month}/{day}
	if ($post_count) {
		$ret['post_count'] = (int) $post_count;
	}
	return $ret;
}
```

**Comment by Levdbas** [comment]
Closing this as stale.
