### ISSUE TITLE
Nothing returning from 'get_sub_field_object' from within a Flexible Content Field

### ISSUE THREAD

**Issue by reformatco** [timber/timber#2475]
I am doing a custom Vimeo player using the API, works perfectly at top level with the following - getting the field object as well as returning the code from an oEmbed field

```
{% if post.meta('video_url') %}
      {% set object = function('get_field_object', 'video_url') %}
      {% set url = function('get_field', 'video_url', false, false) %}
{% endif %}
```

I then have a Flexible Content field with one of the fields being a video field, I think I'm missing something with the scope

```
{% for module in row.modules %}
      // module.oembed is the field that works fine in {{ module.oembed }}
      // both of these return nothing if I dump()
      {% set object = function('get_sub_field_object', 'oembed') %}
      {% set url = function('get_sub_field', 'oembed', false, false) %}
{% endfor %}
```

Am i missing something here? I've been going round in circles for hours. Would really appreciate some help

**Comment by twentyfortysix** [comment]
HI,

this is how I would do it
```
{% for view in post.get_field('flexible_content') %}
       {# here I simply check if we are looping thru desired object as you might have multiple kinds here, that is why we use flexible content right? #}
	{% if view.acf_fc_layout == "player" %}
                {# and simple ask for the data here, that gives you full embed html element #}
		{{ dump(view.oembed) }}
	{% endif %}
{% endfor %}
```

do the get_field for the flexible_content first.. all the inner bits do not need any specialities like your functions just call stuff as as view.oembed,..

if you want to get the url only see https://github.com/timber/timber/issues/1211

**Comment by reformatco** [comment]
Thanks I'll try those from issue #1211 - I have a function I want to call after I've got the URL

**Comment by Levdbas** [comment]
Question, is answered and out of date. Can be closed.
