### ISSUE TITLE
Required parameter $data follows optional parameter $sidebar

### ISSUE THREAD

**Issue by dhbit** [timber/timber#2476]
## Expected behavior
It is expected not to have any deprecation warnings.

## Actual behavior
A warning message is displayed:
`Deprecated: Required parameter $data follows optional parameter $sidebar in /path/to/wp-content/themes/mytheme/vendor/timber/timber/lib/Timber.php on line 462`

Upon closer inspection, the file / code in the master branch is already fixed, yet not available via composer in version 1.18.

## Steps to reproduce behavior
1. Create a blank theme
2. Require timber/timber
3. Set up the initial functions.php, style.css, index.php as per e.g. starter-theme
4. Display the home page of the new theme.

## What version of WordPress, PHP and Timber are you using?
- WordPress 5.8
- PHP 8.0.1

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by gchtr** [comment]
Hey @dhbit

Thanks for filling out a proper issue. This issue has already been reported in https://github.com/timber/timber/issues/2450 and #2461, though. So I’m going to close this. A new version will eventually be released.
