### ISSUE TITLE
Loading views from plugins

### ISSUE THREAD

**Issue by cambell-prince** [timber/timber#248]
More of a question that an issue.  Is there a google group / forum for discussion?

I'm writing a plugin that uses Timber and wants to load a twig file.  I'd like the twig file to be possibly over-ridden by the theme.  This way, the plugin can provide a default view which can easily be modified by the theme if so desired.

Is this already possible (doesn't look like it to me)?

If not, then I propose adding it as a feature to the loader.

**Comment by stevegibbings** [comment]
The large WordPress project I'm working on has the need to have to put templates in plugin folders but still be able to override them in a theme.  I get set $locations to get the plugin versions to be picked up but if I have a version overriding it in my theme it never gets picked up, always the plugin version is used.

It doesn't seem to matter if I include the theme folders or not in setting $locations as suggested earlier in this issue comments by @jarednova 

```
// Render the Twig template
Timber::$locations = array(
    get_stylesheet_directory().'/views',
    get_template_directory().'/views',
    IM_RECIPES_DIR.'views'
);

Timber::render(array('single-' . $post->ID . '.twig', 'single-' . $post->post_type . '.twig', 'single.twig'), $data);
```

Or

```
// Render the Twig template
Timber::$locations = array(
    IM_RECIPES_DIR.'views'
);

Timber::render(array('single-' . $post->ID . '.twig', 'single-' . $post->post_type . '.twig', 'single.twig'), $data);
```

It doesn't seem to follow any order always referencing the plugin.

What is the recommend approach for this right now?

Thanks,

Steve

**Comment by ieugen** [comment]
> The core of the problem is that Timber::render is OLD and never anticipated for this. The style of the code is also very static and fragile (adding a new argument to specify the location of templates would break lots of old stuff). My proposal is to create a TimberView object to take on responsibility for the data collection and rendering.

@jarednova : Any progress on removing the static way of using Timber? I'm trying to build a plugin that has templates and I would like to have a sane way of using it, without impacting my theme, that also uses Timber. 

From my experience and other people's , statics are evil [1]. You can't make the code independent and build proper isolated modules with statics. 

[1] http://corfield.org/entry/Static_is_Evil

**Comment by palmiak** [comment]
@jarednova @gchtr there are few topics regarding rewriting locations/views. I think we should left only one (probably https://github.com/timber/timber/issues/261 ) or create a new task for 2.0 Future) and close the rest. What's your opinion guys.

**Comment by enovision** [comment]
This is how I did it in my Wordpress plugin (which uses the Timber plugin). Based on the suggestion of @eyeseast:

I added a bit the context to make it more clear.
```
<?php
/*
  Plugin Name: Your Plugin
  Version: 0.1
  
  Remark: This is just an excerpt and no working plugin
 */
 
define('THIS_PLUGIN_DIR', WP_PLUGIN_DIR . '/your-plugin'); 

if (!isset($timber)) {
    $timber = new \Timber\Timber();
}

class Your_Plugin
{

    function __construct()
    {
		...
        add_action('plugins_loaded', [$this, 'SetTimberTemplateLocation']);
        ...

    }

	...

    function SetTimberTemplateLocation() {
        global $timber;

        if (is_array($timber::$locations)) {
            $views = $timber::$locations;
        } else {
            $views = array($timber::$locations);
        }
        $views[] = THIS_PLUGIN_DIR . "/templates";

        $timber::$locations = $views;
    }
}

$Your_Plugin = new Your_Plugin();
```

**Comment by JUVOJustin** [comment]
Inspired by @enovision solution I have fixed this for my plugins with the following code:
```
<?php
if (empty(Timber::$locations)) {
	Timber::$locations = array();
}
Timber::$locations = array_merge(Timber::$locations, array(
	get_stylesheet_directory() . '/templates'
));
```

However this has some downsides. Every plugin and theme needs to set the locations this way, otherwise they would be overwritten. As far as i can see it works with regular single timber instance installations and for setups were multiple plugins and themes set locations.

**Comment by gchtr** [comment]
Yes, using `Timber::$locations` could get tricky if it’s used elsewhere and there’s no check for existing locations.

@JUVOJustin I’ve been using the `timber/locations` filter. It is applied after the check for `Timber::$locations`. With your example, it could work like this:

```php
add_filter( 'timber/locations', function( $locations ) {
    $locations[] = get_stylesheet_directory() . '/templates';

    return $locations;
} );
```

In the future, the `timber/locations` filter is probably more future-proof, because we might deprecate using `Timber::$locations` in the future.

**Comment by JUVOJustin** [comment]
@gchtr Implemented it your way, because you are right it seems way more future proof. Somehow locations with non-existing folders throw an error now. I was able to solve that by checking if the path exists first. Are you able to reproduce the difference between the filter and the class property?

```php
add_filter( 'timber/locations', function( $locations ) {

  if (file_exists ( get_stylesheet_directory() . "/juvo-session-manager/public/" ) ) {
      $locations[] = get_stylesheet_directory() . "/juvo-session-manager/public/";
  }

  $locations = array_merge($locations, array(
      JUVO_SESSION_MANAGER_PATH . "/public/partials",
      JUVO_SESSION_MANAGER_PATH . "/admin/partials",
  ));

  return $locations;
} );
```
