### ISSUE TITLE
Timber Cache transients not cleared

### ISSUE THREAD

**Issue by mexn** [timber/timber#2483]
## Expected behavior
All Timber related transients should be removed when calling WP CLI command `clear_cache_timber` resp. when calling `Timber\Loader::clear_cache_timber` with caching mode set to `'transient'`.

## Actual behavior
Transients are not cleared. Reason seems to be the fact, that transients are created with key `_transient_timber_...` but the query for clearing refers to `_transient%timberloader_%` what is oviously not matching.

## Steps to reproduce behavior
Set caching mode to `'transient'`, use caching tag in a template `{% cache 'foo' bar %} ... {% endcache %}`, open a page with the template in browser, check database for existance of transients, attempt to clear cache via WP CLI `wp timber clear_cache_timber` and check the database again if the transients are removed.

## What version of WordPress, PHP and Timber are you using?
WordPress: 5.8.1, PHP 8.0, Timber 1.18.2

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by Levdbas** [comment]
As found out in https://github.com/timber/timber/issues/2762 the cache tags are handled by twig and never compiled to transients. Since transients clearing is still working looking at the tests, I am going to close this.
