### ISSUE TITLE
Deprecated: Required parameter $lineno follows optional parameter $only

### ISSUE THREAD

**Issue by WillyMichel** [timber/timber#2492]
Hello,

Using the new Timber 1.19.0 with php 8.0 gives me the deprecated error : 
`Deprecated: Required parameter $lineno follows optional parameter $only in [...]\web\app\mu-plugins\timber-library\vendor\twig\twig\src\Node\IncludeNode.php on line 25`

I know it's in twig, maybe it needs an update ?

Thank you for your work guys !

**Comment by krays** [comment]
Same here using Timber 1.19.1 and php 8.013

**Comment by leonelectro** [comment]
If you pull in Timber via composer, you will end up with Twig 2.14.10 instead of 1.42.5, and the deprecation notices go away.

**Comment by feralheart** [comment]
I've pulled via composer but got the same deprecation error

**Comment by theamnesic** [comment]
This [here](https://github.com/timber/timber/issues/2548): 

> Not sure there's some plan to support PHP 8.1 in Timber 1.x and I'm pretty sure there won't be any. It will require extra work/time we will preferably put in 2.x that is around the corner.

But, a lot of websites are using Timber 1.19.1 with the WordPress.org plugin, which is easy to install and can be auto-updated.

Is a V2 plugin for WordPress.org planned ? Or only composer for ever ?
I need to update my server to PHP 8, should I stop using Timber as a plugin ?

Thanks

**Comment by jarednova** [comment]
@theamnesic unfortunately there's no WP plugin planned. We found having only one method for install to be very important for future sustainability. Timber 1 might work with PHP 8; however it's not officially supported and not a path I would advise

**Comment by timnolte** [comment]
@laurelstreng & @tropicandid I was checking on the status of this only to find that basically Timber 1.x, which we install from WordPress.org, is basically being abandoned and not going to be updated for PHP 8+. The direction here apparently is to install via Composer directly via Packagist, and that will move to 2.x. We are going to have to do another round of major regression testing on all of the client sites. We should plan to discuss this on the next PHP Upgrade stand-up.
