### ISSUE TITLE
Timber / ACF Block Preview - Fields value is false

### ISSUE THREAD

**Issue by vixen1975** [timber/timber#2493]
I am not sure if this is a bug or not, but thought I would raise it just in case.

I have a series of ACF Blocks and they work fine on the front end. However in the CMS if the preview icon of the block is selected it does not show. If you put {{dump(fields)}} in the twig template it returns false.

## Expected behavior
Click the preview icon of the block and see what the block would output.

## Actual behavior
The block displays nothing. If a dump statement `{{dump(fields)}} `is put in the twig template it returns `bool(false);` If I put a `var_dump($context['fields']) `in the render callback function, it may output data that belongs to a different block.  However, if you add a field to the context variable directly `(eg: $context['test']) `and put that in the twig file, it will display.

## Steps to reproduce behavior
Create a block with ACF (https://www.advancedcustomfields.com/resources/blocks/) and add some fields to it.  (Note if I use a standard PHP template for the ACF block, instead of the render_callback function and Timber/Twig it has no problems displaying).

ACF Render Callback function

```
function test_block_render_callback( $block, $content = '', $is_preview = false ) {
    $context = Timber::context();
    $context['block'] = $block;
    $context['fields'] = get_fields(); //fields will not print/dump in the CMS preview
    $context['is_preview'] = $is_preview;
    $context['test'] = 'Test field'; //this will print in the CMS preview
    Timber::render( 'block/test.twig', $context );
}
```

Twig File

```
<div style="background:silver; height:300px; padding:30px;">
  <p>{{dump(fields)}}</p>
   {{test}}
</div>
```
Everything works as expected on the front end.

## What version of WordPress, PHP and Timber are you using?
Wordpress 5.8.1
PHP 7.4
Timber 1.18.2 (Also tried 1.19)
ACF Pro 5.10.2

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by vixen1975** [comment]
I just thought I would follow up on this, as I have worked out where the problem lies. The problem is actually ACF Pro, not Timber. It would seem that the problem occurs when I use an ACF Block on the widgets screen. Although it causes no issues on the widgets screen, it seems to cause problems on the pages in the CMS (this is all fine on the front end, just the preview in the CMS that has issues).

If I var_dump(get_fields()) in the callback function (for a block in use on a page in the CMS) for some reason I get the fields of a block in a widget, not the block I am actually using. Needless to say, the block spits the dummy and does not display, because it either has no data or the wrong data.

I have contacted ACF and they have advised that "The widget area support for blocks is still quite new and we have received a few issues on the block behaviour with the widgets."

I thought I would share this in case anyone else runs into the issue.

**Comment by gchtr** [comment]
Thank you for sharing your insights 👍. I’m sure this is helpful for others who run into this problem.

**Comment by upperrapids** [comment]
I recently encountered a similar problem with ACF block previews, where dumping the result of get_fields() returned data from a different block. ACF's support team suggested that I add the following filter to functions.php:

`add_filter('block_editor_rest_api_preload_paths', '__return_empty_array');`

According to the WordPress documentation, this "filters the array of REST API paths that will be used to preloaded common data for the block editor." Using this resolved the issue for me. I've not seen any adverse consequences of using the filter, but it's early days.
