### ISSUE TITLE
Fatal error related to CacheStrategy after update to 1.19.0

### ISSUE THREAD

**Issue by hsmio** [timber/timber#2494]
After an auto-update of the plugin to version 1.19.0, WordPress returns a fatal Error on the frontend (see below). wp-admin is working fine with no error. Temporary workaround: downgraded to version 1.18.2.

## Expected behavior

No fatal error :)

## Actual behavior

Here's the PHP logs:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Twig\\CacheExtension\\CacheStrategy\\GenerationalCacheStrategy::__construct() must be an instance of Twig\\CacheExtension\\CacheProviderInterface, instance of Timber\\Cache\\WPObjectCacheAdapter given, called in /var/www/…/wp-content/plugins/timber-library/lib/Loader.php on line 282 and defined in /var/www/…/wp-content/plugins/timber-library/vendor/twig/cache-extension/lib/Twig/CacheExtension/CacheStrategy/GenerationalCacheStrategy.php:43\nStack trace:\n#0 /var/www/…/wp-content/plugins/timber-library/lib/Loader.php(282): Twig\\CacheExtension\\CacheStrategy\\GenerationalCacheStrategy->__construct()\n#1 /var/www/…/wp-content/plugins/timber-library/lib/Loader.php(182): Timber\\Loader->_get_cache_extension()\n#2 /var/www/…/wp-content/plugins/timber-library/lib/Loader.php(70): Timber\\Loader->get_twig()\n#3 /var/www/…/wp-content/plugins/timber-library/lib/Timber.php(334): Timber\\Loader->render()\n#4 /var/www/…/wp-content/plugins/timber-library/lib/Ti in /var/www/…/wp-content/plugins/timber-library/vendor/twig/cache-extension/lib/Twig/CacheExtension/CacheStrategy/GenerationalCacheStrategy.php on line 43
```

Hint: I can see a change of type (`\Asm89\Twig\CacheExtension\CacheStrategy\GenerationalCacheStrategy` -> `\Twig\CacheExtension\CacheStrategy\GenerationalCacheStrategy`) here: https://github.com/timber/timber/compare/1.18.2...1.19.0#diff-113c0a23b77a55c2102db8f0839d67ae2434b759177da10b91d3212d72393ab1R282 which maybe explains this error, but I don't have enough knowledge about Timber yet to be sure it's the cause, or to provide a solution.

## Steps to reproduce behavior

I'll try to setup a demo repo asap, just wanted to open this issue quickly as I thought the v1.19.0 update could have potentially caused the same error on other websites.

## What version of WordPress, PHP and Timber are you using?

WordPress 5.7.3, PHP 7.4.18, Timber 1.19.0

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Installed through WordPress plugin dashboard.

**Comment by hsmio** [comment]
Note: it seems we are not the only ones to have this issue, see https://github.com/timber/timber/issues/2491

**Comment by sean-wilk** [comment]
I had the dame issue when updating this morning and it was because I initially used composer and then moved to the plugin but still had the composer code at the top of functions.php.

I removed that like the guy who posted in [#2491](https://github.com/timber/timber/issues/2491) and that fixed it for me.

**Comment by hsmio** [comment]
Thanks @sean-wilk, that was very helpful. Indeed we still require `mindkomm/timmy` through composer, therefore an outdated version of twig gets loaded too. Closing for now, I'll see if updating timmy is sufficient and report back my findings.

**Comment by frontenddevguy** [comment]
Thanks @sean-wilk 
I used a Timber/Twig starter theme and it had the composer code in functions.php.
commented that out and all is working again
