### ISSUE TITLE
I am getting the following error causing my WordPress site to display critical error

### ISSUE THREAD

**Issue by frontenddevguy** [timber/timber#2495]
Fatal error: Uncaught TypeError: Argument 1 passed to Twig\CacheExtension\CacheStrategy\GenerationalCacheStrategy::__construct() must be an instance of Twig\CacheExtension\CacheProviderInterface, instance of Timber\Cache\WPObjectCacheAdapter given, called in /home/runcloud/webapps/vitahomes/wp-content/plugins/timber-library/lib/Loader.php on line 282 and defined in /home/runcloud/webapps/vitahomes/wp-content/plugins/timber-library/vendor/twig/cache-extension/lib/Twig/CacheExtension/CacheStrategy/GenerationalCacheStrategy.php:43 Stack trace: #0 /home/runcloud/webapps/vitahomes/wp-content/plugins/timber-library/lib/Loader.php(282): Twig\CacheExtension\CacheStrategy\GenerationalCacheStrategy->__construct(Object(Timber\Cache\WPObjectCacheAdapter), Object(Timber\Cache\KeyGenerator), 0) #1 /home/runcloud/webapps/vitahomes/wp-content/plugins/timber-library/lib/Loader.php(182): Timber\Loader->_get_cache_extension() #2 /home/runcloud/webapps/vitahomes/wp-content/plugins/timber-library/lib/Loader.php(70): Timber\Loader->get_twig() in /home/runcloud/webapps/vitahomes/wp-content/plugins/timber-library/vendor/twig/cache-extension/lib/Twig/CacheExtension/CacheStrategy/GenerationalCacheStrategy.php on line 43

There has been a critical error on this website.

Learn more about troubleshooting WordPress.

------

What is causing this?

**Comment by jarednova** [comment]
Hi @frontenddevguy — check out #2494 and #2491. A few others have reported similar error due to mixing upgrade strategies (Composer vs. WP.org vs. manual file copy)

**Comment by frontenddevguy** [comment]
This also happens if you used a Timber/Twig starter theme, which contains that composer autoload code
