### ISSUE TITLE
Menu and MenuItem factory inconsistencies

### ISSUE THREAD

**Issue by nlemoine** [timber/timber#2496]
Hi, 

I'm starting to play around with Timber 2.x and noticed some inconsistencies on the menu API.

**Inconsistency in the filter regarding other same kinds of filter**

https://github.com/timber/timber/blob/996a3244100a77ff3349f74d8f7c736f2213de51/lib/Factory/MenuFactory.php#L108-L112

This filter is taken from `post` and `term` except that it does not work in a similar way. Instead of returning a map, it returns a string. Maybe the name is wrong but as a user, I would except that: 
- a filter containing the word `classmap` should return an array
- all `timber/{object}/classmap` should behave the same

Same applies for the `timber/menuitem/classmap` filter.

**Inconsistency in the filter regarding filter argument**

Those filters (`timber/menu/classmap` and `timber/menuitem/classmap`) also have more arguments but in the first case (menu), it receives a `WP_Term` object whereas the 'menuitem' filter gets a `Timber\Post` object. I think they should get either WP core objects (`WP_*`) or Timber objects but not both mixed up.

**Comment by gchtr** [comment]
Hmmm, yeah, this is an inconsistency. Discussion around this started in https://github.com/timber/timber/issues/2089#issuecomment-538764945, if I can remember correctly.

> as a user, I would except that:
> 
>     * a filter containing the word `classmap` should return an array

I didn’t see that before, but I agree with you.

Because menus and menu items are not really tied to a core type in WordPress, we can’t really apply class maps here. The same goes for users by there, for which we have a `timber/user/classmap` filter.

I guess we could rename the filters:

- `timber/user/classmap` → `timber/user/class`
- `timber/menu/classmap` → `timber/menu/class`
- `timber/menuitem/classmap` → `timber/menuitem/class`

> I think they should get either WP core objects (`WP_*`) or Timber objects but not both mixed up.

We’re merely passing in here what we already know. If we can provide a Timber object, because an object relies on one, we pass a Timber object. Otherwise, we only have a WordPress core object. Yeah, so being consistent here would mean we would have to pass a WordPress object to the `timber/menuitem/classmap` filter.

What if we passed in what we have as a first argument, and the Timber object as a second one?

**Before**

```php
$class = apply_filters( 'timber/menuitem/classmap', MenuItem::class, $item, $menu);
```

**After**

```php
$class = apply_filters( 'timber/menuitem/class', MenuItem::class, $wp_object, $timber_object, $timber_menu );
```

**Comment by nlemoine** [comment]
> Because menus and menu items are not really tied to a core type in WordPress, we can’t really apply class maps here.

The fact that menus and terms are not core objects in WP doesn't mean we can't apply a classmap. Menus don't have property but they have `$args` we can rely on. For the core `post`, the classmap is based on the `post_type` property (because it makes sense) but it could have been any other property like `post_status` but who needs a `Published` class? That doesn't make any sense, I know 😅. I'm just trying to demonstrate that opting for the `post_type` is an opinionated choice, even it feels like the natural one.

In the menu scope, why not use a location classmap? So we could mimick the post factory behavior like:

```php
$class = apply_filters('timber/menu/classmap', [], $term);
$class = $classmap[$location] ?? Menu::class;
```

I guess 99% of WP developers use the menu location slug to get their menu because it's the most reliable/making sense way to get them. Thus, the "natural" property to use in that case IMO. 

> What if we passed in what we have as a first argument, and the Timber object as a second one?

I have no opinion on this and will leave the final cut 😄  It's always better to have more options when using filters.

**Comment by gchtr** [comment]
@nlemoine Now that you explain it this way, I totally see how a menu class map would make sense 👍. The [example in the docs](https://timber.github.io/docs/v2/guides/class-maps/#the-menu-class-map) was really the only relevant example I could come up with.

I’d say the way forward is clear on this one.

- [ ] Update menu class map based on a location.
- [ ] Add a `timber/menu/class` filter.
- [ ] Rename `timber/menuitem/classmap` filter to `timber/menuitem/class` filter and add WP object parameter before the Timber object to be consistent with other filter.
- [ ] Rename `timber/user/classmap` filter to `timber/user/class`.
- [ ] Update docs and Upgrade Guide.

@nlemoine Do you agree?

**Comment by nlemoine** [comment]
Looks like a good plan! I can handle the code within the next days, can leave the docs part to you?

**Comment by gchtr** [comment]
Sounds good! Yes, you can leave the docs part to me :). I’ll wait for your pull request and then add the docs changes on the same branch.

**Comment by nlemoine** [comment]
Great! Can you have a look at #2503? I'd like this to get merged ASAP to avoid a lot of rebasing conflicts.

**Comment by nlemoine** [comment]
While working on this, I noticed a potential pitfall in the `MenuFactory`. 

This factory (`Timber::get_menu()`) takes anything as a first argument: a term id, a `WP_term`, a term slug, a term name, a location slug.

But there might be a problem when it falls under the `from_string` case which is used for term slug/term name/location slug. 
https://github.com/timber/timber/blob/2.x/lib/Factory/MenuFactory.php#L74-L83

What if I try to get a menu from a location slug (say `header`) but a term with the slug `header` exists and is not located at `header` location (I know, this sounds silly but this might happen)? You will get the wrong menu. 

That's why `wp_nav_menu()` uses another argument (`theme_location`) to make the difference between a string that could be a slug/name and a string that is a location.

**Comment by nlemoine** [comment]
I noticed (from a long time actually) that some hooks are missing from the menu generation process. Especially the `pre_wp_nav_menu` which is usually used for [caching](https://github.com/inpsyde/menu-cache/blob/master/index.php#L41) purposes. I don't know how this could be implemented in Timber but I'm always surprised to see how many (greedy) queries are made to generate menus when I check Query Monitor.

**Comment by gchtr** [comment]
> This factory (`Timber::get_menu()`) takes anything as a first argument: a term id, a `WP_term`, a term slug, a term name, a location slug.
> 
> But there might be a problem when it falls under the `from_string` case which is used for term slug/term name/location slug. [https://github.com/timber/timber/blob/2.x/lib/Factory/MenuFactory.php#L74-L83](https://github.com/timber/timber/blob/2.x/lib/Factory/MenuFactory.php?rgh-link-date=2021-09-29T19%3A20%3A23Z#L74-L83)
> 
> What if I try to get a menu from a location slug (say `header`) but a term with the slug `header` exists and is not located at `header` location (I know, this sounds silly but this might happen)? You will get the wrong menu.
> 
> That's why `wp_nav_menu()` uses another argument (`theme_location`) to make the difference between a string that is a slug/name and a string that is a location.

Uuuh, it’s great you’re catching those before others will definitely run into!

We’ve found that sometimes it’s hard to discern what you want to do in a factory by just having one function. That’s why we introduced the `Timber::get_*_by()` functions. With those, we can catch all these cases that are used less often but which we still want to support.

- [Timber::get_post_by()](https://github.com/timber/timber/blob/1d10cceecb1428c98af7fb3c80a0affe7c64a462/lib/Timber.php#L426)
- [Timber::get_attachment_by()](https://github.com/timber/timber/blob/1d10cceecb1428c98af7fb3c80a0affe7c64a462/lib/Timber.php#L546)
- [Timber::get_term_by()](https://github.com/timber/timber/blob/1d10cceecb1428c98af7fb3c80a0affe7c64a462/lib/Timber.php#L705)
- [Timber::get_user_by()](https://github.com/timber/timber/blob/1d10cceecb1428c98af7fb3c80a0affe7c64a462/lib/Timber.php#L839)

Would a `Timber::get_menu_by()` function help here as well?

```php
Timber::get_menu_by( 'slug', $arg );
Timber::get_menu_by( 'location', $arg );
```

And after having written this, I realized that someting like this already came up in https://github.com/timber/timber/issues/2089#issuecomment-586739839. Out of this, we realized that there’s another case we should handle separately: the [Pages Menu](https://github.com/timber/timber/issues/2292).

> I noticed (from a long time actually) that some hooks are missing from the menu generation process. Especially the `pre_wp_nav_menu` which is usually used for [caching](https://github.com/inpsyde/menu-cache/blob/master/index.php?rgh-link-date=2021-09-29T19%3A28%3A45Z#L41) purposes. I don't know how this could be implemented in Timber but I'm always surprised to see how many (greedy) queries are made to generate menus when I check Query Monitor.

There’s definitely room for improvement here. I tried to summarize this in https://github.com/timber/timber/issues/1820 some time ago. Maybe you have some fresh ideas for that.

**Comment by nlemoine** [comment]
Can we close this one? I think #2517 has everything needed.
