### ISSUE TITLE
Query params are transformed to lowercase in URLHelper::get_params()

### ISSUE THREAD

**Issue by peterkracik** [timber/timber#2507]
Hi,

I am using `URLHelper::get_params()` to get parameters, but they are returned in lowercase. 
In my case, I would need to have them case-sensitive. My URL contains an ID similar to this one `8chr5ULa` which is then used for query and external API and the id in lowercase throws an error. 
I saw you call the `strtolower` and I was wondering if there is a reason for it, or it could be removed.

version: 1.18
but I can see, that the behaviour is the same on v2.

https://github.com/timber/timber/blob/2f6955077dfc264c116ef38433e181119523e318/lib/URLHelper.php#L536

**Comment by kevin-quach** [comment]
I second this request as I use this for routing a deeplink which is case sensitive.

**Comment by Levdbas** [comment]
Pr is merged and will be included in next 2.x release.
