### ISSUE TITLE
Naming configuration for side loaded images

### ISSUE THREAD

**Issue by paulkre** [timber/timber#2508]
Hello everyone, this project is amazing. Thanks for all the hard work!

## Is your feature request related to a problem? Please describe.

I'm using Timber in combination with the [WP Offload Media](https://wordpress.org/plugins/amazon-s3-and-cloudfront/) plugin. When using one of Timber's image modification filters (e.g. `resize()`) it will cause Timber to download the image to the server's "uploads" directory in order to perform the modification. The name of the side loaded image is the `md5()` hash based on the image's external URL. The resulting URLs for modified images are not very SEO friendly:

```
/wp-content/uploads/2021/10/e16806f9aae4f1b0ec61251ea02847b8-250x250-c-default.png
```

In comparison, here is the URL of the same resized image without using the WP Offload Media plugin:

```
/wp-content/uploads/2021/10/SEO-Friendly-Title-250x250-c-default.png
```

## Describe the solution you’d like

I'm aware that the side loaded file name has to contain a hash based on the origin URL because it is likely, that the external storage location does not follow the same path structure as WordPress's "uploads" directory (`<year>/<month>`). But I don't see a reason why it should not be possible to override the default naming scheme of side loaded images. This could easily be done without breaking changes by introducing a filter.

This is how Timber currently determines the name of any side loaded image (`$file` being the external URL):

https://github.com/timber/timber/blob/e339378d81578c5587dc5c11a1f7d44c5fa29792/lib/ImageHelper.php#L347-L359

We just have to add one line to the function:

```diff
public static function get_sideloaded_file_loc( $file ) {
   $upload = wp_upload_dir();
   $dir = $upload['path'];
   $filename = $file;
   $file = parse_url($file);
   $path_parts = PathHelper::pathinfo($file['path']);
   $basename = md5($filename);
+  $basename = apply_filters('timber/ImageHelper/sideloaded_file/basename', $basename, $path_parts);
   $ext = 'jpg';
   if ( isset($path_parts['extension']) ) {
      $ext = $path_parts['extension'];
   }
   return $dir.'/'.$basename.'.'.$ext;
}
```

Then we'd be able to define the naming scheme inside the theme configuration:

```php
add_filter('timber/ImageHelper/sideloaded_file/basename', function ($basename, $path_parts) {
  return $path_parts['filename'] . '-' . substr($basename, 0, 6);
}, 10, 2);
```

Resulting in SEO friendly URLs like this one:

```
/wp-content/uploads/2021/10/seo-friendly-title-e16806-250x250-c-default.png
```

I'm happy to provide a PR if this proposal gets approved.

**Comment by Levdbas** [comment]
Hi @paulkre,

Sorry for the very late reaction. If you are still up for creating a PR based on the v2 branch, you are more than welcome.

If you can add a docblock for the filter as well, that would be amazing.
```
/**
* Filters basename for sideloaded files.
*
* @example
* ```php
* // Change the basename used for sideloaded images.
* add_filter( 'timber/sideload_image/basename', function ($basename, $path_parts) {
*     return $path_parts['filename'] . '-' . substr($basename, 0, 6);
* }, 10, 2)
* ```
*
* @param string $basename Current basename for the sideloaded file.
* @param array $path_parts Array with path info for the sideloaded file.
*/
```
