### ISSUE TITLE
Documentation of compile method

### ISSUE THREAD

**Issue by alexkuc** [timber/timber#2509]
This is not strictly speaking a technical bug, but consideration regarding documentation for `compile()` method.

According to current docs (I am using v2):

https://github.com/timber/timber/blob/8dcb41667c8315b7051cdaffb328dfa59668e832/lib/Timber.php#L294-L295

The wording

> Name of the Twig file to render

gives an impression that I need to register location first. However, if I will pass full absolute pass, `compile()` works as expected without any issues.

My consideration - should 

> Name of the Twig file to render

be changed to something like

> Name or full path of the Twig file to render

Use case: when you create component-like directory & file structure, you can have files (or classes) with different path (namespace) but the same file name. When `compile()` uses registered path, the first matching file will be compiled (name collision issue). When using full path, such issue is not an issue anymore.

**Comment by gchtr** [comment]
@alexkuc Thanks for this issue. Even details like that can make a huge difference! 😎

I just added a pull request in #2677 that improves this.

And I have to admit that I didn’t know either that I can pass in full paths. Fantastic!

![](https://media.giphy.com/media/xT0xeJpnrWC4XWblEk/giphy-downsized.gif)

**Comment by gchtr** [comment]
Resolved in #2677. This will soon be updated in the docs.
