### ISSUE TITLE
AltoRouter Unitialized string offset error post 1.19 upgrade

### ISSUE THREAD

**Issue by brodieaustin** [timber/timber#2510]
After upgrading to Timber 1.19, I'm setting an error from AltoRouter when I load my site's homepage:

```
Notice: Uninitialized string offset: -1 in {path}/wp-content/plugins/timber-library/vendor/altorouter/altorouter/AltoRouter.php on line 207
```

Running on Wordpress 5.8.1 with PHP 7.4 and Nginx. I have two custom routes defined in functions.php (not for homepage obvs). Site is running locally, so debugging is turned on, so I'm seeing the error on page.

Never seen this with previous version of Timber. 

Full stack trace: (note that I've obscured the full file path)

```
# | Time | Memory | Function | Location
-- | -- | -- | -- | --
1 | 0.0000 | 359768 | {main}( ) | .../index.php:0
2 | 0.0003 | 360048 | require( '{path}/wp-blog-header.php ) | .../index.php:17
3 | 0.0005 | 360432 | require_once( '/{path}/wp-load.php ) | .../wp-blog-header.php:13
4 | 0.0007 | 361144 | require_once( '{path}/wp-config.php ) | .../wp-load.php:50
5 | 0.0009 | 362472 | require_once( '{path}/wp-settings.php ) | .../wp-config.php:107
6 | 0.0719 | 2763640 | do_action( $hook_name = 'init' ) | .../wp-settings.php:578
7 | 0.0719 | 2764016 | WP_Hook->do_action( $args = [0 => ''] ) | .../plugin.php:470
8 | 0.0719 | 2764016 | WP_Hook->apply_filters( $value = '', $args = [0 => ''] ) | .../class-wp-hook.php:327
9 | 0.1506 | 4190528 | Routes::match_current_request( '' ) | .../class-wp-hook.php:303
10 | 0.1506 | 4190528 | AltoRouter->match( $requestUrl = ???, $requestMethod = ??? ) | .../Routes.php:30
```

**Comment by nlemoine** [comment]
> That won't work if you are installing Timber via Wordpress Packagist or direct from wordpress.org

I never use Timber as a plugin and you shouldn't too. Timber is more a library than a plugin, 2.x will longer be available as a plugin.

> That repo already has the update: "altorouter/altorouter": "^2.0".

It doesn't, [the fix is in 2.0.2](That repo already has the update: "altorouter/altorouter": "^2.0".).

**Comment by brodieaustin** [comment]
@jarednova I just deactivated then deleted plugin through WordPress admin. Reinstalled, tested routes, and it seems to have worked! Thanks so much.

**Comment by jarednova** [comment]
Wow, love when that happens. Thanks again for the original report and big thanks to @nlemoine and @nhstephan for help narrowing in and solving the issue!

**Comment by nhstephan** [comment]
@jarednova Thanks for the update! Doing good here, glad to see the Timber community growing.
