### ISSUE TITLE
Post meta with value NULL is retrieved as Array when getting all meta via $post->meta()

### ISSUE THREAD

**Issue by gustavo-roganti** [timber/timber#2519]
I'm using Timber 2.0.0-alpha.4 

I have a post with some meta values. One of this meta values is set to NULL.

When I get all the meta at the same time via $post->meta() I expect this result:
`array (
  'foo' => 'bar',
  'baz' => NULL,
)`

Instead I am getting this
`array (
  'foo' => 'bar',
  'baz' => 
  array (
    0 => NULL,
  ),
)`

## Steps to reproduce behavior
Add some meta to a post, set one meta value as NULL (eg. using update_post_meta), then retrieve all meta at the same time via `$post->meta()`

## Analysis and potential fix 
(sorry I don't know how to create a PR and I don't know if my code is ok)

In the function `\Timber\CoreEntity::fetch_meta`  in the file `timber/lib/CoreEntity.php` at around line `180` a bit of code is commented with `// Mimick $single argument when fetching all meta values.`
The code tries to detect if a meta value is an array with a single value. To do this, it uses `isset()`. Isset fails when a variable _is_ set but is also null. 

In this case checking with array_key_exists could be better (see https://stackoverflow.com/a/68135825), so a potential fix could be to replace this line:
`if ( 1 === count( $meta ) && isset( $meta[0] ) ) {`
with this line:
`if ( 1 === count( $meta ) && array_key_exists(0, $meta)) {`

**Comment by gchtr** [comment]
Resolved in #2643.

Thanks a lot for your investigation and the pull request, @gustavo-roganti. Very much appreciated! 🙌
