### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by Web-Assembler** [timber/timber#2521]
https://github.com/timber/timber/blob/5c9d981b463146ddfb8026dca6cd31561f007770/lib/Image/Operation/Resize.php#L215

I think it should say `...please install php-gd`

**Comment by jarednova** [comment]
it should! up for submitting a PR?

**Comment by Taru-source** [comment]
@jarednova 
i will create PR to fix this typo. Is it OK?

**Comment by Web-Assembler** [comment]
@Taru-source I already did a pull request (https://github.com/timber/timber/pull/2523) forgot to close this. Thanks though!

**Comment by Taru-source** [comment]
@Web-Assembler 
Got it! Thank you for sharing.
