### ISSUE TITLE
->meta() method returns null

### ISSUE THREAD

**Issue by Sooyoos** [timber/timber#2522]
## Expected behavior
When I use the meta() method I expect to get the acf field value when it is the case. And if not, it gets the post meta, then return its value.

## Actual behavior
When I want to get a value from a custom post meta I want the post meta value.

## Steps to reproduce behavior
Use meta() method to get a post meta.
```
$posts = new Timber\PostQuery( $args );
foreach ( $posts as $post ) {
    update_post_meta( $post->id, 'meta_name', 'meta_value' );
    var_dump( $post->meta('meta_name') ); // should be null
    var_dump( get_post_meta( $post->id, 'meta_name', true ) ); // should be 'meta_value'
}
```

The line in the Timber code that create this null bug is in the file : `timber\timber\lib\Post.php`
inside the `function get_field()`, on the line 897 : `$value = apply_filters('timber_post_get_meta_field', $value, $this->ID, $field_name, $this);`
If I var_dump() before this line I get the post meta value OK, after the given line I have a null.

## What version of WordPress, PHP and Timber are you using?
WordPress 5.8.2
PHP 7.4.14 or 8.0.7
Timber 1.19.1

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
I install Timber with composer with the GitHub repo "timber/timber": "^1.19"
And I think this is the case. A few week/month ago I used the wpackagist repo, and I think that I got this bug after I went on the github install (I wanted to use Timber with php8).

**Comment by xanghyr** [comment]
Hello,

Indeed something changed at some point. Don't know when or how.
But I fixed this with this piece of code in functions.php: 
```
add_filter( 'timber_post_get_meta_field', 'custom_post_get_meta_field', 30, 3 );
function custom_post_get_meta_field( $value, $post_id, $field_name ) {
	if ( $value === null ) {
		$value = get_post_meta( $post_id, $field_name, true );
	}
	return $value;
}
```

**Comment by EpicKau** [comment]
The timber acf integration hooks on 'timber_post_get_meta_field', and only returns value from get_field function.
(https://github.com/timber/timber/blob/75bb47223e32b787fd74e92f692f9fc34dec7e74/lib/Integrations/ACF.php#L29)
Do you get null if you use a valid acf field?

**Comment by Sooyoos** [comment]
No If I get a valid acf field I get the value. But when I try to get a post meta (no acf) with the meta() method I get a null value.

**Comment by nlemoine** [comment]
I think this issue isn't related to Timber. ACF recently (5.11) changed the `get_field` behavior (which used to get the meta value whether a field for the requested exists or not). 

But they reverted back more recently (5.11.2): 

> Fix - get_field() and the_field() functions can once again access meta values regardless of being registered with ACF, restoring functionality that existed before 5.11

https://www.advancedcustomfields.com/changelog/

Can you provide your ACF version? Or confirm this is accurate?

**Comment by Sooyoos** [comment]
Yes I was on 5.11, so that must be it. Thanks to have pointed that out !
