### ISSUE TITLE
meta_query "OR" relation for multiple conditions not working - 2.0.0-alpha.4

### ISSUE THREAD

**Issue by Dominic-Marcelino** [timber/timber#2531]
## Expected behavior
 I would expect that I can use the `relation` parameter for a meta-query inside the `Timber::get_posts()` method
[WP-Docs](https://developer.wordpress.org/reference/classes/wp_meta_query/)

## Actual behavior
The relation is not correctly working and only the last meta query is used

## Steps to reproduce behavior
````
$context = Timber::context([
    'persons' => Timber::get_posts([
      'post_type'      => 'person',
      'posts_per_page' => -1,
      'post_status'    => 'publish',
      'meta_query'     => [
        'relation' => 'OR',
        'meta_query' => [
          'key'     => 'hide_on_teampage',
          'compare' => '=',
          'value'   => 'false',
        ],
        'meta_query' => [
          'key'     => 'hide_on_teampage',
          'compare' => 'NOT EXISTS',
        ],
      'tax_query'      => $tax_query,
      'order'          => 'ASC', 
      'orderby'        => 'menu_order',
    ]),
  ]);
````

This will only return posts where the meta 'hide_on_teampage' does not exists

## What version of WordPress, PHP and Timber are you using?
WordPress 5.7.5., PHP 7.3.5, Timber  2.0.0-alpha.4

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer/Packagist

**Comment by Lucathiel** [comment]
@Dominic-Marcelino 

Isn't that because you're giving another 'meta_query' key to arrays in root 'meta_query'
Doesn't that work in that way instead ?

```
$context = Timber::context([
    'persons' => Timber::get_posts([
      'post_type'      => 'person',
      'posts_per_page' => -1,
      'post_status'    => 'publish',
      'meta_query'     => [
        'relation' => 'OR',
        [
          'key'     => 'hide_on_teampage',
          'compare' => '=',
          'value'   => 'false',
        ],
        [
          'key'     => 'hide_on_teampage',
          'compare' => 'NOT EXISTS',
        ],
      'tax_query'      => $tax_query,
      'order'          => 'ASC', 
      'orderby'        => 'menu_order',
    ]),
  ]);
```

**Comment by nlemoine** [comment]
@Lucathiel is right, your query is malformed. Try using a native `WP_Query`, you will get wrong results too as `Timber::get_posts()` is a wrapper around `WP_Query`.

**Comment by Dominic-Marcelino** [comment]
@Lucathiel @nlemoine Thank's for pointing out!
