### ISSUE TITLE
Update composer/installers to 2.0

### ISSUE THREAD

**Issue by Levdbas** [timber/timber#2533]
## Is your feature request related to a problem? Please describe.
As other libraries are updating composer/installers to 2.0 such as roots/bedrock it becomes more difficult to use Timber in combination with said libraries. Installing Timber on a fresh bedrock install breaks the version constraints.

## Describe the solution you’d like
I suggest bumping the version and create a point release for 1.x and applying the same increase in the 2.x branch. I am not sure if we need to update the version constraints like this `"composer/installers": "~1.0|~2.0",` or to `"composer/installers": "~2.0,`

**Comment by adamtomat** [comment]
As @Levdbas mentioned, this is causing a lot of difficulties (my difficulties I mean it's broken) for us using Timber and Bedrock. I'm happy to try and get some PRs together for 1.x and 2.x branches to help get this resolved

**Comment by adamtomat** [comment]
Thanks for merging this in 👍  

Are you also able to tag this too, please (e.g. `1.19.2`)?

**Comment by jarednova** [comment]
@adamtomat (and future Googlers): please see ....

https://github.com/timber/timber/releases/tag/1.19.2
