### ISSUE TITLE
Timber::get_image returns false when ACF image passed in.

### ISSUE THREAD

**Issue by michaelmano** [timber/timber#2534]
When using the new helper method `get_image` in place of `Image().src` it returns false on ACF field images
This happens in the twig templates as well as straight up php files.

## Expected behavior
return the image object.

## Actual behavior
returns false.

## Steps to reproduce behavior
1. create ACF field containing image. (Mine was a repeater of images)
2. Loop over each image in field and use `get_image`

```
// anywhere on your page template
$acfImages = get_field('images', $post->ID);
$images = array_map(function($image) {
    return \Timber\Timber::get_image($image);
}, $acfImages);

print_r($images);
exit;
```

## What version of WordPress, PHP and Timber are you using?
PHP@8.1 and Timber 2.0.0-alpha.4

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Packagist

**Comment by twentyfortysix** [comment]
Are you sure you feed the **ID** to the Timber\Timber::get_image?
The ACF gallery and Image has 3 possible outputs: [Array, url, ID]
Just a pure guess, the $image you feed in is not an ID

**Comment by Levdbas** [comment]
Closing as stale
