### ISSUE TITLE
Patterns styles for ACF blocks are not working with the latests wordpress version

### ISSUE THREAD

**Issue by pjoulot** [timber/timber#2541]
## Expected behavior
When using patterns, the styles should load inside the preview. The documentation says to use the hook enqueue_block_assets but it doesn't include the stylesheets inside the preview of the patterns.
https://timber.github.io/docs/guides/gutenberg/

```
function my_acf_block_editor_style() {
    wp_enqueue_style(
        'example_block_css',
        get_template_directory_uri() . '/assets/example-block.css'
    );
}

add_action( 'enqueue_block_assets', 'my_acf_block_editor_style' );
```
So I am guessing the documentation needs to be reviewed to describe a way to include styles that are working in the preview of the patterns

## Actual behavior
The preview of the patterns should include the styles. The documentation needs to be fixed to work with the latest version of wordpress.

## Steps to reproduce behavior
- Create a custom ACF block
- Include one stylesheet affecting the HTML of the ACF block (using enqueue_block_assets)
- Create a pattern using the ACF block
- Try to include the pattern inside a page, the preview should not show the block with the style applied

I have to include my stylesheet like this in order to make the preview work
```
function custom_editor_styles() {
	add_editor_style(get_template_directory_uri() . '/css/global/global.css');
}
add_action( 'after_setup_theme', 'custom_editor_styles' );
```

## What version of WordPress, PHP and Timber are you using?
Wordpress 5.9 + Timber 1

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
using the Timber plugin

**Comment by Levdbas** [comment]
Are you sure this is caused by timber? Did you try to render the full block by php and skip Timber altogether? I can't imagine Timber has a role in this, but I might be wrong.
