### ISSUE TITLE
ACF meta  field accessed via Term model aren't processed by ACF integration

### ISSUE THREAD

**Issue by mgburns** [timber/timber#2553]
We're attempting to set up an ACF field group on a taxonomy term with a Relationship field and are seeing inconsistent results than what we observe when attached to a post.

## Expected behavior
Using a `Timber\Term-based model to access an ACF Relationship field value returns an array of IDs instead of Timber model objects when `Return Format` is set to `Post Object` 

## Actual behavior
Using a `Timber\Term`-based model to access an ACF relationship value returns an array of Timber model objects.

## Steps to reproduce behavior
1. Set up an ACF field group with a Relationship field on a Taxonomy. Make sure `Return Format` is set to `Post Object`
2. Edit a term and assign a post to the relationship
3. Attempt to use the field in Twig (ex: `term.meta('related_post')`

The related posts will appear as an array of post IDs instead of an array of Timber model classes. I believe the logic in question was introduced in https://github.com/timber/timber/pull/1238/files#, before ACF supported storing term meta in the term meta table. (This was added in ACF 5.5, which included a [migration process](https://github.com/AdvancedCustomFields/acf/blob/68114e19b6cb2c58045ab5419d94dd41d901a0bf/includes/upgrades.php#L375-L544)).

## What version of WordPress, PHP and Timber are you using?
WP 5.9.1, PHP 7.4.9, Timber 1.19.1

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer/Packagist

**Comment by EpicKau** [comment]
I quickly tested it and can't confirm it.
I get an array of Timber\Post objects back, 
ACF Pro 5.12, WP 5.9.1,  Timber 1.19.1

Could you rename your field an test it again?

**Comment by mgburns** [comment]
Thanks for looking in to it, @EpicKau! I just spun up a fresh WP install with the Timber starter theme. Here are a few relevant screenshots:

![localhost_8080_wp-admin_post php_post=5 action=edit](https://user-images.githubusercontent.com/1508604/157909209-fc34fd78-15f1-4317-bfea-e3818b278c59.png)
![localhost_8080_wp-admin_term php_taxonomy=category tag_ID=2 post_type=post wp_http_referer=%2Fwp-admin%2Fedit-tags php%3Ftaxonomy%3Dcategory](https://user-images.githubusercontent.com/1508604/157909220-219d4dd4-4d0d-4945-919c-0b687e43a2f7.png)
![Screen Shot 2022-03-11 at 9 57 36 AM](https://user-images.githubusercontent.com/1508604/157909244-8d0783cc-fe68-4fd5-a49f-69287af4f00a.png)
![Screen Shot 2022-03-11 at 9 57 47 AM](https://user-images.githubusercontent.com/1508604/157909257-e706c31a-d572-4949-b03b-04a6f2f2dbe8.png)
![Screen Shot 2022-03-11 at 9 57 28 AM](https://user-images.githubusercontent.com/1508604/157909278-dc3315fa-82ed-4b72-b3ae-ff7433bc6660.png)

**Comment by EpicKau** [comment]
@mgburns I just copy your setup and get exact the same output (array of Timber\Post objects). But I dont use the timber starter theme. I will take a look at it and report back.

**Comment by mgburns** [comment]
@EpicKau Ah got it -- that's an interesting approach (hooking into `acf/format_value`), may be a good workaround for us given that the original issue is resolved in the `2.0-alpha`. We'll do some testing on our end and close this issue if there are no drawbacks. Thanks again for taking the time to confirm/sharing your workaround!

**Comment by jarednova** [comment]
Thanks so much for the work to help @EpicKau !!!

**Comment by Levdbas** [comment]
Closing this as this issue seems resolved in 2.0 branch as stated.
