### ISSUE TITLE
\Timber\ImageHelper::resize external (sideloaded) image file URL creates duplicate image files

### ISSUE THREAD

**Issue by gritdigital-mibu** [timber/timber#2557]
## Expected behavior
I expected the \Timber\ImageHelper::resize() helper method when passed the same external image file URL to create a single cached resized image file (with its filename based on the URL).

## Actual behavior
A duplicate image is created each time the helper method is called despite the external image URL remaining the same.

## Steps to reproduce behavior
Place `\Timber\ImageHelper::resize('https://via.placeholder.com/10x10.png', 1, 1, 'center');` in `functions.php` and refresh the page/run multiple times, on every page load a new image will be created.

## What version of WordPress, PHP and Timber are you using?
WordPress 5.9, PHP 8.0.12, Timber 1.19.1

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by gritdigital-mibu** [comment]
Apologies!

Yikes *embarrassed*...
This was due to a `sanitize_file_name` filter hook registered in the code manipulating the filename - I'll leave this issue here in hope it saves someone else some time/pain.

**Comment by jarednova** [comment]
Ha! All good, thanks @gritdigital-mibu
