### ISSUE TITLE
Chmod value incorrect with umask

### ISSUE THREAD

**Issue by vitrix** [timber/timber#2567]
In the file timber-library/vendor/twig/twig/src/Cache/FilesystemCache.php on line 66 there is a command for chmod
The line states `@chmod($key, 0666 & ~umask());`
But when i perform this on an default ubuntu setup on  an Azure server the permissions are not good for me.
I want to allow the user and it's group to write and give others read rights.

So i changed the code to `@chmod($key, 0775);`
I'm wondering if it's possible to change this in the plugin itself, so i don't need to change it when there is an update for the plugin.

**Comment by Levdbas** [comment]
Since this is a part of the twig cache library this it's something that needs to be addressed in the twig cache repo. https://github.com/twigphp/cache-extra
