### ISSUE TITLE
Incorrect date, modification date (time is zero)

### ISSUE THREAD

**Issue by fabswt** [timber/timber#2568]
## Expected behavior

I have an article with the following properties, as confirmed by the WordPress dashboard:

- creation date: 2022-02-23T11:35:46+01:00 .
- modification date: 2022-02-23T11:59:41+01:00

When I use `{{ post.date|date('c') }}` and `{{ post.modified_date|date('c') }}` I would expect to get the same values as above.

## Actual behavior

In practice, I'm getting this:

- creation date: 2022-02-23T00:00:00+01:00
- modification date: 2022-02-23T00:00:00+01:00

Work around:

I'm using this for my single template. Adding this to single.php:

```php
$context['date_published'] = get_the_time('c');
$context['date_modified'] = get_the_modified_time('c');
```

And then using `{{ date_published}}` and `{{ date_modified }}` in the Twig template returns the expected value, with non-zero values for the time.

## What version of WordPress, PHP and Timber are you using?

- PHP 8.1.3
- WordPress 5.9.2.
- Timber 1.19.1

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Composer/Packagist

**Comment by Levdbas** [comment]
This might be related to the incompatibility with the twig date functionality that has addressed in https://github.com/timber/timber/pull/2135.

**Comment by gchtr** [comment]
Yes, this look very much like an issue that was fixed in 2.x. For 1.x, we won’t fix this, unfortunately. I’m going to have to close this.
