### ISSUE TITLE
Moving WP template file contents to a function

### ISSUE THREAD

**Issue by szepeviktor** [timber/timber#2569]
Seeing the starter theme there are almost-empty template files.
For example https://github.com/timber/starter-theme/blob/2.x/theme/single.php

Could you suggest a way to put all code in template files into e.g. `index.php`?
Something like `if (is_singular('post')) {` ...

Do we need https://github.com/Brain-WP/Hierarchy or can we figure it out inhouse?

**Comment by gchtr** [comment]
Maybe this issue is related: #1536

But I think this is a discussion we’re going to have in the future.

**Comment by gchtr** [comment]
I’d say we should rely on libraries like [Brain-WP/Hierarchy](https://github.com/Brain-WP/Hierarchy) for this. Solving this in Timber itself is not a goal in the near future.
