### ISSUE TITLE
How to install Twig 2.x with wpackagist 

### ISSUE THREAD

**Issue by fabswt** [timber/timber#2573]
I'm using WPpackagist to install WordPress and its plugins.

It installs Twig 1.x. Is there any way to require Twig 2.x instead?

**Comment by Levdbas** [comment]
Timber 1.x is bound to twig 1.x. The upcoming Timber 2.x uses Twig 2.x underneath. Timber 2 is currently in Alpha state and is no longer a WordPress plugin you can install via WPackagist. It is now a standalone package. See the https://github.com/timber/timber/tree/2.x branch

**Comment by jarednova** [comment]
@Levdbas nails it!
