### ISSUE TITLE
Timber class is never loaded on the 2.x-dev

### ISSUE THREAD

**Issue by merijnponzo** [timber/timber#2574]
I recently i upgraded to php 8 and composer 2 but with a new bedrock wordpress install and "timber/timber": "2.x-dev" the Timber class is never loaded.

What i tried:
**1. Following the documentation:**
```
composer require timber/timber:dev-2.x
```
results into:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires timber/timber dev-2.x, found timber/timber[dev-joshlevinson-feature/interfaced-object-factories, ..., dev-phpunit6, 0.16.6, ..., 0.x-dev, v1.0-rc.1, ..., 1.19.1, 2.0.0-alpha.1, ..., 2.x-dev] but it does not match the constraint.
```

**2. Adding timber/timber": "2.x-dev to my composer.json and run composer update or install**
This doesn't results into any error messages but the timber class is never loaded

**3. This works:**
```
composer require timber/timber:dev-master
```

Basis test:
https://github.com/merijnponzo/bedrock-timber-test.git

Php 7.4
Composer 2

**Comment by thaikolja** [comment]
Same here, also using Bedrock, but PHP 8.*. The last version Timber worked on is `2.0.0-alpha.4`.

**Comment by naderabbara** [comment]
You need to rewrite the functions and classes that you're loading for Timber 2. The timber starter theme isn't fully ready for timber 2.x, still has various deprecated 1.x functions. Look at the guide in the docs.

**Comment by gchtr** [comment]
As I can see in your files, you still use `new Timber\Timber()` to load Timber:

https://github.com/merijnponzo/bedrock-timber-test/blob/cc1e2cb9d9dffa733460fbea8cfa34047f81de3f/web/app/themes/timber-starter-theme/functions.php#L3

This is deprecated in 2.0.0. Please refer to https://timber.github.io/docs/v2/upgrade-guides/2.0/#initializing-timber for how to upgrade this.

As @naderabbara mentioned, there will probably be other errors.

We didn’t fully update the starter theme yet, but keep track of this in https://github.com/timber/timber/issues/1784.
