### ISSUE TITLE
Filter or action to modify site.option() logic

### ISSUE THREAD

**Issue by broiniac** [timber/timber#2575]
Hi there.

## Is your feature request related to a problem? Please describe.
I'm building Carbon Fields integration. I'd used @nlemoine code as a base (see issue #1474). I can't promise anything, but I hope my code will be „sharable” at some point.

I would like to use `{{ site.option('config_key') }}` to fetch data saved by Carbon:
https://docs.carbonfields.net/learn/containers/theme-options.html

Carbon has rather specific naming convention, which can't be translated into „default” options keys easily:
https://docs.carbonfields.net/learn/advanced-topics/field-name-patterns.html

To fetch option created by Carbon using Timber (v2) *now*, we have to use underscore in the key name like this: `{{ site.option('_config_key') }}` which is *rather* fine as long as we want to use very simple field types only. But this approach won't play nicely with complex fields, nor some Carbon extensions (like `iamntz/carbon-fields-urlpicker`), which persist something like this into database:
```
+-----------+-------------------------+----------------------+----------+
| option_id | option_name             | option_value         | autoload |
|-----------+-------------------------+----------------------+----------|
| 867       | _example_url            |                      | no       |
| 868       | _example_url|||0|url    | https://example.com/ | no       |
| 869       | _example_url|||0|anchor |                      | no       |
| 870       | _example_url|||0|blank  | 0                    | no       |
+-----------+-------------------------+----------------------+----------+
```

## Describe the solution you’d like
What I miss is filter or action which can be used to integrate Carbon (or any other integration which creates wp-options entries) with Timber nicely. We have `timber/post/pre_meta`, `timber/post/meta_object_field`, etc., but nothing related to options.
Can I suggest filter `timber/site/get_option` or action `timber/option/get`?

## Describe alternatives you’ve considered
Super simple solution would be creating Twig Function, which will call `carbon_get_theme_option`, but it's not very Integration-ish since we have to add custom-code.
Con: we won't be using `{{ site.option('config_key') }}`.
Con: Extra custom-code required in Integration installation process.

Another, less simple but more powerful and still requiring custom-code solution would be overriding `__get($option)` in class, which extends `Timber\Site`. 
Pro: we can now use `{{ site.option('config_key') }}` as usual.
Con: Extra custom-code required in Integration installation process.

## Additional context
I'm not sure if missing something and there is some nice way to integrate option-fetching into Timber and Integration.

**Comment by Levdbas** [comment]
Hi @broiniac ,

The ACF integration also relies on adding the option fields yourself via:

```php
$context['options'] = get_fields('options');
```

I did a quick search but there doesn't seem to be a similar way to get all site options right within carbon fields?
You say you would like a filter to change the `__get()` method, but that would require to add a parameter to site.options method and a custom filter for that to work. Not really a path we would like to move into. 

The twig function method you describe does sound like the way forward. And I think you can just add that twig function in the integration code as well. You can chime in at https://github.com/timber/timber/pull/2400
