### ISSUE TITLE
1.19.2 does not appears at wpackagist-plugin/timber-library

### ISSUE THREAD

**Issue by drzraf** [timber/timber#2583]
## Expected behavior
composer update find the `wpackagist-plugin/timber-library` package at version 1.19.2

## Actual behavior
It doesn't

## Steps to reproduce behavior
Go to [wpackagist-plugin/timber-library](https://wpackagist.org/search?q=timber-library) and click the refresh button.

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
`composer require wpackagist-plugin/timber-library:1.19.2`

**Comment by timnolte** [comment]
1.19.2 doesn't appear to have been published to the WordPress.org repository: https://wordpress.org/plugins/timber-library/

**Comment by timnolte** [comment]
@jarednova it doesn't appears that 1.19.2 has been properly published to the WordPress.org repository.

**Comment by jarednova** [comment]
Thanks @timnolte ! will get that set this week

**Comment by jarednova** [comment]
@timnolte this now live on WP.org! I'm actually going to follow up with another release soon though to ensure the fixes for WP 6.0 can be published asap
