### ISSUE TITLE
Query parameters and custom routes in Wordpress 6.0

### ISSUE THREAD

**Issue by chrisgherbert** [timber/timber#2584]
## Expected behavior
The third parameter of Routes::load() becomes the main query of the loaded page template.

## Actual behavior
The query parameters are not used.

## Steps to reproduce behavior

Pass query parameters to Routes::load() -- they no longer work in Wordpress 6.0, but work fine upon downgrading to 5.x

```
Routes::map('/this-is-a-test-route', function(){
  Routes::load('page-route-test.php', false, ['post_type' => 'posts', 'posts_per_page' => 2], 200);
});
```

## What version of WordPress, PHP and Timber are you using?
Wordpress 6.0, PHP 7.4.29, Timber 1.19.2

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by michaelmano** [comment]
So I've had this issue with mulitple of our sites, How I am hacking around it right now and don't feel comfortable doing is passing `$wp->query_vars` into the `get_post` and `PostQuery`.

**Comment by kemmerly** [comment]
I'm seeing the same on a couple of sites using custom routes and updated to WP 6.0.

**Comment by michaelmano** [comment]
Hey @jarednova thanks for that, Ive tested it with several sites and its working perfectly.

**Comment by mdahlke** [comment]
@jarednova Tested this on both sites that were having the issue and it seems to have resolved it. 

WP 5.9.3 & 6.0

Thanks for all the work you put into this, it's greatly appreciated!

**Comment by jarednova** [comment]
Thanks to @mdahlke @rmens @trsteel88 and @michaelmano for all their help to confirm and @chrisgherbert for the issue. This is now live as Timber 1.20.0!

https://github.com/timber/timber/releases/tag/1.20.0
https://wordpress.org/plugins/timber-library/
