### ISSUE TITLE
Blank page when using Timber + Heroic Knowledge Base

### ISSUE THREAD

**Issue by ixtrim** [timber/timber#2585]
Hi, 

I do have a custom theme using Timber / Twig - never had an issue before, with any other plugin. 
Unfortunatelly when we use [Heroic Knowledge Base](https://herothemes.com/wordpress-knowledge-base/). 

We do see on those pages totally clean / blank page. No code is generated in source.

![image](https://user-images.githubusercontent.com/16779727/173230933-1317fb10-8352-4cdc-9e3f-992c69a5424b.png)

Seem like when I do comment in header.php 

`<?php`

`$GLOBALS['timberContext'] = Timber::get_context();`
`ob_start();`

this line : 
`$GLOBALS['timberContext'] = Timber::get_context();`

but then unfortunately, timber is not loading templates obviously, but content of Knowledgebase is displayed, but with no styling etc.

## What version of WordPress, PHP and Timber are you using?
PHP Version: 7.4.28
MySQL: 8.0.29
WordPress: 5.9.3
Timber: 1.19.1

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WP.ORG

**Comment by Levdbas** [comment]
3rd party and older versions reported. Should we close this as well?
