### ISSUE TITLE
Term `description` function removes first paragraph of description

### ISSUE THREAD

**Issue by jhhazelaar** [timber/timber#2588]
## Actual behavior

Expect to have paragraph in description. The function 'term_description' return description with all paragraphs, but de Term function description strips of the first paragrap here: https://github.com/timber/timber/blob/master/lib/Term.php#L369

## Expect behavior

Return description with paragraph.

## What version of WordPress, PHP and Timber are you using?
WordPress 6.0, PHP 8.0, Timber 1.19.2

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by jarednova** [comment]
@jhhazelaar , thanks for the report! Could you put together a PR along with some tests? Very bizarre that you're seeing that. There's a test covering that method:

https://github.com/timber/timber/blob/master/lib/Term.php#L369-L376

```php
		function testTermDescription() {
			$desc = 'An honest football team';
			$term_id = $this->factory->term->create(array('name' => 'New England Patriots', 'description' => $desc));
			$term = new TimberTerm($term_id, 'post_tag');
			$this->assertEquals($desc, $term->description());
		}
```

I'm wondering if there's something going on with certain characters or tags in the text you have in that description field?

**Comment by Levdbas** [comment]
Stale issue, closing.
