### ISSUE TITLE
Implement "toavif" filter to convert images to .avif format

### ISSUE THREAD

**Issue by radex02** [timber/timber#2596]
## Is your feature request related to a problem? Please describe.
The ``avif`` image format has better compression than even the ``webp`` format and is now supported by [70% of browsers](https://caniuse.com/avif). More importantly, it can now be generated by GD starting from ``PHP 8.1`` using ``imageavif``. I have a lot of image heavy websites and this format could most likely reduce their bandwidth usage by ~25%.

## Describe the solution you’d like
I'd like a filter just like the ``tojpeg`` or ``towebp`` filter but for ``avif``.

**Comment by jarednova** [comment]
Thanks @radex02 ! We're actually in the midst of talking about the best way to handle image transformation in the repos so we can be more flexible about what support is/isn't included — I know @nlemoine has some thoughts

**Comment by Levdbas** [comment]
Closing this in favor of #2866
