### ISSUE TITLE
Timer::render() is not working with absolute paths on windows

### ISSUE THREAD

**Issue by iamjonasmarlo** [timber/timber#2603]
I would like to render a template with an absolute path on my windows machine (working with Local).

```
$path = "C:\Users\jonas\Local Sites\mywebsite\app\public/wp-content/themes/my-theme/components/example/index.twig";

$context = Timber::context();
Timber::render($template, $context);
```

On Mac it's working fine! If I'm using a relative path like "/components/example/index.twig" it's working fine as well.

## Expected behavior

The template should be rendered.

## Actual behavior

The Timber::render function returns false, because the Twig\FilesystemLoader->exists() function return false. The functions is called in the Timber\Loader class. So the template isn't rendered.

## What version of WordPress, PHP and Timber are you using?
WordPress: 6
PHP: 7.4.1
Working with nginx in Local.

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Via Composer.

**Comment by jarednova** [comment]
Thank you @iamjonasmarlo! I have to confess that I don't personally use Windows for development. It's likely an issue with the `\` vs `/` directory syntax. Are you able to investigate and propose a PR?

**Comment by joworeiter** [comment]
@iamjonasmarlo I think the Space in the path leads to troubles. 
Could you try to rename your dir to something like "Local_Sites" and try again?

**Comment by Levdbas** [comment]
Not sure why you would want to go for an absolute path like that. There are more elegant ways to traverse that are independent of the platform you are using.
