### ISSUE TITLE
add page slug to transient name

### ISSUE THREAD

**Issue by Colir** [timber/timber#2604]
## Is your feature request related to a problem? Please describe.
I would like to be able to delete a specific page's cache (transient). 
Actually the transient name of a timber cached page is 
"timberloader_[HASH KEY BASE ON DATA]". 

It can be really to hard to retrieve the correct hash key.

## Describe the solution you’d like
Add the post slug to the transient name like "timberloader__[post_slug]_[HASH KEY BASE ON DATA]"

## Describe alternatives you’ve considered
It could be done by adding a filter to the CONSTANT "CACHEGROUP" ( like adding a filter in the set_cache method when generating the var "trans_key")

Thank you !

**Comment by Colir** [comment]
Hello,
after re-dive in this difficulty to find the correct transient loader, i think the best solution would be to add a filter on

`$trans_key = substr($group.'_'.$key, 0, self::TRANS_KEY_LEN);`

In this way, we could be able to add any variable we want in the cache key (slug, ID, wathever...)

Thank you

**Comment by gchtr** [comment]
Small note about how this was fixed: With the next release of Timber, you’ll be able to use the `timber/cache/transient_key` filter to update the transient key.

```php
add_filter( 'timber/cache/transient_key', function( $trans_key, $key, $group, $cache_mode ) {
    return $trans_key . '_my_suffix';
}, 10, 4 );
```

This way, you can use a different transient key when certain conditions are met. This should make it possible to delete the transient for a specific page.
