### ISSUE TITLE
Caption on thumbnails is empty (2.x)

### ISSUE THREAD

**Issue by xavivars** [timber/timber#2607]
When trying to use a post's thumbnail caption is empty. The problem seems to be from Attachment class, that never sets a value for it.

## Expected behavior
Timber displays the caption

## Actual behavior
Caption is empty. It seems to never get defined in https://github.com/timber/timber/blob/2.x/src/Attachment.php

## Steps to reproduce behavior
On `single.twig` for a post with a featured image that has a caption, access ` {{ post.thumbnail.caption }}` and will be null.

## What version of WordPress, PHP and Timber are you using?
WordPress 6.1, PHP 7.4, Timber 2 alpha 6

## Workaround

`{{ post.thumbnail.post_excerpt }}` displays the right caption

**Comment by gchtr** [comment]
Resolved by #2612. This will be in the next release.
