### ISSUE TITLE
Create TimberView object to handle view rendering

### ISSUE THREAD

**Issue by jarednova** [timber/timber#261]
This is from the discussion in #248 and the #259 epic. Create a new object to better organize how templates are rendered and locations are chosen. This will deprecate (but not eliminate) the current static-based approach to data and rendering.
### Acceptance
- [ ] Existing functionality for `Timber::render` and `Timber::compile` still work
- [ ] Themes and multiple plugins can set different rules for the location of twig files
- [ ] New methods are documented in wiki
- [ ] Method for populating context for template is documented
- [ ] Functionality for caching is preserved, new syntax/method is documented
- [ ] Review API with 2 collaborators for sanity-check
- [ ] Reference of files within twig (extension, inclusion) is considered
- [ ] Reference of files within twig (extension, inclusion) is documented

... this work is currently in: https://github.com/jarednova/timber/tree/timber-view. Here's a sample of the API that someone might use in `single.php`:
### Basic theme example with standard locations

``` php
$view = new TimberView();
$view->context['post'] = new TimberPost();
$view->cache(600);
$view->render('single.twig');
```
### Plugin example with custom locations

``` php
$view = new TimberView('my-plugin-context');
$view->cache(600);
$view->context['days'] = my_plugin_get_days_or_something();
$templates = array(
    get_template_directory(),
    get_template_directory().'/templates',
    __DIR__.'/templates'
);
return $view->compile('calendar-overview.twig', $templates);
```

**Comment by roopemerikukka** [comment]
Hi,

Is there any plans to complete this feature? I'm trying to use Timber in a plugin and would like it to work with both themes that use Timber and themes that don't. Is there any current solutions how I can bypass the fact that I cannot change the locations after first initialisation? Would it be safe to use absolute uris in the plugin and not to set the locations at all so the theme can do that if wanted?

**Comment by palmiak** [comment]
@jarednova - are there any plans about this?

**Comment by palmiak** [comment]
I wanted to use Timber in a plugin and investigated how all this works. What surprised me is the fact that we almost have the working functionalaty to use separate templates even for each plugin / theme.

There is something like `$paths = apply_filters('timber/loader/paths', $paths);` with this we can do something like this:
```php
function filter_paths() {
    return [__DIR__.'/front'];
}

add_filter('timber/loader/paths', 'filter_paths');
Timber::render('admin.twig', $context);
remove_filter('timber/loader/paths', 'filter_paths');
```

I know it's not pretty, but it's a quite well functioning workaround to problem with `$locations` which was mentioned for years.

I think it solves all the problems mentioned in #248. Or maybe it's too late and I don't see some obvious problem :)

**Comment by jarednova** [comment]
I'm closing all 2+ year old issues. If someone wants to pick this up, let's make it a fresh issue
