### ISSUE TITLE
Source code contains to be resolved issues "todos"

### ISSUE THREAD

**Issue by szepeviktor** [timber/timber#2626]
Issue `grep -rFni todo src/`

## Expected behavior

No output.

## Actual behavior

41 todos

## What version of Timber are you using?

2.x

**Comment by gchtr** [comment]
To resolve this, I would propose to go through the todos and:

- Create GitHub issues with the `2.0` label for issues we need to resolve before the 2.0 release. For issues that are easy to resolve right away, create a pull request.
- Create GitHub issues with the `2.x Future` label for the todos we can in a future release.
- Leave the todos that are about inline documentation as they are.

If someone wants to help with this, assign yourself to this issue or let us know before you start.

**Comment by gchtr** [comment]
Resolved in #2757.
