### ISSUE TITLE
Allow pagination object to be generated using $prefs only

### ISSUE THREAD

**Issue by phasdev** [timber/timber#2635]
## Is your feature request related to a problem? Please describe.
I'd like to use [Timber\Pagination::get_pagination( $prefs = array() )](https://github.com/timber/timber/blob/8d9bff23d2677652469badb75dcb607449a18204/lib/Pagination.php#L23) to generate a pagination object using `$prefs` only. Since `$prefs` [overrides](https://github.com/timber/timber/blob/8d9bff23d2677652469badb75dcb607449a18204/lib/Pagination.php#L68) `$args` derived from `$wp_query`, this mostly works right now. However the "prev" link is not generated because it refers to the `$paged` query variable when [checking if the prev link should be removed](https://github.com/timber/timber/blob/8d9bff23d2677652469badb75dcb607449a18204/lib/Pagination.php#L93).

## Describe the solution you’d like
If you replace `$paged` with `$this->current` when [checking if the prev link should be removed](https://github.com/timber/timber/blob/8d9bff23d2677652469badb75dcb607449a18204/lib/Pagination.php#L93), then I can set `$current` in the `$prefs` array and the "prev" link will be generated as expected.

## Describe alternatives you’ve considered
Calling `set_query_var('paged', $current)` before calling [Timber\Pagination::get_pagination()](https://github.com/timber/timber/blob/8d9bff23d2677652469badb75dcb607449a18204/lib/Pagination.php#L23) will work around this issue.

## Additional context
I'm rendering search results returned by a [SearchWP](https://searchwp.com/) supplemental search engine, which doesn't use `$wp_query`. If I can build a Timber pagination object from a SearchWP response, then I can use the same search results template for both native WP and SearchWP search engines.

Thanks for your hard work. Timber is awesome! :slightly_smiling_face:

**Comment by Levdbas** [comment]
Hi @phasdev , sorry for the late response. It seems that you have a good understanding of what goes wrong here. Are you open to investigate the problem and maybe submit a PR as well?

**Comment by Levdbas** [comment]
Closing this as a stale issue

**Comment by ghost** [comment]
Hi @Levdbas, can you please re-open this issue so I can link it to a PR?
