### ISSUE TITLE
ACF Relationship field + WPML return a string instead of array in secondary language when only one post is selected.

### ISSUE THREAD

**Issue by langhenet** [timber/timber#2636]
## Expected behavior
Return an array instead of a string for relationship fields with only one post connected (in secondary language).

## Actual behavior
On the secondary language, when only one post is selected in the relationship field, timber should return an array, instead it returns a string.

## Steps to reproduce behavior
- Install WPML +ACF
- Create a `post_page` relationship field in ACF between posts an pages
- create a post in primary language and connect it with a page (only one)
- create a translation

if you `var_dump($this->post_page);` in secondary language it returns a string, but if you `var_dump(get_post_meta($this->ID, 'post_page');` it returns an array;

## What version of WordPress, PHP and Timber are you using?
Wordpress 6.0.1
PHP 7.4
Timber 1.20

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by Levdbas** [comment]
Since [accessing post meta directly in v2](https://timber.github.io/docs/v2/upgrade-guides/2.0/#deprecating-direct-access-to-meta-values) will be deprecated I will close this issue.
