### ISSUE TITLE
post.content in loop shows the latest post's content on all instances

### ISSUE THREAD

**Issue by aaronrobb** [timber/timber#2642]
## Expected behavior

Using ```post.content``` within a loop should give that specific post's content. 

## Actual behavior

The latest post's content shows up in all posts within the loop. 
Using a `{{ dump(post) }}` the `post_content` shows the same content for each post in in the loop page.
Other data - post.link, post.title, are all correct.

## Steps to reproduce behavior

Using a controller to generate the posts:

```
class PressReleaseArchiveController extends BaseController
{

    /**
     * {@inheritDoc}
     */
    public function setContext()
    {
        $this->posts       = Post::all();

        $this->pagination  = Timber::get_pagination(0);

        $this->page_header = [
            'title'   => get_the_archive_title(),
            'content' => get_the_archive_description()
        ];
    }

}

return new PressReleaseArchiveController;
```

Then 
```
{% block content_main %}

		{% block page_builder_section_content %}

			{# Loop through the Posts #}
			{% for post in posts %}
				{% include 'components/content/card/card--press-release.twig' %}
			{% endfor %}

		{% endblock %}
	{% endembed %}

	{% include 'components/site-elements/pagination/pagination.twig' %}

{% endblock %}
```

Then the press release card:
```
{% embed 'components/content/card/card.twig' with {
    'link'           : post.link,,
} %}

	{% block card_content %}
		{{ dump(post) }}
		<div class="content__wrapper">
			<h4 class="card__title">
				{% if link %}
					<a href="{{ link }}" target="{{ (new_tab is same as(true) ? '_blank' : target|default('_self')) }}">{{ post.title }}</a>
				{% else %}
					{{ post.title }}
				{% endif %}
			</h4>

			<p class="card__description release-content">{{ post.content|truncate(50) }}</p>
	</div>
{% endblock %}

{% endembed %}
```

All other parts work ok - post.link shows the correct link, post.title is the correct title.
Just the post.content (and post.preview if there is no excerpt on the post) show the wrong content.

## What version of WordPress, PHP and Timber are you using?
 WordPress 5.9.3, PHP 7.4.27, Timber 1.19.1

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by Levdbas** [comment]
Since a lot of work was done under the hood in https://github.com/timber/timber/pull/1778 to make this work, I don't see this being backported to 1.x. You could try running Timber 2 beta 1 and give that a spin?

**Comment by Levdbas** [comment]
Stale issue, closing.
