### ISSUE TITLE
PHP 8 readiness

### ISSUE THREAD

**Issue by columbian-chris** [timber/timber#2651]
With the PHP 7.4 EOL coming up quick on November 28th, what actions should I be taking to make sure my Timber-dependent theme/site continues to function?

I found [this comment](https://github.com/timber/timber/issues/2492#issuecomment-1126077967) that states that Timber 1.x won't be officially supported for PHP 8, and so logically I could just migrate to 2.x, but then I also ran across [this comment](https://wordpress.org/support/topic/php8-error-deprecated-required-parameter-lineno-follows-optional-parameter/#post-15933472) of doubts that 2.x doubts that 2.x is going to be ready before the PHP 7.4 EOL.  Our web host is trying to push upgrading to PHP 8, and in compatibility testing, Timber seems to be potentially poses a big hindrance to that goal.  Is there by any chance a target goal for the 2.x release date possibly coming soon?

**Comment by nlemoine** [comment]
Hi @columbian-chris, 

PHP 7.4 EOL doesn't mean you have to switch to PHP 8 November 29th 😉 

FYI, [WordPress isn't still officialy supporting PHP 8 (currently beta)](https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/) and it's running nearly half the web. Don't worry too much about this. 

However, Timber 1.x [is going to support PHP 8.0/8.1](https://github.com/timber/timber/actions/runs/3213635869) and it will probably be released in a few days.

Timber 2.x is on its way but it's taking time we do not always have.

**Comment by timnolte** [comment]
I know this is a closed issue but I didn't want to just open a new one. I'm wondering about any sort of ETA on the Timber 2.0 rollout and PHP 8.1 compatibility. I looked at the project and there doesn't seem to be too much that is outstanding and a blocker to a new release. We are looking to start upgrading sites to PHP 8.1 soon but this is sort of a blocker for us. If we can put some people on assisting with the next release we might be able to help. Thanks!
