### ISSUE TITLE
Preview in new page doesn't display Timber code.

### ISSUE THREAD

**Issue by maldorito** [timber/timber#2680]
## Expected behavior
Working WordPress page preview that includes twig template.

## Actual behavior
In preview of WordPress page in new tab, the code inside of the twig template does not render. Only upon a second click of preview in new tab button, does the Timber code render. 

## Steps to reproduce behavior
1. Create a page based on the landing page template seen here:
```
<?php
/**
 * Template Name: Landing Page Template
 */

$post = new TimberPost();
$data = Timber::get_context();
$data['post'] = $post;

$data['small_business'] = false;

if( have_rows('modules') ):
    while ( have_rows('modules') ) : the_row();
        if( get_row_layout() == 'blog_article_cards' ):
            $catId = get_sub_field('blog_articles_category');
        endif;
    endwhile;
endif;

if(isset($catId)) {
    $args = array(
        'cat' => $catId,
        'posts_per_page' => 2,
    );
    $data['package_cards'] = Timber::get_posts( $args );
}

Timber::render('landing-page-template.twig', $data);
```

2. Add a module to the page and add dummy data to the module fields.
3. Click update in the page editor and then click Preview, then click Preview in new tab.
4. After the page loads, the body area where the Timber code should be doesn't display or even load in.

## What version of WordPress, PHP and Timber are you using?
WordPress 5.8.6, PHP 7.3.5, Timber 1.20.0 (Also present on Timber 1.22.0)

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by gchtr** [comment]
Hey @maldorito, thanks for filling out a detailed issue!

It looks like you’re using ACF for most of your post content. And it could be that your issue is not related to Timber at all, but to how WordPress saves post meta (or doesn’t) in post revisions. Please check out this WordPress core ticket: https://core.trac.wordpress.org/ticket/20299.
