### ISSUE TITLE
Add User::profile_link() method

### ISSUE THREAD

**Issue by gchtr** [timber/timber#2682]
As discussed in https://github.com/timber/timber/pull/2676, we could add a `User::profile_link()` method that get’s the link the profile admin page if a user is logged in. This is more clear than `User::edit_link()`, where you might assume that you get URL to edit other users.

- [ ] Add `User::profile_link()` method
- [ ] Add tests.

**Comment by Levdbas** [comment]
Hi @gchtr ,

I would like to take a shot at this. How does this sound?

- Add a new is_current_user() method that matched the User object id with get_current_user_id()
- Add new profile_link() method that returns get_edit_profile_url() when is_current_user() is true

**Comment by gchtr** [comment]
@Levdbas Sounds good! The only thing I would change is to name the method `is_current()` instead of `is_current_user()`. I’ll assign this to you, then 😊.
