### ISSUE TITLE
error on array checking

### ISSUE THREAD

**Issue by aclase** [timber/timber#2685]
I have  check for upsell products in template and get error:

      Got error ‘PHP message: PHP Warning: Attempt to read property “found_posts” on array in …/timber-library/lib/QueryIterator.php on line 76’

Causing part:      
      {% if post.upsell_products|length %}
      ...
      
      
How can process arrays correctly?

**Comment by gchtr** [comment]
What’s `upsell_products`? Where do you define it? Is it a function or a property on `post`? Can you show some code for this?

**Comment by aclase** [comment]
It's added on product page, here more from controller:

`    public function upsell_products()
    {
        if (isset($this->upsell_products)) {
            return $this->upsell_products;
        }

        $cid = $this->generate_cid('upsell');
        $product = $this->product;

        $this->upsell_products = TimberHelper::transient($cid, function () use ($product) {
            return (new Timber\PostQuery($product->get_upsell_ids()))->get_posts();
        }, $this->cache_duration);

        return $this->upsell_products;
    }
`

**Comment by aclase** [comment]
My mistake, seems that 
`            return (new Timber\PostQuery(**array(**$product->get_upsell_ids() **)** ))->get_posts();`
fix the problem

**Comment by Levdbas** [comment]
More of a support question so I am going to close this.
