### ISSUE TITLE
Timber\Menu() not working

### ISSUE THREAD

**Issue by stuartandrewlees** [timber/timber#2688]
Appears to be an issue with new Timber\Menu(). Menus can be added using WP using register_nav_menus.

Works:

register_nav_menus( [
'menu_primary' => _( 'Primary Navigation' ),
'menu_footer' => _( 'Footer Navigation' ),
] );

Doesn't work:

/** Timber Context  (functions.php) */
public function add_to_context( $context ) {
$context['menu_primary']  = new Timber\Menu('Primary Navigation');
$context['menu_footer'] = new Timber\Menu('Footer Navigation');
$context['site']  = $this;
return $context;
}

In Template: (returns nothing)

{% if menu_footer.get_items %}
    <nav id="nav-main">
        {% include "menu.twig" with { 'items': menu_footer.get_items } %}
    </nav>
{% endif %}

## Expected behavior
Should create a display location which I  set and then can use in twig templates. 

## Actual behavior
<img width="677" alt="Screenshot 2022-12-06 at 14 27 42" src="https://user-images.githubusercontent.com/86251738/205938552-e3413222-e462-4e3d-a43b-9febf41fb625.png">

## Steps to reproduce behavior
Fresh WP Install, Install Timber, Create a Menu (in functions.php - add_to_context), View Appearence, Menus no display locations displayed.

## What version of WordPress, PHP and Timber are you using?
WordPress 6.1.1, PHP 8.0.0, Timber 1.22.1, Local by Flywheel

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Downloaded via Plugins section in Wordpress

**Comment by EpicKau** [comment]
You need to register the menu before you can use it in timber....
You use Timber\Menu to make a standard WordPress menu available to the Twig template as an object you can loop through.

more info:  https://timber.github.io/docs/guides/menus/

**Comment by stuartandrewlees** [comment]
Hi [EpicKau](https://github.com/EpicKau), I think you've misunderstood. My menus have been registered in the 'add_to_context' function above when i initialise the timber class in functions.php. The above 'register_nav_menus' was to denote it works via Wordpress functions. From what i've been reading WordPress 6.0+ has changed the way it references the menus, and they are inherently now inaccessible to timber.

**Comment by EpicKau** [comment]
@stuartandrewlees I think i miss something but to be clear, you need both. First you need to setup the menu with 'register_nav_menus' and then you can use it in timber.


`
register_nav_menus( [
'menu_primary' => _( 'Primary Navigation' ),
'menu_footer' => _( 'Footer Navigation' ),
]);

public function add_to_context( $context ) {
$context['menu_primary'] = new Timber\Menu('menu_primary');
$context['menu_footer'] = new Timber\Menu('menu_footer');

return $context;
} 

{{dump(menu_primary)}}

`

**Comment by stuartandrewlees** [comment]
Hey @EpicKau, you are correct. As it turns out the issue was a typo I'd completely missed. :P. It's just been one of those days. Brain on 40%, stroll on Christmas. Thank you for taking the time to help though. Very much appreciated.
