### ISSUE TITLE
Pagination with custom query doesn't seem to work

### ISSUE THREAD

**Issue by YourMark** [timber/timber#2689]
## Expected behavior

I want to display pagination under a list of posts on a custom page template. I'd expect to see the pagination based on the values in `$context['posts']`

## Actual behavior

I don't get any pagination at all. The `pagination.pages` var is empty.

## Steps to reproduce behavior

I used the following code, based on https://timber.github.io/docs/v2/guides/pagination/#what-if-im-not-using-the-default-query?
```
use Timber\Timber;
use Timber\Pagination;
if (!isset($paged) || !$paged) {
	$paged = 1;
}
$context = Timber::context();

$context['posts'] = Timber::get_posts( [
	'post_type' => 'post',
	'paged' => $paged,
] );

// Set pagination to show 2 pages before and 2 after the current selected page.
$context['pagination'] = Pagination::get_pagination( [
	'mid_size' => 2,
	'end_size' => 1,
	'show_all' => false,
] );

echo Timber::compile( [ 'partials/post-list/list.twig' ], $context );
```

It looks like the `$wp_query` var is not passed to the Pagination class which caused it to use the `$wp_query` of the current page, which (logically) has no pagination.

## What version of WordPress, PHP and Timber are you using?

WordPress: 6.1.1
PHP: 7.4.21
TImber: 2.0.0-beta.1

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Timber is installed via composer.

**Comment by mrfsrf** [comment]
Try this:

```php
$pagination_args = array(
    'post_type' => 'post',
    'paged' => $paged,
);

$blog_posts = Timber::get_posts(array(
    'post_type' => 'post',
    'paged' => $paged,
));

$context['pagination'] = new Timber\Pagination($pagination_args, $blog_posts);
```

**Comment by YourMark** [comment]
Thanks for answering this. Unfortunately `convert_wp_object`, doesn't convert `WP_Query`, only `WP_Post`, but $blog_posts in this case a `WP_Query`.

It looks like this works:

`$context['posts'] = new \Timber\PostArrayObject( $blog_posts->posts );`

And this line seems obsolete:
`$context['pagination'] = get_object_vars($obj_pagination);`

I am wondering now however if this is the intended way or that it's maybe a bit of a workaround? Since I'd more or less expect a custom pagination to work with the Timber functionality such as `get_posts()`.

**Comment by mrfsrf** [comment]
I'm not sure that I understand what you wan to achieve. As far as I understand it, you want to include blog posts in custom post type template?
If so, see my UPDATE part from above example. You have to make a new query to retrieve blog posts and you probably need to introduce Router otherwise the link for page 2 for blog posts slider will be `yourpage.com/custom-post-type-slug/page/2`

Note: For Timber v.2.x  you need to install router with composer

```php
Routes::map('custom-post-type-slug/:page/:number?', 'routes_cb');
function routes_cb($params) {
  Routes::load('page-customtype.php', $params, null, 200);
}

/* page-customtype.php */
if (!isset($paged) || !$paged) $paged = 1;
global $params;

$blog_posts = new Timber\PostQuery(array( // $context['blog_posts']
  'post_type' => 'post',
  'paged'     => isset($params['number']) ?? $paged,
));

/* the rest as normal... */
```
But as I said, not sure what you try to achieve.

**Comment by Levdbas** [comment]
Closing as stale
