### ISSUE TITLE
Timber::get_post do not work after updating WP from 5.8.5 to 6.11

### ISSUE THREAD

**Issue by taurus-git** [timber/timber#2693]
After updating WP from 5.8.5 to 6.1.1
Timber::get_post and Timber::get_posts return null on posts, categories, and tags.

## Expected behavior
return non empty WP_Query with actual post / taxonomy

## Actual behavior
global $wp_query; also returns null
```
object(WP_Query)[7856]
  public 'query' => null
  ...
```
get_the_ID() return false or 0

## Steps to reproduce behavior
just update WP from 5.8.5 to 6.1.1

## What version of WordPress, PHP, and Timber are you using?
Example: WordPress 6.1.1, PHP 7.4, Timber 1.3.4

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Timber installed as a lib inside the project

**Comment by taurus-git** [comment]
single.php
$template = 'single.twig';

$context         = \Timber\Timber::get_context();
$context['post'] = \Timber\Timber::get_post( false, '\Entities\Story_Post' ); //here returns false

\Timber\Timber::render( $template, $context );

**Comment by gchtr** [comment]
Is there a reason why you’re still on Timber 1.3.4? The most current stable version is actually 1.22.1. I suggest you first update Timber and see if that solves the issue.

**Comment by taurus-git** [comment]
Thanks a lot I will try.
Any ideas on how to update the theme inside my site?) 
<img width="323" alt="image" src="https://user-images.githubusercontent.com/31800312/209986166-5c3cd3f8-b1b6-4f9e-b154-92422b9c92ca.png">


> Is there a reason why you’re still on Timber 1.3.4? The most current stable version is actually 1.22.1. I suggest you first update Timber and see if that solves the issue.

**Comment by rmens** [comment]
Oof. Your theme seems to ship a lot of dependencies that probably don't get updated. You should ask your theme vendor to update all the dependencies first. 

It that doesn't work, check out what's in the 'lib' and 'vendor' folders and see if the same files are in the latest release of Timber.

**Comment by Levdbas** [comment]
Seems to be stale and is based on a very old issue. Can be closed in my opinion.
