### ISSUE TITLE
post.meta() returns NULL when previewing changes

### ISSUE THREAD

**Issue by bwaltz** [timber/timber#2694]
I am experiencing an issue where changes in ACF fields, which displays when a page is assigned to a particular taxonomy, are returning NULL when previewing.

The issue is only produced when you click the "preview" button after making changes. If you go into the backend of the published post and click "preview" without making any changes, everything works as expected.

![Screen Shot 2023-01-04 at 2 13 46 PM](https://user-images.githubusercontent.com/2333967/210632861-aae696a5-6fb8-4a54-b5f9-a10a2f437111.png)

![Screen Shot 2023-01-04 at 2 13 56 PM](https://user-images.githubusercontent.com/2333967/210632899-242395ee-3f07-486b-b6f6-09c611ed99ef.png)

I can provide a stage server for someone to look at, if need be.

## Expected behavior
Changes made to ACF fields to be displayed when previewing.

## Actual behavior
All post.meta() calls return NULL, even if only one field value was changed.

## Steps to reproduce behavior

1. Go to the backend of a page assigned to the "Office" category
2. Scroll down to the bottom and change a field value in the "Office Detail" section
3. Click "Preview"
4. Notice that everything is blank where the field values should be displaying. If you do `{{ dump(post.meta('address') }}`, for example, you'll see NULL.

## What version of WordPress, PHP and Timber are you using?
WordPress 6.1.1, PHP 8.0.3, Timber 1.22.1 and ACF 6.0.3

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by gchtr** [comment]
Related: #2680.

**Comment by Levdbas** [comment]
As reported [here](https://support.advancedcustomfields.com/forums/topic/custom-fields-on-post-preview/) this is an ACF issue. Closing it here.

**Comment by xavivars** [comment]
@Levdbas , I know you said it's an issue with ACF (and/or how WordPress stores or doesn't store post meta for revisions).

But on `\Timber\Post::meta` (or, actually, on `CoreEntity::fetch_meta` there is a filter that, according to docs, it says it's used by the ACF integration:

https://github.com/timber/timber/blob/2.x/src/CoreEntity.php#L207

And then, ACF Integration doesn't use it, at all:

https://github.com/timber/timber/blob/2.x/src/Integration/AcfIntegration.php#L26-L36

Is there any chance there's a missing filter setup on the ACF integration?

**Comment by bwaltz** [comment]
Does this mean I should use `get_field` instead? TBH even if I do `{{ dump(fn('get_field','address', post.ID, 'true')) }}` in my twig file it still gives me the value of the last save and not the changes I'm trying to preview.

**Comment by gchtr** [comment]
With the upcoming WordPress version 6.4, [post meta revisions](https://make.wordpress.org/core/2023/10/24/framework-for-storing-revisions-of-post-meta-in-6-4/) will be introduced. It seems to me that this bug will be fixed, if you register your meta fields for revisions:

> Meta revisions are also stored for autosaves and when previewing posts, fixing a long standing bug ([#20299](https://core.trac.wordpress.org/ticket/20299)) that caused live post meta to be overwritten when post meta was previewed. This is because using `update_post_meta` to save meta to a revision actually resulted in it being saved to the parent post. With this change, developers can now opt in to meta revisions and core will correctly attach the meta data to the revision. Meta that has revisions is also restored when restoring an autosave or revision.

I assume that ACF will fix this on their end.
