### ISSUE TITLE
Using Timber::get_term($id) for custom taxonomy results in warnings

### ISSUE THREAD

**Issue by mgussekloo** [timber/timber#2697]
## Expected behavior
Passing a taxonomy name should be optional in Timber::get_term, even for custom 

## Actual behavior
Without passing a taxonomy name, in Timber.php on line 199 (function get_term), the default value for $taxonomy is "post_tag".
This means querying a custom taxonomy results in warnings, because the term id and taxonomy don't match.

`
[09-Jan-2023 19:15:39 UTC] PHP Warning:  Attempt to read property "term_id" on null in /Users/martijngussekloo/Development/x/wp-content/plugins/timber-library/lib/TermGetter.php on line 16
[09-Jan-2023 19:15:39 UTC] PHP Warning:  Attempt to read property "taxonomy" on null in /Users/martijngussekloo/Development/x/wp-content/plugins/timber-library/lib/TermGetter.php on line 16
`

## Proposed solution
Make null the default for $taxonomy. So the function (line 199 - 201) in Timber.php would read:

'php
public static function get_term( $term, $taxonomy = null, $TermClass = 'Timber\Term' ) {
		return TermGetter::get_term($term, $taxonomy, $TermClass);
	}
'

**Comment by Levdbas** [comment]
Hi @mgussekloo,

Thank you for reporting this.

The behavior of Timber::get_term [has changed](https://timber.github.io/docs/v2/upgrade-guides/2.0/#timberget_term) in the upcoming 2.0 version of Timber. I invite you to to test this upcoming version and see if this solves your problem.

I think we are not going to change this anymore in the 1.x branch, so I will close this issue.
