### ISSUE TITLE
Method `Term::link()` gives `Term` instead of `WP_Term` to `get_term_link()`

### ISSUE THREAD

**Issue by mcaskill** [timber/timber#2699]
## Expected behavior

A hook on [`pre_term_link`](https://developer.wordpress.org/reference/hooks/pre_term_link/) or [`term_link`](https://developer.wordpress.org/reference/hooks/term_link/) expects to receive [`WP_Term`](https://developer.wordpress.org/reference/classes/wp_term/).

## Actual behavior

[`Term::link()`](https://github.com/timber/timber/blob/2.0.0-beta.1/src/Term.php#L325) passes itself instead of its related `WP_Term` object to [`get_term_link()`](https://developer.wordpress.org/reference/functions/get_term_link/).

```php
$link = get_term_link($this);
```

If a hook is type-hinted to `WP_Term`, PHP will throw a `TypeError`:

```
PHP Fatal error:  Uncaught TypeError: App\Models\Taxonomies\Category::filter_term_link(): Argument #2 ($term) must be of type WP_Term, Timber\Term given, called in web/wp/...
Stack trace:
#0 web/wp/wp-includes/class-wp-hook.php(308): App\Models\Taxonomies\Category->filter_term_link('https://examp...', Object(Timber\Term), 'category')
#1 web/wp/wp-includes/plugin.php(205): WP_Hook->apply_filters('https://examp...', Array)
#2 web/wp/wp-includes/taxonomy.php(4652): apply_filters('term_link', 'https://examp...', Object(Timber\Term), 'category')
#3 vendor/timber/timber/src/Term.php(325): get_term_link(Object(Timber\Term))
#4 vendor/twig/twig/src/Extension/CoreExtension.php(1635): Timber\Term->link()
```

## Steps to reproduce behavior

```php
add_filter( 'term_link', function ( string $link, WP_Term $term, string $taxonomy ) : string {
    // do something
    return $link;
}, 10, 3 );
```

## What version of WordPress, PHP and Timber are you using?

* PHP 5.6+
* WordPress 6.1+
* Timber 1+ or 2+

## Proposed solution

As far as I can see, there's three ways to resolve this:

1. Remove the type or use a less specific type:

    ```php
    add_filter( 'term_link', function ( string $link, object $term, string $taxonomy ) : string {
        // do something
        return $link;
    }, 10, 3 );
    ```

2. If in PHP 8+, use a union type:

    ```php
    add_filter( 'term_link', function ( string $link, WP_Term|Timber\Term $term, string $taxonomy ) : string {
        // do something
        return $link;
    }, 10, 3 );
    ```

    This is not practical if this filter is, for example, in a plugin that is not aware of Timber.

3. In `Term::link()`, pass `WP_Term` instead of `Timber\Term`:

    ```php
    $link = get_term_link($this->wp_object);
    ```

    I don't know if this has side effects. The `Term::link()` method has been [passing itself since 2013](https://github.com/timber/timber/commit/bda33c0796076bb6267aa30d288d6fc9af4afa07).

**Comment by nlemoine** [comment]
Thanks for pointing that out! 🙈

This is not the only filter where Timber uses a Timber object instead of the WP object:
https://github.com/timber/timber/blob/master/lib/MenuItem.php#L276
https://github.com/timber/timber/blob/2.x/src/MenuItem.php#L347

This behavior needs to be fixed in Timber 2.x but fixing this in Timber 1.x will introduce a breaking change (although I don't think people uses the object as a Timber object here).

The third solution is the way to go. Since WordPress isn't fully reliable when it comes to types, I usually don't type filters callbacks.

Would be willing to submit a PR for this?

**Comment by mcaskill** [comment]
> […] not the only filter where Timber uses a Timber object instead of the WP object

Indeed. I did a very quick and light search for any other possible occurrences but couldn't find any.

> […] needs to be fixed in Timber 2.x but fixing this in Timber 1.x […]

Yeah, I wouldn't bother with Timber v1 for this.

> Since WordPress isn't fully reliable when it comes to types, I usually don't type filters callbacks.

Absolutely. I relax or remove the type in those situations.

> Would be willing to submit a PR for this?

Yes. I will submit a patch today.
