### ISSUE TITLE
Page Preview Not Working if Using post->thumbnail() method

### ISSUE THREAD

**Issue by spelkey-ucd** [timber/timber#2702]
## Expected behavior
Native WP page preview functionality:

![image](https://user-images.githubusercontent.com/34284106/213732825-2e8393d8-399c-4fa0-b4df-ef7882613380.png)

## Actual behavior
Preview fails to load with:
```Fatal error: Uncaught Error: Attempt to assign property "post_content" on array in /usr/src/wordpress/vendor/timber/timber/lib/Timber.php:169```

## Steps to reproduce behavior
1. Upload a featured image to a post.
2. Make sure your php or twig template calls `post.thumbnail`
3. Make an edit to the page (do not click update)
4. Click the preview button

This bug also happens if any other post that your page queries with `timber::get_posts()` calls `thumbnail`.

## What version of WordPress, PHP and Timber are you using?
WordPress 6.1.1,  PHP 8.0.27, Timber 2.0.0-beta.1

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by gchtr** [comment]
This looks like a duplicate of https://github.com/timber/timber/issues/2582. It will be fixed by https://github.com/timber/timber/pull/2674.

**Comment by spelkey-ucd** [comment]
@gchtr yup, looks like it. Missed that issue, sorry.

**Comment by gchtr** [comment]
@spelkey-ucd No worries! Thanks to your detailed issue, this was easy to spot as a duplicate 😉. So thank you for taking the time to fill out the issue template.
