### ISSUE TITLE
[BUG] Fatal Error when previewing posts with PHP 8.1

### ISSUE THREAD

**Issue by andrewwfesenko** [timber/timber#2721]
### Expected Behavior

When trying to preview any post (post, page, custom post type) a page preview should be displayed.

### Actual behavior

A fatal error is being displayed:
`Fatal error: Uncaught Error: Cannot use object of type WP_Post as array in /var/www/html/vendor/timber/timber/src/Timber.php on line 194`

### Steps to reproduce behavior

1. Open/create any post
2. Click preview

### Notes

The introduction of changes from #2674 seems to have be the cause, because previewing worked fine prior to these changes:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/62845061/223484171-f8f7bcef-79b2-4c7b-bbb1-33fcdaaffd94.png"><img width="365" alt="image" src="https://user-images.githubusercontent.com/62845061/223484217-3ac62a23-7088-4be0-80f5-1cc375c86fca.png">

<img width="797" alt="image" src="https://user-images.githubusercontent.com/62845061/223483031-150d4d50-30de-40d3-809e-c837490e231f.png">
The example is from a freshly created empty post with no data assigned. But it also happens if the post is configured/ has images, etc.

Now the $data is being treated as an array, while in fact in it a WP_Post object.
<img width="778" alt="image" src="https://user-images.githubusercontent.com/62845061/223968666-164b390c-7795-4bf0-a0b9-613c73478ec6.png">

### What version of Timber are you using?

latest commit 2.x-dev 

### What version of WordPress are you using?

6.1.1

### What version of PHP are you using?

8.1

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by nlemoine** [comment]
Can you provide a full stack trace? I'm currently using latest Timber 2.x and have no issues with previews.

**Comment by andrewwfesenko** [comment]
<table class="xdebug-error xe-uncaught-exception" dir="ltr" border="1" cellspacing="0" cellpadding="1">
<tbody><tr><th align="left" bgcolor="#f57900" colspan="5"><span style="background-color: #cc0000; color: #fce94f; font-size: x-large;">( ! )</span> Fatal error: Uncaught Error: Cannot use object of type WP_Post as array in /var/www/html/vendor/timber/timber/src/Timber.php on line <i>194</i></th></tr>
<tr><th align="left" bgcolor="#f57900" colspan="5"><span style="background-color: #cc0000; color: #fce94f; font-size: x-large;">( ! )</span> Error: Cannot use object of type WP_Post as array in /var/www/html/vendor/timber/timber/src/Timber.php on line <i>194</i></th></tr>
<tr><th align="left" bgcolor="#e9b96e" colspan="5">Call Stack</th></tr>
<tr><th align="center" bgcolor="#eeeeec">#</th><th align="left" bgcolor="#eeeeec">Time</th><th align="left" bgcolor="#eeeeec">Memory</th><th align="left" bgcolor="#eeeeec">Function</th><th align="left" bgcolor="#eeeeec">Location</th></tr>
<tr><td bgcolor="#eeeeec" align="center">1</td><td bgcolor="#eeeeec" align="center">0.0007</td><td bgcolor="#eeeeec" align="right">422496</td><td bgcolor="#eeeeec">{main}(  )</td><td title="/var/www/html/web/index.php" bgcolor="#eeeeec">.../index.php<b>:</b>0</td></tr>
<tr><td bgcolor="#eeeeec" align="center">2</td><td bgcolor="#eeeeec" align="center">0.0020</td><td bgcolor="#eeeeec" align="right">422808</td><td bgcolor="#eeeeec">require( <font color="#00bb00">'/var/www/html/web/wp/wp-blog-header.php</font> )</td><td title="/var/www/html/web/index.php" bgcolor="#eeeeec">.../index.php<b>:</b>5</td></tr>
<tr><td bgcolor="#eeeeec" align="center">3</td><td bgcolor="#eeeeec" align="center">2.9493</td><td bgcolor="#eeeeec" align="right">12993264</td><td bgcolor="#eeeeec">require_once( <font color="#00bb00">'/var/www/html/web/wp/wp-includes/template-loader.php</font> )</td><td title="/var/www/html/web/wp/wp-blog-header.php" bgcolor="#eeeeec">.../wp-blog-header.php<b>:</b>19</td></tr>
<tr><td bgcolor="#eeeeec" align="center">4</td><td bgcolor="#eeeeec" align="center">2.9581</td><td bgcolor="#eeeeec" align="right">13006992</td><td bgcolor="#eeeeec">include( <font color="#00bb00">'/var/www/html/web/app/themes/saas-theme/page.php</font> )</td><td title="/var/www/html/web/wp/wp-includes/template-loader.php" bgcolor="#eeeeec">.../template-loader.php<b>:</b>106</td></tr>
<tr><td bgcolor="#eeeeec" align="center">5</td><td bgcolor="#eeeeec" align="center">2.9581</td><td bgcolor="#eeeeec" align="right">13006992</td><td bgcolor="#eeeeec">Timber\Timber::context( <span>$extra = </span>??? )</td><td title="/var/www/html/web/app/themes/saas-theme/page.php" bgcolor="#eeeeec">.../page.php<b>:</b>6</td></tr>
<tr><td bgcolor="#eeeeec" align="center">6</td><td bgcolor="#eeeeec" align="center">3.2871</td><td bgcolor="#eeeeec" align="right">13035976</td><td bgcolor="#eeeeec">Timber\Timber::get_post( <span>$query = </span>???, <span>$options = </span>??? )</td><td title="/var/www/html/vendor/timber/timber/src/Timber.php" bgcolor="#eeeeec">.../Timber.php<b>:</b>1174</td></tr>
<tr><td bgcolor="#eeeeec" align="center">7</td><td bgcolor="#eeeeec" align="center">3.2872</td><td bgcolor="#eeeeec" align="right">13036016</td><td bgcolor="#eeeeec">Timber\Factory\PostFactory-&gt;from( <span>$params = </span><span>class WP_Post { public $ID = 1000; public $post_author = '2'; public $post_date = '2023-03-09 10:33:42'; public $post_date_gmt = '2023-03-09 08:33:42'; public $post_content = ''; public $post_title = 'test page'; public $post_excerpt = ''; public $post_status = 'publish'; public $comment_status = 'closed'; public $ping_status = 'closed'; public $post_password = ''; public $post_name = 'test-page'; public $to_ping = ''; public $pinged = ''; public $post_modified = '2023-03-09 10:33:42'; public $post_modified_gmt = '2023-03-09 08:33:42'; public $post_content_filtered = ''; public $post_parent = 0; public $guid = 'http://localhost:8070/?page_id=1000'; public $menu_order = 0; public $post_type = 'page'; public $post_mime_type = ''; public $comment_count = '0'; public $filter = 'raw' }</span> )</td><td title="/var/www/html/vendor/timber/timber/src/Timber.php" bgcolor="#eeeeec">.../Timber.php<b>:</b>289</td></tr>
<tr><td bgcolor="#eeeeec" align="center">8</td><td bgcolor="#eeeeec" align="center">3.2872</td><td bgcolor="#eeeeec" align="right">13036016</td><td bgcolor="#eeeeec">Timber\Factory\PostFactory-&gt;from_post_object( <span>$obj = </span><span>class WP_Post { public $ID = 1000; public $post_author = '2'; public $post_date = '2023-03-09 10:33:42'; public $post_date_gmt = '2023-03-09 08:33:42'; public $post_content = ''; public $post_title = 'test page'; public $post_excerpt = ''; public $post_status = 'publish'; public $comment_status = 'closed'; public $ping_status = 'closed'; public $post_password = ''; public $post_name = 'test-page'; public $to_ping = ''; public $pinged = ''; public $post_modified = '2023-03-09 10:33:42'; public $post_modified_gmt = '2023-03-09 08:33:42'; public $post_content_filtered = ''; public $post_parent = 0; public $guid = 'http://localhost:8070/?page_id=1000'; public $menu_order = 0; public $post_type = 'page'; public $post_mime_type = ''; public $comment_count = '0'; public $filter = 'raw' }</span> )</td><td title="/var/www/html/vendor/timber/timber/src/Factory/PostFactory.php" bgcolor="#eeeeec">.../PostFactory.php<b>:</b>33</td></tr>
<tr><td bgcolor="#eeeeec" align="center">9</td><td bgcolor="#eeeeec" align="center">3.2872</td><td bgcolor="#eeeeec" align="right">13036016</td><td bgcolor="#eeeeec">Timber\Factory\PostFactory-&gt;build( <span>$post = </span><span>class WP_Post { public $ID = 1000; public $post_author = '2'; public $post_date = '2023-03-09 10:33:42'; public $post_date_gmt = '2023-03-09 08:33:42'; public $post_content = ''; public $post_title = 'test page'; public $post_excerpt = ''; public $post_status = 'publish'; public $comment_status = 'closed'; public $ping_status = 'closed'; public $post_password = ''; public $post_name = 'test-page'; public $to_ping = ''; public $pinged = ''; public $post_modified = '2023-03-09 10:33:42'; public $post_modified_gmt = '2023-03-09 08:33:42'; public $post_content_filtered = ''; public $post_parent = 0; public $guid = 'http://localhost:8070/?page_id=1000'; public $menu_order = 0; public $post_type = 'page'; public $post_mime_type = ''; public $comment_count = '0'; public $filter = 'raw' }</span> )</td><td title="/var/www/html/vendor/timber/timber/src/Factory/PostFactory.php" bgcolor="#eeeeec">.../PostFactory.php<b>:</b>69</td></tr>
<tr><td bgcolor="#eeeeec" align="center">10</td><td bgcolor="#eeeeec" align="center">3.2925</td><td bgcolor="#eeeeec" align="right">13036016</td><td bgcolor="#eeeeec">Timber\Post::build( <span>$wp_post = </span><span>class WP_Post { public $ID = 1000; public $post_author = '2'; public $post_date = '2023-03-09 10:33:42'; public $post_date_gmt = '2023-03-09 08:33:42'; public $post_content = ''; public $post_title = 'test page'; public $post_excerpt = ''; public $post_status = 'publish'; public $comment_status = 'closed'; public $ping_status = 'closed'; public $post_password = ''; public $post_name = 'test-page'; public $to_ping = ''; public $pinged = ''; public $post_modified = '2023-03-09 10:33:42'; public $post_modified_gmt = '2023-03-09 08:33:42'; public $post_content_filtered = ''; public $post_parent = 0; public $guid = 'http://localhost:8070/?page_id=1000'; public $menu_order = 0; public $post_type = 'page'; public $post_mime_type = ''; public $comment_count = '0'; public $filter = 'raw' }</span> )</td><td title="/var/www/html/vendor/timber/timber/src/Factory/PostFactory.php" bgcolor="#eeeeec">.../PostFactory.php<b>:</b>199</td></tr>
<tr><td bgcolor="#eeeeec" align="center">11</td><td bgcolor="#eeeeec" align="center">3.2926</td><td bgcolor="#eeeeec" align="right">13039136</td><td bgcolor="#eeeeec">apply_filters( <span>$hook_name = </span><span>'timber/post/import_data'</span>, <span>$value = </span><span>['ID' =&gt; 1000, 'post_author' =&gt; '2', 'post_date' =&gt; '2023-03-09 10:33:42', 'post_date_gmt' =&gt; '2023-03-09 08:33:42', 'post_content' =&gt; '', 'post_title' =&gt; 'test page', 'post_excerpt' =&gt; '', 'post_status' =&gt; 'publish', 'comment_status' =&gt; 'closed', 'ping_status' =&gt; 'closed', 'post_password' =&gt; '', 'post_name' =&gt; 'test-page', 'to_ping' =&gt; '', 'pinged' =&gt; '', 'post_modified' =&gt; '2023-03-09 10:33:42', 'post_modified_gmt' =&gt; '2023-03-09 08:33:42', 'post_content_filtered' =&gt; '', 'post_parent' =&gt; 0, 'guid' =&gt; 'http://localhost:8070/?page_id=1000', 'menu_order' =&gt; 0, 'post_type' =&gt; 'page', 'post_mime_type' =&gt; '', 'comment_count' =&gt; '0', 'filter' =&gt; 'raw', 'slug' =&gt; 'test-page', 'status' =&gt; 'publish']</span>, ...<span>$args = </span><i>variadic</i>(<span>class Timber\Post { public $id = 1000; public $ID = 1000; public $object_type = 'post'; protected ?WP_Post $wp_object = class WP_Post { public $ID = 1000; public $post_author = '2'; public $post_date = '2023-03-09 10:33:42'; public $post_date_gmt = '2023-03-09 08:33:42'; public $post_content = ''; public $post_title = 'test page'; public $post_excerpt = ''; public $post_status = 'publish'; public $comment_status = 'closed'; public $ping_status = 'closed'; public $post_password = ''; public $post_name = 'test-page'; public $to_ping = ''; public $pinged = ''; public $post_modified = '2023-03-09 10:33:42'; public $post_modified_gmt = '2023-03-09 08:33:42'; public $post_content_filtered = ''; public $post_parent = 0; public $guid = 'http://localhost:8070/?page_id=1000'; public $menu_order = 0; public $post_type = 'page'; public $post_mime_type = ''; public $comment_count = '0'; public $filter = 'raw' }; protected $___content = NULL; protected $_permalink = NULL; protected $_next = []; protected $_prev = []; protected $_css_class = NULL; public $post_author = NULL; public $post_content = NULL; public $post_date = NULL; public $post_excerpt = NULL; public $post_parent = NULL; public $post_status = NULL; public $post_title = NULL; public $post_type = NULL; public $slug = NULL; protected $__type = NULL }</span>) )</td><td title="/var/www/html/vendor/timber/timber/src/Post.php" bgcolor="#eeeeec">.../Post.php<b>:</b>200</td></tr>
<tr><td bgcolor="#eeeeec" align="center">12</td><td bgcolor="#eeeeec" align="center">3.2926</td><td bgcolor="#eeeeec" align="right">13039544</td><td bgcolor="#eeeeec">WP_Hook-&gt;apply_filters( <span>$value = </span><span>['ID' =&gt; 1000, 'post_author' =&gt; '2', 'post_date' =&gt; '2023-03-09 10:33:42', 'post_date_gmt' =&gt; '2023-03-09 08:33:42', 'post_content' =&gt; '', 'post_title' =&gt; 'test page', 'post_excerpt' =&gt; '', 'post_status' =&gt; 'publish', 'comment_status' =&gt; 'closed', 'ping_status' =&gt; 'closed', 'post_password' =&gt; '', 'post_name' =&gt; 'test-page', 'to_ping' =&gt; '', 'pinged' =&gt; '', 'post_modified' =&gt; '2023-03-09 10:33:42', 'post_modified_gmt' =&gt; '2023-03-09 08:33:42', 'post_content_filtered' =&gt; '', 'post_parent' =&gt; 0, 'guid' =&gt; 'http://localhost:8070/?page_id=1000', 'menu_order' =&gt; 0, 'post_type' =&gt; 'page', 'post_mime_type' =&gt; '', 'comment_count' =&gt; '0', 'filter' =&gt; 'raw', 'slug' =&gt; 'test-page', 'status' =&gt; 'publish']</span>, <span>$args = </span><span>[0 =&gt; ['ID' =&gt; 1000, 'post_author' =&gt; '2', 'post_date' =&gt; '2023-03-09 10:33:42', 'post_date_gmt' =&gt; '2023-03-09 08:33:42', 'post_content' =&gt; '', 'post_title' =&gt; 'test page', 'post_excerpt' =&gt; '', 'post_status' =&gt; 'publish', 'comment_status' =&gt; 'closed', 'ping_status' =&gt; 'closed', 'post_password' =&gt; '', 'post_name' =&gt; 'test-page', 'to_ping' =&gt; '', 'pinged' =&gt; '', 'post_modified' =&gt; '2023-03-09 10:33:42', 'post_modified_gmt' =&gt; '2023-03-09 08:33:42', 'post_content_filtered' =&gt; '', 'post_parent' =&gt; 0, 'guid' =&gt; 'http://localhost:8070/?page_id=1000', 'menu_order' =&gt; 0, 'post_type' =&gt; 'page', 'post_mime_type' =&gt; '', 'comment_count' =&gt; '0', 'filter' =&gt; 'raw', 'slug' =&gt; 'test-page', 'status' =&gt; 'publish'], 1 =&gt; class Timber\Post { public $id = 1000; public $ID = 1000; public $object_type = 'post'; protected ?WP_Post $wp_object = class WP_Post { ... }; protected $___content = NULL; protected $_permalink = NULL; protected $_next = [...]; protected $_prev = [...]; protected $_css_class = NULL; public $post_author = NULL; public $post_content = NULL; public $post_date = NULL; public $post_excerpt = NULL; public $post_parent = NULL; public $post_status = NULL; public $post_title = NULL; public $post_type = NULL; public $slug = NULL; protected $__type = NULL }]</span> )</td><td title="/var/www/html/web/wp/wp-includes/plugin.php" bgcolor="#eeeeec">.../plugin.php<b>:</b>205</td></tr>
<tr><td bgcolor="#eeeeec" align="center">13</td><td bgcolor="#eeeeec" align="center">3.2961</td><td bgcolor="#eeeeec" align="right">13043984</td><td bgcolor="#eeeeec">Timber\Timber::handle_preview( <span>$data = </span><span>class WP_Post { public $ID = 1; public $post_author = '2'; public $post_date = '2022-04-01 10:29:33'; public $post_date_gmt = '2022-04-01 10:29:33'; public $post_content = ''; public $post_title = 'test page'; public $post_excerpt = ''; public $post_status = 'publish'; public $comment_status = 'closed'; public $ping_status = 'closed'; public $post_password = ''; public $post_name = 'financial-newsitem-1'; public $to_ping = ''; public $pinged = ''; public $post_modified = '2022-07-11 13:11:10'; public $post_modified_gmt = '2022-07-11 13:11:10'; public $post_content_filtered = ''; public $post_parent = 0; public $guid = 'http://localhost:8070/?p=1'; public $menu_order = 0; public $post_type = 'post'; public $post_mime_type = ''; public $comment_count = '1'; public $filter = 'raw' }</span>, <span>$post = </span><span>class Timber\Post { public $id = 1000; public $ID = 1000; public $object_type = 'post'; protected ?WP_Post $wp_object = class WP_Post { public $ID = 1000; public $post_author = '2'; public $post_date = '2023-03-09 10:33:42'; public $post_date_gmt = '2023-03-09 08:33:42'; public $post_content = ''; public $post_title = 'test page'; public $post_excerpt = ''; public $post_status = 'publish'; public $comment_status = 'closed'; public $ping_status = 'closed'; public $post_password = ''; public $post_name = 'test-page'; public $to_ping = ''; public $pinged = ''; public $post_modified = '2023-03-09 10:33:42'; public $post_modified_gmt = '2023-03-09 08:33:42'; public $post_content_filtered = ''; public $post_parent = 0; public $guid = 'http://localhost:8070/?page_id=1000'; public $menu_order = 0; public $post_type = 'page'; public $post_mime_type = ''; public $comment_count = '0'; public $filter = 'raw' }; protected $___content = NULL; protected $_permalink = NULL; protected $_next = []; protected $_prev = []; protected $_css_class = NULL; public $post_author = NULL; public $post_content = NULL; public $post_date = NULL; public $post_excerpt = NULL; public $post_parent = NULL; public $post_status = NULL; public $post_title = NULL; public $post_type = NULL; public $slug = NULL; protected $__type = NULL }</span> )</td><td title="/var/www/html/web/wp/wp-includes/class-wp-hook.php" bgcolor="#eeeeec">.../class-wp-hook.php<b>:</b>308</td></tr>
</tbody></table>

**Comment by nlemoine** [comment]
I'm still not being able to reproduce the issue. Could you fork [this repo](https://github.com/nlemoine/timber-run) and try to setup your test case?

**Comment by andrewwfesenko** [comment]
ahhh, I've found the cause for this error. 
<img width="614" alt="image" src="https://user-images.githubusercontent.com/62845061/224287435-8ec6da86-7965-4a7b-b64c-12335a909ca3.png">
It turned out one of our devs manually added a fix for previews last year, but once the issue was fixed in Timber the fix became the problem haha.
Removing this fixed the error.
@nlemoine Thanks for your time!

**Comment by nlemoine** [comment]
Thank you for investigating this issue! Glad everything is ok :)
