### ISSUE TITLE
ACF repeater field working on Single template, but returning number of rows on Archive (custom post type)

### ISSUE THREAD

**Issue by cornederuijter** [timber/timber#2722]
### Expected Behavior

I set up a Repeater field with a Taxonomy reference. 
On Single CPT template I use the following code to retrieve a Repeater field:
```
{% for item in post.meta('auteurs_voor_volgorde') %}
	{% if loop.length > 1 and not loop.last %}
		<a href="{{item.auteur.link}}">{{ item.auteur.titel }} {{ item.auteur }}</a>,
	{%  else %}
		<a href="{{item.auteur.link}}">{{ item.auteur.titel }} {{ item.auteur }}</a>
	{%  endif %}
{% endfor %}
```
This works perfectly, and it renders a list (in order of the Repeater). This should also be done within the Posts for loop on an archive page for this specific CPT. 

### Actual behavior

What happens on an archive page within a Posts for loop is that the same code returns the number of lines, and not the actual array containing the repeater values. 
Other values in the Post are available.

### Steps to reproduce behavior

1. Use code on a Single template and it will show the actual repeater fields.
2. Use code on a Tease template within an archive and it shows the number of rows in the repeater.

### What version of Timber are you using?

1.22.1

### What version of WordPress are you using?

6.1.1

### What version of PHP are you using?

8.0

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Hi @cornederuijter ,

How can item.auteur be both an array containing link and title and also a singular item?  {{ item.auteur }} should return an array to string conversion error if I am right. Can you also post your field configuration here? in json format for example.

`<a href="{{item.auteur.link}}">{{ item.auteur.titel }} {{ item.auteur }}</a>,`

I also think that {{loop.length}} is not a thing in twig. You can check the length of an array with `post.meta('auteurs_voor_volgorde')|length`. Loop.first and loop.last do exist though.

**Comment by cornederuijter** [comment]
Hi @Levdbas 
Via [this link](https://burobureaux.nl/acf-export-2023-03-17.json) a JSON of the ACF field configuration can be downloaded. The field it is about is the "auteurs_voor_volgorde" or key "field_6411c6d96d59d". 

It is a repeater containing one subfield type Taxonomy, giving back the Term Object. ```{{ item.auteur }}``` then returns the name/title of the term, but the link and titel (ACF field to the term) can also be accessed. At least in the single template they can. When written as ```{{ item.auteur.name }}``` it also works.

Additional info regarding the for loop: it doesn't loop anything. When I add "test" after  ```{% for item in post.meta('auteurs_voor_volgorde') %}``` it doesn't print/echo. Though the array contains 2 records.

**Comment by Levdbas** [comment]
So If I am correct, item.titel and item.auteur are term fields. You might want to access them with the meta() method.
When you

```twig
<pre>
    {{ dump(post.meta('auteurs_voor_volgorde')) }}
</pre>
```

What does it return?

**Comment by cornederuijter** [comment]
@Levdbas 

```item``` is a repeater row, ```auteur``` is the term. Within that term ```titel```, ```name``` and ```link``` are available to use. 

When dumping the ```post.meta('auteurs_voor_volgorde')``` nothing shows, it seems the loop is not looping (As if there are no results). When dumping  ```post.meta('auteurs_voor_volgorde')``` before the loop, it just dump ```string(1) "2"```.

However, when dumping on the single page it dumps the actual array that is expected there with two Term objects. 

@gchtr I did see that issue and looked into that. Timber is initialized, and the code shown above does work fine on a single page, it just doesn't on an archive. ACF fields are defined through the GUI and the key is unique (Wordpress wide). 

When doing a select on post_meta  for the unique key I get the below results:
meta_id / post_id / meta_key / meta_value
4493 / 580 / auteurs_voor_volgorde / 2

I am testing this on one post (580) and the repeater contains two rows.

I also tried getting the repeater via post.get_field('auteurs_voor_volgorde'), but the result is similar. 

Also, other ACF fields (singular text fields e.g.) are available to print on the archive.

**Comment by Levdbas** [comment]
And what happens when you `var_dump(get_field('auteurs_voor_volgorde', 580))` on the archive.php file? And how does that file look like? and can you post the archive.twig file as well? I suspect you are using https://github.com/timber/starter-theme/blob/1.x/templates/archive.twig. Is that right?

If so, can you try to copy the contents of index.twig to archive.twig and then try the Twig dump again? Might has something to do with parent() in that case.  Just a guess, but lets make the code as simple as possible to debug.

**Comment by cornederuijter** [comment]
Dumping that gives back ```string(1) "2"```. Below are links to the specific files:
[Archive.twig](https://burobureaux.nl/dir/archive_twig.txt)
[Index.twig](https://burobureaux.nl/dir/index.txt)
[Tease.twig](https://burobureaux.nl/dir/tease.txt)
[Archive.php](https://burobureaux.nl/dir/archive_php.txt)

I did deactivate plugins where possible, since that gives other unwanted errors or complete disables functionality.

**Comment by Levdbas** [comment]
So when `var_dump(get_field('auteurs_voor_volgorde', 580))` in the archive php file, the result is also 2.

so then it's at least not the Twig part, and neither the Timber part I think. Do you use any pre_get_posts filters to change the output?  I found a post somewhere that I cannot find again, that also linked this to a similar problem. Or maybe FacetWP is messing something up?

To completely rule out Timber you could empty the archive.php file and just run the var_dump.

**Comment by cornederuijter** [comment]
@Levdbas thank you very much for getting me on this track. I indeed have a pre_get_posts filter to only query the parent posts of the CPT. When turning of the filter, I get the full array.

I will close this, since it is not a timber issue.

Thanks again!
