### ISSUE TITLE
[BUG] Preview not working when using Gutenberg

### ISSUE THREAD

**Issue by timohubois** [timber/timber#2723]
### Expected Behavior

Today I ran into a problem when I try to display the preview of a post that uses Gutenberg. The Page uses some static components and some of them containing images. In relation to the images, the  received $data of the image is not an object which then causes an issue and the preview will not displayed:
<img width="305" alt="Screenshot 2023-03-20 at 01 27 19" src="https://user-images.githubusercontent.com/46505685/226220170-15f7472f-7591-40d7-b24e-883de3a5befa.png">

### Actual behavior

Getting an error and the page will not rendered:
1. `Fatal error: Uncaught Error: Attempt to assign property "post_content" on array … /vendor/timber/timber/src/Timber.php on line 178`
2. `Error: Attempt to assign property "post_content" on array in …/vendor/timber/timber/src/Timber.php on line 178`

### Steps to reproduce behavior

1. Install the current [next branch](https://github.com/flyntwp/flynt/tree/next) of the Flynt theme.
2. Create at lest min 2 posts with a featured image, each.
3. Try to display use the Preview functionality from Gutenberg.

### What version of Timber are you using?

2.0.0-beta.1

### What version of WordPress are you using?

WordPress 6.1

### What version of PHP are you using?

PHP 8.0

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by timohubois** [comment]
Short update: The bug seems to be related to the 2.0.0-beta.1. When I use 2.x-dev it works as aspected. Would be very happy about to read something about of a new beta version.

**Comment by YourMark** [comment]
I've encountered the same issue with the exact same versions of Timber, WP and PHP.

**Comment by Levdbas** [comment]
Beta 2 is now released @timohubois . Can you confirm that updating to this version solves the issue?

**Comment by timohubois** [comment]
@Levdbas can confirm that the issue is fixed within the Beta 2 release. Great work and many thanks!
