### ISSUE TITLE
[BUG] Elementor integration

### ISSUE THREAD

**Issue by azralth** [timber/timber#2726]
### Expected Behavior

On Elementor option, using the template builder and create archive page from Elementor

### Actual behavior

The builder can't be load with no further information

### Steps to reproduce behavior

1. Go to templates-> Theme builder
2. Add new and choos archive in template option

Then elementor just crash.

### Notes

I think the problem comes from Elementor calling specific post type "elementor_library". And it seems that this post type won't use the single.php file. Don't know how it work but i think this maybe can cause the problem.

### What version of Timber are you using?

Timber 1.22.2

### What version of WordPress are you using?

WordPress 6.2

### What version of PHP are you using?

PHP 8.0

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Hi @azralth , we are not really supporting third-party pagebuilders. I am going to have to close this unfortunately. If you happen to find a solution, please post it here if anyone else want to run this setup.
