### ISSUE TITLE
[BUG] WP's header() function does not work in theme's functions.php

### ISSUE THREAD

**Issue by John-B** [timber/timber#2759]
### Expected Behavior

A function which runs in functions.php and which includes `'header(' Content-Description: File Transfer')` should add the expected html response header.

### Actual behavior

Although  the function does run, the WP header() function does nothing.  As a result, the headers required for a file download  are missing, and the file which should download is rendered in the browser.

### Steps to reproduce behavior

1.Install a Timber and a Timber-based theme.
2.Add a function to functions.php which includes `'header(' Content-Description: File Transfer')` or any other variation on the usual html headers.
3.Check to ensure the function is running.
4.Check and find that the header is not added or modified.
...

### Notes

Is there a workaround or implementation step which I am missing?

I inherited the site. Was given a code package with a broken composer setup. I updated Timber from WP repo.
However, I have also now run 'composer require timber/timber;' and downloaded the latest version of timber and dependencies, and the problem remains. 

### What version of Timber are you using?

Timber 1.22.1

### What version of WordPress are you using?

WordPress 6.2.

### What version of PHP are you using?

PHP 7.4

### How did you install Timber?

Other (see notes)

**Comment by Levdbas** [comment]
@John-B , I am almost certain that this method does not work in a vanilla WordPress template as well. Did you tried that already? Adding headers this late seems not like a good idea anyway. Why not via nginx/htaccess?

**Comment by Levdbas** [comment]
I just tested adding 

```php
function add_test_header()
{
	header(' Content-Description: File Transfer');
}

add_test_header();
```

inside the functions file of twentytwentyone and that results to the same behaviour. If I understand your case the wrong way, please provide a code example.

**Comment by John-B** [comment]
Your test does work in functions.php in twentytwentyone when corrected to WP's API syntax. For example:

```
add_action( 'template_redirect', 'add_test_header' );
function add_test_header()
{
  header('Expires:  Fri, 02 Dec 1990 16:00:00 GMT');
}
```

**Comment by John-B** [comment]
This also works in a Timber-based theme, so maybe I am missing something....
