### ISSUE TITLE
[BUG] URLHelper::is_external() false-positive

### ISSUE THREAD

**Issue by mcaskill** [timber/timber#2766]
### Expected Behavior

Given a WordPress installation with a hostname `example.com` and external URL that contains the hostname as a substring (subdomain, path, query, fragment), for example: `https://facebook.com/example.com`.

Calling `URLHelper::is_external()` with the aforementioned external URL should return `true`.

### Actual behavior

Calling `URLHelper::is_external()` with an external returns `false` because `strstr()` is used to detect the current hostname.

### Steps to reproduce behavior

1. Call `URLHelper::is_external()` with an absolute URL that contains the current host as either:
	- subdomain: `example.com.github.io`
	- domain: `anotherexample.com`
	- path: `github.io/example.com`
	- query: `github.io?url=example.com`
	- fragment `github.io#example.com`

### Notes

* Timber v1: https://github.com/timber/timber/blob/1.22.1/lib/URLHelper.php#L327
* Timber v2: https://github.com/timber/timber/blob/2.0.0-beta.2/src/URLHelper.php#L442

This issue also affects the `URLHelper::is_local()` method.

### What version of Timber are you using?

v2 (issue present since v1)

### What version of WordPress are you using?

Irrelevant (v6.2)

### What version of PHP are you using?

irrelevant (PHP 8.1)

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by gchtr** [comment]
Fixed in #2767 and #2782.
