### ISSUE TITLE
[BUG] Deprecated Twig Errors in PHP 8.1

### ISSUE THREAD

**Issue by baerkins** [timber/timber#2768]
### Expected Behavior

No deprecation errors.

### Actual behavior

Front end errors:

```
Deprecated: Return type of Twig\Node\Node::count() should either be compatible 
with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be 
used to temporarily suppress the notice in /[site-path]/wp-content/plugins/timber-library/vendor/twig/twig/src/Node/Node.php on line 213

Deprecated: Return type of Twig\Node\Node::getIterator() should either be compatible 
with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] 
attribute should be used to temporarily suppress the notice in 
/[site-path]/wp-content/plugins/timber-library/vendor/twig/twig/src/Node/Node.php on line 221
```

### Steps to reproduce behavior

Running php v8.1.13

### Notes

Installed Timber via composer from the wpackagist library (so using the WP plugin repo source, not a 'true' composer install)

### What version of Timber are you using?

1.22.1

### What version of WordPress are you using?

6.2.2

### What version of PHP are you using?

8.1.13

### How did you install Timber?

Other (see notes)

**Comment by megclaypool** [comment]
I am seeing the same errors since I updated PHP to 8.1

**Comment by megclaypool** [comment]
When I look at wp-content/plugins/timber-library/vendor/twig/twig/src/Node/Node.php on line 213, I see the following error in my IDE's popup: 

> Method 'Twig\Node\Node::count()' is not compatible with method 'Twig_NodeInterface::count()'.

**Comment by megclaypool** [comment]
Similarly, on line 221 I see the message:

> Method 'Twig\Node\Node::getIterator()' is not compatible with method 'Twig_NodeInterface::getIterator()'.

**Comment by megclaypool** [comment]
Looking at line 23, I see that there's a problem with `class Node implements \Twig_NodeInterface`:

```
'Twig_NodeInterface' is deprecated.

Twig_NodeInterface

Represents a node in the AST.

<?php
interface Twig_NodeInterface extends
    Countable,
    IteratorAggregate { }
Abstract base interface that cannot be implemented alone. Instead it must be implemented by either {@see IteratorAggregate} or {@see Iterator}.

@deprecated since — 1.12 (to be removed in 3.0)

@author Fabien Potencier [fabien@symfony.com](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)
```

I did a little investigating, and it looks like replacing `class Node implements \Twig_NodeInterface` with `class Node implements \Twig\Node\Node` on line 23 solves the problem. 

##### Note:   
I'm using the WordPress installable plugin version, which seems to still be using Twig 1.something, so at this point I got more errors. I downloaded the GitHub version, `composer install`ed from within the newly downloaded directory, and then replaced the vendor folder in the WP plugin with the vendor directory generated by the GH version. Now everything works. Unfortunately, this fix will be wiped out next time an update to the WP installable plugin is released 🤦🏽‍♀️ I can't move this particular site to a composer-managed workflow, so I guess the solution in this case is to downgrade the PHP back to 7 😛

**Comment by Levdbas** [comment]
Thank you @baerkins  for the bug report and @megclaypool. In Timber 2.x we are going to upgrade to Twig 3 where this error is no longer present. Since all our resources are currently at making Timber 2 a reality we are not going to fix this at this time. You could both give Timber 2 a spin by using `composer require timber/timber:2.x-beta2` in your project. See docs as well: https://timber.github.io/docs/v2/installation/ This version is compatible with PHP8.1.
