### ISSUE TITLE
[BUG] toWebP() causes Uncaught TypeError: imageistruecolor(): Argument #1 ($image) must be of type GdImage, null given Error

### ISSUE THREAD

**Issue by joworeiter** [timber/timber#2771]
### Expected Behavior

Error should appear gracefully - not with fatal error

### Actual behavior

Fatal Error: 

`Fatal error: Uncaught TypeError: imageistruecolor(): Argument #1 ($image) must be of type GdImage, null given in /var/www/html/vendor/timber/timber/src/Image/Operation/ToWebp.php:70 Stack trace: #0 /var/www/html/vendor/timber/timber/src/Image/Operation/ToWebp.php(70): imageistruecolor(NULL) #1 /var/www/html/vendor/timber/timber/src/ImageHelper.php(786): Timber\Image\Operation\ToWebp->run('/var/www/html/w...', '/var/www/html/w...') #2 /var/www/html/vendor/timber/timber/src/ImageHelper.php(251): Timber\ImageHelper::_operate(Object(Timber\Image), Object(Timber\Image\Operation\ToWebp), false) #3 /var/www/html/vendor/twig/twig/src/Environment.php(361) : eval()'d code(109): Timber\ImageHelper::img_to_webp(Object(Timber\Image), 100) #4 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_b586174beedce73510d475d126f1d7b1->block_image_source(Array, Array) #5 /var/www/html/vendor/twig/twig/src/Environment.php(361) : eval()'d code(38): Twig\Template->displayBlock('image_source', Array, Array) #6 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_b586174beedce73510d475d126f1d7b1->doDisplay(Array, Array) #7 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array) #8 /var/www/html/vendor/twig/twig/src/Environment.php(361) : eval()'d code(75): Twig\Template->display(Array) #9 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_8437ccb3c20ecf63eadccf3687fbf1e4->doDisplay(Array, Array) #10 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array) #11 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array) #12 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array) #13 /var/www/html/vendor/timber/timber/src/Loader.php(177): Twig\TemplateWrapper->render(Array) #14 /var/www/html/vendor/timber/timber/src/Timber.php(1445): Timber\Loader->render('blocks/member.t...', Array, false, 'default') #15 /var/www/html/vendor/timber/timber/src/Timber.php(1582): Timber\Timber::compile('blocks/member.t...', Array, false, 'default', true) #16 /var/www/html/packages/themes/atract_2023/blocks/block.php(31): Timber\Timber::render('blocks/member.t...', Array) #17 /var/www/html/web/app/plugins/advanced-custom-fields-pro/pro/blocks.php(678): include('/var/www/html/p...') #18 /var/www/html/web/wp/wp-includes/class-wp-hook.php(308): acf_block_render_template(Array, '', false, 143, Object(WP_Block), Array) #19 /var/www/html/web/wp/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #20 /var/www/html/web/wp/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #21 /var/www/html/web/app/plugins/advanced-custom-fields-pro/pro/blocks.php(652): do_action('acf_block_rende...', Array, '', false, 143, Object(WP_Block), Array) #22 /var/www/html/web/app/plugins/advanced-custom-fields-pro/pro/blocks.php(569): acf_render_block(Array, '', false, 143, Object(WP_Block), Array) #23 /var/www/html/web/app/plugins/advanced-custom-fields-pro/pro/blocks.php(502): acf_rendered_block(Array, '', false, 143, Object(WP_Block)) #24 /var/www/html/web/wp/wp-includes/class-wp-block.php(258): acf_render_block_callback(Array, '', Object(WP_Block)) #25 /var/www/html/web/wp/wp-includes/blocks.php(1072): WP_Block->render() #26 /var/www/html/web/wp/wp-includes/blocks.php(1110): render_block(Array) #27 /var/www/html/web/wp/wp-includes/class-wp-hook.php(308): do_blocks('<!-- wp:acf/mem...') #28 /var/www/html/web/wp/wp-includes/plugin.php(205): WP_Hook->apply_filters('<!-- wp:acf/mem...', Array) #29 /var/www/html/vendor/timber/timber/src/Post.php(1229): apply_filters('the_content', '<!-- wp:acf/mem...') #30 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1635): Timber\Post->content() #31 /var/www/html/vendor/twig/twig/src/Environment.php(361) : eval()'d code(51): twig_get_attribute(Object(Twig\Environment), Object(Twig\Source), Object(Timber\Post), 'content', Array, 'any', false, false, false, 4) #32 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_ce5434521058693ae5ee30ebd5dfb5cd->block_content(Array, Array) #33 /var/www/html/vendor/twig/twig/src/Environment.php(361) : eval()'d code(83): Twig\Template->displayBlock('content', Array, Array) #34 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_93b1927f1e0c1d9c13338ee9f03449ed->doDisplay(Array, Array) #35 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array) #36 /var/www/html/vendor/twig/twig/src/Environment.php(361) : eval()'d code(42): Twig\Template->display(Array, Array) #37 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_ce5434521058693ae5ee30ebd5dfb5cd->doDisplay(Array, Array) #38 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array) #39 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array) #40 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array) #41 /var/www/html/vendor/timber/timber/src/Loader.php(177): Twig\TemplateWrapper->render(Array) #42 /var/www/html/vendor/timber/timber/src/Timber.php(1445): Timber\Loader->render('pages/page.twig', Array, false, 'default') #43 /var/www/html/vendor/timber/timber/src/Timber.php(1582): Timber\Timber::compile(Array, Array, false, 'default', true) #44 /var/www/html/packages/themes/atract_2023/page.php(13): Timber\Timber::render(Array, Array) #45 /var/www/html/web/wp/wp-includes/template-loader.php(106): include('/var/www/html/p...') #46 /var/www/html/web/wp/wp-blog-header.php(19): require_once('/var/www/html/w...') #47 /var/www/html/web/index.php(7): require('/var/www/html/w...') #48 {main} thrown in /var/www/html/vendor/timber/timber/src/Image/Operation/ToWebp.php on line 70`

### Steps to reproduce behavior

1. handle Images with towebp()
2.
3.
...

### Notes

This error happens currently only local with my dev-setup - not on my staging server. 
So perhaps there is module missing? Sadly I have no clue, where to start debugging... 

My Setup: 
WSL2 with Ubuntu
Running Docker on Unix Side with DDEV. 
PHP 8.1

### What version of Timber are you using?

Timber 2 Beta 2

### What version of WordPress are you using?

WordPress 6.2.2 (in Composer/Bedrock Setup)

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Created a PR for this. The `imagecreatefrom..` functions should always return false or an instance of GDimage. For some reason it's null for you. In the PR I check in $input is set in the webp creation process and throw an error when it isn't.

**Comment by gchtr** [comment]
Fixed in #2780.
