### ISSUE TITLE
[BUG] Deprecation Notice implicit conversion from float to int in ImageDimensions.php

### ISSUE THREAD

**Issue by joworeiter** [timber/timber#2772]
### Expected Behavior

No deprecation notice

### Actual behavior

Deprecated:  Implicit conversion from float to int loses precision in /timber/timber/src/ImageDimensions.php on line 151

### Steps to reproduce behavior

1. add an image with strange dimensons as float (eg. a svg)
2. load the page

### Notes

Here would be the fix, I just doesn't have timber dev setup to provide a pull request. 

```
 protected function get_dimension_loaded($dim = null): int
    {
        $dim = strtolower($dim);

        if ('h' === $dim || 'height' === $dim) {
            return (int) $this->dimensions[1];
        }

        return (int) $this->dimensions[0];
    }
```

### What version of Timber are you using?

Timber 2 Beta 2

### What version of WordPress are you using?

WordPress 6.2.2 (in Composer/Bedrock Setup)

### What version of PHP are you using?

PHP 8.1

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by gchtr** [comment]
Thanks for taking the time to open this issue 🙌.

This was fixed in #2775 by converting floats to rounded integers when getting the width and height from an SVG.
