### ISSUE TITLE
[BUG] Issues with Image convert and paths 

### ISSUE THREAD

**Issue by dreamersofdreams** [timber/timber#2789]
### Expected Behavior

I'm trying to convert images using exact method spelled out in documentation to try and convert jpg to webp using twig filter: https://timber.github.io/docs/v2/guides/cookbook-images/#using-webp-images 
This works flawlessly on my local testing environment. When I view network inspector in browser I can see all my jpgs being successfully converted to webp. 

### Actual behavior

On our multisite Wordpress install, our media library points to our image files like so: https://go.arts.vcu.edu/artsstudents/files/2023/08/Summer-2023-Studio-Two-Three-Trash-Market.jpeg 
So in twig file if I use the simple {{post.thumbnail.src}} this loads no problem as seen on this post page: https://go.arts.vcu.edu/artsstudents/studio-two-threes-trash-mart-summer-2023/ the image on that page points to aforementioned image path. Ok cool. 
However, on my homepage (https://go.arts.vcu.edu/artsstudents), all my images for the teaser posts that I used the twig filters to convert to webp's get redirected to some new folder /artsstudents/wp-content/blogs.dir/96/files/external/xxxxxx.jpeg
<img width="1026" alt="Screenshot 2023-08-04 at 10 26 29 PM" src="https://github.com/timber/timber/assets/116822638/7a2d18e0-6357-489a-b935-ae9e6f89bd76">
And most importantly they do not get converted to webps when I review in network tab in browser inspector. 
So Timber is almost treating them as external URLs perhaps?
My twig code is basically right from the documentation to try and convert webp first and then go to the fallbacks:
             ` <picture>
              <source srcset="{{ post.thumbnail.src|towebp }}" type="image/webp">
              <source srcset="{{ post.thumbnail.src|tojpg }}" type="image/jpeg">
              <img class="bd-placeholder-img card-img-top" width="100%" src="{{post.thumbnail.src}}".....>
              </picture>`

The way I originally caught this was I started off trying some popular image converter plugins such as EWWW IO. When I tried using that plugin, it just would not serve the webp images no matter what method I tried (using htaccess redirects, JS redirects, etc.). Both the plugin support and our server admin were stumped b/c server was definitely able to serve up webp images and configs looked fine.  Then we swapped to a 2021 Wordpress theme and it immediately worked and loaded all the proper webp images. 

So obviously something is getting out of whack because of the non-traditional media file path perhaps being on a multisite? But I'm interpreting this as a bug since as soon as I swap to a traditional wordpress theme it just works.  
This site is still a work in progress but it's gonna be image heavy, so being able to convert the jpgs using the twig |towebp filters (and resizing) will be a gamechanger for speed optimization so I'm hoping to get this to work! I'm pretty new to Timber but have learned a lot over last few months and really appreciate all your work on this project - many thanks! 

### Steps to reproduce behavior

1.
2.
3.
...

### Notes

I'm using a pretty simple version of the Timber 2.0 Starter Theme - this will basically be your classic blog type site. 

### What version of Timber are you using?

2.0.0-rc.1

### What version of WordPress are you using?

6.2.2

### What version of PHP are you using?

7.4.33

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by dreamersofdreams** [comment]
After doing some more research I think this is a Starter Theme 2.x issue not being able to handle non-traditional Wordpress paths. So I went back and did a fresh install of starter theme 2.x on our multisite install which handles media as such:
root/artsstudents/files/2023/08....
When I try to use any kind of image optimization plugin, they just will not work with this setup. Likewise, as previously outlined, the theme cannot handle twig image filters, etc. 
But the big takeaway is that traditional Wordpress themes can handle this without any issues. 
I can perhaps report this in the Starter theme github too, but does anyone have any temporary workarounds I might be able to try? Would love to be able to use Timber for our project, but it's critical to be able to optimize our images.

**Comment by dreamersofdreams** [comment]
Believe it or not, my issue was solved by this solution discovered back in 2017: https://github.com/timber/timber/issues/1303#issuecomment-287194017
After all that headache it was something as simple as adding an "s" to http in the site URL settings in wordpress :) I could go ahead and close this, but maybe begs the question of whether there could be some kind of alternative to prevent such outcome? I'm new to Timber so I'll let the experts weigh in.

**Comment by Levdbas** [comment]
Hi @dreamersofdreams , great that you were able to fix your issue. It's true that a good idea in general that the site/home urls always match the actual address being in use.
