### ISSUE TITLE
Nested ACF Repeaters?

### ISSUE THREAD

**Issue by garrettboatman** [timber/timber#279]
I have some nested repeater fields and I can't seem to get them to work in my twig files. How I have it now(not working) is:

``` html+django
{% for item_outer in post.get_field('outer') %}
     {{item_outer.title}}

     {% for item_inner in item_outer.get_field('inner') %}
          {{item_inner.title}}
     {% endfor %}

{% endfor %}
```

Am I missing something obvious?

Here's a link of them working with PHP, but i'd rather not have to handle these in my controller. http://www.advancedcustomfields.com/resources/tutorials/working-with-nested-repeaters/

**Comment by baldursson** [comment]
:thumbsup:

**Comment by middle8media** [comment]
Can someone can help me with this? I am trying to access a repeater inside a repeater inside a repeater

```
{% for item in post.get_field('data_set') %}
    <p>{{ item.data_set_description }}</p> // this renders fine

    {% for item_outer in post.get_field('data_set_files') %}

        {% for item_inner in item_outer.data_set_file_url %}
            {{ item_inner }}
        {% endfor %}

    {% endfor %}

{% endfor %}
```

![image](https://cloud.githubusercontent.com/assets/1033332/15763564/c44f0782-28f2-11e6-924d-b8d58bed63a7.png)

`{{ item_inner }}` does not display.

Any suggestions? Thanks

**Comment by connorjburton** [comment]
Can you try this please? Or something of this variation will work

```
{% for set in post.get_field('data_set') %}
    <p>{{ set.data_set_description }}</p> // this renders fine

    {% for files in set.data_set_files %}
        {% for file in files.data_set_file %}
            {{ file }}
        {% endfor %}
    {% endfor %}
{% endfor %}
```
