### ISSUE TITLE
[BUG] towebp function quality parameter has no effect

### ISSUE THREAD

**Issue by ayhankiz** [timber/timber#2790]
I use the towebp() function, but it seems that the parameter "quality" has no effect on the function. 
The image does not become sharper when I call the function
This is my code

    {% set media = options.g_cta_image %}
    <picture class="cta__image">
        <source srcset="{{ media.url|towebp(100) }}" type="image/webp">
        <source srcset="{{ media.url|tojpg }}" type="image/jpeg">
        <img 
            src="{{ media.url }}"
            alt="{{ media.alt }}" 
            loading="lazy"
            height="700"
            width="400"
            class="img"
        >
    </picture>
    
    Have I done something wrong ?
   

### What version of Timber are you using?

1.22.1

### What version of WordPress are you using?

WordPress: 6.2

### What version of PHP are you using?

PHP 8.1.9

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Hi @ayhankiz , are you sure there isn't a webp version of your image already generated with the old default settings. If so, you could try to delete that older file and regenerate the image.
