### ISSUE TITLE
Allow classes that extend Timber\Post to run code on object instantiation

### ISSUE THREAD

**Issue by herrschuessler** [timber/timber#2792]
## Is your feature request related to a problem? Please describe.
Since #2088, post classes that extend Timber\Post cannot overwrite the constructor, thus making it impossible to run additional code when a new class object is created.

## Describe the solution you’d like
I'd like to be able to overwrite a class method that runs on instantiation, so that I can add own init code.

## Describe alternatives you’ve considered
Not sure if there's already a way to do this.

**Comment by nlemoine** [comment]
How about overriding `build` method? This is where you can put you place your custom code.
