### ISSUE TITLE
[BUG] Conflict with Jetpack 12.6.1

### ISSUE THREAD

**Issue by tylersticka** [timber/timber#2809]
### Expected Behavior

Timber 1.x theme should work when Jetpack version 12.6.1 or greater is installed.

When upgrading Jetpack to version 12.6.1 with any Timber 1.x theme (including the starter theme), a critical PHP error occurs.

### Actual behavior

When a Timber theme is active and Jetpack 12.6.1 is installed, a critical error occurs.

Example error stack:

```
Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/post-template.php:324
Stack trace:
#0 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-videopress/src/class-initializer.php(363): get_the_content()
#1 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/class-wp-hook.php(310): Automattic\Jetpack\VideoPress\Initializer::Automattic\Jetpack\VideoPress\{closure}('')
#2 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#3 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/script-loader.php(2225): do_action('wp_enqueue_scri...')
#5 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/class-wp-hook.php(310): wp_enqueue_scripts('')
#6 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#7 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/general-template.php(3053): do_action('wp_head')
#9 [internal function]: wp_head()
#10 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/lib/Twig.php(296): call_user_func_array('wp_head', Array)
#11 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Environment.php(497) : eval()'d code(70): Timber\Twig->exec_function('wp_head')
#12 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Template.php(453): __TwigTemplate_28c4d9cbcf8c6d7ff58ba31b4ef679fb342af24a7a09df9c29a581cbd91d8695->doDisplay(Array, Array)
#13 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array)
#14 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Environment.php(497) : eval()'d code(101): Twig\Template->display(Array)
#15 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Template.php(214): __TwigTemplate_1f82296bcceac4ae49d87c8aa347a1e7deb6652c60c233ace653d3509b1cef97->block_html_head_container(Array, Array)
#16 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Environment.php(497) : eval()'d code(35): Twig\Template->displayBlock('html_head_conta...', Array, Array)
#17 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Template.php(453): __TwigTemplate_1f82296bcceac4ae49d87c8aa347a1e7deb6652c60c233ace653d3509b1cef97->doDisplay(Array, Array)
#18 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array)
#19 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Environment.php(497) : eval()'d code(35): Twig\Template->display(Array, Array)
#20 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Template.php(453): __TwigTemplate_7e4762580c0bd2e7137951194db301f145d96a7839bc3d333887c8fb4b3ec413->doDisplay(Array, Array)
#21 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array)
#22 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Template.php(432): Twig\Template->display(Array)
#23 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/TemplateWrapper.php(47): Twig\Template->render(Array, Array)
#24 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/lib/Loader.php(79): Twig\TemplateWrapper->render(Array)
#25 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/lib/Timber.php(334): Timber\Loader->render('index.twig', Array, false, 'default')
#26 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/lib/Timber.php(383): Timber\Timber::compile(Array, Array, false, 'default', true)
#27 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/lib/Timber.php(410): Timber\Timber::fetch(Array, Array, false, 'default')
#28 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/themes/starter-theme-1.x/index.php(23): Timber\Timber::render(Array, Array)
#29 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/template-loader.php(106): include('/Users/tylersti...')
#30 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-blog-header.php(19): require_once('/Users/tylersti...')
#31 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/index.php(17): require('/Users/tylersti...')
#32 {main}
  thrown in /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/post-template.php on line 324
```

### Steps to reproduce behavior

1. Install and activate Jetpack 12.6.1
1. Install and activate the Timber plugin
1. Download, install and activate the Timber starter theme
1. Attempt to view any non-admin page

### Notes

I reported the bug to Automattic/Jetpack, but the issue was closed. They say the fault lies with Timber and the way it runs `the_post` action. See thread: https://github.com/Automattic/jetpack/issues/33284

### What version of Timber are you using?

Timber 1.22.1

### What version of WordPress are you using?

WordPress 6.3.1

### What version of PHP are you using?

PHP 8.1.23

### How did you install Timber?

Installed or updated the Timber plugin from the WordPress plugin repository

**Comment by josh-attwood** [comment]
I am also getting this issue on a client site. I have had do disable Jetpack for the minute as it was displaying a php error on every page of the site.

Are there any updates as to when a fix can be pushed? This site uses Jetpack for stats so the client will want this back up and working asap.

**Comment by nlemoine** [comment]
Please read: https://github.com/timber/timber/discussions/2804

We're very sorry but we won't fix any Timber 1.x issues anymore. We're trying to get 2.0 out as soon as we can and encourage users to [migrate to Timber 2.x](https://timber.github.io/docs/v2/upgrade-guides/2.0/).

**Comment by tylersticka** [comment]
@josh-attwood I’ve shared a quick, hacky fix I found in the Automattic issue: https://github.com/Automattic/jetpack/issues/33284#issuecomment-1736405065

**Comment by josh-attwood** [comment]
Hi @nlemoine & @tylersticka, this is really quite frustrating. I understand time might be an issue but it seems problematic to stop fixing any major bugs in version 1 when Timber 2 isn't even ready for general release. We have quite a few sites running Timber and considering that there are many breaking changes it doesn't make sense financially for many sites to upgrade to Timber 2. It seems very unusual to totally drop any support and bug fixes at this stage and I am sure it will cause a lot of people issues! I am not really sure where that leaves us...

**Comment by tylersticka** [comment]
@josh-attwood I'm not a Timber maintainer, just thought I'd forward along my quick fix in case it helped you out. Apologies if it exacerbated your frustration.

We're in the same boat, and the situation _is_ frustrating: I was hoping support would continue until version 2.0 was out of the "release candidate" phase. But, this is free software, version 1.0 is nearly a decade old, WordPress has changed _a ton_ in that time, and many of the latest issues we've encountered arise from some fundamental conflicts between modern WordPress and Timber 1.x that are resolved in 2.x. So I can understand where the project's maintainers are coming from, too.

**Comment by nlemoine** [comment]
@josh-attwood Sorry, I forgot an important detail, the **plugin** 1.x version is dropped. That said, we all have limited time to spend on open source because it's unfortunately not financially sustainable 😉 We will consequently put all our efforts into releasing 2.0, officially. If you're willing to submit a PR to fix this, I'll be happy to review it and merge it, this is open source.

@tylersticka Thanks for understanding, that's why we're trying to make the path to Timber 2 as smooth as possible with detailed migration guides, whether you come from the plugin or the composer version. Give it a try! It's not that much a big leap.
