### ISSUE TITLE
v.2.x ACF Post object field group

### ISSUE THREAD

**Issue by mrfsrf** [timber/timber#2811]
### Actual behavior

In Timber v.2.x ACF Post object field group returns:
`WP_Post {#3128`

In order to use:
```twig
post.meta('example_field').link
post.meta('example_field').thumbnail.src('small')
```
one needs to query:
`{% set hero_post = get_post(post.meta('example_field').ID) %}`
OR
`{% set hero_post = post.convert(post.meta('example_field')) %}`
OR method which I am more fond of:
Change return type of the field to ID
```php
$example_field = get_field('example_field');
$context['hero_post'] = Timber::get_post($example_field);
```

to get:
`object(Timber\Post)#3091 (58)`
```twig
hero_post.link
hero_post.thumbnail.src('small')
```
### Expected Behavior

would be great to have same logic as in v.1.x
In version v.1.x you would get `Timber\Post` from `post.meta('example_field')` [post object ACF field]

### Steps to reproduce behavior

1. Create ACF Post filed group (returns Object)
2. dump(post.meta('example_field'))
3.
...

### What version of Timber are you using?

Timber 2RC1

### What version of WordPress are you using?

Wordpress 6.3.1

### What version of PHP are you using?

PHP 8.1

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Hi @mrfsrf ,

Thank you for taking the time to test the RC version. This behaviour is now op-in via this filter:

`add_filter( 'timber/meta/transform_value', '__return_true' );`

See: https://github.com/timber/timber/pull/2397#issuecomment-762963615
