### ISSUE TITLE
Hook timber/context is deprecated since version 2.0.0! Use timber/context instead.

### ISSUE THREAD

**Issue by philsbury** [timber/timber#2816]
### Expected Behavior

Not to be told new hook is deprecated

### Actual behavior

There is a persistent message that `timber/context` is deprecated and to use `timber/context` instead. I think this comes from Timber ln 1283:

```
/**
   * Filters the global Timber context.
   *
   * @deprecated 2.0.0, use `timber/context`
   */
  self::$context_cache = \apply_filters_deprecated(
      'timber/context',
      [self::$context_cache],
      '2.0.0',
      'timber/context'
  );
```

Should this not pass `timber_context` as the first param?

### Steps to reproduce behavior

Any `add_filter('timber/context')`  or usage of `Timber::context()`

### What version of Timber are you using?

2.0.0-rc.1

### What version of WordPress are you using?

6.3.1

### What version of PHP are you using?

8.2.7

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by gchtr** [comment]
Funny. When I look at the code, the first argument that is passed to `apply_filters_deprecated()` is `timber_context` and not `timber/context`:

https://github.com/timber/timber/blob/6ef7f6907f75db193382eb3beeefe6d5f4ffd396/src/Timber.php#L1283-L1288

If you see a persistent message it looks like something somewhere in your site is still using the `timber_context` filter. Could you check that?

**Comment by philsbury** [comment]
There's no usage of `timber_context` in my theme - did check before posting.

**But** after deleting `vendor` and reinstalling it now seems perfect. How very strange. Will close the issue. 

Thanks @gchtr
