### ISSUE TITLE
[BUG] Getting the size of the attachment doesn't work

### ISSUE THREAD

**Issue by thomasnavarro** [timber/timber#2819]
### Expected Behavior

When I use `Timber::get_attachment($image)`, I want to get the size of the file in MB and not in Bytes, unfortunately the conversion is not done.

### Actual behavior

Code :
```php
<a class="fileLink" href="{{ file.src }}" target="_blank" title="{{ __('Prévisualiser %s', 'interlude')|format(file.title) }}">
<span class="fileLink-extension pill">{{ file.extension|upper }}</span>
<span class="fileLink-title">{{ file.title }}</span>
<span class="fileLink-size">{{ file.size }}</span>
</a>
```

Render :
![Sans titre 2](https://github.com/timber/timber/assets/36193187/f65ea4ac-3c57-41b3-a139-1d29875a0541)

### Notes

For the moment the temporary solution is to do this in the twig: 
`{{ fn('size_format', file.size) }}`

### What version of Timber are you using?

2.0.0-rc.1

### What version of WordPress are you using?

WordPress 6.3.2

### What version of PHP are you using?

8.2

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by nlemoine** [comment]
Size are now returned as a raw value (see https://github.com/timber/timber/pull/2753).

If you want to format your value, use the `size_format` filter:
```twig
{{ file.size|size_format }}
```

This still needs to be documented, I'll update the docs soon.

**Comment by thomasnavarro** [comment]
Perfect, yes indeed, I had relied on the documentation.

Thank you!

**Comment by nlemoine** [comment]
@thomasnavarro It's documented now!
