### ISSUE TITLE
[BUG] Wordpress 6.4 not loading custom templates

### ISSUE THREAD

**Issue by kristjankoppel** [timber/timber#2837]
### Expected Behavior

Expected behavior is that templates load correctly

### Actual behavior

My sites updated to 6.4 and now all pages with custom template don't load template or anything. Even index post listing is not outputted. 

I've already tested everything and i don't know how to continue debugging this. I'm not doing anything crazy when loading timber templates - just the same as sample theme does it. 

There are no PHP error anything - just output is missing. Header and footer are there but nothing else.
Body tag is like that: <body class="home blog logged-in admin-bar no-customize-support lang-et"> 
Query monitor info is like this: https://jmp.sh/PhbkULt4 it shows that WP is falling back to front-page.php file and ignoring all page-blabla.php templates. 

Am i only one using timber and with this problem? 

Rolling back to wordpress 6.3 fixes this but then i'm stuck to 6.3 version and that is not good.

Is it something to do with "Improvements to Template Loading in WordPress 6.4" ?? 

How i even debug this if there is no errors and is there people with same error? 

### Steps to reproduce behavior

1. Use timber based theme
2. Update to wordpress 6.4
3. Update database for WP 6.4
4. Visite site and you'll see that custom templates are not loading

### What version of Timber are you using?

1.22

### What version of WordPress are you using?

wordpress 6.4

### What version of PHP are you using?

PHP 8 or PHP 7.4 still the same.

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by rmens** [comment]
Seems to work here. Timber 2.0r1, PHP 8.2, WP 6.4.

<img width="617" alt="Scherm­afbeelding 2023-11-08 om 10 57 04" src="https://github.com/timber/timber/assets/6742496/b753597e-dd54-4d49-842e-ac977c7bb01e">

**Comment by kristjankoppel** [comment]
Ofcource as i left one thing unnoticed - seems that Polylang Pro is the issue maker. 
Site where this was not installed works nice and on other sites turning Polylang Pro off and then on again made it work. 

I'll go and chat with Polylang Pro support.
