### ISSUE TITLE
Post.content and Gutenberg block attributes

### ISSUE THREAD

**Issue by thanhsst** [timber/timber#2841]
Hi,

How can I get a block align attribute in `{{post.content}}` ?

I want to have a fullwidth block and a paragraph with a `container` class wrapper, so I have created a group block using Gutenberg and set the align to fullwidth. Inside the group block,I have  another group block and a paragraph. The problem is that I cannot get the block align attribute.

I have used `parse_blocks($timber_post)`, but cannot see an align attribute from there. 

On the other hand, I have created a hero block via ACF, which I am able to retrieve the  block align attribute.

PHP: 

```
 function my_acf_block_render_callback( $block, $content = '', $is_preview = false ) {
    $context = Timber::context();

    $slug = str_replace( 'acf/', '', $block['name'] );

    // Store block values.
    $context['block'] = $block;

    // Store field values.
    $context['fields'] = get_fields();

    // Store $is_preview value.
    $context['is_preview'] = $is_preview;

    // Render the block.
    Timber::render( 'block/'.$slug.'.twig', $context );

}
```

HTML: 
`<div class="{{block.align == 'full' ? '' : 'container'}}">`

and it works. How can I have the same block align attribute of Gutenberg block without using ACF.

**Comment by Levdbas** [comment]
Hi @thanhsst ,

Your question has nothing to do with Timber and all with Gutenberg itself. Next time please only make an issue here when it's Timber specific.

You can use the following code for a wrapper element around specific blocks. You only need to add a check for the align wide/full attributes and add the blocks in the $list var.

```php
add_filter('render_block', function ($block_content, $block, $instance) {

   $list = ['core/paragraph', 'core/heading', 'core/list'];

   if (in_array($block['blockName'], $list)) {
      return '<div class="container">' . $block_content . '</div>';
   }

   return $block_content;
}, 10, 3);
```

Hope that helps, but I am going to close the issue here.
