### ISSUE TITLE
[BUG] LocationManager returns wrong locations in child themes

### ISSUE THREAD

**Issue by Levdbas** [timber/timber#2843]
### Expected Behavior

In 1.x child themes could overwrite twig templates. This functionality is now broken since 2.0:

**Expected array of  `Timber\LocationManager::get_locations` with child theme active**
```php
array(4) {
  [0]=>
  string(58) "redacted/themes/child-theme/"
  [1]=>
  string(74) "redacted/themes/child-theme/resources/views/"
  [2]=>
  string(52) "redacted/themes/parent-theme/"
  [3]=>
  string(68) "redacted/themes/parent-theme/resources/views/"
}
```

### Actual behavior

**actual array of  `Timber\LocationManager::get_locations` with child theme active**
```php
array(7) {
  [0]=>
  string(48) "redacted/themes/parent-theme"
  [1]=>
  string(54) "redacted/themes/child-theme"
  [2]=>
  string(0) ""
  [3]=>
  string(64) "redacted/themes/parent-theme/resources/views"
  [4]=>
  string(70) "redacted/themes/child-theme/resources/views"
  [5]=>
  string(64) "redacted/themes/parent-theme/resources/views"
  [6]=>
  string(64) "redacted/themes/parent-theme/resources/views"
}
```

Since `redacted/themes/parent-theme/resources/views` comes earlier then` redacted/themes/child-theme/resources/views` the parent theme has precedence over the child theme.

### Steps to reproduce behavior

1. make minimal parent/child setup where views live in subdir resources.
2. set timber location via `Timber::$dirname = 'resources/views';`
3. activate child theme and overwrite index.twig for example
4. make sure you can spot the difference between the two twig templates.

### Notes

I debugged it to the following rules:

```php
		$locs = array();
		$locs = array_merge($locs, self::get_locations_user());
		$locs = array_merge($locs, self::get_locations_caller($caller));
		//remove themes from caller (this is what missing in v2)
		$locs = array_diff($locs, self::get_locations_theme());
		$locs = array_merge($locs, self::get_locations_theme());
		$locs = array_merge($locs, self::get_locations_caller($caller));
		$locs = array_unique($locs);
		//now make sure theres a trailing slash on everything
		$locs = array_map('trailingslashit', $locs);
		$locs = apply_filters('timber_locations', $locs);
		$locs = apply_filters('timber/locations', $locs);
```
In v2 there is the following code, which has not the same effect.

```php
        //remove themes from caller
        $locs = \array_merge_recursive($locs, self::get_locations_theme());
```

I was able to fix it by adding 

```php    
 $locs = array_diff($locs, self::get_locations_theme());
```

When changing the test-timber-parent.php test and matching assets to point to the same document structure and also add `  Timber::$dirname = 'resources/views';` to the test `TestTimberParentChild::testParentChildGeneral` I got similar results.

### What version of Timber are you using?

2.0.0

### What version of WordPress are you using?

6.4

### What version of PHP are you using?

8.1

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by montagmorgens** [comment]
I can confirm the issue, but adding above line using `array_diff()` throws warnings (Array to string conversion), as – at least in our case – `$locs` can be a multidimensional array.

**Comment by palttamas** [comment]
The following seems to work for me, in `\Timber\LocationManager::get_locations`

```
//priority: user locations, caller (but not theme), child theme, parent theme, caller, open_basedir
$locs = [];
$locs = \array_merge_recursive($locs, self::get_locations_user());
$locs = \array_merge_recursive($locs, self::get_locations_caller($caller));

//remove themes from caller
--$locs = \array_merge_recursive($locs, self::get_locations_theme());
--$locs = \array_merge_recursive($locs, self::get_locations_caller($caller));
++$locs = array_diff($locs, self::get_locations_theme());
++$locs = array_merge_recursive($locs, self::get_locations_theme());

$locs = \array_merge_recursive($locs, self::get_locations_open_basedir());
$locs = \array_map('array_unique', $locs);

//now make sure theres a trailing slash on everything
$locs = \array_map(function ($loc) {
    return \array_map('trailingslashit', $loc);
}, $locs);
```
For a cleaner workaround, the `timber/locations` filter can be used, but it needs to override the `$locs` entirely, so much of the code from `get_locations` has to be copied over to the hook

**Comment by Levdbas** [comment]
Hi @palttamas ,

Good find! Are you interested to create a PR for this?

**Comment by palttamas** [comment]
@Levdbas I will give it a go this week.
