### ISSUE TITLE
[BUG] 2.x accessing more complex post meta ACF objects

### ISSUE THREAD

**Issue by alexgw** [timber/timber#2844]
### Expected Behavior

In either PHP or Twig we'd expect to be able to return objects from post meta where objects are set to return in advanced custom fields, at the moment the raw ids/database values are being returned. E.g

```php
$post = Timber::get_post();
echo '<pre>';
var_dump( $post) ;
var_dump( $post->meta('event_feed') ); // ACF Taxonomy field, set to return an Object
```
Would return the object not the ID. 

### Actual behavior

Instead the raw values are being returned. 

```php
$post = Timber::get_post();
echo '<pre>';
var_dump( $post) ;
var_dump( $post->meta('event_feed') ); // ACF Taxonomy field, set to return an Object, meta() returns the raw value
var_dump( $post->meta('featured_event') ); // ACF Post Object field, set to return an Object, meta() returns the raw value
```

```twig
{% set feed =  post.meta('event_feed') %}
Returns `2`, expected Timber\Term
```

Is the new 2.0 expected behaviour to have to add additional wrapping? 

e.g:

```twig
{% set feed =  Term(post.meta('event_feed')) %}
Returns Timber\Term
```

### Steps to reproduce behavior

See code examples above. 

ACF fields are an ACF Taxonomy field, set to return an Object

### What version of Timber are you using?

2.0

### What version of WordPress are you using?

6.4.1

### What version of PHP are you using?

8.1.23

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Hi Alex,

I think you will need the `$post->setup()` for the values in the PHP file and this: 

https://github.com/timber/timber/issues/2811 and https://github.com/timber/timber/pull/2397#issuecomment-762963615

This change was not very well documented in 2.0. If you would like to help us a hand and make a pr for the docs change, please feel free to do so.

**Comment by alexgw** [comment]
Hey @Levdbas,

Thanks for coming back - I've read through both those things  but I'm not sure I follow. We've tried with `$post-setup()` but it doesn't seem to change anything. 

Using the starter theme from introduction in the docs (I noticed the installation starter theme was different). We updated that to use 2.0 and then the case is still that:

ACF Group, Repeater, Post Object and Relationship *return the raw data*
Expecting Timber\Post or a collection, or the actual content from the ACF field you would get with get_field()
For example:

post.meta('category') will return 2 (the term ID)
post.meta('page') will return the post ID
post.meta('repeater') will return the number or rows added

index.php

```php

use Timber\Timber;

add_filter( 'timber/meta/transform_value', '__return_true' );

$context = Timber::context();

$post = Timber::get_post();
$post->setup();
$context['post'] = $post;
Timber::render( 'index.twig', $context );

```

index.twig

```html
<h1>A Timber Tutorial</h1>

<h3>Category (taxonomy)</h3>
{% set category = post.meta('category') %}
{{ dump(category) }}

<h3>Page (post object)</h3>
{% set page = post.meta('page') %}
{{ dump(page) }}

<h3>Pages (relationship)</h3>
{% set pages = post.meta('pages') %}
{{ dump(pages) }}
{% for item in pages %}
    <p>{{ item.title }}</p>
{% endfor %}

<h3>Repeater</h3>
{% set repeater = post.meta('repeater') %}
{{ dump(repeater) }}
{% for item in repeater %}
    <p>{{ item.title }}</p>
{% endfor %}

<h3>Group</h3>
{% set group = post.meta('group') %}
{{ dump(group) }}
<p>{{ group.title }}</p>

<div>{{ post.meta('rich_text') }}</div>

<pre>{{ dump(post.meta()) }}</pre>
```

Results in:
<img width="720" alt="Screenshot 2023-11-16 at 11 36 09" src="https://github.com/timber/timber/assets/4749089/c17e114d-6859-4931-b10a-0e52c0d66668">

I've attached the demo ACF for recreating it.
[acf-demo (1).json](https://github.com/timber/timber/files/13377121/acf-demo.1.json)

In the spirit of contributing I'd be happy to help with documentation if and when it works - looking at the codebase is the issue within the convert function in Core Entity.php? Dumping the object meta throughout this it seems like this is just returning the raw meta as opposed to converting it to an object as expected.

All the Best,
Alex

**Comment by alexgw** [comment]
To add a further comment from exploring here, some of these seem to be solved by wrapping the meta e.g:

```twig
{% set category = get_term(post.meta('category')) %}

{% set page = get_post(post.meta('page')) %}

{% set pages = post.meta('pages') %}

{% for item in get_posts(post.pages) %}  
```

This works for some things like terms, posts and collections of posts (e.g a relationship field) - is this now the expected pattern in v2.0? This adds a lot of refactoring to older codebases.

But it doesn't seem to work for repeaters or groups - is there a recommended method to access these?
e.g.:

```twig
{% set repeater = post.meta('repeater') %}
{% set group = post.meta('group') %}
```

All the Best,
Alex

**Comment by gchtr** [comment]
If the meta methods return raw data and repeater fields only return a count, that very much sounds like Timber didn’t set up its hooks. Can you confirm that you initialized Timber?

**functions.php**

```php
// Initialize Timber.
Timber\Timber::init();
```

**Comment by alexgw** [comment]
Hi @Levdbas and @gchtr 

Thanks for your responses to confirm that does seem to have been the issue but I'm not sure why it wasn't working properly, perhaps the order we had things in. 

We're now able to work on upgrading lots of sites to Timber 2.0 and PHP 8.2 which is great. Thanks for your help. 

All the Best,
Alex
