### ISSUE TITLE
[BUG] get_image failing for all instances of images accessed from ACF Pro latest release

### ISSUE THREAD

**Issue by mikehermary** [timber/timber#2848]
### Expected Behavior

I have been testing outputting images stored in ACF fields on the archive.twig template in Timber 2.0. The return format for the images tested were both Image ID. The output should display the images, but instead a fatal error is returned.

I have tested using a standalone image field and another nested within a repeater field.

### Actual behavior

When the page is rendered, Fatal error: Uncaught Twig\Error\SyntaxError: Unknown "get_image" function is displayed. The error is displayed on the archive and index twig templates.

### Steps to reproduce behavior

1. Create one or more image fields within an ACF field group
2. Use the suggested render format of `<img src="{{ get_image(post.meta('the_image')).src }}" />` to display the image on the page. This format comes from version 2 of the [documentation](https://timber.github.io/docs/v2/integrations/advanced-custom-fields/#image-field).
3. The fatal error is displayed in the browser.

### Notes

I am running WordPress on macOS Sonoma using MAMP Pro 6.8.1

With debugging enabled and using `{{ dump() }}`, numerous deprecated notices are displayed like the following Deprecated: Creation of dynamic property Timber\Post::$status is deprecated in /Users/michaelhermary/Web Development/Projects/Playground/wordpress-dev/wp-content/themes/timber-starter-theme/vendor/timber/timber/lib/Core.php on line 71. All seem to relate to line 71 of the same core.php file. I am not sure if this is related.

I am using the default timber-starter-theme

### What version of Timber are you using?

2.0

### What version of WordPress are you using?

6.4.1

### What version of PHP are you using?

8.2

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Hi @mikehermary , it seems that you have still version 1.x installed instead of 2. Because you have /lib/ in your path instead of /src/.
Please check your composer file and run composer update.

**Comment by mikehermary** [comment]
Hello @Levdbas, thanks for pointing that out. It just seems weird that I followed the [V2 installation documentation](https://timber.github.io/docs/v2/installation/installation/), yet V1 was installed. The installation was handled via Composer with no inclusion of the plugin in any way. This was all done on a fresh instance of WordPress.

Now, I am experiencing various fatal errors in the theme after running `composer update` and `composer update timber/timber`. Do I need to restart with a fresh V2 of the starter theme or should it be upgraded during the update process?

**Comment by Levdbas** [comment]
I think since you already had timber required in your starter theme, it did not automatically update to v2.

Regarding your fatal errors, the Timber starter theme has been updated with v2 as well. So you could manually update your own starter theme and learn all the ins and outs by doing the update manually or make a fast and clean start with the new timber starter theme. Please see the upgrade guide as well: https://timber.github.io/docs/v2/upgrade-guides/2.0/#initializing-timber

Let me know if this ticket can be closed!

**Comment by mikehermary** [comment]
Hello @Levdbas, thanks for clarifying. I will recreate the Timber installation via Composer and create a new project with the theme.

This ticket can be closed.
