### ISSUE TITLE
[BUG] Context empty in Wordpress Gutenberg blocks

### ISSUE THREAD

**Issue by expedition-jeffrey-tempelman** [timber/timber#2849]
### Expected Behavior

In the Wordpress full site editor we have blocks that show the navigation menu's. 
With the upgrade to Timber 2.0 via the composer packages the $context that is set in our timber.php and should provide us menu, options, theme and site in the context is empty. 

Instead the $context seems to be re-initialised with the data for that block and current post. Al other data from the timber.php is gone. 

timber.php example code:
 ```
$context['menu'] = Timber\Timber::get_menu();
        $context['topmenu'] = Timber\Timber::get_menu('top-menu');
        $context['primarymenumobile'] = Timber\Timber::get_menu('primary-menu-mobile');
        $context['primarymenudesktop'] = Timber\Timber::get_menu('primary-menu-desktop');
```

Navigation gutenberg block:
```
   $context = Timber::context();
            $context['attributes'] = $attributes;
            $context['block_attributes'] = get_block_wrapper_attributes();

            ob_start();
            Timber::render('blocks/heading.twig', $context);
            return ob_get_clean();
```

### Actual behavior

With the old plugin implementation we had the context from the timber.php available in out blocks. 
Now it seems te be loaded later than the blocks are rendered or it is not aware of the existing $context. 

### Steps to reproduce behavior

1.
2.
3.
...

### What version of Timber are you using?

2.0

### What version of WordPress are you using?

6.4

### What version of PHP are you using?

8.2

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Hi @expedition-jeffrey-tempelman 

I ran into this issue myself in Timber 1.x once. Also with ACF blocks and FSE. I think the issue was that the Timber::context() call is earlier called then your expansion of the `timber/context` in your timber.php file.

I did also test if this still occurs, but I have my full context available that is prepared via the `timber/context` filter in my theme.
