### ISSUE TITLE
[Docs] Contradictory instructions for `timber/twig` filter

### ISSUE THREAD

**Issue by wonkeythemonkey** [timber/timber#2851]
If a reader is searching for a method to add a custom filter to Twig, they may come across the [documentation for `timber/twig/filters`](https://timber.github.io/docs/v2/hooks/filters/#timber/twig/filters) in the Filter Hooks section there is no mention here of any deprecation.

Or they might be working through the Timber 2.0 migration guide, which says that [you shouldn't use that filter any more](https://timber.github.io/docs/v2/upgrade-guides/2.0/#updated-timber/twig-filters). It also directs readers to "Check out the new [Extending Twig Guide](https://timber.github.io/docs/v2/guides/extending-timber/) to learn more." There is a bug here: it links to the `Extending Timber` page instead of the `Extending Twig` guide.

If the reader manages to find the `Extending Twig` guide after all (it is linked from the `Extending Timber` page as well), they will find the following under [`Changing filters`](https://timber.github.io/docs/v2/guides/extending-twig/#changing-filters):

> You can replace a filter with your own function or even remove a filter by updating the array items in $filters.

> `add_filter('timber/twig/filters', function ($filters) {`

Which contradicts the information in the upgrade guide.

Then just below that is the following, under [Adding functionality with the Twig Environment filter](https://timber.github.io/docs/v2/guides/extending-twig/#adding-functionality-with-the-twig-environment-filter):

> You can still extend the directly with the timber/twig filter. The only disadvantage of this is that once functions or filters are added to Twig, the can’t be removed anymore.

> Here’s the same functions and filters that we add above. But instead of using timber/twig/functions and timber/twig/filters, we use timber/twig directly.

This suggests that while using `timber/twig` is an option, it's slightly worse than using `timber/twig/filters`.

I would submit a pull request myself to correct these inconsistencies, but I honestly don't know what the correct information should be.

**Comment by Levdbas** [comment]
Thank you for pointing this out @wonkeythemonkey.

@nlemoine , @gchtr , I see you both worked at this part of the codebase where these filters are provided. Can you chime in on this what filters are recommended in which case and how we can clear up the migration guide/twig guide?

**Comment by gchtr** [comment]
Ouch… I can see how this can be really confusing. I added an update to the Upgrade guide in #2855. Check it out here: https://github.com/timber/timber/blob/2.x-fix-twig-filters-info/docs/v2/upgrade-guides/2.0.md#updated-timbertwig-filters.

I’d be happy if you could review that. I hope it’s clear from the update what was updated and what you should use.

And I wonder whether the change in the Upgrade Guide clears up the whole confusion? Or are any other updates needed?

**Comment by wonkeythemonkey** [comment]
That's an improvement for sure, but I'm still confused by what it means to "extend the Twig environment" that doesn't include adding functions or filters. The examples shown on the [Extending Twig Guide](https://timber.github.io/docs/v2/guides/extending-twig/#adding-functionality-with-the-twig-environment-filter) are all adding filters and functions. How is that different from adding filters and functions with the other hooks?

Putting my question more succinctly:
If I want to add a custom filter to Twig in Timber, should I use `timber/twig` with `$twig->addFunction` or `timber/twig/functions` with `$functions['function_name'] =` ?

**Comment by gchtr** [comment]
Hey @wonkeythemonkey. I tried to improve the documentation here again: [`9bb2898` (#2855)](https://github.com/timber/timber/pull/2855/commits/9bb2898384fa9f6fe536c7d8e26c76b819c34ec1)

You can read all about what you can do with `Twig\Environment` in the official Twig documentation: https://twig.symfony.com/doc/3.x/advanced.html. You can also find some examples there. Apart from functions and filters, globals is one of the easier things you could make use of.

But the environment can also be used to create custom Twig Extensions or add your own Twig Tags.

> If I want to add a custom filter to Twig in Timber, should I use `timber/twig` with `$twig->addFunction` or `timber/twig/functions` with `$functions['function_name'] =` ?

You can still use both. Both ways are still valid. We found that using the `timber/twig/functions` filter might be a little easier. That’s why we added it.

Another reason is that when a function or filter is directly added to `\Twig\Enviroment`, it can’t be removed anymore. By using the `timber/twig/functions` filter, other developers could still remove or replace a function before it’s added to `\Twig\Environment`. This could be helpful if you have library or Timber integration adds its own functions or filters. That’s why using `timber/twig/functions` is our recommendation.

Tell me if that clears things up :).

**Comment by wonkeythemonkey** [comment]
That's much more helpful, thank you! With the new version, I feel like any difficulty I have understanding it is because the topic itself is nuanced, not because the documentation is confusing.

**Comment by gchtr** [comment]
@wonkeythemonkey Thanks for the feedback! 💚
