### ISSUE TITLE
Fatal error when get_posts with wrong ID in array

### ISSUE THREAD

**Issue by theamnesic** [timber/timber#2859]
### Expected Behavior

When using get_posts with array like this : `{% for item in get_posts( [ 1503, 543, 3220 ] ) %}`, Timber display posts and ignore if the ID doesn't exists.

### Actual behavior

Fatal error if an ID doesn't exists: 

`Fatal error: Uncaught Error: Call to a member function setup() on null in /Users/g/Sites/g/vendor/timber/timber/src/PostsIterator.php:49 Stack trace: #0 /Users/g/Sites/g/vendor/twig/twig/src/Environment.php(361) : eval()'d code(105): Timber\PostsIterator->current() #1`

### Steps to reproduce behavior

Loop with an array width `get_posts` with a wrong ID.

### What version of Timber are you using?

2.0.0

### What version of WordPress are you using?

6.4.1

### What version of PHP are you using?

8.1.13

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
I tried this myself and can confirm this behavior. `PostsIterator` seems not to like null posts.

**Comment by Levdbas** [comment]
Should be fixed by https://github.com/timber/timber/pull/2918
