### ISSUE TITLE
Overriding builtin WP_Nav_Menu_Widget menu output using Timber::get_menu()

### ISSUE THREAD

**Issue by mindfullsilence** [timber/timber#2861]
## Is your feature request related to a problem? Please describe.
As far as I can tell, there's no way to override the output of the Navigation Menu Widget built into WordPress to utilize Timber's menu and menu-item system. 

## Describe the solution you’d like
Quite honestly, I'm not even sure what the solution would be or if it's even possible considering the internals of WordPress' menu system - but it would be nice if we could use similar functionality as `Timber::get_menu` or hook into the `wp_nav_menu` or possibly `wp_nav_menu_object` to use Timber for rendering menus and menu items when displaying from a Navigation Menu Widget. This sounds like a stab in the dark because it is - WordPress' underlying menu logic is disgusting to work with/read through - so not sure what the best solution is TBH.

## Describe alternatives you’ve considered
Right now, I'm de-registering the built-in widget and registering a custom widget that simply extends the original class and overrides the `widget` method to use Timber for rendering out the menu. This is working for my needs, but tough to consider the long-term effects this will have as the site adds new plugins that effect how menus render. E.g. I'm not entirely sure if a plugin that overrides the Nav_Menu_Walker class will negatively impact the site in any way. 

## Additional context
This is perhaps out-of-scope for the goals of Timber, but I imagine the idea could be broadened to some mechanism of overriding any built-in widget to control its output ('widget_display_callback' filter comes to mind).

**Comment by Levdbas** [comment]
I think this is out of scope for Timber itself. You can create a widget/block yourself that uses your own navwalker function to create this kind of result.
