### ISSUE TITLE
[BUG] Cannot use Timber\Post::factory when extending Post class as the method is private

### ISSUE THREAD

**Issue by montagmorgens** [timber/timber#2873]
### Expected Behavior

When extending a Timber\Post, I should be able to access the factory() method. 

I'm trying to override the children() method which needs to have access to the factory.

### Actual behavior

Timber\Post::factory() is private and cannot be accessed by inhertitance.

### Steps to reproduce behavior

1. Create a class that extends Timber\Post
2. Try to access the factory method
3. It returns false instead of a PostFactory object.

### What version of Timber are you using?

Timber 2.0

### What version of WordPress are you using?

WordPress 6.4.2

### What version of PHP are you using?

PHP 8.1

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Related: https://github.com/timber/timber/issues/2813.

@nlemoine , could you chime in if @montagmorgens has a valid point or is there another recommended way to handle `children` overwrites.

**Comment by nlemoine** [comment]
@montagmorgens Can you provide more details on your use case? The factory is just meant to make post queries, I'd like to have more context before considering making `factory` protected.

**Comment by montagmorgens** [comment]
@nlemoine Our use case is to include children posts with post_status `private`. Since there's no filter hook which would allow us to change the query in the children() method, we tried to override the method.

**Comment by gchtr** [comment]
@montagmorgens Instead of using `$this->factory()`, you could probably use `Timber::get_posts()`  in your custom `children()` method as a quick fix.

**Before**

```php
return $this->factory()->from(\get_children($query));
```

**After**

```php
return Timber::get_posts(\get_children($query));
```

We could probably provide a better solution to update the query by using a filter or adding an optional parameter with query parameters that overwrite the default ones. A pull request would be welcome.
