### ISSUE TITLE
[BUG] $post->meta() dont load values of clone field type

### ISSUE THREAD

**Issue by fgdaniel** [timber/timber#2883]
### Expected Behavior

When use $post->meta('clone_field') need to get all values from that clone field type and their children like below

```php
array(
	'key' => 'value',
	'key2' => 'value2',
)
```

### Actual behavior

Now if we use $post->meta('clone_field') the returned value is null like below.

```php
NULL
```

### Steps to reproduce behavior

1. I just upgrade my timber 1.0 to 2.0 and i discovery this, i have several ACF groups who act as template schema for certain component with clone field by acf

### What version of Timber are you using?

2.0

### What version of WordPress are you using?

Wordpress 6.4.2

### What version of PHP are you using?

PHP 8.1.26

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by fgdaniel** [comment]
I discovered another bug, actually this bug is global, it doesn't take well the values of a field type group

I mean that any group type field has a number of children and they do not appear when you use $post->meta('field_group')

NULL is always returned to us, to overcome this aspect we must use $post->meta('GROUP_CHILDREN'), 'GROUP' means the name of the field, 'CHILDREN' means the name of the child in that group or simply to use acf function "get_field('field')"

**Comment by Levdbas** [comment]
Hi @fgdaniel ,

When creating a ACF field group for posts, add a group field named 'group', add a sub field named test, fill in the value and them in the index.php:

`
$timber_post = Timber::get_post();
var_dump($timber_post->meta('group'));
`

I do get the correct values of the sub fields. Do you run `Timber::init();` ?

I did not test your first question, but that might have the same cause. You could also post your code block where you try to get the value of the field in question so I can take a look at it.

**Comment by fgdaniel** [comment]
Hi @Levdbas 

Here is my entire code with comments

```php
<?php
/*
Template Name: eBooks - Template
 */
use Timber\Timber;

global $paged;
if ( ! isset($paged) || ! $paged) {
	$paged = 1;
}
$context          = Timber::context();
$post             = Timber::get_post();
$context['post']  = $post;
$context['posts'] = Timber::get_posts(array(
	'post_type'              => 'ebooks',
	'posts_per_page'         => 12,
	'paged'                  => $paged,
	'no_found_rows'          => false,
	'update_post_term_cache' => false,
	'update_post_meta_cache' => false,
));
$context['hero']  = $post->meta('hero'); // RETURN NULL
// $context['hero']  = get_field('hero'); // RETURN ALL FIELDS ON THIS GROUP

query_monitor_debug($post->meta('hero')); 
// RETURN NULL


query_monitor_debug(get_field('hero')); 
// RETURN Array
// (
//     [] => 
//     [titlu] => eBook-urile GoostoMix, ghidurile tale pentru sănătate
//     [descriere] => Un ajutorul nesperat de care ai nevoie în viața de zi cu zi și în momentele lipsite de inspirație. eBook-urile GoostoMix sunt un adevărat ajutor.
//     [background] => Array
//         (
//             [ID] => 12250
//             [id] => 12250
//             [title] => ebooks-jumbotron-bg
//             [filename] => ebooks-jumbotron-bg.jpg
//             [filesize] => 64066
//             [url] => https://dev.itup.ro/goostomix2/wp-content/uploads/2023/09/ebooks-jumbotron-bg.jpg
//             [link] => https://dev.itup.ro/goostomix2/ebooks/attachment/ebooks-jumbotron-bg/
//             [alt] => 
//             [author] => 1
//             [description] => 
//             [caption] => 
//             [name] => ebooks-jumbotron-bg
//             [status] => inherit
//             [uploaded_to] => 12116
//             [date] => 2023-09-11 08:29:45
//             [modified] => 2023-09-11 08:29:45
//             [menu_order] => 0
//             [mime_type] => image/jpeg
//             [type] => image
//             [subtype] => jpeg
//             [icon] => https://dev.itup.ro/goostomix2/wp-includes/images/media/default.png
//             [width] => 1088
//             [height] => 500
//             [sizes] => Array
//                 (
//                     [thumbnail] => https://dev.itup.ro/goostomix2/wp-content/uploads/2023/09/ebooks-jumbotron-bg-150x150.jpg
//                     [thumbnail-width] => 150
//                     [thumbnail-height] => 150
//                     [medium] => https://dev.itup.ro/goostomix2/wp-content/uploads/2023/09/ebooks-jumbotron-bg-300x138.jpg
//                     [medium-width] => 300
//                     [medium-height] => 138
//                     [medium_large] => https://dev.itup.ro/goostomix2/wp-content/uploads/2023/09/ebooks-jumbotron-bg-768x353.jpg
//                     [medium_large-width] => 768
//                     [medium_large-height] => 353
//                     [large] => https://dev.itup.ro/goostomix2/wp-content/uploads/2023/09/ebooks-jumbotron-bg-1024x471.jpg
//                     [large-width] => 1024
//                     [large-height] => 471
//                     [1536x1536] => https://dev.itup.ro/goostomix2/wp-content/uploads/2023/09/ebooks-jumbotron-bg.jpg
//                     [1536x1536-width] => 1088
//                     [1536x1536-height] => 500
//                     [2048x2048] => https://dev.itup.ro/goostomix2/wp-content/uploads/2023/09/ebooks-jumbotron-bg.jpg
//                     [2048x2048-width] => 1088
//                     [2048x2048-height] => 500
//                     [featured-image] => https://dev.itup.ro/goostomix2/wp-content/uploads/2023/09/ebooks-jumbotron-bg.jpg
//                     [featured-image-width] => 540
//                     [featured-image-height] => 248
//                 )

//         )

// )

Timber::render( 'archive/ebooks.twig', $context );
```

I attach some images for better understand

Image with query monitor logs: https://imgur.com/i2cRZ3t
Image with ACF Custom Fields details on Post Edit: https://imgur.com/Ccf2Fls
Image with eBook fields acf group: https://imgur.com/G3DA514
Image with Component Hero acf group: https://imgur.com/JafBSRh

On timber 1.0 when you call $post->meta('acf_field') who has several children fields the return value are an array with that specific childrens, now only NULL return,

Later edit: I create a group with name Group and a children text field with name Test and same result...

**Comment by fgdaniel** [comment]
OMG i was stupid, the problem was Timber\Timber::init(); i dont include it... RIP... now works fine..... i'M VERY SORRY FOR MY SUPPORT REQUEST... i know i'm stupid...
