### ISSUE TITLE
Escaping file extension (.twig) while including or extending a file.

### ISSUE THREAD

**Issue by bkrsmanovic** [timber/timber#2888]
### Expected Behavior

INFO: Reopen https://github.com/timber/timber/issues/933

Should take the file. Suppose I have a file called "default.twig" so {extends 'default'} should render the file. Currently it is throwing an load error. The similar functionality is provided in TwigBridge (Laravel) or CraftCMS

### Actual behavior

Throwing an error

### Steps to reproduce behavior

just include a file without .twig extension. It will throw Twig_Error_Load

### What version of Timber are you using?

2.x

### What version of WordPress are you using?

6.x

### What version of PHP are you using?

8.1

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Hi @bkrsmanovic , I understand where you are coming from but I think explicitly typing the full name including the extention is something we would always recommend. This causes less file lookups and thus faster execution. So I am not really a fan of implementing, in my opinion, bad practice as a possibility. Let me know what you think.

**Comment by bkrsmanovic** [comment]
@Levdbas I understand. Its not anything major, its just inconvenience and slight bother because of what you get used to. Just one of those things when ever I stumble upon error it earks a bit nothing else.
Keep up the good work! Timber is awesome :)

**Comment by Levdbas** [comment]
Thank you for your swift response @bkrsmanovic ! I understand that this might feel as bothersome, but hopefully the pro's of timber outweigh these little inconveniences :D If you run into anything else, don't hesitate to open another ticket!
