### ISSUE TITLE
[BUG] Your title

### ISSUE THREAD

**Issue by ecupaio** [timber/timber#2896]
### Expected Behavior

I have an ACF field group that I want to display the content of in a post: 
![Screenshot 2024-01-26 at 11 58 37 AM](https://github.com/timber/timber/assets/7784563/3cf70333-c6a7-4136-93ff-183a06a52bf3)
I would expect to use the Field Group slug to get the content from the post.meta as the docs state. Here is my code:
component
```
// accordion.twig
{% set accordion = post.meta('group_65b309ec1f699') %}
<section>
<div class="h2">{{ accordion.heading }}</div>
<div>{{ accordion.body }}</div>
{% for section in accordion.sections %}
<div>
  <details>
    <summary>{{ section.heading }}</summary>
    <div class="accordion-body">
      {{ section.body}}
    </div>
  </details>
</div>
{% endfor %}
</section> 
```
post
```
//single.twig
<article>
{% include 'components/basic-accordion.twig' %}
</article>
```
post content:
![Screenshot 2024-01-26 at 12 09 20 PM](https://github.com/timber/timber/assets/7784563/54f1a33a-70ae-426b-bcab-5a112a77e3d6)

### Actual behavior

However, I do not see the component displayed on the page. I added some static content to the component to make sure the component was included in the post template and it was, but none of the dynamic content was displayed in the post. 

### Steps to reproduce behavior

1. Create field group
2. Add post.meta('GROUP SLUG') to get content from field group in component
3. Include component on post template
4. Add content to post 
...

### What version of Timber are you using?

Timber 2.x

### What version of WordPress are you using?

Wordpres 6.4.2

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
As far as I know you are not able to get the content of a field group. However you can target the individual meta fields by using post.meta('heading') or post.meta('accordion') for example. I think you are mixing up the difference between the group of fields and the field type "group" which is basically a repeater field without the repeating feature.

Let me know if that helps.

**Comment by ecupaio** [comment]
not a mix up but more of a confusion. i started working on menu items first, where I had to call the menu that I defined in the index.php then get the individual fields but looks like it does that automatically within the context of the component. calling each individual field works! Thank you for your help @Levdbas

**Comment by ecupaio** [comment]
so this isn't [lost to the ancients](https://xkcd.com/979/),  here's the corrected code: 
```
{% set heading = post.meta('heading') %}
{% set body = post.meta('body') %}
{% set sections = post.meta('sections') %}
<section>
<div class="h2">{{ heading }}</div>
<div>{{ body }}</div>
{% for section in sections %}
<div>
  <details>
    <summary>{{ section.heading }}</summary>
    <div class="accordion-body">
      {{ section.body}}
    </div>
  </details>
</div>
{% endfor %}
</section>
```
