### ISSUE TITLE
[BUG] post.children doesn't work with custom post type

### ISSUE THREAD

**Issue by cbirdsong** [timber/timber#2911]
The "children" method of Timber/Post is not working with a custom post type.

### Expected Behavior

Using [the `children` method](https://timber.github.io/docs/v2/reference/timber-post/#children) on a Timber/Post object should allow me to loop through that post's children.

### Actual behavior

`post.children` contains an empty array on a hierarchical custom post type, but it works mostly like you'd expect on the `page` post type.

### Steps to reproduce behavior

Add a custom post type with children, and add some pages with children.

```php
$args = [
	"post_type" => "docs",
	"order" => "ASC",
	"orderby" => "menu_order",
	"post_parent" => 0,
	"posts_per_page" => -1,
];
$posts = Timber::get_posts($args);
$context["docs"] = $posts;
```

```twig
<ul>
	{% for post in docs %}
	<li>
		<span>{{ post.title }}</span>
		{% if post.children %}
			<ul>
			{% for child in post.children %}
				<li><span>{{ child.title }}</span></li>
			{% endfor %}
			</ul>
		{% endif %}	
	</li>
	{% endfor %}
</ul>
```

Using this code, I only get a single-level list of top-level posts. If I change `"post_type"` to `"page",` then I get children (mostly) as expected.

### Notes

Related observation: Changing the query to point at `page` causes `post.children` to include the page's attachments in the media library. This can be worked around by including `page` as an argument for `children()`, but is this expected?

### What version of Timber are you using?

2.0

### What version of WordPress are you using?

Wordpres 6.3

### What version of PHP are you using?

PHP 8.1

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Hi @cbirdsong ,

I just tested this locally with a custom post type and I got a list of the parent custom posts and its attached children. So not sure what is going wrong here. 

- Did you run Timber::init() in your functions?
- are there actual posts attached to parent posts?
- are the child posts published?

Hope that helps

**Comment by Levdbas** [comment]
@cbirdsong , could you let us know if you were able to fix this issue?

**Comment by cbirdsong** [comment]
I didn't fix it, I just worked around it. Digging in and trying to isolate the issue is on my list, but a lot of fires have come up in the last week and I haven't gotten back around to it!

**Comment by Levdbas** [comment]
Hi @cbirdsong ,

I am going to close this ticket until you have the time to provide us with some information so we can help you.
Just reply here and I will be glad to reopen the ticket for you.
