### ISSUE TITLE
Update Documentation for ACF Blocks

### ISSUE THREAD

**Issue by ecupaio** [timber/timber#2916]
## Is your feature request related to a problem? Please describe.
The [current documentation](https://timber.github.io/docs/v2/guides/gutenberg/) for implementing ACF Blocks in Timber shows how to use  the [acf_register_block function](https://www.advancedcustomfields.com/resources/acf_register_block_type/), but, as their docs suggest, developers should use the [block.json](https://www.advancedcustomfields.com/resources/acf-blocks-key-concepts/).  

## Describe the solution you’d like
Updating the [current docs](https://timber.github.io/docs/v2/guides/gutenberg/) with utilizing the block.json from ACF 6. 

## Describe alternatives you’ve considered
Accepting the wordpress community's lack of concise documentation and writing my own, but y'all do a pretty good job of explaining things.

## Additional context
I just created a solution by rendering a twig template within the block php template as shown in their [step-by-step guide](https://www.advancedcustomfields.com/resources/create-your-first-acf-block/), but I'm sure it needs refinement. I might create something in a week or so once I got it just right.

**Comment by Levdbas** [comment]
Hi @ecupaio ,

Would you like to take a shot at this and create a PR for changing the documentation regarding the ACF blocks?

**Comment by JacobPrice** [comment]
@ecupaio If you don't want to do it, let me know.  I have a lot of experience with ACF Blocks in Timber and have been looking for a way to start contributing!

**Comment by ecupaio** [comment]
> @ecupaio If you don't want to do it, let me know.  I have a lot of experience with ACF Blocks in Timber and have been looking for a way to start contributing!

I just got it down yesterday and was able to use some variables for a single php file solution, but a y notes or knowledge you have will be helpful. I'm coming to WordPress development after a long hiatus so your perspective will be very helpful.

I'm off for a few days but I'll open a PR and add you to it.

**Comment by Levdbas** [comment]
Nice collab going on here @ecupaio and @JacobPrice ! Both more then welcome to contribute and if you need any help along the way, just tag me :)

**Comment by JamieBradders** [comment]
Hello 👋 I just wanted to check to see if anyone needed assistance with this issue? I'm quite new to Timber, but feel pretty comfortable with it, and I've been working with my team to figure out an approach to using block.json in Timber. So, with that, I'm happy to help out whilst it's fresh in my brain 😂

**Comment by ecupaio** [comment]
@JamieBradders thanks for the assistance. I got distracted with paid-work but I'm more free now to pursue the docs. I'll post a PR soon and tag you to make contributions if you see a better way.

**Comment by JamieBradders** [comment]
No problem @ecupaio, I totally understand the challenge of juggling paid-work between open source! Thanks for your contribution and let me know if I can help in any way 🙂

**Comment by joworeiter** [comment]
@ecupaio would you tag me as well? I would love to see the way you implement block.json with ACF-Blocks and Timber, maybe I could give my 5cents to the docs.

**Comment by ecupaio** [comment]
@joworeiter absolutely. I am not primarily a wordpress dev so you will absolutely find a better way lol but I appreciate feedback. Just don't ask me why I did a certain thing. I barely know what I'm doing but I'm trying is the reason haha.

**Comment by ecupaio** [comment]
@joworeiter @JamieBradders @Levdbas @JacobPrice here y'all go: https://github.com/timber/timber/pull/2945

**Comment by Levdbas** [comment]
Hi @ecupaio , thank you for this! I've given some feedback in your pr. Let me know if you need any further assistance.
