### ISSUE TITLE
[BUG] pre_get_posts with post__not_in working? I'm having trouble excluding posts.

### ISSUE THREAD

**Issue by KingWebsites** [timber/timber#2928]
Excluding posts using pre_get_posts then using Timber::get_posts() on CPT archive page.

### Actual behavior

Post is not being excluded.

### Steps to reproduce behavior

My pre_get_posts function, excluding a post with ID of 19916:

```php
class CPT_Events
{
	public function __construct()
	{
		$this->hook_actions();
	}

	private function hook_actions()
	{
		add_action('pre_get_posts', array($this, 'exclude_highlighted_event'));
	}

	public function exclude_highlighted_event($query)
	{
		if ($query->is_main_query() && !is_admin() && is_post_type_archive('events'))
		{
			$query->set('post__not_in', array(19916)); // Excluding id 
			$query->set('posts_per_page', 2);
		}
	}
}
new CPT_Events();	
```

My archive-events.php:

```php
$context = Timber::context();	
$context['events'] = Timber::get_posts();	
Timber::render('archive-events.twig', $context);
```

My archive-events.twig template:

```twig
{% block content %}  	
	{% for event in events %}  	
		{{ event.id }} {{ event.title }}<br>  	
	{% endfor %}  	
{% endblock %}
```

Appearing on page, "posts_per_page" (set with pre_get_posts) working, "post__not_in" not working:

**19916** My event with the ID that shoudn't appear.  	
19897 An event that should appear.

### Notes

Not wanting to repeat a WP query I have tried to use pre_get_posts to exclude an event from the query results. The "posts_per_page" argument is working fine but the "post__not_in" doesn't seem to be working.

Am I doing something wrong or is this a bug in Timber?

### What version of Timber are you using?

Timber 2.0

### What version of WordPress are you using?

6.4.3

### What version of PHP are you using?

PHP 8.1

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by KingWebsites** [comment]
Just a quick additional note. The "post__not_in" works when applying the query to Timber::get_posts() in my archive-events.php

```php
$context['events'] = Timber::get_posts([
	'post_type' => 'events',
	'post_status' => 'publish',
	'posts_per_page' => 2,
	'post__not_in' => array(19916)
]);
```

**Comment by Levdbas** [comment]
Hi @KingWebsites , I think you are not using the default query by querying 

```
$context['events'] = Timber::get_posts([
	'post_type' => 'events',
	'post_status' => 'publish',
	'posts_per_page' => 2,
	'post__not_in' => array(19916)
]);
```

So your check $query->is_main_query() is false, since you are running an additional query which is not the main anymore.

https://timber.github.io/docs/v2/guides/context/#use-the-default-query states that you do not have to run a query yourself. Timber will then serve the default query under the `posts` key. I think then your code will work. See also https://timber.github.io/docs/v2/guides/context/#change-arguments-for-default-query

**Comment by KingWebsites** [comment]
Hi @Levdbas, thanks for responding. I think your comment raises a few things.

1. Thanks for letting me know I can change the default query arguments as I'm calling the Timber context.

2. I realise that running Timber::get_posts after this will result in a new query being run IF I add different arguments. That was my experiment as mentioned in my first comment to show that 'post__not_in' was working on a second query.

3. 'post__not_in' is still not working for me when changing the default query using pre_get_posts. All my other query changes work using pre_get_posts:

```php
$date_remove = date('Y-m-d');
$meta_query = array(
	'relation' => 'OR',
	array(
		'key' => 'start_date',
		'value' => $date_remove,
		'compare' => '>=',
		'type' => 'DATE'
	),
	array(
		'key' => 'end_date',
		'value' => $date_remove,
		'compare' => '>=',
		'type' => 'DATE'
	)
);
$query->set('post__not_in', array(19916));
$query->set('meta_query', $meta_query);
$query->set('orderby', 'meta_value_num');
$query->set('meta_key', 'start_date');
$query->set('order', 'ASC');
$query->set('ignore_custom_sort', true);
$query->set('posts_per_page', 6);
```
All of these arguments are changing the events that appear on my /archive-events/ apart from 'post__not_in'. I'm wondering if 'post__not_in' is a special case?

If anybody is using pre_get_posts to change a default query could they add a 'post__not_in' argument containing an array of their latest post ID to see if it's not working for them?

**Comment by KingWebsites** [comment]
Hi @Levdbas, using the merge_default method you mentioned above I have now got the 'post__not_in' argument to work, even if it doesn't work in 'pre_get_posts'.

So if I remove my 'pre_get_posts' 'post__not_in' query argument from my code directly above and place it as a merged argument it is fine, and all my other query arguments above still work.

Remove from 'pre_get_posts':
```php
$query->set('post__not_in', array(19916));
```

Add to archive-events.php:
```php
$context = Timber::context([
	'events' => Timber::get_posts(
		[
			'post__not_in' => array(19916),
		],
		[
			'merge_default' => true,
		]
	)
]);
```

This will solve the problem for the site I'm working on, whilst not having to run the query twice. I really appreciate you pointing me in the right direction.

But it does also leave a question of why 'post__not_in' is the only query argument that doesn't work using 'pre_get_posts', and whether that is a WP issue or a Timber issue. As I noted above it would be good to see if somebody else could quickly test if 'post__not_in' is being ignored in 'pre_get_posts' for them.

**Comment by Levdbas** [comment]
@KingWebsites, I got some time to test this but `post__not_in` does work for me in `pre_get_posts` It might have to do that you are running an additional query which it not the main query at that point. See https://timber.github.io/docs/v2/guides/posts/#the-default-query

Closing this for now, but if you have any other questions, let me know.

**Comment by KingWebsites** [comment]
Thanks for looking into this @Levdbas, I do appreciate it. I don't think I'm running an additional query. If I see this behaviour again on a new site I'll make a vanilla demo to see if I'm getting the same response as you on a CPT. 

But pointing me to the 'merge_default' settings was extremely valuable, to solve this problem and for some other pages I'm working on. Thanks.
