### ISSUE TITLE
V2 is awesome!

### ISSUE THREAD

**Issue by romainmenke** [timber/timber#2931]
_can be closed after reading_

I've spend the last couple of weeks updating ±70 sites to V2 and I am really happy with the direction of Timber.

I only encountered 1 minor bug, so that's great!

In general I found that Timber V2 is a bit less forgiving and more strict but also much more correct.

Thank you to all the contributors and maintainers 🙇

**Comment by Levdbas** [comment]
Thank you @romainmenke ! We are glad to hear that you like V2 and that the process of updating those 70 sites was fairly painless. Please make a bug report for that minor bug if you think its a global Timber bug. 

And glad to have you onboard on the Timber train!

**Comment by romainmenke** [comment]
Already submitted a patch for that issue here : https://github.com/timber/timber/pull/2905
(it isn't blocking for us because we can easily apply local patches for dependencies)

**Comment by Levdbas** [comment]
Just saw that @nlemoine merged this so this will be in the 2.1.0 release 👍

**Comment by romainmenke** [comment]
Thank you 🙇

**Comment by nlemoine** [comment]
Thanks @romainmenke for the kind comment :)

**Comment by gchtr** [comment]
This just made my day, thanks @romainmenke! 🎉
