### ISSUE TITLE
Setup GitHub Sponsoring

### ISSUE THREAD

**Issue by romainmenke** [timber/timber#2932]
We (work) only sponsor through GitHub sponsoring with the bulk sponsoring feature.
This allows us to sponsor most our dependencies with minimal effort.

We noticed that Timber doesn't have this set up.
Would it be possible to add this?

**Comment by Levdbas** [comment]
And thank you for this as well! @jarednova , this is your terrain. Is this something you can setup?

**Comment by jarednova** [comment]
yeah, thanks for the call-out @Levdbas — I'll look into it @romainmenke !

**Comment by jarednova** [comment]
Thanks again @romainmenke. I've sent over the requested paperwork to GitHub. Unfortunately it looks like it requires a bit of manual review from the GitHub team to validate our info. I'll report back once I have an update!

https://github.com/sponsors/timber/dashboard

**Comment by Levdbas** [comment]
Hi @jarednova , any progress from Githubs side?

**Comment by jarednova** [comment]
@Levdbas yeah for real, nothing. I submitted a ticket. Now it's been a year since submitting. Are you able to see ticket progress here ...?

https://support.github.com/ticket/personal/0/2831090

**Comment by Levdbas** [comment]
Unfortunately I do not have access to that. You'll probably need access on organisational level then.

**Comment by jarednova** [comment]
well, nothing to see at this point anyway! Maybe I'll give it another few days and then try making a ruckus on Twitter

**Comment by jarednova** [comment]
Finally, got a human! Things are now submitted for final approval. Here's the ✨ sparking new page ✨ that should launch soon ...
![Screenshot 2024-06-19 at 4 12 32 PM](https://github.com/timber/timber/assets/1298086/d8f2b1bd-ffec-475b-a1ef-02cec5345028)

**Comment by Levdbas** [comment]
Amazing @jarednova !

Updated https://github.com/timber/.github repo to feature the funding badge in all our repositories and removed Fundming.yml at Timber repo to inherit sponsorship settings from this repo as well.

**Comment by jarednova** [comment]
Just got word from GitHub support that things are officially live @Levdbas !

https://github.com/sponsors/timber

**Comment by Levdbas** [comment]
I saw the announcement in my GitHub feed indeed and went straight to work. Our org landing page now features the sponsorship as well: ![afbeelding](https://github.com/timber/timber/assets/17764157/374dd944-3540-43b6-bc06-10fdbdda5873)

**Comment by jarednova** [comment]
Living in the future!

**Comment by romainmenke** [comment]
Awesome!
This is now working on our end, which means that we can start sponsoring Timber together with our other deps :)

Thank you @jarednova for getting this set up!

<img width="713" alt="Screenshot 2024-06-25 at 11 19 09" src="https://github.com/timber/timber/assets/11521496/bf5bb607-757f-4db8-851a-f5d87b146608">


-----

_For us this is resolved, so issue can be closed_

**Comment by Levdbas** [comment]
Thanks for your support @romainmenke !
