### ISSUE TITLE
Security support

### ISSUE THREAD

**Issue by palmiak** [timber/timber#2938]
Inspired by https://github.com/timber/timber/issues/2936

Timber is missing dealing with security. I propose to:
- add "how to disclose vulnerabilities" - they shouldn't be public at first
- using https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/creating-a-repository-security-advisory
- adding docs regarding handling security

**Comment by Sonicrrrr** [comment]
Thank you for your response, I have followed the steps you outlined. However, regarding the vulnerability report in the issue section, I couldn't find a place to delete it

**Comment by gchtr** [comment]
I deleted the issue. Let’s continue working on the issue in the private security advisory.
