### ISSUE TITLE
Timber 1.x couldn't be updated because of missing patched versions in latest advisory

### ISSUE THREAD

**Issue by dennisenderink** [timber/timber#2971]
### Expected Behavior

Updating Timber 1.x (constraint at least `^1.0` / `~1.23.0` / `~1.24.0`) using Composer in combination with `roave/security-advisories` package should result in updating to patched versions `1.23.1` or `1.24.1` (depending on constraint).

### Actual behavior

Updating Timber 1.x results in a conflict with `roave/security-advisories` requiring version `>2.0.0`.

### Notes

This behavior is due to missing patched versions and/or wrong affected versions in the following advisory: https://github.com/timber/timber/security/advisories/GHSA-6363-v5m4-fvq3.

### What version of Timber are you using?

1.24.0

### What version of WordPress are you using?

6.5.2

### What version of PHP are you using?

8.1

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by gchtr** [comment]
I updated the affected and patched versions in the security advisory.

![Screenshot-Eejc1mrF-2024-04-16-11-15-01](https://github.com/timber/timber/assets/2084481/8114a644-76b5-4e5d-bac4-885c7d7a40d9)

I don’t know whether this change will be propagated to the different services that process the advisory. Otherwise we might have to create a new advisory, I guess?

**Comment by dennisenderink** [comment]
It's my understanding that the advisories are being build by GitHub Advisory Database among other things. I was hoping the following advisory would be updated with your change as well: https://github.com/advisories/GHSA-6363-v5m4-fvq3.

**Comment by dennisenderink** [comment]
I just submitted an improvement to the global advisory: https://github.com/github/advisory-database/pull/4272.

**Comment by gchtr** [comment]
> I just submitted an improvement to the global advisory: [github/advisory-database#4272](https://github.com/github/advisory-database/pull/4272).

Thanks for that! It looks like this is the way to go.

**Comment by dennisenderink** [comment]
Yes, it was approved and is merged now, `roave/security-advisories` has been updated as well! I'll close this issue now, thanks for your help. 👍

**Comment by gchtr** [comment]
@dennisenderink That’s great! Thanks to you as well for taking the time to look into this 🙌.

**Comment by eszarek** [comment]
https://github.com/advisories/GHSA-6363-v5m4-fvq3

Can't upgrade from plugin -> 1 ->2 being broken without uninstalling roave.

**Comment by eszarek** [comment]
https://github.com/advisories/GHSA-6363-v5m4-fvq3

Can't upgrade from plugin -> 1 ->2 being broken without uninstalling roave.
