### ISSUE TITLE
[BUG] Member has protected visibility

### ISSUE THREAD

**Issue by nestle49** [timber/timber#2973]
### Expected Behavior

Member has protected visibility

### Actual behavior

Member has protected visibility

### Steps to reproduce behavior

Include Timber 2.1 inside functions.php

1. // Load Composer dependencies.
require_once __DIR__ . '/vendor/autoload.php';

2. // Initialize Timber.
Timber\Timber::init();

I get error 'Member has protected visibility' with php 8.1

### What version of Timber are you using?

1.22.1

### What version of WordPress are you using?

WordPress 6.4

### What version of PHP are you using?

8.1

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Hi @nestle49 ,

does the theme you are running Timber in contain any classes that extend the Timber core classes? And can you also post where this error is exactly thrown?

**Comment by nestle49** [comment]
> Hi @nestle49 ,
> 
> does the theme you are running Timber in contain any classes that extend the Timber core classes? And can you also post where this error is exactly thrown?

I only include the two lines above in my function.php file

I took the theme from here https://underscores.me/ and didn’t change theme

Error in phpStorm line in including  Timber\Timber::init();

**Comment by Levdbas** [comment]
Hi @nestle49 , 

I've read that PHPstorm will sometimes report false positive notices about `Member has protected visibility`

See:
- https://youtrack.jetbrains.com/issue/WI-65245/Member-has-protected-visibility-inspection-bug-with-class-inheritance-and-instanceof
- https://youtrack.jetbrains.com/issue/WI-55618

Not sure if that's also the case with this though.

**Comment by gchtr** [comment]
I just tested and I get the same error if somewhere in my project Timber is installed with version 1. For example, if you still have an older theme with Timber in v1, you might see that error.

![](https://github.com/timber/timber/assets/2084481/cc7f8883-0510-436e-a16d-2b8d991eb592)

You can check the path that is displayed when you hover the error.

Or you can go to that declaration by pressing CMD and then click on `init()`, or place the cursor there and press CMD + B (see https://www.jetbrains.com/help/phpstorm/navigating-through-the-source-code.html#go_to_declaration). You can then see which while is opened.

If you remove Timber v1 from the project, then the error goes away. I’d say this is an issue with PHPStorm and not with Timber. That’s why I’m closing this.

**Comment by nestle49** [comment]
Yes, the plugin was indeed in the directory, but was disabled

Problem solved
