### ISSUE TITLE
question webp filter

### ISSUE THREAD

**Issue by nestle49** [timber/timber#2979]
### Expected Behavior

My code with version 1:

```
 public static function getTop(): array
    {
        $context['image'] = new Timber\Image(carbon_get_the_post_meta('image url in wordpress db or id);
        return $context;
    }
```

And next I can apply |towebp(100)

With version 2 I get error:

`If you send the constructor nothing it will try to figure out the current post id based on being inside The_Loop.`

I trying

`Timber::get_external_image(carbon_get_theme_option(self::LOGO));`

Is it right? Can I use towebp?

### Actual behavior

...

### Steps to reproduce behavior

1.
2.
3.
...

### What version of Timber are you using?

2.1

### How did you install Timber?

None

**Comment by Levdbas** [comment]
Hi @nestle49 

You need to use the `Timber::get_image()` since version 2.0

```php
$image_id = carbon_get_the_post_meta('image_field');
$context['image'] = Timber::get_image($image_id);
```
