### ISSUE TITLE
[BUG] Missing docs for Post::meta()

### ISSUE THREAD

**Issue by 75th** [timber/timber#2982]
### Expected Behavior

The [Timber\Post documentation page](https://timber.github.io/docs/v2/reference/timber-post/#meta) should document the `::meta()` method.

### Actual behavior

That documentation page makes no mention of it, except where the deprecated `::get_field()` method has a broken link to it.

### Steps to reproduce behavior

1. Read the Timber 2.x docs about Timber\Post
2. See that `::get_field()` is deprecated and links to the `::meta()` method.
3. Click the link and be taken to the top of the page instead of any documentation for `::meta()`.

### What version of Timber are you using?

Timber 2.x

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by gchtr** [comment]
@75th Thanks for posting this issue. This is something that I have noted for myself to fix after we moved the `meta()` methods from the different Timber objects to `Timber\CoreEntity`.

I just added an issue in our docs (https://github.com/timber/teak/issues/4) to handle this.

**Comment by Levdbas** [comment]
Now available via: https://timber.github.io/docs/v2/reference/timber-post/#meta
