### ISSUE TITLE
[BUG] Resized images look wrong

### ISSUE THREAD

**Issue by rmens** [timber/timber#2986]
### Expected Behavior

Resized images to not look squashed or stretched.

### Actual behavior

Resized images get squashed or stretched.

### Steps to reproduce behavior

1. Install WP 6.5
2. Install the Timber Starter Theme
3. Make a post with this image as thumbnail as example https://www.pexels.com/nl-nl/foto/zwart-en-wit-zwart-wit-vrouw-mevrouw-19501709/
4. Publish the post
5. Look at the post and you will see that the image looks very squashed or stretched

<img width="1254" alt="Scherm­afbeelding 2024-05-03 om 22 35 12" src="https://github.com/timber/timber/assets/6742496/e87018f7-8c38-41d5-8e08-1f63b8361fcd">
<img width="363" alt="Scherm­afbeelding 2024-05-03 om 22 34 54" src="https://github.com/timber/timber/assets/6742496/a8f023a9-fa5b-4d63-adf2-66080b52f725">

### Notes

Also happens in a theme that's not the Timber starter theme. To rule out any user error, I tested with the starter theme.

### What version of Timber are you using?

Timber 2.1.0

### What version of WordPress are you using?

WordPress 6.5.2

### What version of PHP are you using?

PHP 8.2

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by rmens** [comment]
Maybe relevant: PHP Version 8.2.18

<img width="955" alt="Scherm­afbeelding 2024-05-03 om 22 47 10" src="https://github.com/timber/timber/assets/6742496/ff1a70b6-d455-4d8e-b70d-1cd09d23804f">
<img width="948" alt="Scherm­afbeelding 2024-05-03 om 22 47 04" src="https://github.com/timber/timber/assets/6742496/dd7cda44-f723-4d6a-a9ce-0f47f227b147">

**Comment by Levdbas** [comment]
Thanks for your report @rmens, this only seems to occur when you don't set the third parameter in resize:

```twig
<img src="{{ post.thumbnail.src|resize(1200, 300, 'right') }}" />
```
leads to a correct image, although cropped from the right of the image.

The error seems to lie in this logic:
```php
        if (!$crop || $crop === 'default') {
            return [
                'x' => 0,
                'y' => 0,
                'src_w' => $src_w,
                'src_h' => $src_h,
                'target_w' => $w,
                'target_h' => $h,
            ];
        }
```
https://github.com/timber/timber/blob/2.x/src/Image/Operation/Resize.php#L20

which has been changed from the [1.x version](https://github.com/timber/timber/blob/1.x/lib/Image/Operation/Resize.php)

edit: 

removing `|| $crop === 'default')` from the linked block of code seems to fix the issue. That code of block is meant to force a image in a particular set of dimensions, not cropping it. Can you confirm that works for you as well @rmens ? 

This change was introduced in https://github.com/timber/timber/commit/18bf3586322a7bf829d5a246449a2c794f1e7862 to fix integration tests from what I can see,

**Comment by rmens** [comment]
Yes that works @Levdbas! It would be most logical to default to a center crop when a third parameter isn't specified. Alternatively, we could update the documentation to mandate a third parameter for resizing, although that may not be the most practical solution.

**Comment by gchtr** [comment]
To me, this sounds like a bug if it changed from how it used to be in v1.

I would first fix the issue and then we could also discuss whether changing the default would make sense. But that would be a breaking change for which we have to provide the proper upgrade information.

So, I’m wondering, rather than removing `|| $crop === 'default')`, shouldn’t it be `|| $crop === null)`? Because the way I read the code, the default value for `$crop` is `null` when not provided.

**Comment by rmens** [comment]
I’m wonder what the default behavior in 1.x was. That was probably center cropping and not top right cropping.

**Comment by Levdbas** [comment]
```php
$dest_ratio = $w / $h;
$src_wt = $src_h * $dest_ratio;
$src_ht = $src_w / $dest_ratio;
$src_x = $src_w / 2 - $src_wt / 2;
$src_y = ($src_h - $src_ht) / 6;
```

Well this was the default behaviour in 1.x and should have also been de the default behavior in 2.x were it not for the shortcircuit bug that was introduced.

What this exactly does however is kinda hard to wrap my head around :D This could use some documentation. Its is also kind of strange that you can pass a `default` option but that is not an actual option in the codebase that runs something explicitly. It just prevents the running of a specific crop behaviour.

**Comment by rmens** [comment]
According to ChatGPT it's a center-ish crop

> **$dest_ratio = $w / $h;**
> This line calculates the aspect ratio of the desired output image, where $w is the width and $h is the height that you want the cropped image to have. The aspect ratio is the ratio of width to height.

> **$src_wt = $src_h * $dest_ratio**;
> This line calculates the width of the crop area from the source image. It uses the height of the source image ($src_h) and multiplies it by the desired aspect ratio ($dest_ratio). This ensures that the width of the crop area maintains the aspect ratio of the target image dimensions.

> **$src_ht = $src_w / $dest_ratio;**
> Here, the height of the crop area is calculated using the width of the source image ($src_w) divided by the desired aspect ratio. This also helps in maintaining the aspect ratio consistency with the target dimensions.

> **$src_x = $src_w / 2 - $src_wt / 2;**
> This line determines the horizontal starting point ($src_x) of the crop area. It centers the crop area horizontally within the source image. It does this by taking half of the source width ($src_w / 2) and subtracting half of the calculated crop width ($src_wt / 2).

> **$src_y = ($src_h - $src_ht) / 6;**
> Finally, this line calculates the vertical starting point ($src_y) of the crop area. The formula takes the difference between the source height and the crop height, subtracts it from the source height, and then divides by 6. This is a somewhat unusual choice and suggests that the crop area is intended to be closer to the top of the image rather than being perfectly centered vertically.

**Comment by gchtr** [comment]
I remember that Jared once mentioned that the default crop is not fully from the top, but in the upper part of the image. This is a cropping area that works well in a lot of cases, and mostly works better than just a top or center crop.

**Comment by rmens** [comment]
When I was still using 1.x without an off-site image resizer (which lead to not seeing this bug with the upgrade to 2.x of my theme) the crops always looked good. So cropping from the upper part of the image seems to be good choice imho. Documenting that behavior would be a win.
