### ISSUE TITLE
[BUG] Unknown variable $block in `my_acf_block_render_callback`; wrong variable used in the docs.

### ISSUE THREAD

**Issue by baglio** [timber/timber#2988]
### Expected Behavior

Expect the `my_acf_block_render_callback` function to rendere ACF blocks.

### Actual behavior

Unknown $block variable.

### Steps to reproduce behavior

1. Follow the [Block Editor Gutenberg](https://timber.github.io/docs/v2/guides/gutenberg/) section in the docs.

### Notes

You should replace the **$block['name']** variable name in the `my_acf_block_render_callback` with **$attributes** like so:

```
function my_acf_block_render_callback($attributes, $content = '', $is_preview = false, $post_id = 0, $wp_block = null) {
    // Create the slug of the block using the name property in the block.json.
    $slug = str_replace( 'acf/', '', $attributes['name'] );

    $context = Timber::context();

    // Store block attributes.
    $context['attributes'] = $attributes;

    // Store field values. These are the fields from your ACF field group for the block.
    $context['fields'] = get_fields();

    // Store whether the block is being rendered in the editor or on the frontend.
    $context['is_preview'] = $is_preview;

    // Render the block.
    Timber::render(
        'blocks/' . $slug . '/' . $slug . '.twig',
        $context
    );
}
```

### What version of Timber are you using?

2.x

### What version of WordPress are you using?

6.5.2

### What version of PHP are you using?

php 8.2.10

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Good find @baglio ! Would you like to make a PR for this yourself?

**Comment by baglio** [comment]
> Good find @baglio ! Would you like to make a PR for this yourself?

Sure, thank you. Beware, though, that is my first PR. 😅

**Comment by Levdbas** [comment]
@baglio . amazing! Let me know if you need any help!

**Comment by baglio** [comment]
@Levdbas I opened the request... hopefully in the correct way.

Thank you for your support.
