### ISSUE TITLE
[BUG] No Timber Post object when invalid slug is called

### ISSUE THREAD

**Issue by Luckyfella73** [timber/timber#2989]
### Expected Behavior

I would expect that a Timber/Post object (having the methods like `->meta`) exists even when calling a page that does not exist.

### Actual behavior

I get a warning finally resulting in a fatal error in an other step of my code when calling an URL with a non existing slug - there is no Timber Post at all.

### Steps to reproduce behavior

in my controller if have this lines (reduced to the involved lines here):

**Producing PHP Warnings**
`Warning: Undefined array key "post"`
`Warning: Attempt to read property "meta" on null`
`Warning: Trying to access array offset on value of type null`

```PHP
$data = Timber::context();

$mediastage_slider_items = (int)$data['post']->meta['mediastage_slider_items'];
if ( $mediastage_slider_items > 0) {
    $data['has_mediastage'] = true;
}
```
And further methods working with the Timber Post Obejct / $data['post'] like:

**Producing a PHP Fatal Error**
`Fatal error: Uncaught Error: Call to a member function meta() on null`

```PHP
private function get_page_template_name( $post_object ) // here I pass: $data['post'] 
{
	$post_meta_data = $post_object->meta();

	if ( isset( $post_meta_data['_wp_page_template'] ) && strlen( $post_meta_data['_wp_page_template'] ) > 0 )
	{
		return $post_meta_data['_wp_page_template'];
	}
	else
	{
		return FALSE;
	}
}
```

### Notes

Correct me if I'm wrong but I think Timber 1.x didn't produce this issue.

### What version of Timber are you using?

2.1

### What version of WordPress are you using?

6.5.2

### What version of PHP are you using?

8.1

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Hi @Luckyfella73,

Timber 2 does return null instead of an empty Post object when no post is found. We recommend firmer checking in your codebase.

```php
$mediastage_slider_items = isset($data['post']->meta['mediastage_slider_items']) ? $data['post']->meta['mediastage_slider_items'] : false;
```

Same for your `get_page_template_name` method.

```php
private function get_page_template_name( $post_object ) // here I pass: $data['post'] 
{
        if (null == $post_object) {
           return false;
        }

	$post_meta_data = $post_object->meta();

	if ( isset( $post_meta_data['_wp_page_template'] ) && strlen( $post_meta_data['_wp_page_template'] ) > 0 )
	{
		return $post_meta_data['_wp_page_template'];
	}
	else
	{
		return FALSE;
	}
}
```

Hope that answers your question!

**Comment by Luckyfella73** [comment]
Ah ok - good to know that this is intended to be like this :) I'm going to check for existence of the post object than like you suggested. Thank you for answering that fast!
