### ISSUE TITLE
: [ Timber ] Timber::get_post() was called

### ISSUE THREAD

**Issue by nestle49** [timber/timber#2992]
### Expected Behavior

: [ Timber ] Timber::get_post() was called

incorrectly
. Getting a post by post slug or post name was removed from Timber::get_post() in Timber 2.0. Use Timber::get_post_by() instead. Please see Debugging in WordPress (https://wordpress.org/support/article/debugging-in-wordpress/) as well as Debugging in Timber (https://timber.github.io/docs/v2/guides/debugging/) for more information. (This message was added in Timber version 2.0.0.) in
/var/www/data/public/wp-content/themes/vrwatch/vendor/timber/timber/src/Helper.php
on line
400

### Actual behavior

W

### Steps to reproduce behavior

When I get image that was not downloaded and `Timber::get_image(carbon_get_the_post_meta('site_image')`

### What version of Timber are you using?

2.1

### What version of WordPress are you using?

WordPress 6.4

### What version of PHP are you using?

8.1

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by nestle49** [comment]
Also must be define( 'WP_DEBUG', true );

Problem `Timber::get_image(''`) with empty string parameter (image was not loaded)

**Comment by Levdbas** [comment]
Hi @nestle49,

Thank you for your report.

![afbeelding](https://github.com/timber/timber/assets/17764157/166d2734-db13-48a1-952c-a4a2d61a01c6)
@timber/rangers , adding a check on empty strings in get_post, would that be something we could add?

**Comment by gchtr** [comment]
@Levdbas If we move towards introducing more types, a string will not be something we will accept for `Timber::get_post()`. The function will throw an error then.

@nestle49 I’d say that you will have to check what you pass to `Timber::get_image()` first and don’t call `Timber::get_image()` if you only have an empty string.

```php
$site_image = carbon_get_the_post_meta('site_image');

if ( $site_image ) {
	Timber::get_image( $site_image );
}
```

In version 1 of Timber, it was possible to use a string for `Timber::get_post()`, and Timber would try to fetch a post by title or slug. In Timber 2, we moved that to the `Timber::get_post_by()` function. That’s why you see the error message.

In my view, this is all how it’s supposed to work and not a bug or something we will have to improve.

**Comment by Levdbas** [comment]
@gchtr , agreed about the stricter typing and the checks you'll have to do in your own codebase.

Only thing that is a bit counter intuitive is that for the get_image method you'll get an error involving get_post. The first time I encountered this I was struggling to find were the error came from.

**Comment by gchtr** [comment]
> Only thing that is a bit counter intuitive is that for the get_image method you'll get an error involving get_post. The first time I encountered this I was struggling to find were the error came from.

True that. We could copy the warnings over to `Timber::get_image()`, I guess.

**Comment by nestle49** [comment]
> @nestle49 I’d say that you will have to check what you pass to `Timber::get_image()` first and don’t call `Timber::get_image()` if you only have an empty string.

Yes that's what I'm doing now

The problem is that there are a huge number of such places in the code, and I think it would be more correct to deal with this inside the package, which will significantly reduce the amount of code in the project. Instead of having to check thousands of images in a project, you can check once inside a function. Which is logical, if you pass empty to get_image(), there is no image, it is logical to return an empty string or null, any type castable to false

The second problem I see is that the warning is not an error and is not explicit, that is, as you said above, instead of being told that an empty string was passed to the function, I received an unrelated message and had to debug the whole page before that I understood what the matter was, and what was my surprise when the reason did not find anything in common with the message about error

**Comment by nestle49** [comment]
Also I get same error when I trying get thumbnail

```
$devices = [];
foreach ($devicesIds as $deviceId) {
	if (get_the_post_thumbnail($deviceId['id'])) {
		$device['image'] =  Timber::get_image(get_the_post_thumbnail($deviceId['id']));
	}
	$devices[] = $device;
}
```

Also I tried use `get_the_post_thumbnail_url`

There is an error even if I add a condition

`var_dump(get_the_post_thumbnail($deviceId['id']))` result:

![202405](https://github.com/timber/timber/assets/15983233/840efddc-f6c0-44fd-b3d0-37de9991f178)

**Comment by Levdbas** [comment]
@nestle49 ,

 get_the_post_thumbnail()

Returns a string. You are probably looking for get_post_thumbnail_id() to get a queryable image.

**Comment by gchtr** [comment]
> I think it would be more correct to deal with this inside the package, which will significantly reduce the amount of code in the project.

It might reduce the code in your project and it might be more convenient for you. But if we just accept any type of parameter in our functions and add the relevant checks for it ourselves, then that will make it harder to use static analysis tools, which a lot of developers rely on. It will only make development harder for us library maintainers and introduce more bugs that are hard to predict.

If we can make use of the error handling that is provided by PHP itself (by only allowing certain types), then we should use that and not add our own error handling.

In general, you’re responsible for passing a function parameter with the right type and doing the proper checks beforehand.

> Instead of having to check thousands of images in a project, you can check once inside a function.

In this case, you could **add your own function** that calls `get_post_thumbnail_id()` and converts an empty string to a parameter, that works fine with `Timber::get_image()`.

> The second problem I see is that the warning is not an error and is not explicit, that is, as you said above, instead of being told that an empty string was passed to the function, I received an unrelated message and had to debug the whole page before that I understood what the matter was, and what was my surprise when the reason did not find anything in common with the message about error

Yes, we can see that. I made a pull request to improve the error messages: https://github.com/timber/timber/pull/2999.
