### ISSUE TITLE
[BUG] Missing Doc for `convert_wp_object` method

### ISSUE THREAD

**Issue by mrfsrf** [timber/timber#3004]
### Expected Behavior

Run into situation where i needed to convert the array of `WP_Post` obj to Array of `Timber\Post` obj and was looking for simple solution. Didn't find any on Timber official documentation under 2.x. tag.
That's why i started to dig inside source code and found method under Helper Class `convert_wp_object`

Was the documentation about that method deliberately left out?

Since I'm i prototype stage, the solution is pretty cheap:
```php
$query_args = array(
    's'              => $search_query,
    'paged'          => $paged,
    'posts_per_page' => $posts_per_page,
    'post_type'      => $post_types,
    'post_status'    => 'publish',
    'orderby'        => 'relevance',
);

$wp_query = new WP_Query($query_args);
$wp_posts = $wp_query->posts;

foreach($wp_posts as $wp_post) {
  $timber_posts[] = Timber\Helper::convert_wp_object($wp_post);
}
$context['posts'] = $timber_posts;
```
Is there a more elegant way to achieve that?
Keep in mind that im using Algolia with following option: `Use Algolia with the native WordPress search template`
which hijacks the wp search feature and returns the array of `WP_Post` obj.

### Actual behavior

Serch official documentation and find the solution to the problem. For the problem in question: a way to convert WP_Post obj to Timber\Post obj :)

### Steps to reproduce behavior

1.
2.
3.
...

### What version of Timber are you using?

Timbe 2.2.

### What version of WordPress are you using?

Wordpress 6.5

### What version of PHP are you using?

PHP 8.2

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Hi @mrfsrf , thanks for your report. The method was not marked as an `@api` method and thus not being processed by our documentation software that looks for that tag. I just created a PR for that to work.
