### ISSUE TITLE
Spaceless tag don't remove spaces

### ISSUE THREAD

**Issue by nestle49** [timber/timber#3007]
### Expected Behavior

I use

```
{% apply spaceless %}
        <title>title1</title>
        <title>title2</title>
        <title>title3</title>
{% endapply %}
```
And I get

```
        <title>title1</title>
        <title>title2</title>
        <title>title3</title>
```

But I Want

`<title>title1</title<title>title2</title><title>title3</title>`

### Actual behavior

This worked in the first version with the tag, but it doesn't work that way in the second version with the filter. What's wrong with this functionality? How can I achieve what I expect?

### Steps to reproduce behavior

1. Use spaceless

### What version of Timber are you using?

2.1

### What version of WordPress are you using?

WordPress 6.4

### What version of PHP are you using?

8.1

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Hi @nestle49 ,

I tried to reproduce your issue in Timber 2.2 but I can't duplicate your behaviour:

`<h1>title1</h1><h1>title2</h1><h1>title3</h1>`

Is what I get running

```twig     
{% apply spaceless %}
<h1>title1</h1>
<h1>title2</h1>
<h1>title3</h1>
{% endapply %}
```

How do you inspect the source code?

**Comment by nestle49** [comment]
> Hi @nestle49 ,
> 
> I tried to reproduce your issue in Timber 2.2 but I can't duplicate your behaviour:
> 
> `<h1>title1</h1><h1>title2</h1><h1>title3</h1>`
> 
> Is what I get running
> 
> ```
> {% apply spaceless %}
> <h1>title1</h1>
> <h1>title2</h1>
> <h1>title3</h1>
> {% endapply %}
> ```
> 
> How do you inspect the source code?

Inside devtools

I found at the docs that is bad idea use it for minify html, but I didn't found why

Early this functional was used for minify open graph markup, twitter markup and seo tags

**Comment by Levdbas** [comment]
Check your page source instead and see how its rendered over there. Devtools might auto align your code.

**Comment by Levdbas** [comment]
Was that the fix @nestle49 ?

**Comment by nestle49** [comment]
Yes ths

**Comment by nestle49** [comment]
> Was that the fix @nestle49 ?

@Levdbas 

Here is an example that does not remove spaces, regardless of whether I place the tag inside or outside

```
{% apply spaceless %}
    <script type="application/ld+json">
        {
            "@context": "https://schema.org",
            "@graph": [
                {
                    "@type": "WebPage",
                    "url": "{{- canonical -}}",
                    "name": "{{- title|shortcodes -}}",
                    "description": "{{- description|shortcodes -}}",
                    "@id": "{{- canonical -}}#webpage",
                    "isPartOf": {
                        "@id": "https://site.com/#website"
                    },
                    "datePublished": "{{- jsonLD.datePublished -}}",
                    "dateModified": "{{- jsonLD.dateModified -}}",
                    "inLanguage": "en-US",
                    "potentialAction": [
                        {
                            "@type": "ReadAction",
                            "target": [
                                "{{- canonical -}}"
                            ]
                        }
                    ],
                    "breadcrumb": {
                        "@id": "{{- canonical -}}#breadcrumb"
                    },
                    "mainEntity": [
                        {
                            "@type": "ItemList",
                            "name": "{{- jsonLD.topSites.title -}}",
                            "itemListElement": [
                                {% for site in jsonLD.topSites.sites %}
                                {
                                    "@type": "Website",
                                    "name": "{{- site.title -}}",
                                    "url": "{{- site.permalink -}}",
                                    "image": "{{- site.image.src -}}",
                                    "description": "{{- site.text|striptags -}}"
                                }{{ not loop.last ? ',' }}
                                {% endfor %}
                            ]
                        },
                    ]
                },
            ]
        }
    </script>
{% endapply %}
```

**Comment by gchtr** [comment]
@nestle49 It looks like you want to use the spaceless tag to minify the output. That is specifically what it is **not meant to be used for**:

> This tag is not meant to "optimize" the size of the generated HTML content but merely to avoid extra whitespace between HTML tags to avoid browser rendering quirks under some circumstances.
>
> If you want to optimize the size of the generated HTML content, gzip compress the output instead.
>
> If you want to create a tag that actually removes all extra whitespace in an HTML string, be warned that this is not as easy as it seems to be (think of textarea or pre tags for instance). Using a third-party library like Tidy is probably a better idea.
>
> – from the [spaceless documentation](https://twig.symfony.com/doc/2.x/filters/spaceless.html#:~:text=This%20tag%20is%20not%20meant%20to%20%22optimize%22%20the%20size%20of%20the%20generated%20HTML%20content%20but%20merely%20to%20avoid%20extra%20whitespace%20between%20HTML%20tags%20to%20avoid%20browser%20rendering%20quirks%20under%20some%20circumstances).

Because this is more of a Twig related question, this not something that we can you help you with, because we don’t provide support for Twig itself.

**Comment by nestle49** [comment]
Thank you! It's solution
