### ISSUE TITLE
ISO8601 DATE

### ISSUE THREAD

**Issue by nestle49** [timber/timber#3009]
I get post date `get_the_modified_date( 'c' );`

It gives `2024-06-06T02:54:30+03:00`
But I need `2024-06-06T02:54:30.000Z`

Can Timber help me?

**Comment by Levdbas** [comment]
Try [these answers](https://stackoverflow.com/a/68651948) and next time, do not skip the issue template. When you have questions and not bugs, please post them in https://github.com/timber/timber/discussions
