### ISSUE TITLE
Namespace variables, functions, ... exposed to twig

### ISSUE THREAD

**Issue by romainmenke** [timber/timber#3017]
## Is your feature request related to a problem? Please describe.

Any variable added to `context` or any function, ... might conflict with author defined variables, functions, ...

So any change or addition implies a potential breaking change for users.

## Describe the solution you’d like

Namespace all things that Timber exposes to Twig.

## Describe alternatives you’ve considered

N/A

## Additional context

`foo.twig` :

```twig
{{ user }}
```

`user` is a string with value `bar`:

```twig
{% include 'foo.twig' with { user: 'bar' } %}
```

`user` is the actual WP user:

```twig
{% include 'foo.twig' %}
```

**Comment by nlemoine** [comment]
Hi @romainmenke,

This is not a bug, it's default Twig behavior and more a code practice we would like to improve in the future.

One general advice about includes and variable scope management: (almost) never inherit the global variable scope. Otherwise, you increase the chances to encounter variable name conflicts. 

```twig
{# ❌ Bad #}
{% include 'foo.twig' with { user: 'bar' } %}

{# ✅ Good #}
{% include 'foo.twig' with { user: 'bar' } only %}
```

This way, you have more control hover the available variables in your template scope.

**Comment by romainmenke** [comment]
I know it is not a bug :)
I submitted it as a feature request, potentially for a future version.

It is true that there is a higher chance of conflicts when omitting `only` but letting variables "cascade" down also has benefits.

However stating that using `only` is a best practice doesn't change the breaking nature of adding new global variables in `Timber` :)

Using namespacing is a well known strategy to avoid these types of issues.

**Comment by nlemoine** [comment]
> but letting variables "cascade" down also has benefits.

The drawbacks are far more important than the benefits it provides, IMHO. I would strongly advocate against this. You wouldn't imagine doing the same on the PHP side (e.g. having each declared variables global). It may work at small scale but will quickly turn into a nightmare at larger scale when you have dozens of nested templates.

> However stating that using only is a best practice doesn't change the breaking nature of adding new global variables in Timber :)

Timber does not add any global variable (which is done with `$twig->addGlobal('key', 'value')` in Twig). Timber only "pollutes" the **context** of your rendered template (context ≠ global). A context that you can **choose** to cascade, or not, to your includes using `only`.

Those nuances matter ;)

**Comment by romainmenke** [comment]
> The drawbacks are far more important than the benefits it provides, IMHO. I would strongly advocate against this. You wouldn't imagine doing the same on the PHP side (e.g. having each declared variables global). It may work at small scale but will quickly turn into a nightmare at larger scale when you have dozens of nested templates.

We maintain ±60 themes where we actively push towards not using `only`. It works just fine, even over very long periods and after many iterative changes. I am not saying that you are wrong :) Only that this isn't black/white. You can successfully use either approach.

But more importantly it is a moot point what the best practice is.
Both using `only` and not using `only` are perfectly fine implementations of Twig templates.
We might be using Twig differently than you might prefer, but not in a weird or unexpected way.

> Timber does not add any global variable (which is done with $twig->addGlobal('key', 'value') in Twig). Timber only "pollutes" the context of your rendered template (context ≠ global). A context that you can choose to cascade, or not, to your includes using only.

> Those nuances matter ;)

Not really.

Adding something new to `context` is equally breaking as adding a global for users who already have variables with that name.

This shouldn't be controversial to point out :)
Conflicts between library and user provided variables are a well understood challenge.

-------

To clarify.

I think that the core issue is obvious and indisputable.
Placing the responsibility on the user to navigate this correctly is not the best approach imho.

However, it is totally fine not to solve this issue.

I think it would be nice if Timber did namespacing of things it adds to Twig.
(This could be optional or configurable?)

But I understand that a change of this nature is equally breaking.

**Comment by nlemoine** [comment]
> I think that the core issue is obvious and indisputable.

I wouldn't call it an issue but I'm the author of https://github.com/timber/timber/issues/2409#issue-786809264, so yes, we can both agree that it should be improved.

> Placing the responsibility on the user to navigate this correctly is not the best approach imho.

I'm not placing this on user responsability, just showing a solution that prevents variables to cascade through your template tree.

> I think it would be nice if Timber did namespacing of things it adds to Twig.

Sorry, I'm pretty sure we won't go that way. I can't picture me writing `{{ timber_user }}`, `{{ timber_post }}`, etc. everywhere.

What I have mind is more cleaning up the global context so we don't pollute it with so much keys and rather have a single entry point (as pointed out in https://github.com/timber/timber/issues/2409#issue-786809264) where you can call functions, access "global" WP variables, etc.

So the choice of adding context data/handling conflicts lands in the user's hands.

**Comment by romainmenke** [comment]
> Sorry, I'm pretty sure we won't go that way. I can't picture me writing `{{ timber_user }}`, `{{ timber_post }}`, etc. everywhere.

That's fair

> What I have mind is more cleaning up the global context so we don't pollute it with so much keys and rather have a single entry point (as pointed out in https://github.com/timber/timber/issues/2409#issue-786809264) where you can call functions, access "global" WP variables, etc.
> 
> So the choice of adding context data/handling conflicts lands in the user's hands.

Sounds good!
