### ISSUE TITLE
[BUG] Maybe a bug about acf fields in menus

### ISSUE THREAD

**Issue by xanghyr** [timber/timber#3018]
### Expected Behavior

Have the right acf fields in the menus

### Actual behavior

Always the same acf fields from the last menu called.

### Steps to reproduce behavior

1. Register multiple menus `register_nav_menus()`
2. With ACF create fields with location rules targeting "Form -> Menu"
3. inside `add_filter( 'timber/context', array( $this, 'add_to_context' ) );` retrieve each menus with multiple `Timber::get_menu()`
4. In Appearance -> Menus create menus for each location, and you will have the same acf field group on all (if it's not only me ^^)

### Notes

I had an other problem with menus last month but I don't think it's the same problem.
I tried a clean install with my boilerplate and reproduced the same problem.

Apparently `Timber::get_menu()` triggers `wp_get_nav_menu_items()` inside `advanced-custom-fields-pro/includes/forms/form-nav-menu.php`. So for menus, acf always load stuff from last menu ID called by the last `Timber::get_menu()`.

Maybe I failed something else on my code and it's only me...

For now I fixed it by putting `Timber::get_menu()` inside an `if ( ! is_admin() )`

### What version of Timber are you using?

2.2.0

### What version of WordPress are you using?

6.5.5

### What version of PHP are you using?

8.2

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Hi @xanghyr ,

I tried to reproduce your bug but were unable to:

1. Created a menu location: `footer_navigation`
2. Created a menu and linked it to the footer location.
4. Created a field group with a dummy field and tried targeting both the menu itself and the menu locations
5. Tried calling `Timber::get_menu('footer_navigation')` and `Timber::get_menu(4)` in functions.php

Fields only appeared on the targeted menu or menu location. Where do you invoke your Timber::get_menu call exactly? Is it inside a hook? If so, which one and at what priority?

**Comment by xanghyr** [comment]
Hi,
It's OK now, an early call to the context made this problem.
