### ISSUE TITLE
[DOCS] Widgets guide has incomplete (deprecated) code example

### ISSUE THREAD

**Issue by jasalt** [timber/timber#3021]
### Expected Behavior

Guide page https://timber.github.io/docs/v2/guides/widgets/ should have a simple copy-paste example for registering widget area on site (eg. with Timber starter theme), adding it to context variable and passing to view for rendering.

### Actual behavior

Guide page suggests to use `$data` -variable which is incorrect. Possibly from historic Timber version?

Most complete example I found was by TJ here https://css-tricks.com/timber-and-twig-reignited-my-love-for-wordpress/. It works on Timber 2.0 eventhough it's from 2015.

Steps include:

```
// Registering widget area
function site_widgets_init() {
  register_sidebar( array(
    'name'          => 'News Sidebar',
    'id'            => 'news_sidebar'
  ) );
}

add_action( 'widgets_init', 'site_widgets_init' );

// Include sidebar content to $context
$context['news_sidebar'] = Timber::get_widgets('news_sidebar');
```
And then they are available on template as expected:
```
{{ news_sidebar }}
```

### Notes

Apart from the "typo" of using wrong variable name, it's good to have a full example so beginner theme developers can see a full example including registering in docs.

### What version of Timber are you using?

2.2.0

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by jasalt** [comment]
Also, I would add to doc page that to enable shortcut edit buttons for widgets, the blue icons with pencil in customizer preview, it is required to add ` add_theme_support( 'customize-selective-refresh-widgets' );` setting to theme code, after which it starts working for both classic and block widgets (tested with Timber starter theme). 

Ref: https://make.wordpress.org/core/2016/11/10/visible-edit-shortcuts-in-the-customizer-preview/

**Comment by Levdbas** [comment]
Hi @jasalt ,

Are you willing to create a PR for correcting the typo or maybe give the guide some TLC in general?
We eventually want to add a guide as well to use the new, better supported template parts. I use them in all my projects and are mostly just visual widgets.

**Comment by jasalt** [comment]
@Levdbas Yes, I'll keep this in mind, rushing a bit to finish a project so I left this just as notes for now.
