### ISSUE TITLE
[DOCS] Upgrade guide shows PHP >= 7.4 for Timber 2.0 when it's >=8.1 (right?)

### ISSUE THREAD

**Issue by anna-giverlink** [timber/timber#3022]
### Expected Behavior

I expect the requirements listed in the upgrade guide to match the current requirements for Timber 2.X.

### Actual behavior

In the upgrade guide at [https://timber.github.io/docs/v2/upgrade-guides/2.0/](https://timber.github.io/docs/v2/upgrade-guides/2.0/) , "New requirements" shows the required PHP version as being >= 7.4

[https://timber.github.io/docs/v2/upgrade-guides/2.0/#new-requirements](https://timber.github.io/docs/v2/upgrade-guides/2.0/#new-requirements)
"Timber 2.0 requires you to use a PHP version >= 7.4." 

In the 2.X timber/composer.json the PHP version is shown as needing to be 8.1 or above. (Twig is also ^3.5 while the upgrade guide says >= 2.15.3) 

### Notes

My apologies if I'm misreading something!

### What version of Timber are you using?

Not relevant to issue

### How did you install Timber?

None

**Comment by gchtr** [comment]
@anna-giverlink Sorry if this is confusing.

Timber v2.0.0 comes with the requirements listed in the Upgrade Guide.

In Timber v2.2.0 (see https://github.com/timber/timber/releases/tag/v2.2.0), we bumped the minimum requirements to PHP 8.1 and Twig 3.5.

So if you first want to use Timber v2.0.0 before upgrading to Timber v2.2.0, you could install it using

```
composer require timber/timber:2.0.0
```

**Comment by anna-giverlink** [comment]
@gchtr Oh, I see! Sorry, obviously I totally missed the v2.0.0 vs v2.2.0 part. That's great news. Thank you very much for your patience with this issue and for responding so quickly

**Comment by gchtr** [comment]
Great, happy to help!
