### ISSUE TITLE
[BUG] ImageHelper: URI components polluting FS components

### ISSUE THREAD

**Issue by mcaskill** [timber/timber#3024]
### Expected Behavior

We should be able to manipulate images using Timber's image helper whose URL includes query parameters.

Given an example image URL and snippet:

```twig
<!-- post.thumbnail.src: https://example.com/uploads/2024/07/cat.jpg?lang=fr -->
<img src="{{ post.thumbnail.src|resize(640) }}" />
```

I expect the output of filter `timber/image_helper/analyze_url` to be:

```php
[
	'url'       => 'https://example.com/uploads/2024/07/cat.jpg?lang=fr',
	'absolute'  => true,
	'base'      => 1,
	'subdir'    => '/2024/07',
	'filename'  => 'cat',
	'extension' => 'jpg',
	'basename'  => 'cat.jpg',
]
```

And for Timber's `ImageHelper` to process the image and return something like:

```twig
<!-- Note that the suffix might not be accurate. -->
<img src="https://example.com/uploads/2024/07/cat-640x-c-default.jpg?lang=fr" />
```

### Actual behavior

Timber's `ImageHelper::get_url_components()` fails to consider URI-only components when decomposing the path components which prevents it from finding the file on the file system.

Given the aforementioned image URL.

Logged error:

```
[ Timber ] Error loading /var/www/example.com/uploads/2024/07/cat.jpg?lang=fr
```

Output of filter `timber/image_helper/analyze_url`:

```php
[
	'url'       => 'https://example.com/uploads/2024/07/cat.jpg?lang=fr',
	'absolute'  => true,
	'base'      => 1,
	'subdir'    => '/2024/07',
	'filename'  => 'cat',
	'extension' => 'jpg?lang=fr',
	'basename'  => 'cat.jpg?lang=fr',
]
```

### Steps to reproduce behavior

Pass a URL to an image with a query parameter to one of Timber's image manipulation functions. For example:

```twig
<!-- post.thumbnail.src: https://example.com/uploads/2024/07/cat.jpg?lang=fr -->
<img src="{{ post.thumbnail.src|resize(640) }}" />
```

### Notes

I've bypassed the issue by stripping the query parameter from the `extension` and `basename`:

```php
add_filter( 'timber/image_helper/analyze_url', function ( array $info ): array {
	if ( ( $i = \strpos( $info['extension'], '?' ) ) !== false ) {
		$info['extension'] = \substr( $info['extension'], 0, $i );
	}

	if ( ( $i = \strpos( $info['basename'], '?' ) ) !== false ) {
		$info['basename'] = \substr( $info['basename'], 0, $i );
	}

	return $info;
} );
```

Also, I have not tested hashes in URLs.

### What version of Timber are you using?

Timber 2.2.0

### What version of WordPress are you using?

WordPress 6.5.4

### What version of PHP are you using?

PHP 8.2.20

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Hi @mcaskill ,

Good find. Are you willing to create a PR for this, maybe update your code to check for hashes as well and add some tests to test the new code? If you need help, let me know!
