### ISSUE TITLE
setEscaper() method deprecated

### ISSUE THREAD

**Issue by columbian-chris** [timber/timber#3025]
I'm getting this deprecation error thrown at me a lot:

`Since twig/twig 3.10: The "Twig\Extension\EscaperExtension::setEscaper()" method is deprecated, use the "Twig\Runtime\EscaperRuntime::setEscaper()" method instead (be warned that Environment is not passed anymore to the callable).`

I noticed a very similar error happened once before in #2081 from an older version of Twig that was resolved.

_Running:_

- Timber 2.1.0 (managed via Composer)
- Twig 3.10.3
- WordPress 6.6
- PHP 8.1.27

_Trail:_
```
wp-content/themes/my-theme/vendor/symfony/deprecation-contracts/function.php:25

trigger_deprecation()
    wp-content/themes/my-theme/vendor/twig/twig/src/Extension/EscaperExtension.php:127
Twig\Extension\EscaperExtension->setEscaper()
    wp-content/themes/my-theme/vendor/timber/timber/src/Twig.php:558
Timber\Twig->add_timber_escapers()
    wp-includes/class-wp-hook.php:324
apply_filters('timber/twig')
    wp-content/themes/my-theme/vendor/timber/timber/src/Loader.php:518
Timber\Loader->get_twig()
    wp-content/themes/my-theme/vendor/timber/timber/src/Loader.php:120
Timber\Loader->render()
    wp-content/themes/my-theme/vendor/timber/timber/src/Timber.php:1444
Timber\Timber::compile()
    wp-content/themes/my-theme/vendor/timber/timber/src/Timber.php:1579
Timber\Timber::render()
    wp-content/themes/my-theme/page-title.php:98
```

**Comment by Levdbas** [comment]
Hi @columbian-chris ,

This is fixed in the [2.2](https://github.com/timber/timber/releases/tag/v2.2.0) release. Could you give that a try?
See https://github.com/timber/timber/commit/295349b0316640014a0841acef0f185bbdb8bd2e

**Comment by columbian-chris** [comment]
@Levdbas I'm sure you are correct, which really manifests the underlying actual problem I appear to be having: before I submitted this issue, I ran `composer update` and version 2.1 still remains installed.  I assumed this was because it was the newest version.  Any idea why this would be happening?

**Comment by Levdbas** [comment]
Maybe the version is pinned in your composer file like so @columbian-chris ?

`"timber/timber": "2.1"` instead of `"timber/timber": "^2.1"`? 

Or else try manually bumping the version in your composer file like so `"timber/timber": "2.2"` and then run a `composer update` and see what happens.

**Comment by columbian-chris** [comment]
When I run `composer update timber/timber:2.2`, I do run into some valuable information:

```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires timber/timber ^2.1 -> satisfiable by timber/timber[v2.2.0].
    - timber/timber v2.2.0 requires php ^8.1 -> your php version (7.4.33) does not satisfy that requirement.
```

The PHP version comment surprised me because my site is running 8.1, but when I ran `php -v`, the command line reported version 7.4.33.  `sudo update-alternatives --list php;` reported that I have 7.4, 8.0, and 8.1 installed, so I guess the default version on the command line is still set to 7.4.  When I use `update-alternatives --config php` to change that version version to at least 8.1, I can then run `composer update` and it will update the Timber package as expected.
