### ISSUE TITLE
Gutenberg Block with ACF and Woocommerce

### ISSUE THREAD

**Issue by kirilldorozhynskyi** [timber/timber#3026]
### Expected Behavior

Hi, 

I have a problem that someone might have already encountered.

We use Gutenberg blocks in documentation and retrieve ACF fields through:
$context['ce'] = get_fields();
Here’s the issue: if the WooCommerce plugin is not activated, everything works perfectly. This is the load speed log of one of the blocks using ACF field repeater.

Time taken by get_fields(): benefits-slider :0.0023870468139648 seconds
Number of queries executed by get_fields():benefits-slider :12

And this is its load speed when we activate WooCommerce.

Time taken by get_fields(): jd/benefits-slider :0.90512990951538 seconds
Number of queries executed by get_fields(): jd/benefits-slider :12

As you can see, the wait time for get_fields() has increased many times;

How can we fix this issue? On whose side will the bug be?

### Actual behavior

<img width="1110" alt="Screenshot 2024-07-27 at 13 36 01" src="https://github.com/user-attachments/assets/ba9eeea4-b1d2-4e1a-89cd-1c173fb0913b">

_No response_

### What version of Timber are you using?

Timber: 2.2

### What version of WordPress are you using?

Wordpress:  6.6.1

### What version of PHP are you using?

PHP: 8.3.8

Advanced Custom Fields PRO - Version 6.3.4
WooCommerce - Version 9.1.4

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by gchtr** [comment]
Hey @kirilldorozhynskyi

I’m sorry, but as a community-led project we don’t have the resources to investigate an issue like this.

What you could do is to try and see whether the performance drain also appears when Timber is not installed. ACF, WooCommerce and Timber all use hooks extensively, so it’s very well possible that they affect each other.

If you or someone else finds that Timber really is the issue and can provide more information on what exactly is causing the issue, then we could try to find a solution and fix the issue. But we won’t go and do the investigation for you. We hope you can understand.

I’m going to close this for now. But we’ll reopen if you can provide more details.

**Comment by JacobPrice** [comment]
@kirilldorozhynskyi Depending on how the fields are being modified, the data you need may already be available through the render callback function.

```php
callback_function( $block, $content, $is_preview, $post_id, $wp_block, $context );
```

``$block`` is metadata, as an associative array, and one of the keys ``data`` may have what you need without the additional queries. 

This won't work if the block saves the metadata to the post, but that's probably not your situation in this case.

All else fails, cache will help.
