### ISSUE TITLE
Timber post object does not exist inside ACF blocks inside the editor

### ISSUE THREAD

**Issue by cbirdsong** [timber/timber#3033]
When templating an ACF block, I was trying to get a custom field value out by using `{{ post.meta("field") }}`, and it did not work inside the editor preview of the block. The following all work as expected on the front end, but are blank inside the editor:

```twig
<pre>{{ post.id }}</pre>
<pre>{{ post.meta("field_name") }}</pre>
<pre>{{ function('the_field', 'field_name', post.id) }}</pre>
```

Looking at a dump of the Timber context, everything is there except `post`. Is this expected?

**Comment by Levdbas** [comment]
Hi @cbirdsong ,

Timber does not automatically sets up context in the backend, probably for performance reasons. But you can easily add it to your block context yourself if you need to access it. You could probably also add the post object globally in the backend by using the `timber/context` filter.

**Comment by cbirdsong** [comment]
That's what I ended up doing, but what made this confusing is that most of the rest of the context does exist. The only thing missing was `post`.

**Comment by Levdbas** [comment]
In the [context method](https://github.com/timber/timber/blob/02d31d75e6cbff5b6d61daf07960c94b0fb71da5/src/Timber.php#L1165) the post or posts variable is automatically setup, based on the `is_singular()` and similar functions, these are all false in the backend. we might want to expand on this behaviour if we decide to expand on the ACF integration, but for now, adding the context yourself is the way to go!
