### ISSUE TITLE
[BUG] Escaping Bug in Block twig file.

### ISSUE THREAD

**Issue by mccomaschris** [timber/timber#3036]
### Expected Behavior

Our custom WordPress theme uses ACF Pro to build custom blocks. The Twig file for the basic blog contains this HTML. It seems to be a weird escaping issue that is breaking in the CSS class with the right arrow. If I move this HTML to our page.twig file or our layout.twig file it works perfectly fine. 

https://gist.github.com/mccomaschris/3c38c0867f8da6056e54c6e2f115db1a

### Actual behavior

This is what you see when using devtools to check out the HTML on the actual page when used in our block's Twig file.

<img width="1198" alt="Screenshot 2024-09-10 at 2 49 28 PM" src="https://github.com/user-attachments/assets/31204b87-d1b1-4756-bf7b-52543094fbd0">

### Steps to reproduce behavior

1. Create new block with ACF Pro
2. In the block's Twig file add this code: https://gist.github.com/mccomaschris/3c38c0867f8da6056e54c6e2f115db1a
3. Create New Page in WordPress and add block to page.
...

### What version of Timber are you using?

Timber 2.2.0

### What version of WordPress are you using?

WordPress 6.6.1

### What version of PHP are you using?

PHP 8.2

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Hi @mccomaschris ,

This is not Timber related. I tried rendering the same HTML via the render compile hook from ACF blocks and the issue stays the same. So this must be something related to Gutenberg or ACF.

**Comment by Levdbas** [comment]
update:

Use the esc_attr() function or the https://timber.github.io/docs/v2/guides/escaping/#esc_attr filter to succesfully escape the classes so they render in the editor. I would recommend escaping all these tailwind classes to prevent those kind of issues.
