### ISSUE TITLE
Timber::get_menu(0) returns alphabetically first menu instead of nothing

### ISSUE THREAD

**Issue by cbirdsong** [timber/timber#3063]
To reproduce on a fresh site:
1. Add a menu, which will have an ID that is greater than 0.
2. Use `Timber::get_menu(0)`. You'll get the menu.
3. Add another menu, making sure the slug/name comes after the first one alphabetically.
4. Use `Timber::get_menu(0)` again. You'll get the first menu again.

<details>

<summary>How I found this, if it matters</summary>

While resolving the issue I had that prompted #3062, I switched to using [`get_nav_menu_locations`](https://developer.wordpress.org/reference/functions/get_nav_menu_locations/) to add all menus into the global context. In doing that, I realized that menu locations with no assigned menu are assigned an ID of `0` when returned from that function.

(That function feels better than using `get_registered_nav_menus` [as suggested in the docs](https://timber.github.io/docs/v2/guides/menus/#set-up-all-menus-globally) since I don't have to run a function to see if a menu exists, I can just check for `0`? 🤷‍♂️)

</details>

**Comment by Levdbas** [comment]
This is strange behavior for sure. Shall we add a check for a `0` value in `Timber\Factory\MenuFactory::from_id` and if so return null as well to cover this case @gchtr ?

**Comment by gchtr** [comment]
> Shall we add a check for a `0` value in `Timber\Factory\MenuFactory::from_id` and if so return null as well to cover this case?

I think this would be a good solution.

I didn’t know about that locations that have no menu assigned will return `0`. And that we could use `get_nav_menu_locations()´ instead of `get_registered_nav_menus()` in combination with `has_nav_menu()`. Maybe updating the docs would be worth it as well.
