### ISSUE TITLE
Deprecation of use of the "deprecated", "deprecating_package", and "alternative" options

### ISSUE THREAD

**Issue by columbian-chris** [timber/timber#3069]
After updating my composer packages, I'm hitting deprecation issue: `Since twig/twig 3.15: Using the "deprecated", "deprecating_package", and "alternative" options is deprecated, pass a "deprecation_info" one instead.`

Firing from `.../vendor/symfony/deprecation-contracts/function.php` line ~25

_Using:_
Timber 2.3.0
Twig v3.16.0
Wordpress 6.7.1
PHP 8.2.24
Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
PR is already in place at https://github.com/timber/timber/pull/3064 but we need to check if we will need to bump the minimum required version of Twig as well.

**Comment by columbian-chris** [comment]
Thanks, @Levdbas.

**Comment by Levdbas** [comment]
We'll probably be releasing this next week in a patch release @columbian-chris  :)

**Comment by Levdbas** [comment]
Release is out @columbian-chris

**Comment by columbian-chris** [comment]
Thank you so much, @Levdbas!
