### ISSUE TITLE
Timber\Attachment::path() returns incorrect value

### ISSUE THREAD

**Issue by LoranRendel** [timber/timber#3072]
### Expected Behavior

`Timber\Attachment::path()` returns `/wp-content/uploads/file.png`

### Actual behavior

`Timber\Attachment::path()` returns `wp-contenthttps://example.com/wp-content/uploads/file.png`

### Steps to reproduce behavior

```php
<?php

var_dump(\Timber\Timber::get_post(get_posts( [ 'post_type' => 'attachment', 'numberposts' => 1 ] )[0])->path())
```

### What version of Timber are you using?

Timber 2.3.0

### What version of WordPress are you using?

Wordpress 6.7.1

### What version of PHP are you using?

PHP 8.2

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by mrfsrf** [comment]
first thing that came to mind
Btw. path function doesn't have declaration modifier (static) that you provided in Expected Behavior
```php
    // Timber\Attachment class
    public function path(): string
    {
        $src = $this->src();
        // If src is a URL, convert it to a filesystem path first.
        if (URLHelper::is_url($src)) {
            $src = URLHelper::url_to_file_system($src);
        }

        return URLHelper::get_rel_path($src);
    }
```

Update:
(one)alternative
```php
$img = \Timber\Timber::get_post(get_posts( [ 'post_type' => 'attachment', 'numberposts' => 1 ] )[0];
print_r('wp-content/uploads/' . $img->file());
```

**Comment by Levdbas** [comment]
Thanks you @mrfsrf , for the solution! I've made that into a PR with some additional tests in #3073
