### ISSUE TITLE
Add render path as relative location by default?

### ISSUE THREAD

**Issue by parisholley** [timber/timber#311]
Following in the same nature as #27, right now I am doing this before Timber::render() calls,

```
Timber::$locations[]= get_stylesheet_directory() . '/' . dirname($path);
```

Often times I organized my views in sub folders, and they may share things like sidebars, widgets, etc. Instead of having to do a full path include, it would be nice to have a relative lookup. Ideally, twig/timber would support a './' syntax so that is lookups the file relative to the requesting twig file.

**Comment by bfred-it** [comment]
I just started using Timber and I'm really missing relative paths resolution.

I can do `include file.php`, `require('./file.js')`, `@import 'file.scss'` but not `include file.twig` :(

**Comment by palmiak** [comment]
Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
