### ISSUE TITLE
Is there a better way to work with The Events Calendar?

### ISSUE THREAD

**Issue by geoffyuen** [timber/timber#312]
(I apologize for the terrible post title)

I'm using The Events Calendar plugin. To show the calendar on a page you query posts of type "tribe_events" and then call a function to output the results. Because the function itself echoes the output (as opposed to returning a string) I used this code to capture the output into a variable:

```
ob_start();
query_posts('post_type=tribe_events');
tribe_show_month();
$context['tribe_dump'] = ob_get_contents();
ob_end_clean();

Timber::render('page-home.twig', $context);
```

This works but it just seems dirty to me. Is there something obvious that I'm overlooking?

**Comment by mindfullsilence** [comment]
@jarednova Did you ever get a workable integration for this? Could you throw your progress up in a repo? I wouldn't mind taking a look and possibly contributing if you're open to it.

**Comment by jarednova** [comment]
@mindfullsilence unfortunately it's in a private client repo, but I ripped out the file and have it here in a Gist:

https://gist.github.com/jarednova/894fe08dc01b1466a296423b7a9618d7

This was using a version of ECP from mid-2015 so it's likely not plug-and-play with the current version. Hopefully this can give you a start. I'd LOVE to come up with a stable integration. If you have something going in a repo, please share and we can try to wrangle others (or even Modern Tribe too)

**Comment by chrismcintosh** [comment]
For anybody landing here in 2021 to get this working I had to

1. Have the free version of The Events Plugin by Modern Tribe installed and activated
2.Create a file at the following location inside the Timber theme `tribe/events/v2/default-template.php`

Inside default-template.php add the following code
```
<?php
/**
 * Default Events Template
 * This file is the basic wrapper template for all the views if 'Default Events Template'
 * is selected in Events -> Settings -> Display -> Events Template.
 *
 * Override this template in your own theme by creating a file at [your-theme]/tribe-events/default-template.php
 *
 * @package TribeEventsCalendar
 * @version 4.6.23
 *
 */

use Tribe\Events\Views\V2\Template_Bootstrap;

if ( ! defined( 'ABSPATH' ) ) {
	die( '-1' );
}

$context = Timber::get_context();
$context['tribe_markup'] = tribe( Template_Bootstrap::class )->get_view_html();
Timber::render( array( 'events.twig' ), $context );
```

3.Then on the events.twig file you can use {{tribe_markup}}
