### ISSUE TITLE
Custom (constants) variables in Timber

### ISSUE THREAD

**Issue by chrisvanmook** [timber/timber#314]
Hi Guys,

First of all, Timber is awesome, thanks for making this! 
I would like to know if there is a way to use custom constant variables in Timber. For example, I have this custom constant WP_LOCAL_DEV set to true in my wp-config.php. Now I would access this constant in my layout.twig file, so I could use this with a statement to include certain pieces of code if my WP_LOCAL_DEV is set to true. Could there be a feature where I could do something like this:

<code>Timber::$constants = array('local_dev' => WP_LOCAL_DEV);</code>

so I can use this as the following:

<code>
{% if site.constants.local_dev == 1 %}
//hide this for production
{ endif }
</code>

Many thanks!

**Comment by kala725** [comment]
use constant('WP_LOCAL_DEV') function.  It will give you the required output.
