### ISSUE TITLE
Adding to context globally

### ISSUE THREAD

**Issue by dmtroyer** [timber/timber#328]
Hi All,

I'm having a lot of repetition in my php files to add my [sidebar to the context](https://github.com/jarednova/timber/wiki/Sidebar#method-1-php-file).

This sidebar is on every single page, so it would be nice and dry if I didn't have to add it to the context in every single php file.

I've tried adding it to `functions.php` inside `StarterSite::add_to_context()` but that doesn't seem to work.

Any thoughts?

Thanks!

**Comment by oleggen** [comment]
Also worked great for me 


> add_filter( 'timber_context', function ( $context ) {
> 	global $timber_context;
> 	$timber_context = is_array( $timber_context ) ? $timber_context : array();
> 	$context    = is_array( $context ) ? $context : array();
> 	$context    = array_merge( $timber_context, $context );
> 
> 	return $context;
> } );
> 
> function add_to_context( $key, $val ) {
> 	global $timber_context;
> 	$timber_context[ $key ] = $val;
> }
> 
> add_to_context( 'server', $_SERVER );

**Comment by danicholls** [comment]
I'm trying to do this in a child theme and think I'm misunderstanding something. The parent's functions.php file has `class StarterSite extends TimberSite ....` with all of the normal (working) code, and the child's functions.php registers new sidebars, uses the above code, adding:

```
add_to_context( 'example_widget', Timber::get_widgets('example_widget') );
```

**Comment by gchtr** [comment]
@danicholls What if you don’t work with the code above, but only work with the `timber/context` filter?

```php
add_filter( 'timber/context', function( $context ) {
    $context['example_widget'] = Timber::get_widgets( 'example_widget' );
 
    return $context;
} );
```

**Comment by danicholls** [comment]
That works!
