### ISSUE TITLE
Timber and Themeforest's WordPress Theme Submission requirements

### ISSUE THREAD

**Issue by Lisa-Williams** [timber/timber#330]
I couldn't find a usage support link or mention. So I'm opening this issue.
This is not an issue with Timber, but just a request for information.

I have a design ready to be cut up and sewn together again by WP, which I want to sell at Themeforest.
I would love to use Timber and it's starter theme, but want to find out first if there is anything contained **within** Timber (coding, functional, or procedural) that is going against Themeforest's WP theme submission requirements?: http://themeforest.net/forums/thread/announcement-finalised-wordpress-submission-requirements-phase-1/117137

So if anyone has already used Timber for a TF theme, what were your experiences with TF?
Is there anything of Timber which I should avoid using to prevent rejection?

P.S. I have to admit that I haven't looked into Timber's code at a detailed level yet. Only bumped into it yesterday afternoon.

Thanks,
Lisa

**Comment by gabormeszoly** [comment]
@jarednova here is my discussion with envato :(

**Question:**

Dear Envato,
I have read the WordPress Theme Submission Requirements page on the Envato Market Help center but please clearify if I’m permitted to use TWIG template engine while developing a Wordpress theme for ThemeForest market.
Regards, Gabor

TF Submission Guide: https://help.market.envato.com/hc/en-us/articles/202822450-WordPress-Theme-Submission-Requirements
Twig: http://twig.sensiolabs.org/
Twig + Wordpress example: http://upstatement.com/timber/

**Answer 1:**

Greetings Gabor,
Thank you for contacting Envato Market Help.
I am forwarding this along to the necessary staff for inspection, we'll be in touch as soon as we can.
Thank you for your patience.
Kind Regards,
Bryan F.


**Answer 2:**

Greetings Gabor,
Thank you for your patience.
Our review team has confirmed we are not accepting themes using TWIG template engine at this time.
Please let me know if I can assist you further.
Kind Regards,
Bryan F.

**Comment by jarednova** [comment]
Sorry to hear! I'm kinda surprised, but good to know for the future

**Comment by chetzof** [comment]
I got my theme accepted on ThemeForest and it uses Timber. 

I asked the same question the support team and they said they have no problem with it. So i did create a theme using Timber,  however during review another reviewer rejected it saying they don't allow Twig. 
Then i had to sent them the ID of the ticket, where they allowed using it :)

So in the end they approved it, however required that the theme basic pages should work without Timber activated, so i had to create a lightweight version of the theme without twig, which was basically double work...

Mixed feelings about this.
