### ISSUE TITLE
Is there any replacements of deprecated "add_route" function?

### ISSUE THREAD

**Issue by boochamoocha** [timber/timber#340]
Is there any replacements of deprecated "add_route" function?
I need something like action function can handle custom route.

timber.php (425)

``` php
  * @deprecated since 0.20.0
     */
    public static function add_route($route, $callback, $args = array()) {
        TimberRoutes::add_route($route, $callback, $args);
    }
```

**Comment by laurentvd** [comment]
Any news on this? I was wondering the same thing. Is there an alternative syntax or are you phasing out Timber routes entirely?

**Comment by boochamoocha** [comment]
I use TimberRoutes::add_route instead

**Comment by laurentvd** [comment]
Ah right, thanks for replying. I guess the docs still need to be updated as I couldn't find it there. Thanks again.

**Comment by boochamoocha** [comment]
https://github.com/Upstatement/routes

**Comment by laurentvd** [comment]
:+1:
