### ISSUE TITLE
TimberMenu and custom post type archives

### ISSUE THREAD

**Issue by paul-straetmans** [timber/timber#341]
When I have a custom post type called gallery and go to localhost/website/gallery it won't display the menu item as active. Normal pages are fine (current_page_item class is added).

I know this is not standard for Wordpress. But there a lot of scripts to 'fix' this. This one for example:

``` php
function custom_active_item_classes($classes = array(), $menu_item = false){            
        global $post;
        $classes[] = ($menu_item->url == get_post_type_archive_link($post->post_type)) ? 'current-menu-item active' : '';
        return $classes;
    }
    add_filter( 'nav_menu_css_class', 'custom_active_item_classes', 10, 2 );
```

I've added this function inside the functions.php before and after 

``` php
$data['menu'] = new TimberMenu();
```

but no success. I checked the Wiki, but couldn't find some info about adding extra functions for the menu. 

This is the code in my twig file in case it's relevant :)

``` html+django
{% for item in menu.get_items %}
          <li id="menu-item-{{item.ID}}" class="{% if 'current-page-ancestor' in item.classes or 'current-menu-item' in item.classes %}active{% endif %} {{item.classes | join(' ')}} menu-item-{{item.ID}}">
          <a class="menu-item__link" href="{{item.link}}">{{item.title}}</a>
     </li>
{% endfor %}
```

**Comment by asakurayoh** [comment]
Those changes do not fix the problem with https://wordpress.org/plugins/post-type-archive-links/ .
It use the `wp_nav_menu_objects` filter to apply the class.

**Comment by lmartins** [comment]
Thank you @asakurayoh , i've looked everywhere for a fix to this and your solution works great.

**Comment by macder** [comment]
A simpler solution IMO, as long as the menu item is named the same as the post type:

functions.php
```php
function add_to_timber_context($context) {
    $context['primary_menu'] = array_map(function($item) {
        $item->current = (strtolower($item->title()) === get_post_type()) ?: false;
        return $item;
    }, (new TimberMenu('primary'))->get_items());
    return $context;
}
add_filter('timber_context', 'add_to_timber_context');
```

Then in your twig template:
```
<div class="c-nav">
  <nav class="c-nav__menu" role="navigation">
    <ul class="c-nav__menu-list">
      {% for item in items %}
        <li class="c-nav__menu-item">
          <a class="c-nav__menu-link {{ item.current ? 'active' : '' }}" href="{{item.get_link}}">
            {{item.title}}
          </a>
        </li>
      {% endfor %}
    </ul>
  </nav>
</div>
```

**Comment by palmiak** [comment]
@paul-straetmans can we mark this issue as solved? Please respond in two weeks or we'll close this thread.

**Comment by justiny** [comment]
> @paul-straetmans can we mark this issue as solved? Please respond in two weeks or we'll close this thread.

Definitely not solved, though.
