### ISSUE TITLE
Create TimberMenu object in Template

### ISSUE THREAD

**Issue by asecondwill** [timber/timber#345]
Maybe this is a no-no, but i'd like to be able to create Menu objects in templates like we can create Timber image objects:

````
<img class='round th' src="{{TimberImage(item.image).src|resize(150,150)}}" />
````

However if i try this: 
````
 {% for item in TimberMenu(item.menu).get_items %}
````
(where Item.menu is the id of the menu from ACF's menu field type)  I get 

````
Fatal error: Method TimberFunctionWrapper::__toString() must not throw an exception in /Users/willbarker/Sites/happiseed/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Environment.php(331) : eval()'d code on line 0 - See more at: http://cleverbear.r4/page1-2/#sthash.6oLJM7Yz.dpuf
````

I'm using this as part of a Flexible Content Field that is attached to a widget, so i can use regular widgets interface but be able to create new types of content with ACF & render the info with Timber.  which i think is pretty neat.  It works well for everything else, but I've hit a road block with Menus.

Is there something I'm doing wrong creating the object, or something we can do to TimberMenu object so that it can be used like this?

**Comment by connorjburton** [comment]
Hi @asecondwill - is this still an issue for you?

Thanks
