### ISSUE TITLE
ACF File Custom Field

### ISSUE THREAD

**Issue by addedlovely** [timber/timber#379]
Using a 'File' ACF custom field always returns the ID to the attachment, regardless of whether returning the URL to the file is set in ACF.

To get the path to the file the following works:
{{TimberImage(post.get_field('download')).src}}

Am I missing something, or is this a bug?

**Comment by marcoalexpinheiro** [comment]
I'm having the same issue. I have ACF V5.1.9.1 and the field set with "File URL" but still getting and ID instead of an URL.

**Comment by incredimike** [comment]
Also encountering the same issue. Using Pro. Only returns the ID, even though "url" is set
