### ISSUE TITLE
[Enhancement] Support get_term function of Wordpress in Timber core

### ISSUE THREAD

**Issue by ste93cry** [timber/timber#386]
Hi,
Timber's core already supports the `get_terms` wrapper function of the Wordpress original function. It would be nice to have a `get_term` wrapper too, as now the only way I found to retrieve a single term object is to use `array_pop`.

**Comment by connorjburton** [comment]
@jarednova @ste93cry - i was going to go ahead and start on this but need some clarification, should we be searching over the current posts terms, which is what I would assume, and if so should we be giving the options to search by term id, slug, name or term_taxonomy_id. Replicating `get_term_by`?

**Comment by ste93cry** [comment]
I would expect the function to work as the WordPress [one](https://codex.wordpress.org/Function_Reference/get_term), but returning a TimberTerm object instead

**Comment by jarednova** [comment]
Closed in #1049
