### ISSUE TITLE
Availability on WordPress.com VIP

### ISSUE THREAD

**Issue by westonruter** [timber/timber#398]
We are keen to use Timber on WordPress.com VIP. When I inquired in August they said:

> We're actually not supporting Timber/Twig at this time. There are a few fundamental issues with how the framework works that wouldn't make it a good fit (relies on compiled classes, for example).

Has any additional exploratory work been done to add VIP support for Timber? I know it will at least require quite a bit of review from VIP and also changes to the Timber, forcing certain configurations when `WPCOM_IS_VIP_ENV`.

**Comment by connorjburton** [comment]
Is this still relevant @jarednova ?

**Comment by jarednova** [comment]
Naw, thanks for closing @connorjburton. I'll leave it to @westonruter on the WordPress VIP front. They have some very strict and specific requirements that my shop isn't really versed in; I think @westonruter's project is in a better place to (potentially) win their seal of approval
