### ISSUE TITLE
[Enhancement] Expose WordPress translations functions to Twig context

### ISSUE THREAD

**Issue by ste93cry** [timber/timber#412]
Currently, Timber provides only the standard `__` translation function, but more are needed in many other cases, for example when we have to support singular/plural translations. I would like to see Timber exposing to Twig all the common WordPress translations functions. Here a list of them:

* `translate`
* `__`
* `_e`
* `_n`
* `_x`
* `_ex`
* `_nx`
* `_n_noop`
* `_nx_noop`
* `translate_nooped_plural`

For sure not all will be useful, I just copied here all the translation functions I found on Codex. At least, Timber should support the ones giving singular/plural forms of a text.

**Comment by skynet** [comment]
:+1:

**Comment by connorjburton** [comment]
Will sort this soon.
