### ISSUE TITLE
Adding 3rd-party plugins compatibility

### ISSUE THREAD

**Issue by aristath** [timber/timber#435]
A lot of plugins have virtual pages and/or manipulate the content to add their own.
That includes some of the most popular plugins out there like bbPress, BuddyPress, WooCommerce and a bunch of others.
Unfortunately Timber currently does not handle these properly and it can't display their content.
Ir order for them to be displayed we have to take these into account in our themes and do something like this:

``` php
/**
 * Return the value of an echo.
 * example: maera_get_echo( 'function' );
 */
function maera_get_echo( $function, $args = '' ) {

    ob_start();
    $function( $args );
    $get_echo = ob_get_clean();
    return $get_echo;

}

/**
 * Customize the Timber context
 */
function maera_timber_context( $context ) {

    $context['content'] = maera_get_echo( 'the_content' );
    return $context;

}
add_filter( 'timber_context', 'maera_timber_context' );
```

Then in our twig files we have to add

``` twig
{{ content }}
```

The problem is that the number of plugins that need that "hack" in order to properly work is just staggering!

So my question is: Can't we make that part of Timber core somehow so that _most_ plugins work out of the box without the need for such ugly hacks?

**Comment by jarednova** [comment]
Hey @aristath, so I think `TimberHelper::ob_function` has what you're looking for....

```php

function maera_timber_context( $context ) {
    $context['content'] = TimberHelper::ob_function( 'the_content' );
    return $context;
}
add_filter( 'timber_context', 'maera_timber_context' );
```

Can you give that a quick go and see if it takes care of the issue? There's definitely an inherent tension between the event-based architecture WP and a lot of plugins use vs. the more OOP approach of Timber

**Comment by aristath** [comment]
Hey @jarednova, thank you for taking the time to reply here... I know you're a busy man and I really appreciate you take the time to do so.

The above code seems to be working fine it does simplify the hack a bit.

However simplifying the hack was not my intention...
Themes add a presentation layer to plugins, and Timber allows us to use the awesomeness of twig in our template files.
So when someone creates a theme using Timber, the theme should work with all plugins. That's what themes do!
I can take care of BuddyPress by adding a `bp.php` file that calls a `bp.twig` file.
I can take care of bbPress by adding a `bbp.php` file that calls a `bbp.twig` file.
I can do the same for WooCommerce...
But what about all the other plugins that are out there?
Certainly not all of them are as well though-of as BuddyPress, bbPress or WooCommerce and not all of them have that kind of versatility when it comes to the template files they use. But even if they did, that would mean that I would have to add a `.php` & a `.twig` file for every single plugin out there.

Question is how do we make this hack obsolete and allow Timber to work with everything?
I've been developing a theme framework using TImber for about 8 months now and that question really baffles me!

**Comment by newkind** [comment]
I've seen your work @aristath and I'm really impressed by it and amount of work you've put into it. I also think that we should address this issue ASAP as this is not only affecting us (developers, who need to find workarounds to make some plugins work) but also our customers who can get a wrong impression of  Timber being not compatible with most popular plugins out-of-box. Hopefully we'll be able to come up with a nice solution that won't be a hack ;)

**Comment by ivanjuras** [comment]
+1 for this. Not that I mind, but it's just tedious to always put things into "context" like that.

**Comment by aem** [comment]
Is there an update on this? This is a blocker for a project I'm currently working on and it appears this hack may not be usable for a plugin that is required by the client

**Comment by tschoffelen** [comment]
Same here.

**Comment by palmiak** [comment]
Like @gchtr wrote - this will be hopefuly tackled in 2.0. If the https://github.com/timber/timber/issues/1639 is closed I'm closing this one too.
