### ISSUE TITLE
__toString swallows twig errors

### ISSUE THREAD

**Issue by chetzof** [timber/timber#436]
```
$context['sidebar'] = Timber::get_widgets('sidebar');
Timber::render('template.twig', $context);
```

The return object of `Timber::get_widgets('sidebar')` is `TimberFunctionWrapper` that is passed into main twig template,  which calls the object's `__toString` which in turn renders a twig subtemplate. When there are some errors inside that subtemplate, twig throws an exception with details about the error. However, because all this happens inside the `__toString` method, replaces that helpful information with useless

```
Fatal error: Method TimberFunctionWrapper::__toString() must not throw an exception in /tmp/a0/28/e67cd7e4062ab71579e38606b2ce904d472372c32e272d896153313c4fd5.php on line 0
```

([More info about this](http://stackoverflow.com/questions/2429642/why-its-impossible-to-throw-exception-from-tostring))

I found a nice workaround and adopted it for `TimberFunctionWrapper` https://gist.github.com/chetzof/3607bceac78ca875341c

**Comment by palmiak** [comment]
@chetzof Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread?
