### ISSUE TITLE
No way to use dynamic_sidebar in the view

### ISSUE THREAD

**Issue by paulwilde** [timber/timber#45]
Unless I'm missing something, there is currently no way of using WordPress widgets in any view as dynamic_sidebar() cannot be called. 

It seems you cannot add it to the get_context inside your functions.php file as dynamic_sidebar() seems to echo rather than return. There is currently no get_dynamic_sidebar either, see [here](http://core.trac.wordpress.org/ticket/13169) for the WordPress specific ticket.

If get_dynamic_sidebar did exist you could do something like:

```
// inside functions.php
$data['sidebar_footer'] = get_dynamic_sidebar('footer');

// inside twig view
{% if sidebar_footer %}
<div class="container">
    {{sidebar_footer}}
</div>
{% endif %}
```

**Comment by sb-lc** [comment]
i want to do a similar thing, i need to call a widget in my footer

where do I put this code:

$data['sidebar_footer'] = Timber::get_widgets('footer');

**Comment by asecondwill** [comment]
@sb-lc  - you could put that in your twig.php functions file where you initialise timber.  That way it is global to your view files.

**Comment by sb-lc** [comment]
I have a footer.php file but oin the standard timber / wp setup this is not used to provide data to the footer.twig file so it can't go there. do you mean a file called twig.php that stores global variables? if so how / where is it included?

**Comment by sirmacik** [comment]
Put it in functions.php (add context function).

**Comment by lukewatts** [comment]
What about is_active_sidebar? I can't figure out how to get that to work in templates/views.
