### ISSUE TITLE
TimberMenuItem, documentation should make it clear get_path strips domain name

### ISSUE THREAD

**Issue by MalucoMarinero** [timber/timber#451]
While what get_path does is by and large the best thing to do, it does hide the fact in some special cases you may want to preserve the entire link, and in those cases it's probably good to know the API to Timber Menu Item, rather than having to dig the fact out of the source.

I can add a quick addition to the bottom of the Wiki page for TimberMenu if you like, better documenting the methods on a TimberMenuItem.

**Comment by connorjburton** [comment]
Hi @MalucoMarinero - did you ever add this info to the wiki?

**Comment by MalucoMarinero** [comment]
Nope, sorry, I usually wait for a response before contributing. It's been so long since I made this issue: :D

**Comment by palmiak** [comment]
I think this is already added to documentation.
