### ISSUE TITLE
Timber WPML gettext issue

### ISSUE THREAD

**Issue by Quirksmode** [timber/timber#468]
Hi, 

For some reason I cannot get Timbers built in gettext filter to work with WPML, even though there is a translation available, it always only shows the default text.

    {{__('Example String', 'theme')}

If I run the following function in the php it works first time, and strangely the twig gettext filter above starts working too.

    _e('Example String', 'theme');

As a bonus question, I don't suppose there is an easy way to get WPML to scan .twig files for the gettext strings? I am currently having to do it manually with Poedit.

**Comment by marcoalexpinheiro** [comment]
Any hint with this?

**Comment by marcoalexpinheiro** [comment]
I found a solution for this issue. 
In functions.php add a add_filter to the getttext that manually register the string.


if (WP_ENV == "development") {

    add_filter('gettext', 'force_register_gettext_strings', 20, 3);
    function force_register_gettext_strings($translated_text, $text, $domain)
    {
        icl_register_string($domain, $text, $translated_text);
        return $translated_text;
    }

}

**Comment by Quirksmode** [comment]
Hi Marco, this works great, thanks so much!! Did you manage to solve the issue of 

    {{__('Example String', 'theme')}}

not working?

**Comment by marcoalexpinheiro** [comment]
Not yet @Quirksmode ...

**Comment by marcoalexpinheiro** [comment]
Hey @Quirksmode , I think I found a way to solve the enigma, can you try it in your project to see if it works? 
{{ function("icl_translate", "context", "string", "string") }}

**Comment by Quirksmode** [comment]
YES, you are an absolute legend, this works perfectly. Do you think there would be any performance issues with using this function?

When I ran your previous (add_filter) code I started to run into a lot of duplicate entry database warnings/errors, do you think everything is still ok with my database, could it have done some damage, did you run into similar problems?

Thanks,

Dave

**Comment by benedict-w** [comment]
I'm also experiencing this problem - is this the best workaround?

**Comment by prisis** [comment]
Im using grunt to get all translations. [take a look](https://github.com/gwa/zero)

**Comment by benedict-w** [comment]
Cool. I like that. But does it resolve the WPML issue with Timber's gettext filter not echoing translation?

**Comment by prisis** [comment]
If you can wait to tomorrow, i can test it... and tell you a solution

**Comment by benedict-w** [comment]
It's working now - it was my bad I was using a constant for the context that wasn't passed to the template!

**Comment by benedict-w** [comment]
I have the same issue as OP 

> only shows the default text
> {{__('Example String', 'theme')}

> If I run the following function in the php it works first time, and strangely the twig gettext filter above starts working too.
> _e('Example String', 'theme');

**Comment by Twansparant** [comment]
> {{ function("icl_translate", "context", "string", "string") }}
What would be the value of context and strings in this example? Can't find any proper documentation about the `icl_translate` function. All of these lines don't return the translated string for me:
```twig
{{ function('icl_translate', 'theme', 'Example String', '') }}
{{ function('icl_translate', 'context', 'Example String', 'Example String') }}
```
Thanks!

**Comment by benedict-w** [comment]
I think I resolved this by using the WPML auto-register strings feature in String Translation:

https://wpml.org/documentation/getting-started-guide/string-translation/
