### ISSUE TITLE
Debug bar shows 'error=404' query string for custom routes without a wp_query

### ISSUE THREAD

**Issue by gridsystem** [timber/timber#472]
When a route contains no post query, or points to a controller with no post query, wp debug bar shows the full, non-rewritten query string as containing 'error=404'.

I'm using the routes below.

``` php
Timber::add_route('demo', function($params){
    $query = array();
    Timber::load_template('demo.php', $query, 200, $params);
});
```

``` php
Timber::add_route('pricing', function($params){
    Timber::load_template('pricing.php');
});
```

Edit: Rephrased to make this more readable.
Edit 2: I totally screwed up this bug report, sorry. I hope this makes sense now.

**Comment by palmiak** [comment]
@gridsystem - `Timber::add_route` is deprecated now.

I tested your code using 
```
Timber::add_route('pricing', function($params){
    Timber::load_template('page.php');
});
```
and it works correctly. 

As this is an old one -  if you need any more help please respond in two weeks or we'll close this thread.
