### ISSUE TITLE
Not able to init in TimberImage

### ISSUE THREAD

**Issue by lmartins** [timber/timber#496]
Im getting a lot of these messages on my console: 
```
[06-Mar-2015 17:27:08 UTC] Not able to init in TimberImage with iid=
[06-Mar-2015 17:27:10 UTC] Not able to init in TimberImage with iid=
[06-Mar-2015 17:27:14 UTC] Not able to init in TimberImage with iid=
[06-Mar-2015 17:27:14 UTC] Not able to init in TimberImage with iid=
[06-Mar-2015 17:27:15 UTC] Not able to init in TimberImage with iid=
 ```

The view responsible for calling those images has the following code:

```twig
{% do action('tha_entry_before') %}

<article {{ fn('post_class', ['entry'] ) }}>

    <div class="Media {% if not post.thumbnail %}has-placeholder{% endif %}">

        {% do action('tha_entry_top') %}

        {% if showthumb %}
            <div class="Media-figure {% if not post.thumbnail %}placeholder{% endif %}">
                <a href="{{post.link}}">
                    {% if post.thumbnail %}
                        <img src="{{ post.thumbnail.src|resize(post_thumb_size[0], post_thumb_size[1]) }}" />
                    {% else %}
                        <span class="thumb-placeholder"><i class="icon-camera"></i></span>
                    {% endif %}
                </a>
            </div>
        {% endif %}

        <div class="Media-content">
            <h2 class="entry-title"><a href="{{post.link}}">{{post.title}}</a></h2>
            <div class="entry-details">
                {% if excerpt %}
                    <p>{{post.get_preview(20, false, __('Read More', 'wip'))}}</p>
                {% endif %}
                {% if display_meta %}
                    <div class="entry-meta">{{post.date|date("F jS\\, Y")}} in {{ post.terms('categories')|first }}</div>
                {% endif %}
            </div>
        </div>

        {% do action('tha_entry_bottom') %}

    </div>

</article>

{% do action('tha_entry_after') %}
```

Despite those messages, the front-end is working as expected. Am I missing something here?

**Comment by lmartins** [comment]
Downgraded to previous version of Timber and the console notifications are gone. Must be something with the new version.

**Comment by lmartins** [comment]
@jarednova just to let you know that i've updated to 0.21.0 but im still getting the errors above. 
If you need me to run some other tests or provide any info please let me know.

**Comment by gvinter** [comment]
+1 after updating

**Comment by Quirksmode** [comment]
I get this especially with svg's

**Comment by sidonaldson** [comment]
I too am getting this. Latest version

**Comment by connorjburton** [comment]
Looking into this, has anyone figured out specifically what causes this? I noticed a few of these errors in a recent build I have done, but can't pin-point which image it's complaining about.

**Comment by sidonaldson** [comment]
@connorjburton I already fixed my issue. It was using TimberImage in the head of my page to set the sharing image. I was using the default filter after TimberImage which meant it always tried to load a image even though it does exists, instead I use it inside TimberImage. I'm not sure if it's relevant that it was in the head but anyhoos...

It was:
```
{% set test = TimberImage(post.not_here).src|default(options.real_image) %}
```
change to:
```
{% set test = TimberImage(post.not_here|default(options.real_image)).src %}
```
I've changed the names for brevity. Hope that helps.

**Comment by connorjburton** [comment]
Okay yes that helps, I am wondering if this error is just caused by images that don't exist or incorrect usage of `TimberImage`

**Comment by sidonaldson** [comment]
Certainly, using TimberImage with a non-existent source causes the error. Maybe it's just a case of editing line 234~239 to output better logs? As mentioned above it doesn't affect the front end output

**Comment by zentheme** [comment]
In case it helps anyone, when I got this error the offending code was commented out `{# set img = TimberImage(...) #}` so I was ignoring it but apparently Timber wasn't.

**Comment by connorjburton** [comment]
Hi @zentheme - this does help. Do you happen to know what the full call was?

Thanks

**Comment by zentheme** [comment]
@connorjburton Hey Connor - yea, along the lines of 
`{# {% set randomImageUrl = TimberImage( post.empty_field_value).src %} #}`
The field was returning empty, hence no TimberImage. I had assumed commenting would cause the parser to overlook the code but that's assumptions for you!

**Comment by connorjburton** [comment]
Ah, the reason that would have ran is because to comment something out I think you would have to have done:

```
{# set randomImageUrl = TimberImage( post.empty_field_value).src #}
```

I imagine Timber just parses any `{% %}` it finds, without looking at the context of it.

Anyway, back to the issue, I think I just need to add better error logging.

**Comment by connorjburton** [comment]
When the new release of Timber comes out this should be resolved. Once it is released and if you are still getting the error `Not able to init in TimberImage with iid=` please raise a new issue.

Thanks all.
