### ISSUE TITLE
generated images are wrong colour profile?

### ISSUE THREAD

**Issue by v3nt** [timber/timber#508]
![pastedgraphic-11](https://cloud.githubusercontent.com/assets/6348562/6715659/d2fafa82-cd97-11e4-8e3c-5c1c399db980.png)

Image on left is the original uploaded rgb file. The one on the right is generated by Timber.

**Comment by v3nt** [comment]
Turns out they were uploaded as CMYK but when i convert these to rub via photoshop they are fine. Is there any way of adding a colour profile via timber?

**Comment by jarednova** [comment]
@v3nt absolutely, but it's something I'd look to you to do in a pull request. The general philosophy is to look for an underlying color profile function in WordPress (ideally) or PHP and then add a Twig filter

**Comment by jarednova** [comment]
I'm closing all 2+ year old tickets. If someone wants to pick this up, let's make it a fresh issue
