### ISSUE TITLE
Make |resize and TimberImage S3 friendly

### ISSUE THREAD

**Issue by JoaoSaleiro** [timber/timber#510]
This might be asking for too much, but it would be nice if Timber worked well with "Amazon S3 and CloudFront" plugin. 
When storing images in S3, Timber:
- is not able to resize images from S3
- when resizing a local image, Timber does not save the generated images on S3

**Comment by thisislawatts** [comment]
Hey @JoaoSaleiro, not sure how you got on with this.
I'd propose adding a filter for the generated image's url, in this instance called `timber_resized_image_src`.

Which you could then hook into your theme/plugin with something like:
```php
function mysite_asset_url( $url ) {

	if ( true === global_is_production_env_check() ) {
		return str_replace( 'example.com', 'example.cloudfront.net', $url );
	}

	return $url;
}
add_filter('timber_resized_image_src', 'mysite_asset_url');
```

**Comment by smilingpeanut** [comment]
Any movement on this? Still can't resize images that are hosted on S3.

**Comment by jarednova** [comment]
I'm closing all 2+ year old tickets. If someone wants to pick this up, let's make it a fresh issue
