### ISSUE TITLE
Filtering TimberQueryIterator

### ISSUE THREAD

**Issue by alexsomeoddpilot** [timber/timber#514]
Is there a good way to filter the post array of a TimberQueryIterator?

I'm currently hacking around this using the `get_posts` method.

``` php
function (TimberQueryIterator $posts) {
  return array_filter($posts->get_posts(), function ($post) {
    return get_field('featured', $post->id);
  });
}
```

Is there a way to preserve the pages query variables while filtering it?

**Comment by palmiak** [comment]
Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread.
