### ISSUE TITLE
resize filter should take a TimberImage and return a new TimberImage instance

### ISSUE THREAD

**Issue by teohhanhui** [timber/timber#523]
i.e. `{{ post.thumbnail|resize(width=650, height=650).src }}`

**Comment by teohhanhui** [comment]
This would be an ideal abstraction in my view, but I realize the current implementation doesn't allow this...

**Comment by connorjburton** [comment]
I am not sure I agree with a filter returning something that is then accessible, a filter is just supposed to manipulate the data, not return anything.

Either way, I don't think we would be changing this at this point as it may cause backward compatibility issues.
