### ISSUE TITLE
More elegant multipage-based pagination

### ISSUE THREAD

**Issue by kylehotchkiss** [timber/timber#529]
I was having some issues getting multipage based pagination running. I peeked around the wordpress source code and found a few tidbits that got it working for me. [Per your tweet](https://twitter.com/jaredNova/status/590866585579028480), here's what I did to get it working locally.

```
<?php
    // Timber support for Multipage
    global $post, $page, $pages, $multipage;
    setup_postdata( $post );

    $data = Timber::get_context();
    $data['post'] = new TimberPost();

    // Overwrite whole post with paginated piece, if viewing a
    // paginated page of the overall post
    if ( $multipage ) {
        $data['post']->post_content = $pages[ $page - 1 ];
    }

    Timber::render('single.twig', $data);
?>
```

I'm sure there's a cleaner way to do this - perhaps `TimberPost` handles all the `setup_postdata()`, and all those globals? And it should handle that `if` statement, it's a bit hard to tell form looking at it what it's doing.

Thanks Jared!

**Comment by haroldangenent** [comment]
:+1:

**Comment by palmiak** [comment]
Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
