### ISSUE TITLE
Video embed issue with Timber themes

### ISSUE THREAD

**Issue by TahsinAbrar** [timber/timber#536]
I'm facing a weird problem when I'm developing a theme with Timber. Whenever I embed a youtube video link into a post, the `_oembed` custom meta attributes automatically added to some other posts also. And after each new post, the video `_oembed` attributes automatically add to their custom meta attributes.

I need to check if the post contains `_oembed` custom meta attributes or not. And it shows wrong information because of this. Because the video `_oembed` attributes added to the other posts custom meta attributes.
But with normal Wordpress theme, it's absolutely working. I suppose the issue is related to timber. I tried with [blades theme](https://github.com/Upstatement/blades). And it shows the same result.

Can anyone please give me any guideline?

**Comment by palmiak** [comment]
Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread.
