### ISSUE TITLE
Using a hardcrop with | resize()

### ISSUE THREAD

**Issue by tmyie** [timber/timber#541]
Hey,

Love the plugin. :+1: 

I'm using WooCommerce and trying to get a hard crop based on an image URL. I'm currently using `| resize(100, 100)`.  However, it seems to be doing a soft crop.  [Examples here of the difference between them.](http://havecamerawilltravel.com/photographer/wordpress-thumbnail-crop)

I was wondering whether a hard crop was included with Timber? If not, is there any WP documentation on the Image API it's using?

**Comment by luukdv** [comment]
Setting both arguments on the `resize` filter will actually hard crop your image, you can do soft crops by omitting one of the arguments or using letterbox. See http://timber.github.io/timber/#image-cookbook.

**Comment by palmiak** [comment]
Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
