### ISSUE TITLE
<!--more--> tags don't work in post.content

### ISSUE THREAD

**Issue by ncaroyannis** [timber/timber#546]
Using `Timber::get_posts()` returns an array of posts, but `post.content` doesn't seem to take in to account / format the `<!--more-->` like `the_content()` would. I can't seem to use `post.content|apply_filters('the_content')` either.

Any way to get it to use the default formatting that Wordpress outputs? `post.post_content` doesn't seem to work with filters, either.

**Comment by jnweaver** [comment]
I don't know if this will solve your issue, but I think the following is the correct way to call apply_filters within Twig (because *apply_filters* is a Wordpress function, not a Twig filter):

```
{{ function( 'apply_filters', 'the_content', post.content ) }}
```

I'm not sure that will produce the result you want. You could also try using get_preview() which should detect the  tag. You'd also want to run it through apply_filters as such:

```
{{ function( 'apply_filters', 'the_content', post.get_preview() ) }}
```

[This thread](https://github.com/jarednova/timber/issues/445) is related.

**Comment by designfix** [comment]
Doesn't seem to work either unfortunately, they both produce the same results as the apply_filters twig filter ([it's built in to Timber](https://github.com/jarednova/timber/wiki/WP-Integration#filters)).

`get_preview` uses it's own method for pulling out the content, which strips both the formatting and images.

**Comment by developer-lindner** [comment]
Any update here?

**Comment by gajama** [comment]
Not sure if it will help anyone but I got this to work more-or-less like it had before I started using Timber by doing the following:

`{{ fn( 'apply_filters', 'the_content', post.get_preview(50, false, "<br/>(more...)") ) }}`

Explicitly setting the read more text in the call to `get_preview` because otherwise it defaults to "Read More" and overrides any customisation.

**Comment by gajama** [comment]
After a bit of fiddling around the following more idiomatic way also works for my use case:

` {{ post.get_preview(50, false, more)|apply_filters('the_content') }}` with `more` being passed from the context as in my previous comment.

**Comment by gajama** [comment]
The following works for me:

`{{ post.get_preview(50, false, more)|apply_filters('the_content') }}`

With "more" in the get_preview call being the text and markup I want for the "Read more" link passed in via the context. For example:

`$context['more'] = "<br/>(more...)";` or

`$context[ 'more' ] = '<br/>(more...)<img src="' . get_bloginfo('template_directory'). '/images/more.gif" alt="read more" title="Read more..." />';`

Hope this helps.

**Comment by Beee4life** [comment]
I know it's a late comment, but why not use 
`{{ function( 'the_content', '', true ) }}`

**Comment by danicholls** [comment]
Having apparently the same issue in 2017..

**Comment by danicholls** [comment]
My hacky solution, since I found `get_preview` fetches everything (all HTML) in `post_content` if there's a more tag, but otherwise strips tags.(.?) Fortunately, a binary is okay with me--if a 'more' tag, show all up to it; if not, show full.

```twig
{% set split_content = post.content|split('<!--more-->') %}

{% if split_content|length > 1 %}
    {# has more tag #}
    {{ post.get_preview( split_content|split(' ')|length + 1, false, 'Read more..', false )|apply_filters('the_content') }}
{% else %}
    {{ post.content }}
{% endif %}
```

**Comment by ecksite** [comment]
Not the best solution, due to the fact that the "get_preview" function is depreciated but this works for me:

```twig 
<div property="text">
    {{ post.get_preview(50,false,false,true) }}
</div>

{# the "more" link #}
{% if post.get_preview(50,false,false,true) %}
    <a class="myclass" title="mytitle" href="{{ post.link }}">Post Title</a>
{% endif %}
```

**Comment by jarednova** [comment]
Here's an even simpler usage (using the `PostPreview` class):

Given a post like...

```
In my younger and more vulnerable years my father gave me some advice that I’ve been turning over in my mind ever since.
<!-- more -->
“Whenever you feel like criticizing any one,” he told me, “just remember that all the people in this world haven’t had the advantages that you’ve had.”
```

Try ...
```twig
{# index.twig #}
<div property="text">
    {{ post.preview }}
</div>
```

Which will display:
```html
<div property="text">In my younger and more vulnerable years my father gave me some advice that I’ve been turning over in my mind ever since. <a href="http://example.org/2018/10/great-gatsby" class="read-more">Read More</a>
```

To customize the read more tag (one of the few HTML things in Timber you can't do directly in a `.twig` file):

```twig
{# This is how you change the text inside the <a> tags #}
<div property="text">
    {{ post.preview.read_more('Keep Reading') }}
</div>
```

```php
/* functions.php */
/**
 * Modify the CSS classes on the <a> tags in a post's preview 
 */
add_filter('timber/post/preview/read_more_class', function($read_more) {
 return $read_more . " my-awesome-css-class";
}
```
