### ISSUE TITLE
woocommerce.php seems not to work

### ISSUE THREAD

**Issue by ylcdx** [timber/timber#555]
Hi,

I follow the doc to integrate woocommerce (https://github.com/jarednova/timber/wiki/WooCommerce-Integration) but nothing append when I change html in template single-product.twig 

And if I add a "die" in the file 'theme / woocommerce.php' nothing happens.

My woocommerce.php file :

``` php
if (!class_exists('Timber')){
    echo 'Timber not activated. Make sure you activate the plugin in <a href="/wp-admin/plugins.php#timber">/wp-admin/plugins.php</a>';
    return;
}

$context            = Timber::get_context();
$context['sidebar'] = Timber::get_widgets('shop-sidebar');

if (is_singular('product')) {
    $post = Timber::get_post();
    $context['post']    = $post;
    $product            = get_product( $context['post']->ID );
    $context['product'] = $product;

    Timber::render('views/woo/single-product.twig', $context);

} else {

    $posts = Timber::get_posts();
    $context['products'] = $posts;

    if ( is_product_category() ) {
        $queried_object = get_queried_object();
        $term_id = $queried_object->term_id;
        $context['category'] = get_term( $term_id, 'product_cat' );
        $context['title'] = single_term_title('', false);
    }

    Timber::render('views/woo/archive.twig', $context);

}
```

in my functions.php, I add the woocommerce support : 

``` php
function woocommerce_support() {
        add_theme_support( 'woocommerce' );
}
add_action( 'after_setup_theme', array($this, 'woocommerce_support' ));
```

And the helper for loop product :

``` php
function timber_set_product( $post ) {
    global $product;
    if ( is_woocommerce() ) {
        $product = wc_get_product($post->ID);
    }
}
```

Any ideas, why woocommerce.php doesn't work ? 

Thanks.

**Comment by connorjburton** [comment]
Hi @ylcdx - is this still an issue for you?

**Comment by ylcdx** [comment]
Hi, i didn't test it since, but if woocommerce debug option is set on true, the woocommerce.php file in my theme doesn't work.

**Comment by connorjburton** [comment]
Does it work with Timber disabled?

**Comment by Annalyn** [comment]
I also follow woocommerce.md and my issue is that shop and product page is not displaying at all whether debug is set to true or false.

**Comment by aronvandervalk** [comment]
Try adding the support tag declaration to your functions.php
This worked for me:

`add_theme_support( 'woocommerce' );`

**Comment by palmiak** [comment]
@ylcdx @Annalyn Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
