### ISSUE TITLE
Cannot create case-insensitive route

### ISSUE THREAD

**Issue by jmp909** [timber/timber#560]
I'm trying to create a route for "/blog" to add my own custom functionality, but if a user goes to /Blog or /BLOG etc instead for some reason, then it's missing the route and picking up the default wordpress blog functionality, which seems to ignore the case.

for now I've added a plugin to force lowercase URLs instead, but it would be good to be able to specify whether the route was case sensitive or not

thanks
j

**Comment by jarednova** [comment]
@jmp909 the routes you find are a wrapper for [AltoRouter](https://github.com/dannyvankooten/AltoRouter) is there something in there that allows for case-insensitivity? I'd be happy to add a filter or variable to activate it

**Comment by jmp909** [comment]
It does appear to have regular expressions (as well as other kinds of matches) so maybe something using that? 

http://altorouter.com/usage/mapping-routes.html

Also whilst we are discussing it, I was having trouble trying to match for example anything below /somedir eg /somedir/blah/ and /somedir/blah/something/ etc .  basically I wanted to custom 404 any access to /somedir/* (as opposed to just /somedir/) but couldn't seem to do it . Regular expressions should also likely help here?

Thanks
J

**Comment by connorjburton** [comment]
Hi @jmp909, did you ever solve this and is it still an issue for you? Just clearing up some issues.
