### ISSUE TITLE
Child Theme Views

### ISSUE THREAD

**Issue by matthewsoares** [timber/timber#57]
It appears that Child theme views don't get priority over parent theme views. Is this normal behavior. If so how do I correct this? I would like child views to overwrite parent views.

**Comment by zachwolf** [comment]
I'm not sure if this is the right place for this, but does the child theme mentioned above exist anywhere public? I'm having a real heck of a time trying to get a child theme to load parent pages without a ton of code duplication.

This is a barebones version of my file structure:

```
parenttheme/
    |- views/
        |- base.twig
        |- page-example.twig
    |- style.css
    |- functions.php
    |- index.php
    |- page-example.php
childtheme/
    |- views/
        |- unique.twig
    |- style.css
    |- functions.php
    |- index.php
```

My expectations (let me know if these are wrong), is that when viewing a page with `childtheme` active and `page-example.php` as the template, it would use the `parenttheme/page-example.php` template. However, it just uses `childtheme/index.php` no matter what.

In the example theme, there is the `page.php` which got me part way to a working solution.

```php
<?php
// `timber-starter-theme-master/page.php`
/**
 * The template for displaying all pages.
 *
 * This is the template that displays all pages by default.
 * Please note that this is the WordPress construct of pages
 * and that other 'pages' on your WordPress site will use a
 * different template.
 *
 * To generate specific templates for your pages you can use:
 * /mytheme/views/page-mypage.twig
 * (which will still route through this PHP file)
 * OR
 * /mytheme/page-mypage.php
 * (in which case you'll want to duplicate this file and save to the above path)
 *
 * Methods for TimberHelper can be found in the /lib sub-directory
 *
 * @package  WordPress
 * @subpackage  Timber
 * @since    Timber 0.1
 */

$context = Timber::get_context();
$post = new TimberPost();
$context['post'] = $post;
Timber::render( array( 'page-' . $post->post_name . '.twig', 'page.twig' ), $context );
```

If `$post->post_name` is the same as my template name, "example" in this case, then that finds the right template. However, if `$post->post_name` is something else, like "My Cool Post", then I get an error that "page-My Cool Post.twig" doesn't exist.

My current work-around is to create a file in `childtheme/page-example.php` that just requires the parent theme file, like:

```php
<?php

/*
Template Name: Membership
*/

require_once( ABSPATH . 'wp-content/themes/parenttheme/page-membership.php' );
```

I don't love this approach and it doesn't seem like the intended behavior.

Any guidance on this? I've tried stackoverflow thinking that perhaps I was doing something wrong, but without any success. Thanks for your time!
