### ISSUE TITLE
Timber Bug: queried_object lost with pagination 

### ISSUE THREAD

**Issue by katipierson** [timber/timber#580]
Hello,
i have a custom taxonomy named "interpret". 

My Permalink ist also /interpret/slug/page/3.

I wrote in function.php 

Timber::add_route(':taxonomy/:name/page/:pg', function($params){
    $query = $params['taxonomy'].'='.$params['name'].'&paged='.$params['pg'];
    Timber::load_template('taxonomy.php', $query);
});

Solong it works and i become the right side, but in $wp_query the ["queried_object"] and ["queried_object_id"] are empty and so the breadcrumb, wp_title an other fields are empty.

Can you help me?

Greetings
Kati

**Comment by palmiak** [comment]
@katipierson Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
