### ISSUE TITLE
TimberImage Resize returning incorrect URL

### ISSUE THREAD

**Issue by leefroese** [timber/timber#598]
Since updating Timber to 0.21.5 I've been finding that the resize function on TimberImages doesn't return the absolute URL and is causing issues. I am using

```
<img src="{{TimberImage(item.slide).src|resize(670,410)}}" />
```

This outputs "site-files/f37ca7b351defda658e8ed2dda9bdfa6-200x180-c-default.jpg" instead of "http://localhost:8888/ipw/site-files/f37ca7b351defda658e8ed2dda9bdfa6-200x180-c-default.jpg"

**Comment by jarednova** [comment]
Thank you @leefroese. I notice you don't have a `wp-content` folder (which is fine) can you tell me a little bit more about your setup so I can properly simulate on my end? Is it a single site? Multisite? Can you send me the values for the `siteurl` and `home`? Thanks!

**Comment by leefroese** [comment]
I have `wp-content/uploads` set to `site-files`. It is a single site. The `siteurl` and `home` are `http://localhost:8888/ipw`.

I've found that adding the `{{site.url}}` works, but I didn't used to have to do that. The image is inside an ACF repeater, not sure if that makes a difference.
```
{% for item in post.get_field('slider') %}
    <li>
        <img src="{{site.url}}/{{TimberImage(item.slide).src|resize(670,410)}}" />
    </li>
{% endfor %}
```

**Comment by leefroese** [comment]
Here's what Timber is outputting for a link as an example '/site-files//007aa54f53162facb93318c223a9fbd8-280x0-c-default.jpg'

**Comment by leefroese** [comment]
It seems like the image URL to the resized URL is correct initially. If I make a change such as updating the ACF fields, or there's multiple image fields used, the url changes to something like `/site-files//007aa54f53162facb93318c223a9fbd8-280x0-c-default.jpg`

**Comment by zlove** [comment]
I believe this code in TimberImageHelper::_get_file_url() might be the culprit. It can result in a bad image url:

    private static function _get_file_url($base, $subdir, $filename, $absolute) {
        ...
        if(!$absolute) {
            $url = str_replace(home_url(), '', $url);
        }
        ...
    }

If Wordpress is setup at a subdirectory like `http://www.example.com/wordpress-here/` a correct image url would be like `/wordpress-here/wp-content/2015/11/some-image.jpg`. The code above will strip out not just the host/protocol but also the `/wordpress-here/` leaving an incorrect url of `/wp-content/2015/11/some-image.jpg`.

This came up for me when:

1. Wordpress is installed in a subdirectory
2. I used the `resize()` filter in a Twig view with an image src that is a URL on a different domain.

**Comment by oxyc** [comment]
Another line where `home_url()` breaks sites with WPML is https://github.com/jarednova/timber/blob/c1c82d70ca0b9b9cd1e75a221ae18b44d0bca83a/lib/timber-image-helper.php#L339:L341

```php
if (!$result['absolute']) {
  $tmp = site_url().$tmp;
}
```

**Comment by jarednova** [comment]
@oxyc @leefroese — we have a solution to this in #1027 that's now in `master`: can you confirm that this solves your issue? (h/t @connorjburton)

**Comment by leefroese** [comment]
@jarednova yes issue is solved for me, thanks!
