### ISSUE TITLE
Needs better error_log handling

### ISSUE THREAD

**Issue by ocReaper** [timber/timber#621]
Personally I like logs. They are excellent in debugging and checking if the system works fine. Timber has an error log function which drops everything into the apache log, but some times it's not used and is not configured properly, nor as useful as it can be.

**Comment by ocReaper** [comment]
Hello @drzraf,
So it seems this after 3 years this pull request is working?

**Comment by ocReaper** [comment]
Accidentally closed this issue..

Anyways any of the Timber crew can update me, about the reason this issue and the corresponding PR is still open?

I hope someone updated the logging system or the project started using monolog or other trusted library for logging.

**Comment by jarednova** [comment]
Hi @ocReaper apologies for the long delay here. I'd love to pick this back up if you are. Unfortunately I'd need you to re-submit the PR from way back based on the current master. Here are a few thoughts to making it 💯 ...

1) I can see the backtrace being valuable — but also potentially providing an overwhelming amount of lines. Can we make that something that users opt into based on their configuration?
2) In WP most debug stuff is set by constant (think `WP_DEBUG`), what do you think about changing the Timber log directory and backtrace vars to constants?

**Comment by jarednova** [comment]
I'm closing all 2+ year old tickets. If someone wants to pick this up, let's make it a fresh issue

**Comment by drzraf** [comment]
Are errors now prefixed by "Timber" or something?

**Comment by jarednova** [comment]
@drzraf yep! will be released/deployed early next week to Packagist and WP.org
