### ISSUE TITLE
Integrate with the most popular multilingual plugins.

### ISSUE THREAD

**Issue by davidmaneuver** [timber/timber#631]
I think it would come in handy to expose a method to retrieve a translation of a post.

`````php
$post = new TimberPost(1);
$translated_post = $post->get_translation();
`````

The method could look something like this: (I didn't test this)
`````php
public function get_translation($lang = '') {
  /* Polylang Plugin */
  if (function_exists(pll_get_post)) { // or some other way to check if the plugin is activated.
    $trans_pid = pll_get_post($this->id, $lang);
    return ($trans_pid == $this->id ? $this : new TimberPost($trans_pid));
  }
  /* WPML Plugin */
  // the WPML way
}
`````

Maybe best implemented as a Timber Integration?

Some thoughts on this?

**Comment by Apeli** [comment]
Yes, Polylang integration would be real nice. 

Meanwhile, I use this to get the permalink for a Polylang-translated post:

```php
// In StarterSite::__construct, for exampla

...
add_filter('get_twig', array($this, 'add_twig_pll'));
...

//Then
function add_twig_pll($twig) {
		$function = new Twig_SimpleFunction('pll_permalink', function ($id) {
			return get_permalink(pll_get_post($id));
		});
		$twig->addFunction($function);
		return $twig;
	}

//Usage
{{pll_permalink(10)}}

````

**Comment by JakeHenshall** [comment]
@Apeli Hi, how did you incorporate this into your theme. as a drop down in the menu or on each page / post. Thanks

**Comment by Apeli** [comment]
The pll_permalink -function that adds can be used only directly in the *.twig templates.

As in
`<a href="{{pll_permalink(10)}}">Link</a>`

**Comment by connorjburton** [comment]
Hi guys,

I think for now our preferred route would be add-on plugins to Timber (like Timmy https://github.com/MINDKomm/Timmy) that have these integrations.

Thanks,
Connor
