### ISSUE TITLE
get_comments() should be able to return flat array of comments

### ISSUE THREAD

**Issue by newkind** [timber/timber#632]
Hey!

This is the thing that I came up today while working on the nested comments. I wanted to go with approach of using `wp_list_comments` WP function with my custom callback and pass `post.get_comments` as the source array with all comments.

The issue : because of how `TimberPost::get_comments()` work, I could only get the array of parent comments (12 items instead of 22) with child comments placed in child array under each parent item. Because of that I wasn't able to render any comments that weren't parent. 

Cause : When `TimberPost::get_comments()` is in the use it checks if the current comment is a child comment (`if ($comment->is_child()) {`) and places it in the child array. The only way to prevent this from happening right now is create own class which extends TimberComment class and overrides `is_child()` to `return false;` and provide our new class as the `$CommentClass` argument.

Solution : Maybe we should add one more argument `$flat = false` to `TimberPost::get_comments()` that would allow user to decide if he wants a flat list of comments or one with nested child arrays ?

What do you guys think ?

**Comment by newkind** [comment]
Any opinions here ? :)

**Comment by BertmV** [comment]
I just filed an issue #954 because I need this to actually be nested more than 1 level. Perhaps the solution would be to add a `$level` argument which defaults to the value set in Wordpress `Settings -> Discussion` setting of _Enabled threaded comments ... levels deep_

**Comment by palmiak** [comment]
@newkind Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread

**Comment by newkind** [comment]
Sorry, I haven't been working on this for a while, so you can close it if you want to.
