### ISSUE TITLE
Rethink get_preview API

### ISSUE THREAD

**Issue by jarednova** [timber/timber#65]
Looking for feedback on how to best structure this method, currently it's:

{{post.get_preview(60, $force, 'Read More >>', $strip_tags)}}

where.
60 (number of words to show), 
$force (whether to "force" manually set post excerpts to a shorter length; or let them in at full length)
'Read More >>' (read more hyperlink)
$strip_tags (strips any tags found in the text)
#### Some questions...
- Should arguments be re-ordered?
- How to handle ellipses that are added?
- Should some of this be controlled by global vars or filters?

**Comment by jeffjack** [comment]
For those looking for a way to remove the ' `&hellip;` ' string and don't want to edit the plugin files (don't edit the plugin files. bad. no.), you can just set up a simple script to switch that out with something else:

in your twig file:

    {{post.get_preview(25,false,"",true)|fixEllipsis}}


in your functions.php:

    function add_to_twig($twig){
        $twig->addFilter('fixEllipsis', new Twig_Filter_Function('fixEllipsis'));
        return $twig;
    }
    add_filter('get_twig', 'add_to_twig');

    function fixEllipsis($text){
        $text = str_replace(' &hellip; ', '&hellip;', $text);
        return $text;
    }

**Comment by aeblin** [comment]
@jeffjack Digging the concept, but I can't seem to make that work. Any idea if things may have changed since you threw that together?

**Comment by jeffjack** [comment]
@aeblin Hmm it's still working for me after updating to Timber 0.21.7. I'm on WP 4.2.2 as well. I didn't include it in the example above for the sake of brevity, but make sure you also add the StringLoader extension to $twig as well. For example:
```
function add_to_twig($twig){
    $twig->addExtension(new Twig_Extension_StringLoader());
    $twig->addFilter('fixEllipsis', new Twig_Filter_Function('fixEllipsis'));
    return $twig;
}
add_filter('get_twig', 'add_to_twig');
```
Here's another example use in a twig file:
```
{{post.get_preview(50,false,"Read More",true)|fixEllipsis({'text_replacement': '&hellip; '})}}
```

**Comment by aeblin** [comment]
Hmm, even with the StringLoader extension added, I tend to just get back a syntax error.
```
 unexpected 'add_filter' (T_STRING), expecting function (T_FUNCTION)
```

**Comment by jeffjack** [comment]
Sorry, I was wrong. I think it's due to a final trim added when the $text is returned in the get_preview function in timber-post.php. My str_replace was looking for spaces on each side of the `&hellip;` and that final trim removed that space after. Switch the search string to `' &hellip;'` and it should start working.
