### ISSUE TITLE
get_query_var() Incompatible with Timber Routes? 

### ISSUE THREAD

**Issue by timothymalcham** [timber/timber#657]
I've got a route that looks like this:

```
Timber::add_route('episodes/page/:page', function($params) {
    $query = array(
      'post_type' => 'episode',
      'posts_per_page' => 10,
      'paged' => $params['page']
    );

    Timber::load_template('show-episodes.php', $query, 200, $params);
  });
```

On the `show-episodes.php` template I'm using `get_query_var()`, but that function doesn't seem to work on any page that uses Timber routes, while on any page that doesn't use routing, the method works just fine. I assume the query_vars are being overwritten or something like that (I'm unfamiliar with the relevant internals)? Is there a workaround that would allow me to get query variables from the url?

**Comment by jasperrooduijn** [comment]
Any news on this?
