### ISSUE TITLE
next_post_link with argument

### ISSUE THREAD

**Issue by MateuszCisowski** [timber/timber#671]
Hi,

First of all - great job with Timber!

I have small issue with function. What I'm trying to achieve is a next/prev links for the custom post types with my labels.

Example from Codex:
`<?php next_post_link( '%link', 'Next post in category', TRUE ); ?>`

When I use just function (without any arguments) in this way:
`{{ function('previous_post_link') }}`
it works correctly but when I add arguments:
`{{ function('previous_post_link', '%link', 'next project', TRUE) }}`
nothing shows up.

I'll be really grateful for help.
Thanks in advance!

**Comment by MateuszCisowski** [comment]
I have tried with the
`$context['pagination'] = Timber::get_pagination();`
and in my twig file
`<a href="{{ pagination.prev.link }}">next project</a>`

and it doesn't work... "next project" links to the current page.

What is strange is that when I delete `$content['pagination']` it works exactly the same...  when I dump `$context['pagination']` it shows
`array(2) { ["pages"]=> array(0) { } ["prev"]=> string(0) "" }`

Any ideas?

**Comment by MateuszCisowski** [comment]
OK, I have found temporary solution, I paste it below in case that someone will need it:
```
$next_post = get_previous_post();
if ( is_a( $next_post , 'WP_Post' ) ) {
   $context['nextPost'] = '<a href="' . get_permalink( $next_post->ID ) . '">' . 'next project' .  '</a>';
}

$prev_post = get_next_post();
if ( is_a( $prev_post , 'WP_Post' ) ) {
    $context['prevPost'] = '<a href="' . get_permalink( $prev_post->ID ) . '">' . 'previous project' .  '</a>';
}
```

However I'm still curious how to solve this problem using first (function with arguments) and second (Timber::get_pagination) approach. Thanks!

**Comment by stewarty** [comment]
I think I might be running into something similar.

I'm trying to get previous/next posts within the same category but Timber's post object is having none of it  , both the prev() & next() methods are returning false.

`$context['post']->next = $post->next(true);
$context['post']->prev = $post->prev(true);`

**Comment by connorjburton** [comment]
Thanks for the update @stewarty, will look at this next week

**Comment by henrikwirth** [comment]
For me `$context['pagination'] = Timber::get_pagination();` returns only this:
```
array (size=5)
  'current' => int 1
  'total' => float 1
  'pages' => 
    array (size=0)
      empty
  'next' => null
  'prev' => string '' (length=0)
```
Any thoughts?

**Comment by gchtr** [comment]
@henrikwirth On a single page, you wouldn’t use the pagination that allows you to make a list of pages that list a certain amount of posts. Usually, you use a pagination only for archive pages.

Do you want to show a link to the next post on a single post? In that case, you would use the `prev()` and `next()` methods on a post.

**single.php**

```php
$context = Timber::get_context();
$context['post'] = new Timber\Post();

Timber::render( 'single.twig', $context );
```

**Twig**

```twig
{% if post.prev %}
    <a href="{{ post.prev.link }}">{{ post.prev.title }}</a>
{% endif %}

{% if post.next %}
    <a href="{{ post.next.link }}">{{ post.next.title }}</a>
{% endif %}
```

**Comment by joelkobjoll** [comment]
Im running into the same issue, I have a custom type and im trying to get previous and next post object, but timber is always returning null.

Currently its returning:

`object(Timber\Pagination)#6169 (5) {
  ["current"]=>
  int(1)
  ["total"]=>
  float(1)
  ["pages"]=>
  array(0) {
  }
  ["next"]=>
  NULL
  ["prev"]=>
  string(0) ""
}`

I also hace a look at the dump of $context['post'] = new Timber\Post();

`["_next":protected]=>
  array(0) {
  }
  ["_prev":protected]=>
  array(0) {
  }`

Not sure if its not being updated with any of the new changes since this issue is actually pretty old.

**Comment by Luckyfella73** [comment]
@gchtr Do we have a nice option to loop through the posts using {{ post.prev.link }} in case there is no previous post? Would be nice to have the possibility to link to the last post in that case and from the last to the first post on {{ post.next.link }}.

**Comment by palmiak** [comment]
@Luckyfella73 I think it would be better if you start a sepearate issue (as I understand you would like `post.first.link` and `post.last.link` feature). 

@henrikwirth as I see everything is clear. Can I close this issue?

**Comment by henrikwirth** [comment]
@palmiak everything clear, yup, thanks

**Comment by akolbo** [comment]
Is it possible to use post.prev and post.next to deliver a custom query? Right now I'm getting all posts of my custom post type. I'm using a single template file.

**Comment by jarednova** [comment]
Absolutely @akolbo — just write a custom class that overrides those functions!

https://timber.github.io/docs/guides/extending-timber/

**Comment by akolbo** [comment]
@jarednova, if I need a custom query then will I place the custom class outside of the StarterSite class in functions.php? I've read that the WP_Query function is bad because it makes an additional query, so then the pre_get_posts filter would be the better way to go. I am mostly hacking my through this, but this is what I have sitting outside of StarterSite class:
```
class MyProjectPosts extends Timber\Post {

	public function project_filter_query( $query ) {

		if ( is_singular( 'projects' ) ) {
			
			$query = array(				
				'numberposts' => -1,
				'post_type' => 'projects',
				'meta_key' => 'featured',
				'meta_value' => 1,
				'order' => 'ASC', 
				'orderby' => 'order_clause',
				'meta_query' => array(
					'order_clause' => array(
							'key' => 'order_number',                         
							'type' => 'NUMERIC' // unless the field is not a number    
					)
				)
			); //end $query
	   
	   } else {
			//do nothing
	   }
		
	}	
	add_action('pre_get_posts', 'project_filter_query')		
}
```

Does this look anywhere close to a starting point??

**Comment by jarednova** [comment]
@akolbo — there could very well be a path there, but it's not one I'd recommend. At least, not in the "Timber way." The place that I think would be easiest would be ...

```php

class MyProjectPost extends Timber\Post {

	public function next() {
			$query = array(				
				'numberposts' => -1,
				'post_type' => 'projects',
				'meta_key' => 'featured',
				'meta_value' => 1,
				'order' => 'ASC', 
				'orderby' => 'order_clause',
				'meta_query' => array(
					'order_clause' => array(
							'key' => 'order_number',                         
							'type' => 'NUMERIC' // unless the field is not a number    
					)
				)
			);
			$posts = new Timber\PostQuery($query);
   			return $posts[0];
	}	
}
```

and then on your `single.php` you'd be getting 
```php
$context['post'] = new MyProjectPost();
```
... so that you're using the custom class you've created

**Comment by akolbo** [comment]
That is doing something, thank you! But maybe there's something wrong with my query. As is, {{ post.next.link }} url is returning the first post in the query.

**Comment by jarednova** [comment]
@akolbo ahhhhh now I see the problem (and why you went with the `pre_get_posts` route before). I think what you have here is just a trick WP query problem. You've got essentially a custom "order" of things (based on `order_clause`).

What I think you'd want to do is ...
* query _everything_ via a first query with [just IDs returned](https://developer.wordpress.org/reference/classes/wp_query/#return-fields-parameter)
* Find the "current" post ID in the resulting array, and then save the previous and next IDs in that array to (something like) `$this->next_id` and `$this->prev_id`
* Use those properties to retrieve the appropriate post object with the full data

It's a bit hacky, but it's also pretty straightforward. You could also preserve the results of the first query (which is probably the most expensive one) in a transient or other cache object

**Comment by akolbo** [comment]
@jarednova – Well I gave it a try anyway. At least it's not working the way I wrote it!

```php
class MyProjectPost extends Timber\Post {

	// Query everything via a first query with just IDs returned
	public function projects_query() {
		$args = array(				
			'fields' => 'ids',
			'numberposts' => 6,
			'post_type' => 'projects',
			'meta_key' => 'featured',
			'meta_value' => 1,
			'order' => 'ASC', 
			'orderby' => 'order_clause',
			'meta_query' => array(
				'order_clause' => array(
					 'key' => 'order_number',                         
					 'type' => 'NUMERIC' // unless the field is not a number    
				)
			),						
		);

		$posts = new Timber\PostQuery( $args );		
		return $posts;			
	}	
	// Find the "current" post ID in the resulting array
	public function current_id() {	
		$current_id = get_the_ID();
		return $current_id;
	}
	// Save the previous and next IDs in that array to $this->next_id
	public function next_id() {	
		$next_id = $this->next_id(get_next_post($current_id));
		return $this->next_id;			 
	}
	// Save the previous and next IDs in that array to $this->prev_id
	public function prev_id() {			
		$prev_id = $this->prev_id(get_prev_post($current_id));
		return $this->prev_id;
	}	

} //end class MyProjectPost		

```

**Comment by dualstudiocz** [comment]
Hi, I looking something like this but for subpages.

Structure: 

Page 1
------Subpage 1A
------Subpage 2A

Page 2
------Subpage 1B
------Subpage 2B

This solution works fine:

```
{% if post.prev %}
     <a href="{{ post.prev.link }}">{{ post.prev.title }}</a>
{% endif %}

{% if post.next %}
     <a href="{{ post.next.link }}">{{ post.next.title }}</a>
{% endif %}
```

... but on Subpage 1A is a link on Page 2. I need to stay inside Page and its Subpages. Someone help please?
