### ISSUE TITLE
WPMUDEV Chat + Twig "bug". Ajax call not functioning

### ISSUE THREAD

**Issue by DannyvanHolten** [timber/timber#672]
Hey Guys,

We're building a big project with Twig, but I've encountered somewhat of a problem.
If I install the WPMUDEV Chat plugin it won't function properly.

It will function properly when I have the possibility to "manage_options" assigned to my role. It will not function if i'm not logged in or don't have that options. It seems that the ajax functions or the plug-in cannot acces the necessary ajax files if "manage_options" is not present.

Hopefully anybody is able to help me.

**Comment by connorjburton** [comment]
Hi @DannyvanHolten - does this happen if Timber is disabled?
