### ISSUE TITLE
Remaining Documentation Items

### ISSUE THREAD

**Issue by jarednova** [timber/timber#690]
- [ ] TimberMenu
  - [ ] Internals marked
- [ ] TimberMenuItem
  - [ ] Class usage intro
  - [ ] Class usage example
  - [ ] Internals marked
- [ ] Merge Prior Wiki Docs
  - [ ] Caching
  - [ ] Configure Template Locations
  - [ ] Custom Page Templates
  - [ ] Debugging
  - [ ] Extend Timber
  - [ ] Image Manipulation
  - [ ] Menus
  - [ ] Performance & Caching
  - [ ] Routing
  - [ ] Text Manipulation
  - [ ] Widgets (Dynamic Sidebar)
  - [ ] WooCommerce Integration
  - [ ] WordPress Integration

**Comment by connorjburton** [comment]
Closing in favour of #1035
