### ISSUE TITLE
TimberTheme: No way to get abspath

### ISSUE THREAD

**Issue by aaemnnosttv** [timber/timber#718]
As far as I can tell, there is no way to get the absolute path to the theme, [contrary to what the docs say](https://github.com/jarednova/timber/wiki/Cheatsheet#theme):

```
get_template_directory() => {{ theme.parent.path }}
get_stylesheet_directory() => {{ theme.path }}
```

These are not equivalent, (perhaps due to more recent changes?) as the WP functions return absolute paths, and the timber functions return a relative path to the web root.

According to the inline documentation for the `TimberTheme::path()` method, this is the expected behavior.

How about a `theme.abspath()` method?

**Comment by palmiak** [comment]
Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread

**Comment by aaemnnosttv** [comment]
No, I don't need it at the moment either. Due to the age of this issue I'm guessing no one else did either so I'll go ahead and close it for now. Cheers!
