### ISSUE TITLE
get_context() performance

### ISSUE THREAD

**Issue by jscontrust** [timber/timber#742]
Hello,

I`m using Timber in a theme with a lot of small shortcodes. Every shortcode is rendered by timber. In some cases, a page can consist of 50 shortcodes and more.

I had performance problems, because Timber:get_context needed ~100ms to run. 
I tested, if my "timber_context" function (add_filter('timber_context', 'add_to_context');) was the problem, but it was runned only once, and when I disabled it, the performance problems persisted.

I helped myself by doing the following:

```
class giTimberHelper {
    private $cache_context = null;

    function get_timber_post_from_id($id, $translate = false) {
        $posts = $this->get_timber_posts_from_ids([$id], $translate);

        if ($posts) {
            return $posts[0];
        }
        else {
            return [];
        }
    }  
}
$gi_timber_helper = new giTimberHelper();
```

and then initialize my context with

```
global $gi_timber_helper;
$context = $gi_timber_helper->get_timber_context();
```

I don`t know where this low performance comes from, it`s a big site with a lot of plugins:

```
"wpackagist-plugin/post-thumbnail-editor": "2.4.6",
"wpackagist-plugin/timber-library": "0.21.10",
"wpackagist-plugin/types": "1.8.6.2",
"wpackagist-plugin/advanced-tinymce-configuration": "1.2",
"wpackagist-plugin/breadcrumb-navxt": "5.2.2",
"wpackagist-plugin/post-type-archive-links": "1.3.1",
"wpackagist-plugin/add-custom-fields-to-media": "1.2.5",  
"wpackagist-plugin/json-rest-api": "1.2.3",          
"wpackagist-plugin/post-duplicator": "2.8",
"wpackagist-plugin/post-types-order": "1.8.5",
"wpackagist-plugin/taxonomy-terms-order": "1.4.6.1",    
"wpackagist-plugin/cms-tree-page-view": "1.2.32",
"wpackagist-plugin/admin-menu-tree-page-view": "2.6.9",
"wpackagist-plugin/velvet-blues-update-urls": "3.2.4",
"wpackagist-plugin/regenerate-thumbnails": "2.2.4",
"wpackagist-plugin/wordpress-seo": "2.3.5",
"wpackagist-plugin/gravity-forms-no-captcha-recaptcha": "1.0.7",
"wpackagist-plugin/wp-ffpc": "1.10.0",   
"wpackagist-plugin/backwpup": "3.2.0", 
"wpml-media",
"wpml-string-translation",
"wpml-translation-management",
"gravityforms",
"gravityforms-multilingual",
"gravityformsmailchimp",
"revslider",
```

Please tell me if you need more info...

And thank you for this great plugin: I would probably not develop Wordpress themes if it would not exist!

**Comment by Schwankenson** [comment]
Tested it with a page with almost no plugins, and the problem persists.

**Comment by jeffreygnatek** [comment]
i'm seeing some significant times for timber_context in new relic, on a theme that uses tons of shortcodes (via custom visual composer widgets). would love to find out more about this.

**Comment by palmiak** [comment]
Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread

**Comment by jeffreygnatek** [comment]
Thank you for inquiring but I no longer am interested in following this issue
  
  
  

  
  

  
  
>
