### ISSUE TITLE
Better docs and usage of escaping

### ISSUE THREAD

**Issue by Chrisriis** [timber/timber#771]
I'm absolutely sure that many users will blindly copy a lot of the code from the Wiki, and that means they will output unescaped titles, content etc. It should at least be mentioned here:
https://github.com/jarednova/timber/wiki

It would also be nice if Timber provided WP's escaping functions through Twig, such as `apply_filters('the_content', $var);` etc. Twig's HTML escape `|('html')` escapes common characters such as "&", so I prefer WPs functions.

Thoughts? :)

**Comment by connorjburton** [comment]
Hi @Chrisriis that's a good point, regarding `the_content` you can just do `post.content` and it will have `the_content` applied.

**Comment by connorjburton** [comment]
Moved to #1035
