### ISSUE TITLE
Is it possible to get the TimberPost from the TimberMenuItem ?

### ISSUE THREAD

**Issue by jonben** [timber/timber#778]
Most of the time, menus in Wordpress are created from pages.

Right now, Timber only gives the title, class, link and page ID of a TimberMenuItem.

The page ID is not really helpful in twig templates, it would be nice to be able to access directly the page from the TimberMenuItem.

The use case I need right now is to retrieve the thumbnail image (or any custom field) from the page associated to the menu element. I have submenus with images.

**Comment by alenabdula** [comment]
@jonben I've tested following code and it works. You can modify it as you wish to fit into your template design.

`nav.twig`

```twig

<ul class="nav" role="navigation">
{% for item in menu.get_items %}
  <li><a href="{{item.get_link}}">{{item.title}}</a>
  {% do action('get_thumbnail_image_src', item.slug) %}
  {% if item.get_children %}
    <ul>
    {% for child in item.get_children %}
      <li><a href="{{child.get_link}}">{{child.title}}</a></li>
    {% endfor %}
    </ul>
  {% endif %}
  </li>
{% endfor %}
</ul>

```

`functions.php`

```php

function get_id_by_slug( $slug ) {
	$page = get_page_by_path( $slug );
	if ( $page ) {
		return $page->ID;
	}
	else {
		return null;
	}
}

add_action('get_thumbnail_image_src', 'my_get_thumbnail_image_src', 10, 1);

function my_get_thumbnail_image_src( $slug ) {
	$page_id = get_id_by_slug( $slug );
	$thumb_id = get_post_thumbnail_id( $page_id );
	$url = wp_get_attachment_url( $thumb_id );
	if ( $url ) {
		echo $url;
	}
}

```

@jarednova close ticket?

**Comment by connorjburton** [comment]
As this is answered and there hasn't been an activity i'm going to close this one. Feel free to comment if this is still unanswered.

**Comment by tremby** [comment]
This solution doesn't help for me, since I'm using WPML and so have versions of the same post in multiple languages with the same slug. If I get the post by slug it comes back with the wrong language sometimes.

Is there any valid reason why `get_master_object` is protected rather than public?

**Comment by tremby** [comment]
Here's my workaround.

```php
$getMasterObject = new ReflectionMethod('TimberMenuItem', 'get_master_object');
$getMasterObject->setAccessible(true);
$context['home_menu'] = array_map(function ($item) use ($getMasterObject) {
    return $getMasterObject->invoke($item);
}, (new TimberMenu('home-menu'))->get_items());
```

This is not nice code.

**Comment by cheestudio** [comment]
Just wanted to say that @alenabdula code was a LIFE saver and worked perfectly. I had no idea how I was going to get the featured image from a page without writing a walker class (which kind of defeats the point of using Timber in the first place). So, THANK YOU!  :)

**Comment by Djules** [comment]
There is a public method [`thumbnail`](https://github.com/timber/timber/blob/master/lib/MenuItem.php#L325) in TimberMenuItem class, but it's looking for a thumbnail associated to the WP MenuItem object, instead of the associated page/post, this is non-sense.

I'm going to submit a pull request fixing that, sooner or later.

**Comment by zentheme** [comment]
Bit late to the party here but thought I'd share my solution to this one.
```
function getMenuItemPost( $menuItemId ) {
	$postId = get_post_meta( $menuItemId, '_menu_item_object_id', true );
	return new Post( $postId );
}

add_filter( 'get_twig', function( $twig ) {
	$twig->addFunction( new Twig_Function( 'menu_item_post', 'getMenuItemPost' ) );
} );

// in your twig file...
<img src="{{ menu_item_post( menuItem.ID).thumbnail.src }} ">
```

**Comment by aaronlp** [comment]
A bit late here too and I like the clean custom function by @zentheme above, but here's a solution to use within the twig template without needing to write any helper functions:
`{{ TimberPost(menuItem.object_id).thumbnail.src }}`

**Comment by gchtr** [comment]
Even later to the party… I stumbled over the `thumbnail` method when working on the guide for Menus in the documentation, saw that it wasn’t working properly, and opened [an issue](https://github.com/timber/timber/issues/1572).

That bug was fixed in https://github.com/timber/timber/pull/1577 and will be released with the next version.

The `thumbnail` method will be deprecated. Instead, you will be able to access the thumbnail through the master object (the post/page/term object the menu item represents), like this:

```twig
{% for item in menu.items %}
    <a href="{{ item.link }}"><img src="{{ item.master_object.thumbnail }}" /></a>
{% endfor %}
```

So to answer the initial question from this issue (**Is it possible to get the TimberPost from the TimberMenuItem?**): Yes, as from version 1.5.3 you can use the `master_object` property.

**Comment by TheMangoTrain** [comment]
@gchtr Thanks for the master_object hint! I used this to grab the `id` for each linked menu item (ie object), which I passed into a custom shortcode for tags.

Re: As of now, thumbnails of the linked menu item are accessible via plain `item.thumbnail`, whereas to get the ID of the linked item, you need to use `item.master_object.id`,

```
{% for item in ProjectMenu.items %}
<a href="{{ item.link }}" aria-label="{{ item.title }}">

    {# Getting thumbnail of the menu item #}          
    <img src="{{ item.thumbnail.src('medium') }}" srcset="{{ item.thumbnail.srcset }}" sizes="{{ item.thumbnail.img_sizes }}" alt="{{ item.thumbnail.alt }}" />

    {# Getting a tags of the menu item, via a custom shortcode #}    
    <div class="tags">              
        {% filter shortcodes %}
           [myTags postid="{{item.master_object.id}}"]
        {% endfilter %}
    </div>
</a>
{% endfor %}
```
