### ISSUE TITLE
Timber::get_posts - instantiating class based on post type

### ISSUE THREAD

**Issue by chrisgherbert** [timber/timber#799]
I'm extending the TimberPost class for each of my custom post types - SiteArticle, SiteVideo, SiteAuthor, etc.

Is it possible to have Timber::get_posts instantiate the correct class for a given post type automatically?  I know that I can specify a class to use as the second parameter, but sometimes I have collections of posts that are of multiple post types.  For instance, on the home page I'd like to get a mixed collection recent videos and articles.

Thanks.

**Comment by alenabdula** [comment]
@chrisgherbert maybe this solves your issue.

```php
# functions.php
function add_to_context( $context ) {
    $context['menu'] = new TimberMenu();
    $context['site'] = $this;
    $context['SiteVideo'] = Timber::get_posts('post_type=sitevideo');
    $context['SiteArticle'] = Timber::get_posts('post_type=sitearticle');
    return $context;
}
```

```twig
<!-- your template -->
{% block content %}
    {% set posts = posts|merge(SiteVideo) %}
    {% set posts = posts|merge(SiteArticle) %}
    {% for post in posts %}
        <!-- do magic -->
    {% endfor %}
{% endblock %}
```

Hope that helps
Alen

**Comment by chrisgherbert** [comment]
I could do that, but I have 10+ different post types (my example was simplified) and running a different query for each one would be pretty verbose and might hurt performance significantly.  It also just doesn't feel like the right way to do things.

I'd love to see a way to "register" a custom post type with Timber and provide a corresponding class to use.  That way Timber would know which class to instantiate for each post type.

Another way to handle it would be to have a TimberPostGetter method that determines which class to use for each post object.  That way TimberPostGetter could be extended and that method could be overridden for custom class-choosing logic.  That would be nice for times when choosing a class involves more than just checking the post's type.

**Comment by alenabdula** [comment]
> I could do that, but I have 10+ different post types

@chrisgherbert That's what I was afraid you would say. In a real world example... is the view responsible for merging data? Most definitely not. I've just started playing with Timber so I'm learning as I go, but I would look into a way to "prepare" the data before it is sent for Timber to render.

Maybe you can use [pre_get_posts](https://codex.wordpress.org/Plugin_API/Action_Reference/pre_get_posts) hook to prepare custom query, then just send that data to the view.

Hope that helps,
Alen

**Comment by chrisgherbert** [comment]
I have a class that processes the data before sending it to the view, but it's not as good or as convenient as using the built in Timber stuff.  I was just wondering if there was already a supported way to do what I need and, if not, to suggest it as a possible new feature.

**Comment by connorjburton** [comment]
Hope I understood you correctly.

Hi @chrisgherbert - it should do what you are requesting automatically, if you do something like 

```php
Timber::get_posts(array(
    'post_type' => 'cpt'
));
```

And you have a class that extends `TimberPost`

```php
class cpt extends TimberPost {

}
```

It will init the posts with the `cpt` class automatically. Two caveats, the class name has to be exactly the same as the post type name and (in new releases) it has to extend `TimberPost`

**Comment by chrisgherbert** [comment]
That's great, thanks! The only issue I can see is if the CPT name contains a hyphen it would not be a valid PHP class name, but would be a perfectly valid custom post type.

Would it make sense to look for a camel cased version of the CPT name?  For example, `custom-post-type` would also look for the `CustomPostType` class.  `custom_post_type` could work similarly.

This might seem like a pretty small issue but underscores in URLs are so ugly.

**Comment by connorjburton** [comment]
Ah, very good point.

As a temporary fix, and with a bit of PHP weirdness, you could do something like 

```php
class CustomPostType extends TimberPost {
    public function __construct() {
        class_alias(get_class($this), 'custom-post-type');
    }
}

class_exists('custom-post-type'); # true
```

I know this works in PHP but don't know if it works in this situation with Timber, but I don't see why not as everything is passed as variables.

In the mean time I will look at implementing a more robust check rather than just `class_exists` based off post type.

Let me know if any of this doesn't work, as i'm keen to get this sorted.

**Comment by chrisgherbert** [comment]
When I do this:

```php
class cpt extends TimberPost {
}

Timber::get_posts(array(
  'post_type' => 'cpt'
));
```

`Timber::get_posts` returns `null`.  I've double-checked that `cpt` posts actually exist.  Even if there weren't any, I think it should return an empty array.

Weirdly, if stick the custom post type name inside an array, like this:

```php
Timber::get_posts(array(
  'post_type' => array('cpt')
));
```
...I get an array of `TimberPost` objects (not `cpt` objects).

**Comment by connorjburton** [comment]
Hmm, let me take a look

**Comment by chrisgherbert** [comment]
Excellent, thanks!

I think that going down the "registering" classes with a post type might also make sense, as you probably don't want a bunch of short, super generic class names ("publication", "staff", "slider", to name a few post types that I often use) polluting the global namespace.

**Comment by connorjburton** [comment]
Yes, that's how I ran into the issue with on #847 - I had a `job` class that was just aggregating some data and it assumed I wanted to use that class as my `TimberPost`

I'll still take a look as it should auto register the classes.

**Comment by connorjburton** [comment]
Submitted a PR, there are defo issues with it atm. PR should solve them.
