### ISSUE TITLE
Timber::get_post() behaviour differs from WP get_post()

### ISSUE THREAD

**Issue by ondratra** [timber/timber#819]
Very unfortunate inconsistency in get_post function while working with custom post types. 

assuming we have two posts:
- one post with ID 1234 of regular post type 'post'
- one post with ID 6789 and post_type 'myCustomPostType'
then 

get_post(1234); // returns WP post object
Timber::get_post(1234, 'MyPostClass'); // returns MyPostClass instance
get_post('6789'); // returns WP post object
Timber::get_post(6789); // returns NULL!!!

It's caused by Timber::get_post() internally calling Timber::get_posts() that looks for 'post_type' query parameter; WP get_post() has it's own logic separate from get_posts()

The ugly solution to this situation is to rewrite clause:
Timber::get_post($postId, 'MyCustomClass');
into
$tmpPost = get_post($postId); // get actual post
$post = $tmpPost ? Timber::get_post($tmpPost, 'MyCustomClass') : null; // create desired class instance

Is there a way to fix this easily? (if there is not we should probably update documentation and mention this problem)

**Comment by chrisgherbert** [comment]
I'm not getting the same behavior.  If I run:

```
Timber::get_post(7023)
```

I get the correct TimberPost object, even if the post is a custom post type.

**Comment by connorjburton** [comment]
Hi @ondratra is this still an issue? `Timber::get_post` has always worked for me for custom post types, but maybe it's to do with the fact you want `MyCustomClass`?

**Comment by connorjburton** [comment]
I'm going to close this as it seems inactive, let me know if it's still an issue and I will re-open.

**Comment by kmturley** [comment]
I'm also getting this issue. When I log out the following in page.php:

    print_r(get_posts());

    Array
    (
        [0] => WP_Post Object
            (
                [ID] => 20
                [post_content] => sadbasjdkhsa jhdaskjh 
                [post_title] => This is a post
                [post_type] => post
            )

        [1] => WP_Post Object
            (
                [ID] => 1
                [post_content] => Welcome to WordPress. This is your first post. Edit or delete it, then start writing!
                [post_title] => Hello world!
                [post_type] => post
            )
    )

But when I use the Timber version it's outputting the current page instead:

    print_r(Timber::get_posts());

    Array
    (
        [0] => TimberPost Object
            (
                [ID] => 26
                [post_content] => hello ya
                [post_title] => This is my homepage yup
                [post_type] => page
            )
    )

**Comment by jscontrust** [comment]
I have the same problem. I can`t exactly reproduce when it started, but maybe it happened after updating WPML to it`s latest Version.

> Timber::get_post(1234) 

returns null, if post with id=1234 is a custom post type.

We have the same issue for timberTermInstance.get_posts(). We need to add post_type=our_custom_type_slug to get the corresponding posts.

**Comment by jarednova** [comment]
@jscontrust — does this occur when WPML is NOT activated? I want to make sure I can accurately identify under what circumstances this happens

**Comment by jarednova** [comment]
I've written a test that verifies the behavior seen by @jscontrust as working: ea50d520e0fa83c0322bffa31634c5e0f074a241

**Comment by jarednova** [comment]
@kmturley — I've added your comment on a new issue in #1093

**Comment by jarednova** [comment]
@kmturley — I've verified the error you're seeing in e5ad299. @lggorman — could you investigate a solution?

**Comment by lggorman** [comment]
@kmturley @jscontrust In your `register_post_type` $args array, is `public` set to true and `exclude_from_search` either not set or set to false? (if public is true, exclude from search should be set to false by default).  WordPress's `get_post()` goes directly to the database, but Timber's relies on `get_posts()`, which only gets post types where `exclude_from_search` is set to false.  I think there's a chance this is what's preventing posts from being returned?

**Comment by cjke** [comment]
Just want to confirm, for me, using latest master with @lggorman 's patch is working now for me with custom content types (previously it wasn't)

**Comment by jarednova** [comment]
Awesome! Let's call this one closed!

**Comment by cjke** [comment]
Easy. Thanks for being an awesome and welcoming community
