### ISSUE TITLE
Unsupported Term Meta

### ISSUE THREAD

**Issue by stewarty** [timber/timber#824]
Hi All, quite new to the project.

Looking to use Timber with the native TermMeta as implemented with WordPress 4.4.  A quick look around the codebase make me believe that the current TermMeta implementation relies on ACF being used rather than the builtin API?

Any plans on getting the Native API supported?

**Comment by jedrzejchalubek** [comment]
+1 hightly needed

Getting meta on post types works perfectly fine. `custompost.meta('key')` return values form `wp_postmeta` table.

But getting meta for term don't working. `term.meta('key')` return empty string.

**Comment by ashrayer** [comment]
Please check if I'm right. I made edits in my Term.php

`
	/**
	 * @internal
	 * @param string $field_name
	 * @return string
	 */
	public function get_meta_field( $field_name ) {
		if ( !isset($this->$field_name) ) {
			$field_value = '';
			$field_value = apply_filters('timber_term_get_meta_field', $field_value, $this->ID, $field_name, $this);
			$field_value = apply_filters('timber/term/meta/field', $field_value, $this->ID, $field_name, $this);
			$field_value = get_term_meta($this->ID, $field_name, true);
			$this->$field_name = $field_value;
		}

		return $this->$field_name;
	}`

**Comment by scynetpro** [comment]
`add_filter('timber/term/meta/field', 'fix_damn_timber_bug', 10, 4);

function fix_damn_timber_bug ($field_value, $id, $field_name, $term) {
    return $field_value = get_term_meta($id, $field_name, true);
}`

**Comment by Daronspence** [comment]
So what needs to be done to get this merged into Timber core? Do we need a new method on the Term object that does the standard term meta lookup introduced in 4.4? I'd be happy to take a look at it over the next week or two if I have some time.

**Comment by jarednova** [comment]
#1238 should address this, lemme know if anyone runs into issues
