### ISSUE TITLE
get_field for TimberTerm

### ISSUE THREAD

**Issue by ruscon** [timber/timber#838]
Acf get_field work perfectly for post and term.
Can we add get_field function in TimberTerm ?

get_field -> get_meta_field

**Comment by benedict-w** [comment]
+1

**Comment by jarednova** [comment]
@benedict-w and @ruscon check out #1168! This will be part of Timber 1.1.4 (released week to wp.org)

**Comment by lalop** [comment]
It seems that filters aren't applied in the same way for Post::get_field and Term::get_field so for an ACF field of type relation on a term I get a WP_Post instead of a TimberPost
