### ISSUE TITLE
Twig_Loader_String should not be used

### ISSUE THREAD

**Issue by mahagr** [timber/timber#863]
Timber is using `Twig_Loader_String` to compile strings in: 

https://github.com/jarednova/timber/blob/master/lib/timber.php#L233

This class should never be used; its for internal use only and there is a lot better way to do the same:

Here is the idea how to do it properly:

    $template = $twig->createTemplate($string);
    return $template->render($data);

You can even use existing twig environment allowing user to load and extend existing twig template files.

**Comment by newkind** [comment]
:+1:

**Comment by connorjburton** [comment]
Thanks for raising this @mahagr - it seems `Timber_Loader_String` is actually deprecated too. I had a look and only tests use `compile_string` or `render_string` which are the only instances where `Timber_Loader_String` is used, so we shouldn't be too worried about changing this.

I'll put this as a contrib opportunity as it's a fairly simple one, if its not done in a week or two ill fix it.

**Comment by jarednova** [comment]
@connorjburton thanks for finally taking care of this one. No longer deprecated!

**Comment by mahagr** [comment]
Nice!
