### ISSUE TITLE
Namespace Timber files

### ISSUE THREAD

**Issue by jarednova** [timber/timber#869]
This is spun from #835. If it's helpful/necessary to complete this at the same time as #835: go for it! Otherwise this can wait 'till later. This ticket is about splitting the files into the `Timber` namespace so that `TimberPost` becomes `Timber\Post`. Backwards compatibility should be maintained so that a file that already calls or extends `TimberPost` should not require any changes to keep working. This could be accomplished through an alias or other mechanism.

- [x] Files are namespaced under the `Timber`
- [x] Backwards compatibility is maintained
- [x] `lib/` directory is updated as needed
- [x] Composer autoloading is updated as needed

**Comment by mrgrain** [comment]
I'm quite sure it can be done later. Composer autoloading works already. Backwards compatibility will break if we don't use class_alias

**Comment by connorjburton** [comment]
Okay, I've pretty much got there with this, tests need updating and manual testing is necessary along with full docs updates.

**Comment by connorjburton** [comment]
The old files will need removing too
