### ISSUE TITLE
Integrating Easy Digital Downloads and Other Plugins

### ISSUE THREAD

**Issue by JakeHenshall** [timber/timber#896]
Hi,

My theme is based on a parent / child layout structure and i'm trying to integrate Easy Digital Downloads with it.

If I view this -> http://beast.dev/base/downloads/test-product/ I get this error

Fatal error: Uncaught Error: Call to undefined function post__password_required() in /Users/beast/Documents/code/base/wp-content/themes/base-child/single.php:8 Stack trace: #0 /Users/beast/Documents/code/base/wp-includes/template-loader.php(89): include() #1 /Users/beast/Documents/code/base/wp-blog-header.php(16): require_once('/Users/beast/Do...') #2 /Users/beast/Documents/code/base/index.php(17): require('/Users/beast/Do...') #3 {main} thrown in /Users/beast/Documents/code/base/wp-content/themes/base-child/single.php on line 8

Moving forward what is the best way to integrate 3rd party plugins into my WordPress theme similar to Woocommerce.
### What version of WordPress, PHP and Timber are you using?

WordPress 4.4.2 PHP 7 Timber 0.22.5 Mamp
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Using Composer/packagist

**Comment by connorjburton** [comment]
Hi @JakeHenshall - thanks for this, could you please give me detailed instructions on how to replicate this?

Thanks

**Comment by JakeHenshall** [comment]
Hi @connorjburton Thanks for the reply,

All i did was install Easy Digital Download, Ive followed the Woocommerce instructions to get that working and it so far works perfectly but i don't know if i need to do anything for Easy Digital Downloads and other 3rd party plugins.

Jake.

**Comment by connorjburton** [comment]
Hi @JakeHenshall - can you try this with Timber disabled please?

**Comment by JakeHenshall** [comment]
@connorjburton I've done a little more on this and it seems to work with Timber quite nicely, but it dosent seem to output the images, i dont know if you can have additional templates similar to what Woocommerce does with the woo/single-product/ ive put out a question to EDD and ill link this issue.

**Comment by palmiak** [comment]
@JakeHenshall does this problem still persists? Please respond in two weeks or we'll close this thread
