### ISSUE TITLE
How to style a sticky post

### ISSUE THREAD

**Issue by JakeHenshall** [timber/timber#898]
### Expected behaviour

Change the style of a sticky post to differentiate it from normal posts

### Actual behaviour

i can't seem to style the sticky post

### Steps to reproduce behaviour

Create a sticky post

### What version of WordPress, PHP and Timber are you using?

WordPress 4.4.2, PHP 7, Timber 0.22.5

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Composer/Packagist

**Comment by connorjburton** [comment]
Hi,

Isn't this the same as styling any other post? Not sure how this relates to Timber, could you provide more info please on what issues Timber is having to do with sticky posts

Thanks

**Comment by connorjburton** [comment]
Hi @JakeHenshall - I'm going to close this for now as I don't think this relates to Timber.

If you have any more info please let me know and I will happily re-open.
