### ISSUE TITLE
TimberMenu and WPML

### ISSUE THREAD

**Issue by ogrosko** [timber/timber#899]
Hi I have question about TimberMenu and WPML 

I have created following menu in WP 
**Main Navigation** and **Main Navigation - English** (sinced by WPML), default language german
In twig menu is rendered from variable 
`$mainMenu = new \TimberMenu('main-navigation');`

German menu is correct and coresponds to BE menu (see structure),

**BE menu**
-   Home
-  Page #1
-  Page #2

**FE menu**
-   Home
-  Page #1
-  Page #2
  
  but if I switch page to English (I have translated only Home)

**BE menu EN**
-   Home EN

**FE menu EN**
-  Home EN
- Page #1
- Page #2
- Page #3
- Page #4 

Very vierd behaviour, Don't you thing?
It is problem only if page translations not exists.

but if I switch menu for EN
`$mainMenu = new \TimberMenu('main-navigation-english');`
menu on english page is correct and only Home page link shows up in menu

How can I get menu for all languages without need to get each menu separately by menu slug and do not display not translated pages

Installed latest version of WordPress and Timber via composer (using https://wpackagist.org/)

**Comment by addedlovely** [comment]
In the past I've loaded the correct menu by ID, depending on the current language selected:

```
	    // Load Menu depending on current language
	    $context['language'] = ICL_LANGUAGE_CODE;
	    
	    // Menu ID : Default to English
	    $menuID = 2;
	    
	    switch(ICL_LANGUAGE_CODE) {
		    case 'en':
		    	$menuID = 2;
		    	break;
		    case 'fr':
		    	$menuID = 9;
		    	break;
		    case 'ja':
		    	$menuID = 11;		    
		    	break;
		    case 'de':
		    	$menuID = 10;
		    	break;
		    case 'es':
		    	$menuID = 8;		    
		    	break;
	    }
	    
    	$context['menu'] = new TimberMenu($menuID);
```

**Comment by jon-heller** [comment]
Funny, I ran into this exact same issue today and was going to report it. Like @addedlovely said using the ID works as a backup, but creating a TimberMenu by supplying the location slug always returns the default language menu instead of the translated one.

**Comment by ogrosko** [comment]
Yes solution by @addedlovely works as workarround.
But I thing it should be automatic. imho
When the client adds new language you have to add new menu config

**Comment by connorjburton** [comment]
Hi guys,

We are aware of various improvements that could be made with 3rd party plugins and the like, as we are approaching a 1.0 release, those improvements will be on the back burner for a little while. However once we are on 1.0 we can focus on improving our compatibility with popular plugins, such as WPML

Thanks,
Connor

**Comment by orest22** [comment]
@ogrosko Weird I have similar setup: 
`$context['menu'] = new TimberMenu('top-bar-r');` 
And it looks like works nice. I din't sync menu with 'WP Menus Sync'. Make sure you translate all pages that you need in menu.

**Comment by ogrosko** [comment]
@orest22 Oh I forgot to mention it

When pages has localizations it works with no problems.
It is problem only if page localization not exists

**Comment by ogrosko** [comment]
Any news about this?

**Comment by connorjburton** [comment]
Not yet unfortunately, working through a backlog of post `1.0.0` fixes at the moment.

**Comment by mikeyb31** [comment]
Bump

**Comment by mikeyb31** [comment]
Hopefully this helps a few of you!
https://github.com/timber/timber/pull/1414/commits/5befe275047ef03a7901cb562a6fb6991cfac927

**Comment by palmiak** [comment]
@ogrosko from what I see this should be fixed. If so, please close the issue. 

As this is a bit old issue we'll close in case of no response in two weeks.
