### ISSUE TITLE
Include custom php script

### ISSUE THREAD

**Issue by rabillion** [timber/timber#902]
hi,
i will include a custom php script which contains HTML content and add the code into the timber context
`require_once( $_SERVER['DOCUMENT_ROOT'] . '/custom/script.php' );`
So, how can i get the code in a twig file?

**Comment by connorjburton** [comment]
Hi @rabillion 

You could use one of the solutions posts here http://stackoverflow.com/questions/5817726/wordpress-save-get-template-part-to-variable to return the html from a template, then you can assign that data to context.

So something like 

```php
$context['foo'] = my_function_to_return_template('/custom/script.php');
```

```twig
{{ foo }}
```

I _think_ that should work

P.S - if you are going to go down the `file_get_contents` route, please read http://stackoverflow.com/questions/3629504/php-file-get-contents-very-slow-when-using-full-url

**Comment by connorjburton** [comment]
Thinking about this, `file_get_contents` is probably not a good idea the file has PHP in it. I'd recommend the output buffering method.

**Comment by connorjburton** [comment]
Hi, going to close this for now. Please let me know if this is still an issue

**Comment by rabillion** [comment]
Hi, it works perfectly

**Comment by connorjburton** [comment]
Thanks for getting back to me :+1:
