### ISSUE TITLE
GIF Image not animated after resize

### ISSUE THREAD

**Issue by dkdl** [timber/timber#913]
### Expected behavior
The animated gif image should stay animated after resize

### Actual behavior
Gif image is a still image now

### Steps to reproduce behavior
The gif image is inserted in Wordpress as a Featured Image. Then I use the following code:
````
<img src="{{ post.thumbnail.src|resize(800) }}" alt="{{ post.post_title }}">
````

### WordPress, PHP and Timber Versions
WordPress 4.4.2, PHP 5.6.10, Timber 0.22.5

### How did you install Timber?
Timber is installed via Github and updated to the latest via WP Upgrade Plugins.

**Comment by connorjburton** [comment]
Thanks for the detailed info @dkdl - will look at this over the weekend.

**Comment by dkdl** [comment]
@connorjburton Thanks for taking a look later on. 
In case it is relevant: 
I'm using OSX 10.11.3 and MAMP 3.4 for the localhost

**Comment by connorjburton** [comment]
Hi @dkdl - I've looked into this and it seems to work for me on a local installation. Could you provide the GIF you are using please?

**Comment by dkdl** [comment]
Hi @connorjburton 

I've attached the original file. And the GIF it generates by resizing.

original:
![yum](https://cloud.githubusercontent.com/assets/7533778/13914450/b59eee92-ef4e-11e5-9ce3-2aec180a7b0c.gif)

800 resize:
![yum-800x0-c-default](https://cloud.githubusercontent.com/assets/7533778/13914451/b9c0f2c2-ef4e-11e5-9825-17ccad03e7d2.gif)

Is it otherwise possible to ignore GIF files from resizing? That would be cool as well in my case.

**Comment by connorjburton** [comment]
Hi @dkdl - that image actually works when I resize, resizing smaller and larger than the source.

http://recordit.co/1UnwTpDQAw

Would it be possible for you to grab the master on github and see if that fixes the issue?

Couple of debug suggestions:
1. Try a default theme
2. Try disabling all plugins except Timber

Thanks

**Comment by dkdl** [comment]
Hi @connorjburton 
thanks for the video. Unfortunately no difference. For now I've solved it by checking if it is a GIF:
````
{% if post.thumbnail.src %}

  {% if '.gif' in post.thumbnail.src %}
    <img src="{{ post.thumbnail.src }}" alt="{{ post.title }}" />
  {% else %}
    <img src="{{ post.thumbnail.src|resize(800) }}" alt="{{ post.title }}" />
  {% endif %}

{% endif %}
````

**Comment by connorjburton** [comment]
Hey,

Sorry I can't help any further, hate to say it but I don't think this is a direct issue with Timber. If you do find more info that could help just comment on here and I will re-open this issue.

Thanks

**Comment by jarednova** [comment]
@dkdl a possibility here is the type of image resizing engine available on your server. The `TimberImage` processing uses `wp_get_image_editor` which could use GD or ImageMagick (or something else?) based on what is installed on the server. It's possible that Timber needs one or the other that isn't installed on your server. See if you can identify which library is used; that might help us ID why it works for @connorjburton and I, but not for your setup*

*but warning: it's very possible that a less robust image library simply won't be able to resize animated gifs, in which case the best solution here might just be a warning in the error logs (which is helpful, but unsatisfying)
