### ISSUE TITLE
TimberImage process issue

### ISSUE THREAD

**Issue by salidoraul** [timber/timber#917]
### Expected behavior
An error or a false value when using the resize filter on an empty TimberImage object.

### Actual behavior
Process runs to the point of crashing my server.

### Steps to reproduce behavior

I used <code>TimberImage( var )|resize(900)</code> where TimberImage equaled an empty object (due to the fact that my variable was wrong) and applying the "resize" filter on that empty object would run the process continuously until my server would time out.

### What version of WordPress, PHP and Timber are you using?
WordPress: 4.4.2
PHP: 5.3.29

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
GitHub

**Comment by connorjburton** [comment]
Hi @salidoraul - this is actually resolved in #914 - if you need this urgently, you could pull down the master branch as it's in there.

The fix will exit out of TimberImage if it's passed with an empty parameter
