### ISSUE TITLE
Wrong version tag for RC

### ISSUE THREAD

**Issue by mrgrain** [timber/timber#920]
### Expected behavior
RC releases should be properly named/tagged so composer can detected those and assign it to the right stability channel. It should be tagged as `1.0.0-rc1` or `v1.0.0-rc1`

See:
https://getcomposer.org/doc/04-schema.md#version
https://getcomposer.org/doc/04-schema.md#minimum-stability

### Actual behavior
Release is tagged as `v1.0-rc.1` which is rendered to `dev-1.0rc` by composer, thus putting the release under the dev-stability-channel.

### Steps to reproduce behavior
Check those two links:
https://packagist.org/packages/timber/timber
https://github.com/timber/timber/releases

**Comment by jarednova** [comment]
Thanks for the headsup @mrgrain — I'll make that change

**Comment by jarednova** [comment]
@mrgrain: I updated the version number for 1.0-rc2. Can you confirm this format is correct?: 

https://packagist.org/packages/timber/timber#1.0-rc2

**Comment by mrgrain** [comment]
Yes, this works now. You can run `composer require timber/timber:"~1.0.0"` to confirm (vs. `composer require timber/timber:"~2.0.0"` is not working)

However, I would recommend **not** to change the versioning pattern. It used to be `X.Y.Z` as in `0.22.6` but now we are suddenly on `X.Y` as in `1.0`. Releasing RCs works fine with three level versioning as well.

**Comment by jarednova** [comment]
:+1: I'll make sure the next release follows the three decimal pattern. Thanks for the heads-up on that!
