### ISSUE TITLE
Custom Post Types Support

### ISSUE THREAD

**Issue by developer-lindner** [timber/timber#921]
I'm encountering the following issue with custom post types right now:

`{{post.content}}` works for standard pages & posts.

I got an relation field (ACF) added to a specific page and in twig template accessed through 
`{% set sliderData = site.prepareACFData(post.get_field('products')) %}`

The relation field holds all posts added to this specific page (which are added by custom post type).

`post.get_field('products')`
gives an array of WP_Post Objects, but i want to have those posts prepared by Timber,
which is done by the following function.

`function prepareACFData($postdata){
        $data = array();

```
    foreach($postdata as $post){
        $data[] = new TimberPost($post->ID);
    }
    return $data;
```

 }`

But the prepared data is not accessible as expected.
### Expected behavior

When using

`<ul>
{% for post in sliderData %}
    <li>
        {{ post.content }}
    </li>
{% endfor %}
</ul>`

the prepared content should be shown, but instead i just get
`field_56ec263325889`

`{{ post.title }}`
works as expected...
### Versions

WordPress 4.4.2, PHP 5.6, Timber 0.22.5

**Comment by connorjburton** [comment]
Hi @developer-lindner 

What does `{{ dump(post) }}` show?

**Comment by developer-lindner** [comment]
`object(TimberPost)#4776 (60) {
  ["ImageClass"]=&gt;
  string(11) "TimberImage"
  ["PostClass"]=&gt;
  string(10) "TimberPost"
  ["TermClass"]=&gt;
  string(10) "TimberTerm"
  ["object_type"]=&gt;
  string(4) "post"
  ["_content":protected]=&gt;
  string(19) "field_56ec263325889"
  ["_get_terms":protected]=&gt;
  NULL
  ["_permalink":protected]=&gt;
  NULL
  ["_next":protected]=&gt;
  array(0) {
  }
  ["_prev":protected]=&gt;
  array(0) {
  }
  ["class"]=&gt;
  string(99) "post-208 types type-types status-publish has-post-thumbnail hentry language-de"
  ["display_date"]=&gt;
  string(16) "8. Dezember 2015"
  ["id"]=&gt;
  int(208)
  ["ID"]=&gt;
  int(208)
  ["post_author"]=&gt;
  string(1) "1"
  ["post_content"]=&gt;
  string(1210) " lot of content (unprocessed)"
  ["post_date"]=&gt;
  string(19) "2015-12-08 17:39:12"
  ["post_excerpt"]=&gt;
  string(0) ""
  ["post_parent"]=&gt;
  int(0)
  ["post_status"]=&gt;
  string(7) "publish"
  ["post_title"]=&gt;
  string(6) "SC 312"
  ["post_type"]=&gt;
  string(5) "types"
  ["slug"]=&gt;
  string(6) "sc-312"
  ["_edit_last"]=&gt;
  string(1) "1"
  ["_edit_lock"]=&gt;
  string(12) "1458732310:1"
  ["content-headline"]=&gt;
  string(0) ""
  ["_content-headline"]=&gt;
  string(19) "field_5666eb047925d"
  ["contents"]=&gt;
  string(1) "0"
  ["_contents"]=&gt;
  string(19) "field_56548cb75b6dc"
  ["produktrelation"]=&gt;
  string(0) ""
  ["_produktrelation"]=&gt;
  string(19) "field_5666ed24bb4c0"
  ["industry"]=&gt;
  array(1) {
    [0]=&gt;
    string(36) "Construction &amp; Agricultural Industry"
  }
  ["_industry"]=&gt;
  string(19) "field_566ead58a7828"
  ["end-product"]=&gt;
  array(1) {
    [0]=&gt;
    string(14) "gasoline-tanks"
  }
  ["_end-product"]=&gt;
  string(19) "field_566eae7ca7829"
  ["material"]=&gt;
  array(1) {
    [0]=&gt;
    string(15) "stainless-steel"
  }
  ["_material"]=&gt;
  string(19) "field_566eb006a782a"
  ["_wp_old_slug"]=&gt;
  string(6) "tertre"
  ["top"]=&gt;
  string(1) "0"
  ["_top"]=&gt;
  string(19) "field_5694bc6dc7011"
  ["_thumbnail_id"]=&gt;
  string(3) "416"
  ["slide_template"]=&gt;
  string(7) "default"
  ["hidden-content"]=&gt;
  string(591) "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet."
  ["_hidden-content"]=&gt;
  string(19) "field_56ec263325889"
  ["post_date_gmt"]=&gt;
  string(19) "2015-12-08 16:39:12"
  ["comment_status"]=&gt;
  string(6) "closed"
  ["ping_status"]=&gt;
  string(6) "closed"
  ["post_password"]=&gt;
  string(0) ""
  ["post_name"]=&gt;
  string(6) "sc-312"
  ["to_ping"]=&gt;
  string(0) ""
  ["pinged"]=&gt;
  string(0) ""
  ["post_modified"]=&gt;
  string(19) "2016-03-23 12:27:06"
  ["post_modified_gmt"]=&gt;
  string(19) "2016-03-23 11:27:06"
  ["post_content_filtered"]=&gt;
  string(0) ""
  ["guid"]=&gt;
  string(45) "http://leifeld.ll/?post_type=types&amp;p=208"
  ["menu_order"]=&gt;
  int(0)
  ["post_mime_type"]=&gt;
  string(0) ""
  ["comment_count"]=&gt;
  string(1) "0"
  ["filter"]=&gt;
  string(3) "raw"
  ["status"]=&gt;
  string(7) "publish"
  ["custom"]=&gt;
  array(23) {
    ["_edit_last"]=&gt;
    string(1) "1"
    ["_edit_lock"]=&gt;
    string(12) "1458732310:1"
    ["content-headline"]=&gt;
    string(0) ""
    ["_content-headline"]=&gt;
    string(19) "field_5666eb047925d"
    ["contents"]=&gt;
    string(1) "0"
    ["_contents"]=&gt;
    string(19) "field_56548cb75b6dc"
    ["produktrelation"]=&gt;
    string(0) ""
    ["_produktrelation"]=&gt;
    string(19) "field_5666ed24bb4c0"
    ["industry"]=&gt;
    array(1) {
      [0]=&gt;
      string(36) "Construction &amp; Agricultural Industry"
    }
    ["_industry"]=&gt;
    string(19) "field_566ead58a7828"
    ["end-product"]=&gt;
    array(1) {
      [0]=&gt;
      string(14) "gasoline-tanks"
    }
    ["_end-product"]=&gt;
    string(19) "field_566eae7ca7829"
    ["material"]=&gt;
    array(1) {
      [0]=&gt;
      string(15) "stainless-steel"
    }
    ["_material"]=&gt;
    string(19) "field_566eb006a782a"
    ["_wp_old_slug"]=&gt;
    string(6) "tertre"
    ["top"]=&gt;
    string(1) "0"
    ["_top"]=&gt;
    string(19) "field_5694bc6dc7011"
    ["_thumbnail_id"]=&gt;
    string(3) "416"
    ["content"]=&gt;
    string(0) ""
    ["_content"]=&gt;
    string(19) "field_56ec263325889"
    ["slide_template"]=&gt;
    string(7) "default"
    ["hidden-content"]=&gt;
    string(591) "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet."
    ["_hidden-content"]=&gt;
    string(19) "field_56ec263325889"
  }
}`

**Comment by developer-lindner** [comment]
> object(TimberPost)#4776 (60) {
  ["ImageClass"]=&gt;
  string(11) "TimberImage"
  ["PostClass"]=&gt;
  string(10) "TimberPost"
  ["TermClass"]=&gt;
  string(10) "TimberTerm"
  ["object_type"]=&gt;
  string(4) "post"
  ["_content":protected]=&gt;
  string(19) "field_56ec263325889"
  ["_get_terms":protected]=&gt;
  NULL
  ["_permalink":protected]=&gt;
  NULL
  ["_next":protected]=&gt;
  array(0) {
  }
  ["_prev":protected]=&gt;
  array(0) {
  }
  ["class"]=&gt;
  string(99) "post-208 types type-types status-publish has-post-thumbnail hentry language-de"
  ["display_date"]=&gt;
  string(16) "8. Dezember 2015"
  ["id"]=&gt;
  int(208)
  ["ID"]=&gt;
  int(208)
  ["post_author"]=&gt;
  string(1) "1"
  ["post_content"]=&gt;
  string(1210) " lot of content (unprocessed)"
  ["post_date"]=&gt;
  string(19) "2015-12-08 17:39:12"
  ["post_excerpt"]=&gt;
  string(0) ""
  ["post_parent"]=&gt;
  int(0)
  ["post_status"]=&gt;
  string(7) "publish"
  ["post_title"]=&gt;
  string(6) "SC 312"
  ["post_type"]=&gt;
  string(5) "types"
  ["slug"]=&gt;
  string(6) "sc-312"
  ["_edit_last"]=&gt;
  string(1) "1"
  ["_edit_lock"]=&gt;
  string(12) "1458732310:1"
  ["content-headline"]=&gt;
  string(0) ""
  ["_content-headline"]=&gt;
  string(19) "field_5666eb047925d"
  ["contents"]=&gt;
  string(1) "0"
  ["_contents"]=&gt;
  string(19) "field_56548cb75b6dc"
  ["produktrelation"]=&gt;
  string(0) ""
  ["_produktrelation"]=&gt;
  string(19) "field_5666ed24bb4c0"
  ["industry"]=&gt;
  array(1) {
    [0]=&gt;
    string(36) "Construction &amp; Agricultural Industry"
  }
  ["_industry"]=&gt;
  string(19) "field_566ead58a7828"
  ["end-product"]=&gt;
  array(1) {
    [0]=&gt;
    string(14) "gasoline-tanks"
  }
  ["_end-product"]=&gt;
  string(19) "field_566eae7ca7829"
  ["material"]=&gt;
  array(1) {
    [0]=&gt;
    string(15) "stainless-steel"
  }
  ["_material"]=&gt;
  string(19) "field_566eb006a782a"
  ["_wp_old_slug"]=&gt;
  string(6) "tertre"
  ["top"]=&gt;
  string(1) "0"
  ["_top"]=&gt;
  string(19) "field_5694bc6dc7011"
  ["_thumbnail_id"]=&gt;
  string(3) "416"
  ["slide_template"]=&gt;
  string(7) "default"
  ["hidden-content"]=&gt;
  string(591) "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet."
  ["_hidden-content"]=&gt;
  string(19) "field_56ec263325889"
  ["post_date_gmt"]=&gt;
  string(19) "2015-12-08 16:39:12"
  ["comment_status"]=&gt;
  string(6) "closed"
  ["ping_status"]=&gt;
  string(6) "closed"
  ["post_password"]=&gt;
  string(0) ""
  ["post_name"]=&gt;
  string(6) "sc-312"
  ["to_ping"]=&gt;
  string(0) ""
  ["pinged"]=&gt;
  string(0) ""
  ["post_modified"]=&gt;
  string(19) "2016-03-23 12:27:06"
  ["post_modified_gmt"]=&gt;
  string(19) "2016-03-23 11:27:06"
  ["post_content_filtered"]=&gt;
  string(0) ""
  ["guid"]=&gt;
  string(45) "http://leifeld.ll/?post_type=types&amp;p=208"
  ["menu_order"]=&gt;
  int(0)
  ["post_mime_type"]=&gt;
  string(0) ""
  ["comment_count"]=&gt;
  string(1) "0"
  ["filter"]=&gt;
  string(3) "raw"
  ["status"]=&gt;
  string(7) "publish"
  ["custom"]=&gt;
  array(23) {
    ["_edit_last"]=&gt;
    string(1) "1"
    ["_edit_lock"]=&gt;
    string(12) "1458732310:1"
    ["content-headline"]=&gt;
    string(0) ""
    ["_content-headline"]=&gt;
    string(19) "field_5666eb047925d"
    ["contents"]=&gt;
    string(1) "0"
    ["_contents"]=&gt;
    string(19) "field_56548cb75b6dc"
    ["produktrelation"]=&gt;
    string(0) ""
    ["_produktrelation"]=&gt;
    string(19) "field_5666ed24bb4c0"
    ["industry"]=&gt;
    array(1) {
      [0]=&gt;
      string(36) "Construction &amp; Agricultural Industry"
    }
    ["_industry"]=&gt;
    string(19) "field_566ead58a7828"
    ["end-product"]=&gt;
    array(1) {
      [0]=&gt;
      string(14) "gasoline-tanks"
    }
    ["_end-product"]=&gt;
    string(19) "field_566eae7ca7829"
    ["material"]=&gt;
    array(1) {
      [0]=&gt;
      string(15) "stainless-steel"
    }
    ["_material"]=&gt;
    string(19) "field_566eb006a782a"
    ["_wp_old_slug"]=&gt;
    string(6) "tertre"
    ["top"]=&gt;
    string(1) "0"
    ["_top"]=&gt;
    string(19) "field_5694bc6dc7011"
    ["_thumbnail_id"]=&gt;
    string(3) "416"
    ["content"]=&gt;
    string(0) ""
    ["_content"]=&gt;
    string(19) "field_56ec263325889"
    ["slide_template"]=&gt;
    string(7) "default"
    ["hidden-content"]=&gt;
    string(591) "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet."
    ["_hidden-content"]=&gt;
    string(19) "field_56ec263325889"
  }
}

**Comment by developer-lindner** [comment]
As a workaround i just created another helper function:

`{{ site.prepareContent(post.post_content)}}`

and the function itself:

`function prepareContent($content){
        return apply_filters('the_content', $content);
    }`

But normally Timber should already have been doing this.

**Comment by connorjburton** [comment]
Hmm, `.content` should add that filter by default, you shouldn't have to `apply_filters`. Could you screenshot the post that is linked (208) please? Or describe what that post actually contains (what are you expecting from `.content`?

**Comment by developer-lindner** [comment]
The post content just got standard wysiwyg content, but some posts will have additional shortcodes which are not processed right now (except through my helper function).

**Comment by developer-lindner** [comment]
Could give you a copy to have a deeper look?!

**Comment by connorjburton** [comment]
Hi @developer-lindner - the theme files + DB would be good so I can have a proper look. I've had issues in the past with related repeater fields.

Feel free to email them me at connorjburton@gmail.com

**Comment by developer-lindner** [comment]
Hi @connorjburton, just send you a mail with all details!

**Comment by connorjburton** [comment]
Yep, got it, leave it with me and I will reply on here when I've taken a look.
