### ISSUE TITLE
Q: TimberImage resizing and quality

### ISSUE THREAD

**Issue by ogrosko** [timber/timber#925]
Hi I have some questions

Is it possible to set image quality for TimberImage?

And

Is it possible to resize image with twig resize filter and keep aspect ratio? 
E.G: I have original image (4000x5000) and I resize it to image|resize(1920,1000) and I need to keep aspect of original image (4:3). Is it possible?

**Comment by connorjburton** [comment]
Hi @ogrosko - Timber uses wordpress internals for resizing so I believe setting https://developer.wordpress.org/reference/hooks/jpeg_quality/ would work - obviously only after you have set that filter. You can't regenerate resized images currently. For more in-depth image manipulation you should look at https://github.com/MINDKomm/Timmy - which is a plugin for Timber.

In terms of aspect ratios, you can resize just by width, by leaving the height blank. E.g

`TimberImage(URL)|resize(400)`

Hope that answers your questions
