### ISSUE TITLE
Parent / Child Theme issue

### ISSUE THREAD

**Issue by JakeHenshall** [timber/timber#928]
### Expected behavior

Require Timber in the parent theme which in-turn should carry it through to the child theme.

### Actual behavior

Throwing these errors:
![beast dev base contact](https://cloud.githubusercontent.com/assets/4720782/14229905/320d447e-f93b-11e5-9ac1-3ae7c0b7db5f.png)

Extra Details of how my framework is laid out.

composer.json

<img width="507" alt="screen shot 2016-04-03 at 01 25 33" src="https://cloud.githubusercontent.com/assets/4720782/14229909/6e97763a-f93b-11e5-94dd-e32ca18ab452.png">

File Structure:

<img width="184" alt="screen shot 2016-04-03 at 01 25 19" src="https://cloud.githubusercontent.com/assets/4720782/14229911/82fe806e-f93b-11e5-851a-1645aaefd250.png">

Parent functions.php

<img width="638" alt="screen shot 2016-04-03 at 01 25 06" src="https://cloud.githubusercontent.com/assets/4720782/14229912/8e84ad50-f93b-11e5-880b-751a5cc57f72.png">

### What version of WordPress, PHP and Timber are you using?

4.4.2 PHP7 Timber 0.22.6

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Composer/Packagist

I'm really confused as to what the problem might be any help would be great.

Thanks Jake.

**Comment by connorjburton** [comment]
Hmm, looks like you are possible init'ing Timber twice? Directly loading `/vendor/autoload.php` and `/vendor/timber/timber.php`? Could you try removing the latter

**Comment by Resauce** [comment]
@connorjburton Hi mate, i've removed each one and i still get the same results. as the first message.

**Comment by JakeHenshall** [comment]
@connorjburton Hi mate, i've removed each one and i still get the same results. as the first message.

**Comment by connorjburton** [comment]
For now I think I'd recommend doing `composer require timber/timber:dev-master` and removing the `installer-paths` for Timber. That way you should just be able to require the composer's autoloader and not directly reference `timber/timber.php`

Let me know if that works.

**Comment by JakeHenshall** [comment]
@connorjburton I've just tried the dev-master version and left hte installer paths in and its seemed to have worked, any explanation for that :|, cheers

**Comment by connorjburton** [comment]
Okay cool, I guess because the installer path won't find `jarednova/timber` anymore so it won't make a difference.

When `1.0` is released you will want to make sure to migrate over to that.

**Comment by JakeHenshall** [comment]
@connorjburton Do you know when 1.0 is going to be released?

**Comment by connorjburton** [comment]
Preliminary date is W/C 11th April
