### ISSUE TITLE
Yoast is not working

### ISSUE THREAD

**Issue by trajektorijus** [timber/timber#929]
### Expected behavior
`

META tags generated by Yoast

`

### Actual behavior
`

`

### Steps to reproduce behavior
Install empty theme.
Install Timber and Yoast.
Use Timber routes to render the page.
Use {{ wp_head }} to get Yoast code.

### What version of WordPress, PHP and Timber are you using?
Latest versions

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Doesn't matter

Please can someone provide me a quick fix for this?

**Comment by connorjburton** [comment]
Hi @trajektorijus - is `WP_DEBUG` turned on? Do you get any errors?

**Comment by trajektorijus** [comment]
Yes, no errors.

Just tested with Timber starter theme - it works.
So the problem should be in the router...

**Comment by stewarty** [comment]
Hi @trajektorijus 

Did you set up the router to go to a page that already exists or to a new page that you are creating using templates?  And what is the status of the query_vars object within that page?

**Comment by connorjburton** [comment]
I have just checked on a site I have developed before that used routes and yoast seems to work (see http://www.annemillsrecruitment.co.uk/apply/small-business-accountant-birmingham/)

Any updates on your end?

**Comment by connorjburton** [comment]
Going to close this for now as I can not replicate.
