### ISSUE TITLE
escaping file extension (.twig) while including or extending a file.

### ISSUE THREAD

**Issue by kala725** [timber/timber#933]
### Expected behavior

Should take the file. Suppose I have a file called "default.twig" so {extends 'default'} should render the file. Currently it is throwing an load error. The similar functionality is provided in TwigBridge (Laravel)

### Actual behavior

Throwing an error

### Steps to reproduce behavior

just include a file without .twig extension. It will throw Twig_Error_Load

### What version of WordPress, PHP and Timber are you using?

Wordpress 4.3
Timber 0.21.10
Php 5.5

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Github through composer dependency

**Comment by jarednova** [comment]
I'm closing out old issues. Please open a fresh issue if this is still a live issue that we should investigate — thank you!
