### ISSUE TITLE
Comment Author link

### ISSUE THREAD

**Issue by ChaimaeCh** [timber/timber#936]
Hello there !
First of all, thank your for this amazing plugin that nearly changed my life (hello separated template and php file ! 💃 ) ! It's really simple to use and your doc is amazingly done :)

My problem is that I can't find how to display the comment author link (with comment.autho.link ou something like that). I looked everywhere and even checked te TimberComments file but I can't find anything. I apologize in advance if this is mentioned somewhere :)

Thank you ! 😄

**Comment by connorjburton** [comment]
A timber comment user is a `TimberUser` (http://timber.github.io/timber/#timberuser) which should mean that `comment.author.link` should work, as long as the user is not anonymous

Hope that helps!

**Comment by ChaimaeCh** [comment]
My users do not have to be registered to comment but they can give their website and that's what I'm trying to show but I always get http://www.unepinceedesel.com/author as their link. That's what I can't understand :)

Is that the way it should work ? Because every blog I visit, I don't need to be registered but people can clck on my name to visit my site. Sorry if I'm not clear enough :)

Thanks in advance ! ^__^

**Comment by connorjburton** [comment]
Ah. Okay. You'll have to leave it with us, we will investigate.

Thanks for raising the issue

**Comment by ChaimaeCh** [comment]
Nevermind, I did this to get it : 
`{{function('comment_author_link', comment.ID)}}` if it can help :)

Thank you for your help and time :D
