### ISSUE TITLE
Errors using Timber in a custom plugin when it is not used in a theme? 

### ISSUE THREAD

**Issue by benedict-w** [timber/timber#938]
I am using composer to include Timber as part of a custom plugin I am writing, the site theme is not using Timber. Apologies if this is covered elsewhere (using Timber in a custom plugin - I couldn't find anything):

`Warning: Invalid argument supplied for foreach() in /wp-content/plugins/timber/lib/timber-loader.php on line 177`

Here it seems that in the function get_locations_theme_dir: `Timber::$dirname` is `null`

I also have errors using the built in gettext function:

`Twig_Error_Syntax: Unknown "__" function in ...`

Assume that something is wrong with registering the function - perhaps I set it up wrong or there is something wrong with the autoload?

**Comment by connorjburton** [comment]
There is some information here https://github.com/timber/timber/issues/248 - however I will leave this open to investigate.

**Comment by jarednova** [comment]
I'm closing out old issues. Please open a fresh issue if this is still a live issue that we should investigate — thank you!
