### ISSUE TITLE
Sticky post class is not displayed

### ISSUE THREAD

**Issue by chetzof** [timber/timber#939]
### Expected behavior

The `sticky` post class should be added to the post in the post list

### Actual behavior
The `sticky` post class is NOT present in the class list

### Steps to reproduce behavior
Set a blog post as sticky.

### What version of WordPress, PHP and Timber are you using?
WordPress 4.5, PHP 7, Timber 0.22.5 

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Upgraded to newest version via plugin updater in WordPress dashboard

Calling the native wordpress function `post_class() ` outputs all the correct classes

**Comment by connorjburton** [comment]
Just tested this and it seems to work okay for me, could you please try this on a fresh installation?

**Comment by connorjburton** [comment]
Going to close this for now as it seems fine on fresh install. Let me know if you have more info
