### ISSUE TITLE
ACF has_field

### ISSUE THREAD

**Issue by connorjburton** [timber/timber#942]
### Expected behavior
`post.has_field('foobar')` => boolean depending on if it exists or not on that post

### Actual behavior

`NULL`

### Steps to reproduce behavior

- Create a post with ACF field 'foobar'
- Try `post.has_field('foobar')`
- Will return `NULL`

### What version of WordPress, PHP and Timber are you using?

Latest all

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Composer

**Comment by jarednova** [comment]
Closed by #1024
