### ISSUE TITLE
Author Avatar?

### ISSUE THREAD

**Issue by alzearafat** [timber/timber#943]
Hi,

Thanks for excelent tool! It's really help me a lot,

Anyway, how I can get author avatar URL? Something like this : 

```
{{ post.author.avatar }}
```

The documentation only explain comment avatar.

Thank you in advance for any help you can provide,
Regards

**Comment by connorjburton** [comment]
This actual doesn't seem to be possible at the moment, it shouldn't be too difficult of a fix. Will look at this post `1.0.0` (soon)

**Comment by alzearafat** [comment]
Hi @connorjburton 

Wow, cool! :D 

I will follow the progress ;)

Thank you

**Comment by connorjburton** [comment]
Merged
