### ISSUE TITLE
ACF Post Object does not return as TimberPost

### ISSUE THREAD

**Issue by connorjburton** [timber/timber#944]
### Expected behavior

For posts than are selected via ACF Post Object to return as a `TimberPost`

### Actual behavior

Returns as `WP_Post`

### Steps to reproduce behavior

1. Create an ACF field that is of type `Post Object`
2. Get that field in the template `{% set foo = post.get_field('foobar') %}`
3. `foo` = `WP_Post`

### What version of WordPress, PHP and Timber are you using?

All latest

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Composer

**Comment by stefthoen** [comment]
Has this change been reversed? I'm still getting `WP_Post` when I assign a ACF `Post Object` to `foo`.
