### ISSUE TITLE
[SOLVED] Dynamic sidebar not working?

### ISSUE THREAD

**Issue by alzearafat** [timber/timber#946]
Hi,

I following this doc : http://timber.github.io/timber/#sidebars
But cannot make it work. I want to put my widget in the footer.
Please take a look : 

**functions.php**
```
/**
 * Register our sidebars and widgetized areas.
 *
 */
function sentinel_widgets_init() {

	register_sidebar( array(
		'name'          => 'Home Footer',
		'id'            => 'home_footer_1',
		'before_widget' => '<div>',
		'after_widget'  => '</div>',
		'before_title'  => '<h2 class="rounded">',
		'after_title'   => '</h2>',
	) );

}
add_action( 'widgets_init', 'sentinel_widgets_init' );
```

**sidebar.php**
```
 $context = array();
 $context['home_footer_1'] = Timber::get_widgets('home_footer_1');
 Timber::render('footer.twig', $context);
```

**footer.twig**
```
      <div class="small-12 medium-6 large-4 column">
        {{ home_footer_1 }}
      </div>
```

If I'm doing it wrong, please let me know. The documentation (dynamic sidebar) does not explain in detail where I had to put my code :(

Thank you in advance for any help you can provide,
Regadrs

**Comment by JakeHenshall** [comment]
@connorjburton Hey, i'm also trying todo something similar, I can't seem to allow the widgets to be displayed across all of my pages. instead of putting mine in sidebar.php there are in footer.php but the code is pretty much the same.

**Comment by alzearafat** [comment]
Hi @JakeHenshall 

Thanks, but I still cannot get it working :(

Can you please post detailed codes/steps?

Thank you
Regards

**Comment by alzearafat** [comment]
UPDATE

Finaly, I made it working. These is my steps (I don't know whether this is the best solution or not, but at least it works for me) :

I want to display dynamic sidebar/widget on the homepage/all page,

**functions.php**
```
/**
 * Register our sidebars and widgetized areas.
 *
 */
function sentinel_widgets_init() {

	register_sidebar( array(
		'name'          => 'Home Sidebar',
		'id'            => 'home_sidebar',
		'before_widget' => '<div>',
		'after_widget'  => '</div>',
		'before_title'  => '<h2 class="rounded">',
		'after_title'   => '</h2>',
	) );

}
add_action( 'widgets_init', 'sentinel_widgets_init' );
```

Instead of putting the code in sidebar.php, I put it in index.php : 

**index.php**
```
$context['dynamic_sidebar'] = Timber::get_widgets('home_sidebar');
$templates = array( 'index.twig', 'base.twig' );
```

And I call the code in the base.twig file : 

**base.twig**
```
<p>{{dynamic_sidebar}}</p>
```

@connorjburton @jarednova  Maybe you can update the doc to make it more detailed. The documentation now is very minimal, and confusing, especially for newbies like me.

Thank you,
Regards

**Comment by connorjburton** [comment]
Will re-open till we update the docs

**Comment by twentyfortysix** [comment]
Doesn't work for me.

index.php
```
$data = Timber::get_context();
$data['footer-widgets'] = Timber::get_widgets('front-row-3');
var_dump($data['footer-widgets']); // returns the strings (html output) of the sidebar widgets
```
index.twig
```
{{ footer-widgets }} // returns nothing
{{ dump(footer-widgets) }} // returns "int 0"
```

wordpress 4.5 (only Timber plugin), php 5.6

**Comment by connorjburton** [comment]
Try setting the data to footer_widgets

**Comment by twentyfortysix** [comment]
Okej, I have figured out why, though it is confusing.

all I have written above is still valid.
The problem is the dash "-" in the name of the variable
this will output nothing in the *.twig template:
```
$data['footer-widgets'] = Timber::get_widgets('front-row-3');
$data['what-ever'] = Timber::get_widgets('front-row-3');
```
this will work:
```
$data['footer_widgets'] = Timber::get_widgets('front-row-3');
$data['what_ever'] = Timber::get_widgets('front-row-3');
```
why is that?

**Comment by connorjburton** [comment]
Twig doesn't allow dashes in variables, only array elements accessed like `item['some-dash']`. Not much we can do about it other than throw errors when trying to set data with dashes I guess.

**Comment by twentyfortysix** [comment]
Thanks for the help.
The problem is that does not throw any error. Instead the output is "muted". Plus while you try to {{dump(some-data)}} it either returns 0 or on some hostings it fails completely returning the white screen of death. Without any error, no matter how much you wanna force the information to be shown. That kinda puzzled me in a way that I moved it all to localhost where I have bit more freedom.
```
{{dump(some-data)}} // result in HTTP ERROR 500 on some hostings
```
I guess this goes after the Twig it self.

**Comment by connorjburton** [comment]
I'll have a look into what we can do about throwing errors/notices.

**Comment by nurofsun** [comment]
or you may want to add 'dynamic_sidebar' to $context variable inside add_to_context() in your file functions.php 

the code as follow

`	public function add_to_context( $context ) {
		$context['foo']   = 'bar';
		$context['stuff'] = 'I am a value set in your functions.php file';
		$context['notes'] = 'These values are available everytime you call Timber::context();';
		$context['menu']  = new Timber\Menu();
                /** dynamic_sidebar **/
		$context['dynamic_sidebar'] = Timber::get_widgets('aside_sidebar');
		$context['site']  = $this;
		return $context;
	}
`
