### ISSUE TITLE
Function get_term can't be stored as variable

### ISSUE THREAD

**Issue by adi8i** [timber/timber#962]
I try to check if a field is filled or not storing the function, `{% set test = function('the_terms', post.ID, 'service_type') %}` then i could use `if is not empty'. 

Instead of storing the function it render on front end, as far as i know only `{{ }}` should render something. 

This works: `{% set notes_field = function('get_post_meta', post.ID, 'notes', 'true') %}`
But this doesn't: `{% set test = function('the_terms', post.ID, 'service_type') %}`

Edit: `function('has_term', '', 'service_type', post.ID)` works fine instead. I'll leave the issue open though, i wait your confirmation, if this is the right way or it's a bug.

**Comment by connorjburton** [comment]
`the_terms` displays the terms, it doesn't return them. You are probably looking for something like https://codex.wordpress.org/Function_Reference/get_the_term_list
