### ISSUE TITLE
Return empty array with Timber::get_posts()

### ISSUE THREAD

**Issue by orest22** [timber/timber#963]
### Expected behavior
I would like to use `Timber::get_posts($args, 'Person')` to get array of CPT objects. In $args I've set `post_type=>'person'`. But it returns empty array. In other way if I replace `$args` with query string it works fine.

### Actual behavior
Empty array.

### Steps to reproduce behavior

1. `Timber::get_posts(array('post_type'=>'person'), 'Person');`
2. Return empty
3.  `Timber::get_posts('post_type=person', 'Person');`
3. Return array of Person objects

### What version of WordPress, PHP and Timber are you using?
Wordpress 4.4.2, PHP 5.6, Timber 0.22.6

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by jarednova** [comment]
Hmmmmm, mighty strange. I'll see if I can do a quick test to replicate

**Comment by jarednova** [comment]
@orest22 — I wrote a test for your scenario in 1c40dae288d55778f3c6459ea8a20e9cbb27c906 and it passes. Can you see if there's anything else in your code that might be weird? Also, try upgrading to the current version (1.0.0-rc3) and see if the issue still occurs

**Comment by connorjburton** [comment]
Yes we have likely fixed this as we modified how that works in recent versions.

**Comment by orest22** [comment]
@jarednova Yeah you are right everything works even with 1.0.0-rc2 (Didn't see that you have changed package name). Thank you guys!
