### ISSUE TITLE
Get term name or slug from selected value from Advanced custom fields

### ISSUE THREAD

**Issue by tonimain** [timber/timber#965]
I want to display taxonomy name from my select tasonomy. I added the taxonomy field via advanced custom fields.
It allows me to save the value as object or as reference with id.

So my question is there something special like the standard term function in timber related to the taxonomy field from advanced custom fields ?

At the moment i just get the id's but have no idea how to resolve this to the correct name?
Write own viewhelper ?

**Comment by connorjburton** [comment]
You should be able to do `TimberTerm(id)` which should returns all the details for that term.
