### ISSUE TITLE
New to Timber - Question regarding build process

### ISSUE THREAD

**Issue by dsifford** [timber/timber#966]
Forgive me if this sounds brash, but I'm stunned that in order to use Timber for development, you are required to install a TImber WordPress plugin alongside your theme.

Is this correct? How do theme developers make use of this?

Why not compile the php files _before_ uploading to WordPress using `<insert your favorite taskrunner here>`?

Am I overlooking something or is this seriously how TImber works?

**Comment by alenabdula** [comment]
> you are required to install a Timber WordPress plugin alongside your theme.

Yes. Just like any other WordPress plugin. You could require it via Composer if that's your thing.

> How do theme developers make use of this?

RTFM [here](http://upstatement.com/timber/)

> Am I overlooking something or is this seriously how Timber works?

Yes you are. Issue with WordPress is that data and templates are closely tied together. Having data (Model) and template (View) separated gives you greater control.

Timber helps in this regard by separating your PHP logic (stuff that you do to get the data, for example in your `page.php` file) and then it sends that data to be processed by Twig, which is just a templating language. In addition Timber provides many conveniences and helpers that IMO make developing fun.

Hope that helps. Best, Alen.

**Comment by dsifford** [comment]
Thanks for the clarification.

I suppose still my biggest question is: Why is it necessary to keep the model and view separate when WordPress is deployed? 

I totally agree that separation of concerns is absolutely the thing to do during development. 100% in agreement. However, when ready to deploy, why not have Timber build the files PRIOR to uploading them into WordPress (ie. load up the compiled files)? The fact that a build dependency is required during production is, IMHO, sort of silly.

In a perfect world, you'd be reducing the number of files (and shrinking their size) before uploading to your production server so that you 1) reduce the network load and 2) increase the speed of your application.

I understand this project is in pretty deep already, but I hope you might be able to consider some of these things for the future. At present, this is unfortunately not useful for me. 

Hope this isn't taken the wrong way. Figured you might appreciate some honest feedback from the other side of the fence.

**Comment by alenabdula** [comment]
> why not have Timber build the files PRIOR to uploading them into WordPress (ie. load up the compiled files)?

Timber is a library. Not a build tool. Plus, I think you might be confused how WordPress works, as it loads appropriate template based on query string. If you're looking to improve performance, you'd be far better off optimizating media like images, and adding server caching, so that compiled html can be served which will essentially improve server response time.

> In a perfect world, you'd be reducing the number of files (and shrinking their size) before uploading to your production server so that you 1) reduce the network load and 2) increase the speed of your application.

Are you talking about compiling to PHP templates first, then shrinking the actual PHP files that sit on the server? Am really confused at this point. That would not improve performance, at least nothing noticeable to the visitor. Over-optimization IMO.

> separation of concerns is absolutely the thing to do during development

Separation of concerns has nothing to do with your environment. So am not sure where you're going with this.

**Comment by dsifford** [comment]
Okie dokie, we'll agree to disagree! 

I'm not a PHP guy (or a fan to be perfectly honest) so you probably make points that are simply out of my pay-grade.

I have a single plugin that I'm actively developing and, in the (very very few) PHP files that it has, I was in the market for something that would allow me to separate the template from the logic and then recombine before deployment. The good news is, I found it. 

You can see where my vision was going (that is, if my lack of php knowledge has piqued your interest enough to make you curious) by looking at my ABT repo in my profile.

I appreciate the conversation. Again, sorry if I came off as a snooty jerk.

**Comment by alenabdula** [comment]
I don't care to agree or disagree. I'm only providing information and perspective. At least next time explain your issue at length, so that we can understand context. Instead of coming on here and bashing project; without even reading documentation.

Let's get serious and put our big boy pants on.
