### ISSUE TITLE
WP_Query Order by Future ACF Date & Time Picker Field

### ISSUE THREAD

**Issue by CelticParser** [timber/timber#967]
I have tried various combinations in the wp_query args and I cannot omit past events relative to the current date from displaying in the loop. I have verified that the ACF key, `event_date` is formatted as `yymmdd` in the db table.

I am testing with five Event custom-post-type(s) dated withe the ACF field `event_date`; Two are  in the future and the rest are dated prior to the current date. 

Most likely I have something wrong some where so any guidance will be appreciated.
### Expected behavior

Custom Post-Type listed by **current date** to future dates (_not past dates_). Only 2 events should be listed because the remaining events are `'meta_compare' => '>=',` in relation to the current date.

**Output:**

```
<section>

    <article>

        <p class="meta-top">20160503</p>
        <h1 class="article-title">Test Event Future 01</h1>
        <p class="meta-bottom">Crescent Ballroom - Phoenix, AZ</p>

    </article>

    <article>

        <p class="meta-top">20160520</p>
        <h1 class="article-title">Test Event Future 02</h1>
        <p class="meta-bottom">Google Kirkland - Kirkland, WA</p>

    </article>

</section>
```
### Actual behavior

Custom Post-Type listed by **past date** to future dates. Three Events are listed ( limited to `'posts_per_page'  => 3` ), one being dated prior to the current date.

**Output:**

```
<section>

    <article>
        {# -- Should not be listed -- #}
        <p class="meta-top">20160502</p>
        <h1 class="article-title">Test Event Old</h1>
        <p class="meta-bottom">Grand Ole Opry - Nashville, TN</p>

    </article>

    <article>

        <p class="meta-top">20160503</p>
        <h1 class="article-title">Test Event Future 01</h1>
        <p class="meta-bottom">Crescent Ballroom - Phoenix, AZ</p>

    </article>

    <article>

        <p class="meta-top">20160520</p>
        <h1 class="article-title">Test Event Future 02</h1>
        <p class="meta-bottom">Google Kirkland - Kirkland, WA</p>

    </article>

</section>
```
### Steps to reproduce behavior

```
// $time = current_time( 'YYYYMMDD' ); // Nothing Displays
// $time = current_time( 'yyyymmdd' ); // Everything Displays
// $time = date('yymmdd'); // Everything Displays
$time = current_time( 'timestamp' ); // Everything Displays

// Tried other formats but I cannot recall all of them.

$events_args = array(
    'post_type'         => 'event',
    'post_status'       => 'publish',
    'orderby'           => 'meta_value',
    'meta_key'          => 'event_date',
    'meta_value'        => $time,
    'meta_compare'      => '>=',
    'order'             => 'ASC',
    'posts_per_page'    => 3,
);

$context            = Timber::get_context();
$post               = new TimberPost();
$context['post']    = $post;
$context['events']  = Timber::get_posts($events_args);

Timber::render('pages/page-events.twig', $context);

```
### What version of WordPress, PHP and Timber are you using?
- WordPress 4.5.1
- PHP 7
- Timber 0.22.5
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
- Composer as `"web/app/mu-plugins/{$name}/"`

**Comment by connorjburton** [comment]
Hi, could you please test this without Timber? With a `WP_Query`?

**Comment by connorjburton** [comment]
Any updates on this @CelticParser?

**Comment by palmiak** [comment]
Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
