### ISSUE TITLE
apply_filters

### ISSUE THREAD

**Issue by pboisclair** [timber/timber#972]
Hi, 

I don't figure out how to use apply_filters in Timber with WPML filters. 
E.g.: 
{% set id = 10 }
{{ id|apply_filters(t 'wpml_object_id', id, 'page' )}} 
{{dump(id)}}
Result:
id = 10 (french id page) but is supposed to be 20 (English id page)

It display the original id. I need more info about that? It's possible?

There is a forum who can ask this type of question, because is not an issue.

Thanks

**Comment by connorjburton** [comment]
You can try asking the question here http://stackoverflow.com/questions/tagged/timber there may be more people there that have done this.

**Comment by lkraav** [comment]
Side note: why are we not using http://wordpress.stackexchange.com instead?

**Comment by connorjburton** [comment]
I assume it's a legacy thing, I wonder if you can set up a redirect on Stackexchange

**Comment by pboisclair** [comment]
Thanks guys

**Comment by chrisgherbert** [comment]
The Stack Exchange WordPress community doesn't allow questions about plugins.
