### ISSUE TITLE
Q:Timber cache

### ISSUE THREAD

**Issue by ogrosko** [timber/timber#973]
Hi I have question about timber cache
I have following config:

`define('CACHE_TIME', 86400);
define('TIMBER_CACHE', true);`

`\Timber::$cache = TIMBER_CACHE;`

each template is rendered as follow:
`\Timber::render( 'pages/single/event.twig', $context, CACHE_TIME);`

In DB I can see some records like 

> _transient_timberloader...

And each minute database grow up in 1MB
And wp_options getting huge 100-200MB then queries on wp_options are too long

What I'm doing wrong? What is the best practise for cache settings?

**Comment by connorjburton** [comment]
I have a few sites that have had cache on for a long time and all of them are around 2-3MB, are you sure it's Timber causing this?

**Comment by ogrosko** [comment]
Yes when I delete all _transient_timberloader records database reduced from approx. 100MB to 35MB

**Comment by connorjburton** [comment]
What version of Timber and wordpress are you using?

**Comment by ogrosko** [comment]
wp: 4.5.1
timber: 0.22.6

**Comment by ogrosko** [comment]
Any news about this?
I forget to mention that W3 total cache is also installed

**Comment by connorjburton** [comment]
It's hard to debug, I would try disabling w3 total cache, I can't imagine Timber does this by itself, there will something else effecting the caching system.

**Comment by connorjburton** [comment]
Any updates @ogrosko

**Comment by ogrosko** [comment]
I test it locally it works with no problems.
On live server I changed timber cache time to 5 days. And checking situation how many database will grow up.

**Comment by connorjburton** [comment]
Any updates @ogrosko ? Thanks

**Comment by ogrosko** [comment]
No idea where is the problem
After few days database grows to 250MB :( And no idea where is the problem.

What about to disable timber cache?

**Comment by connorjburton** [comment]
Is this with disabling W3 cache?

**Comment by ogrosko** [comment]
I little worry to disable w3 total cache plugin on live server

**Comment by jakubkaderavek** [comment]
Hi,

I have same problem and in my case is because my client use Google Adwords. When use go to page via PPC, then have unique param gclid in url and Timber create new cache for this page. Of course there can be another params eg. utm,...

But I don't have solution how to exclude some params to not create unique cache.

Thanks for help

**Comment by palmiak** [comment]
@ogrosko Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
