### ISSUE TITLE
Notice errors for the latest upgrade notification

### ISSUE THREAD

**Issue by chetzof** [timber/timber#974]
In the plugin list i've got notification to upgrade to new Timber update, however inside this notification there are lots of notice and deprecated warnings:

``Deprecated: Non-static method TimberAdmin::in_plugin_update_message() should not be called statically in /srv/www/project/current/web/wp/wp-includes/plugin.php on line 525``

``Notice: Trying to get property of non-object in /srv/www/project/current/web/app/plugins/timber-library/lib/timber-admin.php on line 42``

``Notice: Trying to get property of non-object in /srv/www/project/current/web/app/plugins/timber-library/lib/timber-admin.php on line 45``

``Notice: Trying to get property of non-object in /srv/www/project/current/web/app/plugins/timber-library/lib/timber-admin.php on line 54``

PHP 7, Wordpress 4.5.1

**Comment by jarednova** [comment]
Thanks @chetzof! I'll get right on that

**Comment by jarednova** [comment]
Thanks again @chetzof — this is closed #976

**Comment by chetzof** [comment]
Thanks! Is there a solution for users that cannot update to the 1.* version of the plugin? I've got users complaining that it broke their plugin list page, they that are on Version 0.22.6 and cannot upgrade to new version due to deprecations.

**Comment by jarednova** [comment]
@chetzof I just updated the code for 0.22.6 being served from WordPress.org. You can also directly update the `lib/timber-admin.php` file with the contents of this gist:

https://gist.github.com/jarednova/e8a18361412ee4e7c40297ef815e714e
