### ISSUE TITLE
Failed to load template for single-posttype.twig (v1.0)

### ISSUE THREAD

**Issue by minthemiddle** [timber/timber#975]
### Expected behavior
In version 0.22.5 I could load a template for all custom posttypes via `function.php` and the following settings:

(single.php)
```php
$post = Timber::get_post('TimberPost');
(...)
Timber::render(array('single-' . $post->post_type . '.twig', 'single.twig'), $data);
```

### Actual behavior
With version 1.0, I get with my custom posttype `unternehmen` such as in [this link](https://karriere-papier-verpackung.de/unternehmen/strobel-ag-roth/) the following error:

`PHP Fatal error:  Uncaught Twig_Error_Loader: Unable to find template "single-.twig"`

### What version of WordPress, PHP and Timber are you using?
Wordpress 4.5.1, Timber 0.22.5 (no error), Timber 1.0 (breaks custom posttype twig loader)

**Comment by connorjburton** [comment]
Hi @minthemiddle - this is probably due to us removing some functionality to do with 'guessing' what class you want. Could you please try the following:

`$post = Timber::get_post(array(), 'TimberPost');`

**Comment by minthemiddle** [comment]
Ok, let me test this locally.

**Comment by connorjburton** [comment]
Any luck @minthemiddle ?

**Comment by connorjburton** [comment]
Actually try, `TimberPost(false, 'TimberPost')` - I am not sure what you are trying to do with this code however? The first parameter should be your query, and the second parameter is already `\Timber\Post` by default. So this doesn't seem to be doing anything?

**Comment by connorjburton** [comment]
You could actually just remove your call completely and it will work, as `$post` will already be defined by wordpress in `single.php`

I'm going to close this as the `Timber::get_post` call you are doing isn't valid
