### ISSUE TITLE
ACF Repeater not rendering

### ISSUE THREAD

**Issue by swthate** [timber/timber#980]
### Expected behavior
Display ACF Repeater fields

### Actual behavior
Nothing gets rendered

### Steps to reproduce behavior
```php
# template-home.php

{% for item in post.get_field('home_service_list') %}

    <h3>{{ item.home_service_label }}</h3>
    <p>{{ item.home_service_time }}</p>

{% endfor %}
``` 

### What version of WordPress, PHP and Timber are you using?
WordPress 4.5.1, PHP 5.6.10, Timber 1.0.1 -->

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Added plugin from the dashboard.

**Comment by swthate** [comment]
*Update:*

I reverted my Timber version back to 0.22.6 (which did fix some other issues I noticed), but did not fix my repeater field issue.

**Comment by connorjburton** [comment]
Hi, can you dump what is in item. What was the other issue 1.0.1 caused?

**Comment by swthate** [comment]
item turns out to be null.

With 1.0.1 my posts wouldn't load. Got 500 errors.

**Comment by connorjburton** [comment]
I would double check that is the field name and it's populated correctly.
With the 500 error if you turn WP Debug on and switch back to 1.0.1 and
post the error here thatd be really useful.

Thanks

On 5 May 2016 10:22 p.m., "Steven" <notifications@github.com> wrote:
>
> item turns out to be null.
>
> With 1.0.1 my posts wouldn't load. Got 500 errors.
>
> —
> You are receiving this because you commented.
>
> Reply to this email directly or view it on GitHub
<https://github.com/timber/timber/issues/980#issuecomment-217284012>

**Comment by swthate** [comment]
> I would double check that is the field name and it's populated correctly.

Double checked this morning, and ensured my home page template had the fields populated, and from the WP Admin area everything looks fine.

[Here's a screenshot of how I have my custom fields setup.](http://thate.me/images/repeater-fields.jpg)

And here's a little more context to the code I shared above, though I'm not sure more context will necessarily help:

```php
<div class="large-4 column">
    <div class="aside-box">

        {% set service = post.get_template('home_service_list') %}
        {{ dump(service) }} # returns null

        {% for item in post.get_field('home_service_list') %}

            <h3>{{ item.home_service_label }}</h3>
            <p>{{ item.home_service_time }}</p>

            <pre> {{ dump(item) }} </pre> 

        {% endfor %}

    </div>
</div>
```

I don't think I need to, but is there anything I need to add to `home.php` to access ACF fields? I didn't have to in another theme of mine, so I don't think it's that, but I'm just curious.

As for the 1.0.1 issue, I'll create a new issue and post there what I find :)

**Comment by connorjburton** [comment]
I see in your example code you have 

```php
{% set service = post.get_template('home_service_list') %}
{{ dump(service) }} # returns null
```

Which is `get_template` now `get_field` which is why the doesn't work.

The reason your loop doesn't work is because the repeater field will return an array, so you need to do

```php
{% for item in post.get_field('home_service_list') %}

            <h3>{{ item[0].home_service_label }}</h3>
            <p>{{ item[0].home_service_time }}</p>

            <pre> {{ dump(item[0]) }} </pre> 

        {% endfor %}
```

**Comment by swthate** [comment]
Darn code suggestions! Sometimes those cause more trouble than good. Anyway, the array bit makes sense (though I don't remember noticing that in the Wiki's ACF cookbook).

This is very strange. Even after making the changes you listed, the behavior hasn't changed. I made a quick text custom field to test and that one kind of works. By that I mean it will dump correctly, but it won't actually display the string. Eg:

```php
{% set test = post.get_field('home_test') %}
{{ dump(test) }}
```

That returns `STRING(4) "TEST"`

Is `dump(post.get_field(test))` incorrect? I noticed I had to set the test var and call that rather than getting the field within the dump call.

Now, it dumps fine, so I'm assuming the field itself is working correctly. However, when I try to actually print that field, nothing shows up. Eg, `<h5>{{post.get_field('home_test')}}</h5>` just comes up with an empty set of `<h5>` tags in the dom. I also tried calling the test var here but that didn't work either.

Is there anything else embarrassingly simple I'm just not seeing here? 😕

**Comment by swthate** [comment]
I think I finally realized what's going on.

All of this stuff is taking place on the homepage, which is a created page called Home, which uses the home template (`home.twig`). The homepage is this static page so that I can add some ACF fields.

Now, I also wanted to have some of the latest general posts display on the page, too. I'm still really new to Timber, so I was pretty confused as to how to add a WP Query here, but somehow by adding the following to my `template-home.php` file, I could loop through the recent posts:

```php
$args = array( 'post_type' => 'post' );
$context['posts'] = Timber::get_posts( $args );
```

After I remembered all of this, I realized that when I try calling `post.get_field('home_service_list')` It's getting very confused because of the other posts query going on. *Still, if that's the case, why on earth does `dump(home_test)` return that field's contents and the repeater fields don't?*

So if that's what is going on, how do I do something like `wp_reset_query()` in Timber?

**Comment by swthate** [comment]
Final update...

I realized the section where I'm using the ACF fields were never wrapped in the main loop. Now it works.

And if you'll excuse me, I'm now going to bang my head against the wall.

Thanks for your help, @connorjburton sorry to have wasted your time!!

**Comment by connorjburton** [comment]
No problem, anytime :)
