### ISSUE TITLE
1.0 Issue: Posts not displaying

### ISSUE THREAD

**Issue by swthate** [timber/timber#982]
This issue was first mentioned in issue #980.

### Expected behavior
Normal viewing of single posts.

### Actual behavior
After upgrading from 0.22.6 to 1.0.1, I can no longer navigate to any single posts. My homepage and archive pages, etc, all display just fine. But when I try to go to any single post I get the following error:

`Fatal error: Call to undefined method Timber\Helper::get_comment_form() in /Users/steven/Sites/dsi/st-paul-ucc/www/wp-content/themes/st-paul-welcome/single.php on line 15`

Line 15 referenced in the error is `$context['comment_form'] = TimberHelper::get_comment_form();`

### Steps to reproduce behavior
Upgrade from Timber 0.22.6 to 1.0.1 and navigate to any single post.

### What version of WordPress, PHP and Timber are you using?
WordPress 4.5.1, PHP 5.6.10, Timber 1.0.1

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
"Add New" from plugins page in WP Admin area.

**Comment by connorjburton** [comment]
Hey,

`get_comment_form` has been removed (was deprecated for quite a while), please use `{{ fn('comment_form') }}` in your `.twig` file instead

**Comment by katipierson** [comment]
Hello,

This is no solution for me. 
I need the options array for the comments. I tried to do this in twig, but it doesn't work and it isn't a clean way to write code.

How can i use it in the controller?

TimberHelper::comment_form doesn't work there.

Greetings

**Comment by connorjburton** [comment]
`get_comment_form` will be back in `1.0.2`

**Comment by adhorrig** [comment]
Where is ```comment_form``` coming from? It seems to be outside of the starter-theme that I'm working with. I want to add to it but can't find where it resides. I.e. ```{{ fn('comment_form') }}``` will display the comment form, but I want to find the origin of it.

**Comment by katipierson** [comment]
{{ fn('comment_form', comment_args, post.ID) }} - works for me

but it works also 

{{ comment_form }} - if you create it in your single.php in this way:
$context['comment_form'] = comments_template($context['comment_args'], $post->ID);

**Comment by adhorrig** [comment]
Oh, sorry if I wasn't clear. It works for me, I am wondering where the markup for the ```comment_form``` is coming from. 😄

**Comment by katipierson** [comment]
Oh sorry. 

It comes from Helper.php. And You can change it in two ways. You can use
`{{ fn('comment_form', comment_args, post.ID) }}` in twig and set "comment_args" in twig or better in your php-file in this way:
```
$context['comment_args'] = array(
    'title_reply' => 'Schreibe einen Kommentar',
    'title_reply_to' => 'Antworte auf den Kommentar von %s',
    'must_log_in' => '<div class="comment-user-login">Nur registrierte Benutzer können Kommentare schreiben. <a class="comment-user-login-link" href="#kommentar" data-target="#layer-login" data-toggle="modal">Einloggen</a>.</div>',
    'logged_in_as' => '',
    'comment_notes_after' => '',
    'comment_field' => '<textarea id="comment" name="comment" class="form-control" rows="3" aria-required="true"></textarea>',
    'label_submit' => 'Senden',
    'class_submit' => 'btn btn-default comment-form-submit',
);
```
Or you can redeclare it in your php-file with
`$context['comment_form'] = get_comment_form($context['comment_args'], $post->ID);`

Cheers
