### ISSUE TITLE
User.avatar not resizable

### ISSUE THREAD

**Issue by Juleship** [timber/timber#983]
### Expected behavior
I'd like to resize the picture of the avatar via Timber utilities

### Actual behavior
The image doesn't accept size parameters

### Steps to reproduce behavior
1. {{ post.author.avatar }}
2. {{ post.author.avatar | resize(400, 400)} }}
3. The picture is not really resized, it's stretched

### What version of WordPress, PHP and Timber are you using?
WP 4.5.2  
Timber 1.0.1

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Natively via the plugin installer inside wordpress from the plugin list

**Comment by connorjburton** [comment]
Good point, for now you can do `{{ TimberImage(post.author.avatar).src|resize(400) }}` - I will change this so it returns a `TimberImage` by default in `1.0.2`
