### ISSUE TITLE
Q: Getting post type labels

### ISSUE THREAD

**Issue by swthate** [timber/timber#992]
I've been looking all over on how to get post type labels/names into my theme. Originally I did `post.post_type`, but that returns something like "galleries" or "cabinet-meetings". What I want it to return is the *name* label: "Cabinet Meetings". Is it buried away in some post object or something? I did `dump(post)` but all it showed as far as post types was `["post_type"] => string(16) "cabinet-meetings"`.

Thanks!

**Comment by connorjburton** [comment]
This is a very good question, got a feeling this will require a new `Timber\PostType` object that you can pass the slug/id into and get all the details of.

Thoughts @jarednova - should be fairly simple to implement

**Comment by jarednova** [comment]
actually `{{ post.get_post_type }}` will return the object that @swthate is looking for. That said, this might be ripe for revisiting with some clearer syntax soon (I have an idea that I'll PR)

**Comment by swthate** [comment]
Ah-ha. `dump(post.get_post_type)` does return exactly what I'm looking for. Not sure how to go about extracting `["labels"] => { ["name"] => "Calendars" }` though (or is that what you have an idea on? :))

**Comment by nickmoline** [comment]
since in twig objects and arrays are treated the same way (dot notation), it should be `{{ post.get_post_type.labels.name }}`

**Comment by swthate** [comment]
Sweet. I wasn't sure that I was able to make a chain that long!

Thanks, @nickmoline

**Comment by jarednova** [comment]
closed by #1003

**Comment by christophhapple** [comment]
Since `post.get_post_type` has been deprecated in 1.4 I was just wondering if there is any sort of replacement for this?
If not, what is the best practice to get post type labels in a template?

**Comment by jarednova** [comment]
@christophhapple here ya go ...

`{{ post.type.labels.name }}`

if you do a `{{ dump( post.type ) }}` you can see everything inside the object you might want to use

**Comment by christophhapple** [comment]
Thanks @jarednova for getting back to me so quickly.
Shame on me for missing that ...

**Comment by jarednova** [comment]
This is WordPress development — there's no room left for shame
