### ISSUE TITLE
Repeater within Relationship returning String instead of Array

### ISSUE THREAD

**Issue by cheestudio** [timber/timber#993]
### Expected behavior
I have a relationship field pulling in a repeater of images and expect them to display.

### Actual behavior
If I print_r I only get the count of how many images there are printed. A dump returns:

string(1) "4" 

I tried setting the repeater field to return Array, URL and ID on the image field and they all produce the same result. I know I've done this in past versions of Timber, so I'm wondering if something has shifted in how I need to get these field values?

### Steps to reproduce behavior

PHP file:

`
$context['featured_case_studies'] = get_field('featured_case_studies');
`

Twig file:

`          {% for study in featured_case_studies %}
            {% set study = TimberPost(study) %}
              <div class="case-study-entry" id="study-0{{loop.index}}">
                <div class="study-title">
                  <span>Case Study</span>
                  <h4>{{study.title}}</h4>
                  <h3 class="location">{{study.location}}</h3>
                  <a href="" class="view-photos"><img src="{{site.theme.link}}/assets/img/view-photos.gif" alt=""></a>
          <div id="" class="project-photos">
             {{ dump(study.project_photos) }}
                  {% for photo in study.project_photos %}
                    <a href="" rel="study-0{{loop.index}}" class="fancybox"><img src="{{TimberImage(photo.project_image).src|resize(1200,9999,'center')}}" alt=""></a>
                  {% endfor %}
                </div>
                </div>
              </div>
            {% endfor %}`

(Not sure why my code won't format properly, sorry for that. Spacing it out only made it worse).

### What version of WordPress, PHP and Timber are you using?
WP 4.5.2 and Timber 10.0.1

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Downloaded from wp.org

**UPDATE**

I did roll back Timber and got the same behavior.

**Comment by connorjburton** [comment]
Don't you have to do `study.get_field('project_photos')` - can't remember off by heart but try that

**Comment by connorjburton** [comment]
Also in Timber `1.0.0` you don't have to manually set `set study = TimberPost`, we automatically look for posts in ACF repeater fields and return them as `TimberPost`

**Comment by cheestudio** [comment]
1) I tried:

`{% for image in study.get_field('project_images') %}`

And it causes a 500 Internal Server Error! Any other thoughts? I can't imagine this is a unique situation...

2) If I remove `{% set study = TimberPost(study) %}` then no fields are returned at all. So, maybe that was your intention, but it absolutely does not work if I don't include that.

**Comment by cheestudio** [comment]
One other update: when I do this:

`{{study.get_field('project_images')|print_r}}`

I do get the proper data:

`Array ( [0] => Array ( [image_upload] => 67 ) [1] => Array ( [image_upload] => 110 ) [2] => Array ( [image_upload] => 53 ) [3] => Array ( [image_upload] => 41 ) )`

But again, running this:

`{% for image in study.get_field('project_images') %}`

Just locks everything up...

**Comment by cheestudio** [comment]
Hate to be a pest, but any update on this? I've been beating my head against this all weekend. At this point, I'll have to just circumvent Timber entirely just to get this template working!  :(

**Comment by jarednova** [comment]
@cheestudio can you post the JSON file for the ACF custom field? I want to try and replicate your setup exactly to make sure we can understand what's occurring. Based on the error, I'm guessing it's some sort of infinite loop

**Comment by cheestudio** [comment]
Jared,

SO appreciate your time and help. New progress: I can get this code to output the markup:

`
        <div class="case-studies">
          {% for study in featured_case_studies %}
            {% set study = TimberPost(study) %}
              <div class="case-study-entry" id="study-0{{loop.index}}">
                <div class="study-title">
                  <span>Case Study</span>
                  <h4>{{study.title}}</h4>
                  <h3 class="location">{{study.location}}</h3>
                  <a href="" class="view-photos"><img src="{{site.theme.link}}/assets/img/view-photos.gif" alt=""></a>
                  <div id="" class="project-photos">
                    {% for photo in study.get_field('project_photos') %}
                      <a href="" rel="study-{{study.location|lower}}" class="fancybox"><img src="{{TimberImage(study.photo.project_image).src|resize(1200,9999,'center')}}" alt=""></a>
                    {% endfor %}
                  </div>
                </div>
                <div class="study-info">
                  <div class="challenge"><span class="study-header">Challenge:</span> {{study.challenge}}</div>
                  <div class="solution"><span class="study-header">Solution:</span> {{study.solution}}</div>
                  <div class="results"><span class="study-header">Results:</span> {{study.results}}</div>
                  <div class="contractor"><span class="study-header">Contractor:</span> {{study.contractor}}</div>
                </div>
              </div>
            {% endfor %}
          </div>`

And the page loads and the items are ouput with the proper markup (but the image source is clearly not going to work) and the image source is empty. If I change the image to this to get the actual url:

`<img src="{{TimberImage(photo.project_image).src|resize(1200,9999,'center')}}" alt="">`

...it locks up. 

Attached is the JSON file.

**Comment by cheestudio** [comment]
One more update: changing ACF to retrieve the URL rather than the ID works great, but running TimberImage on these fields is what is locking this whole process up. So to clarify, this works (having ACF return a URL):

`<a href="" rel="study-{{study.location}}" class="fancybox"><img src="{{photo.project_image}}" alt=""></a>`

But this locks the page up (regardless of what ACF is returning, which I normally set the image field to return an ID):

`<a href="" rel="study-{{study.location}}" class="fancybox"><img src="{{TimberImage(photo.project_image)|resize(1200,9999,'center')}}" alt=""></a>`

AND, as I wrote this, I realized the issue. Notice the width and height resize arguments I was passing. I confused TimberImage's resize with WP's default, where you normally pass 9999 as the "infinite height" attribute. TimberImage doesn't apparently need this, so I was just choking it, apparently, as it tried to resize all the images into some crazy height.

So....user error. Don't hate me!   :)

But, while you're here, Jared...notice @connorjburton comment above about not needing 

`{% set study = TimberPost(study) %}`

If I remove this, all my fields disappear. Would love some clarity around this...

**Comment by jarednova** [comment]
@cheestudio — the reason is that it's hard to predict what ACF will return in diff't situations. Sometimes it's a post id sometimes a `WP_Post` depends on how exactly you're retrieving it (`get_field` vs `post.my_field`, etc.). @connorjburton have put in a few "automagic" situations where it converts to a `Timber\Post` object, but only when it's sure.

All of this is a long way to say you can kill the study line by starting the for loop with this...

```twig
{% for study in Post(featured_case_studies) %}
```

**Comment by jarednova** [comment]
btw, glad you got it all worked out! I wasn't aware of the infinite height attribute in WP. For Timber you'd want to use this:

```twig
<img src="{{Image(photo.project_image).src|resize(1200, false,'center')}}" alt="">
```

... might be good to put in a catch for "9999" — I can imagine some others might hit that snag

**Comment by cheestudio** [comment]
Jared,

First off...you are THE MAN! 

And this syntax makes sense to me:

`{% for study in Post(featured_case_studies) %}`

I will use that here on out. For some reason my brain really wants to see "Post" as "post" (lowercase) but I can see how that would be really problematic.

Anyway, great to see how Timber is evolving. 

And I want to send you a beer! Do you have a way I can do that?  :)

**Comment by connorjburton** [comment]
Small note on that auto converter, if you set your repeater field to return a WP Post object it will convert it to a `Timber\Post` object, so it's easier than returning an id and having to manually do `Timber\Post(id)`

Glad it's solved and will close this issue now

**Comment by jarednova** [comment]
@cheestudio — best thing you can do is tweet about us — we're at [@TimberWP](https://twitter.com/timberwp). (But I suppose if you do find yourself in Boston, I'd take you up on that beer).

**Comment by cheestudio** [comment]
@connorjburton I don't show ACF has the option to change what the Repeater field itself returns. I do see that for the Relationship field, though. Is that what you meant?

**Comment by swthate** [comment]
So I was going absolutely batty for about two hours trying to get a repeater inside a relationship working. I visited this page and a number of others multiple times. Finally got something to work based on @cheestudio 's code above. Here's my "adaptation":

```twig
{% for areas in service_areas_list %}
{% set areas = TimberPost(areas) %}
    <h5>{{areas.title}}</h5>
    <ul class="list-of-service-area-towns">
    {% for towns in areas.get_field('service_area_towns') %}
        <li class="town">{{towns.service_area_town}}</li>
    {% endfor %}
    </ul>
{% endfor %}
```

Using this I finally got my repeater list to work inside my relationship!

However, you'll notice I do have `set areas = TimberPost(areas)`. I have ensured that my relationship field returns a Post Object and not an ID, but when I remove `TimberPost(areas)` the section disappears.

I understand you may need to see more context, but is there anything here I'm doing wrong? Thanks for all your help, guys!

**Comment by connorjburton** [comment]
Can you do `{{ dump(areas) }}` (before the set command) and post a gist of what that returns? Thanks

**Comment by swthate** [comment]
Here you are: https://gist.github.com/swthate/f4de9c5ad6dfc772362efbe9df22b054

Sorry, was distracted for a few days!

**Comment by cheestudio** [comment]
@swthate Are you sure you are running Timber 1.0? I only experienced what you experience on older versions of Timber. Once I upgraded, using set to initialize the TimberPost was not necessary as long as I was returning the Post Object.

**Comment by connorjburton** [comment]
Good point @cheestudio - it will most likely be your version is out of date. The auto converter was released in `1.0.0` I believe.

**Comment by swthate** [comment]
I'm using 1.0.3 😕

**Comment by connorjburton** [comment]
Can you make sure that on

functions.php line 1163

You have a function called `convert`. If so you can try do an `exit('hi')` on line 1171 and see if it's actually trying to convert the objects.

**Comment by swthate** [comment]
Hmm, which functions.php exactly?

I don't see anything like that in my theme's functions.php (it must not be that functions.php you're talking about, because I have nowhere near 1,000 lines hehe), I tried looking for a functions file in the plugin directory but found nothing, and I can't find a function convert() anywhere in the core functions.php file.

**Comment by connorjburton** [comment]
Sorry, have no idea why I wrote functions.php, was probably multi-tasking. I meant `vendor/timber/timber/lib/Post.php`

**Comment by swthate** [comment]
I did find a public function, but it wasn't on line 1163.

Starting on line 1105 I have this:

```php
/**
 * Finds any WP_Post objects and converts them to Timber\Posts
 * @param array $data
 */
public function convert( $data, $class ) {
	if ( is_array($data) ) {
		$func = __FUNCTION__;
		foreach ( $data as &$ele ) {
			if ( gettype($ele) === 'array' ) {
				$ele = $this->$func($ele, $class);
			} else {
				if ( $ele instanceof WP_Post ) {
					$ele = new $class($ele);
				}
			}
		}
	}

	return $data;
}
```

I'm not sure where to put `exit('hi')` here.

**Comment by connorjburton** [comment]
Put it here

```php
if ( $ele instanceof WP_Post ) {
    exit('hi');
    $ele = new $class($ele);
}
```
