### ISSUE TITLE
Incorrectly ignoring lib/Timber.php in gitignore

### ISSUE THREAD

**Issue by njbarrett** [timber/timber#994]
### Expected behavior
Timber.php is in the /lib folder when cloning the repo.

### Actual behavior
Timber.php is not in the /lib folder when cloning the repo.

### Steps to reproduce behavior
Clone the repo, /lib/Timber.php is missing if you are commiting vendor packages to your own repo

### What version of WordPress, PHP and Timber are you using?
Not relevant

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

I am guessing this is due to this commit https://github.com/timber/timber/commit/74fdc55cb7e91d276520b0f7510e5aaaa5ba97c1

Where all files called timber.php are being ignored. The correct line in gitignore should be `/timber.php` so that the `/lib/Timber.php` file is not ignored

**Comment by jarednova** [comment]
thanks @njbarrett — I was trying to just target the one at the top level. I tried replicating the issue and both when cloning the repo directly (`git clone git@github.com:timber/timber.git`) and by loading through composer I see the file located in `lib/Timber.php`:

![screen shot 2016-05-12 at 8 47 20 am](https://cloud.githubusercontent.com/assets/1298086/15215020/567b62d0-181e-11e6-8beb-59ff9b667c91.png)

In composer I am requiring `"timber/timber" : "1.*"` — is your setup doing something diff't? I'm running Composer 1.0.3

**Comment by jarednova** [comment]
.... all that said @njbarrett: a52cd47 should solve this by targeting Timber.php only at the root level

**Comment by jarednova** [comment]
... one more: I created #995 for the PR. Once the tests pass, I'll merge in

**Comment by njbarrett** [comment]
Thanks, I believe that will fix it.
Sorry for the confusion, the issue is because we are commiting vendor to our repository and so when our repo is cloned the lib/Timber.php file was missing because of the gitignore. However I think your change will resolve the issue now.
