### ISSUE TITLE
PHP Fatal error:  Class 'Timber\\Integrations\\ACF' not found 

### ISSUE THREAD

**Issue by JoaoSaleiro** [timber/timber#996]
Hello,

today I have updated Timber to the most recent version in a Wordpress site with ACF and WPML. 
First, I updated it on my local installation and checked it was working fine.
Then I uploaded it to the server, which has exactly the same files as I have locally, and I got the following error on the server:

PHP Fatal error:  Class 'Timber\\Integrations\\ACF' not found in /var/www/vhosts/[myhost]/website/wp-content/plugins/timber-library/lib/Integrations.php on line 25

I don't have a clue on why this doesn't work with the online installation, but works with the local one. Reverting to the previous version ( 0.22.5 ) fixes the issue. Disabling ACF also fixes the issue (but that's not an option...)

Locally, my PHP is 5.6.11. Server has 5.4.45. 

Do you have any clue that can help figuring out what's happening? Is this a bug on the most recent version with ACF and WPML ?

Thanks!

**Comment by jarednova** [comment]
@JoaoSaleiro this is quite weird. How did you install the plugin on your server? If you moved anything to directly replace 0.22.5 with 1.0 in composer, composer needs to regenerate its autoload file. That's the only thing I can think of here

**Comment by JoaoSaleiro** [comment]
Hello @jarednova . 
Locally, I have updated the plugin via the auto-update of wp-admin. After testing, I have uploaded my local installation to the server via FTP. On the server I get the "PHP Fatal error".

I am not expert with Wordpress, and the first time I heard of Composer was today. :) What should I do to debug why this error happens on the server, but not locally ?

**Comment by joshrickert** [comment]
I just did the same. Production site fails after updating the plugin locally. I get:
`Class 'Timber\Timber' not found in [wp path]/wp-content/plugins/timber-library/init.php on line 5`

**Comment by JoaoSaleiro** [comment]
Hey @jarednova . What can I do to track this issue down and fix it? Thanks!

**Comment by jarednova** [comment]
@JoaoSaleiro — can you email me at jared@upstatement.com. I have some questions I want to ask directly....

**Comment by JoaoSaleiro** [comment]
@jarednova - any news on this topic? I sent you an email two days ago with more info about this issue.
Thanks!

**Comment by JoaoSaleiro** [comment]
Hello,

instead of uploading the local installation of Timber to the server via FTP, I've used the wp-admin update procedure, and Timber is now working on v1.0.3 . So, this issue only happens if the Timber is uploaded from a working local installation to the production server via FTP.

**Comment by jarednova** [comment]
Hi Joao — I have a good hunch based on #542: basically there are some directories renamed from (for example) `cache` to `Cache`. Whereas your local is probably case insensitive (default on OSX) your production server probably _is_ case sensitive. Give that a look and see if you notice any diffs (look in the `lib` directory)

**Comment by connorjburton** [comment]
Any updates on this @JoaoSaleiro

**Comment by andrzejpiotrowski** [comment]
@jarednova solution fixed issue. Git lost the directory name change leaving it all lowercase.

**Comment by kylehotchkiss** [comment]
If you still get this issue, I want to expand on @jarednova's earlier response about caps - all three directories need to be capitalized in `/lib`.
